### ISSUE TITLE
Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11081] opened 2019-10-07 23:36 UTC
```
2019-10-07T17:01:04.962Z E Cannot read property 'children' of undefined
TypeError: Cannot read property 'children' of undefined
    at e.value (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:86:1077286)
    at e.value (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:86:1075685)
    at t.value (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:40:818586)
    at t.value (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:40:819127)
    at Ws (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:94989)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at Hs (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:90891)
    at Ms (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:79559)
    at vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41813
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at _o (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41758)
    at go (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41693)
    at Is (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:78550)
    at Object.enqueueForceUpdate (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:46823)
2019-10-07T17:01:04.964Z E Cannot read property 'children' of undefined
TypeError: Cannot read property 'children' of undefined
    at e.value (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:86:1077286)
    at e.value (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:86:1075685)
    at t.value (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:40:818586)
    at t.value (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:40:819127)
    at Ws (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:94989)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at Hs (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:90891)
    at Ms (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:79559)
    at vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41813
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:67:3884)
    at po (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41541)
    at _o (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41758)
    at go (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:41693)
    at Is (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:78550)
    at Object.enqueueForceUpdate (vector://vector/webapp/bundles/a6f8076a857e57b3741a/bundle.js:59:46823)
2019-10-07T17:01:04.964Z E The above error occured while React was rendering the following components: 
    in t
    in t
    in main
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat
```

**Comment by jryans** [comment] 2019-10-08 11:24
I believe this is a duplicate of https://github.com/vector-im/riot-web/issues/10997.

**Closed by jryans** 2019-10-08 11:24 UTC
Labels: bug, defect, p1, rageshake, react-soft-crash, 🔥 Fire 🔥
