### ISSUE TITLE
Option to disable "message as seen" by participants

### ISSUE THREAD

**Issue by tiotrom** [vector-im/riot-web#8959] opened 2019-02-26 20:49 UTC
So I now realized that people can see if I read their messages even when I disabled the "read receipt" in settings. I feel betrayed. I used Riot for 2 years and I thought this "feature" is off for me for all chats and rooms. What is the point of disabling this for you to not see!? I thought I am disabling it so that no one sees if I see their messages. I feel like I discovered that my house walls were made out of glass for the past 2 years :D - not that this is a huge deal, but it really is uncomfortable and in my view it is not a good design strategy - privacy should be enabled by default and if you want you can opt in for such things.

Is this a bug or a feature though?

I love Riot don't get me wrong, but this feature/bug...

**Comment by turt2live** [comment] 2019-02-26 21:05
I hate to be the bearer of bad news, but this is technically a feature at the moment. https://github.com/vector-im/riot-web/issues/2527 tracks being able to stop the sending of read receipts ("I've seen this" bubbles), and the option you're seeing in the settings is to just turn off the visibility of read receipts for your view only. 

Adding this feature is a bit complex as many parts of the protocol actually rely on read receipts. We would love to add this option though, it just needs some work first: https://github.com/vector-im/riot-meta/issues/66

It's good to hear that your experience of Riot has been fairly good so far (if we ignore this privacy issue you've unfortunately ran into) - please do let us know how else we can improve! For the time being though, I have to close this as a duplicate of https://github.com/vector-im/riot-web/issues/2527

**Closed by turt2live** 2019-02-26 21:05 UTC
Labels: redesign

**Comment by tiotrom** [comment] 2019-02-26 22:12
I understand, ok. I was really surprised though and maybe you should make this option more straight-forward. If I disable the "show typing" - like when I type to not show this, I expect that others will not see when I type, not the other way around like it will hide when others type. Same with "read receipts" I expect for others to not be able to see if I read their messages. Maybe at least, until you implement this feature, say something like "Hide read receipts for me (this will not affect the visibility for other users)". Honestly I love Riot and I am making custom Linux distributions and I include Riot in the builds, and yet I was completely fooled by this option for 2 years thinking that I made myself invisible by opting out of "read receipts". I expect Riot to be very privacy oriented and not even enable such options as default, but let the user enable if they want for others to see his/her activity (like reading messages or typing) - or, when one installs Riot for the first time to be welcomed with a tiny popup asking if he/she wants to enable/disable these visibility/privacy options.

I, for one, making open source projects and managing teams, do not want that from the get-go my online presence on Riot to be always subject to discover-ability. I would rather like to opt-in to such "visibility" options.

Maybe you should add a "visibility" tab under user settings with such options.

Thank you for this great piece of software and I love the new layout!

**Comment by turt2live** [comment] 2019-02-26 22:24
Privacy is very important, I've opened https://github.com/vector-im/riot-web/issues/8961 to explore a more privacy-centric approach to how we do things (even though we do already take privacy very seriously, although not all the way to the extreme of disabling a bunch of features). 

Renaming the option has been suggested before, and to be honest I also agree - I'll get that PR in the pipeline.

**Comment by dcunited001** [comment] 2023-03-16 07:15
> I feel like I discovered that my house walls were made out of glass for the past 2 years :D - not that this is a huge deal, but it really is uncomfortable and in my view it is not a good design strategy - privacy should be enabled by default and if you want you can opt in for such things.

surprise!
