### ISSUE TITLE
We show QR codes when the other device says they don't support it

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12151] opened 2020-01-30 14:32 UTC

**Comment by turt2live** [comment] 2020-02-05 14:19
Blocking this on a decision about the future of QR codes. cc @jryans

**Comment by turt2live** [comment] 2020-02-06 13:54
removing this from workflow board pending requirements

**Comment by bwindels** [comment] 2020-02-18 11:27
Duplicate of https://github.com/vector-im/riot-web/issues/12368

**Closed by bwindels** 2020-02-18 11:27 UTC
Labels: bug, cross-signing-sprint, defect, phase:3, story:2
