### ISSUE TITLE
search doesn't show display names

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#13267] opened 2020-04-18 20:57 UTC
### Description

It just shows the mxid instead. Doesn't matter if e2ee or plain text:

![image](https://user-images.githubusercontent.com/1029578/79670896-72ef1400-81c6-11ea-929b-9f2a7a08ac0e.png)
![image](https://user-images.githubusercontent.com/1029578/79671092-f2311780-81c7-11ea-9a99-88bf99fd758b.png)

### Steps to reproduce

- search in a room
- look at the names of the users

It shows the mxid; I'd expect it to show the proper display name.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 2020041801 (nightly)

**Comment by t3chguy** [comment] 2020-04-18 21:02
Duplicate of https://github.com/vector-im/riot-web/issues/560

**Closed by t3chguy** 2020-04-18 21:02 UTC
Labels: bug
