### ISSUE TITLE
Can react twice with the same emoji

### ISSUE THREAD

**Issue by tredondo** [vector-im/riot-web#13586] opened 2020-05-07 18:22 UTC
You can react to the same message with the same reaction twice: once by choosing the emoji from the picker, and once from the Quick Reactions. But if you hover over them, they show the same code.

![image](https://user-images.githubusercontent.com/10043369/81330410-e3b27f00-9054-11ea-871d-513da0675963.png)

Riot 1.6 web.

**Comment by turt2live** [comment] 2020-05-07 19:51
Duplicate of https://github.com/vector-im/riot-web/issues/11161

**Comment by t3chguy** [comment] 2020-05-07 20:03
This is not the same. That issue is duplicated counts within a key, this is unprintable unicode chars not being filtered out so they key differently.

**Comment by dud1337** [comment] 2020-06-04 08:35
Not all quick reactions have this bug.

Buggy:
* `:thumbsup:`
* `:thumbsdown:`

Safe:
* `:happy:`
* `:tada:`
* `:confused:`
* `:heart:`
* `:rocket:`
* `:eyes:`

![pic](https://user-images.githubusercontent.com/5631021/83734227-fff30d00-a64e-11ea-8674-7e27faa8f291.png)
A quick way to test UI-wise is by selecting, say, `:happy:` from quick-reactions, then searching for it in the main selector, and seeing it already selected. (Light blue underline in image above)

Then repeat the process for `:thumbsup:`. One will see it is not selected in the selector. (Pink underline in image above)

**Comment by t3chguy** [comment] 2020-06-04 21:15
This is now fixed on develop by https://github.com/matrix-org/matrix-react-sdk/pull/4707 for outbound reactions. If you click on an existing reaction which has some invisible unicode then riot will match that invisible unicode and thus you could end up with loads of mismatched thumbs up.

**Closed by t3chguy** 2020-06-04 21:15 UTC
Labels: bug, feature:reactions
