### ISSUE TITLE
Message Editing: Handle error codes when sending

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9772] opened 2019-05-20 11:32 UTC
After chatting with @nadonomy about reactions / edits errors in general, we came up with:

* Use same e2e (!) icon to decorate messages with an error
  * Clicking on it reveals a context menu with any of:
    * Resend reactions
    * Resend edit
    * Encryption information
* Users will see the message status bar explaining the error (network, rate limited, unverified, etc.)
* Irrespective of what colours e2e uses (as its subject to change), unsent edit/reactions should always decorate red

**Comment by manuroe** [comment] 2019-06-19 10:49
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/196)

**Comment by manuroe** [comment] 2019-06-19 10:49
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2511)

**Comment by bwindels** [comment] 2019-06-27 08:53
Dupe of https://github.com/vector-im/riot-web/issues/9692

**Closed by bwindels** 2019-06-27 08:53 UTC
Labels: feature, feature:aggregations, feature:message-editing, phase:2
