### ISSUE TITLE
p2p video call window resize needed

### ISSUE THREAD

**Issue by grinapo** [vector-im/riot-web#13360] opened 2020-04-24 09:44 UTC
### Description

When doing one-to-one video calls the video area (which contains both my and the other party's image) is forced full width within the middle pane. Since its aspect ratio is fixed on a wide display it basically overlaps all the chat, making it impossible to see chat, especially if it contains image attachments.

![2020-04-24_11-32-15_screenshot](https://user-images.githubusercontent.com/1056054/80198175-fc1ba600-861f-11ea-9cbb-21d4dc55fd95.png)

Even forcing out the video (into pincture-in-picture) don't help since the original video area stays the same but black.

It would be extremely useful **to be able to resize the video area independently of the pane geometry**.

### Version information
- **Platform**: chromium web browser, v80.0.3987 (dev), Debian/sid 64bit

- **URL**: private server, riot-web version: 1.6.0-rc.3

**Comment by aaronraimist** [comment] 2020-04-24 23:02
Basically a duplicate of https://github.com/vector-im/riot-web/issues/2268

**Closed** 2020-04-24 23:06 UTC
Labels: bug, ui/ux
