### ISSUE TITLE
[Feature Request] Busy/DND/Do Not Disturb capabilities

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#9239] opened 2019-03-21 18:26 UTC
Any chance we can get Busy/DND/Do Not Disturb functionality baked into Riot? And then maybe have that hook into external systems that could toggle/trigger it?

Per conv/chat room doesn't work for every scenario, a global setting would be nice.

**Comment by turt2live** [comment] 2019-03-21 18:28
Duplicate of https://github.com/vector-im/riot-web/issues/1672

See also https://github.com/vector-im/riot-web/issues/3569, https://github.com/vector-im/riot-web/issues/7758

**Closed by turt2live** 2019-03-21 18:28 UTC
Labels: suggestion

**Comment by BloodyIron** [comment] 2019-03-22 14:47
oops, sorry
