### ISSUE TITLE
VoIP settings have lost their width override so wrap illegibly

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6243] opened 2018-02-23 23:33 UTC
<img width="330" alt="screen shot 2018-02-23 at 23 32 00" src="https://user-images.githubusercontent.com/1294269/36621807-e9a1c1d2-18f1-11e8-96ad-7c87da34ab11.png">

**Comment by turt2live** [comment] 2018-02-23 23:42
Duplicate of https://github.com/vector-im/riot-web/issues/4815

**Closed** 2018-02-24 00:18 UTC
Labels: bug, cosmetic, p1, regression
