### ISSUE TITLE
Please add a way to ingore or hide room invitations.

### ISSUE THREAD

**Issue by starcraft66** [vector-im/riot-web#10535] opened 2019-08-12 00:50 UTC
### Description

There is currently no way to ignore or hide room invitations in Riot. I was invited to a room that has a bot that constantly re-invites me to the room as soon as I decline the invitation. This causes my Riot client to always have an annoying persistent notification badge for the invitation.

### Steps to reproduce

- Get invited to `!HkIVpVBRHoIryLnGUn:chat.thisisjoes.site`
- Decline the invitation

I get re-invited by the bot and there is no way to hide the invite.

Logs being sent: no

### Version information

- **Platform**: Electron client on Ubuntu.

- **OS**: Ubuntu 19.04
- **Version**: 1.3.2

### Screenshot

![invite](https://user-images.githubusercontent.com/1858154/62841748-a82b8580-bc79-11e9-8002-bcfdff81d2a4.png)

**Comment by IronmanDiesForeverAtCloseOfEndgame** [comment] 2019-08-12 00:56
hahahahaha btfo

**Comment by rbreslow** [comment] 2019-08-12 00:57
I'm also experiencing this issue on macOS Mojave. 

![image](https://user-images.githubusercontent.com/1774125/62841848-9d252500-bc7a-11e9-8f99-88a757d66970.png)

**Comment by jellykells** [comment] 2019-08-12 00:59
I believe there are multiple ways to ignore invites already. You can mark the room as low priority, or block the account sending the invite.

**Comment by starcraft66** [comment] 2019-08-12 00:59
@jellykells I don't want to mark the room as low priority, I want nothing to do with this room. I will try ignoring the bot thanks.

**Comment by G2G2G2G** [comment] 2019-08-12 01:00
shutup tristan

**Comment by IronmanDiesForeverAtCloseOfEndgame** [comment] 2019-08-12 01:02
I joined the room and i was given a party upon arrival, you should try it tristan

**Comment by BurnyBoi** [comment] 2019-08-12 01:23
I found a workaround for your issue. All you need to do is JOIN THE GLOWERS CLUB

**Comment by turt2live** [comment] 2019-08-12 02:09
Duplicate of https://github.com/vector-im/riot-web/issues/2341

**Closed by turt2live** 2019-08-12 02:09 UTC
Labels: bug, ui/ux

**Comment by linuxmail** [comment] 2019-09-23 20:38
Have the exact same Room that tries to invite me ... the Glowers club :-/  I think, only IP block helps
