### ISSUE TITLE
Timeline corruption on develop - "Live timeline 0 is no longer live"

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8593] opened 2019-02-13 18:00 UTC
I've seen this ~3 times today, and Travis is getting bitten by it repeatedly.

Symptoms are stacktrace of:

```
Caught /sync error Error: live timeline 0 is no longer live - it has a neighbouring timeline
    at Room../matrix-js-sdk/lib/models/room.js.Room.addLiveEvents (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:28527:19)
    at SyncApi../matrix-js-sdk/lib/sync.js.SyncApi._processRoomEvents (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:35245:10)
    at _callee9$ (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:34809:54)
    at tryCatch (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:49866:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:50100:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:49918:21)
From previous event:
    at https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:34858:46
From previous event:
    at SyncApi._callee10$ (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:34657:74)
    at tryCatch (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:49866:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:50100:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:49918:21)
From previous event:
    at SyncApi._processSyncResponse (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:34946:22)
    at SyncApi._callee7$ (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:34294:60)
    at tryCatch (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:49866:40)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:50100:22)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/c0b74508d5644578d135/bundle.js:49918:21)
consoleObj.(anonymous function) @ rageshake.js:61
16:44:19.277 rageshake.js:61 
```

And a message you try to send gets stuck in localecho state at the bottom of the timeline (in practice it successfully sends).

**Comment by ara4n** [comment] 2019-02-13 18:00
@turt2live can you rageshake?

**Comment by ara4n** [comment] 2019-02-13 18:01
https://github.com/matrix-org/riot-web-rageshakes/issues/1217

**Comment by turt2live** [comment] 2019-02-13 18:07
Past related issues (not as common as whatever happened in the last 24h):
* https://github.com/vector-im/riot-web/issues/8084
* https://github.com/vector-im/riot-web/issues/7507

**Comment by lampholder** [comment] 2019-02-14 15:31
We're declaring this not a release blocker since we have seen very limit incidence of it. One to keep an eye on, though.

**Comment by turt2live** [comment] 2019-02-25 00:14
Latest symptom from https://github.com/matrix-org/riot-web-rageshakes/issues/1238 is #riot-dev was only showing ~50% of the messages received over /sync, which lead to me thinking I was replying to someone that already had an answer :(

**Comment by ara4n** [comment] 2019-03-21 11:46
@richvdh observes:

> yeah :/. I suspect it's in code I wrote
> and happens when there's a fork in the DAG or something

**Comment by lampholder** [comment] 2019-03-21 17:19
Rageshake and reload button?

**Comment by aaronraimist** [comment] 2019-03-22 00:02
Just sent a rageshake on this. I assume I was getting the same issue. 

From the rageshake notes: Visible symptoms were that there were lots of old messages below the latest message in the room. Clicking the scroll to the bottom button actually scrolled you up because the latest message in the room was not at the bottom of the page but somewhere in the middle.

**Comment by turt2live** [comment] 2019-03-22 00:05
That's consistent with the other known (but for some reason not documented) symptom. I assume it felt a bit like a rotating drum rather than a timeline?

**Comment by aaronraimist** [comment] 2019-03-22 00:07
Yes something like that. Now after I sent the rageshake the entire app has become unresponsive. I can't click on anything, the green read receipt bar doesn't update, and animations for other users read receipts is frozen. Do you want another rageshake?

**Comment by turt2live** [comment] 2019-03-22 00:08
I suspect that symptom is a different issue for sure (one of the "the app sets fire to my computer trying to start up" issues), and a rageshake might not reveal it. Would suggest opening a new issue and rageshaking on that just in case though.

**Comment by lampholder** [comment] 2019-03-22 16:21
To add more detail to my very brief comment above - "Rageshake and reload button?" means "Can we mitigate this difficult-to-reproduce/investigate bug by catching the error and prompting the user to 'Rageshake and reload'.

_Obviously_ this is horrible, but better than leaving users to discover the app is broken by its just being super broken and does at least present a way out.

**Comment by turt2live** [comment] 2019-03-23 02:25
ftr, tracking the workaround dialog as https://github.com/vector-im/riot-web/issues/9260 to avoid closing this by accident.

**Comment by turt2live** [comment] 2019-03-25 18:10
ftr we de-fired this pending more information from https://github.com/vector-im/riot-web/issues/9260. If people encounter this, ***please*** rageshake.

**Comment by turt2live** [comment] 2019-03-28 20:13
so at least one case of this is possibly having a server come back to life after being down for a long time. https://github.com/matrix-org/riot-web-rageshakes/issues/1333 shows that at around 18:58:18 a server started processing ~100 bot commands, which Riot was trying to add to the timeline fairly quickly. It looks like the event timestamps are in the past, so possibly that messed up the backfilling? Shortly after the block of events gets processed, the timeline explodes.

The function which is doing the logging there sets neighbouring timelines, which is definitely a good indicator of being a source of problems for when it later explodes due to having such a neighbour. 

https://github.com/matrix-org/riot-web-rageshakes/issues/1334 just shows that the rageshake in 1333 is still a problem after refreshing - nothing of interest.

https://github.com/matrix-org/riot-web-rageshakes/issues/1335 happens some time after debugging it - the interesting part is a "cannot reset neighbour" error followed by a timeline is no longer live problem later on.

I've mirrored the bundle.js causing issues to https://t2l.io/_matrix/media/v1/download/t2l.io/2991333c56d72a5d217b3c07d722ba985844a616 so that the line numbers line up.

**Comment by turt2live** [comment] 2019-04-01 17:10
a bunch of timelines blew up all at once it seems... here's some rageshake analysis:

* https://github.com/matrix-org/riot-web-rageshakes/issues/1341 appears to have tried to join `9:33` to `8:36` (refused: live timeline), then moments later `8:36` to `9:33` (accepted), then `9:33` to `8:36` again (refused: live timeline). This then exploded when trying to add live events to the timeline, and an error immediately after where the explosion was caught.
* https://github.com/matrix-org/riot-web-rageshakes/issues/1342 looks to have happened after 1341, and probably just fallout on the previous explosion
* https://github.com/matrix-org/riot-web-rageshakes/issues/1343 happened within a few minutes of 1341, and is for the same room and event ID. Similar to 1341, it tries to join `7:04` to `9:37` (accepted), then `9:37` to `7:04` (refused: live timeline). The timeline explosion happened about 200ms before this happened, however. It then continued to explode.
* https://github.com/matrix-org/riot-web-rageshakes/issues/1344 happened within a minute of 1343, and has the same behaviour: `8:11` to `9:38` (accepted) and then `9:38` to `8:11` (refused: live timeline). The explosion happened after the double splicing, unlike 1343.
* https://github.com/matrix-org/riot-web-rageshakes/issues/1345 is an anomaly, but happened within about 5 minutes of 1344. This is the only one of the batch with a different room ID being affected. Similar to the other rageshakes, it tries to join `9:42` to `9:15` then `9:15` to `9:42`. The build is custom and older, so it did not pick up on the logging added in https://github.com/matrix-org/matrix-js-sdk/pull/873

Something feels a bit wrong if we're doubly linking timelines, but failing to do so effectively. It appears as though we're creating a split brain with https://github.com/matrix-org/matrix-js-sdk/pull/873 being a thing, but it's a bit hard to tell. It's clear that we're getting into a wrong state though: we should never be trying to set a previous timeline as a neighbour, but somehow we are anyways and that causes an explosion.

For refs:

Where all the rageshakes are refusing to splice:
https://github.com/matrix-org/matrix-js-sdk/blob/cd3c6809a94f6f346b6ba9760eb86df00136da03/src/models/event-timeline-set.js#L418-L421

Where the timelines are blowing up:
https://github.com/matrix-org/matrix-js-sdk/blob/cd3c6809a94f6f346b6ba9760eb86df00136da03/src/models/event-timeline.js#L278-L279

**Comment by turt2live** [comment] 2019-04-01 17:57
https://github.com/matrix-org/riot-web-rageshakes/issues/1352 broke differently: it blew up on https://github.com/matrix-org/matrix-js-sdk/blob/61aea05af0b45452ea8d4727a6f9138770559761/src/models/room.js#L1294-L1297

**Comment by ara4n** [comment] 2019-04-01 18:00
Perhaps the idea of half-linking the double-linked timeline was wrong then - we should either doublelink it or not at all.

**Comment by turt2live** [comment] 2019-04-01 22:46
https://github.com/matrix-org/riot-web-rageshakes/issues/1354 is our first non-develop, non-custom instance of this. It's a desktop build for 1.0.6, which means it also missed https://github.com/matrix-org/matrix-js-sdk/pull/873

----

> Perhaps the idea of half-linking the double-linked timeline was wrong then - we should either doublelink it or not at all.

I'll open a PR for doing this.

**Comment by turt2live** [comment] 2019-04-02 16:49
https://github.com/matrix-org/riot-web-rageshakes/issues/1356, https://github.com/matrix-org/riot-web-rageshakes/issues/1357, and https://github.com/matrix-org/riot-web-rageshakes/issues/1360 all look similar in that they try to do splicing and then fall over. They're also a mix of develop and release, and good indicators that this is happening *a lot* more often than originally thought.

**Comment by turt2live** [comment] 2019-04-03 16:34
Daily rageshake review for explosions:
* https://github.com/matrix-org/riot-web-rageshakes/issues/1361 appears to have fallen over for no explicable reason - there is a single splice going on, but that shouldn't cause it to explode. The timelines are very close together though (4 seconds apart) and right on startup. log-0001 shows that they were previously experiencing the problem and probably decided to rageshake when it happened again on startup. 0001 shows some errors connecting to the homeserver, and some rapid splicing (timelines within seconds of each other).
* https://github.com/matrix-org/riot-web-rageshakes/issues/1364 looks interesting in that there is an explicit "Already have event $redacted in limited sync - not resetting" line, followed by an immediate explosion. Previous logs do not show explosions. This may be a 3rd cause of the error.
* https://github.com/matrix-org/riot-web-rageshakes/issues/1370 looks like the classic "tried to splice and it fell over" behaviour previously described in the comments here.
* https://github.com/matrix-org/riot-web-rageshakes/issues/1369 is weird because the timeline being spliced is handled as an invite by the room list (indicated by it running off the end of the list). Possible storage corruption?
* https://github.com/matrix-org/riot-web-rageshakes/issues/1368 is another "rapidly tried to splice and blew up" scenario.
* https://github.com/matrix-org/riot-web-rageshakes/issues/1367 broke in a different way, but appears strongly related to 1368's crash event. This time the timeline has a pagination token, and using desktop. Assuming they aren't building develop, this is a 4th cause.
* https://github.com/matrix-org/riot-web-rageshakes/issues/1365 looks to have failed due to cause no. 2 (cannot reset due to neighbour, followed by explosion). This is on develop, and may be a half-linked timeline as https://github.com/matrix-org/matrix-js-sdk/pull/877 wasn't landed at the time.

Overall the four potential causes (in terms of what the logs say) are:
1. Something to do with splicing the live timeline into a position where it cannot operate (what https://github.com/matrix-org/matrix-js-sdk/pull/877 and prior try to solve)
2. Probable side effects of https://github.com/matrix-org/matrix-js-sdk/pull/873 causing "cannot reset timeline - it has a neighbouring timeline" when handling a limited sync.
3. New to this batch - possible rapid splicing causing problems.
4. Also new to this batch - having pagination tokens on timelines, which may be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/877

**Comment by turt2live** [comment] 2019-04-03 20:07
A few more came in:

https://github.com/matrix-org/riot-web-rageshakes/issues/1371, https://github.com/matrix-org/riot-web-rageshakes/issues/1372, and https://github.com/matrix-org/riot-web-rageshakes/issues/1373 all look like a case of number 3. Timelines are being spliced when they are only a few seconds old.

**Comment by turt2live** [comment] 2019-04-04 16:36
Another day, another batch of rageshakes. This is the last batch of rageshakes from /app I'll take a look at until we publish a release with some of the fixes - we have more than enough data points.

* https://github.com/matrix-org/riot-web-rageshakes/issues/1374 appears to be case 1, although the timelines it is splicing are less than 30ms apart.
* https://github.com/matrix-org/riot-web-rageshakes/issues/1375 also looks like a classic case 1 failure.
* https://github.com/matrix-org/riot-web-rageshakes/issues/1376 is a case 1 failure
* https://github.com/matrix-org/riot-web-rageshakes/issues/1377 looks like case 3
* https://github.com/matrix-org/riot-web-rageshakes/issues/1379 is on develop, but the logs do not show the problem or the error happening. 
* https://github.com/matrix-org/riot-web-rageshakes/issues/1380 is another classic case 1
* https://github.com/matrix-org/riot-web-rageshakes/issues/1381 blew up for no explicable reason, probably case 1
* https://github.com/matrix-org/riot-web-rageshakes/issues/1382 is another case 1

**Comment by turt2live** [comment] 2019-04-05 17:38
https://github.com/matrix-org/riot-web-rageshakes/issues/1389 is an explosion on develop which appears to be complaining about pagination tokens. In theory, https://github.com/matrix-org/matrix-js-sdk/pull/885 fixes this. 

For context, the error is thrown here:
https://github.com/matrix-org/matrix-js-sdk/blob/b1b49413d0e8c0766bc9fd51ad9acd6da83a41d3/src/models/room.js#L1294-L1297

**Comment by turt2live** [comment] 2019-04-09 20:27
Only one rageshake with the new patches post-release so far: https://github.com/matrix-org/riot-web-rageshakes/issues/1403

Looks like the first error happened in 0004, and the user finally got frustrated enough to send a bug report. Looks to be a case of splicing timelines which are very close to each other, which may be an indicator of a race somewhere:
```
Already have timeline for $redacted - joining timeline !redacted:2019-03-16T15:11:47.610Z to !redacted:2019-03-16T15:11:47.116Z
```

That's a 500ms difference between timelines.

**Comment by turt2live** [comment] 2019-04-15 16:37
There hasn't been much activity in terms of rageshakes for this (even after we brought the rageshake server back online) - we are planning to presume this fixed without complaints saying otherwise.

**Comment by turt2live** [comment] 2019-04-17 15:40
@Half-Shot your client is missing all of the patches which are supposed to fix this

**Comment by Half-Shot** [comment] 2019-04-17 23:34
Ahhhhhh kk

**Comment by turt2live** [comment] 2019-05-01 19:40
There haven't been any complaints and no further rageshakes for a long while, which means I'm confident enough to say this is fixed. If the issue persists for people, please open a new issue.

Leaving this open to track the removal of the prompt: https://github.com/matrix-org/matrix-react-sdk/pull/2939

**Closed** 2019-05-02 15:46 UTC
Labels: bug, critical, p1
