### ISSUE TITLE
Too difficult to open user profile from a long stream of images, for the purpose of ignore

### ISSUE THREAD

**Issue by eras** [vector-im/riot-web#10971] opened 2019-09-27 07:39 UTC
### Description

When a person is spamming channel with pictures, it is too difficult to open the profile of that person for the purpose of ie. ignoring the user. The user info is clickable only in the first message of many, and scrolling upwards only loads older messages moving the user profile up until someone else has cut the stream or the spamming started.

### Steps to reproduce

- Arrange a user to send a sequence of images to a channel
- Try to select that user's profile without scrolling up, potentially a lot, downloading and viewing all the uploaded images in the process
- Find out you need to find the very first message of the user, or alternatively the first message after someone else has said something, to be able to do so
- The per-message menu does not have this option either

Describe how what happens differs from what you expected.

- I would expect there to be a way to open the user profile from either the left side of the message (the profile button could hover on the top of the screen if the message goes further beyond)
- Alternatively I would expect the per-message menu to have a way to select the user profile; or possibly directly ignore the user

Logs being sent: no

Picture from Matrix HQ today:

![image](https://user-images.githubusercontent.com/1159374/65750948-31a3f380-e112-11e9-9e35-bb65b0eb4025.png)

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?

Firefox 68.0.2

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?

Ubuntu 18.04.3 LTS

- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

riot.im/staging

**Comment by turt2live** [comment] 2019-09-27 13:45
Duplicate of https://github.com/vector-im/riot-web/issues/10829

**Closed by turt2live** 2019-09-27 13:45 UTC
Labels: bug, ui/ux
