### ISSUE TITLE
Failed reaction events show 'message not sent' error

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#9755] opened 2019-05-17 17:31 UTC
I was spamming thumbs on a message and then it popped up, I guess it shouldn't do that

**Comment by jryans** [comment] 2019-05-20 08:43
We haven't really defined how error handling should work for reactions, so maybe we can use this as chance to do so.

**Comment by jryans** [comment] 2019-05-20 08:45
@nadonomy / @lampholder, should reactions show error messages in the same ways as messages do, or should something else happen?

**Comment by nadonomy** [comment] 2019-05-20 08:47
> @nadonomy / @lampholder, should reactions show error messages in the same ways as messages do, or should something else happen?

Great question. Will message you on Riot to ensure we have a shared understanding of what happens with messages today to figure it out from there.

**Comment by jryans** [comment] 2019-05-20 11:35
Let's consider this a duplicate of https://github.com/vector-im/riot-web/issues/9692, where we plan to do something about reaction errors generally.

**Closed by jryans** 2019-05-20 11:35 UTC
Labels: bug, feature:aggregations, feature:reactions
