### ISSUE TITLE
Stuck in 'failed to join room' modal forever

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8131] opened 2019-01-15 16:54 UTC
OK button doesn't work, close button keeps on flashing (related to client repeatedly trying to join the room in the background?), had to navigate back to riot.im/experimental to exit. Unexciting screencap incoming.

**Comment by turt2live** [comment] 2019-01-15 16:55
Duplicate of https://github.com/vector-im/riot-web/issues/8100

**Closed by turt2live** 2019-01-15 16:55 UTC
