### ISSUE TITLE
When the left panel is collapsed, there is no indicition that there's unread messages in a room

### ISSUE THREAD

**Issue by Standard8** [vector-im/riot-web#11990] opened 2020-01-22 11:42 UTC
### Description

On the Riot Desktop app for Mac, collapse the left pane which has the room list in it, when new messages come into a room you don't know that is the case. The room order might change, but there's no indicator for the actual messages.

### Steps to reproduce

- Start up Riot client on Mac
- Collapse the left pane
- Wait for messages to come in
- Try and determine which rooms have got messages since you last looked.

There should be some form of indication for this. When expanded, room names are in bold, but they aren't shown when it is collapsed.

<img width="65" alt="Screenshot 2020-01-22 at 11 40 21" src="https://user-images.githubusercontent.com/520844/72891387-091cb680-3d0c-11ea-8420-684f0ad7f56f.png">

### Version information

- **Platform**: Mac OS X 10.14.6, Riot Desktop client

For the desktop app (from my settings):

- matrix-react-sdk version: <local>
- riot-web version: 1.5.7
- olm version: 3.1.3

**Comment by t3chguy** [comment] 2020-01-22 14:10
Duplicate of #5454

**Closed by t3chguy** 2020-01-22 14:10 UTC
Labels: bug
