### ISSUE TITLE
Search for encrypted messages

### ISSUE THREAD

**Issue by vnscriptkid** [vector-im/riot-web#10502] opened 2019-08-05 04:06 UTC
Hi!, I wonder is there any way to search for encrypted messages across rooms. Currently, it works fine to search for plain messages. Greatly appreciate !!!

**Comment by turt2live** [comment] 2019-08-05 04:33
Duplicate of https://github.com/vector-im/riot-web/issues/2548

(short answer: no, it's not implemented yet)

**Closed by turt2live** 2019-08-05 04:33 UTC
Labels: bug
