### ISSUE TITLE
If you switch rooms in the middle of writing a reply the text is remembered but not that it's a reply

### ISSUE THREAD

**Issue by BearerOfHonesty** [vector-im/riot-web#10145] opened 2019-06-23 05:49 UTC
This isn't intuitive because the text still being there suggests that it remembers what was going on last you were in the channel.

If this is intentional behavior I'd suggest instead popping up a confirmation dialogue when sending the reply if there was any room switching while writing the message.

**Comment by turt2live** [comment] 2019-06-23 06:26
Duplicate of https://github.com/vector-im/riot-web/issues/6918

**Closed by turt2live** 2019-06-23 06:26 UTC
