### ISSUE TITLE
Can't cut and paste user pills in the composer

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#11378] opened 2019-11-13 12:27 UTC
Often I'll write a message in one room then realise it's better placed in another. When cutting or copying messages with pills to the clipboard, it seems they're reduced to plaintext. It's a pain to have to go through the message and manually replace the pills after pasting.

**Comment by bwindels** [comment] 2019-11-13 13:42
Indeed. I suppose we could intercept the `copy` event and add a custom mimetype, e.g. `application/x-cider-composer`, that contains the editor parts as json, and look for that mimetype over text when pasting in cider.

**Comment by turt2live** [comment] 2020-01-15 22:36
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3828

**Comment by turt2live** [comment] 2020-01-16 00:29
Reports are it doesn't work

**Comment by turt2live** [comment] 2020-01-16 05:18
Closing because the bug is actually fixed, it just wasn't deployed to /develop. https://github.com/matrix-org/matrix-react-sdk/pull/3848 fixes a regression caused by https://github.com/matrix-org/matrix-react-sdk/pull/3828

**Closed by turt2live** 2020-01-16 05:18 UTC
Labels: easy, suggestion, type:composer
