### ISSUE TITLE
Please, add to emojis hover text with emoji name

### ISSUE THREAD

**Issue by iav** [vector-im/riot-web#13621] opened 2020-05-10 19:21 UTC
Please, add to emojis hover text with emoji name, as in emoji chooser — ":unamused:, :blissful:". It's often hard to differentiate emojis, or recognize it. Especially on a different platforms.
Good to see in skype:
![Skype_2020-05-10_22-09-07](https://user-images.githubusercontent.com/325961/81508180-56e51b00-930b-11ea-8eb4-95391a11bf22.png)

**Comment by t3chguy** [comment] 2020-05-10 19:53
Duplicate of https://github.com/vector-im/riot-web/issues/9911

**Closed by t3chguy** 2020-05-10 19:53 UTC
Labels: bug, ui/ux
