### ISSUE TITLE
Grafana Widget does not work in Windows App but in Browser

### ISSUE THREAD

**Issue by vmario89** [vector-im/riot-web#9167] opened 2019-03-14 04:36 UTC
Hi,
i am running Riot 1.0.1 and using matrix-dimension to embed widgets. I figured out that displaying a widget works in within Browser based riot, but not in the electron provided Windows Application.

I tested the same stuff with vector.im integrations. same situation. Seems to be Riot-related. I double checked config.json - this is the same in Desktop App as well as on web server.

Is there any config setting i am missing?

regards, Mario

**Comment by lampholder** [comment] 2019-03-18 15:30
@jaywink any thoughts?

**Comment by jaywink** [comment] 2019-03-19 09:38
@lampholder unfortunately no. This seems like an issue with the Riot desktop build for Windows since the widget has been confirmed to work by op in riot web - so I think we should rule Scalar and/or Dimension here.

**Comment by jaywink** [comment] 2019-03-19 09:56
@vmario89 Riot 1.0.4 was released yesterday - would you mind upgrading and seeing if the problem persists? Thanks

**Comment by lampholder** [comment] 2019-03-19 09:58
Hey @vmario89 would you be able to describe in more detail how it isn't working?

I just tried a grafana widget on electron macOS - when I tried to load the widget, I got:
- a prompt to log in with username/password or github
- when I try and log in with github, I get a white screen

Is that what you're getting, or another failure mode?

For future reference, screenshots are hugely valuable when trying to debug Riot :)

**Comment by vmario89** [comment] 2019-03-19 15:16
Hi,
i have the following behaviour:

- displaying Grafana widget inside riot.fablabchemnitz.de works fine (version 1.0.4-rc1)
- displaying Grafana wdiget outside riot client, which is redirected to https://dimension.fablabchemnitz.de/widgets/generic-fullscreen?url=https.... and so and works fine too
- displaying Grafana widget inside Windows Riot Client (v1.0.4) does not work. It gives prompt to login inside Grafana. After entering credentials nothing happens. just showing login mask again

I am running exact same config.json for Windows App and web client.

**Comment by jaywink** [comment] 2019-03-20 13:03
Thanks for the additional information @vmario89 . I'm summoning @turt2live related to the Dimension connection here.

> displaying Grafana widget inside Windows Riot Client (v1.0.4) does not work. It gives prompt to login inside Grafana. After entering credentials nothing happens. just showing login mask again

When saying "Windows client", did you build this yourself or is it a vanilla build? What I'm looking at is whether the integration manager was "Scalar" or "Dimension" in this case. If you don't mind giving your Matrix ID, I could have a look from Scalar side what might show there. You can send it to me via PM at `@jaywink:federator.dev` if you prefer.

**Comment by vmario89** [comment] 2019-03-20 13:36
hey. thanks for that, i just sent you some message right now. regards, Mario

**Comment by jaywink** [comment] 2019-03-20 13:54
So confirmed in chat that Dimension is the integration manager used here. However, there is some kind of issue with Riot too since we've confirmed on our end with Scalar the Grafana GitHub login flow doesn't work with desktop riot, but works with web riot.

**Comment by turt2live** [comment] 2019-03-24 00:59
Sorry for the late reply - I don't think this is an integration manager problem. Given it reportedly doesn't work in Dimension or Scalar, and I can't reproduce this using dimension.t2bot.io I think this might be a CORS issue or similar. Double check that your Grafana instance isn't locked to a specific domain, and that it is allowed to be put into an iframe. 

Riot, Dimension, and Scalar all just use iframes so it is usually a matter of getting the right CORS stuff worked out, and possibly might be a bug in Grafana itself (would need to confirm this though).

**Comment by turt2live** [comment] 2019-03-24 01:03
also ftr, Dimension seems to also get the white screen of death when logging in with Github: https://github.com/turt2live/matrix-dimension/issues/257

**Comment by vmario89** [comment] 2019-03-24 22:53
The log says the following:
![grafik](https://user-images.githubusercontent.com/5631071/54887127-a0687180-4e8f-11e9-807c-ec9e0c3382f9.png)

**Comment by jaywink** [comment] 2019-08-16 13:51
Unfortunately there isn't a terrible lot we can do about the white screen of death on trying to use GitHub for login. They disallow this with a combination of `Content-Security-Policy: frame-ancestors 'none';` and (for older browsers `X-Frame-Options: deny` headers. Browsers are doing the right thing by not allowing the resource to be loaded.

Username/password login works fine for me at least. @vmario89 could you confirm once more which one of the following you are seeing? I fail to see a clear mention above.

1) username/password login does not work for grafana
2) github or other oauth login does not work for grafana
3) something else? (please describe and include screenshots)

Thanks!

**Comment by jaywink** [comment] 2019-08-25 13:35
Closing for now as there is no new information.

**Closed by jaywink** 2019-08-25 13:35 UTC
Labels: bug, type:electron, type:scalar, type:widgets
