### ISSUE TITLE
login-registration phase elements should respect system theme

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#13572] opened 2020-05-07 02:41 UTC
Steps to reproduce: set the dark theme and go through the registration process.
The following widgets will always be white regardless of the browser theme:

![image](https://user-images.githubusercontent.com/14617699/81248471-104ea280-9025-11ea-8b9a-b26d68d7a98b.png)
![image](https://user-images.githubusercontent.com/14617699/81248479-13499300-9025-11ea-8d15-0207eba4436a.png)
![image](https://user-images.githubusercontent.com/14617699/81248482-15135680-9025-11ea-97e6-f7551ba54ecf.png)

**Comment by turt2live** [comment] 2020-05-07 05:00
This is an intentional design decision to force the theme to be the light theme.

**Comment by 532910** [comment] 2020-05-07 05:05
I'm disagree, the theme should respect browser settings.

**Comment by turt2live** [comment] 2020-05-07 05:07
Whups, didn't mean to hit close on this one - was just leaving the note sorry

**Comment by aaronraimist** [comment] 2020-05-22 02:56
This is however a duplicate of an existing issue, #10198, so please go add a 👍 over there

**Closed by aaronraimist** 2020-05-22 02:56 UTC
Labels: blocked, needs-design, suggestion, type:login, type:registration, ui/ux
