### ISSUE TITLE
It's possible to react twice to a message

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10465] opened 2019-07-31 05:12 UTC
![image](https://user-images.githubusercontent.com/1190097/62185369-63b9f480-b31f-11e9-9585-e87d202a433a.png)

Unclear on cause. User reports that there was a queue of reaction events (of very long length) waiting to be sent. They quit Riot while waiting for the queue to process, and returned to the above screenshot. One more restart of Riot fixed it.

Likely a cache problem, somewhere.

**Comment by aaronraimist** [comment] 2020-05-07 20:14
Duplicate of #11161 (has thumbs)

**Closed by aaronraimist** 2020-05-07 20:14 UTC
Labels: bug, defect, feature:aggregations, feature:reactions
