### ISSUE TITLE
setting room alias & canonical alias on a newly created room often doesn't stick

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7099] opened 2018-07-27 16:35 UTC
i don't think you can set the canonical alias until the room alias has already been committed, but then the room alias itself also doesn't commit sometimes

**Comment by turt2live** [comment] 2018-07-27 16:36
Related to, if not duplicate of https://github.com/vector-im/riot-web/issues/4952

**Comment by lampholder** [comment] 2018-08-01 09:15
Yeah, looks like a dup to me. I'm going to bump the priority of #4952.

**Closed by lampholder** 2018-08-01 09:15 UTC
