### ISSUE TITLE
Feature request: automatically replace named emojis

### ISSUE THREAD

**Issue by swedneck** [vector-im/riot-web#7346] opened 2018-09-15 21:21 UTC
There's already an option to automatically replace emojis like :) and :(, it would be nice to have the same option for emojis like `:tm:` and `:100:`.

**Comment by turt2live** [comment] 2018-09-15 22:47
Duplicate of https://github.com/vector-im/riot-web/issues/7256

**Closed by turt2live** 2018-09-15 22:47 UTC
