### ISSUE TITLE
"invite to this room" inexplicably wraps after 30ish characters

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#14462] opened 2020-07-14 11:50 UTC
this is remarkably unnerving:

![Peek 2020-07-14 12-49](https://user-images.githubusercontent.com/1389908/87422408-81d04180-c5d0-11ea-81f4-eb4478827d13.gif)

**Comment by t3chguy** [comment] 2020-07-14 12:01
Duplicate of https://github.com/vector-im/riot-web/issues/13066

**Closed by t3chguy** 2020-07-14 12:01 UTC
Labels: bug
