### ISSUE TITLE
Searching for room members does not search invited 3pids

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6539] opened 2018-04-16 18:37 UTC
### Description

From HQ:
![image](https://user-images.githubusercontent.com/1190097/38828322-f3236630-4172-11e8-8e02-7c729af9f8b6.png)

Worse, clicking the "and 3 others" doesn't reveal 3 more people and instead just dismisses the fold

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 65
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment] 2018-04-16 19:40
Well this is new: DUPLICATE OF #6100

**Closed by t3chguy** 2018-04-16 19:40 UTC

**Comment by turt2live** [comment] 2018-04-16 19:41
My github searching skills are failing me. I must train more.
