### ISSUE TITLE
updating display name and profile picture isn't reflected immediately in the top left menu

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#10163] opened 2019-06-25 09:52 UTC
they were updated in the settings in Riot riot-web version: 1.2.2 (using SHHS)

**Comment by turt2live** [comment] 2019-06-25 16:15
Duplicate of https://github.com/vector-im/riot-web/issues/8570

**Closed by turt2live** 2019-06-25 16:15 UTC
