### ISSUE TITLE
Allow custom CSS import in `config.json` …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13137] opened 2020-04-11 22:51 UTC
It would be great to allow custom CSS import in `config.json` … this could be as easy as adding `@import url("/custom.css");` to: https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/themes/light-custom/css/_custom.scss

Maybe it’s even possible to use a css variable here, like: `@import url("var(--custom-css-path)");` … or maybe via sass, like:

```
$custom-css-path: var(--custom-css-path);
@import url("{$custom-css-path}")
```

Think that’s the easiest solution to this, but I’m more than happy if anyone know an even more simple solution which would make it into master very soon.

**Comment by fooness** [comment] 2020-04-12 10:15
This would also allow proper custom font support via defining paths to webfont files.

**Comment by turt2live** [comment] 2020-04-13 06:47
Duplicate of https://github.com/vector-im/riot-web/issues/7316

We are not currently intending on supporting this ourselves - there are several web browser extensions which achieve this.

**Closed by turt2live** 2020-04-13 06:47 UTC
Labels: suggestion

**Comment by fooness** [comment] 2020-04-13 09:56
@turt2live Web browser based, or client-side approaches to this problems are not comparable to server-side approaches. There really should be **some** way to add some custom css without having to manually edit the newly built `index.html` each and every time, over and over again. There needs to be some solutions that’s upstream-compatible in regards of being loaded.

**Comment by turt2live** [comment] 2020-04-13 13:51
The linked issue isn't for server-side support.

**Comment by fooness** [comment] 2020-04-13 14:36
@turt2live My issue was meant to be server-side. Riot-web-instance-specific. Not client-/browser-specific.

**Comment by turt2live** [comment] 2020-04-13 14:43
The config.json is not server side, it's client side. Server side would mean putting objects into account data or similar. 

In any case, custom css isn't a feature at the moment, so would be best to track it with one issue.

**Comment by jryans** [comment] 2020-04-14 16:55
@fooness It may help to discuss your ideas in #riot-web:matrix.org so we can comment on how they may fit with ongoing plans, etc.

**Comment by fooness** [comment] 2020-04-14 19:26
@jryans What’s your handle on Matrix, also `@jryans`? Didn’t find someone with that handle, yet …

**Comment by turt2live** [comment] 2020-04-14 19:27
I believe your query was answered: https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$sRa0_sb5Hv_dlJMFeyfIXr9h_0iWdh7mlDvC7KEYToA?via=matrix.org&via=privacytools.io&via=mozilla.org
