### ISSUE TITLE
No possibility to check all unread rooms by keyboard shortcut

### ISSUE THREAD

**Issue by telmich** [vector-im/riot-web#12325] opened 2020-02-11 22:51 UTC
Referring to #12279 for base information

If using a chat platform on daily basis and having 20+ channels active, it is imperative to have an easy way to find the "next important room" which contains unread messages. Mattermost solves this issue with the Ctrl-k shortcut and is probably one of the best features of Mattermost.

Whether it should be ctrl-k or any other keybinding is less of importance.

**Comment by t3chguy** [comment] 2020-02-11 23:05
Duplicate of https://github.com/vector-im/riot-web/issues/301

**Closed by t3chguy** 2020-02-11 23:05 UTC
Labels: bug
