### ISSUE TITLE
Password reset form doesn't work with generated password

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#9512] opened 2019-04-17 13:34 UTC
![Peek 2019-04-17 14-32](https://user-images.githubusercontent.com/1389908/56291827-eb3b7900-611d-11e9-9a1a-e2a7238b0a16.gif)

**Comment by turt2live** [comment] 2019-04-17 14:56
Closing as a duplicate of https://github.com/vector-im/riot-web/issues/6353 for "riot sucks at using a password manager"

**Closed by turt2live** 2019-04-17 14:56 UTC
Labels: bug
