### ISSUE TITLE
Markdown backslash behaviour is not consistent

### ISSUE THREAD

**Issue by cloudrac3r** [vector-im/riot-web#13694] opened 2020-05-16 10:31 UTC
I have verified using the issue preview feature that this post appears as I expect it to on GitHub.

Riot uses Markdown to format messages. The `*` character triggers italics, and the `\` character cancels a different trigger character. From reading other issues on here, I think you're using the commonmark specification.

### Working case

Typing `\*test one\* *test two*` appears in chat as: \*test one\* *test two*

This is the behaviour that I expect. Around test one, `\` cancels `*`, causing it to appear as a real `*`. Around test two, the `*` is actually used as the italics trigger. This makes sense.

### Not working case

Typing `\*test one\*` appears in chat as: \\\*test one\\\*

This is not the behaviour I expect. As in the previous example, I expect `\` to cancel `*` and appear as a real `*`. Instead, all characters are displayed literally, as if markdown isn't supported at all. The result I expect to see is: \*test\*

### More generally

It seems that using `\` to cancel markdown only actually does that if there are other characters in the message that are interpreted as markdown that apply some formatting. If there are no formatting changes in the message, then the entire message is treated as plain text and all characters are displayed literally rather than all messages being treated as markdown.

This is not what commonmark does: visting [the commonmark demo](https://spec.commonmark.org/dingus/) turns `\*test one\*` into \*test one\* as I would expect.

Even if it _was_ the same behaviour as commonmark, I would put forward the case that this is not intuitive behaviour and should be changed. When I write `\*test one\*`, I expect it to appear in chat as \*test one\*, no matter whether there is other content after it in the same message or not. The current behaviour is inconsistent, not intuitive, and not particularly useful.

### Version information

Happens in both Firefox 76.0 on riot.im and the Riot 1.6.0 desktop app, both on Ubuntu 19.10.

**Comment by t3chguy** [comment] 2020-05-16 11:07
Thanks for the indepth testing, but this is a duplicate of https://github.com/vector-im/riot-web/issues/11230

**Closed by t3chguy** 2020-05-16 11:07 UTC
Labels: bug
