### ISSUE TITLE
Hour overlaps the avatar in chat view

### ISSUE THREAD

**Issue by pascalchevrel** [vector-im/riot-web#11976] opened 2020-01-21 13:46 UTC
### Description
![image](https://user-images.githubusercontent.com/454375/72809448-eaf77d80-3c5b-11ea-9eda-5a24c39ec966.png)

The hour is slightly overlapping the avatar in the chat view in the web client when history view is set to compact.

### Steps to reproduce
Set view as compact

### Version information
- **Platform**: web 

For the web app:

- **Browser**: Firefox Nightly
- **OS**: Linux
Full buildID: Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0 ID:20200120154412
- **URL**: https://chat.mozilla.org/#/room/#synchronicity:mozilla.org

- **Version**: 1.5.7

**Comment by t3chguy** [comment] 2020-01-22 14:03
![image](https://user-images.githubusercontent.com/2403652/72900478-daa8d680-3d1f-11ea-8ff8-7085b838e92d.png)
![image](https://user-images.githubusercontent.com/2403652/72900497-e4323e80-3d1f-11ea-9e87-e540acd4c832.png)

Weirdly cannot reproduce on Chrome and Firefox (72.0.2) respectively

Any chance you have something forcing a different font/size to apply?

**Comment by Fnux** [comment] 2020-04-02 07:24
Duplicate of #11051.

**Closed** 2020-04-02 12:19 UTC
Labels: bug, mozilla
