### ISSUE TITLE
editing a message to be blank should probably redact it

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13671] opened 2020-05-14 13:58 UTC

**Comment by ara4n** [comment] 2020-05-14 13:59
(unless the intention is to keep the history around? in which case perhaps we keep it semantically distinct. or perhaps it should prompt whether to redact.)

**Comment by t3chguy** [comment] 2020-05-14 14:02
Duplicate of https://github.com/vector-im/riot-web/issues/11024

**Closed by t3chguy** 2020-05-14 14:02 UTC
