### ISSUE TITLE
Messages are lost when you refresh Riot page

### ISSUE THREAD

**Issue by JuniorJPDJ** [vector-im/riot-web#12587] opened 2020-03-02 11:49 UTC
Riot allows to refresh page when there are messages waiting to be sent.
IMO it should ask for confirmation or at least save them or save them in local storage.

The infobox telling user "messages will be sent when server is available" is confusing, it makes user feel like messages are saved at user side, but it's not the case, you can't close browser nor refresh page.

Just asking user if he really want to close page should be enough.

**Comment by t3chguy** [comment] 2020-03-02 11:51
Duplicate of https://github.com/vector-im/riot-web/issues/7177

**Closed by t3chguy** 2020-03-02 11:51 UTC
Labels: suggestion
