### ISSUE TITLE
Direct links to users lead to confused / broken state

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8791] opened 2019-02-19 15:49 UTC
![image](https://user-images.githubusercontent.com/1342360/53027852-a072ed00-345d-11e9-8cb6-043742d82e39.png)

### Description

Lots of people use matrix.to links on their contact page as their way of saying "Contact me on Matrix!". After the redesign, these links, such as https://riot.im/app/#/user/@andrewm:amorgan.xyz lead to a blank and empty page.

**This happens whether you're logged in or not.**

### Steps to reproduce

- Click a direct user link such as https://riot.im/app/#/user/@andrewm:amorgan.xyz
- Get a blank and unhelpful page

**Comment by ara4n** [comment] 2019-02-19 15:55
it's worse than this - i think /user links are broken even if you are logged in. I could have sworn i'd filed a bug  for this but can't find it now. E.g. https://riot.im/develop/#/user/@matthew:matrix.org (once logged in) doesn't show the MemberInfo.

**Comment by anoadragon453** [comment] 2019-02-19 15:57
Yikes, indeed.

**Comment by jryans** [comment] 2019-02-19 16:20
Yes, seems likes a duplicate of #8642, but this now has more info and labels. I'll close that one in favor of this.

**Comment by jryans** [comment] 2019-02-19 16:22
Originally posted by @bwindels in https://github.com/vector-im/riot-web/issues/8642#issuecomment-463723857:

> I sort of assumed this wasn't used anymore during the room header refactoring, my bad.
> 
> How should this look though, like before, shoved in the right panel with the middle panel empty?

**Comment by jryans** [comment] 2019-02-21 18:10
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2666

**Closed by jryans** 2019-02-21 18:10 UTC
Labels: bug, p1, redesign, regression, type:memberinfo

**Comment by anoadragon453** [comment] 2019-02-21 18:40
Looks good!
