### ISSUE TITLE
Pasting text within tripple backticks triggers searches?

### ISSUE THREAD

**Issue by sbts** [vector-im/riot-web#4786] opened 2017-08-13 19:23 UTC
Yves discovered this with a simple #72 reference within triple backtick code block

**Comment by t3chguy** [comment] 2017-08-13 20:53
Duplicate of https://github.com/matrix-org/go-neb/issues/186

**Closed by t3chguy** 2017-08-13 20:53 UTC

**Comment by sbts** [comment] 2017-08-15 01:48
Oops, missed those against go-neb
