### ISSUE TITLE
Clicking a user ID in a code block replaces the page with matrix.to instead of riot.im

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#9144] opened 2019-03-12 21:48 UTC
Should pop open the panel, not close riot.

**Comment by t3chguy** [comment] 2019-03-12 22:00
Duplicate of https://github.com/vector-im/riot-web/issues/3681

**Comment by t3chguy** [comment] 2019-03-12 22:01
unless its just User IDs, the other is more generic 🤷‍♂️

**Closed by t3chguy** 2019-03-12 22:00 UTC
