### ISSUE TITLE
Feature request: network logo on bridged user

### ISSUE THREAD

**Issue by homebeach** [vector-im/riot-web#6957] opened 2018-06-28 13:43 UTC
Riot would show network logo if the person is actually from other network than Matrix. For example if user is from XMPP the client would show graphical [XMPP logo](https://upload.wikimedia.org/wikipedia/commons/9/95/XMPP_logo.svg) on user.

**Comment by turt2live** [comment] 2018-06-28 14:41
This kinda feels like a duplicate of https://github.com/vector-im/riot-web/issues/6521 under the scenario of having flair for bridged users. The actual setup of said flair is an ops concern.

**Comment by lampholder** [comment] 2018-06-29 07:33
Yeah, I'd say this is a dup of #6521 (though I don't know what the current status is of these bridges' being associated with community/flair on matrix.org)

**Closed by lampholder** 2018-06-29 07:33 UTC
