### ISSUE TITLE
Remove centralization (Jitsi)

### ISSUE THREAD

**Issue by MyNameIsJulian** [vector-im/riot-web#8107] opened 2019-01-11 16:30 UTC
(deleted)

**Comment by nadonomy** [comment] 2019-01-11 17:18
(Removing the `redesign` label as this issue is completely independent of the redesign.)

**Comment by MazeChaZer** [comment] 2019-01-11 20:53
You can host Jitsi yourself (it's open source) and configure Riot to use that instance. I don't see how the use of Jitsi enforces any kind of "centralization". Matrix is not peer-to-peer, it's federated, meaning you can choose which servers to use and all servers are interoperable. The use of Jitsi doesn't break that. FYI, group calls where very unstable before Jitsi was introduced, so there is a reason they are no peer-to-peer anymore.

**Comment by Julian2000nl** [comment] 2019-01-12 11:06
@MazeChaZer yes you **can** host Jitsi yourself and you **can** configure it in your client. But that's not the point. If you have a group chat with 5000+ people who can all start a call then it's kind of impossible to guarantee everyone has a homeserver with their own Jitsi server and that this is configured in their client. 

Just like Jitsi is not apart of IRC, Jitsi is not apart of Matrix. Matrix uses WebRTC and Riot should use this standard to ensure proper inter-compatibility with non-riot users.

The point is that without Jitsi, Riot is a trustless client meaning you don't really have to trust Vector to not steal your data because it's not going through their servers. Adding Jitsi you now need to trust Vector to not steal your data because even if you configure your own Jitsi server there's still a big chance you'll use their infrastructure when joining an existing group call.

Or, of course, Matrix could completely replace WebRTC with Jitsi, include Jitsi in all the homeservers and make it "the standard" for all clients. Then all Riot has to do is default to the homeserver's Jitsi server instead of their own.

**Comment by MazeChaZer** [comment] 2019-01-13 11:45
Yeah I guess if the Matrix server would provide the location of the Jitsi server this would solve the problem, right? This is how it already works with Synapse and the TURN server if a relay for WebRTC calls is needed. You install your own TURN server and configure Synapse to use it. Would be great if one could configure the Jitsi server on the homeserver and all clients adapt automatically :+1: 
I'm with you on this, I think it's bad that all group calls go over https://jitsi.riot.im/ unless you reconfigure your client. Especially because this configuration is tedious and has to be done at compile time. I just think that Jitsi itself isn't the problem, more the way it's integrated into the system.
Also, this is a duplicate of #7711

**Comment by xuebaxuebaxueba** [comment] 2019-04-27 20:12
Please consider that the way this Jitsi thing is currently implemented somewhat subverts the trust model that people naturally tend to assume with a federated system like Matrix.

As the operator of a small homeserver, it puts me in a position of having to instruct my users not to use features X, Y and Z of the go-to Matrix client lest they have their communications routed over third parties. Which is all the more irritating when neither I nor my users particularly cared about those features in the first place.

Having the client ask the homeserver as per @MazeChaZer's suggestion seems like a reasonable solution. And, going on a bit of a tangent here, but the same model would make sense for determining the location of the identity server as well. I don't see why it should require the user to manually edit the configuration. Ultimately I guess both these things are about how much control you want to exert on the ecosystem with Riot and how much you're willing to defer to server operators.

**Comment by xuebaxuebaxueba** [comment] 2019-04-29 07:31
Related: #6430, #6802

**Closed** 2019-09-25 16:22 UTC
Labels: suggestion

**Comment by Ezwen** [comment] 2019-09-25 16:44
I'm curious, why is this closed? I thought removing Jitsi was part of the plan but not implemented yet.
