### ISSUE TITLE
Counter in header should be directly after 'Riot'

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#11244] opened 2019-10-28 10:22 UTC
The indicator for unread messages in the window header is [n] after the room name.  This incorrectly gives the impression there are n unread messages _in this room_.  Putting the counter before the pipe would repair this.

**Comment by t3chguy** [comment] 2019-10-28 10:23
Duplicate of https://github.com/vector-im/riot-web/issues/10943

**Closed by t3chguy** 2019-10-28 10:23 UTC
