### ISSUE TITLE
Provide way for open matrix links (matrix.to now and mx:// in future) directly in current app

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#5989] opened 2018-01-16 10:09 UTC
At now Riot Electron app rewrites in his interface all links to matrix resources to local, so link like `https://matrix.to/#/#riot:matrix.org` converts to internal `file://...` links, and on click - open them directly in current Riot instance.

But sometimes we receive links to matrix resources not in Riot, but in other sources (email, website, skype, telegram, etc), like:
- https://matrix.to/#/@Murz:matrix.org
- https://matrix.to/#/#riot:matrix.org 
- https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15160962321216952mYDKB:matrix.org

etc. At now there are no way to open those links directly in current running Riot app. 

We can only go to https://matrix.to website and run new separate Riot instance with this url. And harder way - paste this link in current Riot instance as message to some room, and after this - click on posted message for go to link.

Will be good to have ability to directly open matrix.to url in current Riot instance (web page or Electron app), via provide field to paste and open url.

As I thing, good place for this field url will be in `Room directory` page near room filter field with label "Open matrix url".

**Comment by lukebarnard1** [comment] 2018-01-16 11:45
I think a possible solution to this would be to use https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler, and register something like `web+riot://`.

**Comment by MurzNN** [comment] 2018-01-16 13:07
For provide protocol - we need to solve at first https://github.com/matrix-org/matrix-doc/issues/455 issue. And even when protocol will be registered, we don't solve the problem when user receives links in old format like https://matrix.to/#/#riot:matrix.org

So first step is to add ability to open `Matrix URI` in Riot interface (in any link format - `https://matrix.to/`, `matrix://`, `mx://`, `web+riot://`, etc)

And second long step - is specify `matrix://` protocol and integrate it in all Matrix components.

**Comment by t3chguy** [comment] 2018-01-16 13:09
@MurzNN matrix.to could fire off the `matrix://` or whatever link, that way it'd go full circle

**Comment by turt2live** [comment] 2018-01-16 16:02
This is a duplicate of https://github.com/vector-im/riot-web/issues/4940 and https://github.com/vector-im/riot-web/issues/3248

**Comment by t3chguy** [comment] 2018-01-16 16:07
Closing as duplicate of #3248
the other is slightly more about the protohandler

**Closed by t3chguy** 2018-01-16 16:07 UTC
Labels: feature, help-wanted, p3
