### ISSUE TITLE
Cannot discard invitations for deleted rooms/users

### ISSUE THREAD

**Issue by benbucksch** [vector-im/riot-web#12453] opened 2020-02-21 12:57 UTC
### Description

I logged in to my account after a months long absence. After logging in, I see an invitation from somebody. But I cannot dismiss it. Every action says that the room has been deleted. But the invitation does not go away, no matter what I do.

### Steps to reproduce

* I received a chat invitation from @mwyraz:matrix.org . I have no idea whether that's a spammer or a legitimate open-source developer who wanted to contact me. I have no idea when the invitation happened.

Actual results:
* I see 3 buttons:
  * [Start chatting]
  * [Reject & Ignore user]
  * [Reject] / [Ablehnen]
* After I click on them, all of them show that the action failed, because:
  * the room is unknown
  * the server is unknown
  * or the action just stalls without result
* What makes this bug serious is that none of the actions result in the invitation being removed. No matter what I do, the invitation stays. I cannot remove it.
* The invitation shown very prominently both at the start page (literally "front and center") and prominently at the top right, above the room list. Very annoying.

Expected result:
* Invitation does not show, if the room has been removed. OR:
* Invitation is removed, after I click on one of the options and the system notices that the room has been removed. At least at this point, the invitation should be removed.
* The invitation should definitely be removed, if I click "Reject". But that does not happen.

### Screenshots:
After I log in:
![image](https://user-images.githubusercontent.com/1907525/75036206-9bea7580-54b1-11ea-9857-8320058d594f.png)

After I click [Reject], the UI stalls (forever, so I need to refresh the browser page):
![image](https://user-images.githubusercontent.com/1907525/75036244-b58bbd00-54b1-11ea-92fb-8119f2349280.png)

After I click [Start chatting], I get "No known servers":
![image](https://user-images.githubusercontent.com/1907525/75036319-e0761100-54b1-11ea-8e08-d11f4dc1f091.png)

After I click [Reject and Ignore], I get "Unknown room":
![image](https://user-images.githubusercontent.com/1907525/75036351-f5eb3b00-54b1-11ea-97a4-2ef8b2914124.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox trunk
- **OS**: Ubuntu
- **URL**: riot.im/app

**Comment by benbucksch** [comment] 2020-02-21 13:09
In my user settings, tab Security and Privacy, I found an option "Reject all 1 invitations". That button has no effect, either. It refreshes, but stays with 1 invitation.

**Comment by t3chguy** [comment] 2020-02-21 13:16
Duplicate of https://github.com/vector-im/riot-web/issues/3743

**Closed by t3chguy** 2020-02-21 13:16 UTC
Labels: bug
