### ISSUE TITLE
Broken looking devices list

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9380] opened 2019-04-04 10:47 UTC
![image](https://user-images.githubusercontent.com/1342360/55549949-f975a800-56ce-11e9-859d-b56554e0c063.png)

https://matrix.to/#/@half-shot:fuckthe.dev

### Description

Device list looks broken. Why are there `!`s on some devices but not others? Indentation is different on different devices. Half `!` (I guess because it's half-shot?)

### Steps to reproduce

- Click on half-shot.dev's user page
- Scroll down to devices list and see brokenness

Log: sent

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: build of riot.im/develop

**Comment by jryans** [comment] 2019-04-04 14:08
It seems tied to the width of the right panel: currently the browser is refusing to wrap the riot.im URLs (since they are all one word), so the force a min width on the text, and icon gets hidden.

A workaround for now would be to resize the right panel to be a bit wider.

**Comment by jryans** [comment] 2019-04-04 14:18
`overflow-wrap: anywhere;` could work by inserting only minimum breaks required, but it's Firefox only at the moment:

<img width="262" alt="2019-04-04 at 15 16" src="https://user-images.githubusercontent.com/279572/55562860-baeee600-56ec-11e9-8a23-7173e54df3bc.png">

`word-wrap: break-all;` has better support, but it adds a lot more breaks in the middle of words, so it looks bad:

<img width="240" alt="2019-04-04 at 15 17" src="https://user-images.githubusercontent.com/279572/55562910-d35f0080-56ec-11e9-93fa-18bbb3694937.png">

**Comment by anoadragon453** [comment] 2019-04-04 15:15
> overflow-wrap: anywhere; could work by inserting only minimum breaks required, but it's Firefox only at the moment:

Can this be done in JS instead?

**Comment by jryans** [comment] 2019-04-04 16:48
> Can this be done in JS instead?

Doing the overflow would be quite yucky in JS I think... Some alternatives might be:

* Just show the first line and ellipsis after that
* Insert some kind of exotic Unicode space character to break up URLs without taking visual space

**Comment by timo95** [comment] 2019-04-06 10:54
The disappearing icons and not aligned buttons can be fixed like this:

![grafik](https://user-images.githubusercontent.com/24251362/55668434-a6385c80-586a-11e9-905c-bdbe30dea95c.png)

**Comment by jryans** [comment] 2019-04-08 09:06
Another approach would be to set a `min-width` on the icons, but then the buttons start to run away...

<img width="258" alt="2019-04-08 at 10 03" src="https://user-images.githubusercontent.com/279572/55711879-8c6f5480-59e5-11e9-8d69-98c72fcb6980.png">

**Comment by aaronraimist** [comment] 2019-09-28 02:16
Is this fixed now?

**Comment by timo95** [comment] 2019-09-28 06:48
It works, but very long buttons (German) don't leave any room for the text. It should get smaller, when it is small enough for a line break in the button.
![grafik](https://user-images.githubusercontent.com/24251362/65812760-23b2a900-e1cc-11e9-9cbb-2e09c2091792.png)

**Comment by t3chguy** [comment] 2020-07-16 06:25
This is completely redesigned, the issue is likely gone. Please reopen if it still applies.

**Closed by t3chguy** 2020-07-16 06:25 UTC
Labels: bug, defect, help-wanted, major, p2, type:e2e, type:userinfo, ui/ux
