### ISSUE TITLE
Cannot send a message

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9370] opened 2019-04-03 06:55 UTC
Loaded riot/develop, went around some rooms and tried to type in one without any effect. Pressed enter several times to try and send, then looked in the logs and saw errors, specifically the ones from logs-0000.log.gz in the rageshake:

```
TypeError: null has no properties
    ../../ReactSDKDevelop/workspace/matrix-js-sdk/lib/timeline-window.js/TimelineWindow.prototype.getEvents@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:36207:13
    _getEvents@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:84992:22
    onMessageListFillRequest/<@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:84234:221
From previous event:
    onMessageListFillRequest@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:84225:66
    _maybeFill/<@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:82647:20
    tryCatcher@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:165973:16
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromiseFromHandler@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164114:13
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromise@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164171:13
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromise0@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164216:5
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromises@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164296:13
    _drainQueueStep@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161209:9
    _drainQueue@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161202:9
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[2]</Async.prototype._drainQueues@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161218:5
    Async/this.drainQueues@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161088:9
    run@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:322420:22
    notify/<@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:322437:30
    flush@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:318238:9
```

**Comment by bwindels** [comment] 2019-04-03 07:04
![cannotsend](https://user-images.githubusercontent.com/274386/55459291-b4724880-55de-11e9-8e9f-86d7d9ffe100.png)

**Comment by bwindels** [comment] 2019-04-03 07:08
Wonder if this could be related to https://github.com/matrix-org/matrix-js-sdk/pull/873...

**Comment by bwindels** [comment] 2019-04-03 07:10
refreshing fix it fwiw

**Comment by bwindels** [comment] 2019-04-03 07:30
First error seems to be:
```
Already have timeline for $1554223554110GTium:jki.re - joining timeline !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.400Z to !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.600Z
2019-04-03T06:48:46.200Z W %cUnhandled rejection Error: timeline already has a neighbouring timeline - cannot reset neighbour (direction: f)
    ../../ReactSDKDevelop/workspace/matrix-js-sdk/lib/models/event-timeline.js/EventTimeline.prototype.setNeighbouringTimeline@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:25157:15
    ../../ReactSDKDevelop/workspace/matrix-js-sdk/lib/models/event-timeline-set.js/EventTimelineSet.prototype.addEventsToTimeline@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:24588:13
    ../../ReactSDKDevelop/workspace/matrix-js-sdk/lib/client.js/</MatrixClient.prototype.paginateEventTimeline/<@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:5770:44
From previous event:
    ../../ReactSDKDevelop/workspace/matrix-js-sdk/lib/client.js/</MatrixClient.prototype.paginateEventTimeline@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:5762:9
    ../../ReactSDKDevelop/workspace/matrix-js-sdk/lib/timeline-window.js/TimelineWindow.prototype.paginate@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:36132:16
    onMessageListFillRequest@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:84225:16
    _maybeFill/<@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:82647:20
    tryCatcher@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:165973:16
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromiseFromHandler@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164114:13
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromise@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164171:13
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromise0@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164216:5
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromises@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164296:13
    _drainQueueStep@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161209:9
    _drainQueue@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161202:9
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[2]</Async.prototype._drainQueues@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161218:5
    Async/this.drainQueues@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161088:9
    run@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:322420:22
    notify/<@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:322437:30
    flush@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:318238:9 color: red
```
with right after multiple of these:
```
2019-04-03T06:48:46.200Z E timeline is null
TypeError: timeline is null
    ../../ReactSDKDevelop/workspace/matrix-js-sdk/lib/timeline-window.js/TimelineWindow.prototype.getEvents@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:36207:13
    _getEvents@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:84992:22
    onMessageListFillRequest/<@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:84234:221
From previous event:
    onMessageListFillRequest@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:84225:66
    _maybeFill/<@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:82647:20
    tryCatcher@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:165973:16
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromiseFromHandler@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164114:13
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromise@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164171:13
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromise0@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164216:5
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[22]</module.exports/Promise.prototype._settlePromises@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:164296:13
    _drainQueueStep@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161209:9
    _drainQueue@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161202:9
    ./matrix-react-sdk/node_modules/bluebird/js/browser/bluebird.js/</</<[2]</Async.prototype._drainQueues@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161218:5
    Async/this.drainQueues@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:161088:9
    run@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:322420:22
    notify/<@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:322437:30
    flush@https://riot.im/develop/bundles/568d456ab128634d0cfb/bundle.js:318238:9
```

**Comment by bwindels** [comment] 2019-04-03 07:41
`Already have timeline for $1554223554110GTium:jki.re - joining timeline`, this event was right before the last event visible in the timeline btw.

**Comment by bwindels** [comment] 2019-04-03 08:33
Even earlier in the log
```
2019-04-03T06:48:43.400Z I Request to reset timeline in room  !WCHwNGGsrVwPeRtAnq:matrix.org  viewing: !WCHwNGGsrVwPeRtAnq:matrix.org
```
And then these (the lant.uk events seem to be state events that riot does not render by a bot):
```
2019-04-03T06:48:43.600Z I Already have timeline for $155422320012398FAbyl:lant.uk - joining timeline !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:38.400Z to !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.600Z
2019-04-03T06:48:43.600Z I Event $155422290112396PcTJf:lant.uk already in timeline !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.600Z
2019-04-03T06:48:43.600Z I Event $155422260212393IujJW:lant.uk already in timeline !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.600Z
2019-04-03T06:48:43.600Z I Event $155422238759227SCDce:matrix.org already in timeline !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.600Z
2019-04-03T06:48:43.600Z I Event $155422238459214SoznS:matrix.org already in timeline !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.600Z
2019-04-03T06:48:43.600Z I Event $155422237659175NyOnQ:matrix.org already in timeline !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.600Z
2019-04-03T06:48:43.600Z I Event $155422230412387SjEIH:lant.uk already in timeline !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.600Z
2019-04-03T06:48:43.600Z I Event $155422200012381NObIF:lant.uk already in timeline !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.600Z
2019-04-03T06:48:43.600Z I Event $155422170012378NsrSb:lant.uk already in timeline !WCHwNGGsrVwPeRtAnq:matrix.org:2019-04-03T06:48:43.600Z
```

**Comment by bwindels** [comment] 2019-04-03 09:21
So, AFAICT, the following is happening for room `!WCHwNGGsrVwPeRtAnq:matrix.org`:
 1. user is viewing the room
 1. sync comes in and sees gap, resets timeline (request to do so is granted because I was scrolled down)
 1. the scrollpanel tries to paginate more events in at the top, ends up doing a backwards fill on the live timeline and calling /messages
 1. once the result for that comes in, it tries to add those events to the live timeline
 1. somehow, one of the events in the response is already in an existing timeline
 1. we try to link up the live timeline and the existing one. Setting the previous neighbour on the live timeline seems to succeed, but once we try to set the next timeline on the existing timeline, it throws because it already has a next neighbour.
 1.  ...
 1. somehow `this._start.timeline` in the `TimelineWindow` ends up being null, and re-rendering the timeline fails completely.

**Comment by bwindels** [comment] 2019-04-03 09:21
Need to look into whether all timelines would have been reset or not, probably not as _eventIdToTimeline in the timeline set wasn't cleared.

**Comment by bwindels** [comment] 2019-04-03 11:47
This feels related to https://github.com/vector-im/riot-web/issues/8593, wdyt @turt2live ?

**Comment by bwindels** [comment] 2019-04-03 11:52
Might also be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/877

**Comment by turt2live** [comment] 2019-04-03 15:53
I think your primary problem is covered in https://github.com/vector-im/riot-web/issues/8593#issuecomment-478664610 (by the logging added in https://github.com/matrix-org/matrix-js-sdk/commit/5c8890c3c103cf74f981ef5547c5349fbf99c1a1) - Closing as a duplicate of that.

The remainder of your symptoms seem to be `timeline is null` blowing up React, causing a total crash and weird stuff like spinners that won't go away, inability to switch rooms, etc.

**Closed by turt2live** 2019-04-03 15:53 UTC
Labels: bug, major, p1
