### ISSUE TITLE
When viewing a group from the LLP, show me rooms I'm not in

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5733] opened 2017-11-29 21:33 UTC
### Description

Currently when clicking on groups on the Left Left Sidebar I can only see rooms I'm already in that are associated by the group. If I want to see which rooms I'm not part of, I have to manually cross-reference the room list and my sidebar, which is a bit tedious. Instead, taking a Discord and Slack like approach may work better where the rooms are always shown (when considering https://github.com/vector-im/riot-web/issues/5732), even if I'm not in that room. Clicking that room would try the default peek-to-join flow.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 62
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment] 2017-12-01 16:36
I wonder if we could expose this as a togglable setting from the LLS/roomlist.

You don't necessarily want always to show all the rooms (groups could have unwieldy numbers of rooms), but being able to see unjoined group rooms mixed in with the joined rooms is clearly much better than a manual cross referencing exercise.

**Comment by turt2live** [comment] 2017-12-01 16:38
One option would be to also throw the unjoined rooms under a tag, so you'd have an explicit section for "Rooms you're not in".

**Comment by aaronraimist** [comment] 2019-12-23 20:05
Duplicate of #6360 (newer but has more thumbs)

**Closed** 2019-12-23 20:11 UTC
Labels: feature, p3, type:communities, ui/ux
