### ISSUE TITLE
Code block scrollbar invisible on dark theme

### ISSUE THREAD

**Issue by yesennes** [vector-im/riot-web#13062] opened 2020-04-07 18:06 UTC
### Description

On dark theme, the scrollbar for long code block messages is invisible.

### Steps to reproduce

- Turn on dark theme
- Make a very long message inside triple backticks

On light theme a scrollbar is visible. I would expect the same scrollbar to be visible on dark theme.

Logs being sent: no

![image](https://user-images.githubusercontent.com/10568297/78703426-1fccb580-78d8-11ea-83b8-73f0c47386b1.png)
vs
![image](https://user-images.githubusercontent.com/10568297/78703503-48ed4600-78d8-11ea-90ed-1fba89dadcef.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 74.0.1
- **OS**: Ubuntu
- **URL**: riot.im/develop/ and riot.im/app

**Comment by dkasak** [comment] 2020-07-15 17:51
Duplicate of #9052.

**Closed** 2020-07-16 01:22 UTC
Labels: bug, ui/ux
