### ISSUE TITLE
Users failing to log into Riot 1.0 due to null Rooms?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8698] opened 2019-02-15 11:10 UTC
Two reports so far:

https://twitter.com/ElijahLynn/status/1096267706381127680 and a DM from \@Blindripper85 on twitter.

**Comment by jryans** [comment] 2019-02-15 11:12
Looks like a duplicate of https://github.com/vector-im/riot-web/issues/8692.

**Closed by jryans** 2019-02-15 11:12 UTC
