### ISSUE TITLE
[e2e] msgs aren't encrypted after joining a room from permalink

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-web#2771] opened 2016-12-20 15:44 UTC
To reproduce:
1. With device 1, create a room
2. Enable encryption
3. Add an address
4. Set history to anyone, set access to "anyone who knows the room's link apart from guess"
5. Send invitation to device 2
6. With device 2, accepts invitation and send a message
7. With device 1, copy permalink of this message, and send it to an other user on a web client
8. With the user on web client, join the room

Room isn't view as encrypted by the web client. Msgs sent by the client aren't seen as encrypted by devices (padlock is open) or himself.
On the screenshots, riotuser9 is the web client user.
If the user on web client logout and login, the room will be seen as encrypted.
I don't reproduce this on iOS or android.
![screen shot 2016-12-20 at 16 14 25](https://cloud.githubusercontent.com/assets/22364949/21356720/ecfbab26-c6d2-11e6-92fb-af39e632eeec.png)
![screen shot 2016-12-20 at 16 39 06](https://cloud.githubusercontent.com/assets/22364949/21356723/f104f84e-c6d2-11e6-9576-c9eacf097691.png)
![hcfy6dmk0zvwrvp0 ffrll18mstisivy9ehvf9pv9ne1tfov2uyfjawaaafg8k ztluf5xsbgq4codxv1qarkczxpmp2dns6xq7e3v9m0wzydguasfinjspkynkqlwlpayrhyhg0b8mfsxdfdbveohtt6enoeqxc5xha7haonaaaayfgtgc2v yixy vygteq4bdcuzsqqriame0th6bjfrocpcewdl4iaaaagcwzsgsoaaaaakwisjuaa](https://cloud.githubusercontent.com/assets/22364949/21356785/21c231e0-c6d3-11e6-8630-b23d5e761061.jpg)

**Comment by aaronraimist** [comment] 2018-09-08 03:53
I can't reproduce this anymore. Mind retesting with current versions of Riot @jeangb?

**Comment by aaronraimist** [comment] 2018-09-17 21:41
@richvdh you can probably close this.

**Closed** 2018-09-18 00:13 UTC
Labels: bug, p1, type:e2e
