### ISSUE TITLE
Rooms losing names and participants

### ISSUE THREAD

**Issue by kvark** [vector-im/riot-web#13768] opened 2020-05-22 14:45 UTC
### Description

After updating the Web client today (using from Firefox Nightly on macOS), I'm seeing some of the rooms losing their names, and the participant lists getting cleared up:

<img width="273" alt="Screen Shot 2020-05-22 at 10 42 24" src="https://user-images.githubusercontent.com/107301/82679431-f57d5000-9c18-11ea-9fe5-040da1419a2e.png">

These rooms previously had proper names and were full of participants.

### Steps to reproduce

Update to latest Riot Web client. Look at the left bar with the room list.

(I don't know how to get logs from the Web client).

### Version information

For the web app:

- **Browser**: Firefox Nightly 78.0a1 (2020-05-20) (64-bit)
- **OS**: macOS 10.15
- **URL**: riot.im/app

**Comment by aaronraimist** [comment] 2020-05-22 19:15
You can get logs by going to Settings -> Help & About -> Click Submit debug logs

This is a duplicate of https://github.com/vector-im/riot-web/issues/8246 so please thumbs up that issue and submit your logs referencing that one.

When this happens you should be able to work around it by going to the same place in settings I just mentioned and clicking Clear cache and reload

**Closed by aaronraimist** 2020-05-22 19:15 UTC
Labels: bug
