### ISSUE TITLE
Option to change username color

### ISSUE THREAD

**Issue by squidink7** [vector-im/riot-web#12863] opened 2020-03-25 03:11 UTC
**Is your suggestion related to a problem? Please describe.**
Every account has a color tied to it, but there is no option to change it, which seems strange.

**Describe the solution you'd like**
It would be good if there was an option to change the associated color, so users can better express themselves. 

**Additional context**
I have seen another issue on this topic but it was about implementing a way to change it server-side, and there has been no word from that thread pretty much since it was posted. Riot obviously has a way of selecting and remembering a certain color to apply to a username, so it would be nice if there was a simple UI for changing it.

**Extension** 
This is by no means necessary, but it would be a nice addition if changing the color of your username changed the accent color of all the buttons and menus throughout the app from their default green. just an idea though, feel free to ignore.

**Comment by turt2live** [comment] 2020-03-25 03:49
Duplicate of https://github.com/vector-im/riot-web/issues/11816

**Closed by turt2live** 2020-03-25 03:49 UTC
Labels: suggestion
