### ISSUE TITLE
tab complete (of a user) removes text before first letter of user/@

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#13205] opened 2020-04-16 12:59 UTC
![ac](https://user-images.githubusercontent.com/274386/79459298-9e190e00-7fe2-11ea-8660-d4f9fb24f6c9.gif)

**Comment by t3chguy** [comment] 2020-05-01 11:19
Looks like a duplicate of https://github.com/vector-im/riot-web/issues/11546#issuecomment-622348381

**Closed by t3chguy** 2020-05-01 11:19 UTC
Labels: bug, type:autocomplete, type:composer
