### ISSUE TITLE
Updating to Riot desktop 1.5.5 makes read markers not update consistently

### ISSUE THREAD

**Issue by Vroop** [vector-im/riot-web#11567] opened 2019-11-30 03:28 UTC
### Description

Before updating to Riot version 1.5.5, read markers would consistently update as other chat room participants read the messages. Now, the markers don't update consistently. In order to make them update, you sometimes have to navigate to a different room, and then navigate to the original room.

Sometimes, when another participant has read the message, their read marker will **quickly** flick out horizontally and then back to its original position. It will not move vertically to the latest message as expected.

### Steps to reproduce

- Update to Riot desktop 1.5.5
- send a message
- other participants' read markers don't consistently update when they read the message

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Linux Mint
- **Version**: 19.2

**Comment by turt2live** [comment] 2019-11-30 03:33
These are known as read receipts (read markers are the horizontal lines you see to track where you left off). This is a known bug, and should be fixed for the next release. Duplicate of #11496

**Closed by turt2live** 2019-11-30 03:33 UTC
Labels: bug
