### ISSUE TITLE
markdown should be consistent on all clients

### ISSUE THREAD

**Issue by ZerataX** [vector-im/riot-web#5149] opened 2017-10-02 23:26 UTC
### Description
as mentioned in https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15069853502593297uCUAW:matrix.org

On android strike through is done like this:
`~~strike through~~`
but on riot-web:
`<del>strike through</del>`

Same goes for underline

even riot-web itself isn't consistent currently: https://github.com/vector-im/riot-web/issues/3482

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: Firefox
- **OS**: Windows, Arch Linux
- **URL**: riot.im/app

For the desktop app:

- **OS**: Windows, Arch Linux
- **Version**:  0.12.4

**Comment by t3chguy** [comment] 2017-10-03 06:25
It's a known issue android is not using commonmark as it should.

**Comment by lampholder** [comment] 2017-10-04 12:22
Consistency is certainly important; we're tracking the android issue here: https://github.com/vector-im/riot-android/issues/779

I'm going to close this as a duplicate in favour of the android issue and #3482

**Closed by lampholder** 2017-10-04 12:22 UTC
Labels: bug, duplicate

**Comment by ZerataX** [comment] 2017-10-04 12:26
Furthermore isn't using html tags for strike through and underline, but for everything else markdown still inconsistent?

People new to riot coming from other messengers in my experience expect ~~strike~~ to work.

**Comment by Hi-Angel** [comment] 2019-10-05 12:07
> Consistency is certainly important; we're tracking the android issue here: [vector-im/riot-android#779](https://github.com/vector-im/riot-android/issues/779)
> 
> I'm going to close this as a duplicate in favour of the android issue and #3482

I might be misreading something, but it sounds like the problem is with riot-web and not the android one. The OP says:

> On android strike through is done like this:
> `~~strike through~~`
> but on riot-web:
> `<del>strike through</del>`

If you look into [github markdown cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#emphasis), you'll see that android got it correctly. The problem instead is with riot-web.

**Comment by t3chguy** [comment] 2019-10-05 12:44
Riot is using commonmark not github flavoured markdown, riot-android has an open issue to switch to commonmark so it is actually the one which is wrong as commonmark does not support that syntax
