### ISSUE TITLE
Nested rich replies are an endless ping fest.

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#5968] opened 2018-01-11 17:27 UTC
### Description

Decided to test this in offtopic and we ended up with a 3-level nested reply that was still pining richvdh.

### Steps to reproduce

- Send a message with a ping to someone
- Reply to it
- Reply to the reply
- Reply to the replied reply
- and so on

It should probably not ping unless you are in the immediate reply?

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by t3chguy** [comment] 2018-01-13 12:30
This will be caused by the imperfect plaintext representation, so related to https://github.com/vector-im/riot-web/issues/5974

**Comment by t3chguy** [comment] 2018-05-04 08:41
Fixed by merged PR

**Closed by t3chguy** 2018-05-04 08:41 UTC
Labels: bug, major, p1, type:notifications, type:replies, ui/ux
