### ISSUE TITLE
Show only community-less rooms (filter)

### ISSUE THREAD

**Issue by JuniorJPDJ** [vector-im/riot-web#14514] opened 2020-07-15 23:34 UTC
**Is your suggestion related to a problem? Please describe.**
You now can group chats in communities, but you can't see only chats which are NOT in any of your communities.
It becomes problematic if you are in huge communities and you also have big amount of "standalone" chats.

**Describe the solution you'd like**
Add additional button near community add button, which would filter out all rooms with communities.

**Comment by aaronraimist** [comment] 2020-07-16 00:00
Duplicate of https://github.com/vector-im/riot-web/issues/13141

**Closed by aaronraimist** 2020-07-16 00:00 UTC
Labels: suggestion, type:communities, type:llp

**Comment by JuniorJPDJ** [comment] 2020-07-16 07:59
This is not the same @aaronraimist 
I'd like to see rooms not in any community - all rooms in community not to be shown.
This issue is about reversing community filter - go back from community to all rooms, also this in communities.

**Comment by t3chguy** [comment] 2020-07-16 08:02
> You now can group chats in communities, but you can't see only chats which are NOT in any of your communities.
> Add additional button near community add button, which would filter out all rooms with communities.

That is exactly what #13141 wants; https://github.com/vector-im/riot-web/issues/13141#issuecomment-612634256

**Comment by JuniorJPDJ** [comment] 2020-07-16 10:53
Oh sorry, you are right.
