### ISSUE TITLE
[Feature Request] Notifications popup in OS, "Accept/Reject" instead of just "View" (call)

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#7546] opened 2018-10-24 02:47 UTC
I'm on Ubuntu with XFCE, the environment notification pops up when someone calls me, but just says "View", I think it'd be great if we could get "Accept/Reject" in the OS notification styling.

**Comment by aaronraimist** [comment] 2020-01-17 04:54
Duplicate of #11705

Looks like you forgot you opened this :)

The newer issue has more details so I'll close this old one

**Closed by aaronraimist** 2020-01-17 04:54 UTC
Labels: feature, p2, type:voip, ui/ux

**Comment by BloodyIron** [comment] 2020-01-17 16:23
@aaronraimist LOL well I did post this over a year ago, bound to forget it XD

But yeah, I agree, close this one, keep other one open.
