### ISSUE TITLE
Riot Electron Nightly does not update cleanly

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/riot-web#13213] opened 2020-04-16 14:57 UTC
When I click update on Riot Electron Nightly, it closes but often does not return, meaning I have to manually restart. I would guess it happens 1 out of every 3 attempts. I can't see any pattern in this behaviour.

**Comment by t3chguy** [comment] 2020-04-16 15:13
Duplicate of https://github.com/vector-im/riot-web/issues/12433

**Closed by t3chguy** 2020-04-16 15:13 UTC
Labels: bug
