### ISSUE TITLE
when showing invisible events in the timeline, you can end up with the avatar suppressed, which is very confusing

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11860] opened 2020-01-15 13:58 UTC

**Comment by ara4n** [comment] 2020-01-15 13:59
<img width="872" alt="Screenshot 2020-01-15 at 13 57 16" src="https://user-images.githubusercontent.com/1294269/72439622-306d0400-379f-11ea-8473-161e1a979678.png">

**Comment by ara4n** [comment] 2020-01-15 13:59
i wrote the last line, not erik

**Comment by turt2live** [comment] 2020-01-15 16:52
Duplicate of https://github.com/vector-im/riot-web/issues/10350 (same issue, not as good title - will fix)

**Closed by turt2live** 2020-01-15 16:52 UTC
