### ISSUE TITLE
Sign-in page lets me specify both email & phone number

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3526] opened 2017-03-28 00:52 UTC
This is very confusing UX - surely it should be one or the other, using radio buttons or whatever to select the appropriate mode of operation.  If you specify contradictory email & phone number, what happens?

@lampholder i assume this needs a meta bug, as i think it spans iOS & Android too...

**Comment by lampholder** [comment] 2017-03-28 15:42
I can confirm that it impacts Android at least.

So far I've been using riot-meta to track the progress of larger projects than this across the different platforms. For now I'll just file this as a bug on riot-ios and riot-android, too.

**Comment by lampholder** [comment] 2017-03-28 15:44
MAJOR because this is the gateway to the app. The behaviour is actually reasonably forgiving in some cases at least (supply a username and a msisdn and it seems happy enough), so I don't think this will stop logging in, but it creates a confusing impression right at the start of the user journey.

**Comment by giomfo** [comment] 2017-03-29 09:48
@lampholder I would expect a meta bug for this ux request in order to keep in one place the requirements and the request priority.

**Comment by tessgadwa** [comment] 2017-03-29 11:17
Would it be possible to combine with Issue #3532 and just address the
entire on boarding process as a single bug?

On Mar 29, 2017 2:48 AM, "giomfo" <notifications@github.com> wrote:

@lampholder <https://github.com/lampholder> I would expect a meta bug for
this ux request in order to keep in one place the requirements and the
request priority.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vector-im/riot-web/issues/3526#issuecomment-290040153>,
or mute the thread

**Comment by ara4n** [comment] 2017-03-30 14:58
i wonder if a solution here would be to just set `disabled` on the field which isn't focused?

**Comment by lampholder** [comment] 2017-04-03 13:18
We need some design on this. Ideally we'd design this _and_ implement for the next release, but let's _commit_ to getting the design done at least.

**Comment by lampholder** [comment] 2017-04-12 13:00
UX proposed in https://github.com/vector-im/riot-web/issues/3524 solves this issue.

**Comment by lampholder** [comment] 2017-04-12 17:01
Okay, so this is more important than we realised - if you put in both an email and a msisdn, and you only have email registered, it picks your msisdn and fails to log you in.

Upgrading this to `critical`.

**Comment by lampholder** [comment] 2017-04-12 17:04
And to solve this, implement the login mechanism chooser from #3524 but ignore all the stuff about improved country pickers :\ Sorry those things are unnecessarily coupled :(

**Comment by lukebarnard1** [comment] 2017-04-18 10:05
@lampholder could you delete https://github.com/lampholder in that case? That confused me.

**Comment by lampholder** [comment] 2017-04-21 13:26
For non matrix.org homeservers we should drop the template :matrix.org "domain" part of the UI. In the future we might want to add hints that the domain part is not actually necessary to type in here.

**Comment by lukebarnard1** [comment] 2017-04-21 15:13
@lampholder this feels like the wrong place to put that. It's quite unrelated to specifying multiple things on sign-in. I'd prefer it if we were to turn https://github.com/vector-im/riot-web/issues/3524 into "General login UX thread"

**Comment by tessgadwa** [comment] 2017-04-21 15:15
I'd second that.  Please be sure to distinguish from #2984 "General UX Thread."

**Comment by lukebarnard1** [comment] 2017-04-21 15:53
Closing as this is fixed by https://github.com/matrix-org/matrix-react-sdk/pull/811

**Closed** 2017-04-21 15:54 UTC
Labels: bug, cosmetic, critical, design, p1, type:login, ui/ux
