### ISSUE TITLE
Room dropdown changes back to [matrix]

### ISSUE THREAD

**Issue by ligi** [vector-im/riot-web#7782] opened 2018-12-05 10:53 UTC
when entering a custom server in the room dropdown - it get's changed back to [matrix] - which is very confusing:

![riot](https://user-images.githubusercontent.com/111600/49508853-16ff4600-f884-11e8-89a3-3c57d22466d5.gif)

I first thought it is not working - but it actually is. Just the content in the dropdown is wrong. Ideally the rooms would persist in this dropdown. Perhaps even contain all servers where I joined a room once.

**Comment by t3chguy** [comment] 2018-12-05 11:12
> Perhaps even contain all servers where I joined a room once.

This is not how matrix works, rooms aren't *on* servers, servers share rooms, so lets say in Matrix HQ there are 443 different servers, you can join the room using any of them: https://view.matrix.org/room/!QtykxKocfZaZOUrTwp:matrix.org/servers

So having the dropdown show all servers you've encountered would result in a very very very long list

**Comment by ligi** [comment] 2018-12-05 11:21
The size of the dropdown would be smaller than the size of rooms you joined. I still think this is a bug.

**Comment by turt2live** [comment] 2018-12-05 16:04
This would be solved by https://github.com/vector-im/riot-web/issues/5194 being fixed, but I think it's best if we leave this one open to track all the small bugs with the directory.

**Comment by t3chguy** [comment] 2019-02-26 09:09
Duplicate of https://github.com/vector-im/riot-web/issues/7364

**Closed by t3chguy** 2019-02-26 09:09 UTC
Labels: bug, minor, p2, ui/ux
