### ISSUE TITLE
better image size reduction on copy & paste

### ISSUE THREAD

**Issue by Flexmaen** [vector-im/riot-web#14151] opened 2020-06-23 13:04 UTC
**Is your suggestion related to a problem? Please describe.**
When I copy an image and paste it into Riot-Web directly, it often will get be very big and sometimes even exceed 10MB.

**Describe the solution you'd like**
There should be the option to resize images.

**Describe alternatives you've considered**
For example:
Riot-Android asks for reducing it to big/middle/small
Telegram has the option to post it as original or with reduced sice for faster transport
Whatsapp will automaticalle reduce the size.

I think to keep it original and with losless compressen like is done now with PNG is nice, but in most cases it just will do fine if the image and data size is reduced like other clients do it.

**Comment by t3chguy** [comment] 2020-06-23 13:09
Duplicate of #4144

**Closed** 2020-06-23 13:09 UTC
Labels: suggestion
