### ISSUE TITLE
Messages besides previews should wrap in IRC view

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#14763] opened 2020-07-25 10:53 UTC
The message 'XX has sent a picture' is largely hidden behind the preview of that picture, unless the user name column is set ridiculously wide.  Yet, there usually is lots of empty space below that message, previews typically being many lines high.  So wrapping the message would bring it fully into view, and make use of space that is currently wasted.

**Comment by t3chguy** [comment] 2020-07-25 10:54
Duplicate of https://github.com/vector-im/riot-web/issues/14758

**Closed by t3chguy** 2020-07-25 10:54 UTC
