### ISSUE TITLE
Document all UI settings you can change in config.json

### ISSUE THREAD

**Issue by WebFreak001** [vector-im/riot-web#7174] opened 2018-08-16 08:13 UTC
The default UI settings should be changable per deployed riot instance. Right now only the theme is changable but I would like to enable/disable by default some of the extra checkboxes in there like gif playback, url preview, timestamps, etc.

For our instance we want to reduce extra information like profile pic changes, etc. as much as possible to not confuse our users, because they are not very tech-savvy.

**Comment by t3chguy** [comment] 2018-08-16 08:57
Every setting default can be changed in config just how to do so is at present undocumented. Pinging @turt2live

**Comment by WebFreak001** [comment] 2018-08-16 10:04
ah the ones here right? https://github.com/matrix-org/matrix-react-sdk/blob/master/src/settings/Settings.js

**Comment by t3chguy** [comment] 2018-08-16 10:18
Yes any of those can be tweaked in `config.json` just the docs on how are missing from https://github.com/matrix-org/matrix-react-sdk/blob/master/docs/settings.md

**Comment by tulir** [comment] 2019-02-04 09:05
Duplicate of #6791?

**Comment by jryans** [comment] 2019-02-04 09:59
Yes, this seems to be a duplicate of #6791, but this one seems to have more detail and is easier to find, so I think I'll close #6791 in favor of this one.

**Comment by WebFreak001** [comment] 2019-02-04 11:48
can we change this to p1 then because the other issue was p1?

**Comment by jryans** [comment] 2019-02-04 11:51
Sure, updated priority.

**Comment by turt2live** [comment] 2019-02-15 04:51
Closing in favour of https://github.com/vector-im/riot-web/issues/8449

**Closed by turt2live** 2019-02-15 04:51 UTC
Labels: maintenance, p1, type:documentation
