### ISSUE TITLE
Spotify widgets won't delete, keep reappearing

### ISSUE THREAD

**Issue by jph168** [vector-im/riot-web#9378] opened 2019-04-03 21:15 UTC
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by jph168** [comment] 2019-04-03 21:17
had been adding and deleting spotify widgets, I have two now that won't delete when I delete they return a system error or timeout.

**Comment by turt2live** [comment] 2019-04-03 21:18
@jph168 please use the template and fill in the details... It's hard to troubleshoot any issue without that information.

**Comment by lampholder** [comment] 2019-04-30 14:25
Cannot reproduce, and the bug doesn't give anything to go on - closing.

**Closed by lampholder** 2019-04-30 14:25 UTC
Labels: bug, question, type:scalar
