### ISSUE TITLE
Unable to stop filtering by a community

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13146] opened 2020-04-12 19:24 UTC
### Steps to reproduce

- Click a community to filter by it
- Click the communities background, even while scrolled to the top
- Riot still filters the room list by that community

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Manjaro Linux
- **URL**: riot.im/develop

**Comment by t3chguy** [comment] 2020-04-12 19:26
Duplicate of https://github.com/vector-im/riot-web/issues/12988

**Closed by t3chguy** 2020-04-12 19:26 UTC
Labels: bug
