### ISSUE TITLE
Generic "Error creating alias" when attempting to create alias that already exists

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#11462] opened 2019-11-21 23:42 UTC
Could be a bit more friendly and say that the alias is already assigned to another room, or really friendly and offer to move it over to the new room if you were the one that created the original alias

![Screen Shot 2019-11-21 at 5 36 06 PM](https://user-images.githubusercontent.com/5855073/69385786-27235780-0c86-11ea-9c20-8f2fe0ff6867.png)

**Comment by turt2live** [comment] 2019-11-22 04:05
Thank you for reporting (it helps track all the things that went wrong). This is a duplicate of https://github.com/vector-im/riot-web/issues/9367 - I'll flag that accordingly.

**Closed by turt2live** 2019-11-22 04:05 UTC
Labels: room-upgrade-2019
