### ISSUE TITLE
Redacting an edited message only redacts original message but leaved edited one visible

### ISSUE THREAD

**Issue by JochenFriedrich** [vector-im/riot-web#11725] opened 2019-12-25 22:54 UTC
Steps to reproduce:

1. Submit a message
2. Edit the message 
3. Delete (redact) the message

The edited message is still shown in legacy clients. If you turn on hidden events, you can also select the edited message and click on show source to view the message.

![Screenshot_20191225_235005_com kiwibrowser browser](https://user-images.githubusercontent.com/12137836/71451220-a6b6b180-2771-11ea-9a4f-8fd94d9d7942.jpg)

**Comment by tulir** [comment] 2019-12-25 23:03
Duplicate of #10111, which points to matrix-org/synapse#5594

**Closed** 2019-12-25 23:27 UTC
Labels: bug
