### ISSUE TITLE
Permalinked messages can result in weird date separators

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5983] opened 2018-01-14 17:42 UTC
Where has the 10:50 come from?

<img width="918" alt="screen shot 2018-01-14 at 17 42 13" src="https://user-images.githubusercontent.com/1294269/34918880-55f090bc-f952-11e7-8dd6-1fbfc03fcb69.png">

**Comment by t3chguy** [comment] 2018-01-14 17:56
@ara4n any chance of the room/eventId that triggered this so I can reproduce?

**Comment by ara4n** [comment] 2018-01-14 17:58
sure - $1515280967862330nmYOd:matrix.org in Internal

**Comment by turt2live** [comment] 2018-01-14 18:02
Duplicate of https://github.com/vector-im/riot-web/issues/4605

**Comment by t3chguy** [comment] 2018-01-14 18:37
Closing as duplicate

**Closed by t3chguy** 2018-01-14 18:37 UTC

**Comment by t3chguy** [comment] 2018-01-14 18:44
Fixes by https://github.com/vector-im/riot-web/pull/5984 && https://github.com/matrix-org/matrix-react-sdk/pull/1702

![image](https://user-images.githubusercontent.com/2403652/34919384-f889d0b0-f95a-11e7-81e9-eb55efbb5150.png)
