### ISSUE TITLE
App stopped working completely, unhandled promise rejection 'browserName'

### ISSUE THREAD

**Issue by Siilwyn** [vector-im/riot-web#4191] opened 2017-06-05 09:18 UTC
### Description

I've been using Riot for a long time but it suddenly stopped working. I tried clearing my browser data and opening Riot in private mode to no avail.

### Steps to reproduce
1. Open the web app
2. Get stuck on a blank loading page

This is what's seen in the console:
![screenshot from 2017-06-05 11-17-15](https://cloud.githubusercontent.com/assets/5701149/26778198/97ad811c-49e0-11e7-8e64-39839b3cf7e4.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 53.0.3
- **OS**: Ubuntu
- **URL**: https://riot.im/app/

**Comment by MTRNord** [comment] 2017-06-05 09:21
`[sprintf]` errors are related to i18. Sounds like a broken language

**Comment by MTRNord** [comment] 2017-06-05 09:25
@Siilwyn do you use develop or a fixed version?

**Comment by Siilwyn** [comment] 2017-06-05 09:29
@MTRNord can I test that theory somehow? Also that would be weird as I'm just using "English (US)".

**Comment by MTRNord** [comment] 2017-06-05 09:31
@Siilwyn currently no Idea but normaly it says that a `%(browserName)s` is missing somewhere

**Comment by MTRNord** [comment] 2017-06-05 09:33
@Siilwyn do you have any type of AdBlocker running? On my side Firefox and Chrome are working fine.

**Comment by Siilwyn** [comment] 2017-06-05 09:34
Yes uBlock, just tried with all extensions disabled but that didn't work either.

**Comment by MTRNord** [comment] 2017-06-05 09:36
@Siilwyn can you take a look at your Networking Tab in the Console if it is downloading a ``en_EN.json`` ?

**Comment by Siilwyn** [comment] 2017-06-05 09:39
Yes, it's there. `200 OK`.

**Comment by Siilwyn** [comment] 2017-06-05 09:55
Just noticed I have the same problem in Chromium... I tried stepping through with the debugger but can't pinpoint where it goes wrong. After `Counterpart.prototype.translate` returns `entry` containing `"%(appName)s via %(browserName)s on %(osName)s"` it jumps to the `tryCatch` function inside `runtime.js`.

**Comment by MTRNord** [comment] 2017-06-05 09:58
@Siilwyn I know where it fails but cannot reproduce it :/ I check some things to find a trace. Both Chrome and Firefox are working fine on my side

**Comment by MTRNord** [comment] 2017-06-05 10:10
It could be that https://github.com/vector-im/riot-web/blob/24a5297fc8b38dce7790f98a3b25a29372e612db/src/vector/platform/WebPlatform.js#L163 Does not return a string which would cause it to fail.

**Comment by Siilwyn** [comment] 2017-06-05 12:00
Yes that line returns `undefined`, it shouldn't throw an error right? I would assume it should fall back to an empty string or a default?

**Comment by Kegsay** [comment] 2017-06-05 12:03
I would hope that passing an `undefined` value to `_t` wouldn't cause the entire thing to fail, given how the equivalent ES6 template strings work regardless.

```js
> s = {}
{}
> console.log(`hello ${s.foo}`)
hello undefined
```

**Comment by MTRNord** [comment] 2017-06-05 12:48
@Kegsay I guess that is a bug that should also be addressed to counterpart or sprintf-js

**Comment by Kegsay** [comment] 2017-06-05 15:57
https://github.com/matrix-org/matrix-react-sdk/pull/1035 will fix this in all cases, then will close this issue.

**Closed** 2017-06-06 12:56 UTC
