### ISSUE TITLE
Desktop: Unable to delete session after successful Mozilla SSO

### ISSUE THREAD

**Issue by arunsathiya** [vector-im/riot-web#13782] opened 2020-05-23 14:46 UTC
### Description

I am using Mozilla's homeserver, which implements SSO-based login as opposed to Matrix's default username-password based flow. When trying to delete a session from the Riot desktop app, I am prompted to authenticate with SSO. I successfully complete that request, but the desktop app does not recognize that the request has been successfully completed, thus making it impossible to delete a session.

### Steps to reproduce

- Start with a Mozilla homeserver-based (https://chat.mozilla.org) account.
- Login into the desktop app and open settings
- Under `Security & privacy`, delete a different session
- When prompted for SSO authentication, initiate it with a browser of your choice

Describe how what happens differs from what you expected.

Logs being sent: yes/no

After completion of SSO (in my case, GitHub login), come back to the app. Notice that the app is still stuck with this notice:

<img width="739" alt="Screenshot 2020-05-23 at 20 11 37" src="https://user-images.githubusercontent.com/18581859/82733540-1ab1b180-9d32-11ea-82a8-0ae2a9bc13fa.png">

For GitHub search reasons, after SSO, you would have this success message:

```
Thank you

You may now close this window and return to the application
```

It'd be on this page:

https://mozilla.modular.im/_matrix/saml2/authn_response

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Firefox 76.0.1 (64-bit)
- **OS**: macOS 10.15.4 (19E287)
- **URL**: Riot desktop app on Mac (more below)

For the desktop app:

- **OS**: macOS 10.15.4 (19E287)
- **Version**: Version 1.6.2 (1.6.2)

**Comment by t3chguy** [comment] 2020-05-23 14:58
Duplicate of https://github.com/vector-im/riot-web/issues/13719

**Closed by t3chguy** 2020-05-23 14:58 UTC
Labels: bug
