### ISSUE TITLE
can't create a private room with oneself anymore

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#12092] opened 2020-01-27 22:00 UTC
click create room, invite myself, get an error msg 'Failed to invite the following users to chat: @Amandine:matrix.org'. Click on new DM, invite oneself, there is a loading wheel and then it fails silently

**Comment by aaronraimist** [comment] 2020-01-27 22:09
Basically a duplicate of https://github.com/vector-im/riot-web/issues/4833, it just fails in a different way now

**Comment by turt2live** [comment] 2020-01-27 22:11
(the new dialog is supposed to be a little more forgiving in this)

**Comment by aaronraimist** [comment] 2020-01-31 05:01
This seems to work now

**Comment by turt2live** [comment] 2020-02-05 10:41
Indeed, seems to work.

**Comment by turt2live** [comment] 2020-02-20 16:25
This doesn't actually work as expected: it pukes errors when you invite yourself now.

**Closed** 2020-02-21 16:24 UTC
Labels: bug, project:ftue-user-lists
