### ISSUE TITLE
RTE loses focus after a file upload

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4664] opened 2017-07-24 01:09 UTC

**Comment by turt2live** [comment] 2017-07-24 04:48
fwiw, this appeared back in May as https://github.com/matrix-org/matrix-react-sdk/pull/3400 which was fixed by https://github.com/matrix-org/matrix-react-sdk/pull/822 and later backed out, which is now being re-introduced in https://github.com/matrix-org/matrix-react-sdk/pull/894 and may fix this issue. Possibly related to https://github.com/vector-im/riot-web/issues/3944 as well.

**Comment by lukebarnard1** [comment] 2017-08-02 15:36
So the decision on this is that we'll fix it on a case-by-case basis.

**Comment by turt2live** [comment] 2017-09-19 22:28
Duplicate of https://github.com/vector-im/riot-web/issues/4068

**Comment by t3chguy** [comment] 2017-09-19 23:06
Changed my mind about which to close

**Comment by t3chguy** [comment] 2017-09-19 23:06
I'm sorry...I misclicked :(

**Closed** 2018-06-22 09:43 UTC
Labels: bug, minor, p1, type:rte
