### ISSUE TITLE
Riot web only displays half of my communities in Settings (to be able to configure flair). 

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6401] opened 2018-03-27 16:54 UTC
Filed by @AmandineLP via a rageshake.

@AmandineLP can you show me this IRL?

**Comment by AmandineLP** [comment] 2018-04-10 13:44
It got replaced by https://github.com/matrix-org/riot-web-rageshakes/issues/760
I can definitely show it IRL.

**Comment by lukebarnard1** [comment] 2018-04-10 13:53
Looking at this IRL, it seems that each gemini scrollbar in riot on macOS is both native *and* gemini. 

This *may* have something to do with the fact that the box overflows comically.

**Comment by turt2live** [comment] 2019-02-15 04:27
I'm assuming that the issue is resolved by the tab being introduced. @AmandineLP if you continue to have issues, please re-open.

**Closed by turt2live** 2019-02-15 04:27 UTC
Labels: bug, major, p1, platform specific, type:communities
