### ISSUE TITLE
E2EE Setup prompts user for password even if logged in with OIDC

### ISSUE THREAD

**Issue by jordane** [vector-im/riot-web#13916] opened 2020-06-03 21:25 UTC
### Description

After setting up a synapse server with OpenID Connect (using Auth0), I attempted to enable E2EE by following the prompts in riot-web. I did the following:

1. Set a recovery passphrase
2. Confirmed the recovery passphrase
3. Downloaded the recovery code
4. Clicked "Continue"

I was then prompted with a box that is titled "Setting up keys" and prompts "Confirm your identity by entering your account password below.". This is unexpected because of the OIDC flow, Matrix does not know my sso password.

I tried entering the recovery passphrase, but that did not work.

### Steps to reproduce

- Set up synapse v1.14.0 with OIDC using Auth0
- Login to riot-web using Auth0
- Attempt to setup E2EE using above steps

I am prompted with a box asking for my account password, but I don't know what I should enter here (if anything). Clicking the close button closes the dialogue but does not complete the E2EE setup.

Logs being sent: yes

### Version information
- **Platform**: web (in-browser)

For the web app:

- **Browser**: Safari 13.1
- **OS**: macOS 10.15.4
- **URL**: Private server using riot 1.6.2

**Comment by t3chguy** [comment] 2020-06-03 21:26
Duplicate of https://github.com/vector-im/riot-web/issues/13580#issuecomment-625336620

**Closed by t3chguy** 2020-06-03 21:26 UTC
Labels: bug

**Comment by jordane** [comment] 2020-06-03 21:28
@t3chguy Thanks, I didn't think to check the closed bugs (I looked at open bugs and the CHANGELOG).
