### ISSUE TITLE
No longer able to blacklist devices on 1.6.0

### ISSUE THREAD

**Issue by catscratchedme** [vector-im/riot-web#13589] opened 2020-05-07 19:30 UTC
### Description

Before 1.6.0, I was able to blacklist devices individually. Now, there doesn't seem to be an option to do that.

This is helpful in some situations. For example: if you're chatting with someone who's lazy or not tech savvy about removing their old devices, even if they don't use them for Riot any more.

### Steps to reproduce

- Update Riot desktop to 1.6.0

- I expected there to still be an option to blacklist specific devices.

### Version information

- **Platform**:  desktop

For the desktop app:

- **OS**: Linux Mint
- **Version**: 1.9.3

**Comment by aaronraimist** [comment] 2020-05-07 20:11
Duplicate of #11751

**Closed by aaronraimist** 2020-05-07 20:11 UTC
Labels: bug, feature:e2e-cross-signing, phase:4
