### ISSUE TITLE
"This is a preview of this room" panel doesn't disappear after clicking to join

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#4405] opened 2017-06-24 13:03 UTC
### Description

When trying to join a room, I clicked on the "Click here to join the discussion" link.  I joined the room, as can be seen in the screenshot below, but the "This is a preview of this room" panel doesn't disappear.

![image](https://user-images.githubusercontent.com/1012976/27508770-af18346c-58ba-11e7-8602-769292bc1744.png)

After clicking the "Click here ..." a second time, the panel disappeared.

I don't know how reproducible this is.  I only noticed it this one time, but I haven't joined any other rooms recently.

Log: sent    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian
- **Version**: 0.11.3

**Comment by richvdh** [comment] 2017-07-03 11:50
logs at https://github.com/matrix-org/riot-web-rageshakes/issues/213

**Comment by lukebarnard1** [comment] 2017-07-03 15:18
Logs don't reveal a lot more than what has been described here. The room never seems to come back down the sync so the `RoomView` is marked as `waiting` forever.

**Comment by lukebarnard1** [comment] 2017-07-04 16:17
More logs from @ara4n at https://github.com/matrix-org/riot-web-rageshakes/issues/233

**Comment by lukebarnard1** [comment] 2017-07-17 16:14
So the symptom of this is that the client peeks despite there already being a membership event clearly in the room. We just shouldn't peek.

**Comment by lukebarnard1** [comment] 2017-07-17 16:51
Looking into this further, we might be storing the room without emitting the corresponding "Room" event, which will mean the event is never emitted.

**Comment by lukebarnard1** [comment] 2017-07-17 18:22
It turns out that some subset of these problems are being caused by an assumption that react-sdk is making, which is "we will always receive a 'Room' event when the client joins a room". This is not true if the user has peeked because the room has been stored already (probably causing https://github.com/matrix-org/riot-web-rageshakes/issues/213) and is also not true if the user has received an invite to the room. The invite itself will cause the room to be stored.

The fix is to not be `waiting` for a Room event in the RoomView, but instead also be waiting for a RoomMember event (which will be emitted regardless).

The other problem that @ara4n experienced here seems to suggest that the store is out of sync with the server in a permanent way, whereby the client thinks the room has not been joined (despite the joined member event being stored, with the room) but the server does not. Refreshing will not cause the store to update for some reason. The sync logic has changed very little so it is probably not a bug in the js-sdk and might actually be due to the indexdb store. Clearing the caches did rectify the problem, which supports the possibility of the problem lying with the indexdb store.

**Comment by aaronraimist** [comment] 2019-11-28 04:48
Fixed

**Comment by turt2live** [comment] 2019-11-28 04:49
yea, completely replaced.

**Closed by turt2live** 2019-11-28 04:49 UTC
Labels: bug, cannot-reproduce, cosmetic, major, p1
