### ISSUE TITLE
Rooms can't be reordered manually

### ISSUE THREAD

**Issue by anowlcalledjosh** [vector-im/riot-web#7793] opened 2018-12-06 21:24 UTC
### Description

Rooms in the room list apparently can't be reordered by hand – I think, from looking around the other issues, that they're automatically ordered by last activity? If they should be reorderable, then the bug is that they aren't; if they shouldn't be reorderable, then the bug is that the UI makes the user think that they should be.

### Steps to reproduce

- Be in at least two rooms
- Try to reorder the list of rooms
- Get positive visual feedback of the other rooms bubbling around as you drag a room around the list
- Observe that the room snaps back to its original position when released after a short delay where it appears to be settling into the new position, making it look like a bug that rooms can't be reordered

If rooms intentionally aren't reorderable, I wouldn't expect the other rooms in the list to move around when one room is being dragged, since it doesn't actually matter where in the list the room gets dropped.

Log: not sent, assuming not useful

### Version information

- **Platform**: desktop
- **OS**: Ubuntu 18.04
- **Version**: 0.17.6

**Comment by Half-Shot** [comment] 2018-12-07 20:15
They can be in favorites, but not rooms (which internally is even called "recents" or something I think). Reordering should definitely be a thing you can optionally do.

**Comment by jryans** [comment] 2018-12-07 22:03
Thanks for reporting this! The current intent is that you can drag between the categories of rooms (favorites, low priority), but you can't reorder inside a single category. I agree it feels strange, so hopefully it can be improved.

I believe this is a duplicate of #7086. Please reopen if it seems like a separate issue.

**Closed by jryans** 2018-12-07 22:03 UTC
Labels: type:roomlist, ui/ux
