### ISSUE TITLE
Make Share Room link contain room alias

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#14026] opened 2020-06-14 06:02 UTC
**Is your suggestion related to a problem? Please describe.**
At now "Share Room" link contain only id of room, eg this is for `Matrix HQ` room: https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org?via=matrix.org&via=privacytools.io&via=half-shot.uk

Why this url not contain main room alias `#matrix:matrix.org` for better look and easier join process?

**Describe the solution you'd like**
If room have main alias, provide better and shorter link like this: https://matrix.to/#/#matrix:matrix.org

What do you think about this idea?

**Comment by t3chguy** [comment] 2020-06-14 12:03
Duplicate of https://github.com/vector-im/riot-web/issues/12447

**Closed by t3chguy** 2020-06-14 12:03 UTC
Labels: suggestion
