### ISSUE TITLE
after a video call the screen does not turn off (automatically) anymore (until the next reboot)

### ISSUE THREAD

**Issue by DoctorSubtilis** [vector-im/riot-web#9415] opened 2019-04-09 19:52 UTC
### Description

After a video call the screen does not turn off (automatically) anymore (until the next reboot)

### Steps to reproduce

- make a video call
- leave the pc
- after a certain time, the screen should turn off, 
- instead, it continues to remain on indefinitely (with the screensaver)

Log: sent    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Kubuntu 18.04
- **Version**: 1.0.7

**Comment by t3chguy** [comment] 2019-04-10 07:38
Duplicate of https://github.com/vector-im/riot-web/issues/6814

**Closed by t3chguy** 2019-04-10 07:38 UTC
Labels: bug
