### ISSUE TITLE
Sometimes up part of reaction window out of viewport

### ISSUE THREAD

**Issue by iav** [vector-im/riot-web#14507] opened 2020-07-15 20:49 UTC
![download (1)](https://user-images.githubusercontent.com/325961/87594072-1207a700-c6f5-11ea-8a64-745fb34e2071.png)
Image not cropped on up border.

Reaction chooser window not fit up screen border.
There no scroller seen.

chooser window should 
1. be resizeable and/or draggable
2. should stay usable on browser on small screens|not maximized windows

https://develop.element.io/
Element version: 636529bb36b6-react-e1cf5ecd2f24-js-2a688bdac828
olm version: 3.1.3
Google Chrome
Version 83.0.4103.116 (Official Build) (64-bit)
Windows7, x64

**Comment by t3chguy** [comment] 2020-07-16 02:10
Duplicate of https://github.com/vector-im/riot-web/issues/11175

**Closed by t3chguy** 2020-07-16 02:10 UTC
Labels: bug, ui/ux
