### ISSUE TITLE
[Issue] Browser title is hard coded (v1.0.7)

### ISSUE THREAD

**Issue by menturion** [vector-im/riot-web#9436] opened 2019-04-12 09:33 UTC
### Description

Browser title phrase "Riot" seems to be hard coded ((v1.0.7)). 
Setting `"brand": "MyBrand"` in the "config.json" does not have any effect onto the browser title.

### Steps to reproduce

-1- Set the "brand" setting in the "config.json" to e.g. "MyBrand".
-2- Login to Riot web or force-reload the page.

-> Browser <title> is still "Riot".

### Question | Suggestion

If this is the expected behavior(?) I would like to file a feature request to not hard code the title and to use the "brand" setting instead.

**Comment by jryans** [comment] 2019-04-12 09:41
Thanks for the report! 😁 Yes, in general, we'd like the `brand` config to change all "Riot" instances, so it's a bug that it doesn't today. (At the moment, it's actually only used in _one_ place, and the rest are all static...)

Duplicate of https://github.com/vector-im/riot-web/issues/9065.

**Closed by jryans** 2019-04-12 09:41 UTC

**Comment by menturion** [comment] 2019-04-12 10:29
Many thanks for your reply.
Sorry for filing a duplicate, ... although I've search in advance.

**Comment by jryans** [comment] 2019-04-12 10:35
No worries, it's not a problem at all, it's quite hard to know where the issues are sometimes. 😁 Thanks again for the report!
