### ISSUE TITLE
incoming call on start

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#6510] opened 2018-04-12 23:33 UTC
Every time I start riot-web It shows all last incoming calls one by one! It appears for several seconds, than disappears. Then for the next user. Until it fully loads.

riot-web 0.14.0  https://riot.im/packages/debian sid/main amd64

**Comment by c-e-p-x-u-o** [comment] 2018-04-13 10:25
@pacien exactly, thanks for the more detailed explanation.

**Comment by lampholder** [comment] 2018-04-16 11:16
I think this is already filed somewhere, but I'll be damned if I can find it.

But yes, this happens reliably and is annoying :(

**Comment by pacien** [comment] 2018-05-18 11:11
Still here on riot-web 0.15.2.

**Comment by pacien** [comment] 2019-03-15 17:25
I'm not experiencing this problem anymore (running 1.0.1).
I believe this issue can be closed.

**Comment by 532910** [comment] 2019-03-15 17:38
And I still see it running 1.0.3!

**Comment by jryans** [comment] 2019-03-15 17:40
I believe I have also seen this in recent versions, but I can't remember precisely which one I had at the time.

**Comment by dalcde** [comment] 2019-06-02 15:58
This is still an issue in 1.2.1

**Comment by 532910** [comment] 2019-06-02 16:37
> This is still an issue in 1.2.1

Yes.
 
> EDIT: Duplicate of #3572

Looks so.

#6510 is major and #3572 is minor
Should #3572 priority be updatad? Should I close #6510?

**Comment by jryans** [comment] 2019-06-03 08:24
Yes, this looks like a duplicate of #3572. I have updated the priority there.

**Closed by jryans** 2019-06-03 08:24 UTC
Labels: bug, major, p1, ui/ux
