### ISSUE TITLE
Notifications appear to be targeting multiple devices

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3432] opened 2017-03-15 04:30 UTC
*This was originally posted as https://github.com/matrix-org/matrix-doc/issues/834 but was moved here by request - apologies for putting it in the wrong place*.

------

https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1489414975108249jrELW:matrix.org

I've also noticed this. When chatting with someone in the web browser, my phone is also being notified of messages, despite me explicitly having the riot tab open.

This was working up until a week or so ago (as far as I can tell). 

*I'm also unsure of where to report concerns similar to this. I do recall that matrix-doc is the best place for infrastructure-related issues*

**Comment by mvintila** [comment] 2017-03-15 09:55
Tested again this morning (Europe), and now it seems stuck on Desktop as active device. First thought was that it is now working correctly as phone doesn't ring anymore, and it might be caused by load on the matrix.org server during high activity periods, but this is not the case. It is effectively stuck with the desktop as active device.

With the riot window out of focus, and computer locked for more than 10 minutes of chatting on the phone, the notifications sounds still play on the computer, and not on the phone.

Even after closing Riot on desktop, the phone (Android) still doesn't get notified of new messages after more than 5-10 minutes. The notifications appear on the lock screen and in the bar, but no sound/vibration are played.

The behavior seems inconsistent and random. 

If anyone has any tips on where to start, i would love to have a look at the source code and try to understand what's going on to provide better feedback on this.

**Comment by lampholder** [comment] 2017-03-15 17:32
The current expected behaviour is that notifications go out to every registered notification target + every browser/electron Riot instance. Filtering the sending of notifications by client activity has not been implemented.

I don't believe that this behaviour has changed recently (though I am new here).

Some clients self-filter:
 - Riot Web and the electron desktop instances should not display notifications if they have focus (Riot Web seems to be working for me)
 - Riot iOS should automatically ignore push notifications if the app has focus
 - Riot Android appears to be doing the same thing

I also don't get notification sounds on my (android) phone, but I'm allergic to notification sounds so have disabled them at every level possible :P @mvintila are other apps notifying with sound/vibration?

**Comment by mvintila** [comment] 2017-03-16 08:25
Tested again, you are right, the part with the phone notifications not arriving anymore might have been sound settings :(. Notifications do come on every device, all the time.

As far as clients go, Android behaves correctly, no notifications while in focus, but the Linux desktop client does not, it plays sound on every message regardless of focus. See #3434.

**Comment by mvintila** [comment] 2017-03-16 08:27
But is this feature (notify only the active target) on the roadmap?

**Comment by lampholder** [comment] 2017-03-24 11:23
It's something that's been talked about, but I can't find a specific issue for it. Let's make this the issue to track it for now.

I'm classifying this as a P2 feature request. Blocked from further progress until we have a crisp definition of what the behaviour should be precisely.

**Comment by tokred** [comment] 2017-05-08 12:45
@lampholder Although I like the idea of XMPP resource priorities, I think it would be too complex to manage (both for users and implementers). From my perspective, the following high level behaviour would make sense to cover scenarios with multiple clients (e.g. a mobile client and additional client on PC/laptop). Bear with me though, I am no developer:

- Every registered client manages a boolean "presence" state which is announced to the server. Presence means the user is actively using this device (not necessarily the Matrix client) and therefore would prefer notifications solely on this device. If there are no clients with presence set, all clients get notified. If there is 1+ client(s) with presence, only such clients are notified.
- Clients are responsible to announce and refresh presence (i.e. active user) to the server in short-timed intervals, e.g. every 15s. On server-side, presence states expire automatically if no presence updates are received, e.g. after 30s. The server tracks presence states and restricts notifications to present clients. Maybe expiration of the last presence could trigger re-notification to all clients if there were recent notifications to avoid loss.
- Desktop/browser clients determine presence using similar mechanisms other messengers use to manage "away" state, e.g. timeouts, screensaver activation, etc. On mobile clients, presence would be limited to more or less "Riot has focus" or, if background tasks are enabled, to "device is not locked" (would refreshes drain battery?).
- Additionally, clients need to handle notifications separately if they have window focus. I would expect a more subtle/silent information if the client is already focussed compared to the case when it is in the background and I am using another app.

Such an approach would require coordinated changes in both client and server implementations. Any opinions?

Best regards

**Comment by ara4n** [comment] 2017-05-14 22:36
@turt2live are you *sure* you ever saw this working correctly? as far as I know we (sadly) push all notifs to all devices irrespective of presence - hence https://github.com/vector-im/riot-web/issues/1993 being a thing.  (in fact, i think this bug is a dup of #1993, but i'll leave it open until you answer :)

**Comment by ara4n** [comment] 2017-05-14 22:58
(i'm wondering if there /is/ some push/presence interaction here, which might have got damaged when we had to turn off presence for a while due to server load... @dbkr, any idea?)

**Comment by turt2live** [comment] 2017-05-14 23:48
@ara4n I'm reasonably sure it was working in late 2016, at the least. I do recall there being a time when my phone went off because of a message while I was using the web and thought "well that's strange". 

However, it is also entirely possible that the android app was being starved of resources, and simply wasn't notifying because it didn't have some kind of recovery mechanism (I'd constantly be seeing the Riot/Vector logo when opening the app - not as much anymore). 

This sounds like it could be resolved by #1993, although I swear there was a time when notifications were less intrusive.

**Comment by t3chguy** [comment] 2017-05-27 18:16
Duplicate of #469

**Closed by t3chguy** 2017-05-27 18:16 UTC
Labels: feature, p2, type:notifications
