### ISSUE TITLE
Restrict nickname lengths.

### ISSUE THREAD

**Issue by ghost** [vector-im/riot-web#14383] opened 2020-07-08 23:24 UTC
**Is your suggestion related to a problem? Please describe.**
Recently, it has been discovered that the length of your nickname in a room can be insanely long, causing lag and problems with mentioning them.

**Describe the solution you'd like**
A nice nickname length-cap would be around 20-30 characters most likely.

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
None needed.

**Comment by penloy** [comment] 2020-07-08 23:25
A screenshot of this issue:

![image](https://user-images.githubusercontent.com/25794029/86980005-a3699d00-c17a-11ea-8dc5-3300416e10f4.png)

**Comment by penloy** [comment] 2020-07-08 23:26
![image](https://user-images.githubusercontent.com/25794029/86980055-c72ce300-c17a-11ea-86ec-99c53ad5e74b.png)

**Comment by Kellegram** [comment] 2020-07-08 23:27
It me :D Yeah this is crazy, my name is the entire Bee movie script from start to finish. Which while hilarious and a great way to experience the movie ( ;p )  is causing huge lag for people. This is done with the /myroomnick command.

**Comment by aaronraimist** [comment] 2020-07-10 18:18
Duplicate of https://github.com/vector-im/riot-web/issues/5739

**Closed by aaronraimist** 2020-07-10 18:18 UTC
Labels: suggestion
