### ISSUE TITLE
Spoilers are visible in the room list message preview

### ISSUE THREAD

**Issue by surakin** [vector-im/riot-web#14801] opened 2020-07-28 16:24 UTC
### Description

Spoilers show their text in the room list message preview

### Steps to reproduce

- Enable room list message previews in element web/desktop
- From Element Android send /spoiler text to a channel
- Notice the spoiler text is shown in the room list.

Logs being sent: yes/no

- Tested on Element Android 1.0.0, Element Web & Desktop 1.7.2

**Comment by turt2live** [comment] 2020-07-28 16:33
Duplicate of https://github.com/vector-im/riot-web/issues/14447

**Closed by turt2live** 2020-07-28 16:33 UTC
Labels: bug, type:new-room-list
