### ISSUE TITLE
clicking on RRs should surely open MemberInfo

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6066] opened 2018-01-30 09:50 UTC

**Comment by lukebarnard1** [comment] 2018-01-30 09:54
Currently they toggle the +n RRs sliding out from underneath if there are >5

**Comment by t3chguy** [comment] 2018-01-30 09:55
Duplicate of https://github.com/vector-im/riot-web/issues/5784

**Comment by lukebarnard1** [comment] 2018-01-30 09:55
Also this is a dup: https://github.com/vector-im/riot-web/issues/5784

**Comment by lukebarnard1** [comment] 2018-01-30 09:55
o_o @t3chguy jinx!

**Closed** 2018-01-30 09:55 UTC
