### ISSUE TITLE
m.room.create and m.room.power_levels events are incorrectly rendered.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#12217] opened 2020-02-03 20:37 UTC
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- Create a room.
- Notice that the first event is blank.
- Expand `created and configured the room.`
- Notice that the power levels event is also blank.
- Change the PLs of yourself
- Notice that event is not blank.

Describe how what happens differs from what you expected:

I'd expect the events to be entirely invisible, or have textual descriptions.

![image](https://user-images.githubusercontent.com/2072976/73688900-f1a6db80-46c4-11ea-8db9-50ddf5d0cc73.png)

### Version information

- **Platform**: riot.im/develop on Chromium 78

**Comment by turt2live** [comment] 2020-02-03 22:11
Closing as a duplicate of https://github.com/vector-im/riot-web/issues/11510 until you say you don't have 'show hidden events' enabled :)

**Closed by turt2live** 2020-02-03 22:11 UTC
Labels: bug
