### ISSUE TITLE
Room widgets show infinite  spinner when minimised and maximised

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/riot-web#6709] opened 2018-05-12 09:25 UTC
Probably due to the most recent changes to sticker widget matrix-org/matrix-react-sdk#1888

**Comment by turt2live** [comment] 2018-05-12 14:59
Duplicate of https://github.com/vector-im/riot-web/issues/6707

**Closed** 2018-05-14 10:17 UTC
