### ISSUE TITLE
[Bug] Windows, set to start up, steals focus even though minimized

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#6423] opened 2018-03-31 04:37 UTC
When Riot-Web (Desktop) is set to auto start with Windows, it often steals focus repeatedly. This can be really annoying when I'm trying to type in passwords while my system is starting up.

Any chance we can get it to stop stealing focus pls? A "start minimized" option might handle this.

Desktop Version 0.13.5

**Comment by t3chguy** [comment] 2019-08-05 11:31
I cannot reproduce this on Windows 10

**Comment by t3chguy** [comment] 2020-07-12 18:52
Closing as unable to reproduce and it would be an upstream issue anyhow

**Closed by t3chguy** 2020-07-12 18:52 UTC
Labels: bug, cannot-reproduce, major, p1, type:electron, ui/ux
