### ISSUE TITLE
community invite by mail

### ISSUE THREAD

**Issue by sebus430** [vector-im/riot-web#13306] opened 2020-04-21 10:35 UTC
I hope this is the right place for my suggestion,

At the moment it is possible to invite to rooms using a users E-Mail address. When inviting to communities this is suddenly not possible.
Would it be possible to implement the room behaviour for communites?

![community_invite](https://user-images.githubusercontent.com/55051076/79856331-8075eb00-83cc-11ea-915f-5b9c0f0f32e4.png)
![room_invite](https://user-images.githubusercontent.com/55051076/79856334-81a71800-83cc-11ea-992b-4f2a6b89ea68.png)

**Comment by t3chguy** [comment] 2020-04-21 10:46
Duplicate of https://github.com/vector-im/riot-web/issues/10802

**Closed by t3chguy** 2020-04-21 10:46 UTC
Labels: suggestion
