### ISSUE TITLE
Ability to "jump" to specific time/date in chat history?

### ISSUE THREAD

**Issue by Ezwen** [vector-im/riot-web#11274] opened 2019-10-31 20:51 UTC
**Is your suggestion related to a problem? Please describe.**

While the search tool works really well, and while looking at messages from the past days works rather well by scrolling up, I find it really difficult to explore older messages from the chat history. For instance, if I want to look at messages from one month ago, the only choice I have is to scroll… quite a lot.

**Describe the solution you'd like**

While scrolling I was thinking that I would love to have a button that pops out a calendar widget where I could click on a day, and it would jump to the chat history from that day.

**Describe alternatives you've considered**

I don't see any alternatives for now but I'm rather bad at UX design :)

**Comment by gloomy-ghost** [comment] 2019-11-10 01:24
see also: filter by date https://github.com/vector-im/riot-web/issues/4752

**Comment by jryans** [comment] 2019-11-11 12:22
Thanks for the feedback! I think this is effectively the same request as https://github.com/vector-im/riot-web/issues/7677, so let's consider this a duplicate of that.

**Closed by jryans** 2019-11-11 12:22 UTC
Labels: suggestion
