### ISSUE TITLE
Riot app fails to load if integrations URLs are falsey

### ISSUE THREAD

**Issue by cuibonobo** [vector-im/riot-web#4871] opened 2017-08-24 16:05 UTC
### Description

I'm running a Matrix server inside a corporate LAN and do not have federation turned on, so I set the `integrations_*_url` keys in `config.json` to empty strings in order to avoid seeing the "Could not connect to integration server" error in the UI. Per #2606 and its corresponding pull request, the UI should disable integrations and not even attempt to connect to an integration server.

Unfortunately in the latest update (0.12.1) this functionality is broken. Opening the app shows a loading gif and does not go any further. I've saved a gist of my full Developer Console log [here](https://gist.github.com/cuibonobo/9f8af3fc511d2e8ec4845bd6fb61159b), but a (hopefully) representative portion of it is below:

```text
rageshake.js:65 MatrixClient sync state => PREPARED
rageshake.js:65 newscreen room/!zYIoXaXAWRBpUaIsbO:matrix.floydcounty.tv
rageshake.js:65 RVS update: !zYIoXaXAWRBpUaIsbO:matrix.floydcounty.tv undefined loading? false joining? false initial? true waiting? undefined shouldPeek? true
async.js:61 Uncaught Error: Minified React error #109; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=109&args[]=t for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (reactProdInvariant.js:31)
    at f._renderValidatedComponent (ReactCompositeComponent.js:830)
    at f.performInitialMount (ReactCompositeComponent.js:361)
    at f.mountComponent (ReactCompositeComponent.js:257)
    at Object.mountComponent (ReactReconciler.js:45)
    at h.mountChildren (ReactMultiChild.js:236)
    at h._createInitialChildren (ReactDOMComponent.js:703)
    at h.mountComponent (ReactDOMComponent.js:522)
    at Object.mountComponent (ReactReconciler.js:45)
    at h.mountChildren (ReactMultiChild.js:236)
    at h._createInitialChildren (ReactDOMComponent.js:703)
    at h.mountComponent (ReactDOMComponent.js:522)
    at Object.mountComponent (ReactReconciler.js:45)
    at h.mountChildren (ReactMultiChild.js:236)
    at h._createInitialChildren (ReactDOMComponent.js:703)
    at h.mountComponent (ReactDOMComponent.js:522)
```

### Steps to reproduce

  * Install Riot.app version 0.12.1
  * Change the values of `integrations_ui_url` and `integrations_rest_url` in `Riot.app/Contents/Resources/webapp/config.json` to empty strings
  * Launch Riot.app

You should see the app on a loading screen indefinitely. Leaving the integrations URLs at their default values will load the app, but the UI displays a "Could not connect to integration server" because my Matrix server does not have federation turned on (as described in [this comment](https://github.com/vector-im/riot-web/issues/3329#issuecomment-288819208) of #3229).

Log: not sent ('Settings' page is inaccessible)

![screenshot 2017-08-24 12 04 33](https://user-images.githubusercontent.com/391241/29675851-67daf9ec-88c4-11e7-95fa-28e273b1a73e.png)

### Version information

- **Platform**: desktop
- **OS**: macOS
- **Version**: 0.12.1

**Comment by t3chguy** [comment] 2017-08-24 16:07
potentially fixed in 0.12.2

rest of fix (to return the ability to hide Scalar stuffs by providing empty strings) is https://github.com/matrix-org/matrix-react-sdk/pull/1332

**Comment by turt2live** [comment] 2017-08-25 00:37
Cannot reproduce on 0.12.2 (deployed it myself today)

**Comment by t3chguy** [comment] 2017-08-25 07:32
thanks @turt2live 
Closing as direct effect is fixed, secondary effects tracked here: #4852

**Closed by t3chguy** 2017-08-25 07:32 UTC

**Comment by chized** [comment] 2020-02-10 13:19
I setup a homeserver over intranet and I have a similar error. I using Nginx for reverse proxy. From client Riot.im,  user can make one-one calls but this error shows up one the user on a call becomes three or more.
Can I use matrix.org for federation?
If not, do I need another local server for federation i.e separate server, Or is there a way to make conference call work within our intranet without federation. Thanks in advance

**Comment by ODDSys** [comment] 2020-03-30 06:15
I also experience the same issue as @chized, i do not use federation.
1 to 1 voice and video work fine, it just throws the error on conference calls.
Conference does work on the android riot app, issue appears to only be in riot-web.

**Comment by chized** [comment] 2020-03-30 08:33
> 
> 
> I also experience the same issue as @chized, i do not use federation.
> 1 to 1 voice and video work fine, it just throws the error on conference calls.
> Conference does work on the android riot app, issue appears to only be in riot-web.

I did not know it could work on the android app.  For riot web, I set up dimension and add the jitsi meet widget to enable conference video calls

**Comment by jryans** [comment] 2020-03-30 11:50
Please stop by #matrix:matrix.org for questions like these and we can redirect to an appropriate room as needed.
