### ISSUE TITLE
Add Sound Speaker device selector in Riot settings

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#6784] opened 2018-05-23 09:39 UTC
Very often for calls people use headphones instead of default device (loudspeakers). At now Riot don't provide speaker device selector for sound output, only microphone. Other IM apps (based on Electron too, eg Skype) provide device selector for speaker too.

Please add Sound Speaker device selector in Riot settings.

**Comment by t3chguy** [comment] 2018-05-23 09:40
Duplicate of https://github.com/vector-im/riot-web/issues/4203 .

**Closed by t3chguy** 2018-05-23 09:40 UTC
