### ISSUE TITLE
Add option to disable automatic image display from Files repository

### ISSUE THREAD

**Issue by voice06** [vector-im/riot-web#10963] opened 2019-09-25 22:09 UTC
The recent spam attacks I've been seeing have been using the room's file repository to get images past the setting to display / not display inline images/content from websites. Particularly fun when its a flood of NSFW content on public room.

Is there a way we can get an option added so instead of just displaying them right away you need to click to view or open them from the files list? It'd be nice to be able to flip a bit when one of these attacks is on-going.

**Comment by aaronraimist** [comment] 2019-09-27 15:06
Duplicate of https://github.com/vector-im/riot-web/issues/4286 / https://github.com/vector-im/riot-web/issues/2466

**Closed** 2019-09-27 16:45 UTC
Labels: suggestion
