### ISSUE TITLE
UX: Decrypting a file to download gives no feedback to the user.

### ISSUE THREAD

**Issue by compu42** [vector-im/riot-web#13410] opened 2020-04-28 01:16 UTC
### Description

Pressing "Decrypt" on a file to download gives no feedback. This is especially confusing for users who may not understand that the file has to be loaded and decrypted before it becomes downloadable. This is especially a problem for large files that take a while to load and decrypt, and it's also a problem for slow servers that can't serve said files as quickly.

I have gotten so many messages from my friends saying "Why is it not decrypting?"

I suggest making the button change to "Decrypting..." or "Decrypting, please wait..." while its being loaded and decrypted to not confuse users.
### Steps to reproduce

- Receive a large file.
- Press "Decrypt [filename]"
- Notice how the button doesn't change or give any feedback before becoming downloadable.

Describe how what happens differs from what you expected.

It would simply make more sense for the button to say "Decrypting..."

Log: N/A    

### Version information

- **Platform**: Desktop and Web

For the web app:

- **Browser**: Seems to be all browsers, I personally tested on Firefox.
- **OS**: Seems to be all OSes, I personally tested on Debian 10, Windows 10, Ubuntu 19.04, and Ubuntu 14.04.
- **URL**: riot.im/app

For the desktop app:

- **OS**: Windows 10, Debian 10, Ubuntu 19.04, Ubuntu 14.04
- **Version**: 1.5.15

**Comment by turt2live** [comment] 2020-04-28 03:32
Duplicate of https://github.com/vector-im/riot-web/issues/2749

**Closed by turt2live** 2020-04-28 03:32 UTC
