### ISSUE TITLE
Breadcrump / Left room stays in the breadcrump history

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riot-web#11644] opened 2019-12-11 14:37 UTC
### Description

When you leave a room, the room stays in the breadcrump history.
If you tap on it you can eventually rejoin

**Comment by turt2live** [comment] 2019-12-11 15:59
Duplicate of https://github.com/vector-im/riot-web/issues/10127

**Closed by turt2live** 2019-12-11 15:59 UTC
Labels: bug
