### ISSUE TITLE
Riot Update overwrites custom config.js

### ISSUE THREAD

**Issue by vmario89** [vector-im/riot-web#9240] opened 2019-03-21 23:32 UTC
Hi,
i recognized clicking Riot Update buttom within app works fine (if update path is set in config.js) butt would be great if the update would not overwrite the config.json. Instead it should keep the old one or ask the user if the update likes to roll out the standard/default config file.

**Comment by turt2live** [comment] 2019-03-21 23:37
Effectively a duplicate of https://github.com/vector-im/riot-web/issues/4394

**Closed by turt2live** 2019-03-21 23:37 UTC
Labels: suggestion
