### ISSUE TITLE
Something like linuxfr's norloges - the ability to permalink based on timestamp

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3575] opened 2017-04-06 13:29 UTC
So that if someone mentions a timestamp (formatted however) in a chatroom, you can click on the timestamp to jump to that point in conversation in the room.  E.g. 'Hey, what were we talking about on **April 26**?' and you click on the date and it zips you to Apr 26 2016

**Comment by lampholder** [comment] 2017-04-06 16:41
Presumably you'd implement this by:
 - generally supporting time-based permalinks
 - Riot's being responsible for digesting of any date/time matching strings into said permalinks, making any sensible assumptions about implied year, week, day etc.

**Comment by ara4n** [comment] 2017-04-06 17:16
Yup.  One nicer extension could be if the sending client also marked up 
timestamps with some metadata to make it easier for other clients to 
recognise them - e.g. `<a rel="ts://2017-04-06T17:15:18+00:00">a few 
days ago</a>` or something.  This has overlap with tagging users with 
their MXID and other desiderata.

Supporting time-based permalinks is a bit tough as time is bifurcated in 
Matrix.  But would be a really nice user feature, i think.

**Comment by aaronraimist** [comment] 2020-02-25 18:23
Duplicate of #7677

**Closed by aaronraimist** 2020-02-25 18:23 UTC
Labels: feature, needs-design, p3
