### ISSUE TITLE
Add "Show only unread" quick toggle for room list

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#14307] opened 2020-07-03 10:28 UTC
Will be good to have "Show only unread" quick toggle in room list, it exists in VK Messenger and some other, and very useful. It can be located in right of filter input styled as toggle with tooltip "Show only unread rooms".

**Comment by turt2live** [comment] 2020-07-10 03:30
Duplicate of https://github.com/vector-im/riot-web/issues/7635

**Closed by turt2live** 2020-07-10 03:30 UTC
Labels: suggestion, type:roomlist
