### ISSUE TITLE
When I type in Chinese, the characters that the keyboard typed are often lost for no reason

### ISSUE THREAD

**Issue by RealShine** [vector-im/riot-web#8694] opened 2019-02-15 09:52 UTC
### Description

When I type in Chinese, the characters that the keyboard typed are often lost for no reason. It is very difficult to input Chinese, and a word often has to be entered many times.

### Version information

For the desktop app:

- **OS**: Windows 10, 
- **Version**: 1.0.0

**Comment by jryans** [comment] 2019-02-15 11:18
Yes, sorry to hear about the trouble. The input library we use doesn't play well with input methods, unfortunately. I hope it can be fixed soon, but for now I'll mark this as a duplicate of https://github.com/vector-im/riot-web/issues/7665.

**Closed by jryans** 2019-02-15 11:18 UTC
