### ISSUE TITLE
Version 0.15.2 and 0.15.3 of riot-web: Encryption not working any longer, earlier encrypted rooms become undecryptable

### ISSUE THREAD

**Issue by chrissi55** [vector-im/riot-web#6761] opened 2018-05-18 05:29 UTC
### Description

After Upgrading my Version of riot-web: to 0.15.2 all e2e encrypted chats are undecryptable.
Program says - enforce resending keys again but when key pulling is enforced nothing happened.

Exporting and Importing Keys of another (Android) Client will re-enable all posts till point of export.

But newly send messages are again encrypted for the Linux Client.

All my devices where accepted by riot.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

@dbkr  Log: How to extract the errorlogfile? I can't find the log under /var/log/... nor /opt/riot/....  please give me a hint     

### Version information

- **Platform**: desktop!

For the web app:

- **Browser**: no webapp -> desktop
- **OS**: Linux
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Linux, Zorin OS (ubuntu)?
- **Version**: riot 0.15.2, Zorin 12.3 

Update:
I cleared the Cache and reboot ... no difference, chat stays encrypted

**Comment by dbkr** [comment] 2018-05-18 08:52
Can you fill in the rest of the fields in the bug report please? Most importantly, sent log files from both the sender and receiver.

**Comment by akontsevich** [comment] 2018-05-18 15:36
I have same issue: now can't access messages at all on any device with 0.14 or 0.15.2 versions.
**OS:** Linux openSUSE
**Browser:** FF

**Comment by akontsevich** [comment] 2018-05-19 11:58
Could we change encryption logic for simplicity and convenience:
- p2p chats - both participants have keys
- Rooms - only admin or people with enough privileges has keys and can enable/disable room encryption at any time
?

**Comment by akontsevich** [comment] 2018-05-19 12:35
>This is hardwired at the Matrix level, so not something Riot can change

Bad, need to change Matrix then :) Need to think about the users!

**Comment by t3chguy** [comment] 2018-05-19 12:36
@akontsevich its done for security;
imagine an end-to-end encrypted room with matrix.org users in, matrix.org as a server could hide the encryption state event from its users and then users in that room would start to send things into the room unencrypted, which is currently not possible as once encryption is enabled it can never be disabled in a room.

**Comment by akontsevich** [comment] 2018-05-19 12:38
Then need to keep history on admin machine.

**Comment by t3chguy** [comment] 2018-05-19 12:40
@akontsevich thats not how Matrix works, its more like email where all the servers involved in a room store it, no one owns the room.

**Comment by akontsevich** [comment] 2018-05-19 16:42
To make product people love need to make application from users point of view. Old Skype way encrypting p2p and keeping history on users machine is the best and most convenient approach for now.  Worked for years without any problem for millions of users. Matrix approach creates problems right from the start. Need to take best world practices and polish them rather reinvent the wheel.

**Comment by t3chguy** [comment] 2018-05-19 17:18
But riot and matrix are federated, not p2p.

**Comment by akontsevich** [comment] 2018-05-19 17:26
Bad, I thought servers are used only to more easier connect users. Disappointed in Riot. Encrypted history on server always easy to decrypt if necessary. Will not suggest Riot to people any more. Still no Skype alternative then. Damn!

**Comment by ara4n** [comment] 2018-05-19 21:54
we have only heard about this from two people, and haven’t seen any logs to debug (please submit them via the Submit Logs button in User Settings), so we’re still trying to assess how bad the situation is.

Have you been trying to switch back and forth between 0.14 and 0.15 desktop apps?

**Comment by ara4n** [comment] 2018-05-19 22:27
(i'm going to delete the "why don't we completely change Matrix's encryption model" comments, as they're irrelevant to this bug - feel free to open a separate spec bug over at matrix-org/matrix-doc if you like)

**Comment by ptman** [comment] 2018-05-20 07:41
From the "New issue" template:

 You can send us the app's logs via the 'Report bug'
link on the 'Settings' page. Very important for hard-to-reproduce bugs. Please
file a bug here too!

**Comment by chrissi55** [comment] 2018-05-20 11:18
Log transmitted via link -> https://github.com/vector-im/riot-web/issues/6761

**Comment by akontsevich** [comment] 2018-05-20 14:26
>You can send us the app's logs via the 'Report bug' link on the 'Settings' page.

I do not see any 'Report bug' link there. Is it exist in 0.14?

**Comment by chrissi55** [comment] 2018-05-21 05:44
@akontsevich 
In the riot desktop / web-app go to the settings (main settings) and scroll down until the E2E Encryption Keys export / import. Underneath that export / import buttons you should habe another Button for Error Reporting.
Insert the GitHub URL of this issue 
-> https://github.com/vector-im/riot-web/issues/6761

and you should be able to send a logfile

What i dislike here is the fact, that a user can't preview it's logfile before (!) it is send
Not that kind of confidence base i would prefer!

**Comment by dbkr** [comment] 2018-05-21 11:00
I have one log from this issue but I can't see anything in it that would cause problems. If anyone else is able to send logs, that would be great - see the issue template for how to do so. Logs from the sender side too would be ideal.

**Comment by akontsevich** [comment] 2018-05-21 11:08
>in the riot desktop / web-app go to the settings (main settings) and scroll down until the E2E Encryption Keys export / import. Underneath that export / import buttons you should see another button for error reporting.

I do not have either in 0.14 or 0.15 desktop. Where are they located, how to get them and upload here manually. Also I see "Export room keys" button there. Where room keys are stored in Linux/Mac/Windows, how to load them manually? May be I can find them on this PC or another?

**Comment by dbkr** [comment] 2018-05-21 13:57
Just been chatting about this with PC-Admin in #riot:matrix.org. It looks like at some point the indexeddb data got deleted, resetting the device key. I don't yet know what caused this.

Logging out and logging back in again (a third time...) made things work again, so this is a workaround if you have keys from another device you can import and export

**Comment by akontsevich** [comment] 2018-05-21 14:02
> Logging out and logging back in again (a third time...) made things work again, so this is a workaround if you have keys from another device you can import and export

Where this keys are stored?! Path?! Linux/Mac/Windows?

**Comment by dbkr** [comment] 2018-05-21 14:07
@akontsevich this one of the settings you seem to be missing somehow - I'd suggest dropping into #riot:matrix.org and someone can help figure out why you can't find these.

**Comment by akontsevich** [comment] 2018-05-21 14:09
@dbkr You are developer? You do not know? :)

**Comment by dbkr** [comment] 2018-05-21 14:10
Let's keep this for actual discussion on the bug itself please, rather than help with finding settings.

**Comment by akontsevich** [comment] 2018-05-21 14:40
@dbkr according to #riot:matrix.org history many users have this bug and unable to continue working with Riot. And people can't get desktop Riot to work. I can't web version as well. So think no help there.

**Comment by akontsevich** [comment] 2018-05-21 14:45
Hmm... I found this text in desktop version when trying to relogin:

> **Sign out**
For security, logging out will delete any end-to-end encryption keys from this browser. If you want to be able to decrypt your conversation history from future Riot sessions, please export your room keys for safe-keeping.

So seems after upgrading Riot signouts somehow and cleared all the keys. So I need always save all the keys from all rooms on every sign out? And watch for them manually all the time? What a stupid an inconvenient behaviour.

**Comment by chrissi55** [comment] 2018-05-21 14:53
> Just been chatting about this with PC-Admin in #riot:matrix.org. It looks like at some point the indexeddb data got deleted, resetting the device key. I don't yet know what caused this.

So, there is a bug, that could be reproduced? I think so ...

> Logging out and logging back in again (a third time...) made things work again, so this is a workaround if you have keys from another device you can import and export

Wouldn't that cause a new device key? And does that mean, that in the e2e chat my logged out and re-logged in device become "unknown" with yellow breakdown triangle?
I would wait until there might be another solution...

Exporting the keys / room keys is not the problem!
One export for all rooms is doing the job well but for now a little bit annoying :-)

**Comment by akontsevich** [comment] 2018-05-21 15:27
Bad you've left 0.15.2 version in web - logged-in Windows now (web version) - same issue. I've shared keys with other devices but messages still encrypted. So it is broken everywhere.

**Comment by chrissi55** [comment] 2018-05-21 15:33
> Windows now (web version) - same issue. I've shared keys with other devices but messages still encrypted. So it is broken everywhere.

That are bad news! So i hope that the admins here could  reproduce the bug as it is and mark this issue as "issue" so that others don't run into the same trap ....

@akontsevich   you should be able to send a logfile (errorlog) from your Windows client maybe?
More infos could help the developers i hope....

**Comment by akontsevich** [comment] 2018-05-21 15:46
> @akontsevich  you should be able to send a logfile (errorlog) from your Windows client maybe?

I've sent them from Windows machine - only web version have the button, so do not think it will help much.

**Comment by thomas-profitt** [comment] 2018-05-28 18:56
I'm having what sounds like the same issue.

I'm in 2 E2E rooms, both 1:1, both with the same person, on Riot Web and Riot Android.

All messages in both rooms, whether they were from me on Riot Web, the other user on Riot Desktop (Windows), or either of us on Riot Android, began show as "unable to decrypt" in Riot Web for me, but continue to show normally for me on Riot Android (and presumably for the other user's clients). When I click "Re-request encryption keys" in my Riot Web, nothing happens.

I clicked my name in the member list on Riot Web and looked at devices: my mobile shows as verified, with correct device ID. I did the same in Riot Android, and my Riot Web shows as verified with the correct ID. All proper.

Clearing my cache in Riot Web did not affect it.

I sent a message from Riot Web, and here's its E2E info modal from Riot Web (where it was sent and has a 🔒 icon) and Riot Android (where it is displayed, but has a ⚠ icon instead):
![screenshot from 2018-05-28 13-35-48](https://user-images.githubusercontent.com/13843293/40626491-8209d54c-627e-11e8-80a8-9959a6aff5f9.png)

**Comment by akontsevich** [comment] 2018-05-29 02:33
I think bug somewhere in settings saving: I switched notifications off because of electron bug, on next start they are switched on as by default. Some other settings returned to default values as well.

**Comment by richvdh** [comment] 2018-06-20 13:56
> Just been chatting about this with PC-Admin in #riot:matrix.org. It looks like at some point the indexeddb data got deleted, resetting the device key. I don't yet know what caused this.

It feels like we should close this as a duplicate of the more specific and clearer #6808.

People should be aware this is far from the only cause of "unable to decrypt" errors. #2996 is a more general bug which tries to keep track of the various reasons for it.

**Closed by richvdh** 2018-06-20 13:56 UTC
Labels: bug, major, p1, type:e2e
