### ISSUE TITLE
LeftPanel keyboard navigation often doesn't work if you use the mouse to navigate to the filter box

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12656] opened 2020-03-08 15:21 UTC
If you click on the filter box, start typing, and then try to use arrow keys to navigate the filtered LeftPanel it often doesn't work. If you navigate there via cmd/ctrl-K it gets it right however

**Comment by Infinity-Intellect** [comment] 2020-03-08 17:13
I'm new to the community and would like to work on this issue. 
I followed your steps to reproduce the issue, however I am able to navigate to a particular filtered chat room using my arrow keys. Is there any other way specific way by which I can reproduce the issue ?

**Comment by turt2live** [comment] 2020-03-09 04:40
It's possible to be a macOS specific issue. I also can't reproduce.

**Comment by aaronraimist** [comment] 2020-03-10 04:47
I haven't been able to reproduce this in either. Tried both Firefox and Chrome on macOS.

**Comment by turt2live** [comment] 2020-07-08 17:56
This is fixed in the new room list anyhow

**Closed by turt2live** 2020-07-08 17:56 UTC
Labels: cannot-reproduce, type:roomlist
