### ISSUE TITLE
Contact list / Room list only shows icons

### ISSUE THREAD

**Issue by rainerschoe** [vector-im/riot-web#14840] opened 2020-07-31 10:49 UTC
### Description

After upgrading riot-desktop to element-deskop (normal system update via Arch Linux repositories), The contact list and room list contains only Icons (No names anymore). Rest is working fine. Also when I hover over the icons I can see the names.

I am not sure if this is a feature/option or a bug. I am experiencing it as a bug.

![riot_contactlist](https://user-images.githubusercontent.com/36071440/89027330-97609d80-d32a-11ea-82ac-67e72c80501c.png)

### Steps to reproduce

Not sure how to reproduce. Only have this system to test and it appeared after doing an Arch linux system upgrade which included new Riot/Element version.
I am using own home server (not sure if this is relevant).

Logs being sent: yes/no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: Element version: 1.7.2  olm version: 3.1.3

**Comment by turt2live** [comment] 2020-07-31 11:57
Duplicate of https://github.com/vector-im/riot-web/issues/14782

**Closed by turt2live** 2020-07-31 11:57 UTC
Labels: bug, ui/ux
