### ISSUE TITLE
No way to log out if your HS is down

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6721] opened 2018-05-14 11:07 UTC
We used to have a 'logout' link at the bottom of the page with the spinner while we waited for the sync to happen. Now we have offline support, the main interface loads if it can't connect to your HS. Unfortunately, you can't open the settings page because that requires a connection to your HS, so there's no way to log out.

**Comment by lukebarnard1** [comment] 2018-05-14 12:39
This was already a problem before offline mode. E.g. your HS goes offline when you've already made it past the first spinner.

This is a duplicate of https://github.com/vector-im/riot-web/issues/2289

**Closed by lukebarnard1** 2018-05-14 12:39 UTC
