### ISSUE TITLE
Message ordering broken in some 1:1 rooms

### ISSUE THREAD

**Issue by kaiyou** [vector-im/riot-web#9691] opened 2019-05-13 06:49 UTC
### Description

Since upgrading to 1.1.0, multiple users report having problems with message ordering. I myself only noticed this in new private-message bridged rooms using different kinds of bridges.  tulir on `#riot:matrix.org` reported seing this on many 1:1 rooms.

The ordering issue could be described by : 
 - at some point, one (a user reported seing a bunch instead) of my messages keeps being displayed as the last message(s)
 - my new messages from this point are displayed in proper order, above this one
 - the other person's messages are all displayed above these

### Steps to reproduce

- Open a 1:1 conversation, chat a bit until you trigger the issue
- If the issue is not triggered after a few messages, open a new 1:1 conversation

I could only reproduce this once, it does not seem deterministic, or I could not pinpoint the exact trigger.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux (up-to-date) and Windows, both reported
- **Version**: 1.1.0

**Comment by jryans** [comment] 2019-05-13 08:22
Has anyone submitted debug logs for this issue? Those may be helpful in pinpointing the cause.

**Comment by turt2live** [comment] 2019-05-13 15:15
Duplicate of https://github.com/vector-im/riot-web/issues/9443

**Closed by turt2live** 2019-05-13 15:15 UTC
Labels: bug, 🔥 Fire 🔥
