### ISSUE TITLE
Switching keyboard layout  with Alt+Shift brings up the menu bar

### ISSUE THREAD

**Issue by eyalroz** [vector-im/riot-web#14006] opened 2020-06-12 20:58 UTC
With the desktop client, if I switch my keyboard layout with Alt+Shift (between Hebrew and English), this brings up the menu bar, moves keyboard focus to it.

This happens all the time, basically; and in both directions of the switch.

It doesn't seem to happen with the web-based client;  it also doesn't happen when I edit a previous post and switch direction within the textbox that's been opened.

### To reproduce:

* Add a Hebrew keyboard layout to your desktop 
* Make sure Alt+Shift (or at least, LeftAlt+Shift) switches between the keyboard layouts.
* Start riot-desktop
* Login and enter some room
* Type some text in one layout, then LeftAlt+Shift.

The menu bar appears and focus goes there. It shouldn't. I mean, ok, there could be another shortcut for making it visible or it could be visible always, but its shortcut should not override the keyboard layout switch.

### Version information

- **Platform**: Desktop.
- **OS**: Devuan GNU/Linux Beowulf (~= Debian Buster without systemd)
- **Desktop environment**: Cinnamon (probably doesn't matter)
- **Version**:  riot-web version: 1.6.4, olm version: 3.1.3

**Comment by t3chguy** [comment] 2020-06-12 21:20
Duplicate of https://github.com/vector-im/riot-web/issues/3871

**Closed by t3chguy** 2020-06-12 21:20 UTC
Labels: bug
