### ISSUE TITLE
Messages containing just emojis and spaces should still show large emoji

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#7698] opened 2018-11-14 10:50 UTC
### Description

If I enter the message `😀😀`, I get large emoji, but if I enter `😀 😀` then I get small emoji. I expect large emoji in both cases.

### Solution

Accept space as a valid character in an "emoji-only" message.

### Other Considerations

Accept newlines as well.

**Comment by turt2live** [comment] 2018-11-14 15:37
Duplicate of https://github.com/vector-im/riot-web/issues/4571

**Closed by turt2live** 2018-11-14 15:37 UTC
