### ISSUE TITLE
message edits/history doesn't work with partial markdown

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#13412] opened 2020-04-28 09:37 UTC
### Description

It seems when you edit a message and apply markdown to a part of the message (e.g. asef => **as**ef) the "Message edits" box doesn't open anymore. It just shows the spinner and then closes itself.

Strangely it works correctly if you change the whole message (e.g. asef => **asef**). Maybe there is some problem calculating the difference/edit?

### Steps to reproduce

- send a message (e.g. "foo bar")
- edit that message and use markdown for a substring (e.g. "foo **bar**")
- click on the little "(edited)" besides the message

The message box won't display the edit history. I'd expect it to display it just like with other edits.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.5.15

**Comment by t3chguy** [comment] 2020-04-28 09:42
Duplicate of https://github.com/vector-im/riot-web/issues/11661

**Closed by t3chguy** 2020-04-28 09:42 UTC
Labels: bug
