### ISSUE TITLE
Closing the right panel causes your scroll to jump to the bottom of the timeline

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#12623] opened 2020-03-05 14:32 UTC
Very upsetting when you're halfway through scrollback and you go to close the right panel to dive deeper into messages.

**Comment by bwindels** [comment] 2020-03-05 14:56
Duplicate of https://github.com/vector-im/riot-web/issues/9822

**Closed by bwindels** 2020-03-05 14:56 UTC
