### ISSUE TITLE
[...] context menu runs off the screen

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8761] opened 2019-02-18 15:27 UTC
Clicking on the [...] menu on a message with the right panel collapsed runs off the screen. I suspect this has always been the case, but is exacerbated by the new characterful 'End-to-end encryption' menu option. A cheap fix could be to shorten the menu option, but otherwise we might want to investigate popping the menu out of the left if there isn't enough space, like how most OS's do.

**Comment by turt2live** [comment] 2019-02-19 04:36
Duplicate of https://github.com/vector-im/riot-web/issues/3429

**Closed by turt2live** 2019-02-19 04:36 UTC
