### ISSUE TITLE
"Connectivity to the server has been lost" - still more time, even network is ok

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-web#14529] opened 2020-07-16 09:01 UTC
### Steps to reproduce
- Network is lost
- Element-desktop says "Connectivity to the server has been lost"
- same time
- network come to up state
- Element-desktop still says "Connectivity to the server has been lost" - by 3-5 minutes

I think that elements-desktop must be more quickly understand, that network already is up (I think ~5-15 seconds).
- Linux ubuntu 16.04 LTS amd64
- Elements desktop 1.7.0

**Comment by t3chguy** [comment] 2020-07-16 09:05
Do you have browser extensions like PrivacyBadger or uMatrix?

**Comment by t3chguy** [comment] 2020-07-16 09:13
Duplicate of https://github.com/vector-im/riot-web/issues/1702

**Closed by t3chguy** 2020-07-16 09:13 UTC
Labels: bug

**Comment by sl5net** [comment] 2021-01-05 17:01
i got this error toxay 21:01:05 18:01:23 and its still thery in linux but not in android.

**Comment by danger89** [comment] 2021-04-06 16:22
I also got this issue on my Linux system (Linux Mint) with Element desktop app (==element-web).  

> Connectivity to the server has been lost.
> Sent messages will be stored until your connection has returned.

My Synapse server is running and works fine on my mobile.

Really really weird! It was really unable to login, it was unable to get the login list or anything else for that matter. The only workaround was to actually **LOGOUT** and login _again_ (even clearing the cache was not enough, I tried that as well).

Root-cause: still unknown.

**Comment by remipp** [comment] 2021-04-20 08:44
(I think) I'm having the same problem with element-desktop, except for me there was no network disconnect and reboots etc. didn't fix it. It seems like my session has been deauthorized somehow, so logging out and back in should fix it, however I haven't yet backed up my encryption key. Is there any way I can backup the keys in this state? It isn't showing the startup toast and I didn't find anything poking in `.config/Element`. DevTools shows this, with the 401 repeating about every second:
![image](https://user-images.githubusercontent.com/31708910/115365324-90cdcb00-a1c4-11eb-9c4e-e57e9a0c0001.png)

**Comment by SimonBrandner** [comment] 2021-04-20 10:00
@remipp, please open a new issue

**Comment by remipp** [comment] 2021-04-20 16:04
@SimonBrandner I thought my issue was more related to this one's description (especially the most recent comment above mine) than the other one but I commented in the other one aswell now.

**Comment by skobkin** [comment] 2021-07-14 12:30
My Element Desktop on Linux can't connect at all since June, I think.

That's how it looks in the Synapse logs when I run Element Desktop on Linux:

```
2021-07-14 15:25:10,760 - synapse.handlers.presence - 348 - INFO - persist_presence_changes-6405 - Persisting 1 unpersisted presence updates
2021-07-14 15:25:14,423 - synapse.http.server - 75 - INFO - GET-198956 - <XForwardedForRequest at 0x7f6f36f30c90 method='GET' uri='/_matrix/client/r0/thirdparty/protocols' clientproto='HTTP/1.0' site=8008> SynapseError: 401 - Invalid Authorization header.
2021-07-14 15:25:14,427 - synapse.access.http.8008 - 311 - INFO - GET-198956 - <IP_removed> - 8008 - {None} Processed request: 0.004sec/0.001sec (0.003sec, 0.000sec) (0.000sec/0.000sec/0) 69B 401 "GET /_matrix/client/r0/thirdparty/protocols HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.7.31 Chrome/89.0.4389.128 Electron/12.0.11 Safari/537.36" [0 dbevts]
2021-07-14 15:25:14,595 - synapse.access.http.8008 - 311 - INFO - GET-198958 - <IP_removed> - 8008 - {None} Processed request: 0.001sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 201B 200 "GET /_matrix/client/versions HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.7.31 Chrome/89.0.4389.128 Electron/12.0.11 Safari/537.36" [0 dbevts]
2021-07-14 15:25:14,656 - synapse.http.server - 75 - INFO - GET-198960 - <XForwardedForRequest at 0x7f6f37ed6450 method='GET' uri='/_matrix/client/r0/voip/turnServer' clientproto='HTTP/1.0' site=8008> SynapseError: 401 - Invalid Authorization header.
2021-07-14 15:25:14,658 - synapse.access.http.8008 - 311 - INFO - GET-198960 - <IP_removed> - 8008 - {None} Processed request: 0.002sec/0.001sec (0.001sec, 0.000sec) (0.000sec/0.000sec/0) 69B 401 "GET /_matrix/client/r0/voip/turnServer HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.7.31 Chrome/89.0.4389.128 Electron/12.0.11 Safari/537.36" [0 dbevts]
2021-07-14 15:25:14,731 - synapse.http.server - 75 - INFO - GET-198961 - <XForwardedForRequest at 0x7f6f5c39ce10 method='GET' uri='/_matrix/client/r0/pushrules/' clientproto='HTTP/1.0' site=8008> SynapseError: 401 - Invalid Authorization header.
2021-07-14 15:25:14,732 - synapse.access.http.8008 - 311 - INFO - GET-198961 - <IP_removed> - 8008 - {None} Processed request: 0.001sec/0.000sec (0.002sec, 0.000sec) (0.000sec/0.000sec/0) 69B 401 "GET /_matrix/client/r0/pushrules/ HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.7.31 Chrome/89.0.4389.128 Electron/12.0.11 Safari/537.36" [0 dbevts]
2021-07-14 15:25:14,898 - synapse.http.server - 75 - INFO - GET-198964 - <XForwardedForRequest at 0x7f6f44aae490 method='GET' uri='/_matrix/client/r0/joined_groups' clientproto='HTTP/1.0' site=8008> SynapseError: 401 - Invalid Authorization header.
2021-07-14 15:25:14,899 - synapse.access.http.8008 - 311 - INFO - GET-198964 - <IP_removed> - 8008 - {None} Processed request: 0.001sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 69B 401 "GET /_matrix/client/r0/joined_groups HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.7.31 Chrome/89.0.4389.128 Electron/12.0.11 Safari/537.36" [0 dbevts]
2021-07-14 15:25:14,905 - synapse.http.server - 75 - INFO - GET-198965 - <XForwardedForRequest at 0x7f6f36f0ad90 method='GET' uri='/_matrix/client/r0/capabilities' clientproto='HTTP/1.0' site=8008> SynapseError: 401 - Invalid Authorization header.
2021-07-14 15:25:14,908 - synapse.access.http.8008 - 311 - INFO - GET-198965 - <IP_removed> - 8008 - {None} Processed request: 0.004sec/0.000sec (0.001sec, 0.000sec) (0.000sec/0.000sec/0) 69B 401 "GET /_matrix/client/r0/capabilities HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.7.31 Chrome/89.0.4389.128 Electron/12.0.11 Safari/537.36" [0 dbevts]
2021-07-14 15:25:16,134 - synapse.http.server - 75 - INFO - POST-198967 - <XForwardedForRequest at 0x7f6f36f30dd0 method='POST' uri='/_matrix/client/r0/rooms/!VSXjOhavOacPjgBfnT%3Amatrix.org/read_markers' clientproto='HTTP/1.0' site=8008> SynapseError: 401 - Invalid Authorization header.
2021-07-14 15:25:16,138 - synapse.access.http.8008 - 311 - INFO - POST-198967 - <IP_removed> - 8008 - {None} Processed request: 0.004sec/0.001sec (0.003sec, 0.000sec) (0.000sec/0.000sec/0) 69B 401 "POST /_matrix/client/r0/rooms/!VSXjOhavOacPjgBfnT%3Amatrix.org/read_markers HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.7.31 Chrome/89.0.4389.128 Electron/12.0.11 Safari/537.36" [0 dbevts]
2021-07-14 15:25:16,224 - synapse.access.http.8008 - 311 - INFO - GET-198969 - <IP_removed> - 8008 - {None} Processed request: 0.008sec/0.001sec (0.005sec, 0.000sec) (0.004sec/0.002sec/2) 87B 200 "GET /_matrix/client/r0/profile/%40skobkin%3Askobk.in HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.7.31 Chrome/89.0.4389.128 Electron/12.0.11 Safari/537.36" [0 dbevts]
2021-07-14 15:25:16,520 - synapse.http.server - 75 - INFO - POST-198971 - <XForwardedForRequest at 0x7f6f3727ad10 method='POST' uri='/_matrix/client/r0/publicised_groups' clientproto='HTTP/1.0' site=8008> SynapseError: 401 - Invalid Authorization header.
2021-07-14 15:25:16,523 - synapse.access.http.8008 - 311 - INFO - POST-198971 - <IP_removed> - 8008 - {None} Processed request: 0.002sec/0.001sec (0.002sec, 0.000sec) (0.000sec/0.000sec/0) 69B 401 "POST /_matrix/client/r0/publicised_groups HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.7.31 Chrome/89.0.4389.128 Electron/12.0.11 Safari/537.36" [0 dbevts]
```

**Comment by oren** [comment] 2021-09-05 01:14
I am trying to access my chatrooms via https://app.element.io and getting the same message in red. Firefox on ubuntu.

**Comment by SimonBrandner** [comment] 2021-09-05 06:04
For anyone experiencing this, please open a new issue, link to this one and send logs
