### ISSUE TITLE
"Failure to create room" on login when Riot creates a chat with riot-bot, but the homeserver has a federation whitelist

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7411] opened 2018-09-27 20:26 UTC
![image](https://user-images.githubusercontent.com/1190097/46172666-4d578e00-c261-11e8-960b-6ca958ffbf51.png)

The config for this homeserver doesn't permit it to talk to matrix.org, and therefore fails to create the room for riot-bot.

**Comment by lampholder** [comment] 2018-10-01 15:46
Yuk. I think we really need a Synapse api that exposes all of its configuration settings that a client might care about (such as whether it supports federation).

Do we get a specific 'federation denied' error mesage from Riot's attempt to automatically initiate a chat with riot bot? Anything that could let us provide a better error (or swallow it entirely in the riotbot case?)

**Comment by aaronraimist** [comment] 2018-10-27 02:03
Duplicate of #4062

Could probably just edit the title of that issue to be a little less specific as this also affects any failed invite, not just Riot bot. Currently you can reproduce by attempting to start a chat with `@tleydxdy:mt.tlebear.win`(https://github.com/matrix-org/synapse/issues/4098)

**Closed** 2018-10-27 02:04 UTC
Labels: bug, minor, p2
