### ISSUE TITLE
Resizing Riot causes a wild right panel to appear

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10156] opened 2019-06-24 15:04 UTC
With the right panel collapsed, resizing Riot from Big -> Small -> Big causes a wild member list to appear.

Have to click the member list button twice (first to enable the buttons state) to disable it.

**Comment by turt2live** [comment] 2019-12-05 23:55
Duplicate of https://github.com/vector-im/riot-web/issues/8772

**Closed by turt2live** 2019-12-05 23:55 UTC
Labels: bug, defect, p2, type:memberlist, type:rightpanel
