### ISSUE TITLE
Channels in room list take up too much space

### ISSUE THREAD

**Issue by Sancus** [vector-im/riot-web#14505] opened 2020-07-15 20:08 UTC
The amount of vertical space that the icons take up produces a channel list that requires way too much scrolling, IMO. If this is intentional, OK, but some sort of compact version would be nice. There were compact options introduced in "Appearances"->"Advanced" but they only affect the chat, not the room list.

Right now, in a full screen window I can only get about 15 channels in the list before having to scroll. This is half as much as discord, IRC, or Slack.

A good example of what I think the room list SHOULD look more like is this user style: https://github.com/dannycolin/riot-compact

**Comment by robintown** [comment] 2020-07-15 20:41
Indeed, the room icons should be smaller when message previews are disabled.

**Comment by andkit** [comment] 2020-07-15 20:52
This has actually gotten worse for me with the element ui refresh, as there are now various extra things taking up vertical space:

- a search icon
- a discover rooms icon
- Start Chat button (previously this was next to the private chats expander)
- Create Room icon (also beside expander in previous version)

Paradoxically those last two are still small + icons beside the expander in the wide (wiith labels) version of the sidebar, so the compact collapsed version actually uses *more* space :-(
I'd really prefer the collapsed sidebar to do the same again as well

As for the search and discover buttons, are they really needed in the collapsed sidebar? Clicking search annoyingly expands the sidebar anyway, so can't they both be shown only in the expanded sidebar? Or at least make the search icon a bit smaller and put both of them in one row.

And I too would second smaller icons similar to those in the linked user style.

**Comment by turt2live** [comment] 2020-07-15 21:15
Duplicate of https://github.com/vector-im/riot-web/issues/14099

**Closed by turt2live** 2020-07-15 21:15 UTC
Labels: bug, ui/ux
