### ISSUE TITLE
Key backup prompt appeared even though key backup is already set up

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#10776] opened 2019-09-06 10:21 UTC
### Description

I switched to a room and saw the key backup prompt, which made me think my backup might've been deleted somehow. I went into settings to see that it instead is still there and fine, and when closing settings I saw that the prompt was now gone.

Logs being sent: yes

### Version information

- **Platform**: web
- **Browser**: Firefox v71a
- **OS**: Debian Buster
- **URL**: riot.im/develop

**Comment by wrapper** [comment] 2019-10-22 05:08
+1 I'm getting the key backup prompt on various rooms despite having enabled it multiple times on the same room / device.

**Comment by uhoreg** [comment] 2019-11-18 04:00
Anoa's problem sounds like https://github.com/vector-im/riot-web/issues/9990.  wrapper's problem sounds different as it's persistent.

**Comment by jryans** [comment] 2020-04-29 16:46
Yes, this sounds like a duplicate of https://github.com/vector-im/riot-web/issues/9990.

**Closed by jryans** 2020-04-29 16:46 UTC
Labels: bug, feature:e2e-key-backup
