### ISSUE TITLE
context menu option to join invites from roomtile's context menu as well as reject

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5917] opened 2018-01-04 10:59 UTC

**Comment by t3chguy** [comment] 2018-01-04 12:10
All the join code is in roomView
I'll see about moving it to MatrixChat and hooking it over dispatch

**Comment by turt2live** [comment] 2018-01-04 15:59
Duplicate of https://github.com/vector-im/riot-web/issues/5271

**Comment by t3chguy** [comment] 2018-01-04 16:01
Yup

**Closed by t3chguy** 2018-01-04 16:01 UTC
