### ISSUE TITLE
[Labs: Custom user status] Changing status generate too much PUT events that will rate limited

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#10716] opened 2019-09-01 21:15 UTC
On changing custom user status string event in Riot widget, Riot will generate mass PUT events to each joined room like `_matrix/client/r0/rooms/!GmeRxiaTmtSzdSQsrE%3Acalculate-linux.org/state/im.vector.user_status/%40murz%3Aru-matrix.org`. 

So after some success queries, other queries will rate limited on server side and failed, and seems not retried. I think we need apply rate limiting to them on Riot side?

**Comment by turt2live** [comment] 2019-09-01 22:26
Duplicate of https://github.com/vector-im/riot-web/issues/7931

**Closed by turt2live** 2019-09-01 22:26 UTC
Labels: bug
