### ISSUE TITLE
Automatically being added to room I left before

### ISSUE THREAD

**Issue by schmittlauch** [vector-im/riot-web#5644] opened 2017-11-18 19:25 UTC
### Description

A while ago I used to be a member of the #riot:matrix.org room (back when the app was still called vector), but I left it already some months ago. Since then I've been re-added multiple times, which is quite annoying because of the many notifications I get from such a busy room.

### Steps to reproduce

This bug is a bit hard to reproduce. In my case I can only describe what I did:

- enter the room #riot:matrix.org (this so far only happened to me with this room)
- stay there for a while
- leave the room
- \<much time can pass here\>
- suddenly see yourself being a member again and getting notifcations

Log: sent on Sa 18. Nov 19:21:34 UTC 2017

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 56.0
- **OS**: Gentoo linux x86_64
- **URL**: riot.im/app, currently at version 0.13.1 with matrix-react-sdk 0.11.1

**Comment by richvdh** [comment] 2017-11-18 19:33
This is caused by https://github.com/matrix-org/synapse/issues/1953

**Comment by schmittlauch** [comment] 2017-11-18 19:39
Good to know. I never had these problems with other clients, but as I'm using Riot far more often than e.g. Quaternion the probability for seeing that here is much higher.

**Comment by uhoreg** [comment] 2017-11-19 01:02
It is probably coincidental that you're seeing it more as you're using Riot more, since the issue is a server-side issue.

**Comment by turt2live** [comment] 2019-07-16 06:06
Closing in favour of the well-known "State Resets" issue. The answer nowadays is to upgrade the room to v2 or higher.

**Closed by turt2live** 2019-07-16 06:06 UTC
Labels: bug, major, p1
