### ISSUE TITLE
[Feature Request] Save/Bookmark messages

### ISSUE THREAD

**Issue by poulad** [vector-im/riot-web#8119] opened 2019-01-14 02:30 UTC
Hi

Users can currently copy the link to a message to store a reference to it.

It would be great if Riot offers a bookmark :star: option, e.g. in the message actions menu, so the user has a quick way to do so.

There could also be a pseudo-room __Saved Messages__ in order to see all the bookmarked/saved messages.

**Comment by aaronraimist** [comment] 2019-01-14 02:32
Duplicate of #2938, please put a thumbs up on that issue instead :)

**Closed** 2019-01-14 02:33 UTC
