### ISSUE TITLE
Remember collapsing state of the left panel

### ISSUE THREAD

**Issue by jaragunde** [vector-im/riot-web#2689] opened 2016-12-05 08:56 UTC
When you open the web client, all the categories in the left panel are expanded excepting "historical". It would be great if it could remember which ones are collapsed on exit and replicate that state when the client is open again.

**Comment by 4nd3r** [comment] 2017-05-25 05:05
not only left panel, but also right one.

**Comment by t3chguy** [comment] 2017-08-16 17:33
Related to #https://github.com/vector-im/riot-web/issues/2124

**Comment by turt2live** [comment] 2017-10-13 20:47
I feel this is actually a duplicate of #2124, although this issue has more info.

**Comment by jryans** [comment] 2019-01-04 23:59
This was fixed on experimental by https://github.com/matrix-org/matrix-react-sdk/pull/2297, and it's planned to move through the release process in the coming weeks.

**Closed by jryans** 2019-01-04 23:59 UTC
Labels: feature, minor, p2, type:roomlist, ui/ux

**Comment by jaragunde** [comment] 2019-01-07 17:17
Thanks!
