### ISSUE TITLE
Can't accept or clear an invite

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#13851] opened 2020-05-28 20:48 UTC
Yay, someone loves me:
<img width="980" alt="Screenshot 2020-05-28 at 21 45 49" src="https://user-images.githubusercontent.com/4626865/83192138-0c4a0800-a12d-11ea-9c39-f812bf73c9c2.png">

Boo:
<img width="780" alt="Screenshot 2020-05-28 at 21 45 55" src="https://user-images.githubusercontent.com/4626865/83192158-110ebc00-a12d-11ea-8f98-6e011a8587f6.png">

 I have 404's and 403's in my console. If a user accepts an invite which fails should the client just clear the invite?

**Comment by turt2live** [comment] 2020-05-28 20:49
Duplicate of https://github.com/vector-im/riot-web/issues/3743 (or one of the other many stuck invite issues).

**Closed** 2020-05-28 20:56 UTC
