### ISSUE TITLE
Red Mention Markup leaks into annotations.

### ISSUE THREAD

**Issue by NotAFile** [vector-im/riot-web#9810] opened 2019-05-22 20:14 UTC
### Description

This is another one for https://github.com/vector-im/riot-web/issues/9070.

I've also noticed that this markup applies to the "toolbar". However, since the emojis are colored, this is no longer visible.

### Steps to reproduce

- Add annotation to message that mentions you
- It becomes red

The markup should only highlight the message.

Log: not sent    

riot-web?

![image](https://user-images.githubusercontent.com/5447747/58205163-37aa4380-7cde-11e9-8731-b14c9bb5dc38.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 69
- **OS**: Fedora Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment] 2019-05-22 20:16
Duplicate of https://github.com/vector-im/riot-web/issues/9697

**Closed by turt2live** 2019-05-22 20:16 UTC
Labels: bug, ui/ux
