### ISSUE TITLE
Historical rooms list isn't working

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11798] opened 2020-01-08 11:22 UTC
I only have 2 entries in it. Historical historical rooms seem to be lost

**Comment by turt2live** [comment] 2020-01-08 15:55
Duplicate of https://github.com/vector-im/riot-web/issues/9129 or one of the other 30 historical room issues. It needs product oversight to figure out what it's supposed to do haven bitrotten beyond recognition.

**Closed by turt2live** 2020-01-08 15:55 UTC
