### ISSUE TITLE
Green outline around Disinvite button

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9096] opened 2019-03-09 19:05 UTC
![image](https://user-images.githubusercontent.com/1342360/54075992-d9082880-429d-11e9-8c52-9353f3e39707.png)

### Description

The disinvite button (when you're removing the invite of a user to a room) the "disinvite" button has a green outline around it even though it's a red/danger button.

### Steps to reproduce

- Invite a user to a room
- Remove their invite
- See the red Disinvite button has a green outline

Describe how what happens differs from what you expected.

Log: not sent    

### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: private riot.im/develop

**Comment by t3chguy** [comment] 2019-09-11 10:02
Cannot reproduce:
![image](https://user-images.githubusercontent.com/2403652/64688140-a4ab3a00-d483-11e9-9f31-eff9cd2ae772.png)

**Comment by t3chguy** [comment] 2019-09-11 10:02
Closing presumably fixed incidentally

**Closed by t3chguy** 2019-09-11 10:02 UTC
Labels: bug, cosmetic, major, p1, type:theming, ui/ux

**Comment by anoadragon453** [comment] 2019-09-11 12:26
Yes :slightly_smiling_face: Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3269
