### ISSUE TITLE
Entering long text without any whitespace breaks layout

### ISSUE THREAD

**Issue by NotAFile** [vector-im/riot-web#6890] opened 2018-06-16 16:50 UTC
### Description

When entering a very long text without any whitespace, riot's layout breaks

### Steps to reproduce

- open chat
- enter aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
- stuff breaks

I'd expect it to wrap if the line is too long

Log: not sent    

### Version information

- **Platform**: web
- **Browser**: Firefox? nightly
- **OS**: Fedora
- **URL**: riot.im/app

**Comment by turt2live** [comment] 2018-06-16 16:51
Do you have a screenshot of the issue? It seems fine over here:
![image](https://user-images.githubusercontent.com/1190097/41500657-3540d1f0-7153-11e8-9db8-44d5cf9accda.png)

**Comment by t3chguy** [comment] 2018-06-16 16:51
wraps fine here
![image](https://user-images.githubusercontent.com/2403652/41500656-e1697740-718d-11e8-9e2c-18053ce62204.png)

**Comment by NotAFile** [comment] 2018-06-16 17:20
Here's how it looks for me, on both /develop and /app 

![image](https://user-images.githubusercontent.com/5447747/41500870-47d4ba88-719a-11e8-8391-bedf5c07c9a5.png)

**Comment by lampholder** [comment] 2018-06-18 09:29
Seems to be a firefox issue - my Chrome is fine but my Firefox (60.0.something) shows the same failure mode.

**Comment by t3chguy** [comment] 2020-03-24 20:45
Is this still an issue for you in the new composer?

**Comment by turt2live** [comment] 2020-03-24 20:46
This is a duplicate of another issue that you closed @t3chguy, so probably not.

**Closed by turt2live** 2020-03-24 20:46 UTC
Labels: bug, minor, p2, platform specific, type:old-composer
