### ISSUE TITLE
Make image lightboxes display images in landscape

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#11092] opened 2019-10-08 17:38 UTC
Currently the '2 column' design with download buttons & metadata on the right effectively means we display images in portrait, whereas we should optimise for displaying images in landscape on desktop.

**Comment by turt2live** [comment] 2019-10-08 18:39
effectively a duplicate of https://github.com/vector-im/riot-web/issues/3638

**Closed by turt2live** 2019-10-08 18:39 UTC
