### ISSUE TITLE
The x to clear the channel filter doesn't work

### ISSUE THREAD

**Issue by folsen** [vector-im/riot-web#10875] opened 2019-09-16 14:40 UTC
![image](https://user-images.githubusercontent.com/8249/64967198-63aa8f80-d8a0-11e9-93e6-11444758cad6.png)

### Description

The x to clear the channel filter doesn't work.

### Steps to reproduce

- Click filter
- Enter text
- Try to click x to clear text
- See nothing happen

### Version information
- **Platform**: web
- **Browser**: Firefox Developer Edition 70.0b6
- **OS**: macOS
- **URL**: riot.im/app

**Comment by turt2live** [comment] 2019-09-16 14:44
Duplicate of https://github.com/vector-im/riot-web/issues/10857 (will be fixed in the imminent release)

**Closed by turt2live** 2019-09-16 14:44 UTC
Labels: bug, ui/ux
