### ISSUE TITLE
Switching from Dark theme to light theme leaves some elements black

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5593] opened 2017-11-14 15:08 UTC
### Description

Switching from Dark theme to light theme leaves some elements black

### Steps to reproduce

- Switch to dark theme
- Switch to light theme

![image](https://user-images.githubusercontent.com/62835/32787077-f16573fa-c955-11e7-8776-b7d0dfae33a2.png)

### Version information

Riot web a7a9433ef9a4-react-b58514f42730-js-7a59579dcdec on Firefox 52.4.0

**Comment by turt2live** [comment] 2017-11-14 16:06
Duplicate of https://github.com/vector-im/riot-web/issues/5583

**Comment by pafcu** [comment] 2017-11-14 16:11
Unlikey #5583 as that was fixed, while this is still a problem. Also maybe not #5589 because it specifically mentions SVGs, while here SVGs seem unaffected and this occurs after theme change, not "business as usual"

**Comment by ara4n** [comment] 2017-11-15 01:02
whatever this was, it's fixed now - at least in FF 57 and Chrome 62.

**Closed by ara4n** 2017-11-15 01:02 UTC
