### ISSUE TITLE
Uploaded videos aren't playable afterwards

### ISSUE THREAD

**Issue by jomat** [vector-im/riot-web#11764] opened 2020-01-03 14:33 UTC
### Description

Uploading a video results in a download link instead of an embedded video. Middle click opens and plays the video in a new tab.

### Steps to reproduce

- Upload video

![YWUqViLIYAoYJKTqUgvRNtDm](https://user-images.githubusercontent.com/381286/71728436-f7df3900-2e34-11ea-871d-a50d33713966.png)

Logs being sent: yes

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 70.0.1
- **OS**: Alpine Linux
- **URL**: riot.asra.gr v1.5.6

**Comment by jomat** [comment] 2020-01-03 14:34
![image](https://user-images.githubusercontent.com/381286/71728858-31647400-2e36-11ea-907a-1d09789c0a26.png)

**Comment by turt2live** [comment] 2020-01-03 17:20
This is probably a duplicate of https://github.com/vector-im/riot-web/issues/7069

**Closed by turt2live** 2020-01-03 17:20 UTC
Labels: bug, ui/ux

**Comment by jomat** [comment] 2020-01-03 18:13
No.
I have the images issue sometimes on slow connections.

But I wasn't able to upload small videos (see the size in the screenshot!) for a year or so. And my private internet connection has 50 mbps upstream. And other users are also complaining about this issue alot!

Feel free to try it yourself before closing this issue. Both, Riot and HS registration are publicly available.

**Comment by jomat** [comment] 2020-01-05 13:40
Found and resolved the problem, wasn't related to #7069. Also solved another problem which looked like #11418 despite it affected all videos (again) and thus didn't have the same causes probably. I didn't open an issue as it would have been closed as duplicate anyways :-(

Both problems were my fault and not caused by riot, no further action needed.

**Comment by ara4n** [comment] 2020-01-05 14:58
can you say what the fault was on your side, in case others make the same mistake? (to avoid  https://xkcd.com/979/)

**Comment by t3chguy** [comment] 2020-01-05 15:11
@ara4n it was a CSP misconfiguration
