### ISSUE TITLE
Home button in topleftmenu is absent?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8494] opened 2019-02-09 14:09 UTC

**Comment by jryans** [comment] 2019-02-09 18:00
At the moment, a home button is only shown in the top left menu if a home page is configured. Default Riot on /develop currently only sets a welcome page but no home page, so no home button is displayed there.

**Comment by jryans** [comment] 2019-02-09 18:01
I'll close this since I believe it's working as intended. Maybe I'm missing something though, so please reopen if that's the case.

**Closed by jryans** 2019-02-09 18:01 UTC

**Comment by afranke** [comment] 2019-02-10 09:58
> a home button is only shown in the top left menu if a home page is configured

Hmmm ok, fair enough. I have no idea how one would do that, though.

**Comment by jryans** [comment] 2019-02-11 09:31
> I have no idea how one would do that, though.

Sure, that's fair, as we haven't documented it. I submitted https://github.com/vector-im/riot-web/pull/8514 to describe it in the README.
