### ISSUE TITLE
matrix.to links don't work when clicked a 2nd time

### ISSUE THREAD

**Issue by Kegsay** [vector-im/riot-web#13004] opened 2020-04-02 15:12 UTC
- Go to a room
- Make some messages
- Make a matrix.to link to earlier messages
- Click it. Rejoice! It works.
- Scroll down back to the matrix.to link.
- Click it. Sadface. It doesn't work.

Probably because there is no fragment change happening, so callbacks don't fire the second time. Swapping rooms then doing it again makes it work.

**Comment by t3chguy** [comment] 2020-04-02 15:15
I am 100% sure this is a duplicate but cannot find it :'(

**Comment by turt2live** [comment] 2020-04-02 15:44
Duplicate of https://github.com/vector-im/riot-web/issues/2903

**Closed by turt2live** 2020-04-02 15:44 UTC
Labels: bug
