### ISSUE TITLE
Hide the verification events with no rendered text

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13523] opened 2020-05-05 21:02 UTC
Currently we show blank lines, which is confusing and distracting at best

**Comment by turt2live** [comment] 2020-05-05 21:06
this is a suggebug because it could be either.

**Comment by turt2live** [comment] 2020-05-05 21:19
also suppress the notification badges

**Comment by bwindels** [comment] 2020-05-06 08:49
Related/dupe of https://github.com/vector-im/riot-web/issues/11993

**Comment by bwindels** [comment] 2020-05-06 09:12
> also suppress the notification badges

What do you mean by this? Do the verification request events create notifications for you? Is this when receiving them or when opening the app and it loads the previously received ones from cache?

**Comment by turt2live** [comment] 2020-05-06 16:58
It creates notifications for everyone by default - the room will appear read (not bold) but still have a grey badge. This is because by default the notifications are 'all messages' and the verification messages are `m.room.message` events.

Unless you click or somehow trigger a read receipt, the notifications will be shown.

**Closed** 2020-06-03 16:10 UTC
Labels: bug, feature:e2e-cross-signing, phase:4, story:2, story:e2ee-priority:44, suggestion
