### ISSUE TITLE
How to disable identity server?

### ISSUE THREAD

**Issue by rugk** [vector-im/riot-web#6157] opened 2018-02-15 13:01 UTC
When I edit the `config.json` I see `default_is_url` is set to `https://vector.im`. Now I do not want to use an identity server (by default), so how can I disable that?

I tried to set it to an empty string (`""`) or `null`, but in both cases it is still pre-filled in riot-web. So how can I just don't use it?

**Comment by t3chguy** [comment] 2018-02-15 14:23
Duplicate of https://github.com/vector-im/riot-web/issues/5921

**Closed by t3chguy** 2018-02-15 14:23 UTC
