### ISSUE TITLE
If you start your message with an emoji, newlines get lost

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6648] opened 2018-05-01 13:15 UTC
To reproduce, use the editor in markdown mode, and enter this beautiful haiku:

:disappointed: start messages with
emoji
no new lines

**Comment by t3chguy** [comment] 2018-05-01 13:33
Duplicate of https://github.com/vector-im/riot-web/issues/6523

**Closed by t3chguy** 2018-05-01 13:33 UTC
