### ISSUE TITLE
Make the application proxy/Tor friendly

### ISSUE THREAD

**Issue by 35609902357** [vector-im/riot-web#12963] opened 2020-03-31 15:26 UTC
Add proxy settings, and even better if in the proxy settings a pre-built generic Tor option is available which automatically sets 127.0.0.1:9050 as proxy, before the login prompt.

The Tor options should include a failsafe mechanism to automatically block leaks (for example block WebRTC audio/video calls as they would leak the real IP address)

**Comment by turt2live** [comment] 2020-03-31 15:27
Duplicate of https://github.com/vector-im/riot-web/issues/3320

**Closed by turt2live** 2020-03-31 15:27 UTC
Labels: suggestion
