### ISSUE TITLE
Encryption breaks when disk is full

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/riot-web#10430] opened 2019-07-27 11:54 UTC
### Description

E2EE session is killed when disk runs out of storage.
Error is displayed in E2EE rooms in riot as InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase'

Probably related to/dupe of #4014.

### Steps to reproduce

- run riot desktop
- join e2ee room
- fill your storage device (in this case C: on Windows 7)

Log: sent

brb verifying the 30 e2e devices... _really_ looking forward to Xsigning...

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows 7 x64
- **Version**: 1.3.0

**Comment by turt2live** [comment] 2019-07-27 18:42
Duplicate of https://github.com/vector-im/riot-web/issues/4014

(sorry)

**Closed by turt2live** 2019-07-27 18:42 UTC
