### ISSUE TITLE
Create option to move rooms with unread messages to the top of the favorites panel

### ISSUE THREAD

**Issue by Bortseb** [vector-im/riot-web#13948] opened 2020-06-07 15:46 UTC
**Is your suggestion related to a problem? Please describe.**
Currently, rooms in the favorites section are ordered by the time that I favorited them (seemingly). Also, depending on what ratio I divide the Favorites/Direct Messages/Rooms sections into, certain rooms will be hidden at the bottom of the favorites panel and would need me to scroll to look there to see them. (Another slight problem, though sort of unrealted to this issue, is that the different between a read and an unread channel is hard to visually distinguish because the only difference is the bolding of text, which isn't clear enough to my eye.)

**Describe the solution you'd like**
I suggest enabling the favorites section to be sorted by other parameters, but more importantly to enable the option to have rooms with unread messages in them moved to the top of the list, which is already what happens in the "Rooms" panel, just below favorites and DMs.

**Comment by t3chguy** [comment] 2020-06-07 17:09
Duplicate of https://github.com/vector-im/riot-web/issues/4484

**Closed by t3chguy** 2020-06-07 17:09 UTC
Labels: suggestion
