### ISSUE TITLE
Nag users to clean up their devices

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12913] opened 2020-03-28 14:57 UTC
If folks have got into the habit of constantly logging back in and creating new devices, we should encourage them to clean up their old devices, otherwise E2EE is going to get very upset

**Comment by aaronraimist** [comment] 2020-03-28 16:11
Duplicate of https://github.com/vector-im/riot-web/issues/2154

**Closed by aaronraimist** 2020-03-28 16:11 UTC
