### ISSUE TITLE
Message menu go past the screen limit

### ISSUE THREAD

**Issue by erdnaxeli** [vector-im/riot-web#4875] opened 2017-08-24 23:26 UTC
### Description

The menu on a message (the 3 dots) can pass by the screen border.

### Steps to reproduce

- click on the menu of the last message of a room

The menu can sometime go outside the screen. See attached screen shot.

![2017-08-25-011608_1320x1041_scrot](https://user-images.githubusercontent.com/479441/29693097-fb0c6cc2-8933-11e7-8eb0-359b5af4dd59.png)

The "Source URL" entry on the menu is not visible.

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 50.0.2
- **OS**: Debian sid
- **URL**: private, v0.12.2

**Comment by turt2live** [comment] 2017-08-25 00:35
Duplicate of #3429

**Closed** 2017-08-25 06:33 UTC
