### ISSUE TITLE
Soft-crash while previewing a room

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12805] opened 2020-03-20 10:29 UTC
Rageshake at https://github.com/matrix-org/riot-web-rageshakes/issues/2428
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at bs (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2262960)
    at bc (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2281880)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2302960)
    at zr (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2228081)
    at vc (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2279767)
    at ic (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2270129)
    at https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2228372
    at t.unstable_runWithPriority (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2302960)
    at zr (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2228081)
    at $r (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2228317)
2020-03-19T13:40:33.671Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at bs (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2262960)
    at bc (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2281880)
    at t.unstable_runWithPriority (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2302960)
    at zr (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2228081)
    at vc (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2279767)
    at ic (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2270129)
    at https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2228372
    at t.unstable_runWithPriority (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2302960)
    at zr (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2228081)
    at $r (https://riot.im/app/bundles/48795db129c835dd0ea9/bundle.js:2:2228317)
2020-03-19T13:40:33.671Z E The above error occured while React was rendering the following components: 
    in h3
    in div
    in div
    in RoomPreviewBar
    in yc
    in div
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in yc
    in MatrixChat
```

**Comment by turt2live** [comment] 2020-03-20 15:48
Duplicate of https://github.com/vector-im/riot-web/issues/11793

**Closed by turt2live** 2020-03-20 15:48 UTC
Labels: bug, p1, react-soft-crash
