### ISSUE TITLE
Text for display name change event uses new display name

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6092] opened 2018-02-05 16:11 UTC
A display name change notification looks like "New Bob changed their display name from Bob to New Bob" which is surely nonsensical as well as redundant since we always knew him as Bob before, and now he's called New Bob.

I'd have thought it should be, "Bob changed his display name to New Bob".

**Comment by t3chguy** [comment] 2018-02-05 16:18
+1000000

**Comment by t3chguy** [comment] 2018-02-05 16:19
Duplicate of https://github.com/vector-im/riot-web/issues/5171 though
https://github.com/vector-im/riot-web/issues/5171#issuecomment-341943727 is exactly your suggestion

**Closed by t3chguy** 2018-02-05 16:19 UTC
