### ISSUE TITLE
Desktop needs a way to open files rather than just save them

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14245] opened 2020-06-29 13:47 UTC
I'm getting very bored scrabbling around in my `~/Downloads` every time i want to view a file someone's sent me - e.g. a PDF

**Comment by t3chguy** [comment] 2020-06-29 14:34
Duplicate of https://github.com/vector-im/riot-web/issues/14171

**Closed by t3chguy** 2020-06-29 14:34 UTC
