### ISSUE TITLE
Editing as message breaks the bullets hierarchy

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#10041] opened 2019-06-13 11:37 UTC
I was applying manual bullets to a long list of existing text, including 2 and 3 level deep ones. Fat fingers meant I sent the message before it was finished, so edited it and then the hierarchy was gone

**Comment by bwindels** [comment] 2019-06-13 11:40
Oh, yeah, the html > md converter for the editing editor doesn't prepend whitespace yet to list items depending on the nesting level.

**Comment by jryans** [comment] 2019-06-17 10:03
@bwindels Is this a duplicate of https://github.com/vector-im/riot-web/issues/9859?

**Closed** 2019-06-21 10:55 UTC
Labels: bug, feature:aggregations, feature:message-editing, p1, type:new-composer
