### ISSUE TITLE
[Feature Request] Drag & Drop URLs/Images from browser to chat

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#6000] opened 2018-01-18 01:33 UTC
Unsure if this is feasible, but I would like it if I could drag & drop a URL or image in a tab from a browser right into the chat message field. Whether this is web/desktop. But I'm not sure if this is actually feasible or not. Is it?

Drag & Drop could be either paste the text, or upload the image to the channel (that'd be cool too!).

**Comment by turt2live** [comment] 2018-01-18 01:37
Duplicate of https://github.com/vector-im/riot-web/issues/3015

**Comment by BloodyIron** [comment] 2018-01-18 01:42
@turt2live ack! Sorry about that :(

**Closed** 2018-01-18 01:42 UTC
