### ISSUE TITLE
"Explore rooms" window breaks with Synapse 1.7.0

### ISSUE THREAD

**Issue by JonahAragon** [vector-im/riot-web#11665] opened 2019-12-13 23:28 UTC
### Description

Querying a server that does not share their room directory with unauthenticated users or federated servers by default shows "Riot failed to get the public room list. Internal server error". **This is obviously expected** (although I do think the error could be nicer)**, *however***, after doing so when you switch back to a server that does share their room directory, the window does not load the results as expected, but stays stuck on the error message without refreshing.

### Steps to reproduce

- Open "Explore Rooms"
- Query directory of a server that does not share public info, such as `privacytools.io` (of course, don't do this from a user on the `privacytools.io` server itself)
- Query the directory of a server that does share public info, such as `matrix.org`

Riot will fail to retrieve the room directory of matrix.org's server.

Logs being sent: no

<img width="738" alt="image" src="https://user-images.githubusercontent.com/3637842/70838326-4e74cc80-1dcd-11ea-963d-35a7e6341d7e.png">

👍 

<img width="739" alt="image" src="https://user-images.githubusercontent.com/3637842/70838333-53d21700-1dcd-11ea-8654-5cdbfc6c43db.png">

👎 

### Version information

- **Platform**: Web and Desktop

For the web app:

- **Browser**: Chrome
- **OS**: Windows
- **URL**: riot.im/app

For the desktop app:

- **OS**: macOS
- **Version**: 1.5.6

**Comment by turt2live** [comment] 2019-12-14 01:31
Duplicate of https://github.com/vector-im/riot-web/issues/7792

**Comment by turt2live** [comment] 2019-12-15 05:31
#7792 is the wrong directory, sorry. Looks like this isn't a duplicate of anything at the moment - it has been known for a while though.

**Closed** 2019-12-17 15:07 UTC
Labels: bug, p1, type:roomdirectory
