### ISSUE TITLE
Can't get rid of invitations from servers that no longer exist

### ISSUE THREAD

**Issue by peoro** [vector-im/riot-web#8943] opened 2019-02-25 21:04 UTC
I was invited to join a room by a user on a different server.
The server is no longer online, and I cannot get rid of the invitation.

Clicking on `accept` gives a "No known servers" error.
Clicking on `decline` gives a "Not a known room" error.

**Comment by t3chguy** [comment] 2019-05-10 20:00
For the record, decline followed by a `Clear Cache & Reload` from Settings is the way to work around this Synapse bug for now.

**Comment by t3chguy** [comment] 2019-08-13 16:43
Closing as duplicate of https://github.com/vector-im/riot-web/issues/4225

**Closed by t3chguy** 2019-08-13 16:43 UTC
Labels: bug, major, p1, stuck-invite
