### ISSUE TITLE
Line break after emoji is not displayed

### ISSUE THREAD

**Issue by MazeChaZer** [vector-im/riot-web#6559] opened 2018-04-19 12:08 UTC
Somehow line breaks after emojis get swallowed:

![screenshot_20180419_135953](https://user-images.githubusercontent.com/2766101/38990307-fd6c28e8-43d9-11e8-88bb-48e4f821b280.png)

Source code for the messages above:

```json
  "content": {
    "body": "Test 😁\nasdf 😂",
    "msgtype": "m.text"
  },
```

```json
  "content": {
    "body": "Test\nasdf",
    "msgtype": "m.text"
  },
```

### Version information

- **Platform**: Dektop
- **OS**: Arch Linux
- **Version**: 0.14.1

**Comment by t3chguy** [comment] 2018-04-19 12:10
Duplicate of https://github.com/vector-im/riot-web/issues/6523

**Closed by t3chguy** 2018-04-19 12:10 UTC
