### ISSUE TITLE
Deletion of messages in encrypted (or any other) chat/room

### ISSUE THREAD

**Issue by johnstonesnow** [vector-im/riot-web#10276] opened 2019-07-06 16:14 UTC
I should preface this by saying I am NOT a programmer. It seems more and more that Matrix, as wonderful as it is, is only really usable for programmers and dev types. 

I would like to delete all my messages sent in Riot client to a certain other user, we were chatting in a 1-1 encrypted chat. I can delete a message individually from all devices, great! But I cant see any way to do it in bulk. Please could someone advise IF this can be done, and if not, take this as a feature request.

(If there any cheats/workarounds, such as deletion of my entire account, please say, as i could do that, my account is very new and i can just create another)

thanks

**Comment by t3chguy** [comment] 2019-07-07 08:47
for now you can use https://github.com/xwiki-labs/matrix-stfu
Closing in favour of https://github.com/vector-im/riot-web/issues/5885

**Closed by t3chguy** 2019-07-07 08:47 UTC
Labels: suggestion

**Comment by johnstonesnow** [comment] 2019-07-07 09:40
Why did you close this?
No, for now I can NOT use STFU. I am not a programmer. I have no idea where config files are, how to edit them, or indeed what OS you are referring to in that stfu thing. I take it you have no other advice, except 'become a programmer and hand code the feature yourself'?

**Comment by t3chguy** [comment] 2019-07-07 09:40
I closed it as it is a duplicate of https://github.com/vector-im/riot-web/issues/5885

**Comment by t3chguy** [comment] 2019-07-07 09:41
You asked for 

> (If there any cheats/workarounds, such as deletion of my entire account, please say, as i could do that, my account is very new and i can just create another)

So I provided you with matrix-stfu

**Comment by johnstonesnow** [comment] 2019-07-07 09:50
Yes, I also said I am no programmer. I dont see how it;s a duplicate, but I can barely understand thse github threads. I think the answer is..... there is no way to delete messages in bulk, at least not without custom coding. Will that be a feature in future?

**Comment by t3chguy** [comment] 2019-07-07 09:58
Yes, read the description of #5885:

> It could be as simple as 'redact all messages from this user' for now.

**Comment by johnstonesnow** [comment] 2019-07-07 13:26
'redact all messages from this user' - That sounds like something a sysadmin/room administrator would do. Doesnt sound like a "delete all MY messages" option. 

Do you know if deleting my account will offer an option to remove all posts by my username, or not?

**Comment by t3chguy** [comment] 2019-07-07 14:33
Right but in a 1-1 chat everyone is a room administrator. So it does apply for a delete all my messages in your original query

**Comment by johnstonesnow** [comment] 2019-07-07 14:47
Do you know if deleting my account will offer an option to remove all posts by my username, or not?

**Comment by t3chguy** [comment] 2019-07-07 18:10
You can request a GDPR erasure when deactivating your account, but like with email it will only delete your copy of your messages, other copies belong to those users/servers

**Comment by johnstonesnow** [comment] 2019-07-07 18:24
Hmm, I dont know much about code, but I know a bit about GDPR and that sounds like a hornet's nest! Does Matrix confer the rights and responsibilities of "data processors" onto all its users, and all server managers?! I would think deletion of personal data needs to be a function that at least a room admin can accomplish when necessary, I can see legal wranglings over GDPR at some point, hopefully it would be ruled to not apply, but I doubt it given the past rulings on it. Even SKYPE (spit) allows deletion of all data (if one believes the word of a monkey at MS, which I dont!)

**Comment by ara4n** [comment] 2019-07-07 19:18
You have to think of Matrix as being like email rather something like Skype. If I request gdpr erasure from my mail server, i don’t expect every email i ever sent to somehow get magically deleted, nor even for my emails to suddenly disappear from the email inboxes of other users on the same server. So too for Matrix. The privacy policy as per https://matrix.org/legal tries to make this abundantly clear.

That said, we do provide a redaction button, and we could provide a bulk redaction function as per #5885 too, although it would be very prone to abuse, which is why we have not prioritised it. But based on the legal advice we’ve received it is not a prerequisite for gdpr compliance.

**Comment by adalvigi** [comment] 2019-07-08 01:01
I think STFU is not a solution as it implies that you have control over the server. You can't do it if you're the admin of a room that's hosted on the matrix.org homeserver. I'd really like to have a bulk redaction tool, and while that's not ready I'm trying to find a way to write a JS script to run in the Chromium developer console of Riot to do it. I'm not really skilled so if anyone, even @ara4n himself wanted to lend a hand I'd really appreciate!

**Comment by t3chguy** [comment] 2019-07-08 09:25
> I think STFU is not a solution as it implies that you have control over the server.

Does it?
It just uses a username and access token just like every other matrix client, so does not require any special permissions over a server.

**Comment by adalvigi** [comment] 2019-07-08 13:14
> It just uses a username and access token just like every other matrix client, so does not require any special permissions over a server. 

I've seen the README using it with a node instance so I thought it was implied that it ran in the node instance of the server. How do you use it for Matrix.org?

**Comment by t3chguy** [comment] 2019-07-08 13:23
Synapse has no Node instance, no Matrix servers exist in Node. 
Yes, matrix-stfu is written in Node.JS javascript, but it runs in any compatible Node runtime.

You specify the username in the config and the code gets the url from the username, which is a bit naughty but will work in most cases: https://github.com/xwiki-labs/matrix-stfu/blob/master/stfu.js#L25

**Comment by johnstonesnow** [comment] 2019-07-08 17:45
> You have to think of Matrix as being like email rather something like Skype. If I request gdpr erasure from my mail server, i don’t expect every email i ever sent to somehow get magically deleted, nor even for my emails to suddenly disappear from the email inboxes of other users on the same server. So too for Matrix. The privacy policy as per https://matrix.org/legal tries to make this abundantly clear.
> 
> That said, we do provide a redaction button, and we could provide a bulk redaction function as per #5885 too, although it would be very prone to abuse, which is why we have not prioritised it. But based on the legal advice we’ve received it is not a prerequisite for gdpr compliance.

So rather than Matrix being like Skype in actually OWNING the data which is peddled through its servers, Matrix/Riot simply creates a network to achieve delivery, as you say, much like email. That makes sense. I still think it should be an absolute no brainer to give people an option to remove their own messages, you do offer it on a one by one basis, so a bulk (simply tick to select multiple messages even) should be simple and no doubt appreciated by users. 

I will leave the tech chat to continue talking progammer-speak, but if an option ever arrives to give an average USER the option to delete their messages, I for one will be very pleased, if I am still a user of Matrix which currently seems unlikely sadly. 

Thanks for your time
