### ISSUE TITLE
Google Calendar integration does not work

### ISSUE THREAD

**Issue by fladd** [vector-im/riot-web#9106] opened 2019-03-11 11:39 UTC
### Description

When adding a calendar ID (from a calendar that is made publicly readable), the calendar is not shown, but an error message:

Sorry, this calendar can not be displayed

X-Frame-Options: DENY

### Steps to reproduce

- Add calendar widget
- Add calendar ID
- Save

Describe how what happens differs from what you expected.
I expect the calendar to show.

Log: not sent?    

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Chrome, Safari, Firefox
- **OS**: Windows, macOS
- **URL**: riot.im/develop and riot.im/app

**Comment by fladd** [comment] 2019-03-11 11:40
Here are the permission settings for the calendar:

![image](https://user-images.githubusercontent.com/2971539/54121508-e7b82200-43fa-11e9-87ba-37eaf0821279.png)

**Comment by fladd** [comment] 2019-03-11 21:23
Using a custom widget with the share URL from google calendar does work.

I would suggest to remove the Google Calendar Widget as an option.

**Comment by lampholder** [comment] 2019-03-15 14:09
Interesting - it works for me.

Adding a calendar widget for the new york times astronomy calendar `nytimes.com_89ai4ijpb733gt28rg21d2c2ek@group.calendar.google.com`

![image](https://user-images.githubusercontent.com/1922197/54437059-b8235580-472b-11e9-833c-5c98754e76b2.png)

Can you try with the above calendar id and let us know how you get on?

@jaywink cc'ing you 'cause this looks very likely to be a scalar/widgetty thing rather than a Rioty thing

**Comment by fladd** [comment] 2019-03-15 14:32
Yeah that one works indeed. Not sure why. Especially since the one that did not worked for me worked just fine as a custom widget.

**Comment by jaywink** [comment] 2019-03-18 14:17
Hi @fladd 

Would you be able to retry this again? We did have some temporary problems during those times with the Scalar backend, so maybe this was just caught in bad luck. If you could ping the approximate time then that you tried and will have a peek at logs to try and take the issue forward, if it still doesn't work.

Thanks!

**Comment by fladd** [comment] 2019-03-18 18:59
@jaywink It works now, thanks, but since one cannot customize the calendar view, the custom widget with the embed code from google calendar is still the better solution. Not sure what the calendar widget has in addition to the custom widget. Could someone explain?

**Comment by jaywink** [comment] 2019-03-20 13:17
@fladd the calendar widget works by "calendar ID" while the custom widget takes a URL and embeds anything that is embeddable. While both might do the same end result, it might be possible to extend the specific calendar widget in the future to work better or provide extra functionality. You can use whichever works better for you :)

Thanks for confirming the widget(s) work now. And sorry for the temporary blib we had in Scalar. I'll close this issue as no actions to take.

**Closed by jaywink** 2019-03-20 13:17 UTC
Labels: bug, major, p2, type:scalar, type:widgets

**Comment by vladimiroff** [comment] 2020-03-09 08:54
I would like to re-open this issue. Followed the same steps as reported above and got a similar result:

![screenshot_20200309_105206](https://user-images.githubusercontent.com/150954/76197069-1fb39a00-61f4-11ea-9de5-8c1a5fc1cb48.png)

**Comment by turt2live** [comment] 2020-03-09 16:14
Your calendar needs to be public.

**Comment by vladimiroff** [comment] 2020-03-09 16:33
It is public.

**Comment by turt2live** [comment] 2020-03-09 16:37
I can only reproduce the problem if the calendar is private in some way, or if the wrong info was punched into the widget. Using a public calendar ID the widget loads fine for me.

**Comment by MikeCheque** [comment] 2020-04-05 00:33
> 
> 
> Your calendar needs to be public.

so after making it public, which link in gcal settings does one copy and paste into the widget? I have this same issue currently

**Comment by cbeams** [comment] 2024-03-29 23:26
Indeed, none of the above work for me anymore:

1. It is no longer possible to enter a Calendar ID in the Google Calendar widget calendar address field (valid uri is required)
2. When entering a well-known public calendar such as the NYT Space and Astronomy Events Calendar [1] as discussed above above, the same "Sorry, this calendar can not be displayed - Failed to request remote content" error message appears.

The Google Calendar widget appears to simply be broken.

\[1\]: https://calendar.google.com/calendar/ical/nytimes.com_89ai4ijpb733gt28rg21d2c2ek%40group.calendar.google.com/public/basic.ics

**Comment by t3chguy** [comment] 2024-03-29 23:57
@cbeams this issue is 5 years old. The repo for the integrations manager is https://github.com/element-hq/element-integration-manager

**Comment by jiriholzel** [comment] 2024-10-04 07:49
Hello, I have still same problem. Is calendar integration dead? thx
