### ISSUE TITLE
timestamps are over the avatar when replying to an emote

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#9602] opened 2019-05-01 10:55 UTC
![image](https://user-images.githubusercontent.com/8582858/57014446-133fd780-6c08-11e9-8ebc-4e56a6d67fbf.png)

**Comment by turt2live** [comment] 2019-05-01 15:40
Duplicate of https://github.com/vector-im/riot-web/issues/2284#issuecomment-431060891

**Closed by turt2live** 2019-05-01 15:40 UTC
