### ISSUE TITLE
Multiple selection

### ISSUE THREAD

**Issue by alittlebitofit** [vector-im/riot-web#9655] opened 2019-05-09 07:01 UTC
Currently there is no way I can select multiple messages or multiple chats/rooms neither on web client nor on android app.

It would be better to have a feature that lets you select multiple messages, multiple rooms/chats. 

Deletion would get easier with this new feature.

Hope I am thorough.

**Comment by turt2live** [comment] 2019-05-09 14:05
Duplicate of https://github.com/vector-im/riot-web/issues/5885, https://github.com/vector-im/riot-web/issues/3689, https://github.com/vector-im/riot-web/issues/2158

**Closed by turt2live** 2019-05-09 14:05 UTC
Labels: suggestion

**Comment by alittlebitofit** [comment] 2019-05-09 15:27
@turt2live Thanks for the reference. :)
