### ISSUE TITLE
Permalink only works once

### ISSUE THREAD

**Issue by rkfg** [vector-im/riot-web#4787] opened 2017-08-13 20:12 UTC
### Description

Clicking a permalink only moves to the designated message once and doesn't work after that.

### Steps to reproduce

- post a permalink to a message outside of the currently visible chat log
- click it (it works and scrolls to the message)
- scroll back to the bottom (with a button or manually)
- click the permalink again

Nothing happens. It should jump to the same message again, no matter how many times I click it.

### Version information

- **Platform**: web

- **Browser**: Chrome 61.0.3163.39
- **OS**: Debian testing amd64
- **URL**: riot.im/develop

**Comment by t3chguy** [comment] 2017-08-13 20:42
Duplicate of #2903

**Closed by t3chguy** 2017-08-13 20:42 UTC
