### ISSUE TITLE
custom font size + new room sublists = fail

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14775] opened 2020-07-27 11:26 UTC
if you expand the custom font size, the new room sublists start truncating entries when expanded, making it impossible to see or select the bottommost items on the list unless you filter

**Comment by t3chguy** [comment] 2020-07-27 11:27
Duplicate of https://github.com/vector-im/riot-web/issues/14482

**Closed by t3chguy** 2020-07-27 11:27 UTC
