### ISSUE TITLE
power level changes in the timeline can show entirely blank now

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12379] opened 2020-02-14 23:23 UTC
<img width="160" alt="Screenshot 2020-02-14 at 23 23 12" src="https://user-images.githubusercontent.com/1294269/74576002-10d52100-4f81-11ea-85fc-c01d4e30c5e3.png">

**Comment by turt2live** [comment] 2020-02-15 00:01
Duplicate of https://github.com/vector-im/riot-web/issues/11510

**Closed by turt2live** 2020-02-15 00:01 UTC
