### ISSUE TITLE
Tray icon stopped working in recent version

### ISSUE THREAD

**Issue by ndorf** [vector-im/riot-web#13853] opened 2020-05-28 21:25 UTC
### Description

Using Debian Buster with the MATE desktop, the tray icon no longer appears after upgrading to riot-desktop 1.6.2.

### Steps to reproduce

- Start Riot
- Ensure that the "Show tray icon..." preference is selected
- Tray icon does not appear

It used to work fine until recently, I think as recently as riot-web 1.6.0.

Even though the tray icon is not visible, it does seem to be minimizing to it on close successfully: after closing the window with Ctrl+W, several riot-desktop processes are still running, desktop notifications for new incoming messages do appear, and starting the app again draws it instantaneously.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian Buster with MATE desktop
- **Version**: riot-desktop 1.6.2 from https://packages.riot.im/debian/

**Comment by t3chguy** [comment] 2020-05-28 21:37
Duplicate of https://github.com/vector-im/riot-web/issues/12518

**Closed by t3chguy** 2020-05-28 21:37 UTC
Labels: bug
