### ISSUE TITLE
Option to disable Markdown

### ISSUE THREAD

**Issue by 07151129** [vector-im/riot-web#13774] opened 2020-05-22 21:30 UTC
**Is your suggestion related to a problem? Please describe.**

I often find myself messaging unformatted output that gets interpreted as Markdown by riot, and requires reformatting by hand to make it readable. This gets especially time consuming for long text. While code block formatting is somewhat helpful, it introduces a scrollable region, and still requires surrounding text with ```.

**Describe the solution you'd like**

Add options that allow the user to:

1. Prevent own message(s) from being interpreted as Markdown by the recipients.
2. Prevent incoming messages from being interpreted as Markdown locally.

Possibly, these two options could be implemented with room granularity.

**Comment by aaronraimist** [comment] 2020-05-22 21:59
Duplicate of https://github.com/vector-im/riot-web/issues/483

What you can do for now is prefix the message with `/plain`

**Closed by aaronraimist** 2020-05-22 21:59 UTC
Labels: suggestion

**Comment by 07151129** [comment] 2020-05-22 22:02
> Duplicate of #483
> 
> What you can do for now is prefix the message with `/plain`

I do not see how this is a duplicate. `/plain` requires prefixing every single message. I am trying to automate this.

**Comment by aaronraimist** [comment] 2020-05-22 22:03
#483 is the issue asking for what you want. Add a 👍 there. What I was trying to give you was a workaround until it is implemented.

**Comment by 07151129** [comment] 2020-05-22 22:34
Sorry, I should have read more carefully. Thanks for the suggestion.
