### ISSUE TITLE
Add option to send by ctrl-enter

### ISSUE THREAD

**Issue by Eisfunke** [vector-im/riot-web#6871] opened 2018-06-13 20:38 UTC
Normally, riot sends a message when pressing enter, newlines can be added by shift-enter.

It'd be great if Riot could get an option to add newlines by enter and send the message by ctrl-enter instead. This would help people using many newlines (like me) and people who often send messages accidentally when trying to add a newline (also like me).

I got this idea from the Telegram desktop client, which has an option like that.

**Comment by t3chguy** [comment] 2018-06-13 20:39
Duplicate of https://github.com/vector-im/riot-web/issues/5006.

**Closed by t3chguy** 2018-06-13 20:39 UTC
