### ISSUE TITLE
Message action bar doesn't have tooltips

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#11204] opened 2019-10-23 13:36 UTC
<img width="244" alt="Screenshot 2019-10-23 at 14 39 03" src="https://user-images.githubusercontent.com/4626865/67398646-e4952f00-f5a2-11e9-980c-5c65c02a2f46.png">

From: https://zpl.io/a3e7okQ

We lost the quick reactions tooltip when merging in the emoji picker (https://github.com/vector-im/riot-web/issues/11176) and the other tooltips were never implemented during aggregations dev.

**Comment by t3chguy** [comment] 2019-12-07 13:12
Duplicate of https://github.com/vector-im/riot-web/issues/9716

**Closed by t3chguy** 2019-12-07 13:12 UTC
