### ISSUE TITLE
mangled MELS in #matrix-dev

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10138] opened 2019-06-21 17:45 UTC
https://matrix.to/#/!DYgXKezaHgMbiPMzjX:matrix.org/$15610787807OKjXb:ks.matfyz.cz?via=matrix.org&via=matrix.allmende.io&via=tchncs.de

<img width="1290" alt="Screenshot 2019-06-21 at 18 45 36" src="https://user-images.githubusercontent.com/1294269/59941305-c680bc00-9454-11e9-8e9f-4565b816d2da.png">
<img width="326" alt="Screenshot 2019-06-21 at 18 44 28" src="https://user-images.githubusercontent.com/1294269/59941306-c680bc00-9454-11e9-9010-2dfa118cf02d.png">

**Comment by turt2live** [comment] 2019-06-21 17:47
Duplicate of https://github.com/vector-im/riot-web/issues/10115

**Closed by turt2live** 2019-06-21 17:47 UTC
Labels: bug
