### ISSUE TITLE
button to disable markdown

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14394] opened 2020-07-09 22:47 UTC

**Comment by simonmichael** [comment] 2020-07-10 15:27
Thank you @ara4n ! Here's some context from the Riot Web/Desktop room:

sm:
> man, I wish I could turn off Riot's auto markdown formatting completely
> so I can discuss computing topics without constantly remembering too late I have to add special escaping

Matthew:
> we used to have a button for disabling markdown. it's a bit annoying it's vanished

TravisR:
> we replaced it with /plain

I feel this feature is surprising enough and in need of changing often enough that it needs to be more visible and configurable. I think a permanent visible control/indicator is probably best. If not that, then a global or per-channel setting would be useful, but less convenient.

**Comment by simonmichael** [comment] 2020-07-10 15:37
PS, I forgot to mention that most of my matrix use involves chatting with IRC users in bridged channels, which makes the unexpected auto-formatting more problematic - I can see the formatting broke my pasted command lines in Riot, but I'm never quite sure what IRC users saw, and it's always important to me to avoid obvious typos and visual noise on IRC caused by using a matrix client.

**Comment by aaronraimist** [comment] 2020-07-10 18:17
Duplicate of https://github.com/vector-im/riot-web/issues/483

**Closed by aaronraimist** 2020-07-10 18:17 UTC
