### ISSUE TITLE
Joins sometimes show up as weird blank lines

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#12575] opened 2020-02-29 00:17 UTC
This should show "X made no changes" rather than being blank

<img width="930" src="https://user-images.githubusercontent.com/5855073/75596526-9ca57d80-5a56-11ea-863b-176954fdf899.png">

<img width="786" src="https://user-images.githubusercontent.com/5855073/75596552-b5ae2e80-5a56-11ea-93e2-deada8ca7636.png">

https://matrix.to/#/!mjbDjyNsRXndKLkHIe:matrix.org/$p-yUWNLgeEOfU8YHoYLBnl_zZMRrbmWXW3xFwtVOG80?via=gament.org&via=raim.ist&via=queersin.space

v1.5.10

**Comment by turt2live** [comment] 2020-02-29 00:26
Duplicate of https://github.com/vector-im/riot-web/issues/11510

**Comment by aaronraimist** [comment] 2020-02-29 00:28
@turt2live I don't think its a duplicate. I don't have Show Hidden Events turned on.

**Comment by aaronraimist** [comment] 2020-02-29 00:30
In fact turning on Show Hidden Events causes it to show up properly.
<img width="394" src="https://user-images.githubusercontent.com/5855073/75596946-5b15d200-5a58-11ea-8972-9f7b8295a1cf.png">

**Comment by turt2live** [comment] 2020-02-29 00:55
oh, hmm, that's a pretty serious regression. We used to just hide these.

**Comment by t3chguy** [comment] 2020-03-02 12:36
I cannot reproduce this:

![image](https://user-images.githubusercontent.com/2403652/75676872-13728e80-5c82-11ea-8e0a-4d37b3ef0401.png)

Looking at the code I also cannot see how it'd happen. The same logic gets applied with then further restricting done.

**Comment by t3chguy** [comment] 2020-03-02 12:40
This is already fixed on /develop
presumably by changes in MELS

**Comment by aaronraimist** [comment] 2020-03-02 16:00
I can see this on /develop

<img width="935" alt="Screen Shot 2020-03-02 at 9 59 17 AM" src="https://user-images.githubusercontent.com/5855073/75693416-8709a100-5c6c-11ea-8934-8c8241351c05.png">

<img width="1210" alt="Screen Shot 2020-03-02 at 9 59 24 AM" src="https://user-images.githubusercontent.com/5855073/75693413-85d87400-5c6c-11ea-99d8-ce5751d370cd.png">

**Comment by turt2live** [comment] 2020-03-02 16:01
@aaronraimist can you rageshake on this please?

**Comment by aaronraimist** [comment] 2020-03-02 16:03
Done

**Comment by turt2live** [comment] 2020-03-02 16:03
Thanks, I can also reproduce it in the same room.

**Closed** 2020-03-04 19:24 UTC
Labels: bug, p1, rageshake, regression, reproduced, type:timeline
