### ISSUE TITLE
Riot icon disappears after upgrade to 1.2.0

### ISSUE THREAD

**Issue by hooger** [vector-im/riot-web#9897] opened 2019-05-30 08:06 UTC
### Description

After upgrading to 1.2.0 from 1.1.2 the icon of Riot disappears from the taskbar (so I cannot focus it in case of minimizing), and on the window list the icon is not the official icon, but a regular "some window" icon.

### Steps to reproduce

- Shut down riot-web
- Upgrade to riot-web 1.2.0 from 1.1.2
- Start riot-web
- Icon on the window list is not good, and there is no icon on the tray or taskbar
- Have the setting "The close button puts the application down on the tray" enabled (this message is a google translated version of the original hungarian that I see)
- Hit the close button
- Application disappears (but still running, based on ps, and "restarting" it from menu calls it pretty quick)

Describe how what happens differs from what you expected:
- I want my icons back :D (sry for strong phrasing)

![kép](https://user-images.githubusercontent.com/12232146/58618026-d7109d00-82c1-11e9-8907-a8ae98b21ba5.png)

Red circle shows the wrong icon display, blue circle shows where the Riot icon was right before I upgraded.
### Version information

- **Platform**: web (in-browser) or desktop?

For the desktop app:

- **OS**: Debian stable, up-to-date at the time of bug report creation
- **Version**: 1.2.0

**Comment by hooger** [comment] 2019-05-30 09:41
Interesting! When the first message arrived, the Riot icons automagically appeared with the number in bubble and after I read the new message, and the notification was gone, the icon stayed. However after restarting the app the issue resurfaces. This is still a bug, that needs to be addressed I think, but at least I can live with that.

**Comment by jryans** [comment] 2019-05-30 09:50
Thanks for the report! That is definitely strange and unexpected. We've had a lot of trouble with those icons in desktop builds... At the moment, I'm not sure what would cause that, but let's keep this issue open and see if it affects others as well.

**Comment by Me4Linux** [comment] 2019-05-30 12:33
Same here. After upgrading to 1.2.0 and restarting my systems (Xubuntu 16.04 and Debian 9) there's no Riot.im symbol in the notification area.

**Comment by edwardando** [comment] 2019-05-30 14:33
I confirm: the tray icon has gone for me too on Debian Stretch with Openbox

**Comment by jryans** [comment] 2019-05-30 14:52
Hmm, very curious. I have asked #riot-web:matrix.org, and some Linux users _do_ have the app icon still, so we'll need to look for some kind of root cause here.

As far as I know, nothing was changed in Riot with the icon art... We did change from Electron 4.1.5 to 4.2.2, so it's possible that is related to the issue here.

**Comment by jryans** [comment] 2019-05-30 14:55
I don't see any changes to app icons in Electron changelog between those versions (but of course it's still possible that something may have changed anyway).

Electron 5 does mention some fixes in this area, but it's unclear if they'll help with this issue.

**Comment by adrianiainlam** [comment] 2019-05-31 03:47
Same here, Ubuntu 16.04

**Comment by mrdumpty** [comment] 2019-05-31 07:23
Same here, Linux Mint 19.1 Tessa (Mint version)
No Riot icon on system tray.

**Comment by adrianiainlam** [comment] 2019-05-31 15:20
Suddenly started working for me again, after someone messaged me.

**Comment by Me4Linux** [comment] 2019-05-31 16:09
Asked some friends to message me and as soon as one of them did there's the symbol back again. But after closing and reopening the client the bug's also back.

**Comment by vsatmydynipnet** [comment] 2019-06-01 09:23
Debian Buster and Sid, XFCE, riot-web 1.2.1 the problem is still there.

**Comment by erciccione** [comment] 2019-06-02 10:37
+1 on Debian sid, riot 1.2.1, but i had this problem before. It was usually necessary to wait some minutes and the icon would appear, but now nothing show up unless i get pinged.

**Comment by mrdumpty** [comment] 2019-06-03 08:13
The bug still exists with 1.2.1, icon appears only when receiving first message after startup. Linux Mint 19.1 Tessa (Mate version).

**Comment by i47320673** [comment] 2019-06-06 21:10
Linux Mint 17.3
The same issue in 1.2.1. 
1.1.2 works fine.

**Comment by Fzorkas** [comment] 2019-06-09 19:32
Bug also exists for me. Linux Mint 19 Tara MATE.

**Comment by heini** [comment] 2019-06-10 06:11
Same here.

Debian Buster, KDE, Riot-Web 1.2.1.

**Comment by DoctorSubtilis** [comment] 2019-06-13 14:41
Also here, Kubuntu 18.04, Riot-web 1.2.1

**Comment by anjannath** [comment] 2019-06-14 11:42
So i use riot from flathub, update to version 1.2.1, and faced the same issue, running on Fedora 30

**Comment by dbkr** [comment] 2019-06-14 13:54
@jryans any chance this could have been triggered by the change to the favicon code to avoid using the canvas on startup? ie. there's some problem with the icon file we're providing but once we update the favicon with canvas, it works spits out a PNG which is fine?

**Comment by jryans** [comment] 2019-06-17 15:53
> @jryans any chance this could have been triggered by the change to the favicon code to avoid using the canvas on startup? ie. there's some problem with the icon file we're providing but once we update the favicon with canvas, it works spits out a PNG which is fine?

Hmm, I agree the timing is suspicious, as [the change to delay favicons](https://github.com/vector-im/riot-web/pull/9616) first appeared in Riot 1.2.0. At the moment though, I can't reproduce this issue with Riot 1.2.1 on Ubuntu 18.04.2. I'll investigate further, as there's clearly a variety of system configurations affected.

**Comment by DoctorSubtilis** [comment] 2019-06-18 14:35
Today, I don't know why and how, the riot tray icon is reappeared.

**Comment by jryans** [comment] 2019-06-18 15:10
The icon should reappear once you receive a notification. Only the default app icon at startup (before the first notification) appears to be affected. I'm working on a fix for the default case now.

**Comment by DoctorSubtilis** [comment] 2019-06-18 15:12
Ah, ok. Thank you!

**Comment by edwardando** [comment] 2019-06-18 15:13
After a rare restart mine is back too!

**Closed** 2019-06-18 16:35 UTC
Labels: bug, p2, regression, type:electron

**Comment by jryans** [comment] 2019-06-18 16:36
Thanks for your patience! This should be fixed in all cases once the next Riot release ships (probably in a few days).

**Comment by jryans** [comment] 2019-06-19 16:06
This was not included in Riot 1.2.2, so it will go out with the next release.
