### ISSUE TITLE
[Feature Request] Embed on webpage

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#5714] opened 2017-11-28 19:41 UTC
I would love to have an instance of riot-web that I can embed on the side of my page, so people can see public channels, how many are in them, then join from it. It doesn't necessarily need to have every bell and whistle, but maybe some options too so we can turn features on/off for that.

Maybe also have this as a way for guests to easily join rooms too?

**Comment by turt2live** [comment] 2017-11-28 19:42
Duplicate of https://github.com/vector-im/riot-web/issues/647

**Comment by BloodyIron** [comment] 2017-11-28 19:44
Oops, thought the other one was closed, my bad!

**Closed** 2017-12-01 15:34 UTC
Labels: duplicate
