### ISSUE TITLE
Implement option to pin rooms with mentions to the top of the roomlist

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6604] opened 2018-04-25 15:15 UTC

**Comment by turt2live** [comment] 2018-04-26 03:58
Duplicate of https://github.com/vector-im/riot-web/issues/1104 (mostly)

**Comment by turt2live** [comment] 2018-11-01 14:04
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1936

**Closed by turt2live** 2018-11-01 14:04 UTC
Labels: feature, p1, type:roomlist
