### ISSUE TITLE
Forgets homeserver url when creating account

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#8929] opened 2019-02-25 10:21 UTC
### Description

Custom server flows reset to matrix.org too often:

### Steps to reproduce

- Visit riot.im/app
- Click sign in
- Enter custom HS and IS urls
- Realise you need to create an account, click "Create Account" text
- *Page has reset to "create account on matrix.org"* - despite coming from custom HS/IS url page
- Clicking Advanced - page has not remembered the custom HS/IS url here either

Describe how what happens differs from what you expected.

I would expect creating an account from the sign-in page to remember my HS and IS urls.

Doing the reverse - going from create an account back to the signing page does remember the HS and IS urls, which is good.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox
- **OS**: Ubuntu
- **URL**: riot.im/app

**Comment by jryans** [comment] 2019-02-26 16:04
Thanks for the report. This sounds like a duplicate of https://github.com/vector-im/riot-web/issues/8695.

**Closed by jryans** 2019-02-26 16:04 UTC

**Comment by jryans** [comment] 2019-02-27 11:32
@michaelkaye I can no longer reproduce this on https://riot.im/develop (still happens on /app for now). Do you agree? (There are several reports of this, so verifying it's fixed would be great.)

**Comment by michaelkaye** [comment] 2019-02-27 11:37
I cannot replicate on /develop at the moment - the options default to the custom HS/IS and stay there until i click "matrix.org" which does then reset them (but that's probably OK)

**Comment by jryans** [comment] 2019-02-27 11:40
Thanks, sounds like it's been fixed by other changes then.
