### ISSUE TITLE
desktop client: entering community view gets you stuck 

### ISSUE THREAD

**Issue by rubo77** [vector-im/riot-web#8658] opened 2019-02-14 20:59 UTC
### Description

If I click on a community in the left bar to see only those rooms from that community, there is no way back to the view of all rooms.

### Steps to reproduce

- click on any community icon on the left

There should be a button to close the community view.

### Version information

matrix-react-sdk version: <local>
riot-web version: 1.0.0
olm version: 3.0.0

- **Platform**: desktop
- **OS**:  Ubuntu
- **Version**: 18.10

### Workaround

Completely close the desktop app and restart

**Comment by turt2live** [comment] 2019-02-14 21:02
Duplicate of https://github.com/vector-im/riot-web/issues/7953

**Closed by turt2live** 2019-02-14 21:02 UTC

**Comment by rubo77** [comment] 2019-02-27 18:08
solution: click underneath the communities in the empty area and you get rid of the community selection ;)

This is not obvious at all, there should be a big X or something!
