### ISSUE TITLE
Auto refocus chat input when no other input selected

### ISSUE THREAD

**Issue by swedneck** [vector-im/riot-web#8070] opened 2019-01-09 00:32 UTC
- **Browser**: Firefox 64.0
- **OS**: Fedora 29

### Description
Currently whenever a user wants to type a message, they have to make sure the chat input is selected by clicking it. This is tedious and results in having to re-type if you forgot to do this.

Instead i propose that as long as no other input field is selected, the chat input should be focused. 
This allows users to just start typing and have it register, without needing to click the chat input first.

**Comment by t3chguy** [comment] 2019-01-09 00:43
Duplicate of #5775

**Closed by t3chguy** 2019-01-09 00:43 UTC
Labels: redesign
