### ISSUE TITLE
Unable to forget "world readable" rooms

### ISSUE THREAD

**Issue by LunarTwilight** [vector-im/riot-web#9475] opened 2019-04-15 07:26 UTC
### Description
Unable to "forget" rooms that are viewed, but not joined.

### Steps to reproduce
- Find a "world readable" room (eg, the Riot iOS room)
- View it but don't join
- Try to forget the room

Expected result: I should be able to forget the room.

Actual result: There is no forget option.

Log: sent.

![image](https://user-images.githubusercontent.com/13520392/56114136-6c232680-5f0c-11e9-84af-495539475736.png)

### Version information
- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.0.7

**Comment by jryans** [comment] 2019-04-16 13:48
@LunarTwilight Where are you seeing the room appear in the room list? Is it "Rooms", "Historical", something else ...?

**Comment by turt2live** [comment] 2019-04-16 15:13
Duplicate of https://github.com/vector-im/riot-web/issues/9168 ("World Readable" doesn't make a difference here)

**Closed by turt2live** 2019-04-16 15:13 UTC
Labels: bug, defect, major, p2, type:roomlist
