### ISSUE TITLE
Sometimes legit invitees cannot write in a room

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#7790] opened 2018-12-06 15:48 UTC
See here: https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$1544110954587329cEkKR:matrix.org?via=matrix.org&via=linuxgaming.life&via=disroot.org&via=chat.weho.st

**Comment by turt2live** [comment] 2019-03-22 00:12
There's no logs associated with this, and the linked conversation doesn't really help narrow down the issue. Closing as a duplicate of https://github.com/vector-im/riot-web/issues/7838 to track the larger issue here: https://github.com/vector-im/riot-web/issues/7843

**Closed by turt2live** 2019-03-22 00:12 UTC
Labels: bug, major, p1
