### ISSUE TITLE
New message notifications on system tray icon not always working

### ISSUE THREAD

**Issue by CouponCodeSwap** [vector-im/riot-web#13035] opened 2020-04-05 20:14 UTC
### Description

The little red notification with message count does not always appear on the System Tray icon. If the Riot window is minimized to Task Manager, the notifications appear. If Riot is minimized to System Tray icon, they only appear on the first new message before any messages have been sent. Or, notifications appear on the first new incoming message after resume from suspend if Riot was minimized to System Tray icon before any outgoing messages were sent. When I send a message and then minimize to System Tray icon again, notifications never work. This is not good because expected behavior is a notification of new messages while Riot is minimized to System Tray icon.

### Steps to reproduce

- Send a message.
- Minimize to System Tray icon.
- Wait for new incoming message. There will be no notification.
- Bring Riot window to focus, the new message is in there despite the lack of notification.

### Version information

**OS**
Arch Linux, Plasma desktop 5.18.4, Qt 5.14.2, Electron 8.2.0-3

**Version**
Riot 1.5.12-1

Note: This is different than issue #11594 because it does not make a difference whether the Enable audible notifications for this session setting is on or off.

**Comment by aeridus** [comment] 2020-04-09 19:44
I'm frequently seeing the converse of this issue as well, where the system tray icon will show a little red notification count even after I clear new messages in the client. None of my channels have new messages, but the icon still seems to think there are some.

**Comment by CouponCodeSwap** [comment] 2020-04-09 23:57
Yes, I see that occasionally as well. Just happened a few minutes ago, all of the new messages are seen but the red notification count on the icon does not disappear until I quit and restart Riot.

**Comment by geckolinux** [comment] 2020-04-12 19:14
Same here on openSUSE Tumbleweed. Sometimes the notification fails to appear, or the unread count doesn't update, and sometimes it fails to reset after opening and reading all the messages.

**Comment by jryans** [comment] 2020-04-14 16:56
@CouponCodeSwap Sorry to hear about this. Is it a new issue, or has it been like this for a while?

**Comment by CouponCodeSwap** [comment] 2020-04-14 18:59
> Sorry to hear about this. Is it a new issue, or has it been like this for a while?

Hi jryans. I have been using Riot since December of last year and this issue has been present since then. Was hoping it would be fixed with some of the updates that have rolled out, but alas the bug persists. It seems to affect the app across operating systems, Linux and Windows 10 at least.

I came to Riot after beginning a quest to find an open source, decentralized replacement for Skype. Researched and tried a number of different options and came to the conclusion that Riot is the best alternative. I would like to recommend Riot to more friends and clients and promote the platform in general. This bug is the only issue found thus far that makes me hesitant to do so. One other thing is a feature request: it would be nice to have an emoji picker button as most are accustomed to it, but that is not something that would prevent me from recommending Riot.

If I can assist in any way towards solving this bug, please let me know.

**Comment by steef435** [comment] 2020-04-16 14:27
This issue seems to persist with the fresh riot-desktop code (1.6rc). For me, the icon only updates if the window is not closed (but it doesn't have to have focus).

Currently I don't have the time to look into it, but note to self/others: I suspect that the callback set up in src/tray.js
`global.mainWindow.webContents.on('page-favicon-updated', async function(ev, favicons) {`
(currently https://github.com/vector-im/riot-desktop/blob/master/src/tray.js#L72) only gets called when the window exists.

**Comment by steef435** [comment] 2020-04-16 21:54
> Currently I don't have the time to look into it, but note to self/others: I suspect that the callback set up in src/tray.js
This turned out to be false.

I can now sort of consistently reproduce this bug in the following way:

0. On startup, everything works properly
1. Close Riot window
2. The icon will _not_ update on the first (and only the first) change of the unread counter
3. The icon starts working properly on the next change of the unread counter and remains working correctly while the window is closed, after the window is opened, but as soon as 1. occurs 2. will again occur.

There are callbacks getting fired to this page-favicon-updated, but the one passed in step 2. is the wrong one (the previous one it seems). So it seems to me there are two places where this could go wrong: in the favicon setting logic in riot-web, or in the favicons passed by electron.

**Comment by CouponCodeSwap** [comment] 2020-04-17 06:38
Started digging around in the src files and I think this might be where the code needs adjusting:

https://github.com/vector-im/riot-web/blob/develop/src/vector/platform/VectorBasePlatform.js

Currently scanning that file to see if I can spot anything obvious.

**Comment by CouponCodeSwap** [comment] 2020-05-08 22:34
Just curious if this issue has been acknowledged by the dev team yet and if not, what needs to be done so that it may be added to the queue for fixing? Now that Riot has spell-check, the only thing holding me back from recommending it to friends, family, acquaintances and clients as an alternative to Skype etc. is this notification bug.

**Comment by t3chguy** [comment] 2020-05-12 08:53
Related or duplicate of https://github.com/vector-im/riot-web/issues/4709

**Closed** 2020-05-18 09:19 UTC
Labels: bug, type:notifications, type:trayicon
