### ISSUE TITLE
Presence does not work anymore in Riot 0.14

### ISSUE THREAD

**Issue by ejpcmac** [vector-im/riot-web#6498] opened 2018-04-11 20:43 UTC
### Description

Since I updated to Riot 0.14, I see myself offline for a few seconds to minutes. It is the same for friends that have updated (they see themselves offline, so do I) but not thoose who have not updated yet: they see me offline, but I see them online as expected.

### Steps to reproduce

* Use Riot 0.14 on a homeserver with presence

You are now connected but offline. Your contacts see you offline. You see some people online, mainly thoso who have not yet updated Riot.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS
- **Version**: 0.14.0

**Comment by turt2live** [comment] 2018-04-11 20:56
This is a duplicate of https://github.com/vector-im/riot-web/issues/5727 which has a bit of a troubled history.

**Comment by ejpcmac** [comment] 2018-04-11 21:28
@turt2live That’s indeed a strange issue. The stranger thing is that it used to work well for me until today.

**Comment by t3chguy** [comment] 2018-04-11 21:31
@ejpcmac yes that is expected, because the code at fault was part of today's release

**Comment by dbkr** [comment] 2018-04-12 10:52
dup of https://github.com/vector-im/riot-web/issues/5727 which is also now closed.

**Closed by dbkr** 2018-04-12 10:52 UTC
