### ISSUE TITLE
Huge images don't thumbnail

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2576] opened 2016-11-13 19:38 UTC
Like this one.

![logos geektime 1](https://cloud.githubusercontent.com/assets/1294269/20248296/b714034e-a9d8-11e6-99ea-acde23f33bbe.png)

**Comment by pafcu** [comment] 2017-12-15 10:43
Duplicate of https://github.com/vector-im/riot-web/issues/1065

**Closed** 2017-12-15 18:11 UTC
Labels: bug, cosmetic, p2, type:timeline
