### ISSUE TITLE
There's no obvious way to go back to global chat list after opening a community.

### ISSUE THREAD

**Issue by TheReverend403** [vector-im/riot-web#8707] opened 2019-02-15 15:39 UTC
- **Browser**: Firefox 65
- **OS**: Gentoo

### Description

There's no obvious way to go back to global chat list after opening a community.

### Steps to reproduce

- Click on any community in the farthest left sidebar.
- Try to go back to the global chat list without manually editing the URL.

Start here.

![Start here.](https://a.pste.pw/cQI.png)

Now go here.

![Now go here.](https://a.pste.pw/aDO.png)

Now try and get back here.

![Now try and get back here](https://a.pste.pw/cQI.png)

**Comment by turt2live** [comment] 2019-02-15 17:13
Duplicate of https://github.com/vector-im/riot-web/issues/7953

**Closed by turt2live** 2019-02-15 17:13 UTC
Labels: redesign
