### ISSUE TITLE
Add a way to temporarily mute notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7796] opened 2018-12-07 01:32 UTC
eg: `/mute 5m` or something

**Comment by lampholder** [comment] 2018-12-10 14:04
HOW DOES THIS NOT HAVE MORE UPVOTES?

**Comment by aaronraimist** [comment] 2018-12-14 17:07
This is pretty advanced but I'd also love a way to schedule it. For example I'm in a room that is extremely busy once a week at a specific time so I'd like to turn of push notifs during that time but during the rest of the week it is pretty quiet so I want notifications.

**Comment by aaronraimist** [comment] 2019-01-16 01:01
Oh just realized this is a duplicate of #3569

**Closed** 2019-01-16 01:04 UTC
Labels: feature, p2
