### ISSUE TITLE
One-line message view

### ISSUE THREAD

**Issue by matthiasbeyer** [vector-im/riot-web#9291] opened 2019-03-26 20:21 UTC
![2019-03-26-211754_589x48_scrot](https://user-images.githubusercontent.com/427866/55030455-b51e4400-500c-11e9-80d3-777284056075.png)

### Description

Right now, a message in riot has two lines. Can we have an option to have username and text on one line? Possibly even with the username right-aligned so that it does not "flatter" with shorter and longer usernames?

### Version information

- **Platform**: web (in-browser)
- **Browser**:Firefox 65.0.2 (64bit)
- **OS**: NixOS linux
- **URL**: riot.im/app

**Comment by turt2live** [comment] 2019-04-02 19:08
Effectively a duplicate of https://github.com/vector-im/riot-web/issues/6982

**Closed by turt2live** 2019-04-02 19:08 UTC
Labels: suggestion

**Comment by matthiasbeyer** [comment] 2019-04-03 06:00
Awesome, thank you!
