### ISSUE TITLE
The login button can have text overflowing out of the box in some locales and platforms

### ISSUE THREAD

**Issue by Porkepix** [vector-im/riot-web#4804] opened 2017-08-16 19:36 UTC
### Description

The login button can have text overflowing out of the box in some locales and platforms

### Steps to reproduce

- Go on https://riot.im/develop/#/home or https://riot.im/app/#/home without a connected account with French as requested locale and on a Mac
- You can see the text go outside of the box (see joined screenshot)

Describe how what happens differs from what you expected.

The box should be sized to contain the text.

![Screenshot of the home](https://user-images.githubusercontent.com/709500/29381724-8b5b7e46-82ca-11e7-85ee-8ff0117559cc.png)

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox stable and nightly, Chrome.
- **OS**: macOS
- **URL**: riot.im/develop / riot.im/app

Additional informations:

Problem visible on both Firefox and Chrome on macOS, but not on Linux nor Windows.
It seems to be related to the font and its style (Linux may have the requested font missing too).
Text seems to be bold on macOS compared to other platforms.
I think it's important to check other locales for both the sign in and log in buttons as many locales can have longer texts than French.

**Comment by lampholder** [comment] 2017-08-17 09:45
Ideally these buttons would:
- expand to fit the text content
- wrap over two lines if both buttons can't fit on the same line

**Comment by turt2live** [comment] 2017-08-17 19:50
Duplicate of https://github.com/vector-im/riot-web/issues/4713

**Comment by t3chguy** [comment] 2017-08-17 20:31
Thanks @turt2live 
Closed other in favour of this one as it has @lampholder's master plan on it

**Comment by lukebarnard1** [comment] 2017-08-18 10:21
We might be able to get away with just using CSS, similarly to #4776

**Closed** 2017-09-06 12:36 UTC
Labels: bug, cosmetic, easy, major, p1
