### ISSUE TITLE
Smarter 'mark as read' behaviour

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9032] opened 2019-03-04 11:42 UTC
Spun out from @tiotrom's comments on https://github.com/vector-im/riot-web/issues/8961

Idea: only mark messages as seen if the user is actively engaging with Riot, like it is clicking the messaging form and starts to type. This way you are truly "marking as read".

So many times I opened Riot to change a setting and it had a room in focus and it marked the messages as "seen by me" without me having any interest in reading them. Or when I leave Riot in focus and has a chat room in focus and basically all messages are seen as "read by me" even though I am not even at the computer. It projects false events. It needs to be way smarter if it is going to respect the user freedom. I feel like my hand is forced every time I open Riot since messages are marked as "seen" even though I either do not read those messages, or

**Comment by jryans** [comment] 2019-03-04 11:51
I agree we should definitely try to improve this. I believe this issue is a duplicate of https://github.com/vector-im/riot-web/issues/8041.

**Closed by jryans** 2019-03-04 11:51 UTC

**Comment by tiotrom** [comment] 2019-03-04 12:32
Yes please do that! :) If I click the "write area" or click the message, then mark it as "read". Maybe even add an "invisible" mode that once selected in Riot, I should be "invisible" completely. I know it sounds weird when I put it this way, but I felt more "stealth" on Skype with their invisible mode than Riot now - but of course Riot is by far better in all regards and seeing you guys taking this into account makes me very happy. Thank you for your work!
