### ISSUE TITLE
In the Electron app, images cannot be downloaded in unencrypted rooms Windows 10

### ISSUE THREAD

**Issue by horstvogel** [vector-im/riot-web#14329] opened 2020-07-04 12:16 UTC
Windows 10 Electron App 1.6.8 
In the Electron app, images cannot be downloaded in unencrypted rooms. The images are only opened in the browser. That works in encrypted rooms.

**Comment by t3chguy** [comment] 2020-07-04 12:18
Duplicate of https://github.com/vector-im/riot-web/issues/12405

**Closed by t3chguy** 2020-07-04 12:18 UTC
Labels: bug
