### ISSUE TITLE
Multiple admin per community

### ISSUE THREAD

**Issue by D4nte** [vector-im/riot-web#14741] opened 2020-07-24 02:32 UTC
**Is your suggestion related to a problem? Please describe.**
Currently, there is only one "admin" per community. This means that all admin work for the given communuty needs to be done by one person.

**Describe the solution you'd like**
The possibility to have several admin for a given community. Ideally there could also be an "owner" and "admin" concept to avoid the overtaking of a community by a wild admin, but this could be a later feature.

**Describe alternatives you've considered**
I understand there are few rights related to a community admin:

- Update logo of community
- Update description of community
- Add/Remove users to community
- Add/Remove rooms to community

An admin has all permission, adding the possibility to make an existing user also an admin is the most simple way to solve the problem at hand.

An alternative would be to introduced several role levels and permissions.

I can imagine 3 role types:

- Owner
- Admin
- Moderator

And permission going with them:

- Update logo of community (owner, admin)
- Update description of community (owner, admin)
- Add/Remove users to community (owner, admin, moderator)
- Add/Remove rooms to community (owner, admin, moderator?)
- Add/Remove admin (owner)
- Add/Remove moderator (owner, admin)

Maybe the role of the moderator is superfluous. To true design this UX it'd be best to ask the users :)

**Comment by turt2live** [comment] 2020-07-24 02:43
Duplicate of https://github.com/vector-im/riot-web/issues/5240

**Closed by turt2live** 2020-07-24 02:43 UTC
Labels: suggestion

**Comment by D4nte** [comment] 2020-07-24 04:41
@turt2live: Thanks! Maybe it would be worth updating the terminology/title of the original issue to make it easier to find? I did a search in the issues around "community" and "multiple admin" but obviously missed this issue.
