### ISSUE TITLE
A new room only appears in breadcrumbs the second time you enter it

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#9625] opened 2019-05-03 09:42 UTC
Create a new room, send a bunch of messages, switch to another room: the room you just created is not in the breadcrumbs while it should be. It should probably appear the moment you enter it, like when you switch to an existing one

**Comment by turt2live** [comment] 2019-05-03 16:28
is this on /app or /develop? It appears to work okay on develop ._.

![image](https://user-images.githubusercontent.com/1190097/57151416-28467300-6d8e-11e9-8247-6eeb53e4ce63.png)

**Comment by lampholder** [comment] 2019-05-29 10:08
I can't reproduce this either on /develop, so I'm going to close this

**Closed by lampholder** 2019-05-29 10:08 UTC
Labels: bug, cannot-reproduce, p1, question, type:breadcrumbs, ui/ux
