### ISSUE TITLE
add buttons for switch between images of room in full image view mode

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-web#13191] opened 2020-04-16 01:07 UTC
Now:
1. open room with many images in room
1. press on image for see it on full screen mode
1. If user want see next image in room (for example many photos of tourist hike) - He need press "X", scroll to next image, press next photo and again and again...

Need:
1. open room with many images in room
1. press on image for see it on full screen mode
1. Press "next" or "previous" buttons - show next image in room in full screen mode or show previous image in room in full screen mode.

**Comment by t3chguy** [comment] 2020-04-16 01:09
Duplicate of https://github.com/vector-im/riot-web/issues/337

**Closed by t3chguy** 2020-04-16 01:09 UTC
Labels: suggestion
