### ISSUE TITLE
Can't go back to previous room after following link to a specific message

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9013] opened 2019-03-01 10:36 UTC
STR:

1. Someone posts a link to a specific message in some room, such as https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$1551416672193jAeZn:t2l.io?via=matrix.org&via=half-shot.uk&via=linuxgaming.life
2. When I click this link from inside Riot, it changes rooms and navigates to the specific message correctly
3. When I try to click the browser's back button to return to the previous room, the location bar briefly flashes, but is then set back to the specific message URL and Riot doesn't go anywhere.

Here are the console logs when pressing back:

```
Routing URL  https://riot.im/develop/#/room/!QtykxKocfZaZOUrTwp:matrix.org/$1551416672193jAeZn:t2l.io?via=matrix.org&via=half-shot.uk&via=linuxgaming.life rageshake.js:61:8
RVS update: !QtykxKocfZaZOUrTwp:matrix.org undefined loading? false joining? false initial? undefined shouldPeek? true rageshake.js:61:8
Switching to room id !QtykxKocfZaZOUrTwp:matrix.org at event $1551416672193jAeZn:t2l.io rageshake.js:61:8
newscreen room/#matrix:matrix.org/$1551416672193jAeZn:t2l.io rageshake.js:61:8
```

**Comment by turt2live** [comment] 2019-03-01 15:25
Duplicate of https://github.com/vector-im/riot-web/issues/3543 (I think)

**Closed by turt2live** 2019-03-01 15:25 UTC
