### ISSUE TITLE
dragging a room from one section to another can result in flickering

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#3946] opened 2017-05-17 19:00 UTC
as reported by temsmeding in https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14950470741847448GElGx:matrix.org, and as seen in https://matrix.org/_matrix/media/v1/download/matrix.org/EExFlTxOsvaCBbXjmTCoqQLD

**Comment by t3chguy** [comment] 2017-05-17 19:00
https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14950470941847717xPHdY:matrix.org

**Comment by tomsmeding** [comment] 2017-05-17 19:04
I have this issue in Firefox 53.0.2 on OS X, if relevant.

**Comment by tomsmeding** [comment] 2017-05-17 19:08
More info: this only happens if, apart from the room being dragged, both the source and the target section are empty. Otherwise, no flickering occurs.

**Comment by t3chguy** [comment] 2017-05-17 19:17
I reproduced this on Chrome on Windows

**Comment by turt2live** [comment] 2017-05-17 20:18
Duplicate of #3370, related to #3280

**Comment by uhoreg** [comment] 2017-05-17 21:09
I don't think it's a dup of #3370.  I think it's just caused by the fact that when you drag rooms between empty sections, the size changes due to the drag hint, so if the mouse is in the right spot, then the section that the mouse is over will constantly change.

**Comment by lampholder** [comment] 2017-05-22 15:29
P2 rather than P1 just because (presumably) people don't see it that often?

**Comment by turt2live** [comment] 2020-07-10 03:09
Closing in favour of https://github.com/vector-im/riot-web/issues/8614

**Closed by turt2live** 2020-07-10 03:09 UTC
Labels: bug, cosmetic, p2, type:roomlist, ui/ux
