### ISSUE TITLE
Community panel : option to only show rooms without communities

### ISSUE THREAD

**Issue by Ezwen** [vector-im/riot-web#13534] opened 2020-05-06 08:37 UTC
**Is your suggestion related to a problem? Please describe.**

I am starting to use communities, and the left panel does nicely allow me to filter my rooms and only show rooms of one given community.

However, I have no way to easily access _the list of rooms that are not part of any of the communities I belong to_, while I often have this need.

**Describe the solution you'd like**

I would like to be able to ask Riot to only show me all _rooms that are part of no communities at all_. For instance, an icon similar to a community, but to trigger a filter only allowing "without communities" rooms.

**Comment by t3chguy** [comment] 2020-05-06 08:55
> only show rooms of one given community.

You can shift click multiple btw

**Comment by t3chguy** [comment] 2020-05-06 08:56
Duplicate of https://github.com/vector-im/riot-web/issues/8013

**Closed by t3chguy** 2020-05-06 08:56 UTC
Labels: suggestion

**Comment by Ezwen** [comment] 2020-05-06 09:04
Apologies for the duplicate, I did search before but strangely did not find the existing issue!
