### ISSUE TITLE
Smarter thumbnails

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#11951] opened 2020-01-20 19:49 UTC
Being able to set thumbnail size would be great, and having subsequent small thumbnails line up side-by-side would be even greater.
I realise that 10,000 different thumbnail sizes would be hard on the server, so this should presumably be a client thing, the server sending some 'maximum size thumbnail'.

**Comment by turt2live** [comment] 2020-01-20 19:51
Duplicate of https://github.com/vector-im/riot-web/issues/1520

**Closed by turt2live** 2020-01-20 19:51 UTC
