### ISSUE TITLE
"no visible files in this room" on desktop [but visible on Android]

### ISSUE THREAD

**Issue by Thatoo** [vector-im/riot-web#8712] opened 2019-02-15 18:27 UTC
### Description

In some chats, when I click on "Files", it says that "There are no visible files in this room" whereas Riot on Android shows me plenty of files.

### Steps to reproduce

- Go on one chat (same issue for direct chat or not)
- On the right, click on "Files"
- get the message "There are no visible files in this room"

I should have plenty of files listed.

![capture d ecran de 2019-02-15 19-14-09](https://user-images.githubusercontent.com/464782/52876112-8207ab80-3156-11e9-80be-799250ff4128.png)

In this chat there are files!

![capture d ecran de 2019-02-15 19-13-58](https://user-images.githubusercontent.com/464782/52876111-80d67e80-3156-11e9-8e34-51cb8a192fa7.png)

In this chat Files don't appear whereas if I go on Riot for Android, there are files as you can see in the following screenshot of the same room (I know it's not obvious because we can't read the name of room but it is the same room).

![screenshot_20190215-192242](https://user-images.githubusercontent.com/464782/52876373-5b964000-3157-11e9-8659-f74ae54d5da3.png)

My intuition make me think it is related to encryption. I mean, I feel that it happens to encrypted chats and not to non encrypted chat. Anyway, I don't understand why it works on Android and not on Desktop.

### Version information

- **Platform**: desktop
For the desktop app:

- **OS**: Ubuntu 18.04
- **Version**: 1.0.1

**Comment by turt2live** [comment] 2019-02-15 19:29
Duplicate of https://github.com/vector-im/riot-web/issues/4959

**Closed by turt2live** 2019-02-15 19:29 UTC
