### ISSUE TITLE
[Bug] "tm" character breaks URL hyperlinking in Riot desktop app

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#9318] opened 2019-03-28 23:02 UTC
No joke, the below URL breaks in riot:

https://www.corsair.com/ca/en/Categories/Products/Cases/Carbide-Series™-Air-240-High-Airflow-MicroATX-and-Mini-ITX-PC-Case/p/CC-9011070-WW

That's actually a full URL, and at the "tm" part riot stops hyperlinking the rest.

Versions
matrix-react-sdk version: <local>
riot-web version: 1.0.5
olm version: 3.0.0

**Comment by turt2live** [comment] 2019-03-28 23:16
Duplicate of https://github.com/vector-im/riot-web/issues/4932

**Closed by turt2live** 2019-03-28 23:16 UTC
Labels: bug

**Comment by BloodyIron** [comment] 2019-03-29 23:33
Oops! Sorry!
