### ISSUE TITLE
emoji autocomplete is case sensitive

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7199] opened 2018-08-20 16:14 UTC
- Go to composer
- Type :Three 
- Expect to have suggested :three:
- Actually have suggested :on:

**Comment by aaronraimist** [comment] 2018-09-19 02:01
Can't reproduce this in Riot 0.16.4 or current /develop

**Comment by turt2live** [comment] 2018-10-31 22:56
I also can't reproduce this - closing.

**Closed by turt2live** 2018-10-31 22:56 UTC
Labels: bug, minor, p2, ui/ux
