### ISSUE TITLE
Riot Desktop does not obey config.json on launch

### ISSUE THREAD

**Issue by drseussofporn** [vector-im/riot-web#9313] opened 2019-03-28 16:59 UTC
On installation of Riot Desktop 1.0.5 for Windows, I modified the config.json folder in %LOCALAPPDATA%\riot-web\app-1.0.5\resources\webapp with my own default_hs_url and default_is_url. When Riot Desktop is launched and the Sign In option is chosen, the default HS and IS urls (matrix.org and vector.im) are still present. However, if I change the language to something else (causing a refresh/update) my correct custom HS and IS options appear correctly. This seems to be the same issue as in #8730 

Steps to reproduce:
- On a fresh install of Riot Desktop, customize the HS and IS urls in config.json
- Launch Riot Desktop and click Sign In
- Observe the default HS and IS urls

Expected behavior: 
On launch, Riot should populate the correct settings from config.json

Version information:

- **Platform**: Desktop
- **OS**: Windows 10
- **Version**: 1.0.5

**Comment by turt2live** [comment] 2019-03-28 17:27
Duplicate of https://github.com/vector-im/riot-web/issues/9224

**Closed by turt2live** 2019-03-28 17:27 UTC
Labels: bug
