### ISSUE TITLE
Collapsing of widget is not remembered

### ISSUE THREAD

**Issue by nvbln** [vector-im/riot-web#5399] opened 2017-10-23 17:36 UTC
When opening a room with a widget, the widget will show. However, is the widget is not in use, it can get quite annoying when you have to collapse the widget every time you open that room. 

Wouldn't it be better to remember if a widget is collapsed so it stays collapsed until the user clicks on the widget bar again?

**Comment by t3chguy** [comment] 2017-10-23 17:49
Duplicate of https://github.com/vector-im/riot-web/issues/4850

**Closed by t3chguy** 2017-10-23 17:49 UTC
