### ISSUE TITLE
Show app bar button still visible when integrations disabled

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4877] opened 2017-08-24 23:45 UTC
### Description

The manage integrations button is hidden, but the show app bar is not.

### Steps to reproduce

- Remove the integration URLs from your riot config
- Visit a room

Log: not sent    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome 60
- **OS**: Windows 10
- **URL**: Internal. v0.12.2

**Comment by t3chguy** [comment] 2017-08-25 07:31
Duplicate of #4852

**Closed by t3chguy** 2017-08-25 07:31 UTC
