### ISSUE TITLE
Different logo for Riot Nightly

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12709] opened 2020-03-12 12:06 UTC
So we can tell them apart

Split from https://github.com/vector-im/riot-web/issues/12452

**Comment by dreadnaut** [comment] 2020-03-12 23:38
Out of nowhere, a "nightly" variation of the current logo:
![logo-nightly](https://user-images.githubusercontent.com/584584/76576590-6f2aec00-64ba-11ea-9177-b7d8d70b5daa.png)

[SVG version](https://github.com/vector-im/riot-web/files/4327090/logo-nightly.zip) (zipped, as GitHub does not accept SVG attachments.

**Comment by jryans** [comment] 2020-04-14 10:30
We've decided this is not a blocker for cross-signing release.

**Comment by t3chguy** [comment] 2020-04-14 10:35
Right now it looks like nightly has no icon at all however:
![image](https://user-images.githubusercontent.com/2403652/79215803-0b426d00-7e44-11ea-941c-3f7975fac469.png)

**Comment by turt2live** [comment] 2020-04-14 18:59
@t3chguy sounds like a bug with our electron upgrade: https://github.com/vector-im/riot-web/issues/12518

**Comment by t3chguy** [comment] 2020-04-14 19:01
I doubt it, all those reports are Linux caused by https://github.com/vector-im/riot-web/issues/12518#issuecomment-595780659
I use Windows

**Comment by turt2live** [comment] 2020-04-14 19:02
It's also fine for me:
![image](https://user-images.githubusercontent.com/1190097/79263483-261ade80-7e50-11ea-8b86-d9c850723d3c.png)

**Comment by t3chguy** [comment] 2020-04-14 19:03
Is it fine for you the moment the app starts?

**Comment by turt2live** [comment] 2020-04-14 19:05
Oh, nope. Let's track that separately: https://github.com/vector-im/riot-web/issues/13170

**Comment by turt2live** [comment] 2020-07-17 14:59
Closing in favour of https://github.com/vector-im/riot-web/issues/14592

**Closed by turt2live** 2020-07-17 14:59 UTC
Labels: blocked, feature:e2e-cross-signing, needs-design, phase:4, story:5
