### ISSUE TITLE
file upload CSS doesn't show when a file upload has failed

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9669] opened 2019-05-10 11:44 UTC
normal messages go red if they can't be sent right now. file upload localechoes do not, however

**Comment by turt2live** [comment] 2019-05-10 15:46
Duplicate of https://github.com/vector-im/riot-web/issues/3391

(insert sadface for 2017 issue here)

**Closed by turt2live** 2019-05-10 15:46 UTC
