### ISSUE TITLE
It should be possible to dismiss a profile view with a single, obvious click.

### ISSUE THREAD

**Issue by Caspy7** [vector-im/riot-web#12031] opened 2020-01-24 05:33 UTC
I'm using Mozilla's riot instance at chat.mozilla.org 

When I click on a user's avatar in the chat area a sidebar panel appears on the right.  I was done with it but could not for the life me find a simple way to dismiss it. I was expecting an X on the upper right. Eventually I clicked the arrow at the top left of the sidebar which gave me a list of users. From here it was *still* not apparent how to close the panel.  I eventually figured out to click one of the buttons in the toolbar.

It shouldn't take two non-obvious clicks just to close a profile view (which took only one click to get there. Like me, I'd expect most people to look for the X on the upper right, so how about do that?

**Comment by t3chguy** [comment] 2020-01-24 15:06
Duplicate of https://github.com/vector-im/riot-web/issues/11965

**Closed by t3chguy** 2020-01-24 15:06 UTC
Labels: bug, ui/ux
