### ISSUE TITLE
Read-receipts no longer collapse when you click on the expanded view

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3052] opened 2017-01-24 23:00 UTC
If you click on the 'n+' to expand RRs, you can no longer collapse them again by clicking on the expanded view. This got broken by https://github.com/matrix-org/matrix-react-sdk/pull/616

**Comment by JaniM** [comment] 2017-01-25 09:45
Specifically caused by https://github.com/matrix-org/matrix-react-sdk/pull/616/commits/959163f2ef0cd77bf0999061e810e17030766624#diff-c61f9e65499f25bdada51665a89137b7

This was a temporary fix. AccessibleButton inherently wraps a clickable element in a div. Because BaseAvatar now uses AccessibleButton when the avatar is clickable, this caused ReadReceiptMarkers to pop out of the read receipt field.

I think it can be fixed by giving the BaseAvatar button element a `element="span"`, but I haven't had the chance to test it. Relevant commit: https://github.com/matrix-org/matrix-react-sdk/pull/616/commits/959163f2ef0cd77bf0999061e810e17030766624#diff-1af0d2e8ab026c73cdb22e5550104ea0

**Comment by uhoreg** [comment] 2017-01-25 14:09
I don't know if it's related, but I used to be able to expand the RRs by clicking on the avatars or on the "+n", but now it looks like they only expand if I click on the "+n".  Clicking on the avatars now does nothing.

**Closed** 2017-02-02 17:45 UTC
Labels: regression
