### ISSUE TITLE
Error message for invalid m.room.encryption event is very bad

### ISSUE THREAD

**Issue by tulir** [vector-im/riot-web#14290] opened 2020-07-02 13:56 UTC
### Description

When sending a message to a room that contains a `m.room.encryption` event that riot can't handle (e.g. redacted, sent incorrectly, etc), riot shows an extremely unhelpful "Your message was not sent" notification. The notification contains absolutely no information why it was not sent, and it offers a "Resend message" button that doesn't work.

### Steps to reproduce

- Send a `m.room.encryption` state event with an unsupported algorithm or redact an existing `m.room.encryption` event
- Try to send a message

Expected result: useful error message that says the room is misconfigured or that the server is hiding the configuration, maybe offer a button to send a fixed encryption event if the user is admin.

Actual result: useless and confusing error message

![image](https://user-images.githubusercontent.com/4224639/86366695-c3352880-bc83-11ea-8bde-528df6580558.png)

This might also apply for 

### Version information

- **Platform**: web
- **Browser**: Firefox 79.0b2
- **OS**: Ubuntu 20.04
- **URL**: riot.im/develop

**Comment by t3chguy** [comment] 2020-07-02 14:17
Duplicate of https://github.com/vector-im/riot-web/issues/3498#issuecomment-288840814

**Closed by t3chguy** 2020-07-02 14:17 UTC
Labels: bug
