### ISSUE TITLE
Unable to list user devices as of Javascript error

### ISSUE THREAD

**Issue by Luzifer** [vector-im/riot-web#10865] opened 2019-09-13 17:00 UTC
### Description

After a new login in Riot.im in a clean browser profile I'm no longer able to list users devices as of a JS error (see attached StackTrace).

### Steps to reproduce

- Created a new browser profile
- Logged in with custom home-server
- Clicked on any user (no matter whether self or other user, no matter whether encrypted or unencrypted channel, no matter whether own or different home-server)
- See infinite spinner instead of user device list
- See attached StackTrace

Expectation: No errors, having a device list.

Logs being sent: yes

### Version information

- **Platform**: web, hosted on riot.im

```
matrix-react-sdk version: <local>
riot-web version: 1.3.4
olm version: 3.1.0
```

For the web app:

- **Browser**: Brave Version 0.70.93 Chromium: 76.0.3809.132 (Official Build) unknown (64-bit)
- **OS**: Arch Linux
- **URL**: riot.im/app

### JS StackTrace

```
Unhandled rejection TypeError: Cannot read property 'isSynapseAdministrator' of undefined
    at t.<anonymous> (https://riot.im/app/bundles/846f118…/bundle.js:118:399852)
    at E (https://riot.im/app/bundles/846f118…/bundle.js:30:95839)
    at Generator._invoke (https://riot.im/app/bundles/846f118…/bundle.js:30:95627)
    at Generator.e.<computed> [as next] (https://riot.im/app/bundles/846f118…/bundle.js:30:96018)
    at Generator.c (https://riot.im/app/bundles/846f118…/bundle.js:1:85751)
    at f._promiseFulfilled (https://riot.im/app/bundles/846f118…/bundle.js:1:42623)
    at t.<anonymous> (https://riot.im/app/bundles/846f118…/bundle.js:1:44650)
From previous event:
    at D.B [as _captureStackTrace] (https://riot.im/app/bundles/846f118…/bundle.js:1:28634)
    at new f (https://riot.im/app/bundles/846f118…/bundle.js:1:41498)
    at t.<anonymous> (https://riot.im/app/bundles/846f118…/bundle.js:1:44587)
    at t.e.exports.h.default.createClass._updateStateForNewMember (https://riot.im/app/bundles/846f118…/bundle.js:118:387528)
    at t.componentDidMount (https://riot.im/app/bundles/846f118…/bundle.js:118:384963)
    at t.componentDidMount (https://riot.im/app/bundles/846f118…/bundle.js:71:5917)
    at e.notifyAll (https://riot.im/app/bundles/846f118…/bundle.js:63:99322)
    at d.close (https://riot.im/app/bundles/846f118…/bundle.js:73:60347)
    at d.closeAll (https://riot.im/app/bundles/846f118…/bundle.js:46:13975)
    at d.perform (https://riot.im/app/bundles/846f118…/bundle.js:46:13470)
    at v.perform (https://riot.im/app/bundles/846f118…/bundle.js:46:13387)
    at v.perform (https://riot.im/app/bundles/846f118…/bundle.js:23:62482)
    at Object.E [as flushBatchedUpdates] (https://riot.im/app/bundles/846f118…/bundle.js:23:62651)
    at u.closeAll (https://riot.im/app/bundles/846f118…/bundle.js:46:13975)
    at u.perform (https://riot.im/app/bundles/846f118…/bundle.js:46:13470)
    at Object.batchedUpdates (https://riot.im/app/bundles/846f118…/bundle.js:63:113623)
    at Object.e [as enqueueUpdate] (https://riot.im/app/bundles/846f118…/bundle.js:23:62985)
    at a (https://riot.im/app/bundles/846f118…/bundle.js:60:5967)
    at Object.enqueueSetState (https://riot.im/app/bundles/846f118…/bundle.js:60:6798)
    at t.s.setState (https://riot.im/app/bundles/846f118…/bundle.js:63:96196)
    at t.value (https://riot.im/app/bundles/846f118…/bundle.js:30:78480)
    at t.e._invokeCallback (https://riot.im/app/bundles/846f118…/bundle.js:78:200999)
```

**Comment by t3chguy** [comment] 2019-09-13 17:03
Duplicate of #10854

**Closed** 2019-09-13 17:03 UTC
Labels: bug
