### ISSUE TITLE
Feature Request : Fully support logging into MULTIPLE servers like Quaternion.

### ISSUE THREAD

**Issue by mistergibson** [vector-im/riot-web#12411] opened 2020-02-18 19:50 UTC
**Is your suggestion related to a problem? Please describe.**

I simply need to log into multiple non-federated servers. I *could* use Quaternion, but your GUI is sooo much better than that one. Also, your jitsi integration is great and missing on Quaternion.

**Describe the solution you'd like**

Internally, make your user server-profiles stackable in series - one for each user login/server session. I actually like how Quaternion mixes all the user's rooms of all servers into a single list, but you might make a checkbox enable/disable for that. You might want to make a tab on the top of the window for each server if you feel separating them is more desirable. The bottom line is I *need* to log into multiple servers that will never be federated.

**Describe alternatives you've considered**

Pestering Quaternion devs to make theirs more like yours -- but seems a low activity project.

**Additional context**

N/A

**Comment by turt2live** [comment] 2020-02-18 20:06
Duplicate of https://github.com/vector-im/riot-web/issues/2320

**Closed by turt2live** 2020-02-18 20:06 UTC
Labels: suggestion
