### ISSUE TITLE
Experimental: Mashing text in to the room filter can freeze the whole app

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7926] opened 2018-12-20 15:01 UTC
No logs 'cause it ded.

I've seen this now on two occasions; it's occurred when I've mistyped what I'm trying to filter a few times and then mashed a bunch of stuff in frustration (this detail may or may not be important)

**Comment by lampholder** [comment] 2018-12-20 15:02
Another clue: the processor goes nuts, so some sort of infinite loop might be occurrign.

**Comment by jryans** [comment] 2018-12-20 16:33
From the profile @lampholder shared, this is caused by an infinite loop in `_onMoveFocus` from `LeftPanel.js`. I'll keep digging.

**Comment by jryans** [comment] 2018-12-20 20:20
Steps to reproduce:

1. Enter enough random characters in room filter so that no rooms match
2. Press the Enter key

**Comment by jryans** [comment] 2018-12-20 23:09
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2380.

**Closed by jryans** 2018-12-20 23:09 UTC
Labels: bug, major, p1, regression
