### ISSUE TITLE
Community Invites have no context menu

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5918] opened 2018-01-04 11:05 UTC
related to #5917

**Comment by turt2live** [comment] 2018-04-12 21:07
Duplicate of https://github.com/vector-im/riot-web/issues/5527

**Comment by t3chguy** [comment] 2018-06-12 13:52
Progress 
![image](https://user-images.githubusercontent.com/2403652/41294547-32c76a98-6e50-11e8-9c36-04eefceeddf1.png)

**Closed** 2018-06-14 16:33 UTC
Labels: bug, p1, type:communities, ui/ux
