### ISSUE TITLE
Highlights have the "hover" style on latest develop

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#10255] opened 2019-07-04 10:37 UTC
![image](https://user-images.githubusercontent.com/5547783/60660574-f1eda880-9e4f-11e9-8095-c9c94144d6d0.png)

I've noticed that since yesterday (at least) the messages containing my name or a highlight keyword have the same style as when I place my cursor over them. I've observed this on latest develop.

**Comment by turt2live** [comment] 2019-07-04 14:31
Duplicate of https://github.com/vector-im/riot-web/issues/10248

**Closed by turt2live** 2019-07-04 14:31 UTC
