### ISSUE TITLE
Not able to join room

### ISSUE THREAD

**Issue by MichaelKohler** [vector-im/riot-web#11180] opened 2019-10-21 18:37 UTC
### Description

I tried to join https://riot.im/develop/#/room/#riot-web:matrix.org but when clicking the "Join" button it crashed.

### Steps to reproduce

- Use riot.im develop version
- Try to join #riot-web:matrix.org

### Version information

- **Browser**: Firefox Nightly
- **OS**: macOS 10.14.6
- **URL**: riot.im/develop

**Comment by MichaelKohler** [comment] 2019-10-21 18:37
I've just now also sent debug logs.

**Comment by MichaelKohler** [comment] 2019-10-21 18:38
"Clear cache and reload" helped.

**Comment by turt2live** [comment] 2019-10-21 19:16
Duplicate of https://github.com/vector-im/riot-web/issues/11120 (same stacktrace)

**Closed by turt2live** 2019-10-21 19:16 UTC
