### ISSUE TITLE
The Enabling of "Enable email notifications" is not being saved when Signing Out.

### ISSUE THREAD

**Issue by cusco-travel-services** [vector-im/riot-web#13796] opened 2020-05-24 22:44 UTC
### Description

The Enabling of the Option "Enable email notifications" is not being saved when Signing Out.

### Steps to reproduce

My Sister and I have Riot Desktop 1.6.2 installed on MX Linux 19.1.

Both of us have added an email address to our accounts within the General category of our Account Settings.

We also configured our Notifications to "Enable email notifications".

However, when I Sign-out, this option is being Disabled and I have not been able to receive any notifications. I know this because, when I Sign-in, "Enable email notifications" is disabled again. This problem has not occurred for my Sister.

I have tried more than 1 email address, including an, ugh, Gmail address, but it makes no difference.

All other changes to various options are being saved but not for this one. Why is MY "Enable email notifications" setting not being saved?

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: MX Linux 19.1
- **Version**: riot-web version: 1.6.2, olm version: 3.1.3

**Comment by turt2live** [comment] 2020-05-25 02:04
Duplicate of https://github.com/vector-im/riot-web/issues/6072

**Closed by turt2live** 2020-05-25 02:04 UTC
Labels: bug
