### ISSUE TITLE
Allow continuable up- and downloads

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#12392] opened 2020-02-16 22:47 UTC
Is it very frustrating (especially if one is poor and has to pay for the connection) to see an almost-finished up- or download break down, and then have to restart from scratch.  Allowing continuation from where it broke of would be much better.

**Comment by t3chguy** [comment] 2020-02-16 22:48
Duplicate of #10695

**Closed** 2020-02-16 22:49 UTC

**Comment by Biep** [comment] 2020-02-19 21:14
Oops - sorry!
