### ISSUE TITLE
Upgrade encryption button not working

### ISSUE THREAD

**Issue by GirardR1006** [vector-im/riot-web#12309] opened 2020-02-10 18:37 UTC
### Description

Upgrade encryption button not working in develop version

### Expected behaviour

Encryption upgrade should proceed when clicked on the corresponding button

### Actual behaviour

Nothing happens

Screenshot:

![image](https://user-images.githubusercontent.com/19275558/74178615-27574180-4c3c-11ea-9bbe-57adced33399.png)

Logs being sent: yes

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 72.0.2
- **OS**: Arch Linux
- **URL**: riot.im/develop

**Comment by TestardR** [comment] 2020-02-10 20:23
@GirardR1006 I can't reproduce. It proceeds on both Firefox and Chrome. 
![image](https://user-images.githubusercontent.com/40339476/74186813-9d16d980-4c4b-11ea-9f2b-302efbfc4fdc.png)

**Comment by GirardR1006** [comment] 2020-02-10 21:00
I have ublock origin, cookie autodelete and noscript activated.
Just tested on Chrome 77.0.3865.120, cannot proceed either.

I sent logs using the built-in tool inside of riot-web, hoping it contains more info.

**Comment by jryans** [comment] 2020-03-11 15:31
@GirardR1006 I believe this may be fixed now, could you please retest?

**Comment by jryans** [comment] 2020-03-12 16:55
I am fairly sure this is fixed now, but if not, please comment and reopen.

**Closed by jryans** 2020-03-12 16:55 UTC
Labels: bug, cross-signing-sprint, phase:2, story:1, ui/ux
