### ISSUE TITLE
matrix.to links posted in a room take you to a browser

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#14652] opened 2020-07-20 12:31 UTC
Rather than the expected join preview. E.g. https://matrix.to/#/!EgoVrPyOnPSVXERlxj:gruenhage.xyz/$jT9sVwWkLXlpHXS67URk4UT9p3yPIkla6rSk1TsQH1Y?via=half-shot.uk&via=matrix.org&via=maunium.net

I don't remember if this is an actual bug or not-a-feature-yet, but I'd expect my client to navigate to the room when I click on a matrix.to url.

**Comment by t3chguy** [comment] 2020-07-20 12:33
Cannot reproduce

**Comment by t3chguy** [comment] 2020-07-20 12:33
![14652](https://user-images.githubusercontent.com/2403652/87937951-a1161580-ca8d-11ea-9ec2-dafc33ed9ad1.gif)

**Comment by t3chguy** [comment] 2020-07-20 12:56
Duplicate of https://github.com/vector-im/riot-web/issues/3681

**Closed by t3chguy** 2020-07-20 12:56 UTC
Labels: bug, cannot-reproduce
