### ISSUE TITLE
Launching the app with the roomlist collapsed leaves the contents collapsed when you re-expand it.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14816] opened 2020-07-29 15:50 UTC
<img width="259" alt="Screenshot 2020-07-29 at 16 49 35" src="https://user-images.githubusercontent.com/1294269/88822295-93623d80-d1bb-11ea-9526-1a164ad4262a.png">

**Comment by t3chguy** [comment] 2020-07-29 15:51
Duplicate of https://github.com/vector-im/riot-web/issues/14782

**Closed by t3chguy** 2020-07-29 15:51 UTC
Labels: bug
