### ISSUE TITLE
ILAG Branch: Captcha gets stuck on screen

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4095] opened 2017-05-30 20:27 UTC
### Description

![image](https://cloud.githubusercontent.com/assets/1190097/26603344/bd1ee4dc-4543-11e7-9ac8-b5af6b975975.png)

No errors in console.

### Steps ~~to reproduce~~ used to cause this

- Go to root and be redirected to `#/home`
- Click 'start chat' in left sidebar
- Get prompted for username
- Press enter after entering username
- Get captcha
- Complete challenges (checkbox + street signs in this case)
- Dialog disappears, popover stays

Popover disappears after clicking elsewhere.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 53
- **OS**: Windows 10
- **URL**: localhost, built against https://github.com/vector-im/riot-web/commit/d264426ece53c71c3b60f724fa723f0d240b5525 and https://github.com/matrix-org/matrix-react-sdk/commit/c15568e003a9a32c37bf6600b796698cea66cd41

**Comment by lampholder** [comment] 2017-05-31 14:50
Additional datapoint: the captcha has worked properly for me on Chrome.

**Comment by turt2live** [comment] 2017-05-31 15:20
I've managed to get it stuck on Chrome. Only when it gives me a prompt to pick street signs though

**Comment by lampholder** [comment] 2017-06-01 10:34
I have now managed to reproduce this on FF. Googling doesn't easily reveal this to be a problem for anybody else (unsurprisingly, since Google probably know what they're doing with CAPTCHAs).

I've dumped the logs for my session but it doesn't look like it contains anything useful.

**Comment by lukebarnard1** [comment] 2017-06-01 10:48
My theory on this is that the recapcha thing is supposed to be closed by the tick box element. This is an iFrame(?) that is presumably being replaced by a spinner too quickly, so the dialog doesn't receive the `postMessage` to close?

**Comment by lampholder** [comment] 2017-06-01 10:50
Yeah, the recaptcha box is an iframe.

**Comment by lampholder** [comment] 2017-06-01 12:44
Since this does go away if the user clicks elsewhere on the screen, I'm going to remove the `release-blocker` label on this.

**Comment by turt2live** [comment] 2017-06-05 14:20
When I was testing it was 100% guaranteed on Chrome. It is possible that something changed in the branch to fix this, however. I'll re-test and see if it is still an issue.

**Comment by Matrixcoffee** [comment] 2017-06-15 19:33
I reproduced this as well.

**Comment by ara4n** [comment] 2017-06-15 23:15
marking as release blocker as this sounds like a reallt minging regression :(

**Comment by dbkr** [comment] 2017-06-16 09:30
Fixed

**Closed by dbkr** 2017-06-16 09:30 UTC
Labels: bug, major, p1, release-blocker, type:signup, ui/ux
