### ISSUE TITLE
Search in rooms doesn't expand closed sections

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6689] opened 2018-05-09 16:13 UTC
eg. search for a person, the people section is closed, they're in the results but the section remains closed so it's non-obvious it's found them

**Comment by lampholder** [comment] 2018-05-15 10:26
The search UX is having some design love applied currently :)

**Comment by turt2live** [comment] 2018-05-25 22:42
Duplicate of https://github.com/vector-im/riot-web/issues/4364

**Closed** 2018-05-25 22:44 UTC
Labels: bug, minor, p2, ui/ux
