### ISSUE TITLE
Phantom Scrollbar

### ISSUE THREAD

**Issue by pixlwave** [vector-im/riot-web#8649] opened 2019-02-14 19:02 UTC
- **Browser**: Riot.app desktop wrapper app - 1.0.0
- **OS**: macOS 10.14

### Description

If you mouse over the blue bar on the left of the window, a phantom scroll bar appears:
<img width="141" alt="screenshot 2019-02-14 at 18 35 55" src="https://user-images.githubusercontent.com/6060466/52810557-bf9f0280-308a-11e9-86b9-6bd307a42dc8.png">

### Steps to reproduce

- Using a laptop with just the trackpad (no mouse but not tested with a mouse).
- Move the cursor over the blue bar on the left.
- The scroll bar appears!

I wouldn't expect to see a scroll bar.

Log: not sent?

**Comment by turt2live** [comment] 2019-02-14 19:05
Duplicate of https://github.com/vector-im/riot-web/issues/8197

**Closed by turt2live** 2019-02-14 19:05 UTC
Labels: redesign

**Comment by pixlwave** [comment] 2019-02-14 19:18
Ah sorry, I did try and search for this but didn't know it was called the LLP, so didn't find that issue.
