### ISSUE TITLE
Feature request: auto-play externally linked gifs and gif-like videos (through hostname whitelist for gif-like video sharing platforms) in chat thumbnail

### ISSUE THREAD

**Issue by ell1e** [vector-im/riot-web#14567] opened 2020-07-17 04:10 UTC
**Is your suggestion related to a problem? Please describe.**
The easiest way to link GIFs without bothering to configure anything is to just paste a GIF url, which usually links either to a .gif directly or to an .mp4 directly from a major gif sharing site like giphy or imgur. I use this in all other messengers where it works fine, but in riot/element/matrix it results in a static preview and people need to click it for auto-play which is super clumsy. As pointed out in #2433 linking gifs is a pretty common alternative so it'd be cool if that also work

**Describe the solution you'd like**
Auto-play any linked gifs in the thumbnail preview, and auto-play (without sound!) any directly linked video if it comes from a user-configurable host whitelist (should be in local user settings) that should default to major gif sharing platforms.

**Describe alternatives you've considered**
There do appear to be more direct gif integrations already. But they need to be manually activated first, and also if I copy a giphy link from elsewhere (like some Telegram friend) into matrix that won't work then, right?

**Additional context**

**Comment by t3chguy** [comment] 2020-07-17 07:12
Duplicate of https://github.com/vector-im/riot-web/issues/7473

**Closed by t3chguy** 2020-07-17 07:12 UTC
Labels: suggestion

**Comment by ell1e** [comment] 2020-07-17 07:39
@t3chguy wait, but doesn't ask #7434 to *stop* autoplay of certain things? but linking mp4s just never seems to autoplay, so kind of the opposite problem

**Comment by t3chguy** [comment] 2020-07-17 07:45
Its up to the server whether you get sent a still image of a GIF URL Preview or the GIF, I'd suggest a Synapse bug
