### ISSUE TITLE
Riot doesn't show redacted member events

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#5954] opened 2018-01-09 11:41 UTC
It should show them with the name/avatar blanked out so you still know someone's joined/left/whatever

**Comment by pafcu** [comment] 2018-01-09 13:35
Related/ duplicate of https://github.com/vector-im/riot-web/issues/5684

**Comment by lampholder** [comment] 2018-01-11 13:29
Agreed dup.

**Closed by lampholder** 2018-01-11 13:29 UTC
Labels: duplicate
