### ISSUE TITLE
@admins and @mods to write to all admins/mods

### ISSUE THREAD

**Issue by jo-so** [vector-im/riot-web#13698] opened 2020-05-16 18:48 UTC
**Is your suggestion related to a problem? Please describe.**
When someone is flooding a room with spam, it's time consuming to go to the settings of the room and lookup the admins and mods there, write there names on a paper, close the dialogue and message them.

**Describe the solution you'd like**
It would be helpful if every user could write to @admins or @mods in every room and the admins resp. moderators get this message.###

**Comment by TheDiscordian** [comment] 2020-05-17 20:41
Discord solves this with roles that can be tagged in a conversation exactly like this `@admins`. I've been thinking about this issue lately, and we're going to be mitigating it with a bot in my rooms.

As flairs seem related to Discord's roles, would it be possible to make it so flairs can be tagged in chat, enabling all users of a specific community in a specific room receive a notification? Would that be an acceptable solution to this problem? This is my ideal solution to this problem.

Currently we're mitigating this issue by having users carrying out a specific role set keywords, but there's no way to verify what keywords a person has. Additionally someone might not want the "admin" keyword for example to ping them everywhere.

**Comment by turt2live** [comment] 2020-05-18 06:28
Duplicate of https://github.com/vector-im/riot-web/issues/8147

**Closed by turt2live** 2020-05-18 06:28 UTC
Labels: suggestion
