### ISSUE TITLE
404 on Desktop Download Site

### ISSUE THREAD

**Issue by PapiPyro** [vector-im/riot-web#9473] opened 2019-04-15 04:34 UTC
### Description

The link to download Riot leads to a 404'd web page at https://riot.im/download/desktop

### Steps to reproduce

- Go to https://about.riot.im/downloads
- Select "macOS, Windows & Linux" option
- 404 page https://riot.im/download/desktop

![image](https://user-images.githubusercontent.com/45219403/56107776-2ec39680-5f16-11e9-8051-c89f47775a4a.png)

- **Platform**: web download page lol

**Comment by turt2live** [comment] 2019-04-15 05:38
Duplicate of https://github.com/vector-im/riot-web/issues/9453

**Closed by turt2live** 2019-04-15 05:38 UTC
