### ISSUE TITLE
Allow choice of preferred color for nicknames

### ISSUE THREAD

**Issue by Kommynct** [vector-im/riot-web#14024] opened 2020-06-14 02:49 UTC
**Is your suggestion related to a problem? Please describe.**
Currently it seems that nickname colors are completely random

**Describe the solution you'd like**
An option to choose between the colors and assign it to your profile, call it the favorite color of the user. It adds a little nice customization and could also be used to color the accents/other things.

**Describe alternatives you've considered**
I've considered having the user set colors for every other person with a pre-set default, i'm unsure if that'd be better.

**Comment by t3chguy** [comment] 2020-06-14 12:03
Duplicate of https://github.com/vector-im/riot-web/issues/11816

**Closed** 2020-06-26 01:19 UTC
Labels: suggestion
