### ISSUE TITLE
No keyboard shortcut for changing rooms in responsive mode

### ISSUE THREAD

**Issue by telmich** [vector-im/riot-web#12327] opened 2020-02-11 22:53 UTC
Referring to #12279 for base information

The current mapping of Ctrl-k in desktop mode allows to navigate between rooms. As soon as the responsive mode is activated, this shortcut is disabled. 

From an UX point of view this is a rather strange behaviour that the web app looses a feature, when it goes responsive

**Comment by t3chguy** [comment] 2020-02-11 23:14
Duplicate of https://github.com/vector-im/riot-web/issues/11365

**Closed by t3chguy** 2020-02-11 23:14 UTC
Labels: bug, ui/ux
