### ISSUE TITLE
can not cancel invite to non exist room

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-web#12277] opened 2020-02-07 03:52 UTC
Steps to reproduce:

1.  Whatsapp-bridge try create room and invite me to this room
2. It can not create room (said FORBITTEN to log), but invite send to me success
3. In riot web I try accept this invite and get: No known servers
4. In riot web I try cancel this invite and get: M_UNKNOWN: Not a known room
5. I can not remove this invite from riot-web. Only some number of "clear cache" help to remove this "bad invite".

I think  that "cancel invite" must remove invite force, even if server return error.

Ubuntu 16.04 amd64
matrix-react-sdk: <local>
riot-web: 1.5.6
olm: 3.1.3

**Comment by t3chguy** [comment] 2020-02-07 04:49
Duplicate of https://github.com/vector-im/riot-web/issues/3743

**Closed by t3chguy** 2020-02-07 04:49 UTC
Labels: bug
