### ISSUE TITLE
When clicking on a reply, please take me to the replied message!

### ISSUE THREAD

**Issue by ludwigbald** [vector-im/riot-web#14101] opened 2020-06-18 21:19 UTC
**Is your suggestion related to a problem? Please describe.**
Nothing happens when I click on a reply.

**Describe the solution you'd like**
It should take me to the replied message and highlight it. That's the way WhatsApp does it, and it makes a lot of sense!

**Comment by t3chguy** [comment] 2020-06-18 21:29
Click on the timestamp, as for all permalinks.

![image](https://user-images.githubusercontent.com/2403652/85073702-29657a00-b1b3-11ea-996b-9a28a326ebd8.png)

**Comment by t3chguy** [comment] 2020-06-18 21:29
Duplicate of https://github.com/vector-im/riot-web/issues/7151

**Closed by t3chguy** 2020-06-18 21:29 UTC
Labels: suggestion
