### ISSUE TITLE
Avatar Privacy

### ISSUE THREAD

**Issue by gsantner** [vector-im/riot-web#6850] opened 2018-06-07 15:13 UTC
Copy on request from riot-android <https://github.com/vector-im/riot-android/issues/2346>

----

Hi, as it seems like there is only support for one user picture (which can everybody see) - I thought to ask if that is gonna change at some point.

A user might want to use a personal picture that personal friends/family can only see, while public/all others see another - without face e.g..

Is there any support in Matrix for this or if not, is there any way this privacy option may get added? This is currently a public leaking bit of information.

---

**Comment by t3chguy** [comment] 2018-06-07 15:17
Profile Pictures are actually per-room. There is just no UI for this.

Duplicate of https://github.com/vector-im/riot-web/issues/5488

**Closed by t3chguy** 2018-06-07 15:17 UTC

**Comment by gsantner** [comment] 2018-06-08 22:02
but it is somewhat lowest priority or what does p3 mean?

**Comment by t3chguy** [comment] 2018-06-08 22:06
See the readme for an explanation of the issue labels

**Comment by gsantner** [comment] 2018-06-08 22:27
@turt2live thats basically my point, yes

**Comment by gsantner** [comment] 2018-07-03 10:23
See comment https://github.com/vector-im/riot-android/issues/2346 too. Have more info and full explainatiom posted there whats the problem. For me high privacy is very important.

@t3chguy  @turt2live
