### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by barkingbandicoot** [vector-im/riot-web#11026] opened 2019-10-02 06:04 UTC
**Is your suggestion related to a problem? Please describe.**

Could you please add the option to adjust font size.
**Describe the solution you'd like**

I would like the option to enlarge the text. My ageing eyes find it difficult to read.

Thanks!

**Comment by t3chguy** [comment] 2019-10-02 12:45
Duplicate of #3160

**Closed by t3chguy** 2019-10-02 12:45 UTC
Labels: suggestion
