### ISSUE TITLE
New room list: I somehow managed to collapse only one section

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#14838] opened 2020-07-31 06:36 UTC
### Description

![image](https://user-images.githubusercontent.com/1342360/89007224-463bb400-d300-11ea-8516-b28924740915.png)

### Steps to reproduce

I think it was a combination of rotating my screen and changing the app zoom level (ctrl-+).

It seems to have fixed itself after waiting 30s though.

Logs being sent: yes

### Version information

- **Platform**: desktop nightly
- **OS**: Manjaro Linux
- **Version**: 2020072901

**Comment by turt2live** [comment] 2020-07-31 12:02
Duplicate of https://github.com/vector-im/riot-web/issues/14782

**Closed by turt2live** 2020-07-31 12:02 UTC
Labels: bug
