### ISSUE TITLE
Can not close invitation

### ISSUE THREAD

**Issue by HKalbasi** [vector-im/riot-web#13690] opened 2020-05-15 19:43 UTC
### Description
I can not reject invitation or accept it. I get a "no known server error" and nothing happend.
There is always a noise for this invite in my riot notifications.

### Steps to reproduce
I am not sure, but I think if you send an invite from a server and then close it, this will be happend.

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox? 76
- **OS**: Ubuntu
- **URL**: chat.mozilla.org

**Comment by turt2live** [comment] 2020-05-15 19:51
Duplicate of https://github.com/vector-im/riot-web/issues/3743 or some variant.

Try going to Settings -> Help -> Clear Cache and Reload to clear it. If that doesn't work, visit #riot-web:matrix.org for support.

**Closed by turt2live** 2020-05-15 19:51 UTC
Labels: bug

**Comment by HKalbasi** [comment] 2020-05-16 03:03
Solved. Thank you
