### ISSUE TITLE
"Restoring keys from backup" not working

### ISSUE THREAD

**Issue by jluttine** [vector-im/riot-web#13657] opened 2020-05-13 12:58 UTC
### Description

Verification, cross-signing and/or key backup doesn't work on Desktop.

### Steps to reproduce

On Android:

- Use an existing account in Riot X Android and set up the new encryption stuff.

On Desktop:

- Remove existing Riot config from the desktop so it's clean and fresh:

```
rm -r ~/.config/Riot
```

- Open Riot Desktop.

- Sign in with the same existing user account

- Riot says: "Upgrade your encryption". Enter password and click Next.

- Riot says: "Restoring keys from backup. Fetching keys from server...". It stays like this forever (at least 15 minutes). I think one time it finished with some error message after a very long wait, but I'm not sure.

- Click x to stop this step and click skip, skip, skip to skip this step for now.

- Open settings -> Security & Privacy.

- Click "Connect this session to Key Backup" -> The same issue as before. "Restoring keys from backup" forever..

- Cancel, and back to settings -> Security & Privacy

- Cross-signing advanced section looks like:

```

Cross-signing public keys: | not found
-- | --
Cross-signing private keys: | not found
Self signing private key: | not found locally
User signing private key: | not found locally
Session backup key: | not found locally
Secret storage public key: | not found
Homeserver feature support: | exists
Secret Storage key format: | up to date
```

- Click "Bootstrap cross-signing and secret storage". Takes a few minutes, then an error message: "Unable to query secret storage status".

- Sh*t. Well, let's try to verify from the Android device!

On Android:

- Settings -> Security & Privacy -> Show All Sessions.

- Click "Riot Desktop on Linux" session, "Manually Verify by Text" -> "Verify" -> BOOM -> "RiotX has stopped".

I have no more ideas what to try. Nothing works.

Logs being sent: yes/no

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Linux (NixOS)
- **Version**: 1.6.0

**Comment by jluttine** [comment] 2020-05-13 13:03
Possibly duplicate of https://github.com/vector-im/riot-web/issues/13481, at least for some parts. I don't really know Riot too well to say whether they are exactly the same issue or not.

**Comment by dbkr** [comment] 2020-05-14 10:28
This does sound like a dupe of #13481 or possibly https://github.com/vector-im/riot-web/issues/9425, so let's track there.

**Closed by dbkr** 2020-05-14 10:28 UTC
Labels: bug, feature:e2e-cross-signing, phase:4

**Comment by jluttine** [comment] 2020-06-23 11:14
Just to confirm that this is now fixed. It was broken in 1.6.0 but works in 1.6.5. (Probably some version in between contained the fix but I didn't bother figuring that out as the information that 1.6.5 works was sufficient to me.)
