### ISSUE TITLE
Markdown in Links

### ISSUE THREAD

**Issue by CryptKid** [vector-im/riot-web#6630] opened 2018-04-28 10:24 UTC
Riot compiles Links as Markdown and brakes them

If someone sends a link that contains elements like * Markdown interprets, the link is broken

Could you please fix this by disabling md for areas detected as links?

![grafik](https://user-images.githubusercontent.com/30263141/39395396-8a27c2f0-4ade-11e8-9223-133295725297.png)

### Version information
riot-web: 0.14.1
olm: 2.2.1
as Desktop application
running on Kubuntu 18.04
Or on Arch Linux
or using Android App

**Comment by t3chguy** [comment] 2018-04-28 10:29
The issue is that would mean writing a custom Markdown parser that would not comply with the Commonmark specification that is in use by riot-web. There have been talks of switching to GFM which doesn't have this issue.

**Comment by aaronraimist** [comment] 2020-01-17 22:57
Duplicate of #4674

**Closed by aaronraimist** 2020-01-17 22:57 UTC
Labels: bug, feature, major, p1, type:timeline
