### ISSUE TITLE
ability to lock down jitsi to the right matrix users

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13482] opened 2020-05-02 22:05 UTC
ideally we need the ability to restrict access to jitsi conferences to those present in the relevant matrix rooms, to stop your jitsi server becoming a free-for-all for everyone who stumbles across it with a web browser

**Comment by turt2live** [comment] 2020-05-04 17:47
duplicate of https://github.com/vector-im/riot-web/issues/13074

**Closed by turt2live** 2020-05-04 17:47 UTC
Labels: type:jitsi
