### ISSUE TITLE
element-desktop not starting under Debian Buster

### ISSUE THREAD

**Issue by rupi-lol** [vector-im/riot-web#14486] opened 2020-07-15 14:02 UTC
### Description

element-desktop doesn't start using Debian Buster

Error: 
Trace/breakpoint trap

### Steps to reproduce

- installed element-desktop from riot.im/packages/debian ("upgrade" from riot-desktop 1.6.8)
- start fails with: Trace/breakpoint trap

- tried --no-sandbox:
- start fails with: FATAL:platform_shared_memory_region_posix.cc

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Debian Buster
- **Version**: 1.7.0

**Comment by t3chguy** [comment] 2020-07-15 14:03
Duplicate of https://github.com/vector-im/riot-web/issues/13171

**Closed by t3chguy** 2020-07-15 14:03 UTC
Labels: bug

**Comment by jryans** [comment] 2020-07-16 13:58
To be clear, we do intend to fix both this issue and the linked nightly one in a set of releases today.
