### ISSUE TITLE
1-to-1 encrypted rooms don't show files in the files-tab

### ISSUE THREAD

**Issue by schiessle** [vector-im/riot-web#10653] opened 2019-08-25 12:16 UTC
I'm using Riot 1.3.2 both in the browser and as desktop app. I just noticed that the files tab on the right sidebar is empty, even that multiple pictures has been share to the room. The room is a 1-to-1 room with end-to-end encryption enabled.

![image](https://user-images.githubusercontent.com/1589737/63649823-e8dbd200-c742-11e9-9976-e747ff3a40f6.png)

Is this a known issue?

**Comment by t3chguy** [comment] 2019-08-25 12:29
This is because the tab is generated server side and the server can't tell which messages are files so only shows the files before encryption was enabled currently

**Comment by turt2live** [comment] 2019-08-25 19:19
Duplicate of https://github.com/vector-im/riot-web/issues/4959

**Closed by turt2live** 2019-08-25 19:19 UTC
Labels: bug
