### ISSUE TITLE
Massive pills don't wordwrap sanely

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8920] opened 2019-02-24 22:51 UTC
<img width="706" alt="screenshot 2019-02-24 at 22 51 25" src="https://user-images.githubusercontent.com/1294269/53306578-c39b0380-3886-11e9-99aa-d39f694b3ac3.png">

**Comment by turt2live** [comment] 2019-02-24 23:51
Duplicate of https://github.com/vector-im/riot-web/issues/6023

**Closed by turt2live** 2019-02-24 23:51 UTC
