### ISSUE TITLE
Read receipts are covered up when hovering over a message

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#7608] opened 2018-10-26 14:58 UTC
When there are lots of read receipts you can expand them, but then when you go to hover over them they get covered by the grey background of the message, like so:

![screenshot from 2018-10-26 15-52-07](https://user-images.githubusercontent.com/8428120/47574605-e26ca600-d937-11e8-98ae-059005cd49d7.png)

**Comment by turt2live** [comment] 2018-10-26 15:03
Duplicate of https://github.com/vector-im/riot-web/issues/6152

(due to https://github.com/vector-im/riot-web/issues/6152#issuecomment-406427348)

**Comment by erikjohnston** [comment] 2018-10-26 15:07
I'd honestly vote that we close #6152 and reopen this one, since it a) did get fixed and b) its really quite difficult to find issues if their titles and descriptions don't match actually match the bug.

**Comment by lampholder** [comment] 2018-11-01 12:03
Let's not port this bug into the redesign :D

**Comment by ara4n** [comment] 2019-06-04 11:32
> Let's not port this bug into the redesign :D

we ported the bug into the redesign.

meanwhile, if nothing else, it undermines my demos - being able to say "look at all the users who read this message!" only for the highlight to hide them feels shonky at best.

**Closed** 2019-06-06 13:22 UTC
Labels: bug, minor, p1, ui/ux
