### ISSUE TITLE
Device/session/backup/cross-signing verification broken after client upgrade.

### ISSUE THREAD

**Issue by erAck** [vector-im/riot-web#13623] opened 2020-05-10 23:44 UTC
### Description

After the web client update something is utterly broken with the device/session verification. First there was a signature upload error during the upgrade process. Now under settings security cross-signing, bootstrap, it asks for the recovery passphrase and then "Error: Key type master from getCrossSigningKey callback did not match". For a session verification it asks for the recovery passphrase and then nothing happens. After logout/login also can't verify the session. Additionally now it doesn't let me connect the session to the key backup.

### Steps to reproduce

- let the client upgrade to the version introducing cross-signing
- during the process (I do not remember which exact steps) there was an error "Signature upload failed"
- go to Settings -> Security & Privacy, Cross-signing
- click Bootstrap cross-signing and secret storage
- enter recovery passphrase

"Error: Key type master from getCrossSigningKey callback did not match"
displayed in red.

- try the same with clicking on recovery key and entering that => same error

- logout
- login
- go to Settings -> Security & Privacy, Key backup
- it says "This session is not backing up your keys"
- click Connect this session to Key Backup
- enter recovery passphrase
- first short message box Restoring keys from backup
- then Error "Unable to restore backup" message box
- for Cross-signining the same process and error as above

Logs being sent: yes

### Version information

- **Platform**: web (in-browser)

- **Browser**: Firefox 68.8.0esr **and** 76.0 (upgraded client in both)
- **OS**: Debian stable **and** Fedora F31
- **URL**: riot.im/app

**Comment by jryans** [comment] 2020-05-12 10:28
@bwindels This sounds potentially the same as the bootstrapping issue you are looking at, possible close as a duplicate?

**Comment by bwindels** [comment] 2020-05-13 07:35
It is indeed. Closing as duplicate of https://github.com/vector-im/riot-web/issues/13542

**Closed by bwindels** 2020-05-13 07:35 UTC
Labels: bug, feature:e2e-cross-signing, phase:4, story:1
