### ISSUE TITLE
Cross-signing broken completely

### ISSUE THREAD

**Issue by SomeoneSomewhereHow** [vector-im/riot-web#13519] opened 2020-05-05 19:38 UTC
Three devices. All at latest versions
Windows Application.
iPhone XR running latest iOS
and latest Firefox

Login from Windows client
**Verify this session - Other users may not trust it**
**-> verify**

Displays message:
Verify this sesion from one of your other sessions, granting it access to encrypted messages

Firefox:
**Verify this session - Other users may not trust it**

Displays message:
Verify this sesion from one of your other sessions, granting it access to encrypted messages

Lets try using a recovery passphrase
Enter my passphrase -> Next
The windows disappears with no result.

Lets try to bootstrap (Bootstrap cross-signing and secret storage) within the Riot IM, Windows Application:

Displays Error:
Error: Key type master from getCrossSigningKey callback did not match

If I try to use the application to verify either my Firefox session or IOS. Nothing happens. 
The recovery passphrase box disappears and dumps me back to the main conversation screen with the same toaster of "Verify this session"

Lets try signing out, maybe it just needs to redo is thing, and now I've lost all my messages. 

** Unable to decrypt: The sender's device has not sent us the keys for this message. **

All above still doesn't work.

**Comment by turt2live** [comment] 2020-05-05 19:45
@SomeoneSomewhereHow please go to settings -> help and submit debug logs for this issue.

**Comment by SomeoneSomewhereHow** [comment] 2020-05-05 19:48
Done so.

**Comment by bwindels** [comment] 2020-05-08 12:35
As said, we're working on making this part more reliable. In the meantime, you should be able to work around the issue by hitting **Reset cross-signing and secret storage** in the settings during a moment where the server more responsive, You'll find this under "Security & Privacy" (under the Cross-signing header). Note that **you will lose any verifications you have made so far** though, but I assume it's unlikely you managed to cross-signing anything given the broken state.

Sorry again for this inconvenience!

**Comment by jryans** [comment] 2020-05-11 13:30
@bwindels Is this another issue we expect to fix with https://github.com/vector-im/riot-web/issues/13581 then?

**Comment by bwindels** [comment] 2020-05-11 16:47
> @bwindels Is this another issue we expect to fix with #13581 then?

Yes

**Comment by bwindels** [comment] 2020-05-11 16:51
Also linking to https://github.com/vector-im/riot-web/issues/13542, which is the actual bug rather than the task to solve it.

**Comment by jryans** [comment] 2020-05-11 16:54
Okay, it sounds like this is effectively a duplicate of https://github.com/vector-im/riot-web/issues/13542 then, which we are working to improve, so I'll close this report. In the mean time, you can manually reset as highlighted above.

**Closed by jryans** 2020-05-11 16:54 UTC
Labels: bug, feature:e2e-cross-signing, phase:4, story:1
