### ISSUE TITLE
MD/HTML can be used to falsify link targets

### ISSUE THREAD

**Issue by pacien** [vector-im/riot-web#12774] opened 2020-03-18 15:43 UTC
### Description

It's possible to use Markdown/HTML formatting to hide the real target of a link.
This could be used in phishing attacks.

### Steps to reproduce

```json
{
  "content": {
    "body": "[https://www.mq.edu.au/about/coronavirus-faqs/updates-from-the-vc](https://www.youtube.com/watch?v=dQw4w9WgXcQ)",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://www.youtube.com/watch?v=dQw4w9WgXcQ\">https://www.mq.edu.au/about/coronavirus-faqs/updates-from-the-vc</a>",
    "msgtype": "m.text"
  }
}
```

is rendered as:

![15845454395543](https://user-images.githubusercontent.com/1449319/76977617-d5d65c80-6935-11ea-8cc1-c83055c16b3e.png)

### Mitigation

Other instant messaging apps and most email clients display a warning/confirmation pop-up when clicking on this kind of links, clearly displaying the actual target to the user and letting them choose whether to open it or not.

### Version information

- **Platform**: web and desktop
- **Version**: 1.5.12

Riot on mobile might be affected too.

**Comment by t3chguy** [comment] 2020-03-18 15:51
Duplicate of https://github.com/vector-im/riot-web/issues/7748

**Closed by t3chguy** 2020-03-18 15:51 UTC
Labels: bug, ui/ux
