### ISSUE TITLE
Device Name settings are not greatly accessible

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#11288] opened 2019-11-01 13:48 UTC
> Device name settings doesn't make any sense with speech cues - "Desktop row 1 column 1 device table editable desktop selection negative 1 multiline editable desktop" (my device name is "Desktop")

**Comment by turt2live** [comment] 2019-11-01 15:04
Duplicate of https://github.com/vector-im/riot-web/issues/11221 (effectively)

**Closed by turt2live** 2019-11-01 15:04 UTC
Labels: accessibility
