### ISSUE TITLE
"Show more" is not properly handled in compact mode

### ISSUE THREAD

**Issue by SpasGP** [vector-im/riot-web#14811] opened 2020-07-29 12:03 UTC
### Description

The button for expanding the favorites for example - "Show more" is not shown properly when the left side is collapsed.

[](url)

### Steps to reproduce

- Just compress the contacts list down to show only the avatars and you'll see that it's not displayed properly.

![show_more](https://user-images.githubusercontent.com/52784475/88797693-65c1c800-d1ac-11ea-84a3-602b368ec13f.PNG)

### Version information

For the desktop app:

- **OS**:  Windows 10
- **Version**: 1.7.2

**Comment by turt2live** [comment] 2020-07-30 21:10
Effectively a duplicate of https://github.com/vector-im/riot-web/issues/14782

**Closed by turt2live** 2020-07-30 21:10 UTC
Labels: bug, regression, type:new-room-list
