### ISSUE TITLE
Can't run with electron: protocol.registerStandardSchemes is not a function

### ISSUE THREAD

**Issue by pkrasicki** [vector-im/riot-web#10042] opened 2019-06-13 12:49 UTC
### Description

Crashes on start.

### Steps to reproduce

- yarn install
- yarn build
- yarn add electron
- yarn electron

```
yarn electron
yarn run v1.15.2
$ yarn install:electron && electron .
$ install-app-deps
  • please use as subcommand: electron-builder install-app-deps
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=linux arch=x64 appDir=/home/user/riot-web/electron_app
App threw an error during load
TypeError: protocol.registerStandardSchemes is not a function
    at Object.<anonymous> (/home/user/riot-web/electron_app/src/electron-main.js:211:10)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at loadApplicationPackage (/home/user/riot-web/node_modules/electron/dist/resources/default_app.asar/main.js:105:12)
    at Object.<anonymous> (/home/user/riot-web/node_modules/electron/dist/resources/default_app.asar/main.js:153:5)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
Unhandled exception TypeError: protocol.registerStandardSchemes is not a function
    at Object.<anonymous> (/home/user/riot-web/electron_app/src/electron-main.js:211:10)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at loadApplicationPackage (/home/user/riot-web/node_modules/electron/dist/resources/default_app.asar/main.js:105:12)
    at Object.<anonymous> (/home/user/riot-web/node_modules/electron/dist/resources/default_app.asar/main.js:153:5)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
```

### Version information

- **Platform**: desktop
- **OS**: Debian
- **Version**: 1.2.1

**Comment by t3chguy** [comment] 2019-06-13 21:21
Duplicate of https://github.com/vector-im/riot-web/issues/9562

**Closed by t3chguy** 2019-06-13 21:21 UTC
Labels: bug
