### ISSUE TITLE
`In reply to` element needs to be visually declared interactive …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13139] opened 2020-04-12 11:21 UTC
The `In reply to` element is not really semantic. It does not say “click me to expand, to reveal any other messages/replies regarding the quoted messages below” … that’s not good.

It’s very much worse, though, and I’ll call it a bug, that the element is not visually declared interactive. There’s two probably easy-to-implement options … either underline that element, which makes it semantically a hyperlink, or style it like a button.

<img width="514" alt="Screenshot 2020-04-12 at 13 14 26" src="https://user-images.githubusercontent.com/11408027/79067451-a4944680-7cbf-11ea-9ec8-916aede15906.png">

PS: Same applies to `expand` …

<img width="732" alt="Screenshot 2020-04-12 at 13 18 32" src="https://user-images.githubusercontent.com/11408027/79067518-284e3300-7cc0-11ea-9944-3cd808a937c0.png">

---

Also, for both elements, maybe the use of chevrons `>`, `<`, and one of those pointing down, could work better than words … also it’s already used in some places …

<img width="343" alt="Screenshot 2020-04-12 at 13 21 22" src="https://user-images.githubusercontent.com/11408027/79067571-8e3aba80-7cc0-11ea-82bb-ad96dffa48c8.png">

**Comment by fooness** [comment] 2020-04-12 11:27
This is sorf-of related to everything related `threads` and `threading`.

I’m rather sure many people don’t know the `In reply to` element is clickable.

**Comment by turt2live** [comment] 2020-04-14 19:36
Closing this as a duplicate of https://github.com/vector-im/riot-web/issues/6969 given the design obviously needs some work in general.

**Closed by turt2live** 2020-04-14 19:36 UTC
Labels: bug, ui/ux
