### ISSUE TITLE
Please add a button/pop-up for emoji as for stickers

### ISSUE THREAD

**Issue by sergeytol** [vector-im/riot-web#11667] opened 2019-12-14 19:56 UTC
(Riot desktop client for Ubuntu)
There is no way to choose emoji visually and put it by mouse click. Typing emoji code :something: manually - awful user experience, it's not convenient. It would be great to have a button/pop-up for that as for stickers.

**Comment by t3chguy** [comment] 2019-12-14 21:06
Duplicate of #1107

**Closed by t3chguy** 2019-12-14 21:06 UTC
Labels: bug, ui/ux
