### ISSUE TITLE
New room list: Emotes double the sender name

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#14186] opened 2020-06-24 14:44 UTC
<img width="170" alt="image" src="https://user-images.githubusercontent.com/279572/85577878-88067a00-b631-11ea-8e75-b5ee04ceb491.png">

**Comment by turt2live** [comment] 2020-06-24 14:45
Duplicate of https://github.com/vector-im/riot-web/issues/14041

(yes, I realize the scope is completely unclear on previews - will update the issue)

**Closed by turt2live** 2020-06-24 14:45 UTC
Labels: bug, type:new-room-list
