### ISSUE TITLE
Performance Regression

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8059] opened 2019-01-08 11:39 UTC
Some recent changes have introduced some performance - @turt2live thought there were three potential causes.

**Comment by ara4n** [comment] 2019-01-08 11:44
@turt2live has already fixed the primary cause, over at https://github.com/matrix-org/matrix-react-sdk/pull/2413

**Comment by lampholder** [comment] 2019-01-08 13:22
Yeah, I saw he had 3 potential causes - just wanted a quick placeholder to track them :)

**Comment by turt2live** [comment] 2019-01-14 23:32
Considering this a duplicate of https://github.com/vector-im/riot-web/issues/8033 and/or fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2413

The third issue I discovered was https://github.com/vector-im/riot-web/issues/8122

**Closed by turt2live** 2019-01-14 23:32 UTC
Labels: bug, critical, release-blocker
