### ISSUE TITLE
should be able to download debug logs locally to send out of band for when rageshaking isn't working for some reason

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8997] opened 2019-02-28 19:05 UTC
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y

**Comment by turt2live** [comment] 2019-02-28 19:33
Related: https://github.com/vector-im/riot-web/issues/3879

**Comment by turt2live** [comment] 2019-02-28 19:55
Also related: https://github.com/vector-im/riot-web/issues/8998

Also somewhere we have a bug for CCing people on their rageshake, and https://github.com/matrix-org/rageshake/issues/21 seems relevant.

**Comment by aaronraimist** [comment] 2020-01-05 01:18
Duplicate of #3304

**Closed** 2020-01-05 01:20 UTC
Labels: feature, minor, p2
