### ISSUE TITLE
'Unverified devices in room' shield icon used for generic errors

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#11431] opened 2019-11-19 16:51 UTC
![image](https://user-images.githubusercontent.com/1342360/69167365-c14f9800-0aec-11ea-8480-0ad885974ed3.png)

The shield icon should probably not be used here.

**Comment by turt2live** [comment] 2019-11-19 16:56
Duplicate of https://github.com/vector-im/riot-web/issues/11422

**Closed by turt2live** 2019-11-19 16:56 UTC
Labels: bug, ui/ux
