### ISSUE TITLE
Desktop app does not present a save dialog

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/riot-web#14356] opened 2020-07-06 16:18 UTC
Riot app on Windows or Mac
* Hover on an image
* Select image
* Select “Download this file”
* Problem: at times images will open in full screen in browser, at other times it asks you to download the image

**Comment by t3chguy** [comment] 2020-07-06 16:21
Duplicate of https://github.com/vector-im/riot-web/issues/12405

**Closed by t3chguy** 2020-07-06 16:21 UTC
Labels: bug
