### ISSUE TITLE
Room cannot be marked as read when latest message in this room is a hidden redacted message

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-web#4336] opened 2017-06-16 14:28 UTC
When you enable the option to hide redacted messages and someone sends a message and redacts it before it got seen it is not possible to set this room as read. The unread-flag persist (observable by room name beeing bold) until another message gets send (and seen) or i disable the option to hide redacted messages

**Comment by richvdh** [comment] 2017-06-21 10:39
I suspect this has causes similar to https://github.com/vector-im/riot-web/issues/1192.

**Comment by t3chguy** [comment] 2017-08-17 13:55
I think this is fixed now

**Comment by t3chguy** [comment] 2017-08-19 09:56
Tested, cannot reproduce which seems to match my memory of fixing it

**Closed by t3chguy** 2017-08-19 09:56 UTC
Labels: bug, major, p2
