### ISSUE TITLE
Profile Picture deletion should have a confirmation dialogue

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#7675] opened 2018-11-08 21:00 UTC
### Description

I just tried to exit settings and ended up hitting the other 'X' button, which cleared my profile picture. I type this as my old rooms are still having the profile picture be updated.

### Steps to reproduce

- Go to Settings
- Go to close Settings
- Accidentally hit the small 'X', not the big 'X'
- cry

**Comment by turt2live** [comment] 2018-11-08 21:08
Duplicate of https://github.com/vector-im/riot-web/issues/6656

**Closed by turt2live** 2018-11-08 21:08 UTC

**Comment by anoadragon453** [comment] 2018-11-08 21:15
Ah, searching 'profile picture' didn't turn anything up, and neither did Github's new feature :P Thanks!
