### ISSUE TITLE
The Secure Message Recovery notif should say if you already have a backup in place (and that 'setup' means 'just verify the device that started the backup' in that case)

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8072] opened 2019-01-09 10:07 UTC
If you:
- have backup configured from device A
- sign in on device B (which has not verified device A)
- go to an encrypted room on device B

You will see the in-room reminder block telling you to set up key backup:
![image](https://user-images.githubusercontent.com/1922197/50892343-2713c380-13f6-11e9-8e3e-ec26321460e8.png)

This message isn't appropriate in this situation - instead you should be advised that there's already a backup in place - you just need to verify the device that configured the backup.

Riot does the right thing if you click 'Set up' - it takes you via the verification flow - it's just not obvious that that is going to happen.

**Comment by jryans** [comment] 2019-01-09 10:18
Hmm, in https://github.com/vector-im/riot-web/issues/7902, we did add a slightly modified dialog text for this specific case. If the issue is an unverified device, device B is meant to show the slightly different message:

> To view your secure message history and ensure you can view new messages on future devices, set up Secure Message Recovery.

which I discussed with @nadonomy briefly. So if you are not seeing that on device B, there may be a bug there.

In general, this dialog is slightly awkward at the moment, as it is eventually intended to take you to a cross-signing flow (instead of simple device verification), but we don't have cross-signing yet. The text displayed currently represents that future cross-signing world. Since it's possible we might not have cross-signing for end of Jan, we may want to also clarify the text a bit more.

**Comment by ara4n** [comment] 2019-01-11 17:10
Perhaps until we have cross-signing, it should say:

> To view your secure message history, verify one of your devices which is already in the conversation.

...if you have another verified device on the account?

However, we mustn't miss that it sounds like a bug that the wrong dialog was being shown here in the first place?

**Comment by lampholder** [comment] 2019-01-16 13:44
I have been able to reproduce this reliably (and found a [handful of bonus bugs](https://github.com/vector-im/riot-web/issues/8142) at the same time whilst I was at it)

**Comment by dbkr** [comment] 2019-01-17 16:10
I suspect that the fact that this is showing the wrong dialog is because of https://github.com/vector-im/riot-web/issues/8142.

Do we want to do anything else here other than fix the above (eg. the wording change Matthew is suggesting)?

**Comment by lampholder** [comment] 2019-01-22 10:40
How about:

Secure Message Recovery has been set up from another device.

To view your secure message history and ensure you can view new messages on future devices, verify that device now.

[ Don't ask again ]  [ Verify device ]

**Comment by dbkr** [comment] 2019-01-22 14:24
wfm 👍

**Comment by lampholder** [comment] 2019-01-24 17:36
We need some text for the other case

**Comment by lampholder** [comment] 2019-01-25 15:59
If:
- key backup has been set up on a device, and
- that device is _not_ verifiable (i.e. it has logged out)

then:

### Secure Message Recovery

Secure Message Recovery has been set up a device with the ID: **JKLJKLJKLJK**

To view your secure message history and ensure you can view new messages on future devices, set up Secure Message Recovery.

[Dont ask again] [Set up]

**Comment by lampholder** [comment] 2019-01-25 16:06
I think that there are certainly more _accurate_ things we could be saying in each of these dialogues, but I think accuracy perhaps reduces usability here.

**Comment by jryans** [comment] 2019-01-30 15:37
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2506.

**Closed by jryans** 2019-01-30 15:37 UTC
Labels: feature, mvp, p1, question, type:e2e
