### ISSUE TITLE
Horizontal scrollbar in fenced code blocks not visible on the dark theme

### ISSUE THREAD

**Issue by dkasak** [vector-im/riot-web#8734] opened 2019-02-16 17:23 UTC
![scrollbar not visible](https://i.imgur.com/dWTtOAo.png)

It's there since I'm able to click on it and scroll, but I suppose it's the same colour as the background.

**Comment by turt2live** [comment] 2019-02-16 18:27
Duplicate of https://github.com/vector-im/riot-web/issues/4256

**Closed by turt2live** 2019-02-16 18:27 UTC
Labels: redesign

**Comment by dkasak** [comment] 2019-02-16 18:33
Is this really a duplicate? I found that issue but it seemed different: the screenshots there do show the scrollbar, it's just partially hidden by the text. Also, I seem to remember that prior to the redesign the scrollbars on `<pre>` blocks were visible for me.

**Comment by turt2live** [comment] 2019-02-16 18:37
It's a further regression, but the issue appears to be the same afaict
