### ISSUE TITLE
Unread message count in tab should be left-justified

### ISSUE THREAD

**Issue by marckell** [vector-im/riot-web#11105] opened 2019-10-09 18:16 UTC
### Description

When there are more than a few browser tabs open, the title text in the tab cuts off the unread count number since it's at the end.

Riot | &lt;room title&gt; &lt;unread count&gt;

![screenshot](https://user-images.githubusercontent.com/7455552/66508014-23949200-ea85-11e9-8be7-69599a8ac0d4.png)

I don't think the previous version had this issue. Maybe the room name wasn't there previously?

### Steps to reproduce

- Open web client
- Open a few more tabs
- Open riot in a tab
- Open a room (name length makes a difference here, too)
- Wait until a new message is received in the room

Due to the width of the tabs and the name of the room, the count isn't visible. I've had to enable desktop browser notifications, which isn't ideal for me (I'm not always looking at the browser when a message arrives). Maybe the count could be left-justified in the title?

Logs being sent: no

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 77
- **OS**: Windows 10
- **URL**: private url/1.4.2

**Comment by t3chguy** [comment] 2019-10-09 18:30
Duplicate of https://github.com/vector-im/riot-web/issues/10943

**Closed by t3chguy** 2019-10-09 18:30 UTC
Labels: bug, ui/ux
