### ISSUE TITLE
Device verification apparently succeeds on RiotX, but "compromised" on Riot-Web

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#12681] opened 2020-03-10 16:39 UTC
### Description

I just tried to complete device verification between RiotX-Android and
`riot.im/develop`. I used the emoji verification, rather than the QR code.

RiotX says everything is fine, while `riot.im/develop` tells me that something
is compromised:

![Screenshot_20200310-165645_RiotX dbg](https://user-images.githubusercontent.com/195073/76336250-03982180-62f6-11ea-9b35-cf5b643e68de.jpg)
![Screenshot_2020-03-10 Riot](https://user-images.githubusercontent.com/195073/76336264-072ba880-62f6-11ea-97b5-f0687873ad1c.png)

Now, I am pretty sure nothing is compromised. I run the homeserver for both,
I've verified the internet connection, and I am also the only one who's
touched the "sessions".

### Steps to reproduce

- In Riot-Web: Click on "Review" in the popup telling me about an unverified
  session, then click on Continue.
- In RiotX: Click on "Verification Request" popup, then "Can't scan"
- When emojis show up, click "match" on both sides.

I now expect both sides to report success or failure, but certainly not one
side to say it's fine, and the other complaining.

### Version information

For the web app:

- **Browser**: Firefox 73
- **OS**: Linux
- **URL**: riot.im/develop

For the mobile app:

- **OS**: Android 8
- **Version**: RiotX 0.18.0-dev

**Comment by bwindels** [comment] 2020-03-12 11:05
RiotX seems to have sent a key mismatch:
```
2020-03-10T15:42:49.963Z I Verification request WQesVke9p4h6sONGWYwhCfiT0a7WPArc: m.key.verification.cancel event with id:undefined, content:{"transaction_id":"WQesVke9p4h6sONGWYwhCfiT0a7WPArc","code":"m.key_mismatch","reason":"Key mismatch"} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:3=>5, observeOnly:false=>false
```

**Comment by bwindels** [comment] 2020-03-12 11:14
RiotX logged this around the same time:
```
03-10 15:41:36.582Z 13104 W/ /SASDefaultVerificationTransaction: ## SAS Verification: Could not find device FD5+qMFmSC+KhfOV99iGB5U2E0bjt8k/f0FYkGLFylI to verify
03-10 15:41:36.600Z java.lang.Throwable: Cannot sign from this account, public and/or privateKey Unknown Lb2R4xqu2RWLR7rILbK4ksdiOLAukkqwy0kmCodUz0Q
	at im.vector.matrix.android.internal.crypto.crosssigning.DefaultCrossSigningService.trustDevice(DefaultCrossSigningService.kt:612)
	at im.vector.matrix.android.internal.crypto.verification.SASDefaultVerificationTransaction.verifyMacs(SASDefaultVerificationTransaction.kt:315)
	at im.vector.matrix.android.internal.crypto.verification.DefaultOutgoingSASDefaultVerificationTransaction.onKeyVerificationMac(DefaultOutgoingSASDefaultVerificationTransaction.kt:226)
	at im.vector.matrix.android.internal.crypto.verification.SASDefaultVerificationTransaction.acceptVerificationEvent(SASDefaultVerificationTransaction.kt:209)
	at im.vector.matrix.android.internal.crypto.verification.DefaultVerificationService.handleMacReceived(DefaultVerificationService.kt:749)
	at im.vector.matrix.android.internal.crypto.verification.DefaultVerificationService.onMacReceived(DefaultVerificationService.kt:738)
	at im.vector.matrix.android.internal.crypto.verification.DefaultVerificationService.access$onMacReceived(DefaultVerificationService.kt:83)
	at im.vector.matrix.android.internal.crypto.verification.DefaultVerificationService$onToDeviceEvent$1.invokeSuspend(DefaultVerificationService.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:139)
	at android.os.HandlerThread.run(Unknown Source:28)

03-10 15:41:36.600Z 13104 W/ /SASDefaultVerificationTransaction$verifyMacs: ## SAS Verification: Failed to sign new device LEZHAVVUAY
java.lang.Throwable: Cannot sign from this account, public and/or privateKey Unknown Lb2R4xqu2RWLR7rILbK4ksdiOLAukkqwy0kmCodUz0Q
	at im.vector.matrix.android.internal.crypto.crosssigning.DefaultCrossSigningService.trustDevice(DefaultCrossSigningService.kt:612)
	at im.vector.matrix.android.internal.crypto.verification.SASDefaultVerificationTransaction.verifyMacs(SASDefaultVerificationTransaction.kt:315)
	at im.vector.matrix.android.internal.crypto.verification.DefaultOutgoingSASDefaultVerificationTransaction.onKeyVerificationMac(DefaultOutgoingSASDefaultVerificationTransaction.kt:226)
	at im.vector.matrix.android.internal.crypto.verification.SASDefaultVerificationTransaction.acceptVerificationEvent(SASDefaultVerificationTransaction.kt:209)
	at im.vector.matrix.android.internal.crypto.verification.DefaultVerificationService.handleMacReceived(DefaultVerificationService.kt:749)
	at im.vector.matrix.android.internal.crypto.verification.DefaultVerificationService.onMacReceived(DefaultVerificationService.kt:738)
	at im.vector.matrix.android.internal.crypto.verification.DefaultVerificationService.access$onMacReceived(DefaultVerificationService.kt:83)
	at im.vector.matrix.android.internal.crypto.verification.DefaultVerificationService$onToDeviceEvent$1.invokeSuspend(DefaultVerificationService.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:139)
	at android.os.HandlerThread.run(Unknown Source:28)
```

**Comment by madduck** [comment] 2020-03-12 11:19
Thanks for tracking this down. I have no idea what this means of course, but it seems like a RiotX bug more like a Riot-Web one then?

**Comment by bwindels** [comment] 2020-03-12 11:21
Yes, just doing initial investigation and making notes here for whoever will pick it up.

**Comment by bwindels** [comment] 2020-03-12 11:25
As a side-note, RiotX doesn't seem to be handling .start event races yet:
```

2020-03-10T15:43:35.436Z I Verification request E6lL0CdROFJcSukzGLis1Yh6THKAxWUG: m.key.verification.start event with id:undefined, content:{"short_authentication_string":["emoji","decimal"],"message_authentication_codes":["hkdf-hmac-sha256","hmac-sha256"],"transaction_id":"E6lL0CdROFJcSukzGLis1Yh6THKAxWUG","from_device":"LYLVVWDWSX","key_agreement_protocols":["curve25519"],"method":"m.sas.v1","hashes":["sha256"]} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:3=>4, observeOnly:false=>false
2020-03-10T15:43:35.496Z I Verification request E6lL0CdROFJcSukzGLis1Yh6THKAxWUG: m.key.verification.start event with id:undefined, content:{"method":"m.sas.v1","from_device":"LEZHAVVUAY","key_agreement_protocols":["curve25519"],"hashes":["sha256"],"message_authentication_codes":["hkdf-hmac-sha256","hmac-sha256"],"short_authentication_string":["decimal","emoji"],"transaction_id":"E6lL0CdROFJcSukzGLis1Yh6THKAxWUG"} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:4=>4, observeOnly:false=>false
2020-03-10T15:43:39.822Z I received to_device m.key.verification.cancel from: @madduck:madduck.net id: undefined
2020-03-10T15:43:39.826Z I Verification request E6lL0CdROFJcSukzGLis1Yh6THKAxWUG: m.key.verification.cancel event with id:undefined, content:{"transaction_id":"E6lL0CdROFJcSukzGLis1Yh6THKAxWUG","code":"m.unexpected_message","reason":"the device received an unexpected message"} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:4=>5, observeOnly:false=>false
```

**Comment by BillCarsonFr** [comment] 2020-03-12 13:13
(yes concurrent start is not yet handled)

By looking at the logs, riotX is reaching the point where it signs the device, that will then produce the following log
> Cannot sign from this account, public and/or privateKey Unknown 

Which is expected as riotX in this case is read only for cross signing. 
If we reach this point it means that no cancel was sent.

I wonder then from wich device is coming the cancel

**Comment by BillCarsonFr** [comment] 2020-03-12 13:56
This tx; `WQesVke9p4h6sONGWYwhCfiT0a7WPArc`
Looks like it was a QR code verification and not a SAS (it was canceled due to a bug that is now fixed and merged)

Same with this one `bU6uMDDCWDaXiLITqletIgdrEXglkymw`

**Comment by BillCarsonFr** [comment] 2020-03-12 14:11
The problematic transaction is this one:

````
2020-03-10T15:44:06.219Z I PUT /sendToDevice/m.key.verification.request/m1583855046219.6 {"@madduck:madduck.net":["LYLVVWDWSX"]}
2020-03-10T15:44:06.540Z I Verification request VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq: m.key.verification.request event with id:undefined, content:{"methods":["m.sas.v1","m.qr_code.show.v1","m.reciprocate.v1"],"transaction_id":"VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq","from_device":"LEZHAVVUAY","timestamp":1583855046219} deviceId:null, sender:@madduck:madduck.net, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:1=>2, observeOnly:false=>false
2020-03-10T15:44:06.541Z I Crypto: adding new request to requestsByTxnId with id VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq undefined
2020-03-10T15:44:06.546Z I Starting load of AsyncWrapper for modal
2020-03-10T15:44:11.793Z I received to_device m.key.verification.ready from: @madduck:madduck.net id: undefined
2020-03-10T15:44:11.797Z I Verification request VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq: m.key.verification.ready event with id:undefined, content:{"transaction_id":"VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq","from_device":"LYLVVWDWSX","methods":["m.sas.v1","m.qr_code.scan.v1","m.reciprocate.v1"]} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:2=>3, observeOnly:false=>false
2020-03-10T15:44:14.016Z I received to_device m.key.verification.start from: @madduck:madduck.net id: undefined
2020-03-10T15:44:14.020Z I Refreshing/starting the verification transaction timeout timer
2020-03-10T15:44:14.021Z I Verification request VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq: m.key.verification.start event with id:undefined, content:{"short_authentication_string":["emoji","decimal"],"message_authentication_codes":["hkdf-hmac-sha256","hmac-sha256"],"transaction_id":"VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq","from_device":"LYLVVWDWSX","key_agreement_protocols":["curve25519"],"method":"m.sas.v1","hashes":["sha256"]} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:3=>4, observeOnly:false=>false
2020-03-10T15:44:14.021Z I downloadKeys: already have all necessary keys
2020-03-10T15:44:14.036Z I PUT /sendToDevice/m.key.verification.accept/m1583855054036.7 {"@madduck:madduck.net":["LYLVVWDWSX"]}
2020-03-10T15:44:14.275Z I Verification request VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq: m.key.verification.accept event with id:undefined, content:{"key_agreement_protocol":"curve25519","hash":"sha256","message_authentication_code":"hkdf-hmac-sha256","short_authentication_string":["emoji","decimal"],"commitment":"5OxFl93MLSUuspq+f6S0sUUkO2J3B/WsYMI9VtX8a5c","transaction_id":"VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq"} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:4=>4, observeOnly:false=>false
2020-03-10T15:44:19.242Z I received to_device m.key.verification.key from: @madduck:madduck.net id: undefined
2020-03-10T15:44:19.243Z I Refreshing/starting the verification transaction timeout timer
2020-03-10T15:44:19.243Z I Verification request VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq: m.key.verification.key event with id:undefined, content:{"transaction_id":"VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq","key":"XLbCgGYuIK7tVFbEEbPfgHWtW5M/JL5594Fv4zEXgn4"} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:4=>4, observeOnly:false=>false
2020-03-10T15:44:19.244Z I PUT /sendToDevice/m.key.verification.key/m1583855059244.8 {"@madduck:madduck.net":["LYLVVWDWSX"]}
2020-03-10T15:44:19.520Z I Verification request VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq: m.key.verification.key event with id:undefined, content:{"key":"I8ZAb5o/Hp7p2P0oVnsw5blGLK/+zgFwuOqTZtdpBSw","transaction_id":"VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq"} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:4=>4, observeOnly:false=>false
2020-03-10T15:44:26.148Z I SAS calculateMAC: hkdf-hmac-sha256 ["k3LFcDVURc693Hxqw8zmmltEau9AYbRnkSDAdeHvdTE","MATRIX_KEY_VERIFICATION_MAC@madduck:madduck.netLEZHAVVUAY@madduck:madduck.netLYLVVWDWSXVBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sqed25519:LEZHAVVUAY"] ai5eZfuudXVLWFZMV0ZaTVYwWmFUVll3V21GVVZsbDM
2020-03-10T15:44:26.150Z I SAS calculateMAC: hkdf-hmac-sha256 ["FD5+qMFmSC+KhfOV99iGB5U2E0bjt8k/f0FYkGLFylI","MATRIX_KEY_VERIFICATION_MAC@madduck:madduck.netLEZHAVVUAY@madduck:madduck.netLYLVVWDWSXVBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sqed25519:FD5+qMFmSC+KhfOV99iGB5U2E0bjt8k/f0FYkGLFylI"] RFY+K6g0ZzAIekFJZWtGSlpXdEdTbHBYZEVkVGJIQlk
2020-03-10T15:44:26.151Z I SAS calculateMAC: hkdf-hmac-sha256 ["ed25519:FD5+qMFmSC+KhfOV99iGB5U2E0bjt8k/f0FYkGLFylI,ed25519:LEZHAVVUAY","MATRIX_KEY_VERIFICATION_MAC@madduck:madduck.netLEZHAVVUAY@madduck:madduck.netLYLVVWDWSXVBj1L8SqpS1pHG8rQdP3tjj69ss5p8SqKEY_IDS"] NPVAQfqocW/UVy9VVnk5VlZuazVWbFp1YXpWV2JGcDE
2020-03-10T15:44:26.152Z I PUT /sendToDevice/m.key.verification.mac/m1583855066152.9 {"@madduck:madduck.net":["LYLVVWDWSX"]}
2020-03-10T15:44:26.327Z I Verification request VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq: m.key.verification.mac event with id:undefined, content:{"mac":{"ed25519:LEZHAVVUAY":"ai5eZfuudXVLWFZMV0ZaTVYwWmFUVll3V21GVVZsbDM","ed25519:FD5+qMFmSC+KhfOV99iGB5U2E0bjt8k/f0FYkGLFylI":"RFY+K6g0ZzAIekFJZWtGSlpXdEdTbHBYZEVkVGJIQlk"},"keys":"NPVAQfqocW/UVy9VVnk5VlZuazVWbFp1YXpWV2JGcDE","transaction_id":"VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq"} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:4=>4, observeOnly:false=>false
2020-03-10T15:44:30.207Z I received to_device m.key.verification.mac from: @madduck:madduck.net id: undefined
2020-03-10T15:44:30.209Z I Refreshing/starting the verification transaction timeout timer
2020-03-10T15:44:30.209Z I Verification request VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq: m.key.verification.mac event with id:undefined, content:{"transaction_id":"VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq","mac":{"ed25519:LYLVVWDWSX":"upzUVfB2QjLRakxSYWt4U1lXdDRVMWxYZERSVk1XeFk"},"keys":"CKscY/y2eTIlVElsVkVsc1ZrVnNjMVpyVm5Oak1WcHk"} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:false, isLiveEvent:true, isRemoteEcho:false, phase:4=>4, observeOnly:false=>false
2020-03-10T15:44:30.211Z I SAS calculateMAC: hkdf-hmac-sha256 ["ed25519:LYLVVWDWSX","MATRIX_KEY_VERIFICATION_MAC@madduck:madduck.netLYLVVWDWSX@madduck:madduck.netLEZHAVVUAYVBj1L8SqpS1pHG8rQdP3tjj69ss5p8SqKEY_IDS"] CKscY/y2eTIlVElsVkVsc1ZrVnNjMVpyVm5Oak1WcHk
2020-03-10T15:44:30.216Z I SAS calculateMAC: hkdf-hmac-sha256 ["zBHZv8G0Ep4EG26DCU1+ZmxZ8/E+FYqjj2nDlAu/u4I","MATRIX_KEY_VERIFICATION_MAC@madduck:madduck.netLYLVVWDWSX@madduck:madduck.netLEZHAVVUAYVBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sqed25519:LYLVVWDWSX"] LSLWV76fNmY0bVkwYlZrd1lsWnJkMWxzV25Ka01XeHo
2020-03-10T15:44:30.266Z I PUT /sendToDevice/m.key.verification.cancel/m1583855070266.10 {"@madduck:madduck.net":["LYLVVWDWSX"]}
2020-03-10T15:44:30.267Z E error verify {"type":"m.key.verification.cancel","content":{"code":"m.key_mismatch","reason":"Key mismatch"},"unsigned":{}}
2020-03-10T15:44:30.267Z E {"type":"m.key.verification.cancel","content":{"code":"m.key_mismatch","reason":"Key mismatch"},"unsigned":{}}
2020-03-10T15:44:30.472Z I Starting load of AsyncWrapper for modal
2020-03-10T15:44:30.479Z I Verification request VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq: m.key.verification.cancel event with id:undefined, content:{"code":"m.key_mismatch","reason":"Key mismatch","transaction_id":"VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq"} deviceId:LYLVVWDWSX, sender:@madduck:madduck.net, isSentByUs:true, isLiveEvent:true, isRemoteEcho:true, phase:4=>5, observeOnly:false=>false
2020-03-10T15:44:31.770Z I received to_device m.key.verification.done from: @madduck:madduck.net id: undefined
````

RiotX checks the mac and is happy (see the .done event sent)
But somehow the mac check fails on web, then sending a cancel (that does nothing on riotX side because the transaction is already successfull and finished)
in rX POV all is good, the keys are what they should be

**Comment by bwindels** [comment] 2020-03-12 16:31
So, wrt to request `VBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sq`, riot-web (`LEZHAVVUAY`) seems to have ended up with the wrong device key for the Riot X (`LYLVVWDWSX`) session. It thinks the device key is `zBHZv8G0Ep4EG26DCU1+ZmxZ8/E+FYqjj2nDlAu/u4I` and checks the MAC with that key, which doesn't match and it cancels with `key_mismatch`. This is visible in this log line:
```
2020-03-10T15:44:30.216Z I SAS calculateMAC: hkdf-hmac-sha256 ["zBHZv8G0Ep4EG26DCU1+ZmxZ8/E+FYqjj2nDlAu/u4I","MATRIX_KEY_VERIFICATION_MAC@madduck:madduck.netLYLVVWDWSX@madduck:madduck.netLEZHAVVUAYVBj1L8SqpS1pHG8rQdP3tjj69ss5p8Sqed25519:LYLVVWDWSX"] LSLWV76fNmY0bVkwYlZrd1lsWnJkMWxzV25Ka01XeHo
```
When I query matrix.org for the device key for `LYLVVWDWSX`, I get `G+0SguBkzjWXcMcojULGJu/RXq5+L5jcYTeAaZJPY/c`, something different indeed.

**Comment by bwindels** [comment] 2020-03-12 17:31
@madduck Do you remember how long ago you created the `LYLVVWDWSX` session with Riot X? (e.g. how long ago did you log in on your phone for the last time?)

**Comment by madduck** [comment] 2020-03-12 18:28
@bwindels I don't remember re-logging in on RiotX, so it must have been a while ago. Unless there's a way to find out, I can't give you more info, sorry.

**Comment by tuxayo** [comment] 2020-03-14 01:09
Got this issue or maybe a variant.
In a previous trial it worked using the emoji based verification.

On the 2nd try (disconnected RiotX and wiped it's data), booth said "compromised" but it seems to have succeeded in RiotX as it's not asking anymore for verification.

Are more logs necessary for this issue?

**Comment by bwindels** [comment] 2020-03-17 10:59
> Got this issue or maybe a variant.
> In a previous trial it worked using the emoji based verification.
> 
> On the 2nd try (disconnected RiotX and wiped it's data), booth said "compromised" but it seems to have succeeded in RiotX as it's not asking anymore for verification.
> 
> Are more logs necessary for this issue?

Yes @tuxayo, please rageshake from both devices at your earliest convenience.

**Comment by ara4n** [comment] 2020-03-24 23:21
I just got this too.
 * https://github.com/matrix-org/riot-web-rageshakes/issues/2447
 * https://github.com/matrix-org/riot-android-rageshakes/issues/9836

**Comment by BillCarsonFr** [comment] 2020-03-25 10:35
https://github.com/vector-im/riotX-android/issues/1170

Looks like the riotX device keys have been rotated

**Comment by jryans** [comment] 2020-03-26 10:33
I'll track this for now on web so it's not lost, but seems likely to be fixed by Android side.

**Comment by tuxayo** [comment] 2020-03-26 16:19
https://github.com/vector-im/riot-web/issues/12681#issuecomment-600007769
> Yes @tuxayo, please rageshake from both devices at your earliest convenience.

https://github.com/vector-im/riot-web/issues/12681#issuecomment-604352262
> I'll track this for now on web so it's not lost, but seems likely to be fixed by Android side.

Couldn't reproduce with current versions :D 

After trying 3 times to
- log in with RiotX
- verify between RiotX and Riot web develop

Version of RiotX: 0.18.1 F-Droid

**Comment by jryans** [comment] 2020-03-31 10:04
Wonderful, sounds like this is now fixed, thanks for verifying! 🎉 

I'm assuming the key rotation issue is fixed by https://github.com/vector-im/riotX-android/pull/1172.

**Closed by jryans** 2020-03-31 10:04 UTC
Labels: bug, cross-signing-sprint, phase:3, story:1

**Comment by cnchamraeun-dev** [comment] 2025-08-04 05:39
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJxcmNvZGVJZCI6IjMtMjE2MzIiLCJkZWFsZXJDb2RlIjoiOTk5MDAwIiwiZGVhbGVyTmFtZSI6IkpPVFVOIENhbWJvZGlhIiwiY2FzaGJhY2tBbW91bnQiOjMsImNhc2hiYWNrQ3VycmVuY3kiOiJVU0QiLCJpYXQiOjE3MjI1NzIwODN9.rNu1-u2-8SS2o_SmXgqH8IE_xFCEQ3yXSnYoUCSIwUs
