### ISSUE TITLE
OOM on startup if your logs in a previous session got too big

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#7464] opened 2018-10-05 15:31 UTC
On startup, https://github.com/matrix-org/matrix-react-sdk/blob/master/src/rageshake/rageshake.js#L257 collects your each of your previous sessions' logs into a massive string (one massive string per session). Obviously, if your logs got big (for example due to https://github.com/vector-im/riot-web/issues/7409) , this is going to OOM, and there's nothing you can do about it, short of clearing out your indexeddb.

**Comment by turt2live** [comment] 2018-10-05 21:29
Duplicate of https://github.com/vector-im/riot-web/issues/7433

**Closed by turt2live** 2018-10-05 21:29 UTC
