### ISSUE TITLE
jitsi "More actions" is cut off

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#12916] opened 2020-03-28 20:48 UTC
### Description

The "More actions" menu is cut off, thus you can't see e.g. the "View full screen" button
![image](https://user-images.githubusercontent.com/1029578/77833407-62a2c680-713d-11ea-95a5-3b378facef25.png)

### Steps to reproduce

- start a jitsi conference
- click on the three dots aka "More actions"

I'd expect a shorter menu or a larger widget, because otherwise I can't view and use all menu buttons.

Logs being sent: no

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.5.12

**Comment by turt2live** [comment] 2020-03-28 22:30
Duplicate of https://github.com/vector-im/riot-web/issues/6785#issuecomment-604038713

**Closed by turt2live** 2020-03-28 22:30 UTC
Labels: bug, type:voip
