### ISSUE TITLE
[feature] Select a community when creating a new room

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#6506] opened 2018-04-12 14:57 UTC
### Description

I'd like that the members of my community would be able to create rooms directly linked to the community.

By default, in the room creation form, the room is in no community, but there would be a list of all the communities of the user and, if wanted, the user would be able to select a community in which the new room will be.

If this idea is accepted, I think the list should not be put in the "Advanced" sub section, it should be easily visible to the user. Why I think that is because I think of the communities as mere groups as well as companies. And if a member of a company creates a room, he should be able to link this room to the company community directly.

It is basically what Slack does, but mainly because, from the start, Slack is less open than Matrix. But the feature is still interesting IMO since it really allows the member of the community to be part of the community. The creation of new rooms in a community is a key component for an active community.

Of course, the capacity for any member to add a new room has to be enabled by the community admin (e.g. we don't want any member of the Matrix community to start creating rooms in it, it shall be reserved to the "core" member of Matrix).

### Version information

- **Platform**: all
- **Version**: for the future versions

**Comment by tulir** [comment] 2018-04-12 14:59
Duplicate of #5819

**Closed** 2018-04-12 15:02 UTC
