### ISSUE TITLE
Unable to paste copied formatted text 

### ISSUE THREAD

**Issue by agilob** [vector-im/riot-web#6842] opened 2018-06-05 14:45 UTC
### Description

Copy text from facebook post or other source where the whole text is a link. Pressing CTRL+V in text input area results with the following exception being printed in console each time paste combination is pressed.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 60.0.1
- **OS**: Ubuntu, Arch Linux both
- **URL**: riot.im/app 

https://gfycat.com/EnchantedFatalBlueshark

In the video you can see I copied text from wykop.pl, the text is a link. I tried to paste it several times into the chat input but it didnt work. I pasted the text into search box in Firefox, copied it again (removes text formatting, html etc.) and pasted it again to chat input.

```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
invariant.js:38
r
invariant.js:38
D</t.prototype.getEntity
ContentState.js:149
value/<
MessageComposerInput.js:197:24
n/<
findRangesImmutable.js:31
reduce/<
immutable.js:4411
Ue.prototype.__iterate
immutable.js:2194
reduce
immutable.js:4406
n
findRangesImmutable.js:29
_</t.prototype.findEntityRanges
ContentBlock.js:106
value
MessageComposerInput.js:191:8
value self-hosted:980:17 u</e.prototype.getDecorations/<
CompositeDraftDecorator.js:70
forEach self-hosted:261:13 u</e.prototype.getDecorations
CompositeDraftDecorator.js:58
generate
BlockTree.js:61
a/<
EditorState.js:478
lt/r.__iterateUncached/<
immutable.js:3004:28
ct/o.__iterateUncached/<
immutable.js:3074
rt.prototype.__iterate/<
immutable.js:2820:27
Ze.prototype.__iterate/<
immutable.js:2687:26
Ue.prototype.__iterate
immutable.js:2194
Ze.prototype.__iterate
immutable.js:2686
rt.prototype.__iterate
immutable.js:2818
ct/o.__iterateUncached
immutable.js:3071
V
immutable.js:606
R.prototype.__iterate
immutable.js:276
lt/r.__iterateUncached
immutable.js:3003
V
immutable.js:606
R.prototype.__iterate
immutable.js:276
forEach
immutable.js:4374
Ae/<
immutable.js:1949
fe.prototype.withMutations
immutable.js:1341
Ae
immutable.js:1938
Ie
immutable.js:1911
fe.prototype.merge
immutable.js:1292
a
EditorState.js:475
w</e.set/r<
EditorState.js:108
fe.prototype.withMutations
immutable.js:1341
w</e.set
EditorState.js:78
w</e.push
EditorState.js:349
value
MessageComposerInput.js:682:29
value self-hosted:980:17 r
editOnPaste.js:75
N</t.prototype._buildHandler/<
DraftEditor.react.js:146
r
ReactErrorUtils.js:24
a
EventPluginUtils.js:83
s
EventPluginUtils.js:106
p
EventPluginHub.js:41
h
EventPluginHub.js:52
forEach self-hosted:261:13 n
forEachAccumulated.js:22
processEventQueue
EventPluginHub.js:252
r
ReactEventEmitterMixin.js:15
handleTopLevel
ReactEventEmitterMixin.js:25
i
ReactEventListener.js:70
perform
Transaction.js:141
batchedUpdates
ReactDefaultBatchingStrategy.js:60
i
ReactUpdates.js:95
dispatchEvent
ReactEventListener.js:145
dispatchEvent
```

**Comment by t3chguy** [comment] 2018-06-05 14:57
Duplicate of https://github.com/vector-im/riot-web/issues/4962

**Closed by t3chguy** 2018-06-05 14:57 UTC
