### ISSUE TITLE
Switching between dark and light theme only works once

### ISSUE THREAD

**Issue by mtausig** [vector-im/riot-web#4996] opened 2017-09-07 08:59 UTC
### Description

If I open the settings in the riot desktop client, I can switch between the dark and the light theme.
If I change this option once, the theme immediately changes, but changing the option again, doesn't do anything. To change the theme back, I have to close the settings dialog and reopen it.

### Steps to reproduce

1. Open Settings
2. Click on "Dark theme" in the  *USER INTERFACE* section
3. Click on "Light theme" in the  *USER INTERFACE* section
4. Close Settings
5. Open Settings
6. Click on "Light theme" in the  *USER INTERFACE* section

After 2., the app goes dark, but it doesn't change back in step 3. 
Step 6. finally returns me to the light theme

### Version information

*riot-web-0.12.2* running on Ubuntu Xenial 16.04 installed from the official APT repo at https://riot.im/packages/debian

**Comment by t3chguy** [comment] 2017-09-07 09:01
Duplicate of https://github.com/vector-im/riot-web/issues/4700

**Closed by t3chguy** 2017-09-07 09:01 UTC

**Comment by mtausig** [comment] 2017-09-07 09:05
Sorry.
