### ISSUE TITLE
You can't scroll the roomlist with the trackpad if you try and scroll the headings not the list of rooms themselves

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6001] opened 2018-01-18 11:41 UTC
Which is super annoying if you have some custom tags.

**Comment by t3chguy** [comment] 2018-01-18 11:43
Duplicate of https://github.com/vector-im/riot-web/issues/2696

**Comment by t3chguy** [comment] 2018-01-18 11:43
okay I guess scroll whell vs trackpad but still

**Closed by t3chguy** 2018-01-18 11:43 UTC

**Comment by lampholder** [comment] 2018-01-18 11:45
Issue search fail shame 😢  (thanks for deduping)
