### ISSUE TITLE
Discovering how to get out of community mode is hard

### ISSUE THREAD

**Issue by NoraCodes** [vector-im/riot-web#9549] opened 2019-04-23 20:22 UTC
### Description

When I joined my first organization and clicked on the icon, it took me a long time to figure out that I should click on the left-side black bar to get back to the non-organization mode.

It would be preferable to have a "default" organization badge there, maybe a globe or the Matrix logo or something, so that it's clear where to click to get back to seeing all your rooms, contacts, etc.

### Version information

- **Platform**: Desktop (Ubuntu)

```
riot-web:
  Installed: 1.0.6
  Candidate: 1.0.6
  Version table:
 *** 1.0.6 500
        500 https://riot.im/packages/debian cosmic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by jryans** [comment] 2019-07-24 10:38
Thanks for the feedback. I believe this is a duplicate of https://github.com/vector-im/riot-web/issues/7953.

**Closed by jryans** 2019-07-24 10:38 UTC
Labels: bug, p2, type:communities, ui/ux
