### ISSUE TITLE
Icon Description Missmatch when Verifying Device

### ISSUE THREAD

**Issue by vbrandl** [vector-im/riot-web#13925] opened 2020-06-04 14:13 UTC
![Screenshot Desktop](https://user-images.githubusercontent.com/20639051/83766103-427f0e80-a67c-11ea-9541-037cf8a9b4f2.png)
![Screenshot Android](https://user-images.githubusercontent.com/20639051/83766106-43b03b80-a67c-11ea-82b5-3b9037272953.png)

### Description

I tried verifying a desktop client (running `riot-web version: 1.6.2`, the electron application) from my Android device (running Riot `0.9.11` from F-Droid). The icons were the same, but the textual description for `spanner`/`wrench` did not match. Both devices have the language set to `en_UK` so it shouldn't be a problem with AE/BE.

#### Desktop

- **OS**: NixOS 20.03
- **Version**: 1.6.2

#### Mobile

- **OS**: LineageOS 17.1
- **Version**: 0.9.11 (from F-Droid)

**Comment by t3chguy** [comment] 2020-06-04 21:13
Duplicate of https://github.com/vector-im/riot-web/issues/10798

**Closed by t3chguy** 2020-06-04 21:13 UTC
Labels: bug, ui/ux
