### ISSUE TITLE
Email notifications can't be disabled

### ISSUE THREAD

**Issue by tuxiqae** [vector-im/riot-web#9021] opened 2019-03-01 22:39 UTC
### Description

Whenever I disable the email notifications it just re-enables itself (to see it I need to change it, switch menu and go back to the Notifications menu. and then it'll appear as active once again.)

Log: Sent

### Version information

- **Platform**: desktop

- **OS**: Arch Linux 4.20.11 (KDE)
- **Version**: 1.0.1

The output from the about page:
Versions
matrix-react-sdk version: <local>
riot-web version: 1.0.1
olm version: 3.0.0

**Comment by RandScullard** [comment] 2019-03-03 17:59
I am seeing the same issue. You don't even need to switch menus; just toggle any of the other notification switches and the "Enable email notifications" switch will switch back to "on".

**Comment by c7hm4r** [comment] 2019-03-06 15:11
Possible duplicate: https://github.com/vector-im/riot-web/issues/6072 , however at least for me Synapse is not entangled this time, I get an null reference error in Chrome and Firefox:

![bildschirmfoto von 2019-03-06 16-05-21](https://user-images.githubusercontent.com/1974041/53891311-68a5a100-402a-11e9-9eaf-7c36b76b3420.png)

**Comment by c7hm4r** [comment] 2019-03-06 15:26
Duplicate of: https://github.com/vector-im/riot-web/issues/8837

**Comment by jryans** [comment] 2019-03-06 15:51
Thanks for the report! I agree it looks like this was fixed as part of #8837.

**Closed by jryans** 2019-03-06 15:51 UTC
Labels: bug, major, p1, type:notifications
