### ISSUE TITLE
Full release notes on full releases

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#9887] opened 2019-05-29 16:32 UTC
When 1.2.0 released (just now) the release notes on github don't include all that has changed. One needs to go back to all RC's, and even that might not include everything.

Can we please get a complete list of what has changed in the Release Notes for release versions of Riot? :)

**Comment by jryans** [comment] 2019-05-29 16:35
Thanks for the suggestion, I am fairly sure everyone agrees it should be done... Now we just need time to do it. Duplicate of https://github.com/vector-im/riot-web/issues/8731.

**Closed by jryans** 2019-05-29 16:35 UTC
Labels: suggestion
