### ISSUE TITLE
Superfluous space inserted when entering a '

### ISSUE THREAD

**Issue by rhaamo** [vector-im/riot-web#7191] opened 2018-08-18 13:42 UTC
### Description

When entering a ```'``` there is a space inserted right before in the input prompt.

### Steps to reproduce

- In a chat
- Type like ```that's```
- Expect to see ```that's```
- See ```that 's``` instead
![image](https://user-images.githubusercontent.com/8625/44299735-14d8a200-a2fc-11e8-89d4-75fc4f4effe5.png)

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox Nightly (63.0a1, no stable to test)
- **OS**: Ubuntu
- **URL**: my own deployment of riot, reproduced with `v0.16.0` and `v0.16.1-rc.1`

Markdown enabled or no doesn't change anything.
My layout is "English (US, intl., with dead keys)"
I used the firefox Profile Manager to create a blank one, logged to my riot, still have the issue.

**Comment by lampholder** [comment] 2018-08-20 15:42
There are a couple of other dead keys related bugs:
- https://github.com/vector-im/riot-web/issues/7124
- https://github.com/vector-im/riot-web/issues/7149

My problem is I don't know enough about this keyboard layout to reproduce the problems.

So, to try and create the right test environment, here's what I'm doing:
- On Ubuntu LTS 16.04
- Terminal: `$ sudo dpkg-reconfigure keyboard-configuration`
- Choose: Generic 105-key (Intl) P
- Choose: English (US)
- Choose: English (US) - English (US, international with dead keys)
- Choose _key to function as AltGr_: The default for the keyboard layout
- Choose _compose key_: No compose key
- Choose _contral+alt+backspace to terminate X server_: No

Then:
- Go to riot electron
- Select composer
- Type `that's` by pressing the keys: <kbd>t</kbd><kbd>h</kbd><kbd>a</kbd><kbd>t</kbd><kbd>AltGr</kbd>+<kbd>'</kbd><kbd>s</kbd>
- Pressing carriage return to submit the message to riot

When I do this, I see `that's` exactly as it's meant to be seen - no additional spaces.

So - what's different between my test setup and what you're doing? If you can highlight the differences then we can get a reproducable problem and figure out what needs doing for a fix :D 

Thanks!

**Comment by rhaamo** [comment] 2018-08-20 15:51
Everything is same here, I just don't use the electron but web app.

However I type my ```'``` by pressing <kbd>'</kbd> then <kbd>space</kbd>, using <kbd>AltGr</kbd><kbd>'</kbd> it works, just not the other method.

Same issue with ``` ` ``` too.

**Comment by rhaamo** [comment] 2018-11-05 16:57
I definitely had this issue on Firefox and was the case with 0.17.0 too.

However in the mean time I upgraded from Ubuntu LTS to the latest "stable" and I can't reproduce the issue (still sometimes the '" etc. acts weirdly).

So... I don't really know, that issue have been affecting a bunch of people and some works where some other using the same setup doesn't.

Perhaps something on gnome/gtk input handling side was broken and updating fixed it.

I might get back to LTS because the "stable" is causing me issues (unrelated to riot) so I will look if it's again an issue after reinstalling.

**Comment by turt2live** [comment] 2018-11-05 17:51
I'll give it a try on 18.04 and see what happens. My testing with 18.10 seems to show it is fixed, so it might indeed be a package problem.

**Comment by turt2live** [comment] 2018-11-05 21:43
I think this might be an 18.04 issue at the very least: I can't get the dead keys to work in any application. In 18.10 everything is fine, but in 18.04 is definitely broken. I tried with US International (with dead keys) and Spanish (with dead tilde).

**Comment by turt2live** [comment] 2018-11-05 23:03
This is not an upstream issue as far as I can tell. I finally got a reproducible test case, and it is specific to Riot.

**Comment by turt2live** [comment] 2018-11-06 19:46
I'm pretty sure this is an upstream Firefox issue. Firefox is sending two keyDown events for space, leading to Riot doing the right thing and inserting two spaces. I've reported it here and I guess we'll see where it goes: https://bugzilla.mozilla.org/show_bug.cgi?id=1505147

I managed to create a minimal test case to prove it is not a Riot issue with this code pen: https://codepen.io/anon/pen/YRyNpv

**Comment by rhaamo** [comment] 2018-11-06 20:04
Thanks for finding this !

I tried your codepen but can't reproduce, but I'm using Firefox Nightly (65.0a1 (2018-10-30) currently) on ubuntu 18.10 too.

That's a weird one, let's see how the firefox side of the bug will goes.

**Comment by turt2live** [comment] 2018-11-26 16:31
As of a few minutes ago, the Firefox bug was classified as fixed for Firefox 65. Would be good to see if the issue gets fixed for people when the patch lands somewhere usable for testing.

**Comment by jryans** [comment] 2018-12-12 17:33
The Firefox fix here should be present in both [Nightly](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly) and [Beta](https://www.mozilla.org/en-US/firefox/channel/desktop/#beta) builds, if someone affected would like to give those a try to confirm the fix. It hasn't reached Release channel yet.

**Comment by rhaamo** [comment] 2018-12-15 12:37
I've finally reinstalled ubuntu lts after too many issues with my update to the latest and I can try again.

Updated riot (web) to 0.17.8 and firefox is nightly up to date.

And I still have the superfluous spaces in riot :(

**Comment by jryans** [comment] 2018-12-19 13:59
I have just compared Firefox 64 vs. 64 on Ubuntu 18.04.1.

It appears there are multiple Firefox bugs in play here:

* @turt2live [reported](https://bugzilla.mozilla.org/show_bug.cgi?id=1505147) the case of <kbd>'</kbd><kbd>'</kbd><kbd>Space</kbd> which I have verified is indeed fixed in Firefox 65+
* I have [reported](https://bugzilla.mozilla.org/show_bug.cgi?id=1515321) the case of <kbd>'</kbd><kbd>Space</kbd> which is currently waiting on Firefox for triage

**Comment by rhaamo** [comment] 2018-12-29 10:48
from the reply in the new firefox bug issue, it looks like it's the correct behaviour and not a bug (in firefox).

so it would be a bug in the input lib-thing riot-web is using ?

**Comment by jryans** [comment] 2018-12-31 20:56
For the <kbd>'</kbd><kbd>Space</kbd> case, it does seem like Firefox is following the keyboard events spec more closely than Chrome, so it's unlikely that Firefox will make a change.

After more investigation, the Slate input library we use in Riot does not have this issue by itself. Using the [Slate example page](https://www.slatejs.org/#/input-tester), <kbd>'</kbd><kbd>Space</kbd> works as expected (a single `'` character is added).

The problem is introduced by an [`onKeyDown` handler](https://github.com/matrix-org/matrix-react-sdk/blob/a3778dc822022e803c5b2a9d083f3889eeda4806/src/components/views/rooms/MessageComposerInput.js#L764-L765) in the Riot React SDK. This exists to mark each word you type as separate chunks for undo / redo.

One way to keep this undo feature while also avoiding the extra space problem here would be to instead use the `keypress` event in place of `keydown`. However... the Slate library doesn't currently let you use `onKeyPress` handlers. :sob: So, for now I am trying to investigate if Slate would accept an addition of `onKeyPress` handlers.

There may also be some other way to rewrite what Riot's doing with the space character that also avoids this issue, so we'll keep looking at other possibilities as well.

Thanks for your patience. I can imagine this must be frustrating!

**Comment by t3chguy** [comment] 2020-03-24 20:41
Is this still an issue for you in the new composer?

**Comment by t3chguy** [comment] 2020-04-14 10:24
Assuming no

**Closed by t3chguy** 2020-04-14 10:24 UTC
Labels: bug, minor, p2, type:old-composer, upstream-issue
