### ISSUE TITLE
saving picture looses file extension

### ISSUE THREAD

**Issue by rexometer** [vector-im/riot-web#5114] opened 2017-09-24 13:54 UTC
### Description

I'm using version 0.12.4 of riot-web desktop version for mac. If I get a picture for example with the name: ima_ee01575.jpeg, click on it and download it. It is saved to my hard disk with the name ima_ee01575. So the file extension is missing.

Using riot with firefox, it works as expected.

### Steps to reproduce

- click on a received or send picture
- download it
- file extension is missing

### Version information

- Version of riot-web for desktop: 0.12.4 (https://riot.im/download/desktop/install/macos/Riot-0.12.4.dmg)
- mac OSX 10.11.6

- **Platform**: web (in-browser) or desktop?

For the desktop app:

- **OS**: macOS
- **Version**: 10.11.6

**Comment by t3chguy** [comment] 2017-09-24 13:55
Duplicate of https://github.com/vector-im/riot-web/issues/5011

**Closed by t3chguy** 2017-09-24 13:55 UTC
