### ISSUE TITLE
Historical section has rooms with no "forget" option

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9502] opened 2019-04-16 13:52 UTC
STR:

1. A Historical section appeared today when I loaded https://riot.im/develop with my m.o account
2. It has several ancient rooms I haven't seen appear in a long time
3. The room context menu doesn't have a "Forget" option to remove them

**Comment by uhoreg** [comment] 2019-04-16 14:56
I think this is the same as https://github.com/vector-im/riot-web/issues/9168

**Comment by turt2live** [comment] 2019-04-16 15:13
Duplicate of https://github.com/vector-im/riot-web/issues/9168

**Closed by turt2live** 2019-04-16 15:13 UTC
Labels: bug
