### ISSUE TITLE
Image messages are confusingly larger than the images

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#9274] opened 2019-03-25 21:41 UTC
When I right-click an image and then recant, clicking outside of the image or the pop-up menu, I often end up with the image enlarged.  This is because the message that contains the image tends to be larger than the image itself.  This is very counterintuitive - on would expect simply to cancel the right-click.
Either the message should be reduced to the size of the image, or a click in this case (when the pop-up menu is shown) should not be interpreted as if there were no menu shown

**Comment by turt2live** [comment] 2019-03-25 21:56
Duplicate of https://github.com/vector-im/riot-web/issues/8747

**Closed by turt2live** 2019-03-25 21:56 UTC
