### ISSUE TITLE
If you click on a room avatar on a room without an avatar you get a lightbox with a broken image in it

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8326] opened 2019-01-30 16:16 UTC
I think it just shouldn't be clickable if there's no avatar.

**Comment by turt2live** [comment] 2019-01-30 16:36
Duplicate of https://github.com/vector-im/riot-web/issues/6732

See timeline for a fix in progress

**Closed by turt2live** 2019-01-30 16:36 UTC
Labels: bug, minor, p2, redesign
