### ISSUE TITLE
Part of replied message showing up on message body

### ISSUE THREAD

**Issue by yangm97** [vector-im/riot-web#7524] opened 2018-10-20 07:12 UTC
### Description

edit later

bugged mesage:
https://matrix.to/#/!DwmKuvGvRKciqyFcxv:matrix.org/$1540018956494954xTFWC:matrix.org

screenshot:
https://matrix.org/_matrix/media/v1/download/matrix.org/bxXyecRcetkIjVkwxixuqfmg

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Log: sent/not sent?    

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 0.x.y

**Comment by Mikaela** [comment] 2018-10-20 07:17
Android

![screenshot](https://matrix.org/_matrix/media/v1/download/matrix.org/miQoxxjVriudLlgOVwOPqHwj)

**Comment by lampholder** [comment] 2018-10-23 14:53
Am I right in understanding the problem is there in Riot Web but the same event rendered on Riot Android looks fine?

The underlying event data looks sound as far as I can tell:

```
{
  "origin_server_ts": 1540018956323,
  "sender": "@yangm97:matrix.org",
  "event_id": "$1540018956494954xTFWC:matrix.org",
  "age": 287052989,
  "unsigned": {
    "age": 287052989
  },
  "content": {
    "body": "> <@Ciblia:matrix.org> Oh, so there is no way around CAs or DNS? I think CAs could possibly be replaced with DANE (?), but that would probably be more work on the DNS, but if everything is E2EE, the good news is that dnscrypt is not needed\n\nyeah, the propposed solution for root CAs was yet another WoT. what are the chances of pwning both at the same time? genuinelly curious",
    "format": "org.matrix.custom.html",
    "msgtype": "m.text",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!DwmKuvGvRKciqyFcxv:matrix.org/$1540018833494580aSSVw:matrix.org\">In reply to</a> <a href=\"https://matrix.to/#/@Ciblia:matrix.org\">@Ciblia:matrix.org</a><br>I think it's quite the opposite. mainstream browsers are starting to label HTTP websites as INSECURE, so it kind of made sense to me to reuse that layer to stablish trust</blockquote></mx-reply>Oh, so there is no way around CAs or DNS? I think CAs could possibly be replaced with DANE (?), but that would probably be more work on the DNS, but if everything is E2EE, the good news is that dnscrypt is not needed</blockquote></mx-reply>yeah, the propposed solution for root CAs was yet another WoT. what are the chances of pwning both at the same time? genuinelly curious",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$1540018833494580aSSVw:matrix.org"
      }
    }
  },
  "room_id": "!DwmKuvGvRKciqyFcxv:matrix.org",
  "user_id": "@yangm97:matrix.org",
  "type": "m.room.message"
}
```

It looks like whatever translates the `<mx-reply>` tag from the `formatted_body` into the HTML in Riot is borked :\

**Comment by yangm97** [comment] 2018-10-23 18:28
@lampholder both are rendering wrong.

**Comment by dbkr** [comment] 2019-09-13 09:29
Repro steps: use devtools to send a message into the room with content:
```
{
    "body": "> <@bob:example.com> sent an image.\n\nI am a fish",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!xxxxxxxxx:example.com/$xxxxxxxxxxxxx:example.com\">In reply to</a> <a href=\"https://matrix.to/#/@bob:example.com\">@bob:example.com</a><br>sent an image.</blockquote></mx-reply>I am a fish",
    "msgtype": "m.text"
  }
```

...then reply to that message

**Comment by uhoreg** [comment] 2020-07-16 23:16
fixed by https://github.com/matrix-org/matrix-react-sdk/pull/5006

**Closed** 2020-07-16 23:53 UTC
Labels: bug, minor, p2, type:replies
