### ISSUE TITLE
Icon on Windows destkop again

### ISSUE THREAD

**Issue by Metzlmane** [vector-im/riot-web#10313] opened 2019-07-11 12:38 UTC
On every Update after "there is a new version of Riot", I get the shortcut Icon on the Desktop again.
Could there be an option to avoid this?

**Comment by t3chguy** [comment] 2019-07-11 13:38
Duplicate of https://github.com/vector-im/riot-web/issues/4601

**Closed by t3chguy** 2019-07-11 13:38 UTC
Labels: suggestion

**Comment by zingmars** [comment] 2019-09-20 18:46
No it's not. The linked issue is about tray icons, this is about desktop shortcuts being created after update. The issue is also still present, so please re-open.

**Comment by t3chguy** [comment] 2019-09-21 01:21
Duplicate of #9210 then
