### ISSUE TITLE
User ID shown to differentiate users with the same nickname does not disappear

### ISSUE THREAD

**Issue by timo95** [vector-im/riot-web#9399] opened 2019-04-08 09:07 UTC
### Description

User ID shown to differentiate users with the same roomnick is shown even after one person changes its roomnick. The users don't have the same nick anymore and as such it should not show the ID. Restarting the client does not fix this.

### Steps to reproduce

- 2 people use the same roomnick
- The user ID is shown to differentiate the users: `Roomnick (@someId:matrix.org)`
- UserA changes the roomnick
- On new messages the name of UserB still includes the user ID after the nick

The name of UserB should not include the user ID after UserA changed it to a different name.
The Android and iOS apps show the correct behaviour.

Log: not sent    

![username](https://user-images.githubusercontent.com/24251362/55711460-f9d2b380-59ec-11e9-81b2-d5d0a562d067.png)

The screenshot also possibly shows a race condition. A's name should also include his ID (the mobile app included it).

### Version information

- **Platform**: Desktop
- **OS**: Tested on Windows and Arch
- **Version**: 1.0.6

**Comment by t3chguy** [comment] 2020-07-12 19:22
Duplicate of https://github.com/vector-im/riot-web/issues/4795

**Closed by t3chguy** 2020-07-12 19:22 UTC
Labels: bug, p1, type:timeline, ui/ux
