### ISSUE TITLE
EXIF data is ignored by avatar uploader

### ISSUE THREAD

**Issue by yangm97** [vector-im/riot-web#4955] opened 2017-09-01 06:40 UTC
### Description

Using riot desktop on macOS High Sierra, setting the display picture will result in an upside down avatar set

### Steps to reproduce

- Change the display picture

The display picture should be the same as the file selected, not upside down.

Log: sent    

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: macOS High Sierra
- **Version**:  0.12.2 

EDIT: turns out my photo had EXIF data telling: “Orientation: Rotate 180”, so the actual issue is avatar uploader ignoring EXIF data

**Comment by MacLemon** [comment] 2017-09-12 09:58
I think that the Avatar uploader *should* actually strip all EXIF data, but respect the rotation tag.

Why strip all EXIF? Privacy! There is absolutely no reason to leak the GPS location, camera make and model, lens serial number, etc. to the server or any other account receiving that avatar picture.

Since the server will (afaik) rescale the avatar picture anyway, it could respect the rotation and still remove everything else. (Of course it could also remove the rotation tag and just rotate the picture as instructed there.)

Ideally the client would already do this before uploading. (Prevents privacy leaks at the source and reduces uploaded data and burden on the server.)

**Comment by t3chguy** [comment] 2017-09-12 09:59
Related https://github.com/vector-im/riot-web/issues/1999

**Comment by t3chguy** [comment] 2017-09-12 10:00
@MacLemon the issue you want is https://github.com/vector-im/riot-web/issues/4426

**Comment by turt2live** [comment] 2019-02-15 02:23
Duplicate of https://github.com/vector-im/riot-web/issues/2059

**Closed by turt2live** 2019-02-15 02:23 UTC
Labels: bug, minor, p2
