### ISSUE TITLE
FTUE: Canonical DMs

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10765] opened 2019-09-05 22:44 UTC
<img width="1028" alt="Screenshot 2019-09-05 at 15 42 15" src="https://user-images.githubusercontent.com/4626865/64388380-c627a400-cff3-11e9-9f3b-b5be1530407b.png">

[https://zpl.io/ad141pp](https://zpl.io/ad141pp)

- [ ] Make DMs canonical (https://github.com/matrix-org/matrix-doc/pull/2199)
- [ ] Implement new DM flow
- [ ] Don’t send message invite until sending first message

Update behaviour of member button (top right):
 - [ ] In a 1:1 DM should simply reveal the user profile
  - [ ] In a group DM, should reveal the member list

**Comment by r4dh4l** [comment] 2019-10-11 09:34
HI,

I hope this is the right issue https://matrix.org/blog/2019/10/10/new-vector-raises-8-5-m-to-accelerate-matrix-riot-modular is referring to saying

> Canonical DMs (having one DM per user, and have them feel clearly distinct from ‘rooms’)

Actually I was a little bit afraid reading this because the "everything is a room" concept of Matrix is a fantastic feature. This concept is not the problem in my opinion, the problem is that newcomers thinking in "Direct chat" and "Group chat" are not introduced into this concept at all.

May I suggest the following:

- completely redesign what happens when users press/click the `+` button:

1. It should open "create a new [matrix] room" in all cases (because this is what technically happens, don't hide this from users).
2. Explain what happens in a short note like: 

> All conversations in the [matrix] network take place in rooms. Like in real life a room can be empty, can contain just you or a fluctuating amount of people. There are no fixed "multi user chat" or "direct chats" (a direct chat can become a multi user chat and a multi user chat can become a direct chat, even just for you an your personal notes).

3. Use the wizard steps which are currently appear for "Start a chat", so just ask for "Who would youb like to communicate with?" because this can be just me, another user and me or a group of users and me. Finished.
4. All other settings the wizard "Create a private room"  is asking for can be done later via rooms settings while
- "Make this room public" default is "no"
- "Block users on other matrix homeservers from joining this room (This setting cannot be changed later!)" default is "no" and online visible if the initially invited users are from the same home server

Overall: Don't hide a matrix core feature from the users - explain it well. Users are willing to learn if the explanation is done well.

- merge the categories "people" and "rooms" to "normal priority" (because this is canonical to "favorites" and "low priority") and completely hide what is not used
- let people define their own contact categories instead

**Comment by turt2live** [comment] 2019-11-25 04:08
@r4dh4l as mentioned on the proposal, nothing is changing about the backend of the room: it's still a room. Much of your proposal is already in the design screenshot (wizard-like setup, most options not included, easier to use than before). Explaining that DMs are just rooms is hard to do, particularly when the average user doesn't care and just wants to get talking - they'll realize it's just a room when the chrome around the app is still there like it is for any other room.

**Comment by turt2live** [comment] 2019-11-25 04:12
also closing this in favour of the broken out issues:
* https://github.com/vector-im/riot-web/issues/11201
* https://github.com/vector-im/riot-web/issues/11200
* https://github.com/vector-im/riot-web/issues/11199
* https://github.com/vector-im/riot-web/issues/11198
* https://github.com/vector-im/riot-web/issues/11197
* https://github.com/vector-im/riot-web/issues/11196

**Closed by turt2live** 2019-11-25 04:12 UTC
Labels: project:ftue

**Comment by bwindels** [comment] 2019-11-25 08:41
@turt2live are these requirements from this issue included in any of the other tickets?
>  Make DMs canonical (matrix-org/matrix-doc#2199)
>  Don’t send message invite until sending first message
> In a 1:1 DM should simply reveal the user profile
> In a group DM, should reveal the member list

There is some overlap with the "Improve User Lists" FTUE project, but that one doesn't include the above AFAIK.

**Comment by turt2live** [comment] 2019-11-25 16:05
@bwindels it looks like they weren't - have filed https://github.com/vector-im/riot-web/issues/11495 to track the missing pieces (rather than fix this issue for the requirements)
