### ISSUE TITLE
Mysterious notification from upgraded/tombstoned room

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/riot-web#13503] opened 2020-05-05 11:51 UTC
### Description

Mods and Admins can still post to old versions of a room: #13502. If they do, Riot adds a notification to the global notification count, but you can not find the origin of this in the UI.

### Steps to reproduce

- Upgrade room, see #13502
- Post in old version of room

Either ignore new events to old rooms, or somehow indicate them.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.5.15

**Comment by turt2live** [comment] 2020-05-05 15:29
This sounds like a duplicate of https://github.com/vector-im/riot-web/issues/11859

**Closed by turt2live** 2020-05-05 15:29 UTC
Labels: bug
