### ISSUE TITLE
Plaintext representation of nested rich replies get mangled at some point

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/riot-web#5974] opened 2018-01-11 17:42 UTC
The plaintext representation of the rich reply example from #5969 ended up
looking like this:

```
&Adam:
> TravisR:
> Welcome Back Bot:
> Welcome back, @richvdh:sw1v.org

beep

So what does a reply to a reply look like?

Oh boy...
```

This isn't at all helpful to clients that aren't html-aware. Maybe it's only the
first message that gets `>` style quotes. Maybe it's specific to `m.notice`
messages. Either way, it's confusing.

**Comment by lampholder** [comment] 2018-01-16 11:30
I suggest the plaintext include the message being replied to (in a predictable format), a link to that message's event, and the message text of the reply. Something like:

```
2017-09-15T12:04:33Z <toml> (@tom:lant.uk): Hey, bob, how's it going? [https://matrix.to/#/!lbPPsPcefsfdsefPjRn:lant.uk/$1513243242101Udovh:lant.uk]
Pretty good thanks, and you?
```

**Comment by t3chguy** [comment] 2018-01-16 11:33
@lampholder how about nested in that case?

**Comment by t3chguy** [comment] 2018-01-16 12:39
So if we want to fix #5968, then the plaintext rep wouldn't have the entire nested depth, which is going to be hard as we'll have to parse out any quoted events before quoting it ourselves

**Comment by t3chguy** [comment] 2018-02-01 15:58
Related https://docs.google.com/document/d/1KLdKtuZBbFoWDSfN4KM3p7LnIvFBQfSORICBo8zRHaE/edit

**Comment by t3chguy** [comment] 2018-02-01 16:01
So fwiw this issue is caused by https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/MessageComposerInput.js#L853 assuming that there are no newlines. It should instead prepend `> ` to each line in `contentText`

**Comment by t3chguy** [comment] 2018-05-04 08:41
Fixed by merged PR

**Closed by t3chguy** 2018-05-04 08:41 UTC
Labels: bug, major, p1, type:replies, ui/ux
