### ISSUE TITLE
Unable to delete uploaded files

### ISSUE THREAD

**Issue by AaronMT** [vector-im/riot-web#3994] opened 2017-05-22 21:49 UTC
### Description

One is unable to delete uploaded files in a room with members

### Steps to reproduce

- Upload a file

### Expected Results

- On opening the files pane there should be an option to delete a file

### Version information

Using Riot IM on the web in Chrome 58.0.3029.110, Windows 10

Homeserver is https://matrix.org
Identity Server is https://vector.im
matrix-react-sdk version: 0.8.9
riot-web version: 0.9.10
olm version: 2.2.1

**Comment by uhoreg** [comment] 2017-05-23 02:37
A workaround is to redact the file event from the room.  If people already have the file link, they can still fetch it, but new people won't see the file in the room.

**Comment by lampholder** [comment] 2017-05-23 14:58
There will come a time when sbdy uploads something they really didn't want to/shouldn't have, so this is an important feature for the platform to have.

How it's implemented, who can delete which files, and what the implications are for files than have been cached remotely is an interesting topic (which may have already had some thought).

**Comment by CIAvash** [comment] 2018-03-04 18:41
What @lampholder said happened to me, I wanted to delete the file I uploaded and naively thought removing the event would delete it but it seems I was wrong. It was a private chat and people seeing it wasn't a problem, I just wanted it to be deleted from the server.

What interface is going to be provided for deleting files that no longer can be seen? Will users have access to a list of files they have uploaded?

It would be nice if there was some docs that explained how much control users have over their content.

**Comment by t3chguy** [comment] 2018-03-04 18:44
@CIAvash I mean in the end if you don't control the servers that have your content you can't ensure deletion, this is even more painful when considered with federation

**Comment by colans** [comment] 2018-08-01 22:12
Maybe add two permissions for this:
* Delete your own files (default: 0, anybody)
* Delete others' files (default: 50, moderators)

**Comment by t3chguy** [comment] 2018-08-01 22:14
@colans the issue is files don't belong to rooms, I could upload a file once and send it into 100s of rooms, having those room moderators able to delete the file would be potentially massively destructive?
(esp given its impossible to know what rooms a file is in, because e2ee)

**Comment by turt2live** [comment] 2019-02-15 02:27
Closing in favour of https://github.com/vector-im/riot-web/issues/5025 (more outbound links)

**Closed by turt2live** 2019-02-15 02:27 UTC
Labels: feature, p2
