### ISSUE TITLE
breadcrumbs don't get updated to reflect room upgrades

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11472] opened 2019-11-22 17:55 UTC
if you click on a breadcrumb after upgrading a room you can get teleported back into the old room, which is rather annoying

**Comment by turt2live** [comment] 2019-11-22 17:56
Duplicate of https://github.com/vector-im/riot-web/issues/11469

**Closed by turt2live** 2019-11-22 17:56 UTC
