### ISSUE TITLE
seequ says adding a room to favs doesn't remove from rooms

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3801] opened 2017-05-04 12:56 UTC
probably shouldComponentUpdate() fail

**Comment by turt2live** [comment] 2017-05-04 14:16
related/dupe: #3797

**Comment by lampholder** [comment] 2017-05-05 08:46
High priority because super-glitchy.

If this turns out only to affect tag API users perhaps consider a lower priority.

**Comment by JaniM** [comment] 2017-05-16 17:28
This was fixed by removing `im.vector.fake.recent`, as per #3797.

**Comment by lampholder** [comment] 2017-07-21 11:57
Closing as a dupe of #3797

**Closed by lampholder** 2017-07-21 11:57 UTC
Labels: bug, major, p1, type:roomlist
