### ISSUE TITLE
there is no tab, space, comma or enter complete on the new DM invite text field

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12283] opened 2020-02-07 11:23 UTC
i'd expect ke<tab> to expand to kegan or something. or typing @kegsay:example.com and hitting return to actually use the mxid. But unless you actually click on the autocomplete list item, there doesn't seem to be any way to actually complete the ID into a pill, or even use the ID correctly the dialog at all.  Hitting space or enter just starts entering freeform whitespace in.  It's all a regression from the previous invite dialog

**Comment by turt2live** [comment] 2020-02-07 11:56
Duplicate of https://github.com/vector-im/riot-web/issues/11771

**Closed by turt2live** 2020-02-07 11:56 UTC
