### ISSUE TITLE
Create room button should add the room to the filtered community

### ISSUE THREAD

**Issue by brylie** [vector-im/riot-web#11824] opened 2020-01-12 11:06 UTC
### Description

On Riot.im, I am managing a couple of groups. When I try to add a room to the group, it is successfully created but does not appear under the group room list.

### Steps to reproduce

- Create a community on Riot.im
- Click community icon to activate community namespace
- Click the "+" next to the *Rooms* header in the sidebar
- Fill in required details, including making room public

The room should appear in the rooms list for other group members to see.

### Version information

- **Platform**: web (in-browser) at riot.im

For the web app:

- **Browser**: Firefox 72.0.1
- **OS**: Ubuntu
- **URL**: riot.im/app

**Comment by turt2live** [comment] 2020-01-13 03:10
This is actually unrelated to https://github.com/vector-im/riot-web/issues/6192.

The + button doesn't actually do anything with respect to the group - the room still needs to be manually added to the group. I thought we had an issue for this already, but I can't find it.

I've updated your issue title to reflect this.

**Comment by brylie** [comment] 2020-01-13 09:10
Thank you, @turt2live. The UX is indeed a bit counter-intuitive :-)

From an end-user perspective, the + button would seem to be creating a new group under the community. That is, in fact, desirable, as I would like to create a community and add a couple of groups.

In the meantime, is there some documentation showing how I can get rooms to show up under the  "Rooms" section of the community portal?

**Comment by brylie** [comment] 2020-01-13 09:14
All I can find under the room settings is "Show flair for these communities." Adding flair doesn't seem to associate the room with the community.

**Comment by brylie** [comment] 2020-01-13 09:21
Hm. I did manage to find it.

1) click the community icon
2) click the ellipsis that pops up
3) click the "View Community" button
4) click the hash symbol in the upper-right-hand corner of the screen
5) click the "Add rooms to this community" button
6) search for one or more existing rooms
7) click the "Add to community" button

These steps would be much simpler by adding the room to the community when using the "+" button next to the "ROOMS" header in the community sidebar.

Relatedly, does using the "+" button next to "PEOPLE" in the community sidebar add people to the community?

**Comment by brylie** [comment] 2020-01-13 09:33
Also, the rooms list is not showing up for anonymous people.
https://riot.im/app/#/group/+codebuddies:matrix.org

It would be useful if the conversations in our community could be publicly visible, so new community members would have a clear incentive to join.

**Comment by t3chguy** [comment] 2020-01-13 11:39
One issue here is you can actually select multiple communities to filter using shift, so should it get added to all of them?

**Comment by brylie** [comment] 2020-01-13 17:52
Hm, that makes it a bit trickier. 

IMO there should be only one allowed community filter at a time. That is probably more familiar, as people are accustomed to using systems like Discord and Slack that show only one community's channels at a time.

If the community button filters down to only one community at a time, it would follow naturally that clicking the "add room" plus button would add a room to that community.

**Comment by t3chguy** [comment] 2020-01-13 17:55
Riot is already very different to Discord as a room can be in 0 to Infinity communities. Multiple community filtering is on purpose and is very useful for a lot of people

**Comment by Dremor** [comment] 2020-02-14 14:49
I agree that the current behaviour is quite non-intuitive. If you create a room, you expect to see it immediately in the room list, not to have to do a multi-step procedure to add it to your currently selected communities.
 
> One issue here is you can actually select multiple communities to filter using shift, so should it get added to all of them?

In my opinion, the ideal solution would be something like this:
- Add the list of your communities in the channel creation (after the "Subject" field, or after the "Make this room public" radio button), with a mean to select/unselect all.
    - If one or more communities is selected, select them by default in the communities list
    - if no community is selected, none are selected in the list.

**Comment by hiaselhans** [comment] 2020-03-16 21:51
i agree with @Dremor 

users are used to commercial solutions behaviour.
The closest would be to choose with radio buttons from:

 * make it public
 * add it to communities
 * add all users in the comunity to the room

**Comment by Zash** [comment] 2020-03-31 10:51
Related to #9970 ?

**Comment by t3chguy** [comment] 2020-03-31 10:54
Duplicate of https://github.com/vector-im/riot-web/issues/9970 which has more attention

**Closed by t3chguy** 2020-03-31 10:54 UTC
Labels: suggestion
