### ISSUE TITLE
Created a room on mobile and encrypted it but it the encryption option is off on riot web

### ISSUE THREAD

**Issue by Qwertie-** [vector-im/riot-web#3776] opened 2017-04-30 13:08 UTC
On riot for android (fdroid 0.6.9) I created a room with another user with the button on their profile, I then enabled encryption. Everything working fine so far, both of us are talking with e2e enabled. I then loaded riot web development version and the room is full of 
`
** Unable to decrypt: The sender's device has not sent us the keys for this message. **`

Messages sent from web send unencrypted and the encryption option on web is unticked. I reloaded the page and nothing changed.

Attempting to enable encryption from web does nothing.

**Comment by lampholder** [comment] 2017-05-01 20:19
After joining from Riot web, when you (or the other user) try and send a message does it warn you that there's a new device in the room? I believe that a user with a verified device will have to verify your new device before it can send and receive encrypted messages.

That said, it sounds like there's another bug at play here - the room settings (the 'encryptedness' of the room) should be the same regardless of the device that's accessing the room.

Do you have any logs that you can share?

What do you mean by "Messages sent from web send unencrypted" - can you describe what this looks like?

Thanks!

**Comment by Qwertie-** [comment] 2017-05-02 05:20
>After joining from Riot web, when you (or the other user) try and send a message does it warn you that there's a new device in the room? I believe that a user with a verified device will have to verify your new device before it can send and receive encrypted messages.

I got this message and pressed send anyway

Not aware of any logs but when I send from desktop it shows up on my phone with the unlocked icon and on web I see "send a message (unencrypted)" in the text box.

**Comment by lampholder** [comment] 2017-05-11 15:36
HI @Qwertie- - if you scroll to the bottom of the global settings page (found by clicking the cog in the bottom left corner) you'll find a 'report a bug' button - clicking this will let you submit Riot logs to help with diagnosing an issue such as this.

**Comment by lampholder** [comment] 2017-05-11 15:43
Do you know if the encrypting event might have been redacted, as per https://github.com/vector-im/riot-web/issues/3498 ?

This is a little trick to verify - you might be able to see the redacted image in the timeline at a likely-looking spot in the history.

**Comment by Qwertie-** [comment] 2017-05-14 08:37
The event was not redacted. I recently reinstalled my OS so firefox's storage was wiped and when I relogged in to riot the room was showing as encrypted properly now.

**Comment by lukebarnard1** [comment] 2018-05-16 15:37
I can't reproduce this. Closing.

**Closed by lukebarnard1** 2018-05-16 15:37 UTC
Labels: bug, major, p1, type:e2e
