### ISSUE TITLE
new user flow with direct chat link (broken and non-obvious)

### ISSUE THREAD

**Issue by chaseadam** [vector-im/riot-web#5598] opened 2017-11-14 17:57 UTC
Ideally there is a quick way for **new** users to chat with a matrix user based on a link.
Links generated for riot do not have a flow for new users. For example https://riot.im/app/#/user/@chaseadam:matrix.org will put you into:
![screenshot from 2017-11-14 12-39-57](https://user-images.githubusercontent.com/333031/32795259-309f4856-c939-11e7-9aa5-a9028ff5f015.png)

when clicking on "start a chat" it goes through the temp user flow:
![screenshot from 2017-11-14 12-39-17](https://user-images.githubusercontent.com/333031/32795321-539396aa-c939-11e7-8fa7-e7e664d7a028.png)

unfortunately, after going through the new user flow, the "Start a chat" and "Press <icon> to start a chat with someone" elements don't appear to do anything.

The channel invite screen is more obvious (red join link) and the new user flow functions as as expected.
![screenshot from 2017-11-14 12-46-28](https://user-images.githubusercontent.com/333031/32795756-ae180934-c93a-11e7-9262-97439335176e.png)
![screenshot from 2017-11-14 12-52-40](https://user-images.githubusercontent.com/333031/32795762-b6d19658-c93a-11e7-8a16-32f956201787.png)

**Comment by chaseadam** [comment] 2017-11-14 17:59
relates to #2373 and #877

**Comment by turt2live** [comment] 2017-11-14 17:59
related/duplicate of: https://github.com/vector-im/riot-web/issues/4418 (based on https://github.com/vector-im/riot-web/issues/4418#issuecomment-313075153 )

**Comment by lampholder** [comment] 2017-11-22 16:11
The https://riot.im/app/#/user/@chaseadam:matrix.org?action=chat flow is _supposed_ to meet this usecase. But independently of that this looks quite horribly broken :( :( :(

**Comment by lukebarnard1** [comment] 2018-05-16 16:47
In practice, I'm not certain it is, at least testing locally.

**Closed** 2018-05-16 18:00 UTC
Labels: ILAG, bug, major, p1, ui/ux
