### ISSUE TITLE
Backup has an invalid signature from verified device

### ISSUE THREAD

**Issue by Morcin** [vector-im/riot-web#9357] opened 2019-04-02 09:42 UTC
### Description

Hi! I have a user reporting issues with his encryption and his key backup... Riot gives the following message in the settings:

Backup version: 1
Algorithm: m.megolm_backup.v1.curve25519-aes-sha2
All keys backed up 
Backup has a valid signature from verified device BTQPEYAOLK
Backup has an invalid signature from verified device LULYAOAXZE
This backup is trusted because it has been restored on this device

### Version information

- **Platform**: web (in-browser) or desktop?
Web - Chrome macOS 10.14.4 - 1.0.6
Desktop - macOS 10.14.4 - 1.0.6

**Comment by jryans** [comment] 2019-04-02 10:50
Thanks for the report! @dbkr, maybe you can help with this one?

**Comment by ara4n** [comment] 2019-04-02 10:55
i’ve asked for a rageshake from the other device, which should arrive tonight

**Comment by dbkr** [comment] 2019-04-02 11:04
Looks like the error here is that there isn't actually a signature from that device at all, but something thinks there is. What is device `LULYAOAXZE` and did you create / restore the backup on it?

**Comment by Morcin** [comment] 2019-04-02 21:51
I've just uploaded the logs from the second device, but it seems this device does not have the ID LULYAOAXZE, so this might not be related after all?

But I am unable to decrypt the message sent from device 1 on device 2 and vice versa

**Comment by dbkr** [comment] 2019-04-03 10:02
Yeah, it looks like this does have a different device ID and is just getting the same error message. I've added some logging (https://github.com/matrix-org/matrix-js-sdk/pull/883) which might help track down what's going on.

**Comment by Morcin** [comment] 2019-04-04 07:41
Found the right device and just did the rageshake. The backup status reports this, is that text supposed to be red?
![Screenshot 2019-04-04 at 09 40 23](https://user-images.githubusercontent.com/3593558/55538055-d262aa80-56bd-11e9-99fb-1dade84900a2.png)

**Comment by dbkr** [comment] 2019-04-09 12:41
Hmm, not a lot more to go on here: the device is failing to check its own signature in the same way but has had this signature as far as the logs go back. I've also fixed the bug where that text is red (it was correctly red but incorrectly reading 'valid'). The logging I added previously might help to throw some more light on what's going on here, so if you update Riot, you could try submitting a another bug report (from any of the devices).

**Comment by exuvo** [comment] 2019-04-12 19:12
I have the same problem in my client. Using default matrix.org homeserver.
Backup has 2 signatures. One from pre matrix security breach and one after. Device B Android phone shows both the old signature and the new one (from itself) as valid. Device A Desktop Windows7 only shows the old signature as valid and thinks device Bs signature is invalid (device is verified).

**Comment by dbkr** [comment] 2019-05-17 09:10
Still not sure what this could be happening so very interested in bug reports once the above logging PR has landed.

**Comment by Morcin** [comment] 2019-06-05 07:21
I re-uploaded some logs, I believe above PR has made it into stable?

I also think I have found what caused this; an Apple macbook restored from time machine displayed this behaviour, the backup was made on a different device, and then restored to a new machine. Would Riot/Matrix see this as the same device with a different signature? And if so, is something in place to accommodate for changing a device signature?

**Comment by dbkr** [comment] 2019-06-07 10:08
Thanks for resubmitting logs - I've now realised what the problem is here and it's fixed by the above PR.

**Comment by dbkr** [comment] 2019-06-07 10:08
actually shouldn't close this quite yet

**Closed** 2019-06-07 10:26 UTC
Labels: bug, question, type:e2e, 🔥 Fire 🔥
