### ISSUE TITLE
Show presence inside 1:1 chat icon

### ISSUE THREAD

**Issue by heylix** [vector-im/riot-web#11234] opened 2019-10-26 12:08 UTC
**Is your suggestion related to a problem? Please describe.**

If I want to write with someone instead of calling them for an immediate response, I would like the user icon (![icon_person](https://user-images.githubusercontent.com/36211486/67619262-b2313f00-f7f9-11e9-904b-b49c83a1c79c.png)) to show information about their online status.

**Describe the solution you'd like**

The person icon could be filled with solid green if they're online, with yellow if they're online but haven't done anything in the last X minutes and white (as currently) if they're offline.

**Describe alternatives you've considered**

If you click on their 1:1 chat you can see in the user list of said chat when they were last online.

**Additional context**

This issue was raised by test123321__ in #riot-web:matrix.org.

**Comment by tulir** [comment] 2019-10-26 12:09
Duplicate of #4199

**Closed** 2019-10-26 12:14 UTC
Labels: suggestion
