### ISSUE TITLE
New room list should have a "compact mode"

### ISSUE THREAD

**Issue by eternaleye** [vector-im/riot-web#14704] opened 2020-07-22 17:28 UTC
**Is your suggestion related to a problem? Please describe.**

The Element room list has always been far too spaced-out for my usage pattern, which includes a relatively large number of rooms. As a result, I have to do a lot of scrolling back and forth in normal usage, rather than being able to see at a glance what needs my attention.

**Describe the solution you'd like**

Ideally, I'd like a much more "condensed" room list mode, somewhat akin to the IRC mode for the room itself.

**Describe alternatives you've considered**

I've made heavy use of room tags and other tools for grouping rooms to help with this issue, but in the end it's not sufficient to just show fewer rooms.

Historically, I've resolved this with a user style applied via Stylus; the relevant parts of it (having just updated it for the new room list) are:

```CSS
    /* The room list entries are way too damn big */
    section#matrixchat .mx_LeftPanel .mx_RoomList .mx_RoomTile {
        margin-bottom: 0 !important;
        padding: 1px !important;
    }

    /* Part of this is due to the enormous avatars */
    section#matrixchat .mx_LeftPanel .mx_RoomList .mx_RoomTile .mx_DecoratedRoomAvatar .mx_BaseAvatar_initial,
    section#matrixchat .mx_LeftPanel .mx_RoomList .mx_RoomTile .mx_DecoratedRoomAvatar .mx_BaseAvatar_image {
        width: 16px !important;
        height: 16px !important;
        font-size: 10.4px !important;
        line-height: 16px !important;
    }

    /* Part of this is due to slightly oversized buttons */
    section#matrixchat .mx_LeftPanel .mx_RoomList .mx_RoomTile .mx_RoomTile_menuButton,
    section#matrixchat .mx_LeftPanel .mx_RoomList .mx_RoomTile .mx_RoomTile_notificationsButton {
        width: 16px !important;
        height: 16px !important;
    }
```

However, in the new room list, this results in an enormous amount of blank space below the shown rooms, as the resizer hard-codes how large it _expects_ room tiles to be, and deletes/recreates them based on this expectation:

![image](https://user-images.githubusercontent.com/99404/88207630-ef99f000-cc04-11ea-88ea-03a49276fcc9.png)

Given that, I've finally gotten around to submitting this. If this is not feasible, making `.mx_RoomSubList_resizer` decide how many rooms to show based on actual size of room tiles would make my workaround continue functioning.

**Comment by turt2live** [comment] 2020-07-22 17:29
Duplicate of https://github.com/vector-im/riot-web/issues/14099

**Closed by turt2live** 2020-07-22 17:29 UTC
Labels: suggestion

**Comment by turt2live** [comment] 2020-07-22 17:31
> making .mx_RoomSubList_resizer decide how many rooms to show based on actual size of room tiles would make my workaround continue functioning.

This is how it works btw, it just doesn't know that the height changed. People have reported success with running https://gist.github.com/turt2live/bca81c40117b6d5098b6b9cdaf9d3040 after their styles have been applied.

**Comment by eternaleye** [comment] 2020-07-22 17:31
Oh, thank you!
