### ISSUE TITLE
Failing to build latest release

### ISSUE THREAD

**Issue by ArchangeGabriel** [vector-im/riot-web#11925] opened 2020-01-18 00:50 UTC
Running `yarn install` from inside the extracted 1.5.7 release tarball yelds:
```
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["gemini-scrollbar@matrix-org/gemini-scrollbar#91e1e566"] is trying to unpack in the same destination "/build/.cache/yarn/v6/npm-gemini-scrollbar-1.4.3/node_modules/gemini-scrollbar" as pattern ["gemini-scrollbar@github:matrix-org/gemini-scrollbar#91e1e566"]. This could result in non-deterministic behavior, skipping.
warning requirejs@2.3.6: Invalid bin entry for "r.js" (in "requirejs").
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "matrix-react-sdk > emojibase-data@4.1.0" has unmet peer dependency "emojibase@*".
warning "matrix-react-sdk > qrcode-react@0.1.16" has incorrect peer dependency "react@0.12 - 16.2".
warning "matrix-react-sdk > react-addons-css-transition-group@15.6.2" has incorrect peer dependency "react@^15.4.2".
warning "matrix-react-sdk > diff-dom > rollup-plugin-terser@5.1.2" has unmet peer dependency "rollup@>=0.66.0 <2".
warning " > electron-builder-squirrel-windows@21.2.0" has unmet peer dependency "app-builder-lib@~21.2.0".
warning "eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
$ node scripts/yarn-sub.js matrix-js-sdk install && node scripts/yarn-sub.js matrix-react-sdk install
yarn install v1.21.1
info No lockfile found.
[1/4] Resolving packages...
warning better-docs > react-ace > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning better-docs > vue-docgen-api > pug > pug-code-gen > constantinople > babel-types > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning browserify-shim > exposify > through2 > xtend > object-keys@0.4.0: 
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > better-docs@1.4.7" has unmet peer dependency "react@^0.16.0".
warning " > better-docs@1.4.7" has unmet peer dependency "react-dom@^0.16.0".
warning "better-docs > react-frame-component@4.1.1" has unmet peer dependency "prop-types@^15.5.9".
warning "better-docs > react-frame-component@4.1.1" has unmet peer dependency "react@>= 16.3".
warning "better-docs > react-frame-component@4.1.1" has unmet peer dependency "react-dom@>= 16.3".
warning "better-docs > react-ace@6.6.0" has unmet peer dependency "react@^0.13.0 || ^0.14.0 || ^15.0.1 || ^16.0.0".
warning "better-docs > react-ace@6.6.0" has unmet peer dependency "react-dom@^0.13.0 || ^0.14.0 || ^15.0.1 || ^16.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ yarn clean && yarn build && git rev-parse HEAD > git-revision.txt
yarn run v1.21.1
$ rimraf lib dist
Done in 0.17s.
yarn run v1.21.1
$ babel src -s -d lib --verbose --extensions ".ts,.js" && rimraf dist && mkdir dist && browserify -d browser-index.js | exorcist dist/browser-matrix.js.map > dist/browser-matrix.js && terser -c -m -o dist/browser-matrix.min.js --source-map "content='dist/browser-matrix.js.map'" dist/browser-matrix.js
src/ReEmitter.js -> lib/ReEmitter.js
src/autodiscovery.js -> lib/autodiscovery.js
src/base-apis.js -> lib/base-apis.js
src/client.js -> lib/client.js
src/content-helpers.js -> lib/content-helpers.js
src/content-repo.js -> lib/content-repo.js
src/crypto/CrossSigning.js -> lib/crypto/CrossSigning.js
src/crypto/DeviceList.js -> lib/crypto/DeviceList.js
src/crypto/OlmDevice.js -> lib/crypto/OlmDevice.js
src/crypto/OutgoingRoomKeyRequestManager.js -> lib/crypto/OutgoingRoomKeyRequestManager.js
src/crypto/RoomList.js -> lib/crypto/RoomList.js
src/crypto/SecretStorage.js -> lib/crypto/SecretStorage.js
src/crypto/algorithms/base.js -> lib/crypto/algorithms/base.js
src/crypto/algorithms/index.js -> lib/crypto/algorithms/index.js
src/crypto/algorithms/megolm.js -> lib/crypto/algorithms/megolm.js
src/crypto/algorithms/olm.js -> lib/crypto/algorithms/olm.js
src/crypto/deviceinfo.js -> lib/crypto/deviceinfo.js
src/crypto/index.js -> lib/crypto/index.js
src/crypto/key_passphrase.js -> lib/crypto/key_passphrase.js
src/crypto/olmlib.js -> lib/crypto/olmlib.js
src/crypto/recoverykey.js -> lib/crypto/recoverykey.js
src/crypto/store/base.js -> lib/crypto/store/base.js
src/crypto/store/indexeddb-crypto-store-backend.js -> lib/crypto/store/indexeddb-crypto-store-backend.js
src/crypto/store/indexeddb-crypto-store.js -> lib/crypto/store/indexeddb-crypto-store.js
src/crypto/store/localStorage-crypto-store.js -> lib/crypto/store/localStorage-crypto-store.js
src/crypto/store/memory-crypto-store.js -> lib/crypto/store/memory-crypto-store.js
src/crypto/verification/Base.js -> lib/crypto/verification/Base.js
src/crypto/verification/Error.js -> lib/crypto/verification/Error.js
src/crypto/verification/QRCode.js -> lib/crypto/verification/QRCode.js
src/crypto/verification/SAS.js -> lib/crypto/verification/SAS.js
src/crypto/verification/request/InRoomChannel.js -> lib/crypto/verification/request/InRoomChannel.js
src/crypto/verification/request/RequestCallbackChannel.js -> lib/crypto/verification/request/RequestCallbackChannel.js
src/crypto/verification/request/ToDeviceChannel.js -> lib/crypto/verification/request/ToDeviceChannel.js
src/crypto/verification/request/VerificationRequest.js -> lib/crypto/verification/request/VerificationRequest.js
src/errors.js -> lib/errors.js
src/filter-component.js -> lib/filter-component.js
src/filter.js -> lib/filter.js
src/http-api.js -> lib/http-api.js
src/indexeddb-helpers.js -> lib/indexeddb-helpers.js
src/indexeddb-worker.js -> lib/indexeddb-worker.js
src/interactive-auth.js -> lib/interactive-auth.js
src/logger.js -> lib/logger.js
src/matrix.js -> lib/matrix.js
src/models/event-context.js -> lib/models/event-context.js
src/models/event-timeline-set.js -> lib/models/event-timeline-set.js
src/models/event-timeline.js -> lib/models/event-timeline.js
src/models/event.js -> lib/models/event.js
src/models/group.js -> lib/models/group.js
src/models/relations.js -> lib/models/relations.js
src/models/room-member.js -> lib/models/room-member.js
src/models/room-state.js -> lib/models/room-state.js
src/models/room-summary.js -> lib/models/room-summary.js
src/models/room.js -> lib/models/room.js
src/models/search-result.js -> lib/models/search-result.js
src/models/user.js -> lib/models/user.js
src/pushprocessor.js -> lib/pushprocessor.js
src/randomstring.ts -> lib/randomstring.js
src/realtime-callbacks.js -> lib/realtime-callbacks.js
src/scheduler.js -> lib/scheduler.js
src/service-types.js -> lib/service-types.js
src/store/indexeddb-local-backend.js -> lib/store/indexeddb-local-backend.js
src/store/indexeddb-remote-backend.js -> lib/store/indexeddb-remote-backend.js
src/store/indexeddb-store-worker.js -> lib/store/indexeddb-store-worker.js
src/store/indexeddb.js -> lib/store/indexeddb.js
src/store/memory.js -> lib/store/memory.js
src/store/session/webstorage.js -> lib/store/session/webstorage.js
src/store/stub.js -> lib/store/stub.js
src/sync-accumulator.js -> lib/sync-accumulator.js
src/sync.js -> lib/sync.js
src/timeline-window.js -> lib/timeline-window.js
src/utils.js -> lib/utils.js
src/webrtc/call.js -> lib/webrtc/call.js
Successfully compiled 72 files with Babel.
Done in 16.59s.
fatal: not a git repository (or any of the parent directories): .git
error Command failed with exit code 128.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
child_process.js:650
    throw err;
    ^

Error: Command failed: yarn install
    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at Object.<anonymous> (/build/riot/src/riot-web-1.5.7/scripts/yarn-sub.js:18:15)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 128,
  signal: null,
  output: [ null, null, null ],
  pid: 2531,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by t3chguy** [comment] 2020-01-18 00:51
Duplicate of #11851

**Closed by t3chguy** 2020-01-18 00:51 UTC
Labels: bug

**Comment by ArchangeGabriel** [comment] 2020-01-18 00:53
I had searched for the error message, but not for `building from tarball`… Thanks!
