### ISSUE TITLE
clicking on LeftPanel when greyed out (e.g. by UserSettings) should cancel UserSettings

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5783] opened 2017-12-04 22:31 UTC
generally clicking on a greyed out background should cancel whatever modal state we're in, as per the dialogs. or UserSettings

**Comment by t3chguy** [comment] 2017-12-04 22:33
Duplicate of #5658

**Closed** 2017-12-04 22:33 UTC
