### ISSUE TITLE
Pressing escape should mark messages as read and jump to most recent

### ISSUE THREAD

**Issue by napostrophe** [vector-im/riot-web#12537] opened 2020-02-26 19:49 UTC
Pressing escape does nothing.

It would be nice if pressing escape should mark messages in a channel as read and bring you to the most recent message (bottom) like in Discord and Slack

**Comment by t3chguy** [comment] 2020-04-08 17:47
> and bring you to the most recent message (bottom)

Discord and Slack docs do not suggest they do this and that they only mark it as read

**Comment by napostrophe** [comment] 2020-04-08 18:36
> > and bring you to the most recent message (bottom)
> 
> Discord and Slack docs do not suggest they do this and that they only mark it as read

I haven't looked at their docs so I can't confirm whether they _say_ they do so or not, but in practice they do.

**Comment by jryans** [comment] 2020-04-09 09:30
Here are Slack's options around marking as read:

<img width="540" alt="2020-04-09 at 10 24" src="https://user-images.githubusercontent.com/279572/78879852-63483080-7a4c-11ea-90a6-14775902ecaf.png">

In my testing, pressing `esc` does not scroll anywhere, but instead it only updates the read state. @napostrophe, what settings above do you typically have set in Slack? Can you re-test to confirm if it does still scroll, as I can't reproduce it here.

**Comment by t3chguy** [comment] 2020-04-09 10:41
in Discord it does jump to bottom

**Comment by napostrophe** [comment] 2020-04-09 19:00
> In my testing, pressing `esc` does not scroll anywhere, but instead it only updates the read state. @napostrophe, what settings above do you typically have set in Slack? Can you re-test to confirm if it does still scroll, as I can't reproduce it here.

I tried again and it seems not to do it anymore. Sorry if my memory is failing me but I remembered it doing so. Maybe it's the fact that Slack starts at the newest message that made me think that. My bad. It does still work in Discord, though.

**Closed** 2020-04-30 16:40 UTC
Labels: Community PR, suggestion, type:shortcuts
