### ISSUE TITLE
Don't sort reactions by count

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#12167] opened 2020-01-31 10:57 UTC
Instead sort by the order they were reacted.

This was a miscommunication across platforms when we implementated aggregations last year. The order of reacting is an tool of expression in itself, which web currently breaks. Presently, iOS implements them correctly:

![image](https://user-images.githubusercontent.com/4626865/73534304-bc766100-4418-11ea-8c19-bc2ad2ba52ba.png)

Compared to:

<img width="463" alt="Screenshot 2020-01-31 at 10 56 47" src="https://user-images.githubusercontent.com/4626865/73534326-c8622300-4418-11ea-835d-1809e9021a9b.png">

**Comment by jryans** [comment] 2020-01-31 11:57
Duplicate of https://github.com/vector-im/riot-web/issues/9698

**Closed by jryans** 2020-01-31 11:57 UTC
