### ISSUE TITLE
Community list in LLP has an unneeded scroll bar

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#8592] opened 2019-02-13 17:38 UTC
![image](https://user-images.githubusercontent.com/1391051/52731652-24d4f400-2fb6-11e9-919b-e998c53b6618.png)

**Comment by turt2live** [comment] 2019-02-13 17:39
Duplicate of https://github.com/vector-im/riot-web/issues/8197

**Closed by turt2live** 2019-02-13 17:39 UTC
Labels: redesign

**Comment by Cadair** [comment] 2019-02-13 17:48
darn it, I searched for so many different things :woman_facepalming:
