### ISSUE TITLE
FR: Put a lock in the room icons for encryption

### ISSUE THREAD

**Issue by gerroon** [vector-im/riot-web#8742] opened 2019-02-17 03:53 UTC
Hi

It will be really useful to have a lock icon in the icons of encrypted room's. It is hard to tell which room is encrypted which is not, well until one enters the room.

thanks

**Comment by aaronraimist** [comment] 2020-01-05 01:39
Duplicate of #11226

**Comment by turt2live** [comment] 2020-01-05 02:18
Not sure that's true, 11226 seems to be about the general decoration and not the room list.

**Comment by foldleft** [comment] 2020-01-24 11:24
Duplicate of https://github.com/vector-im/riot-web/issues/11935

**Closed by foldleft** 2020-01-24 11:24 UTC
Labels: feature, suggestion, type:e2e, ui/ux
