### ISSUE TITLE
UX impovement request: add ability to copy-paste encryption key id

### ISSUE THREAD

**Issue by unclechu** [vector-im/riot-web#6676] opened 2018-05-05 02:29 UTC
In the user menu I could see it by hovering mouse on a key:
![screenshot from 2018-05-05 07-26-44](https://user-images.githubusercontent.com/799353/39658880-e60e6da6-5035-11e8-9304-da9dce1e7cf2.png)
But I can't copy-paste it to ask to verify it or something. I think it would be handy if we could select it as text or even have a button to copy it to the clipboard buffer.

**Comment by lampholder** [comment] 2018-05-09 09:18
If you click on the 'Verify...' it does load a modal which has the device id (and the device key) in a highlightable and copy+pastable format.

**Comment by lampholder** [comment] 2018-05-09 22:13
That's true. 

Okay, in which case I guess we can consider this a bug - I expect it to be fairly minor though unless there's a strong use case for people wanting this information for devices they've already verified?

**Comment by Mikaela** [comment] 2019-11-27 12:39
I think this is a duplicate of https://github.com/vector-im/riot-web/issues/2735.

**Closed** 2019-11-27 15:58 UTC
Labels: bug, p3, ui/ux
