### ISSUE TITLE
encrypted symbol on list of salon/chat

### ISSUE THREAD

**Issue by Thatoo** [vector-im/riot-web#7194] opened 2018-08-19 21:37 UTC
Hello,

In Riot android, we can easily see which chat/salon is encrypted thanks to a small lock on the bottom right of the chat/salon's picture.
In Riot desktop, there isn't any symbol to show it. No lock sign...
Would it be possible to have an option that display this symbol in Riot desktop too?

Thank you,

Thatoo

**Comment by lampholder** [comment] 2018-08-20 13:08
I would like this too, though I don't think it's been considered for the redesign.

**Comment by ara4n** [comment] 2018-08-20 14:19
i would also like this too - let's use the design tag for stuff which needs design input.

**Comment by aaronraimist** [comment] 2020-01-05 01:39
Duplicate of #11226

**Closed** 2020-04-13 09:08 UTC
Labels: cosmetic, feature, needs-design, p2, type:e2e, type:roomlist
