### ISSUE TITLE
Search in a room: give visual feedback while executing

### ISSUE THREAD

**Issue by Croydon** [vector-im/riot-web#3414] opened 2017-03-11 22:36 UTC
### Description

Searches can take a long time. After typing in a keyword and pressing the search button I can't see anything going on for a long time.

## Expected result

While the search is going on in the background there should be visual feedback of some sort so that I know that something is going on at all (is the search even working? is the search on holidays?) 

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 0.9.7

**Comment by ara4n** [comment] 2017-03-11 22:47
The search icon should be flashing at you.  But agreed this should be fixed.

**Comment by Croydon** [comment] 2017-03-11 22:48
Oh, indeed. It's really hard to see with the dark Riot theme and a light green room color.

**Comment by lampholder** [comment] 2017-08-04 08:55
Related https://github.com/vector-im/riot-web/issues/4707

**Comment by grahamperrin** [comment] 2017-09-15 19:09
Thanks @lampholder 

@Croydon is my #4707 a duplicate of this 3414?

AFAICT (at least, with `/develop/`) there _is_ feedback if the search is begun with <kbd>Return</kbd> or <kbd>Enter</kbd>.

**Comment by Croydon** [comment] 2018-01-03 00:27
I just rediscovered this as I'm trying to catch up with my inbox.

Yes, it is a duplicate.

But imho here should be getting more done as the color fix of the button. The loading circle, when messages in rooms are loaded, can be reused on the search page as it is much more obviously.

**Comment by turt2live** [comment] 2019-02-15 00:33
This happened

**Closed by turt2live** 2019-02-15 00:33 UTC
Labels: bug, cosmetic, design, p1, ui/ux
