### ISSUE TITLE
Consider ditching RRs on tiny screens to save space

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2002] opened 2016-08-23 23:34 UTC

**Comment by t3chguy** [comment] 2017-10-24 20:38
RRs are now user-disablable, and there is a new issue of the space still being taken up - I think that splits off from this

**Comment by aaronraimist** [comment] 2020-03-07 02:12
Closing as duplicate of https://github.com/vector-im/riot-web/issues/4248 and https://github.com/vector-im/riot-web/issues/1633 which have thumbs and conversation

**Closed by aaronraimist** 2020-03-07 02:12 UTC
Labels: cosmetic, feature, p3, type:readreceipts
