### ISSUE TITLE
Tiny Background Icon

### ISSUE THREAD

**Issue by sherif7810** [vector-im/riot-web#7898] opened 2018-12-17 17:09 UTC
### Description

Fuchsia background icon in KDE is tiny.

### Steps to reproduce

1. Add FlatHub.
2. Run `flatpak install flathub im.riot.Riot`.

I expected the icon to be larger.

### Version information

- **Platform**: Desktop
- **OS**: 64 bit Linux (Fedora 29 KDE spin).

### Screenshot

![screenshot_20181217_190826](https://user-images.githubusercontent.com/37023248/50102966-2fca0d00-022f-11e9-97da-da23cfeca1f7.png)

**Comment by turt2live** [comment] 2018-12-17 17:13
Duplicate of https://github.com/vector-im/riot-web/issues/7555

**Comment by sherif7810** [comment] 2018-12-17 17:13
[Repo](https://github.com/flathub/im.riot.Riot).

**Closed by turt2live** 2018-12-17 17:13 UTC

**Comment by mortlind** [comment] 2019-01-18 07:42
@turt2live You closed this issue, since it is a duplicate of #7555 and on the same day, you close #7555 because it is a duplicate of this issue (#7898)? Did you intend to reference some third issue in one of the notes about duplication? None these two issues seems to be resolved.
