### ISSUE TITLE
Diff syntax in dark mode is wrong

### ISSUE THREAD

**Issue by dngray** [vector-im/riot-web#11553] opened 2019-11-28 17:22 UTC
Red should be for removal, green for addition. It is the opposite of light mode, ie what we normally expect.

See screenshot:
![diffsyntax](https://user-images.githubusercontent.com/48640805/69824403-8db6f100-1203-11ea-8be0-abf7eced619b.png)

**Comment by t3chguy** [comment] 2019-11-28 19:40
Duplicate of https://github.com/vector-im/riot-web/issues/7921

**Closed by t3chguy** 2019-11-28 19:40 UTC
Labels: bug
