### ISSUE TITLE
Option to disable markdown missing

### ISSUE THREAD

**Issue by CyberneticCody** [vector-im/riot-web#14167] opened 2020-06-23 23:15 UTC
![composer](https://user-images.githubusercontent.com/55600371/85475930-fccfaa80-b584-11ea-8c70-a7ed4a99e7f8.png)
![composer options](https://user-images.githubusercontent.com/55600371/85475932-fccfaa80-b584-11ea-9747-e15dd3b8ed7b.png)

### Description
There used to be an option to disable markdown in the desktop client, and there still is an option to do so on mobile. In this new version of Riot the option appears to have gone missing.

### Steps to reproduce
Clean install the latest version, open settings or try to find the markdown button in the composer.

Expected results: Find the option to disable markdown, or the button that used to be on the composer.

Logs being sent: Yes

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Linux Mint (Ubuntu) 19.3 Cinnamon
- **Version**: 1.6.6 (The desktop app says "riot-web version" so I hope this is right... I am not using the web version.

**Comment by jryans** [comment] 2020-06-24 11:39
In the current version, all messages are treated as Markdown, there are no modes or options. I believe this is a duplicate of https://github.com/vector-im/riot-web/issues/483.

**Closed by jryans** 2020-06-24 11:39 UTC
Labels: suggestion, type:composer, ui/ux

**Comment by CyberneticCody** [comment] 2020-06-24 12:00
Why would Vector remove that feature? I used to keep markdown turned off because it is super annoying

**Comment by jryans** [comment] 2020-06-24 12:21
Removing modes is believed to simplify the composer experience for most people.
