### ISSUE TITLE
Redacting events in e2e rooms show both the placeholder image and 'unable to decrypt' error

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#5033] opened 2017-09-14 09:28 UTC
![image](https://user-images.githubusercontent.com/8582858/30422305-7693acbc-9937-11e7-9616-c83a3ceefda8.png)

**Comment by turt2live** [comment] 2017-09-14 14:35
Duplicate of https://github.com/vector-im/riot-web/issues/3744

**Closed** 2017-09-14 14:37 UTC
