### ISSUE TITLE
Announcement rooms are awfully sluggish

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#14711] opened 2020-07-22 23:07 UTC
It's almost certainly just having to page through hundreds and hundreds of join/parts and maybe avatar/displayname changes, but the experience is phenomenally bad - I'm five minutes into loading Element Web Announcements and I've managed to load one event from Ryan.

Is there anything we can do to better serve the announcement case?

This was brought to my attention by a user who also reported that the had the same experience after switching out of and back into the room (i.e. this triggered another slow load) - I _haven't_ been able to reproduce this so far.

**Comment by turt2live** [comment] 2020-07-22 23:44
Duplicate of https://github.com/vector-im/riot-web/issues/3261

**Closed by turt2live** 2020-07-22 23:44 UTC
Labels: bug
