### ISSUE TITLE
Option to collapse media thumbnails out of the way

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2418] opened 2016-10-05 13:30 UTC
We should unify this with hiding URL previews out of the way - probably an option in the EventTile context menu would be sufficient

**Comment by Matrixcoffee** [comment] 2017-03-21 14:13
#1520 seems relevant here as well.

**Comment by aaronraimist** [comment] 2020-03-07 02:21
Duplicate of #2466

**Closed by aaronraimist** 2020-03-07 02:21 UTC
Labels: feature, p2, type:timeline
