### ISSUE TITLE
Sublist can still fail to refresh correctly after removing filters (and community filters)?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8811] opened 2019-02-20 02:50 UTC
Some combination of unfiltering the roomlist is causing blank patches to appear in the RoomSubLists still. I don't think this is a layout alg issue as much as the rerender optimisation failing in some scenario when you change the list filtering.

If you scroll it by even 1 pixel, the missing labels immediately get rerendered.

take a look at the blank people section:

![blanks](https://user-images.githubusercontent.com/1294269/53062889-35a3cf00-34ba-11e9-9b10-f10c2b22122e.png)

**Comment by ara4n** [comment] 2019-02-21 22:16
still getting precisely this even after travis' ordering rewrite landed

**Comment by bwindels** [comment] 2019-02-22 17:10
https://github.com/matrix-org/matrix-react-sdk/pull/2681 landed today containing further fixes. Do you still see this?

**Comment by lampholder** [comment] 2019-03-14 15:03
Related https://github.com/vector-im/riot-web/issues/8801

@ara4n have you seen this again since https://github.com/matrix-org/matrix-react-sdk/pull/2681 20 days ago? Can we close this if not?

**Comment by ara4n** [comment] 2019-04-04 13:57
i get this absolutely constantly, i'm afraid; about 1 in 3 times i remove a filter.

**Comment by ara4n** [comment] 2019-04-06 00:15
case in point:

<img width="343" alt="Screenshot 2019-04-06 at 01 14 18" src="https://user-images.githubusercontent.com/1294269/55662214-6ee59380-5809-11e9-8c75-5a930fc8f5b8.png">

**Comment by bwindels** [comment] 2019-04-08 11:41
As I can't repro at all on my account, I suspect you need a large number of rooms in a section for the lazyrenderlist to screw up. So that would indicate it's not sort-related, but lazyrenderlist related. Will try to test with a larger account.

**Comment by bwindels** [comment] 2019-04-10 09:16
Tried with `davetest` (which isn't as large as your account) and could not reproduce. Does the People section have a scrollbar when this happens? Also, is it always the People section or happens with e.g. Rooms as well?

**Comment by bwindels** [comment] 2019-04-10 09:20
Also, could you please copy the DOM from the inspector (e.g. Copy as HTML) for the whole RoomSubList when you see it happening again?

**Comment by ara4n** [comment] 2019-09-19 12:45
i get this almost constantly. but i'd missed the questions here - will do so next time i see it. (although if letterboxes are going away i'm not sure we want to spend /too/ much time on this)

**Comment by ara4n** [comment] 2019-09-19 17:29
got this just now - @bwindels: I DM'd you with the innerHTML of the sublist from FF.
<img width="303" alt="Screenshot 2019-09-19 at 18 25 57" src="https://user-images.githubusercontent.com/1294269/65266646-6230cf80-db0b-11e9-9932-3f730de34217.png">

**Comment by t3chguy** [comment] 2020-07-16 08:14
Assuming resolved with new roomlist

**Closed by t3chguy** 2020-07-16 08:14 UTC
Labels: bug, cannot-reproduce, major, p1, type:roomlist
