### ISSUE TITLE
Adding an integration to a private chat should not change the name of the room

### ISSUE THREAD

**Issue by jimmycuadra** [vector-im/riot-web#4885] opened 2017-08-25 12:30 UTC
### Description

When you add an integration to a room that is categorized under the "people" group in the sidebar, the room name currently gets changed from the other person's name to include the name of the integration you added, and the room's avatar will change to something generic instead of the avatar of the other person.

### Steps to reproduce

* Start a new chat with a person.
* The name of the room will appear as "<person's name>" and the room's avatar will be the other person's avatar.
* Add an integration, e.g. Imgur.
* The name of the room will change to "<person's name> and Imgur" and room avatar will change to something generic.

I think the last bullet point should not happen.

### Version information

- **Platform**: Desktop/Electron
- **OS**: macOS Sierra (10.12.6)
- **Version**: 0.12.2

**Comment by uhoreg** [comment] 2017-08-25 12:58
Duplicate of #3087

**Closed by uhoreg** 2017-08-25 12:58 UTC
