### ISSUE TITLE
Clear text from filter box after a selection has been made.

### ISSUE THREAD

**Issue by Soundtoxin** [vector-im/riot-web#13844] opened 2020-05-28 18:10 UTC
**Is your suggestion related to a problem? Please describe.**
When using the amazing room filter feature via the ctrl-k shortcut, I noticed that even once I've made my selection by pressing enter, the text stays in the filter box. This does NOT impact fast room-switching, hitting ctrl-k again and typing part of another room name overwrites it, I can hit enter, I can still switch all from the keyboard.
The problem is then when "dog" from searching for my "dog ___" room stays in the filter box and hides all my other non-dog rooms. I then can't glance over and see my rooms, even though I've already done my room switch.

**Describe the solution you'd like**
I would like the filter box to be cleared after a selection has been made. This seems to be how Nheko does it.

**Describe alternatives you've considered**
A config option to set the current or new behavior could work okay, although I'm curious if anyone would prefer the current functionality even.

**Comment by t3chguy** [comment] 2020-05-28 18:17
I am 1000% sure this is a duplicate but am failing to find it :'(

**Comment by t3chguy** [comment] 2020-05-28 18:18
Duplicate of https://github.com/vector-im/riot-web/issues/7625

**Closed by t3chguy** 2020-05-28 18:18 UTC
Labels: suggestion
