### ISSUE TITLE
The direct chat invite username input is smaller than it appears

### ISSUE THREAD

**Issue by connection-reset** [vector-im/riot-web#14228] opened 2020-06-28 12:01 UTC
### Description
The actual input field in the direct chat invite dialog is smaller than it appears.

### Steps to reproduce

- Start a new direct chat from the sidebar
- Enter a few characters (17 "@" characters or 30 "a"s did it for me)
- Notice that the characters don't fill the (apparent) space but instead get line wrapped

The input field should be as big as it appears and probably not be a multi-line input.

Logs being sent: no

![2020-06-28_13-45-42](https://user-images.githubusercontent.com/6831775/85946617-e2f7e400-b945-11ea-8a7b-afaf2780e7b4.png)

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.6.4

**Comment by t3chguy** [comment] 2020-06-28 12:16
Duplicate of https://github.com/vector-im/riot-web/issues/13066

**Closed by t3chguy** 2020-06-28 12:16 UTC
Labels: bug, ui/ux
