### ISSUE TITLE
Allow to download debug logs

### ISSUE THREAD

**Issue by clopez** [vector-im/riot-web#11653] opened 2019-12-12 14:39 UTC
The feature to send debug logs its not working to me for some reasons that I don't know, see:

![debug_logs](https://user-images.githubusercontent.com/221181/70721203-74c73900-1cf5-11ea-97a2-217375cec609.png)

It would be amazing if this had another button "**Download logs**" that allowed me to download the logs, for checking locally or attaching later.

Can you add that? Thanks

**Comment by t3chguy** [comment] 2019-12-12 15:03
Duplicate of #8997

**Closed** 2019-12-12 15:03 UTC
Labels: suggestion
