### ISSUE TITLE
consider extending `m.emote` for /me's

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4459] opened 2017-06-29 10:41 UTC
this would allow for an i18n-friendly way of doing `/me's`/`/my` by adding something like a `possessive` flag to the content of an `m.emote` message allowing the client to render it slightly differently, for Riot in english it'd just append `'s` to the end of the Display Name for example - ties into #3443

**Comment by t3chguy** [comment] 2017-06-29 10:47
note to self: this would require slight refactor in https://github.com/MTRNord/matrix-react-sdk/blob/7ef16b154abf6ddf7e69130e480cdf8e7c263e74/src/components/views/rooms/MessageComposerInput.js#L522-L552
replacing the helper methods with a locally generate payload (looking cleaner imo)

**Comment by uhoreg** [comment] 2017-10-29 02:19
I'm not sure how i18n friendly this would actually be.  For one thing, the sentence that the emote is in may not match the interface language.  Secondly, it might require more complicated parsing of the sentence.  For example "/my maison est bleu" would need to turn into "La maison d'uhoreg est bleu".

**Comment by turt2live** [comment] 2019-02-15 02:00
Duplicate of https://github.com/vector-im/riot-web/issues/3443

**Closed by turt2live** 2019-02-15 02:00 UTC
Labels: feature, p4
