### ISSUE TITLE
Unable to unban a user.

### ISSUE THREAD

**Issue by rajanand02** [vector-im/riot-web#3099] opened 2017-01-31 01:08 UTC
Unable to unban a user once they have banned. The settings shows a list of banned user but on clicking the username nothing happens. The unban feature is missing in mobile clients as well. refer [298](https://github.com/vector-im/riot-android/issues/298)

**Comment by eternaltyro** [comment] 2017-01-31 06:31
Try this:

`/unban <username>`

**Comment by rajanand02** [comment] 2017-01-31 07:05
/unban <username> is giving me a modal with `Cannot leave user who was banned` as the message.

![image](https://cloud.githubusercontent.com/assets/4851763/22455328/bf196c84-e7b1-11e6-926f-9751f85f0ee1.png)

**Comment by eternaltyro** [comment] 2017-01-31 07:05
Duplicate of #3091

**Closed** 2017-01-31 07:32 UTC
