### ISSUE TITLE
User account avatar is not repainted when set it settings until the desktop app is restarted

### ISSUE THREAD

**Issue by alexander-yevsyukov** [vector-im/riot-web#14808] opened 2020-07-29 08:34 UTC
### Description

When I set the photo for my new account it did not replace the avatar placeholder shown before the user name at the top of the chat list panel. It takes to restart the desktop app for the photo to appear.

### Steps to reproduce

- Create new account.
- Go to All Settings / General / Profile.
- Upload a photo.
- Click the Save button.
- Notice that there is still the avatar placeholder instead of the newly set photo.
- Close the desktop app and start the app again. Now the photo appears.

### Version information

- **Platform**: Desktop
- **OS**: macOS
- **Version**: 1.7.2

**Comment by turt2live** [comment] 2020-07-30 21:09
I can't reproduce this or it got fixed on develop.

**Closed by turt2live** 2020-07-30 21:09 UTC
Labels: bug, cannot-reproduce, regression, type:new-room-list
