### ISSUE TITLE
Calls not supported Chrome

### ISSUE THREAD

**Issue by BladzheR** [vector-im/riot-web#11348] opened 2019-11-08 08:41 UTC
Calls not supported Chrome Version 78.0.3904.97, (64 bit Linux)

FireFox works(70.0.1 (64-bit Linux))

Riot-web 1.5.3; Matrix 1.5;

**Comment by jryans** [comment] 2019-11-13 10:30
Thanks for reporting this issue. I'm adding this to our investigation queue.

**Comment by dbkr** [comment] 2019-11-19 11:19
I'm not managing to reproduce this bug. Do you have any more information or repro steps? What homeservers are you using? What is the other client you're calling? What are your VoIP settings in Riot? How does it fail?

**Comment by t3chguy** [comment] 2020-06-01 14:09
Closing as unable to reproduce, Chrome VOIP has changed hugely since then

**Closed by t3chguy** 2020-06-01 14:09 UTC
Labels: bug, p1, type:voip
