### ISSUE TITLE
Riot-web don't send or show unavailable (idle, away, last active, last seen) presence states from client app in user status

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4811] opened 2017-08-18 09:44 UTC
I have Synapse homeserver with presence states enabled. And on large room I see only `Online` and `Offline for XXh` presence statuses for all people, and never see `Unavailable for XXh` (or away, idle, last active, last seen) status for users, that don't touch Riot app or computer many hours. And same problem with Riot Android app.

[Matrix spec](https://matrix.org/docs/spec/client_server/unstable.html#m-presence) provide `unavailable` state for this info:
```
["online", "offline", "unavailable"]
```
Does Riot use this state and send activity info as `last_active_ago` argument? If yes, why I don't see it in my homeserver setup? And how to enable sending away events in Riot-web and display them, confugure away timeout, etc?

**Comment by richvdh** [comment] 2017-08-18 11:51
It *does* show users with the `unavailable` presence as "idle".  The issue is that there aren't very many such users.

[The issue is compounded by the fact that presence is disabled on matrix.org, as per https://github.com/vector-im/riot-web/issues/2667]

**Comment by richvdh** [comment] 2017-08-18 12:12
in terms of setting our state to unavailable: closing in favour fo #4813

**Closed by richvdh** 2017-08-18 12:12 UTC
