### ISSUE TITLE
Ability to notify all mods or admins in a room.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13944] opened 2020-06-06 14:44 UTC
We must already have a bug for this somewhere, but I can't find it.  Just as we have `@room` support for ops to ping all users in a room, we should also have `@mods` or whatever to allow random users to (try to) ping all moderators in a room.

**Comment by t3chguy** [comment] 2020-06-06 14:46
Duplicate of https://github.com/vector-im/riot-web/issues/8147

**Closed by t3chguy** 2020-06-06 14:46 UTC
Labels: bug
