### ISSUE TITLE
Zero width space when pasting URL

### ISSUE THREAD

**Issue by ptman** [vector-im/riot-web#7175] opened 2018-08-16 08:17 UTC
### Description

Copy&Pasting (using ^c & ^v) from firefox address bar to riot composer adds a zero width space character (u+200b) to the end. Very frustrating. Breaks the url previews and makes most urls nonworking (some servers strip out whitespace).

### Version information

- **Browser**: Firefox
- **OS**: Debian
- **URL**: riot.im/develop

**Comment by lampholder** [comment] 2018-08-20 15:50
Which version of firefox are you seeing this in?

And are you copying from the ff address bar to a riot composer running in ff, or somewhere else? Have you verified the contents of your clipboard by pasting somewhere else?

Fwiw I couldn't reproduce this on either my mac or my ubuntu machine, running 63.0a1 (2018-07-24) and 61.0.1 respectively.

**Comment by ptman** [comment] 2018-08-20 18:17
Firefox 61.0.2, but I think it started with 60. Yes, copying from address bar to riot in the same firefox. The clipboard contents do not have extra chars at the end when pasting elsewhere.

**Comment by turt2live** [comment] 2018-10-31 22:57
@ptman are you seeing this on recent versions of Riot? 0.17 and higher have a newer composer that might have resolved the problem.

**Comment by ptman** [comment] 2018-11-01 07:52
Sure, let's close this. I'll reopen if I run into it again.

**Comment by ptman** [comment] 2019-03-04 09:02
I'm again having this problem with firefox. Going via the terminal (paste into terminal, copy from terminal) fixes it. Maybe related to #7062

**Comment by t3chguy** [comment] 2020-03-24 20:41
Is this still an issue for you in the new composer?

**Comment by ptman** [comment] 2020-03-25 06:39
haven't run into this lately, but haven't been using riot as much

**Comment by t3chguy** [comment] 2020-03-25 09:49
Closing for now, reopen if it happens again

**Closed by t3chguy** 2020-03-25 09:49 UTC
Labels: bug, cannot-reproduce, minor, p2, platform specific, question, type:old-composer
