### ISSUE TITLE
Sometimes get the "username already in use" message during registration

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#10001] opened 2019-06-10 10:53 UTC
Related: https://github.com/vector-im/riot-web/issues/7314

I got a similar experience twice in a row.
- First time, I:
    - registered with a username and password
    - went through three rounds of CAPTCHA
    - accepted the t's and c's
    - *was bounced back to the registration page with a 'This username is in use' error message at the top of the registration screen
    - checking the db, I had successfully registered the account
- Second time, I:
    - registered with a username and password
    - went through one or two rounds of CAPTCHA
    - accepted the t's and c's
    - saw a flash of "This username is in use' at the bottom of the registration screen
    - successfully entered the app

I had dev tools networking tab open for the second time through, here are some logs delivered in what is obviously the optimal format: anmiated gif:
![Screen Recording 2019-06-10 at 11 51 28 2019-06-10 11_52_46](https://user-images.githubusercontent.com/1922197/59191048-4ca82300-8b76-11e9-91df-1619fa75c985.gif)

**Comment by lampholder** [comment] 2019-06-10 10:54
Oh and:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/1922197/59191107-76614a00-8b76-11e9-845f-c010fece988b.png">

**Comment by lampholder** [comment] 2019-06-10 12:30
Just OOI, if your IS _does_ become unavailable after you've logged in, the obvious things that break are:
- invite by threepid (the request 500s and renders in Riot as a "*Server Error* _Unknown server error_" modal
- assocaiting an email with your account does work???

**Comment by lampholder** [comment] 2019-06-10 12:37
That last (now hidden) comment was wrong. If you stop your client from being able to communicate with the IS (but the IS is still up), nothing bad happens at all - you can still invite people and you can still add your own additional threepid associations.

**Comment by jryans** [comment] 2019-06-11 17:04
According to today's standup, this is believed to be fixed now. @lampholder, did you want to retest, or should we close?

**Comment by dbkr** [comment] 2019-06-13 16:19
This is caused by https://github.com/matrix-org/synapse/issues/5450

**Comment by dbkr** [comment] 2019-06-13 16:20
But also, https://github.com/matrix-org/matrix-react-sdk/pull/3101 means it would no longer be a problem for us.

**Comment by turt2live** [comment] 2019-06-18 16:40
(closing - we believe we've fixed this on develop, therefore the latest RC, therefore the next release)

**Closed by turt2live** 2019-06-18 16:40 UTC
Labels: bug, p1, type:registration, 🔥 Fire 🔥
