### ISSUE TITLE
Inserting emoji using OS X character picker causes composer to lose focus

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7218] opened 2018-08-24 10:01 UTC
Press ctrl+cmd+space to bring up the character picker, insert any character. Message composer loses the focus.

**Comment by lampholder** [comment] 2018-08-24 10:31
天啊现在我的电脑说的中文。

That's better. Despite messing up the keyboard chording and somehow switching input to Chinese, I _didn't_ experience this issue with the mac character picker. I'm on High Sierra 10.13.6 (17G65) and Riot Electron 0.16.

Either clicking or using the keyboard, both left the cursor in the composer.

**Comment by aaronraimist** [comment] 2018-10-11 03:48
@lampholder I can reproduce this in Chrome. In Safari, it loses focus and doesn't even type the emoji (if it is the first character) on /develop. Possibly related to updating slate?

**Comment by dbkr** [comment] 2018-10-11 08:34
https://github.com/vector-im/riot-web/issues/7472 has some diagnosis on this (I failed to find the original bug I filed). It happened for me both before an and after updating slate.

**Comment by lampholder** [comment] 2018-10-11 09:58
Gnh, I _can_ now repro this on Electron and on Chrome, and I've noticed something else on Firefox - following the same repro steps you get two emoji in the composer, a native one and a emojione one.

**Comment by lampholder** [comment] 2018-10-11 10:01
Useful stuff from @dbkr's second filing of this bug (#7472):

 Composer loses focus after typing emoji ...if it's the first character you type in the composer.

I'm using the OS X emoji picker here: unsure if there's a way to repro it on other platforms. Focus composer, ctrl+cmd+space, pick an emoji, emoji goes into composer, press another letter, nothing happens. If you press space, you get a space and can carry on typing.

Having looked into this a little, the selection in the DOM is moving to the sticker button in the time between the composer's componentDidUpdate and a setTimeout(,0) in componentDidUpdate.

```
componentDidUpdate() {
        console.log("i dun updated");
        const s = window.getSelection();
        console.log("selection anchor: ", s.anchorNode); // <-- prints the last text node in composer
        setTimeout(function() {
            console.log("selection anchor: ", s.anchorNode); <-- prints sticker button
        }, 0);
    }
``` 

More interestingly, I can repro this on the slatejs.org examples *if* I edit the HTML to put `<div>hello</div>` right after the content-editable div.

Edit: and conversely, if I remove everything after the composer in Riot (ie. the composer buttons and the members panel) I don't get the bug.

**Comment by ara4n** [comment] 2018-10-11 10:03
i got bitten by this (for the first time) today, since the upgrade to 0.41.

**Comment by dbkr** [comment] 2018-10-11 11:53
https://github.com/ianstormtaylor/slate/issues/2251 filed upstream

**Comment by turt2live** [comment] 2018-11-05 23:05
Closing in favour of https://github.com/vector-im/riot-web/issues/7665 to track the upstream issue.

**Closed by turt2live** 2018-11-05 23:05 UTC
Labels: bug, minor, p1, platform specific, type:composer, ui/ux, upstream-issue
