### ISSUE TITLE
[Feature request] Add a cute seal emoji

### ISSUE THREAD

**Issue by CsatiZoltan** [vector-im/riot-web#7791] opened 2018-12-06 17:30 UTC
Related issue #2648 , though no solution is provided so far to define custom emojis.

**Comment by lampholder** [comment] 2018-12-10 14:12
ᶘ ᵒᴥᵒᶅ

**Comment by lampholder** [comment] 2018-12-10 14:13
(The right solution to this is absolutely to support custom emojis)

**Comment by CsatiZoltan** [comment] 2018-12-11 09:59
> 
> 
> ᶘ ᵒᴥᵒᶅ

Can you elaborate how you typed it?

**Comment by turt2live** [comment] 2019-03-26 18:16
Custom emoji would be https://github.com/vector-im/riot-web/issues/2648

For now, we're moving towards relying on the operating system's emoji (https://github.com/vector-im/riot-web/issues/9281) so a request to the Unicode consortium may be in order. Closing this as a duplicate of https://github.com/vector-im/riot-web/issues/2648 and https://github.com/vector-im/riot-web/issues/9281

**Closed by turt2live** 2019-03-26 18:16 UTC
Labels: minor, p3
