### ISSUE TITLE
Overview of links in room

### ISSUE THREAD

**Issue by ptman** [vector-im/riot-web#6905] opened 2018-06-18 13:10 UTC
### Description

It would be nice to have an overview of links in a room in the same way that there's a list of files.

**Comment by t3chguy** [comment] 2018-06-18 13:11
This would be *expensive* because its not possible to ask the server to filter these for you

**Comment by krombel** [comment] 2018-06-18 13:30
You might add a tag on messages which contain links when sending them. This would then as well be useful to not list matrix.to links

**Comment by t3chguy** [comment] 2018-06-18 13:35
Would still need a spec change either way.

**Comment by lampholder** [comment] 2018-06-18 13:45
I would dearly love for this feature to exist :) 

When we hit something like this, the requirement to change the spec means that realising the potential value is usually blocked behind some much more important spec discussions. I _think_ it would be nice if all matrix clients could experiment with such features by using their own custom events, and then if the experiments worked out those custom events could be transitioned to part of the spec.

As a thought experiment - could that work here?

**Comment by turt2live** [comment] 2018-06-18 14:49
The spec proposal process requires proof of implementation (to make sure it's not insane/too hard/etc), so I think that fits perfectly here :)

**Comment by t3chguy** [comment] 2018-06-18 15:54
The experiment would have to be in synapse mostly so that filtering can work with this

**Comment by aaronraimist** [comment] 2020-01-15 21:34
Duplicate of #8746 (newer but it has more thumbs)

**Closed by aaronraimist** 2020-01-15 21:34 UTC
Labels: feature, p2
