### ISSUE TITLE
Selecting emoticon via mouse removes focus of text input field

### ISSUE THREAD

**Issue by makedir** [vector-im/riot-web#6663] opened 2018-05-03 17:10 UTC
If you type into the text field, and begin typing an emoticon, for example ":sm" and then select an emoticon with the mouse, the text field has no focus anymore, enter wont work.

Please change/fix this, so if you select an emoticon, you can easily send it away via enter.

Another issue: if more than one emoticon is in a row, they are rendered small and not big.

Client is latest desktop 64bit Windows.

**Comment by turt2live** [comment] 2018-05-03 17:34
Duplicate of https://github.com/vector-im/riot-web/issues/5078

**Closed** 2018-05-08 08:42 UTC
