### ISSUE TITLE
Disable Communites Filter Panel doesn't seem to work any more

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6561] opened 2018-04-19 14:05 UTC
Enabling the setting doesn't remove the communities filter panel.

It still doesn't take effect even after refreshing the page.

**Comment by lampholder** [comment] 2018-04-19 14:13
Ugh, this is somehow intermittent.

**Comment by lukebarnard1** [comment] 2018-04-25 10:52
I can't reproduce this. Note that you do have to close settings for the setting to take effect.

**Comment by CR0CKER** [comment] 2019-09-17 01:05
Same here. The preferences setting shows no effect in a freshly installed Riot desktop app on MacOS.

**Comment by t3chguy** [comment] 2019-10-10 08:43
Duplicate of fixed https://github.com/vector-im/riot-web/issues/8418

**Closed by t3chguy** 2019-10-10 08:43 UTC
Labels: bug, regression, type:communities, type:llp, ui/ux
