### ISSUE TITLE
Can't paste images

### ISSUE THREAD

**Issue by lnicola** [vector-im/riot-web#10010] opened 2019-06-11 08:09 UTC
### Description

Can't paste PNG images from clipboard:

![image](https://user-images.githubusercontent.com/308347/59254399-c30d5980-8c38-11e9-9323-1eb84f7d1436.png)

Server logs:

```
synapse[3521]: 2019-06-11 11:01:41,361 - synapse.http.server - 112 - ERROR - POST-21 - Failed handle request via 'UploadResource': <XForwardedForRequest at 0x7f3c582ccc18 method='POST' uri='/_matrix/media/v1/upload?filename=image.png' clientproto='HTTP/1.0' site=8008>
synapse[3521]: Traceback (most recent call last):
synapse[3521]:   File "/usr/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
synapse[3521]:     result = g.send(result)
synapse[3521]:   File "/usr/lib/python3.7/site-packages/synapse/storage/_base.py", line 527, in runWithConnection
synapse[3521]:     defer.returnValue(result)
synapse[3521]:   File "/usr/lib/python3.7/site-packages/twisted/internet/defer.py", line 1362, in returnValue
synapse[3521]:     raise _DefGen_Return(val)
synapse[3521]: twisted.internet.defer._DefGen_Return: None
synapse[3521]: During handling of the above exception, another exception occurred:
synapse[3521]: Traceback (most recent call last):
synapse[3521]:   File "/usr/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
synapse[3521]:     result = g.send(result)
synapse[3521]:   File "/usr/lib/python3.7/site-packages/synapse/storage/_base.py", line 487, in runInteraction
synapse[3521]:     defer.returnValue(result)
synapse[3521]:   File "/usr/lib/python3.7/site-packages/twisted/internet/defer.py", line 1362, in returnValue
synapse[3521]:     raise _DefGen_Return(val)
synapse[3521]: twisted.internet.defer._DefGen_Return: None
synapse[3521]: During handling of the above exception, another exception occurred:
synapse[3521]: Traceback (most recent call last):
synapse[3521]:   File "/usr/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
synapse[3521]:     result = g.send(result)
synapse[3521]:   File "/usr/lib/python3.7/site-packages/synapse/storage/_base.py", line 586, in _simple_insert
synapse[3521]:     defer.returnValue(True)
synapse[3521]:   File "/usr/lib/python3.7/site-packages/twisted/internet/defer.py", line 1362, in returnValue
synapse[3521]:     raise _DefGen_Return(val)
synapse[3521]: twisted.internet.defer._DefGen_Return: True
synapse[3521]: During handling of the above exception, another exception occurred:
synapse[3521]: Traceback (most recent call last):
synapse[3521]:   File "/usr/lib/python3.7/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
synapse[3521]:     yield h(self, request)
synapse[3521]:   File "/usr/lib/python3.7/site-packages/synapse/rest/media/v1/upload_resource.py", line 95, in _async_render_POST
synapse[3521]:     content_length, requester.user
synapse[3521]:   File "/usr/lib/python3.7/site-packages/synapse/rest/media/v1/media_repository.py", line 176, in create_content
synapse[3521]:     None, media_id, media_id, media_type,
synapse[3521]:   File "/usr/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
synapse[3521]:     result = g.send(result)
synapse[3521]:   File "/usr/lib/python3.7/site-packages/synapse/rest/media/v1/media_repository.py", line 573, in _generate_thumbnails
synapse[3521]:     thumbnailer = Thumbnailer(input_path)
synapse[3521]:   File "/usr/lib/python3.7/site-packages/synapse/rest/media/v1/thumbnailer.py", line 43, in __init__
synapse[3521]:     self.image = Image.open(input_path)
synapse[3521]:   File "/usr/lib/python3.7/site-packages/PIL/Image.py", line 2705, in open
synapse[3521]:     % (filename if filename else fp))
synapse[3521]: OSError: cannot identify image file '/var/lib/synapse/media_store/local_content/vi/XO/lhlBSJHGjKpTnqzomjBu'
```

Contents of uploaded file:

```js
function stream() {
    [native code]
}
```

Looks like you're sending the definition of a function called `stream` instead of a field. The strange thing is that sometimes it's working.

### Version information

- **Platform**: Web
- **Browser**: Firefox Nightly
- **OS**: Arch Linux
- **URL**: Self-hosted `riot-web 1.2.1`, `matrix-synapse 0.99.5-1`

**Comment by t3chguy** [comment] 2019-06-11 08:13
Duplicate of #9913

**Closed** 2019-06-11 08:13 UTC
Labels: bug
