### ISSUE TITLE
can't autocomplete in a command line

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#7079] opened 2018-07-24 11:15 UTC
if I type '/me asks tom' and tries to autocomplete 'tom' the autocomplete is still about the /me command, despite having other words in the middle

**Comment by lampholder** [comment] 2018-07-24 11:32
I think this is a dup of https://github.com/vector-im/riot-web/issues/6993 - this looks like it's a regression we introduced on the draft.js-backed composer, which now also (and independently?) exists on the slate.js-backed composer

**Comment by t3chguy** [comment] 2018-07-24 12:52
This should have been fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2074 but due to a double-negative typo it was not, it will be fixed in the upcoming Slate fixes PR as its somewhat related

**Closed** 2018-07-24 12:53 UTC
