### ISSUE TITLE
Hovering over the tray icon should show the rooms with unread messages.

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10737] opened 2019-09-03 10:31 UTC
Most people will have some 'important' rooms, to messages of which quick attention is necessary, and others that can wait.  It also helps pintpoint the source of spurious counters.

**Comment by t3chguy** [comment] 2020-07-16 06:35
https://www.electronjs.org/docs/api/tray#traysettooltiptooltip

**Comment by t3chguy** [comment] 2020-07-17 17:19
Duplicate of https://github.com/vector-im/riot-web/issues/7190

**Closed by t3chguy** 2020-07-17 17:19 UTC
Labels: suggestion, type:electron, type:trayicon
