### ISSUE TITLE
Private rooms information leak via URLs

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-web#6807] opened 2018-05-27 22:07 UTC
I am sorry if this is a duplicate, I did try to look for open issues using all the usual keywords, but without success.

So we have a private room, and in it, we shared a semi-secret document (via upload). Circumstance had it that someone accidentally leaked the URL to the scan to another forum. He immediately noticed, but there was nothing we could do, AFAICT, for knowledge of the URL would allow *anyone* to download the scan. One doesn't even need to be logged in to Riot/Matrix, let alone be a member of the room.

This is bad, and I'd argue that media URLs should essentially default to 403s or 401s, unless credentials are provided *and* those would be enough to let you see the media in Riot.

**Comment by t3chguy** [comment] 2018-05-27 22:17
Duplicate of https://github.com/matrix-org/matrix-doc/issues/701

**Closed by t3chguy** 2018-05-27 22:17 UTC

**Comment by madduck** [comment] 2018-05-27 23:01
Silly me, @t3chguy. Too early in the morning, and too few coffees, as to think this was in any way a UI problem. Sorry about that.
