### ISSUE TITLE
Hidden Device Names by Default

### ISSUE THREAD

**Issue by erik-roberts** [vector-im/riot-web#9365] opened 2019-04-02 21:06 UTC
### Description

I would like to have the option to hide device names. Currently, one can often see full names, types of devices, and software used from rooms. Device names should be be hidden by default imo.

**Comment by turt2live** [comment] 2019-04-02 21:14
Effectively duplicate of https://github.com/vector-im/riot-web/issues/2295

**Closed by turt2live** 2019-04-02 21:14 UTC
