### ISSUE TITLE
flatpak build not long accepting --profile option. 

### ISSUE THREAD

**Issue by veritanuda** [vector-im/riot-web#14659] opened 2020-07-20 19:07 UTC
### Description

Since the name change and the new build of the Matrix client Element/Riot. I can no longer specify different start up profiles. Previously I could use `flatpak run im.riot.Riot --profile <myusername>` but it appears this option is ignored and it loads the last profile only. 

### Steps to reproduce

execute `flatpak run im.riot.Riot --profile <profile>` the profile should be loaded. Instead the default first profle is.

### Version information
````
flatpak info  im.riot.Riot

Element - Create, share, communicate, chat and call securely, and bridge to
other apps

          ID: im.riot.Riot
         Ref: app/im.riot.Riot/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.7.1
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 226.5 MB
     Runtime: org.freedesktop.Platform/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: 8228d8bab5916ab273e99ec317175acf17550059cd3e72def08c68b78fc1cfcb
      Parent: 9ef7506d320f018c258b3cebc57169421a6be8175d875c10ed248355b6e52e63
     Subject: Update element-desktop_1.7.1_amd64.deb (3f514872)
        Date: 2020-07-17 03:27:58 +0000
````

- **Platform**: flatpak desktop

-  **OS**: 
* Debian 10 
* Linux 5.7.0-1-amd64 
* Gnome 3.36.3 
* Flatpak 1.8.1

**Comment by t3chguy** [comment] 2020-07-21 00:54
Duplicate of https://github.com/vector-im/riot-web/issues/14623

**Closed by t3chguy** 2020-07-21 00:54 UTC
Labels: bug
