### ISSUE TITLE
markdown engine

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#8919] opened 2019-02-24 20:05 UTC
I'm not sure this is riot-web issue as riot-android and riot-ios are also affected.

Please add support for markdown strikethrough syntax with two tildes: `~~Scratch this~~`.

**Comment by t3chguy** [comment] 2019-02-24 20:08
Riot Web uses commonmark and has expressed that it will not be making a custom dialect of markdown by adding features and those should be added upstream.

Express your desires at https://talk.commonmark.org/t/strikeout-threw-out-strikethrough-strikes-out-throughout/820

**Comment by 532910** [comment] 2019-02-24 20:26
> Riot Web uses commonmark and has expressed that it will not be making a custom dialect of markdown by adding features and those should be added upstream.

I'm absolutely agree that riot shouldn't make workaround for commonmark.

But may be riot should change commonmark to some other markdown engine? For example gitlab uses https://kramdown.gettalong.org/ that has strikethrough support, but it's on ruby.

**Comment by t3chguy** [comment] 2019-02-24 20:44
Duplicate of https://github.com/vector-im/riot-web/issues/5940

**Closed by t3chguy** 2019-02-24 20:44 UTC

**Comment by 532910** [comment] 2019-02-24 21:26
sorry
