### ISSUE TITLE
Send message overflows draft editor on small screens/windows

### ISSUE THREAD

**Issue by Nostradamos** [vector-im/riot-web#5307] opened 2017-10-16 21:42 UTC
### Description

When resizing the riot window, it's possible that the width of the draft editor width is getting to small to display the "Send unencrypted message" message and it will overflow.

### Steps to reproduce
- Resize width of the window until the text can't get wrapped in the draft editor div

Log: not sent    

https://i.imgur.com/omSNL0Q.png

### Version information
Web: current riot.im/staging (0.12.7)
Desktop: 0.12.6

- **Platform**: web (in-browser) and desktop

For the web app:

- **Browser**: Chrome 61
- **OS**: Arch Linux
- **URL**: riot.im/staging

For the desktop app:

- **OS**: Arch Linux
- **Version**: 0.12.6 

### Possible fix

Adding `overflow-y: auto;` or maybe `overflow-y: hidden;` to ` .DraftEditor-root`. Will do a PR as soon as i find some time.

**Comment by uhoreg** [comment] 2017-10-17 15:07
Duplicate of #4821

**Closed by uhoreg** 2017-10-17 15:07 UTC
