### ISSUE TITLE
The "sidebar blurred avatar background" mod is scary and inconvenient

### ISSUE THREAD

**Issue by Ai-rin** [vector-im/riot-web#14511] opened 2020-07-15 21:10 UTC
The new theme's "sidebar blurred avatar background" feature looks really weird.
Initially it made me even think something wrong with my monitor. 
I didn't understand what's that big grey spot until I checked the sources and found the css.
Moreover, i suspect it's also slows down the client (my main PC is not so new and every bit counts)
If you insist this feature should be there, at least please consider making it optional.
Thank you.
![image](https://user-images.githubusercontent.com/29887769/87595846-de7a4c00-c6f7-11ea-8780-bf1f8c5a1b77.png)

**Comment by t3chguy** [comment] 2020-07-16 01:14
Duplicate of #14493

**Closed** 2020-07-16 01:15 UTC
Labels: bug, needs-design, type:new-room-list, ui/ux

**Comment by dkasak** [comment] 2021-04-23 11:34
I think this is very much also a duplicate of #14665.
