### ISSUE TITLE
Some settings are not available in narrow windows

### ISSUE THREAD

**Issue by ktosiek** [vector-im/riot-web#4783] opened 2017-08-12 18:01 UTC
### Description

When using riot-web in a small window, I could not access some settings. Most notably the `Delete` button for account's devices was not visible.
This has been a problem to at least one user: https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$150255226859345jTIJC:sorunome.de

### Steps to reproduce

- Open Riot in a window narrower than 1250px
- Open settings
- Scroll down to the list of devices

Log: not sent    

### Version information

- **Platform**: probably both, verified on desktop

For the desktop:
- **OS**: Ubuntu
- **Version**: 0.11.4

**Comment by t3chguy** [comment] 2017-08-13 11:18
Duplicate of https://github.com/vector-im/riot-web/issues/2668

**Closed by t3chguy** 2017-08-13 11:18 UTC
