### ISSUE TITLE
There is still no way to view the public keys of your own devices

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13150] opened 2020-04-13 15:32 UTC
If I view my own MemberInfo and expand the device list, the cursor makes it look like i can click on them. But nothing happens if I do, and I have no way of viewing the device's public keys for legacy verif purposes (e.g. people who want to publish their pubkeys out of band as an additional safety measure)

**Comment by ara4n** [comment] 2020-04-13 15:32
I also can't view the pubkeys of verified devices for other people.

**Comment by aaronraimist** [comment] 2020-04-13 16:48
Duplicate of https://github.com/vector-im/riot-web/issues/2735

**Closed by aaronraimist** 2020-04-13 16:48 UTC
