### ISSUE TITLE
Unable to register from desktop app, should be disabled

### ISSUE THREAD

**Issue by Extarys** [vector-im/riot-web#7848] opened 2018-12-13 08:03 UTC
### Description

When a user register an account on the Desktop version of Riot, it says the Robot verification is not yet compatible and the user need to click on a link that open a web page.

The user then need to re-enter it's registration information.

There is no way int he app to go back, you need to close the app and re-open it.

The experience is awful and should be corrected.

### Steps to reproduce

Create an acocunt on the desktop app

Describe how what happens differs from what you expected.

I would expect to
 1) be able to make the captcha in the app (I understand though why this isn't possible), or;
 2) Tell the user registrations are currently not supported in the desktoop version,
or at least
 3) put a button to go back to the login screen
### Version information

- **Platform**: desktop

For the desktop app:
matrix-react-sdk version: <local>
riot-web version: 0.17.8
olm version: 3.0.0
- **OS**: Linux Mint
- **Version**: 0.17.8

**Comment by Extarys** [comment] 2018-12-14 01:36
When I first tried it a couple of days ago, I gave up.

- I tried creating an account on riot-android
- Received some email
- Try clicking on the links to follow the steps
- Didn't work
- Installed the desktop app
- Fill in registration info
- Being told I need to open a browser
- Refill my registration information

It was quite painful - I was very sad and told myself I could never try and switch my friends to Riot. But I decided to make a little video tutorial for them. :D

UX is an important part to attract people now.

Thanks for your reply.

**Comment by turt2live** [comment] 2019-01-28 18:55
I think this is a duplicate of https://github.com/vector-im/riot-web/issues/7617

**Closed by turt2live** 2019-01-28 18:55 UTC
Labels: bug, major, p2, type:electron, type:registration

**Comment by Extarys** [comment] 2019-01-30 14:02
Yes indeed it is similar. But I'm also refering to the android app which makes us input our infos and then ask us to create an account on the desktop... which makes us refill our infos.
