### ISSUE TITLE
Inconsistencies with numbered lists in messages and editing/CIDER

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10807] opened 2019-09-09 15:37 UTC
When editing messages, the numbers are inconsistent:

![CIDER lists](https://user-images.githubusercontent.com/4626865/64545477-a63afd80-d2dd-11e9-8fbf-221deb689efa.gif)

With the edit UI displaying numbered lists all as 1. and the message themselves being 1-7 or 1-4 & 1-3 in the GIF above.

Related issue: https://github.com/vector-im/riot-web/issues/10808

**Comment by bwindels** [comment] 2019-09-09 15:58
Hmm, instead of going for visual parity between a rendered and editing message, I think it makes more sense to aim for markdown that renders back to HTML that is rendered in the same way. Using `1. ` for every numbered list item, or any other number for that matter, is [valid markdown](https://daringfireball.net/projects/markdown/syntax#list).

Or is your issue that the list is split up in two when edited, when it was intended to be 1 list with the middle item having multiple lines? If so, please file as that or rename this bug.

**Comment by nadonomy** [comment] 2019-09-09 16:03
> Hmm, instead of going for visual parity between a rendered and editing message, I think it makes more sense to aim for markdown that renders back to HTML that is rendered in the same way. Using `1. ` for every numbered list item, or any other number for that matter, is [valid markdown](https://daringfireball.net/projects/markdown/syntax#list).

Huh, I didn't know that's how MD numbering works! Every day's a school day.

> Or is your issue that the list is split up in two when edited, when it was intended to be 1 list with the middle item having multiple lines? If so, please file as that or rename this bug.

I can see the academic arguments for going either way, but I think considering we're building real-time messaging we should focus on short lists. So I'd expect linebreaks to indicate new lists, rather than longer bullets.

**Comment by bwindels** [comment] 2019-09-09 16:20
> I can see the academic arguments for going either way, but I think considering we're building real-time messaging we should focus on shorter terser communication than long-form blog posts etc. So I'd expect linebreaks to indicate new lists, rather than longer bullets.

I would suggst we just went with what markdown does here, instead of inventing or own variant.

```
 - foo
   bar
 - baz
```
renders to

 - foo
   bar
- baz

I would suggest to only consider it a bug if the html to markdown conversion produces different markdown than the original one, e.g. if html > md when editing and md > html when saving produce incompatible results.

**Comment by bwindels** [comment] 2019-09-10 08:09
Given the above, can we close this bug @nadonomy ?

**Comment by nadonomy** [comment] 2019-09-10 19:19
> > I can see the academic arguments for going either way, but I think considering we're building real-time messaging we should focus on shorter terser communication than long-form blog posts etc. So I'd expect linebreaks to indicate new lists, rather than longer bullets.
> 
> I would suggst we just went with what markdown does here, instead of inventing our own variant.
> 
> ```
>  - foo
>    bar
>  - baz
> ```
> 
> renders to
> 
> * foo
>   bar
> * baz
> 
> I would suggest to only consider it a bug if the html to markdown conversion produces different markdown than the original one, e.g. if html > md when editing and md > html when saving produce incompatible results.

This sounds reasonable.

Just to chew the fat on this some more— in the GIF above I've composed a message, which has rendered with a numbered list of 1/2/3/4. Then, when editing, it's jarring for it to be displayed again all with 1's, I actually thought I'd hit a bug or the edit composer had somehow 'corrupted' my message.

Should we make that consistent?

**Comment by bwindels** [comment] 2019-09-11 08:01
> Should we make the 'md when editing' part of the UX consistent always?

Not sure what you mean here. What about the MD is not consistent with what when editing or writing a message now?

**Comment by nadonomy** [comment] 2019-09-11 15:50
> Not sure what you mean here. What about the MD is not consistent with what when editing or writing a message now?


![MD](https://user-images.githubusercontent.com/4626865/64712971-f6969480-d470-11e9-9ef8-f3341b901051.gif)

I input a numbered list as:

`
1. a
2. numbered
3. list
`

but then when editing it's changed to:

`
1. a
1. numbered
1. list
`

likewise, I inserted line breaks, which disappear when editing. Both of those things are extremely jarring and cause me to not trust the edit UI (is it going to send with the numbered list incorrectly? is it going to send without line breaks? do I need to insert them again? etc).

So I'm suggesting that once a message is sent, the edit UI should print the message as it was being rendered in the timeline, to avoid confusion and hesitation. Right now, often when I use the edit UI I _don't trust it_ as the UX causes me to pause.

**Comment by tulir** [comment] 2019-11-28 10:10
This was fixed by matrix-org/matrix-react-sdk#3552

**Closed** 2019-11-28 12:15 UTC
Labels: feature:message-editing, suggestion, type:composer
