### ISSUE TITLE
Spell Check for desktop (Windows, Linux, MacOS, etc)

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#12384] opened 2020-02-16 03:30 UTC
Any chance we can get a robust spell check for Riot Desktop Windows, Linux and MacOS? It's something I miss vs my mobile experience.

**Comment by turt2live** [comment] 2020-02-16 04:41
Duplicate of https://github.com/vector-im/riot-web/issues/2661

**Closed by turt2live** 2020-02-16 04:41 UTC
Labels: suggestion
