### ISSUE TITLE
Reactions may get locally duplicated, fixed by page refresh

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#11710] opened 2019-12-23 23:33 UTC
### Description

I reacted to a message in `#riot:matrix.org` and it seemed to work normally. A few hours later I looked at the room and the message appeared to have two reactions, both coming from me.

<img width="455" alt="Screen Shot 2019-12-23 at 5 20 43 PM" src="https://user-images.githubusercontent.com/5855073/71384908-cb602d00-25a9-11ea-8475-c8d447071507.png">

https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$sS5AwL4iwPsEpSjMby3de4e8u9tJYrE5sI1k78zbBQE?via=matrix.org&via=privacytools.io&via=feneas.org

After refreshing the page it went back to correctly just showing the one reaction.

### Version information

- **Platform**: web 

For the web app:

- **Browser**: Safari 13
- **OS**: macOS
- **URL**: riot.im/develop 443d381, react SDK: 8c70eda

Rageshake sent

**Comment by aaronraimist** [comment] 2020-01-11 06:43
I've had a couple other people also say they are getting this. I am also noticing it happening more.

<img width="224" alt="Screen Shot 2020-01-11 at 12 34 26 AM" src="https://user-images.githubusercontent.com/5855073/72200085-81c96c00-340a-11ea-8f99-0337200fd76c.png">
<img width="290" alt="Screen Shot 2020-01-11 at 12 34 22 AM" src="https://user-images.githubusercontent.com/5855073/72200086-81c96c00-340a-11ea-9a73-b21c01de95e1.png">

**Comment by anoadragon453** [comment] 2020-02-12 14:04
Duplicate of https://github.com/vector-im/riot-web/issues/11161

**Closed by anoadragon453** 2020-02-12 14:04 UTC
Labels: bug, feature:reactions
