### ISSUE TITLE
Click and Drag users between favourites/other groups

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#12613] opened 2020-03-05 04:58 UTC
I want to be able to click and drag users between direct messages, favourites, or even have rooms be dragged around between groupings too. Please?

**Comment by turt2live** [comment] 2020-03-05 05:12
Duplicate of https://github.com/vector-im/riot-web/issues/8614

**Closed by turt2live** 2020-03-05 05:12 UTC
Labels: suggestion

**Comment by BloodyIron** [comment] 2020-03-05 05:13
Oops sorry.
