### ISSUE TITLE
Emoji picker from reactions should be generally available in the editor

### ISSUE THREAD

**Issue by jacotec** [vector-im/riot-web#11797] opened 2020-01-08 08:32 UTC
Meanwhile Riot-Web has a really good emoji picker, which can be used to select an emoji for reactions.

I don't see any reason why this, already implemented emoji picker is not available generally in the editor. Finding and using emojis when writing posts is still a complete mess ... and a great picker is already in place. Why is this not available also when writing normal posts?

**Comment by t3chguy** [comment] 2020-01-08 12:43
Duplicate of https://github.com/vector-im/riot-web/issues/9484

**Closed by t3chguy** 2020-01-08 12:43 UTC
Labels: suggestion
