### ISSUE TITLE
Tray icon vanishes after each update

### ISSUE THREAD

**Issue by Noisefever** [vector-im/riot-web#9236] opened 2019-03-21 13:39 UTC
### Description

On Windows 10 you can configure each tray icon to be hidden or not (in the submenu). Unfortunately you can only configure "show all" or "hide automatically except [App]". And because the Riot install folder is named with the version number, after each update I have to config that again and again to see the tray icon. With this update rate this is really nerv wrecking!
And without seeing the tray icon I can't determine if someone has written a message. 

### Version information

1.05

- **Platform**: Windows 10

**Comment by t3chguy** [comment] 2019-03-21 14:22
Duplicate of https://github.com/vector-im/riot-web/issues/4601

**Closed by t3chguy** 2019-03-21 14:22 UTC
