### ISSUE TITLE
Rooms in Favorites change order.

### ISSUE THREAD

**Issue by dali99** [vector-im/riot-web#12853] opened 2020-03-24 20:23 UTC
### Description

Rooms in the favorites tag are changing order

### Steps to reproduce
The bug seems to be triggered by switching between the rooms, but one person has reported that they thinks it's sometimes triggered randomly as well

According to Riot Web on matrix this should never happen

### Version information

- **Browser**: Firefox  73.0.1
- **OS**: NixOS
- **URL**: riot.dodsorf.as

- **Browser**: Firefox 74.0
- **OS**: Windows 7
- **URL**: riot.dodsorf.as

**Comment by turt2live** [comment] 2020-03-24 20:27
This was a historical bug in the first introduction of the importance algorithm, but should have been resolved ages ago. Its reappearance is very worrying, so if people encounter this please submit logs so we have a chance at identifying what went wrong.

**Comment by t3chguy** [comment] 2020-04-13 09:38
Duplicate of https://github.com/vector-im/riot-web/issues/12571

**Closed by t3chguy** 2020-04-13 09:38 UTC
Labels: bug, regression, type:roomlist
