### ISSUE TITLE
three dot room menu gets cut off if no space is left

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#4720] opened 2017-08-01 07:41 UTC
### Description

The room menu doesn't leave the Riot window and just gets cut off.

![image](https://user-images.githubusercontent.com/1029578/28814336-70b0880e-769d-11e7-8d4f-bb74e706e05c.png)

### Steps to reproduce

- Join a room
- resize the window so the room takes all the space vertically
- open the menu (three dots) of a room on the lower end of the room list
- menu is missing entries, which get cut off

I'd expect the menu to move up to compensate this.

Log: not sent    

### Version information

- **Platform**: desktop

- **OS**: Windows 10
- **Version**: 0.11.4

**Comment by t3chguy** [comment] 2017-08-01 09:56
Duplicate of #3792

**Closed by t3chguy** 2017-08-01 09:56 UTC
