### ISSUE TITLE
Support swipe through image's 

### ISSUE THREAD

**Issue by olymk2** [vector-im/riot-web#14765] opened 2020-07-25 19:52 UTC
**Is your suggestion related to a problem? Please describe.**
On mobile you can swipe through your images this does not appear to work on the web version.

**Describe the solution you'd like**
2 arrow icons to navigate through room images, hook into the keyboard arrow keys as shortcuts and perhaps swipe on touch devices if possible.

**Comment by t3chguy** [comment] 2020-07-25 19:54
Duplicate of https://github.com/vector-im/riot-web/issues/337

**Closed by t3chguy** 2020-07-25 19:54 UTC
Labels: suggestion
