### ISSUE TITLE
Login layout doesn't fit some languages (French in particular)

### ISSUE THREAD

**Issue by AdrienMatricon** [vector-im/riot-web#6395] opened 2018-03-27 07:21 UTC
### Description

The French for "Matrix ID" is "identifiant Matrix", which is much longer. The layout seems to be unable to fit such a long string of characters (the problem would probably also happen in other languages in which the string is long)

### Steps to reproduce

- Go to https://riot.im/app/#/login
- Select French ("Français") as the language
- This happens:

![screenshot](https://user-images.githubusercontent.com/14818215/37952416-effb4f32-319f-11e8-88bc-38fb98c166ab.png)

### Version information

- **Platform**: web
- **Browser**: Firefox 59.0.1 (64-bit)
- **OS**: both on Ubuntu and MacOS
- **URL**: https://riot.im/app/#/login

**Comment by turt2live** [comment] 2018-03-27 15:46
Effectively a duplicate of https://github.com/vector-im/riot-web/issues/5767

**Comment by lampholder** [comment] 2018-03-27 16:24
I'm happy to combine these two issues (since you're right, they're effectively the same) but I'll bump the priority of #5767 (because there are more native French speakers than there are people using long-domained homeservers).

**Closed by lampholder** 2018-03-27 16:24 UTC
