### ISSUE TITLE
Wrong count of room members

### ISSUE THREAD

**Issue by alex-rk86** [vector-im/riot-web#13193] opened 2020-04-16 05:48 UTC
Hi,

I have self-hosted matrix server, no guests or self-registration allowed, no federation.
My total number of registered users is around 30, no guests allowed. I can confirm the correct number of users by querying Matrix users table.

When I select on Riot Web / Explore rooms, the rooms the member count is too high (> 90). When I list members - all looks good, only people I expect. The similar behavior is from Android Riot.IM client.

It is not specific to platform or browser.

OS: Ubuntu server 18.04
Matrix-synapse: 0.34.0.1
Riot Web version: 1.5.15

Thank you,
Alex

**Comment by t3chguy** [comment] 2020-04-16 08:56
Duplicate of https://github.com/vector-im/riot-web/issues/11982 (its actually a Synapse issue)

**Closed by t3chguy** 2020-04-16 08:56 UTC
Labels: bug
