### ISSUE TITLE
User pill for mention of someone not in the room ignores display name in link

### ISSUE THREAD

**Issue by ilmari** [vector-im/riot-web#14497] opened 2020-07-15 18:11 UTC
### Description

When showing the pill for a user in a room they're not in, the pill first shows the MXID, then switches to the display name, even if the display name is empty.

For example [this mention of @oftc-irc:matrix.org](https://matrix.to/#/!BAXLHOFjvDKUeLafmO:matrix.org/$Aqx+U/Sz3VQt6kZKYg+gRkVrcJcoHGZJV7Hr7FJqMOs?via=matrix.org&via=feneas.org&via=privacytools.io):

![no-display-name-pill](https://user-images.githubusercontent.com/72175/87577416-c93af880-c6ca-11ea-8ad3-e9d357b46cf8.png)

Compare [this mention in another room the bot is in](https://matrix.to/#/!ghLusDPaikIiBVbiyH:matrix.org/$AvU3GTd39iFVguSRoOiXrMaou0t1KdAyCtyzf8fnYAg?via=matrix.org&via=ilmari.org&via=t2bot.io):

![Screenshot from 2020-07-15 18-49-27](https://user-images.githubusercontent.com/72175/87578298-21262f00-c6cc-11ea-897f-c3a0537287d6.png)

The the mention in the `formatted_body` is identical: `<a href="https://matrix.to/#/@oftc-irc:matrix.org">@oftc-irc:matrix.org</a>`.

### Steps to reproduce

- start writing a mention of a user in a room they're in so it gets pilled
- copy the pill from the composer
- paste the pill into a room the user is not in and send the message
- observe the MXID in the pill be replaced with the display name (even if empty)
- switch to another room and back
- observe the MXID appear, and then be replaced again.

I'd expect the pill to either start out with the display name from the `<a>` contents,
or at least keep showing the the MXID if the display name comes back empty.

Logs being sent: no

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Firefox 68.10.0esr (64-bit)
- **OS**: Debian 10 (Buster)
- **URL**: https://app.element.io/
- **Element version**: 1.7.0

**Comment by t3chguy** [comment] 2020-07-16 01:48
Duplicate of https://github.com/vector-im/riot-web/issues/7063

**Closed by t3chguy** 2020-07-16 01:48 UTC
Labels: bug
