### ISSUE TITLE
Open widget in new window leaves Jitsi running in Riot

### ISSUE THREAD

**Issue by pv** [vector-im/riot-web#13025] opened 2020-04-03 16:36 UTC
# Description

The "Open widget in new window" button on active Jitsi conference leaves the conference running inside Riot.

This confuses people to join the conference twice, which can result to echo and also audio looping (i.e. loud screeching noise). I had a conference in Riot with some nontechnical users and *everyone* ended up doing this (and complained about it), so I think this is a mainstream issue in the video conferencing feature.

This is probably compounded by #12916 #8851, as there's currently no other way for nontechnical users to increase the size of the widget or fullscreen it (you can in principle press `s`, but you need to know that beforehand, and the input focus has to be in the in jitsi widget and not in the chat input field).

### Steps to reproduce

1. Start Jitsi videoconference from its widget on a channel in Riot, by clicking "Join conference"
2. Click on the "Open widget in new window" button on the upper right corner of the widget.
3. Click "Join conference" on the newly opened browser window.
4. Now you are twice in the conference
5. Sound artifacts of varying badness (echo and/or loud noise from amplification loop)

### Version information

- **Platform**: web (latest Chrome, Ubuntu and Windows), and also on desktop (1.15.15)

**Comment by t3chguy** [comment] 2020-04-03 16:43
Duplicate of #12896

**Closed** 2020-04-03 16:44 UTC
Labels: bug

**Comment by pv** [comment] 2020-04-03 16:45
Sorry, missed that --- only searched for jitsi, but not for the tag.
