### ISSUE TITLE
Searching for users sometimes appears not to work properly.

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#6599] opened 2018-04-25 09:31 UTC
I want to start a chat with benoit, we're both in the team internal room, but when clicking Start chat and searching for 'benoit' he doesn't appear in the results

**Comment by ara4n** [comment] 2018-05-02 23:37
relatedly, icons seem to be missing entirely from search results too. plus I also couldn't find stevio earlier.

**Comment by ara4n** [comment] 2018-05-02 23:38
this is precisely the sort of regression that i think we should be prioritising fixes for rather than letting it overflow into future sprints...

**Comment by t3chguy** [comment] 2018-06-16 19:52
It seems to work for me so could you verify whether it still occurs for you @AmandineLP 
![image](https://user-images.githubusercontent.com/2403652/41501996-39388bb4-71a7-11e8-8a04-34c6c1497b40.png)

**Comment by dbkr** [comment] 2018-07-17 09:03
I also can't repro this (ie. he appears for me)

**Comment by lampholder** [comment] 2018-09-21 16:36
I think we could make a significant improvements to the UX if:
- any valid mxid that the homeserver can't or won't confirm is a real account (for whatever reason) should appear in grey with a grey default avatar (maybe with a question mark instead of the initial avatar)
- the search dialogue could report the status of `search_all_users` and explain the consequences

Even better if valid mxids that _aren't_ real users could appear in red and block the invite's sending (but I reckon that's going to be a lot more fiddly to impl).

**Comment by lampholder** [comment] 2018-09-21 16:57
Right, I'm going to break this issue in two. This issue will represent 'inviting is broken'. I'll make a separate issue for 'invite UX is confusing'.

Some useful conversation from https://github.com/vector-im/riot-web/issues/6970 which I've killed off for simplicity:
![screenshot 2018-09-21 at 17 56 17](https://user-images.githubusercontent.com/1922197/45894949-cf5e3780-bdc7-11e8-8628-426641edcdca.png)

**Comment by ara4n** [comment] 2018-09-22 12:11
> First up - what is the behaviour meant to be? Forgetting for a moment about the UX - who should come back in search results when you search?

If your server has `search_all_users: false` (the default), search results should return:
 * Users who you share a room with.
 * Users who are in public rooms.
Else:
 * All users known to your server.

The directory is maintained only by your local server, and does not interact with the directories maintained by other servers (which are not exposed over federation).

There seem to be two separate bugs here:
 * I can't find some users at all on the matrix.org directory (e.g. `@nadonomy:matrix.org` and benoit here)
 * Users often appear in the invite results with a missing profile (e.g. `@bwindels:matrix.org` in #6970).

My theory is that synapse is failing to keep the user directory maintained correctly... *and* Riot is failing to sometimes provide the right profile info (given this is certainly an intermittent bug).

**Comment by turt2live** [comment] 2018-10-04 20:19
Author's note: This comment is just a research notes dump to hopefully help track down possible problems here. 

----

> Riot is failing to sometimes provide the right profile info

This sounds like a symptom of synapse not knowing entirely what to return, given I would expect Riot to just use the profile info returned from the search results. Unless Riot does something weird, in which case it probably shouldn't. Profiles being broken sounds a bit like https://github.com/matrix-org/synapse/issues/3310

Because this issue is most prominent on matrix.org (which might be a symptom of the user count) and matrix.org uses workers, I'm tempted to blame https://github.com/matrix-org/synapse/issues/3714 to a degree. https://github.com/matrix-org/synapse/issues/3631 might also be related, although that doesn't appear to be the case in this issue.

The directory being unstable appears to be hinted at by https://github.com/matrix-org/synapse/issues/2306

**Comment by turt2live** [comment] 2018-10-04 20:59
also for information gathering purposes: matrix.org uses `update_user_directory: false` (because worker) and `search_all_users: false`, implying this might be a race condition (or similar) in synapse, as described by https://github.com/matrix-org/synapse/issues/3714 - although shouldn't the race condition be fixed by `update_user_directory: false`? (to be continued...)

**Comment by turt2live** [comment] 2018-10-04 21:44
more info: 
> meanwhile, i suspect riot might have a codepath to insert local members in to the user lookup rather than just use the directory
> which might explain why it sometimes magically starts working

**Comment by turt2live** [comment] 2018-10-15 19:18
I can't seem to replicate the issue locally, but it is easily reproducible on matrix.org:

1. Create 2 accounts and log in to both
2. Create a new room with Account 1
3. Try to invite Account 2 by name only - it should fail to find a result, requiring the full user ID
4. Finish inviting the user and accept the invite on Account 2
5. Create another new room with Account 1
6. Try the same process from step 3, except this time it should give some result - this fails on matrix.org but not with a self-hosted server. I even tried with workers and wasn't able to reproduce the issue.

I suspect this a result of the load matrix.org is under, and I'm not about to spin up a test environment to match the same scale to see if it fails in the same way.

**Comment by richvdh** [comment] 2019-07-08 12:23
The user directory was rewritten by https://github.com/matrix-org/synapse/issues/4537 and friends, and I wasn't able to reproduce this on matrix.org, so I think it's fixed.

**Closed by richvdh** 2019-07-08 12:23 UTC
Labels: bug, critical, p1, regression, synapse

**Comment by CybotTM** [comment] 2019-10-04 10:34
Still have similar problems with web and desktop client - not with new RiotX client.
Seems client is messing with server results - there are just results in the result list missing, which should be there - and correctly appear in RiotX client search results.

**Comment by t3chguy** [comment] 2019-10-04 10:36
Please make a new issue with some usable information so this can be investigated, results from both, can be anonymized, ideally API responses from the network tab etc
