### ISSUE TITLE
Show these rooms to non-members on the community page and room list? option when adding room to group is not honoured.

### ISSUE THREAD

**Issue by 5chdn** [vector-im/riot-web#5742] opened 2017-11-30 11:14 UTC
### Description

Communities list private, invite-only channels, even though this feature was not enabled: _Show these rooms to non-members on the community page and room list?_

### Steps to reproduce

- Create a community
- Add a channel to the community
- Uncheck "Show these rooms ..."
- Visit the community as guest
- It shows private rooms

Describe how what happens differs from what you expected: Communities list private, invite-only channels, even though this feature was not enabled.

Log: sent.

![screenshot at 2017-11-30 12-10-20](https://user-images.githubusercontent.com/15729797/33428026-a222549c-d5c7-11e7-8711-15effaddc016.png)

See: https://riot.im/app/#/group/+parity:matrix.parity.io

### Version information

- **Platform**: web in-browser and web in-rambox.

For the web app:

- **Browser**: Chrome 62, and Firefox 57?
- **OS**: Arch Linux
- **URL**: riot.im/app

**Comment by lampholder** [comment] 2017-12-01 17:51
I think I understand this issue now. The problem is that the setting exposed on adding a room to a group:

![image](https://user-images.githubusercontent.com/1922197/33495790-ade653a2-d6bf-11e7-86f1-2a448be3b8f9.png)

Is not actually honoured:

![image](https://user-images.githubusercontent.com/1922197/33495841-e3e20c58-d6bf-11e7-8abe-c866e07563b0.png)

I think the functionality of hiding a room from public listing still works, but (until this bug is fixed) you can only enable that functionality by:
- going to the community mgmt page as a community admin
- clicking on the non-obvious (#) icon ![image](https://user-images.githubusercontent.com/1922197/33495879-0a7e4ed0-d6c0-11e7-9979-e33a8c6536f7.png)
- clicking on the room you want to hide from non-members
- toggling the VISIBILITY IN ROOM LIST setting

I'll update the issue title accordingly.

**Comment by lukebarnard1** [comment] 2017-12-01 17:54
This is a bug in the js-sdk, where `addRoomToGroup` sends a `{ "visibillity": ... }` instead of `{ "m.visibility": ... }`

**Comment by 5chdn** [comment] 2017-12-04 10:10
thanks for the workaround :+1:

**Comment by lukebarnard1** [comment] 2017-12-04 12:40
Fixed as of https://github.com/vector-im/riot-web/releases/tag/v0.13.3

**Closed by lukebarnard1** 2017-12-04 12:40 UTC
Labels: bug, major, p1, type:communities

**Comment by 5chdn** [comment] 2017-12-06 10:40
thanks. confirming this works now :)
