### ISSUE TITLE
Impossible to edit long messages without newlines, the editor scroll always jumps to the bottom

### ISSUE THREAD

**Issue by rkfg** [vector-im/riot-web#6825] opened 2018-05-30 06:51 UTC
### Description

I recorded a video to better illustrate this:
[bug-2018-05-30_09.43.04.zip](https://github.com/vector-im/riot-web/files/2052655/bug-2018-05-30_09.43.04.zip)

### Steps to reproduce

- copy&paste or write a long text without a single newline so that a vertical scrollbar appears
- try to edit something in the beginning
- the scroll position always resets to the bottom
- adding a newline in the end allows for normal editing

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 67.0.3396.18 (behaves different in Firefox, the caret still stays on top but at least it's visible)
- **OS**: Debian testing amd64
- **URL**: private server, 0.15.4

**Comment by lampholder** [comment] 2018-05-30 14:40
Confirmed, and enraging.

I expect this will be fixed by the inbound Slate.js rewrite of the composer.

**Comment by turt2live** [comment] 2018-10-31 22:40
@rkfg I can't reproduce this anymore - are you still seeing it on recent versions of Riot (0.17 or higher)?

**Comment by t3chguy** [comment] 2020-03-24 20:46
Closing as no response to unable to repro

**Closed by t3chguy** 2020-03-24 20:46 UTC
Labels: bug, major, p2, question, type:old-composer

**Comment by rkfg** [comment] 2020-03-24 20:58
Sorry, didn't notice it 1.5 years ago (lol). Indeed, now it works as expected.
