### ISSUE TITLE
Show multiple uploaded pictures in a collection

### ISSUE THREAD

**Issue by jsonjuri** [vector-im/riot-web#12498] opened 2020-02-25 07:21 UTC
When you select multiple pictures and upload them they are added in multiple rows in huge size. It would be a great improvement to show them in a collection, like in WhatsApp.

![image](https://user-images.githubusercontent.com/11409905/75223820-3fa19180-57e2-11ea-969a-679027f873fc.png)

The screenshot below is from a phone but it can be created similar on the web.
![image](https://user-images.githubusercontent.com/11409905/75223521-95296e80-57e1-11ea-93b9-4853ad4ac2af.png)

**Comment by t3chguy** [comment] 2020-02-25 10:47
Duplicate of https://github.com/vector-im/riot-web/issues/5872

**Closed by t3chguy** 2020-02-25 10:47 UTC
Labels: suggestion
