### ISSUE TITLE
should not use media key

### ISSUE THREAD

**Issue by magiclu** [vector-im/riot-web#13456] opened 2020-04-30 12:33 UTC
![image](https://user-images.githubusercontent.com/3338197/80710485-68ffd600-8b21-11ea-8080-7918662acaac.png)
Riot version 1.5.15 
windows 10

### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by t3chguy** [comment] 2020-04-30 12:45
Do not ignore the issue template.

Looks like a duplicate of https://github.com/vector-im/riot-web/issues/11614

**Closed by t3chguy** 2020-04-30 12:45 UTC
Labels: bug, ui/ux
