### ISSUE TITLE
report uisis to piwik

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6262] opened 2018-02-27 14:11 UTC

**Comment by Ekleog** [comment] 2018-05-28 11:14
I think this is a duplicate of #6390? (well, technically #6390 would be a duplicate of this one, but it looks like it's more active and is the one referenced in the tracking issue for E2E, so…)

**Comment by t3chguy** [comment] 2018-05-28 12:03
Closing in favour of #6390

**Closed by t3chguy** 2018-05-28 12:03 UTC
Labels: feature, p1, type:e2e
