### ISSUE TITLE
Make images appear bigger in lightbox

### ISSUE THREAD

**Issue by wuhlheide** [vector-im/riot-web#11885] opened 2020-01-16 12:48 UTC
The padding in the lightbox is just too big. Uploaded images should appear bigger in the Lightbox. Maybe we can place the upload information and the download button under the image.

![lightbox](https://user-images.githubusercontent.com/53553858/72526507-dafc2a00-3866-11ea-8fd9-215c376d15be.JPG)

**Comment by t3chguy** [comment] 2020-01-16 12:54
Duplicate of https://github.com/vector-im/riot-web/issues/3638

**Closed by t3chguy** 2020-01-16 12:54 UTC
