### ISSUE TITLE
Riot exploded in a cloud of NPEs whilst trying to pillify a rich reply?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6115] opened 2018-02-09 21:49 UTC
![screen shot 2018-02-09 at 21 48 10](https://user-images.githubusercontent.com/1294269/36051708-ff442030-0de2-11e8-8191-62f8aaa74b50.png)

Had to refresh to recover the app.

**Comment by turt2live** [comment] 2018-02-09 21:50
This is a duplicate of https://github.com/vector-im/riot-web/issues/6059 which either directly or indirectly causes https://github.com/vector-im/riot-web/issues/6089

**Closed** 2018-02-09 21:55 UTC

**Comment by ara4n** [comment] 2018-02-09 21:59
yeah, agreed it all seems to be the same thing.
