### ISSUE TITLE
chat with riot-bot button on welcome-page should reuse 1:1s

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4273] opened 2017-06-11 21:52 UTC
i just clicked it and it started a whole new chat rather than re-use my existing one

**Comment by turt2live** [comment] 2017-06-12 00:30
I couldn't reproduce this:
![image](https://user-images.githubusercontent.com/1190097/27015760-12bcd892-4ed4-11e7-8468-18ce8fefa9e4.png)

**Comment by turt2live** [comment] 2019-02-15 01:49
Closing in favour of https://github.com/vector-im/riot-web/issues/8133

**Closed by turt2live** 2019-02-15 01:49 UTC
Labels: bug, p2, riotbot
