### ISSUE TITLE
Single letter usernames and display names are overly notified.

### ISSUE THREAD

**Issue by Torwegia** [vector-im/riot-web#14510] opened 2020-07-15 21:06 UTC
### Description

With a username like t messages like "I can't do that Dave" will result in a mention notification. 

### Steps to reproduce

- Create an account with the user name t
- Be in a chat room where someone uses a contraction like can't, won't, or something similar. 

Logs being sent: yes/no

### Version information

From my client

Versions
Element version: v1.7.0
olm version: 3.1.3

- **Platform**: web (in-browser) or desktop?

This occurs both on the web and in the riot android application. For the webclients I tried browser and os do not seem to change the behavior (OS/Browsers used: Firefox on macOS, Firefox on windows and Firefox on Arch Linux.

**Comment by aaronraimist** [comment] 2020-07-15 23:59
Duplicate of https://github.com/vector-im/riot-web/issues/9302

**Closed by aaronraimist** 2020-07-15 23:59 UTC
Labels: bug
