### ISSUE TITLE
Self-hosted Dimensions integration manager does not work on element-desktop

### ISSUE THREAD

**Issue by ctwelve** [vector-im/riot-web#14606] opened 2020-07-18 03:09 UTC
First-time reporting to the project,  and I'm virtually certain this problem is limited to the desktop app. Issues are locked over there, so this seemed the best place.

### Description

I have a self-hosted deployment of https://github.com/spantaleev/matrix-docker-ansible-deploy which shows an odd behavior. If I log into the web client, the Dimension integration manager shows up fine. If I use a mobile client, such as Element for iOS, I still get Dimension when logged in. However, when I use the desktop client on any platform, it defaults to the Scalar integration manager rather than our self-hosted Dimension.

We have verified the `.well-known` files are configured correctly, and we have also verified via the develop/debug menu in Riot/Element chat (a few weeks ago, anyway) that the desktop client was in fact fetching the correct server...just not using it.

This is baffling and worrisome, because among other things it means our Jitsi calls are not properly integrated.

### Steps to reproduce

- access our homeserver using the Element desktop client
- issue does not apply to web client, either our own or elsewhere in the Matrix-verse
- issue also does not effect mobile Element client on iOS

Logs being sent: yes/no

### Version information

- **Platform**: desktop?
- **OS**: Windows, macOS
- **Version**: 1.7.1, though this issue has been present for a while.

**Comment by turt2live** [comment] 2020-07-18 04:06
Duplicate of https://github.com/vector-im/riot-web/issues/14315

**Closed by turt2live** 2020-07-18 04:06 UTC
Labels: bug
