### ISSUE TITLE
e2e key backup passphrase can end up in a state where it gives you no feedback as to what is wrong

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7860] opened 2018-12-13 19:33 UTC
![image](https://user-images.githubusercontent.com/1190097/49962670-0c236180-fed3-11e8-946e-a65479613d16.png)

Passphrase tested: [HorseBattery1](https://xkcd.com/936/)

**Comment by jryans** [comment] 2019-01-07 20:31
This seems to be an artifact of how the `zxcvbn` password checker works... If your password is [pretty good but not great](https://github.com/dropbox/zxcvbn#usage), it appears to return a "score" of 3 out of 4 but without specific suggestions to improve.

Related: https://github.com/dropbox/zxcvbn/issues/231

**Comment by dbkr** [comment] 2019-01-17 15:53
This is a prioritised bug but I don't think we have a clear way to move forward on it - our options are:
 * Work around it by filling in a placeholder, "Keep going..." or something
 * Fix the bug upstream (nontrivial)

**Comment by dbkr** [comment] 2019-01-17 18:15
A little further probing reveals the linked bug isn't quite our problem (it's about user inputs and HorseBattery1 isn't in our user inputs). The problem is actually that zxcvbn is hard coded to give no feedback if the score is more than 2: https://github.com/dropbox/zxcvbn/blob/master/src/feedback.coffee#L16

This is presumably because dropbox happened to only require strength 3 passwords and therefore hardcoded it into their library because why not. Gven the activity levels, I wouldn't hold out a great deal of hope of any PRs being merged upstream, least of all one that changes a deliberate-looking decision, so I'm revising our options to:

 * Work around it by filling in a placeholder, "Keep going..." or something
 * Fork zxcvbn and remove the hardcoded check

**Comment by lampholder** [comment] 2019-01-21 18:31
I'd be happy with 'Keep going...' for now (or some other encouraging phrase) rather than forking zxcvbn just yet.

**Comment by jryans** [comment] 2019-01-30 15:37
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2471.

**Closed by jryans** 2019-01-30 15:37 UTC
Labels: bug, defect, minor, p3, type:e2e
