### ISSUE TITLE
Custom Riot Themes

### ISSUE THREAD

**Issue by jph168** [vector-im/riot-web#9730] opened 2019-05-15 10:18 UTC
**Describe the solution you'd like**
I was thinking of Being able to load custom css.themes or something that could allow, I know it may be a lot to ask for 
-custom text colors 
-Set client background and/or sections to custom pictures/colors
-Insert Your Own through the Clients Folders

**Additional context**

![57752289-7d8f5800-769d-11e9-849b-9ea0daaade30](https://user-images.githubusercontent.com/31376624/57768481-91988100-76c0-11e9-9487-ebb22a8b4007.png)
![Custom](https://user-images.githubusercontent.com/31376624/57769837-c78b3480-76c3-11e9-94d9-712aca4f6439.png)
![Screenshot_2019-05-15_03-48-15](https://user-images.githubusercontent.com/31376624/57770168-8cd5cc00-76c4-11e9-9cda-1c23dabf57cd.png)

**Comment by aaronraimist** [comment] 2019-05-15 19:45
Thanks but there are already a few issues for this

Duplicate of #4482, #5844, #7316

**Closed** 2019-05-15 19:50 UTC
Labels: suggestion
