### ISSUE TITLE
The repository '.../debian cosmic Release' does not have a Release file.

### ISSUE THREAD

**Issue by tejasvi** [vector-im/riot-web#9097] opened 2019-03-10 12:31 UTC
```
tejasvi@surface:~$ sudo apt update
Ign:1 https://riot.im/packages/debian cosmic InRelease
Hit:2 http://la-mirrors.evowise.com/ubuntu cosmic InRelease
Hit:3 http://archive.canonical.com/ubuntu cosmic InRelease                     
Get:4 http://la-mirrors.evowise.com/ubuntu cosmic-updates InRelease [88.7 kB]  
Err:5 https://riot.im/packages/debian cosmic Release                           
  Could not handshake: An unexpected TLS packet was received. [IP: 202.141.80.19 3128]
Get:6 http://la-mirrors.evowise.com/ubuntu cosmic-backports InRelease [74.6 kB]
Get:7 http://la-mirrors.evowise.com/ubuntu cosmic-security InRelease [88.7 kB]
Reading package lists... Done                             
E: The repository 'https://riot.im/packages/debian cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Ubuntu 18.10

**Comment by tejasvi** [comment] 2019-03-10 12:35
#8095

**Comment by jryans** [comment] 2019-03-11 10:00
Yes, this appears to be a duplicate of #8095, so let's move the conversation there.

**Closed by jryans** 2019-03-11 10:00 UTC
