### ISSUE TITLE
Etherpad addon crashes in Chrome 

### ISSUE THREAD

**Issue by samsaidi** [vector-im/riot-web#12996] opened 2020-04-02 06:02 UTC
Description

I was trying to load an etherpad content in a room I was just invited at (by myself from another acount), i get this error message :

_An error occurred
The error was reported with the following id: 'eOyx6FzsI91n1TtAJwhr'

Please press and hold Ctrl and press F5 to reload this page, if the problem persists please send this error message to your webmaster:
'ErrorId: eOyx6FzsI91n1TtAJwhr
URL: https://scalar.vector.im/etherpad/p/!RiovHUjJSxIiUTsRJo_matrix.org_Pad_FELiCiTE?showControls=true&showChat=false&chatAndUsers=false&alwaysShowChat=false&showLineNumbers=true&useMonospaceFont=false&userName=%24matrix_user_id
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
Uncaught TypeError: Cannot read property 'setStateIdle' of null in https://scalar.vector.im/etherpad/javascripts/lib/ep_etherpad-lite/static/js/pad.js?callback=require.define at line 3'_

### Steps to reproduce

- @pseudoA:matrix.org (which is myself from another account and from Firefox) invited me in 1) a room and 2) to her community 
- @pseudoB:matrix.org (me from Chrome) accepted both invitation (1 and 2)
- @pseudoB:matrix.org went in the room I was invited at
- @pseudoB:matrix.org tried to load the etherpad @pseudoA:matrix.org had just created
- @pseudoB:matrix.org loaded, again and again : I always get the same error message : 

I just hoped to see the etherpad content to modify it from Chrome and my @pseudoB:matrix.org account, and see modification on the @pseudoA:matrix.org account on firefox (testing for future users).

Bug Report Send ?
Yes, just about to

### Version information

- **Platform**: web in-browser

For the web app:

- **Browser**: Chrome,
- **OS**: macOS,
- **URL**: https://riot.im/app

**Comment by turt2live** [comment] 2020-04-02 16:42
Duplicate of https://github.com/vector-im/riot-web/issues/12900

**Closed by turt2live** 2020-04-02 16:42 UTC
