### ISSUE TITLE
message stuck "undelivered" at bottom of chat window, without delivery failure notification

### ISSUE THREAD

**Issue by aral-matrix** [vector-im/riot-web#13512] opened 2020-05-05 17:51 UTC
### Description

Since upgrading to riot 1.6.0, some message deliveries are not correctly acknowledged as delivered, but also do not time out. Other users can see them, and a restart of riot-desktop loads them correctly in the room history. Until the restart, they stay at the bottom of the chat window.

### Steps to reproduce

- send a message in any room
- bug seems common, but can not be reproduced reliably.

### Describe how what happens differs from what you expected.

Expected behavior: Riot should either get a delivery / reception acknowledgement from the home-server, and display the message as part of the chat history - or report a timeout & offer the option to delete / re-send.

I suspect this is showing up at the moment due to heavy load on the matrix homeserver.

Logs being sent: yes/no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Debian
- **Version**: 1.6.0 
![delivery-bug1](https://user-images.githubusercontent.com/25549366/81098554-d0df6380-8f09-11ea-951b-490444abd9a0.png)
![delivery-bug2](https://user-images.githubusercontent.com/25549366/81098563-d341bd80-8f09-11ea-960e-00eda4b7a1d1.png)

**Comment by ara4n** [comment] 2020-05-05 18:14
this is due to a server bug on matrix.org exposed by the huge load explosion we had due to enabling e2ee. closing as dup of https://github.com/matrix-org/synapse/issues/7409 - thanks for filing.

**Closed by ara4n** 2020-05-05 18:14 UTC
Labels: bug

**Comment by aral-matrix** [comment] 2020-05-05 23:59
I suspected as much - but I still think there's a "bug" in riot for keeping those messages in "limbo" instead of reporting a delivery failure.. in my humble opinion, low priority, but should be kept on the to-do list...

**Comment by t3chguy** [comment] 2020-05-06 08:06
@aral-matrix well no the issue is the server says successfully accepted the sent event and gives us back an event id but then the event never comes back down sync as it is meant to so we don't know exactly where it fits within the timeline order.

**Comment by aral-matrix** [comment] 2020-05-06 09:31
Okay, that makes sense.. in that case there's no ideal solution for the messenger... Closed it is, then... :)

**Comment by Shaping** [comment] 2022-01-10 13:51
I have to problem still.  I have one message stuck from several months ago.  I have second stuck from a few weeks ago.  My business partner has one stuck message in the room we share.  The message that is stuck for him is not the same one that is stuck for me.

My Android Element client shows one stuck message.  My Windows desktop Element client shows two stuck messages.   The one stuck message on Android is neither of the stuck messages on the desktop.  

This is one of our main complaints.  I'm trying to hold on.  He wants to return to Telegram.  We like the encryption of Element, but the ergonomics are mediocre to poor.  He's not a fan.  (The other showstopper for us is the lack of correct/timely notifications.  This is fairly simple to do.  If the devs here have any doubt about how to do this correctly, do what Tg does; it works.  We've seen enough falsely positive notifications from Element to screw up three time-sensitive financial transactions.  This is point at which user will trade back the improved secure for less security in favor of reliable and time communication that has been acked and does not need to be second guessed about whether it has really been acked.  In such cases the improved encryption is not as valuable.)
