### ISSUE TITLE
State is incomplete on joining a room with LL

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7303] opened 2018-09-08 20:07 UTC
Split out from https://github.com/vector-im/riot-web/issues/7211#issuecomment-416982109:

@bwindels says:

 I noticed one thing in the sync response after accepting an invite (so when the room appear under "join" for the first time): the state events are not complete. I don't receive the state at the point where I join. Instead I only get what seem to be the 3 first state events (m.room.create, m.room.member for room creator, m.room.power_levels). I would have expected the invite member event for another member to be in there that was invite just before me.
More concretely, the timeline looks like this, and the syncing user is Bruno3:

* Bruno1 joined the room.
* Bruno1 made future room history visible to all room members.
* Bruno1 changed the room name to the happy few.
* Bruno1 invited Bruno2.
* Bruno1 invited Bruno5.
* Bruno1 invited Bruno3.
* Bruno2 joined the room.
* Bruno3 joined the room.

Is this how it is supposed to work @ara4n ?
I tried to reproduce on develop with LL turned off but there state.events was just empty?
I thought you'd get the full room state (apart from joined members with LL turned on) after accepting a room, much like when doing an initial sync for a joined room? Maybe I'm missing something.

--

Separately, I'd seen this problem too (at least on iOS):

![image](https://user-images.githubusercontent.com/1294269/45258164-17826080-b3ab-11e8-9586-1bfe830bdfa7.png)

My notes at the time were:

> newly joined used in LL room don’t show up as having joined after accepting an invite into the room

**Comment by ara4n** [comment] 2018-09-08 21:30
Thinking further: i wonder whether (like #7211) this is also LL effectively behaving as intended, at least for @bwindels's issue: after you /join a room, you rely on /messages (i think?) to backpaginate the history (i think). So the initial /sync response for that room will only include the members who are in the timeline, which will be minimal.

I'm surprised that:

> I tried to reproduce on develop with LL turned off but there state.events was just empty?

however; i'd expect your first /sync for a room to contain a snapshot of the state (so you can set the room name/topic/avatar correctly).  How else would you know the state of the room you've just joined?

Eitherway, in the iOS screenshot I showed, there's either an iOS bug, or /messages (I assume?) is somehow losing the membership events that precede the join.

**Comment by ara4n** [comment] 2018-09-09 01:05
Actually, this isn't true. You should get the history in /sync once you've joined the room.  So the initial state of the room should be accurate (albeit missing almost membership events, given the only members we care about will be those in the timeline + heroes).

So I have no idea how the joins were missing from the timeline on iOS; i wonder if it's actually an iOS specific bug rather than serverside (cc @manuroe)

**Comment by bwindels** [comment] 2018-09-10 08:51
> Actually, this isn't true. You should get the history in /sync once you've joined the room. So the initial state of the room should be accurate (albeit missing almost membership events, given the only members we care about will be those in the timeline + heroes).

Indeed, that's how I understand it should work as well. There should be no difference in what state events you get back from `/sync` for a room on initial sync, or the room appearing for the first time under `join` during a normal sync, right? E.g. all non-member state events should be there, and the member state events relevant to the returned timeline (with LL turned on). In the issue described above in the description, I wasn't seeing `m.room.name` at least, and I think the membership events for the invites in the timeline were missing as well... would need to double check that.

**Comment by ara4n** [comment] 2018-09-10 16:28
> There should be no difference in what state events you get back from /sync for a room on initial sync, or the room appearing for the first time under join during a normal sync, right? E.g. all non-member state events should be there, and the member state events relevant to the returned timeline (with LL turned on). 

^ correct.

>  the issue described above in the description, I wasn't seeing m.room.name

It's possible you hit https://github.com/matrix-org/synapse/issues/2735 (or https://github.com/matrix-org/synapse/issues/3028)?  Was this a federated room undergoing state resets?

> and I think the membership events for the invites in the timeline were missing as well

Well, this would be expected if the invites happened before the beginning of the timeline events you received?

**Comment by bwindels** [comment] 2018-09-10 16:50
> It's possible you hit matrix-org/synapse#2735 (or matrix-org/synapse#3028)? Was this a federated room undergoing state resets?

No, this was on a local synapse with only users local to that HS IIRC.

**Comment by bwindels** [comment] 2018-09-13 08:08
Remaining action point here is to try and reproduce it again to get more details, and otherwise close it.

**Comment by bwindels** [comment] 2018-09-20 09:40
Cannot reproduce, so closing

**Closed by bwindels** 2018-09-20 09:40 UTC
Labels: bug, lazy-loading, p1
