### ISSUE TITLE
joined designUX long ago, I can no longer get in

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/riot-web#5518] opened 2017-11-05 09:20 UTC
I can't recall when I joined (sorry), but the room is in the directory with the suggestion that guests can join, and: 

- I can no longer get in. 

Screenshots of `/develop/` and `/app/` with SeaMonkey: 

![2017-11-05 07 13 46 develop](https://user-images.githubusercontent.com/192271/32413085-ac42a65e-c201-11e7-82fb-094abd04456b.png)

![2017-11-05 07 14 20 develop](https://user-images.githubusercontent.com/192271/32413086-b107a0f4-c201-11e7-9227-a619f3ff0712.png)

![2017-11-05 07 15 17 develop](https://user-images.githubusercontent.com/192271/32413088-b52ac72e-c201-11e7-95a4-22732be8d05d.png)

![2017-11-05 07 16 20 app](https://user-images.githubusercontent.com/192271/32413091-b91aa930-c201-11e7-8d57-3437421e6831.png)

![2017-11-05 07 17 49 app](https://user-images.githubusercontent.com/192271/32413093-beae80f6-c201-11e7-9880-d7e73eaccff8.png)

The symptoms with Firefox 56.0.1 (64-bit) are the same as with SeaMonkey. 

I tried promoting the room from LOW PRIORITY, then from ROOMS to FAVOURITES. Still no go.

**Comment by grahamperrin** [comment] 2017-11-05 10:32
I forgot to include the screen recording that preceded those five screenshots. here: 

[2017-11-05 07:07 Riot not reaching the designUX room.ogv.zip](https://github.com/vector-im/riot-web/files/1443923/2017-11-05.07.07.Riot.not.reaching.the.designUX.room.ogv.zip)

**Comment by grahamperrin** [comment] 2017-11-05 11:43
Whilst I can still not use the room with riot.im in Seamonkey, I **did** successfully enter the room and send a test message a few hours ago: 

- with Riot.im 0.7.03 (G-da8a7535b)
- on Android 6.0.1 on a YotaPhone 2
- with keyword _GELI_
- at 08:38

**Comment by uhoreg** [comment] 2017-11-05 16:00
I'm experiencing this issue too, and just sent a rageshake from Web.

**Comment by grahamperrin** [comment] 2017-11-06 06:35
@uhoreg thanks, I see you in the room. 

Do you have a comparable issue with any other room? 

Can you use the room with Chromium (or Google Chrome) but not with Firefox?

Here at the time of writing: Chromium 61.0.3163.100 (Developer Build) (64-bit) _is_ working with the room.

**Comment by uhoreg** [comment] 2017-11-23 03:06
Riot desktop seems to be working, so this seems to be a Firefox-specific issue

**Comment by grahamperrin** [comment] 2017-11-24 01:49
Testing with Iridium 58.0 (64-bit) on FreeBSD-CURRENT, it seems that the room has been renamed so, for example: 

https://riot.im/develop/#/room/#designUX:matrix.org

I'll retry with SeaMonkey …

**Comment by grahamperrin** [comment] 2017-11-24 02:02
SeaMonkey 2.49.1_7 <https://www.freshports.org/www/seamonkey> has no trouble with the renamed room. 

https://matrix.to/#/!blHeuKmYNNfIqDlWGO:matrix.org/$15108696751556475Agobe:matrix.org (2017-11-16)

> `art|code (@rosecheval:matrix.org) changed the room name to RiotDesignUX.`

@uhoreg can you use the renamed room with Firefox?

**Comment by uhoreg** [comment] 2018-01-19 16:47
I am now able to enter the renamed room.  But the underlying bug probably still should be fixed.

**Comment by turt2live** [comment] 2019-07-16 06:08
It sounds like the problem is a mix of state resets and angry Riots. I am presuming this fixed by time.

**Closed by turt2live** 2019-07-16 06:08 UTC
Labels: bug, major, p1, platform specific
