### ISSUE TITLE
Clarification for status: emoji / smiley support

### ISSUE THREAD

**Issue by adevress** [vector-im/riot-web#4424] opened 2017-06-26 21:07 UTC
Hi Guys,

I work in an organization that make a test to use riot.im / matrix as a possible replacer for Slack.

A recurrent complain about our users is the lack of smiley / emoticon of Riot ( compared to Slack ).

I see many tickets opened around about this topic but no clear answer, consequently I would like to ask you three questions :

- Is the support for emoji / smiley already added  ?
-> If Yes, How to enable it / use it ?
-> If No, Is it plan to add it ? What are the blockers ?

Adev

**Comment by t3chguy** [comment] 2017-06-26 21:11
Enable Composer in Settings>Labs
then you can type Emojis using their proper name in `:name:` format

Closing in favour of those other mentioned issues.
Might be easier just asking in #riot:matrix.org next time :)

**Closed by t3chguy** 2017-06-26 21:11 UTC

**Comment by ara4n** [comment] 2017-06-26 21:22
Just to clarify: the problem is that the experimental composer in labs (which has an emoji picker) is unstable, which is why it's in labs.  We're currently working on improving its stability though, but I wouldn't recommend it for daily use.

**Comment by t3chguy** [comment] 2017-06-26 21:42
Pasting in emojis from system keyboards such as on Mobile and on Mac (I believe) will work too

**Comment by ara4n** [comment] 2017-06-26 22:00
(On macOS you hit ctrl-cmd-space on any app to insert emoji, for instance, although few people seem to know this. 😿)

**Comment by adevress** [comment] 2017-06-27 08:35
@ara4n Yes but it would be good to have something that works on every platform and not only OSX.
And it would also be good it is through the interface and with a button, like most messaging App and not through an obscure keyboard binding ^^
