### ISSUE TITLE
Add feature to browse communities

### ISSUE THREAD

**Issue by brylie** [vector-im/riot-web#11827] opened 2020-01-13 09:41 UTC
When viewing the "groups" page, now called Communities, it is either empty or lists communities to which the current user belongs. How can users discover existing communities?

**Describe the solution you'd like**
When viewing the Communities (groups) page, there would be an intuitive way to discover existing communities. E.g., there could be a community browser, featured communities, community search, or something similar.

**Describe alternatives you've considered**
Well, I'm not sure how else to facilitate community discovery.

**Additional context**
There tend to be more people who join communities than organize new communities. Let's accommodate the majority use-case of discovering/joining communities.

**Comment by turt2live** [comment] 2020-01-13 18:06
Duplicate of https://github.com/vector-im/riot-web/issues/4428

**Closed by turt2live** 2020-01-13 18:06 UTC
Labels: suggestion
