### ISSUE TITLE
Very low colour contrast with the light theme

### ISSUE THREAD

**Issue by globau** [vector-im/riot-web#11960] opened 2020-01-21 03:50 UTC
### Description

Multiple elements of the light theme have a very low contrast, resulting in poor legibility and are likely to be an accessibility issue for vision impaired users.

For example the contrast of the message timestamp (`.mx_MessageTimestamp`) `#acacac` on `#ffffff` is 2.27:1, while 4.5:1 is the recommended minimum (https://www.w3.org/WAI/WCAG21/quickref/#contrast-minimum).  `#676767` is the closest match that meets contrast standards.

### Version information

- **Platform**: Riot desktop/electron app 
- **OS**: macOS,
- **Version**: v1.5.7

**Comment by turt2live** [comment] 2020-01-21 04:20
Duplicate of https://github.com/vector-im/riot-web/issues/7946

**Closed by turt2live** 2020-01-21 04:20 UTC
Labels: bug
