### ISSUE TITLE
Instant expose autocompete user list after typing @ in composer

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#11878] opened 2020-01-16 10:00 UTC
Most of custom (not public) chat rooms generally have not too much members, so will be good to expose autocomplete users list immediately after typing @ in composer, with list of room members, so users can select user via mouse, without typing his name via keyboard.

**Comment by MurzNN** [comment] 2020-01-16 10:08
For example, Telegram and Skype expose list of room members immediately after typing `@` in composer.

**Comment by t3chguy** [comment] 2020-07-16 06:42
Duplicate of https://github.com/vector-im/riot-web/issues/8960

**Closed by t3chguy** 2020-07-16 06:42 UTC
Labels: needs-product-decision, suggestion, type:autocomplete
