### ISSUE TITLE
Voice Messages

### ISSUE THREAD

**Issue by IngwiePhoenix** [vector-im/riot-web#12295] opened 2020-02-09 13:30 UTC
**Is your suggestion related to a problem? Please describe.**
Not related to a problem - however, it would solve a quality-of-life problem, if that counts.

**Describe the solution you'd like**
Using Matrix to bridge several services like WhatsApp and Telegram is great, but one of their great features is to send voice messages. I am visually impaired, so I would usually prefer to not having to type on my phone and send voice messages instead while being on the go. Having this feature would sure make things easier for me - and also keep things a little more natural, as other participants within those services send (... a lot.) of voice messages.

**Describe alternatives you've considered**
Wouldn't really know an alternative other than to... not implement it?

**Additional context**
Recording a simple WAV off the users's selected microphone and sending that should do just fine.

**Comment by t3chguy** [comment] 2020-02-09 13:59
Duplicate of #1358

**Closed** 2020-02-09 13:59 UTC
Labels: suggestion
