### ISSUE TITLE
[FF71] Unable to decrypt: ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied.

### ISSUE THREAD

**Issue by solstag** [vector-im/riot-web#11609] opened 2019-12-05 14:48 UTC
### Description

Encrypted rooms now show for each message:
`** Unable to decrypt: ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. **`

### Steps to reproduce

- Login.
- Set up key recovery.
- Click "Restore from backup" to make sure keys get recovered.
- Open any encrypted room.
- Notice the "doesn't have keys" message has changed to the above "constraint error".

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 71
- **OS**: Fedora GNU/Linux
- **URL**: riot.im/app (`matrix-react-sdk version: <local>, riot-web version: 1.5.5, olm version: 3.1.3`)

**Comment by solstag** [comment] 2019-12-05 14:50
I should add that I can read encrypted rooms normally from the Android app.

**Comment by turt2live** [comment] 2019-12-05 14:51
@solstag Please go to the settings page and on the Help tab click "Submit debug logs", referencing this issue.

**Comment by solstag** [comment] 2019-12-05 14:59
> @solstag Please go to the settings page and on the Help tab click "Submit debug logs", referencing this issue.

Tried to, got : `Failed to send logs: Failed to write logs: undefined`

**Comment by solstag** [comment] 2019-12-05 15:00
There's an option to "clear cache and reload", should I try that ? I have already tried <Control+Shift+R>.

**Comment by turt2live** [comment] 2019-12-05 15:03
Oh, this is firefox 71. I imagine this is https://github.com/vector-im/riot-web/issues/11606 then. I'll leave this open to triage.

**Comment by turt2live** [comment] 2019-12-05 15:14
@solstag are you using any particular settings in Firefox? Sometimes the privacy protection features interfere with the way Riot functions.

**Comment by solstag** [comment] 2019-12-05 15:18
> @solstag are you using any particular settings in Firefox? Sometimes the privacy protection features interfere with the way Riot functions.

Not that I know of, but perhaps defaults have changed? I have adblock, tried disabling it but no changes. Will try to login from a fresh profile.

**Comment by solstag** [comment] 2019-12-05 15:23
Tried with a clean Firefox profile, same issue. Still can't send logs.

**Comment by solstag** [comment] 2019-12-05 15:32
This may be related: the first time I access `riot.im/app` in a new profile, I get a strange message in a light red box:
```
Your Riot is misconfigured
Invalid homeserver discovery response
```
A second attemp renders the login screen. I created another profile and it happened again.

**Comment by sbiberhofer** [comment] 2019-12-05 15:35
I'm experiencing the same problem w/ riot-1.5.5 and Firefox 71 on Voidlinux. The console log usually reads something like 

~~~~
Error running command: getOutOfBandMembers indexeddb-worker.js:1:17088
[object Event] indexeddb-worker.js:1:17141
IndexedDBStore failure, degrading to MemoryStore [object Object]: ""
    _onWorkerMessage indexeddb-remote-backend.js:208
NotificationUtils.js:32:4
TypeError: this.promise is undefined bluebird.js:3510:25
TypeError: this.promise is undefined bluebird.js:3510:25
TypeError: this.promise is undefined bluebird.js:3510:25
TypeError: this.promise is undefined bluebird.js:3510:25
~~~~

I'm not sure if this is helpful but I'm also uncertain how to debug this since riot stops syncing (which looks like #11606 ) and behaves weirdly. I initially believed this to be connected to my cookie settings (which were quite restrictive) but have since experinced this in a clean profile too.

**Comment by jryans** [comment] 2019-12-05 16:54
For those on Fedora, this [Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=1779570) seems to suggest the browser storage is broken in some way for Fedora's custom build of Firefox 71.

**Comment by bwindels** [comment] 2019-12-06 09:23
Closing this as a duplicate of #11606 , as it this ticket describes a different symptom of the same problem. Please look there for updates and workarounds.

**Closed by bwindels** 2019-12-06 09:23 UTC
Labels: bug, 🔥 Fire 🔥
