### ISSUE TITLE
Login screen doesn't adapt well to viewport that isn't high enough

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#8284] opened 2019-01-28 16:24 UTC
![image](https://user-images.githubusercontent.com/274386/51850176-22696d80-2319-11e9-9d7a-904fc0189aae.png)

**Comment by jryans** [comment] 2019-01-28 19:41
This appears to be fixed in my local branch that should be up for review soon.

**Comment by jryans** [comment] 2019-01-28 22:23
Hmm, actually, I can't reproduce this on https://riot.im/experimental/#/login right now either... @bwindels, what browser were you in?

**Comment by bwindels** [comment] 2019-01-29 10:45
that was in Gnome Web, but I also see it in latest Chromium, so I suspect any webkit browser.
If I remove the height: 100% on mx_AuthPage it looks ok (unless the content can't fill the viewport).

**Comment by jryans** [comment] 2019-01-29 14:42
Hmm, so you checked against https://riot.im/experimental/#/login and not a local branch? Here's what I see from Chrome on macOS:

![2019-01-29 at 08 41](https://user-images.githubusercontent.com/279572/51915827-a2d3b100-23a1-11e9-8725-7745db8f28a5.png)

(I have now merged more changes to experimental login since this issue was first opened, so it looks different than previous screenshots...)

**Comment by jryans** [comment] 2019-01-30 15:22
Fixed by https://github.com/vector-im/riot-web/pull/8307.

**Closed by jryans** 2019-01-30 15:22 UTC
Labels: bug, defect, redesign
