### ISSUE TITLE
UX/behaviour for room icons inconsistent with user avatars

### ISSUE THREAD

**Issue by Nostradamos** [vector-im/riot-web#5430] opened 2017-10-25 08:57 UTC
When clicking on a room icon, it should show the room icon in full screen.
So clicking on a room icon should have the same behaviour as clicking on a user avatar.
Besides that, on a hover over a room icon it should turn the mouse icon into this magnifier.

Currently clicking on a room icon opens the the room settings, which also happens when clicking on the room title, or even the gear next to the room title. So we have three different clickable items in the same line which all result in the same.

**Comment by t3chguy** [comment] 2017-10-25 09:03
Duplicate of https://github.com/vector-im/riot-web/issues/2502

**Closed by t3chguy** 2017-10-25 09:03 UTC
