### ISSUE TITLE
Rooms disappeared from sidebar

### ISSUE THREAD

**Issue by notmart** [vector-im/riot-web#14647] opened 2020-07-20 08:56 UTC
### Description

After the transition from riot.im to element.io some rooms disappeared from the sidebar

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

A couple of rooms i'm subscribed to, 
https://app.element.io/#/room/#kirigami:matrix.org
and
https://app.element.io/#/room/#plasma:kde.org

are still there in the sidebar when i log in in the old site riot.im, but not in app.element.io
In the "explore rooms" search page #plasma:kde.org does come up in search, while #kirigami:matrix.org doesn't.
If I enter manually the two urls above, i can enter the rooms in element and use them correctly (so i'm still correctly subscribed to both)

Describe how what happens differs from what you expected.

screenshot of riot vs element, not the same rooms in the sidebar
![image](https://user-images.githubusercontent.com/4526371/87918809-35c14900-ca77-11ea-950e-ab57518ed625.png)
![image](https://user-images.githubusercontent.com/4526371/87918886-4ffb2700-ca77-11ea-8b70-5351905fe72a.png)

### Version information
- **Platform**: web 
- **Browser**: Firefox 73
- **OS**: Ubuntu
- **URL**: https://app.element.io

**Comment by Half-Shot** [comment] 2020-07-20 08:59
Same problem for me. Notice that in my debug logs there are lots of errors about missing rooms too.

**Comment by t3chguy** [comment] 2020-07-20 09:33
Duplicate of https://github.com/vector-im/riot-web/issues/14554

**Closed by t3chguy** 2020-07-20 09:33 UTC
