### ISSUE TITLE
Add UX to communities/groups right panel to set admins

### ISSUE THREAD

**Issue by benparsons** [vector-im/riot-web#10907] opened 2019-09-18 09:59 UTC
# Want

It's possible to have multiple admins for a community, and to add/remove admins. I would like a UX for this in the right panel.

This could be based on the existing groups right panel + the admin UX from the rooms right panel.

# Notes

There will be a potential problem in the form of:

- a is admin
- a makes b admin
- b removes adminship from a
- a writes to support@matrix.org to complain

I think this is an acceptable risk given that it's currently impossible to manage communities through riot.

Also: this is purely an MVP stopgap until the expected communities overhaul. This is, I think, the minimum work needed to really make communites useful in the short-term.

**Comment by t3chguy** [comment] 2019-09-18 10:49
Is there a matching Synapse/spec issue for Groups to support this?

**Comment by turt2live** [comment] 2019-09-18 20:47
This is not possible currently. Duplicate of https://github.com/vector-im/riot-web/issues/5240

**Closed by turt2live** 2019-09-18 20:47 UTC
Labels: suggestion
