### ISSUE TITLE
Pasting formatted text into message textfield doesn't work

### ISSUE THREAD

**Issue by torarnv** [vector-im/riot-web#5655] opened 2017-11-19 21:52 UTC
### Description

Copying formatted text (from a webpage, or Riot itself (quoting someone, e.g.)), and then pasting it into the message textfield result in no text in the field.

### Steps to reproduce

- Copy some text from a webpage
- Place cursor in message entry box
- Right click, choose "Paste"

The make the text appear, you have to choose "Paste and match style", which shouldn't be needed.

### Version information

Latest web-app

**Comment by t3chguy** [comment] 2017-11-19 21:53
Duplicate of https://github.com/vector-im/riot-web/issues/4962

**Closed by t3chguy** 2017-11-19 21:53 UTC
