### ISSUE TITLE
Unable to load session: e is null

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10501] opened 2019-08-04 18:05 UTC
```
2019-08-04T13:17:40.878Z E Unable to load session e is null
t.trackStores@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:63:264037
e/<@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:1:9697
E@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:38:13739
b/i._invoke</<@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:38:13527
x/</e[t]@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:38:13918
c@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:1:85498
o/<[16]</t.exports/p.prototype._promiseFulfilled@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:1:42370
o/<[22]</n.exports/F.prototype._settlePromise@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:1:59567
o/<[22]</n.exports/F.prototype._settlePromise0@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:1:60165
o/<[22]</n.exports/F.prototype._settlePromises@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:1:61517
f@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:1:13607
p@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:1:13546
o/<[2]</l.prototype._drainQueues@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:1:15054
l/this.drainQueues@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:1:13288
a@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:63:1095121
I/<@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:63:1095266
u@https://riot.im/app/bundles/e738ccbb3f8723bd3dcf/bundle.js:46:200295
```

**Comment by jryans** [comment] 2019-08-05 11:08
Duplicate of #10344

**Closed by jryans** 2019-08-05 11:08 UTC
Labels: bug, rageshake
