### ISSUE TITLE
Ability to configure spell check (currently wrong & cannot be disabled)

### ISSUE THREAD

**Issue by c33s** [vector-im/riot-web#13684] opened 2020-05-15 10:15 UTC
### Description

- if i write in german, everything is "red"
![2020-05-15 12_11_22- #  Riot _  #](https://user-images.githubusercontent.com/649209/82039439-459e6480-96a5-11ea-8940-ad99321fbee2.png)

- no way to disable spell checking
most of the time i write everthing lowercase, so even if the spell check would work correct for german, i would have many "red" words. so a switch to enable/disable the spellcheck would be required.

### Steps to reproduce

- write in a langage which is not english.

Describe how what happens differs from what you expected.

### Version information

- **Platform**: desktop?

For the desktop app:

- **OS**: Windows
- **Version**: 1.6.0

**Comment by c33s** [comment] 2020-05-15 10:15
refs: https://github.com/vector-im/riot-web/issues/2661

**Comment by t3chguy** [comment] 2020-05-15 10:56
If you have complaints about the dictionary itself, then it is the Chromium one.
Otherwise duplicate of https://github.com/vector-im/riot-web/issues/13543

**Closed by t3chguy** 2020-05-15 10:56 UTC
Labels: bug

**Comment by Exagone313** [comment] 2020-07-24 16:02
This isn't a duplicate of #13543, please re-open the issue.

**Comment by t3chguy** [comment] 2020-07-24 16:04
It is based on https://github.com/vector-im/riot-web/issues/13543#issuecomment-624566667

**Comment by Exagone313** [comment] 2020-07-24 16:06
I understand that both issues can be solved in the same development, but titles are different.

**Comment by Exagone313** [comment] 2020-07-24 16:09
Sorry, I'm in the wrong repo :smiley:
