### ISSUE TITLE
Quote messages with keeping link to original message

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4796] opened 2017-08-15 12:25 UTC
At now Riot have function to quote message, but now this feature only copy text of selected message to textarea with `>` symbol, so link to original message will broken.

Rocket.Chat have same feature, but much impoved: on `Quote` and `Reply` action it copy to textarea only link to selected message, like `[ ](https://demo.rocket.chat/channel/test2341?msg=7Lwm8tugAJ8huWu9G)` instead of message text, and chatlog interface replace this to quoted original message, also this allow multiple quotation, here is screenshot: http://i.imgur.com/Gbw3zD5.png

Implement feature like this in Matrix protocol will not need to change something on server side, and can be implemented in client side only.

So will be good to implement same behavior on Riot interface - quote messages as permalink to original message by id, and render them dynamically as quotation in chat log window.

**Comment by t3chguy** [comment] 2017-08-15 12:33
Duplicate of #3571

**Closed by t3chguy** 2017-08-15 12:33 UTC
