### ISSUE TITLE
Triple clicking doesn't select pills

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#7107] opened 2018-07-30 14:05 UTC
Type some text into the composter including a mention pill, triple click to select everything then press backspace to delete. The pill is not deleted.

**Comment by aaronraimist** [comment] 2018-10-21 01:37
I can't reproduce this

**Comment by t3chguy** [comment] 2018-10-27 11:01
Related to https://github.com/vector-im/riot-web/issues/7053

**Comment by turt2live** [comment] 2018-10-31 22:37
Closing as a duplicate of https://github.com/vector-im/riot-web/issues/7053 (can reproduce)

**Closed by turt2live** 2018-10-31 22:37 UTC
Labels: bug, minor, p1, regression, type:composer
