### ISSUE TITLE
Respect "do not disturb" in GNOME (Linux)

### ISSUE THREAD

**Issue by Yajo** [vector-im/riot-web#13941] opened 2020-06-06 10:51 UTC
**Is your suggestion related to a problem? Please describe.**
When I enable "do not disturb" in my GNOME desktop, notifications do not display, but there's still a sound when I recieve a chat message.

**Describe the solution you'd like**
When on do not disturb, riot should shut up :yum: 

**Describe alternatives you've considered**
Riot could have a "silence" trigger in the app itself, if it's not possible to do it otherwise.

**Additional context**
riot-web: 1.6.3
olm: 3.1.3
Desktop app, installed from Flathub. OS: Fedora Silverblue 32.

**Comment by t3chguy** [comment] 2020-06-06 12:12
Closing as duplicate of https://github.com/vector-im/riot-web/issues/7758

**Closed by t3chguy** 2020-06-06 12:12 UTC
Labels: suggestion
