### ISSUE TITLE
Riot doesn't tell me anymore if I have new unread messages under the ones I'm seeing on screen

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#10257] opened 2019-07-04 10:47 UTC

**Comment by jryans** [comment] 2019-07-08 15:21
Does anyone know when this was last believed to work? (Trying to spot whether it's a regression, and if so, when it may have appeared.)

**Comment by turt2live** [comment] 2019-07-08 15:34
Worked in 1.2.2

**Comment by bwindels** [comment] 2019-07-09 17:04
Neither me or Travis can reproduce this in the room (#ping:maunium.net) where he used to be able to repro this. I tried on /app, riot 1.2.3.

**Comment by turt2live** [comment] 2020-02-28 21:30
Closing due to no further information - probably fixed at some point.

**Closed by turt2live** 2020-02-28 21:30 UTC
Labels: bug, cannot-reproduce, p1, regression, type:timeline
