### ISSUE TITLE
Nick tab-completion at the beginning of the input regressed with RTE

### ISSUE THREAD

**Issue by eternaleye** [vector-im/riot-web#6014] opened 2018-01-20 02:20 UTC
I remember [bringing this up](https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1503715193762471xIHpz:matrix.org) when it first landed, but apparently never filed a ticket.

In the old, pre-RTE editor, tab-completing a sequence of names at the beginning like `foo<tab>bar<tab>baz<tab>` produced a comma-separated list of names, terminated by a colon.

In short:
- `foo<tab>` produced `foo: `
- Appending `bar<tab>` to that produced `foo, bar: `
- Appending `baz<tab>` to that produced `foo, bar, baz: `

In the RTE editor, it instead inserts a pill for the first name followed by a colon, then inserts the subsequent names as if they were mere references in the body of the message.

This makes it decidedly suboptimal for addressing multiple people in a message, and requires significant time to patch up on each message.

**Comment by t3chguy** [comment] 2018-01-20 08:36
Duplicate of #4883

**Comment by t3chguy** [comment] 2018-01-20 08:36
Duplicate of #4883

**Closed** 2018-01-20 08:36 UTC
