### ISSUE TITLE
Implement "Categories" Feature for rooms

### ISSUE THREAD

**Issue by jdbohrman** [vector-im/riot-web#9944] opened 2019-06-03 22:35 UTC
### Implement "Categories" feature

One thing I miss from Discord is the ability to categorize my rooms/channels into different subgroups based on their function. The current UI is a mess in that regard because when I pull up my rooms, I just see a huge list with no organization whatsoever. 

![rooms](https://user-images.githubusercontent.com/27848025/58838592-c09d7500-8624-11e9-8349-39606e94c9e9.png)

Compared to:

![Screenshot from 2019-06-02 20-39-29](https://user-images.githubusercontent.com/27848025/58838611-d0b55480-8624-11e9-8a00-9b0cbbca8142.png)

### Version information
Riot-web Version 1.2.1

- **Platform**: web (in-browser) or desktop?

Web

For the web app:

Browser: Chrome
OS: PopOS!
URL: Private

**Comment by MTRNord** [comment] 2019-06-04 04:51
There are already tags. Riot just misses a ui to add them. It does Show them if they are present. @tur2live has a Web App to Set them afaik

**Comment by turt2live** [comment] 2019-06-04 05:11
Indeed, this is a duplicate of https://github.com/vector-im/riot-web/issues/1373. I do have an interface at https;//tags.t2bot.io (https://github.com/turt2live/matrix-tag-manager) for managing them, although you'll still have to enable the Labs options - see https://github.com/vector-im/riot-web/issues/8723.

**Closed by turt2live** 2019-06-04 05:11 UTC
Labels: bug, ui/ux
