### ISSUE TITLE
We should prompt the user at registration whether they want to bind their 3pid or not

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10054] opened 2019-06-14 08:57 UTC
We used to do this in Console with a checkbox; from a privacy perspective we should do it in Riot also, somehow.

We may also want to give ISes a way to publish their terms of use and let the user confirm they really want to use the IS.

**Comment by anoadragon453** [comment] 2019-08-07 12:30
Duplicate of https://github.com/vector-im/riot-web/issues/10401

**Closed by anoadragon453** 2019-08-07 12:30 UTC
Labels: privacy, suggestion, type:threepids
