### ISSUE TITLE
After cross-signing successfully adds device, there is still a dialog infini-spinner remaining

### ISSUE THREAD

**Issue by benparsons** [vector-im/riot-web#12067] opened 2020-01-27 11:42 UTC
<img width="837" alt="Screenshot 2020-01-27 at 11 37 11" src="https://user-images.githubusercontent.com/1197991/73172093-22ea3f00-40fa-11ea-8d51-6694f2520bfe.png">

**Comment by foldleft** [comment] 2020-01-27 15:59
Thanks for the feedback!

I've been unable to repro yet.  Here's the steps I tried:
1. Solo
* Tried logging in on https://riot.im/app as `test2` on my local instance.  As this user had no devices, I was prompted for a cross-signing key directly.  I was unable to repro.

**Comment by turt2live** [comment] 2020-01-27 16:01
I had this this morning too. I wrote it off as slow homeserver, but I believe Ben's should be fast enough.

**Comment by foldleft** [comment] 2020-01-27 16:07
2. With two riot-web devices, one running develop (A) and one on riot.im/app (B)
* Login screen on B
<img width="718" alt="Screenshot 2020-01-27 at 16 01 13" src="https://user-images.githubusercontent.com/3935731/73190899-92722580-411e-11ea-8392-2dd933724bb3.png">
<img width="752" alt="Screenshot 2020-01-27 at 16 01 24" src="https://user-images.githubusercontent.com/3935731/73190974-a87fe600-411e-11ea-94e5-e7bf37704800.png">
* A gets a request. **At this point my options fork, and I proceed from A**
<img width="514" alt="Screenshot 2020-01-27 at 16 01 33" src="https://user-images.githubusercontent.com/3935731/73190989-ae75c700-411e-11ea-8354-7ef78af870ac.png">
<img width="828" alt="Screenshot 2020-01-27 at 16 01 38" src="https://user-images.githubusercontent.com/3935731/73191033-c6e5e180-411e-11ea-8eca-a86361e7e477.png">
<img width="814" alt="Screenshot 2020-01-27 at 16 01 47" src="https://user-images.githubusercontent.com/3935731/73191084-d82eee00-411e-11ea-8fe4-767235cbb569.png">
* Device B gets a query about this
<img width="806" alt="Screenshot 2020-01-27 at 16 01 52" src="https://user-images.githubusercontent.com/3935731/73191121-e846cd80-411e-11ea-8764-178500d8838c.png">
* Device A's state changes
<img width="1272" alt="Screenshot 2020-01-27 at 16 02 05" src="https://user-images.githubusercontent.com/3935731/73191142-f0067200-411e-11ea-969d-133b1c703a7d.png">
* Device B follows through
<img width="869" alt="Screenshot 2020-01-27 at 16 02 12" src="https://user-images.githubusercontent.com/3935731/73191180-fdbbf780-411e-11ea-8632-cbd4eda3fa0e.png">
<img width="820" alt="Screenshot 2020-01-27 at 16 02 17" src="https://user-images.githubusercontent.com/3935731/73191181-fdbbf780-411e-11ea-8464-7f132c7dbc56.png">
* Device A supplies the SSSS key
<img width="1182" alt="Screenshot 2020-01-27 at 16 02 27" src="https://user-images.githubusercontent.com/3935731/73191228-0d3b4080-411f-11ea-8b7d-2b77e6f328d5.png">
<img width="851" alt="Screenshot 2020-01-27 at 16 02 40" src="https://user-images.githubusercontent.com/3935731/73191231-0d3b4080-411f-11ea-8316-0339276c9fa4.png">
* Device B is told things are good, and is prompted for the same SSSS key for backups
<img width="810" alt="Screenshot 2020-01-27 at 16 02 49" src="https://user-images.githubusercontent.com/3935731/73191255-19270280-411f-11ea-8d8b-b4faa64d16d8.png">
<img width="830" alt="Screenshot 2020-01-27 at 16 02 55" src="https://user-images.githubusercontent.com/3935731/73191256-19270280-411f-11ea-834a-c629cddf79e1.png">

**Comment by foldleft** [comment] 2020-01-27 16:11
oh! I think I just got a repro. there was a moment there where both clients were sitting in the "waiting for client to accept" state for about 10s

**Comment by turt2live** [comment] 2020-01-27 16:16
I got it *after* the emoji were confirmed, as I think @benparsons did too.

**Comment by turt2live** [comment] 2020-01-27 16:17
The spinner before is almost certainly homeserver delays.

**Comment by benparsons** [comment] 2020-01-27 16:24
yeah for me the dialog I show in the screenshot was just sat there at the end of the whole process

**Comment by foldleft** [comment] 2020-02-12 11:25
can't repro due to being unable to complete the flow right now (doing a synapse/riot-web rebuild to check it's not old state) but this flow is very changed, maybe we should close this one as unreproduceable

**Comment by jryans** [comment] 2020-02-12 11:34
Makes sense to me, let's track any remaining problems in fresh issues.

**Closed by jryans** 2020-02-12 11:34 UTC
Labels: bug, cross-signing-sprint, phase:2, story:1
