### ISSUE TITLE
Save button is too hidden when setting avatar

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11898] opened 2020-01-17 02:58 UTC
<img width="1068" alt="Screenshot 2020-01-17 at 02 57 48" src="https://user-images.githubusercontent.com/1294269/72580849-3bc24b80-38d5-11ea-9ac4-db60a87db729.png">

**Comment by aaronraimist** [comment] 2020-01-17 03:56
Duplicate of #10170

**Closed by aaronraimist** 2020-01-17 03:56 UTC
Labels: bug, mozilla
