### ISSUE TITLE
Presence is not clearly shown anymore in Riot 1.0.x

### ISSUE THREAD

**Issue by ejpcmac** [vector-im/riot-web#8775] opened 2019-02-19 12:20 UTC
- **Browser**: Electron app
- **OS**: Fedora, NixOS, macOS

### Description

In Riot pre-1.0, the (off|on)line status was clearly shown: offline usernames and icons where greyed, and online users where normal. Now, offline users are not greyed anymore. It is still possible to see the status by hovering the username to display the status line, but it is not evident to see who is online and who isn’t.

### Steps to reproduce

- Use Riot 1.0.0+
- Connect to a home server with presence enabled
- Join a room with (on|off)line users
- Show the “Members” bar
- Note that you can’t easily tell who is online and who isn’t

You should be able to see the presence quickly.

**Comment by turt2live** [comment] 2019-02-19 15:09
This is fixed on develop.

**Comment by ejpcmac** [comment] 2019-03-25 07:54
This bug seems to have appeared again in v1.0.4.

**Comment by jryans** [comment] 2019-03-25 14:16
Reopening for triage against 1.0.4.

**Comment by turt2live** [comment] 2019-03-25 15:51
Duplicate of https://github.com/vector-im/riot-web/issues/9178

(fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2794)

**Closed by turt2live** 2019-03-25 15:51 UTC
Labels: redesign
