### ISSUE TITLE
I can't invite someone when I only know their user ID

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#3442] opened 2017-03-15 15:26 UTC
Because the drop down hides the invite button and even if I type a valid ID the selection is on the first item of the list (even if the ID is wrong). Suggestion on how to fix: Move the invite button on the right and not select any item in the list if the ID is valid but different from any listed.

**Comment by lukebarnard1** [comment] 2017-03-15 15:30
@AmandineLP I suspect this is a dupe of https://github.com/vector-im/riot-web/issues/3404. It seems that this UI is quite confusing.

>if I type a valid ID the selection is on the first item of the list (even if the ID is wrong)

This is probably because the fuzzy search has decided that the best it could find is the user shown. If the user hasn't been seen by your Riot before, then that user is not searchable.

**Comment by lampholder** [comment] 2017-03-15 16:03
Yep; this looks like a dupe to me.

@AmandineLP I'm not yet 100% sure of duplicate etiquette, but I'm going to close this - pls reopen if you think #3404 doesn't identify the same issue.

**Closed by lampholder** 2017-03-15 16:03 UTC
Labels: duplicate
