### ISSUE TITLE
scroll position reverts to top while scrolling down in left panel

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#13884] opened 2020-06-02 11:51 UTC
see https://matrix.to/#/!RbKRuLTvHIhArQcvjr:matrix.org/$1591098660121702AieRS:matrix.org?via=matrix.org&via=vector.modular.im&via=lant.uk

**Comment by turt2live** [comment] 2020-06-02 13:17
Duplicate of https://github.com/vector-im/riot-web/issues/13565

**Closed by turt2live** 2020-06-02 13:17 UTC
