### ISSUE TITLE
hit the video call button in a room which already has a widget; minimise then maximise the widget; jitsi no longer loads

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8631] opened 2019-02-14 14:50 UTC

**Comment by lampholder** [comment] 2019-03-14 13:29
https://matrix.lant.uk/_matrix/media/v1/download/lant.uk/iAzZKlgCpWCQJiqLmUtrKZyl

**Comment by turt2live** [comment] 2020-04-03 21:26
Duplicate of https://github.com/vector-im/riot-web/issues/7363 (fixed)

**Closed by turt2live** 2020-04-03 21:26 UTC
Labels: bug, major, p1, type:voip
