### ISSUE TITLE
Accepting an invited didn't move the invite from the invite section to the room section of the roomlist

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#8373] opened 2019-02-02 00:09 UTC

**Comment by turt2live** [comment] 2019-02-02 00:51
This is the anti-update-while-hovering behaviour interacting badly with other use cases. Moving off the room list magically fixes it.

**Comment by turt2live** [comment] 2019-02-11 23:15
Closing as a duplicate of https://github.com/vector-im/riot-web/issues/8186 due to cause, not symptoms.

**Closed by turt2live** 2019-02-11 23:15 UTC
