### ISSUE TITLE
Support re-sending e2e keys to other participants in the room

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#9505] opened 2019-04-16 22:50 UTC
**Is your suggestion related to a problem? Please describe.**
When I still have access to my old e2ee messages, but my room mate hasn't, I want to provide those messages again.

This is especially acute now that many people have lost their keys due to the measures taken after *the incident*.

**Describe the solution you'd like**
If one member of an encrypted room has lost the keys, but another member still has them, allow that other member to resend all keys/messages to the first member.  If needed a cut-off for messages from before the time of joining could be applied.  This should 'revive' the currently unreadable messages rather than send copies.

**Comment by aaronraimist** [comment] 2020-02-19 01:10
Looks like you opened this twice. I'll leave the newer one open since it has some more discussion.

Duplicate of #12275

Also related: https://github.com/vector-im/riot-web/issues/2286

**Closed by aaronraimist** 2020-02-19 01:10 UTC
Labels: suggestion

**Comment by Biep** [comment] 2020-02-19 21:33
Early onset Alzheimer kicking in again..
