### ISSUE TITLE
Taskbar/tray icon missing in gnome-shell

### ISSUE THREAD

**Issue by blefuscu** [vector-im/riot-web#13753] opened 2020-05-21 15:28 UTC
### Description

Tray icon is missing in Cinnamon (gnome-shell) since version about 1.6.1

* this functionality used to work in the past, stopped working on around 18-20.05.2020
* possibly related to #13692 ?

### Steps to reproduce
1. start riot-desktop

#### Expected behaviour
* tray icon appears in gnome-shell tray

### Actual behaviour
* no tray icon present, although notifications are present
* restarts do not help

### Version information

- **Platform**: desktop
- **OS**: Linux Mint 19.3 Cinnamon
- **Version**: 1.6.1
- Cinnamon version: 4.4.8

**Comment by t3chguy** [comment] 2020-05-21 15:29
Duplicate of https://github.com/vector-im/riot-web/issues/12518

**Closed by t3chguy** 2020-05-21 15:29 UTC
