### ISSUE TITLE
Unable to decrypt messages received when offline when using only in private/incognito mode

### ISSUE THREAD

**Issue by tx1683** [vector-im/riot-web#10578] opened 2019-08-16 11:45 UTC
### Description

When using in only one device in browser in private/incognito mode and using online backup most encrypted messages received when user is offline are undecryptable when logged in. 

### Steps to reproduce

- Log in to Riot Web in browser private mode
- Connect to key backup
- Normal usage
- Log out / close tab / close browser
- Someone sends encrypted message
- Log in
- Connect to key backup
- Most or all messages received when offline cannot be decrypted

Messages send to me, when my only device is offline should be encrypted using that device pubkey. When logged in with new key and then to online backup that messages should be decrypted using that key which was restored from backup.

### Version information

- **Platform**: web
- **Browser**: Firefox 68.0.2 and earlier, all in private mode 
- **OS**: Arch Linux
- **URL**: few self hosted instances and riot.im/app, all 1.3.2 and/or earlier

**Comment by t3chguy** [comment] 2019-08-16 11:52
The issue is that when you log in you generate a new set of device keys, and any key rotations which happen while you have no active devices would go unnoticed

**Comment by tx1683** [comment] 2019-08-16 11:58
Key rotation in sender I presume?
Shouldn't sender wait with rotating its keys when recipient is offline?
Or any other solutions...
That issue is making encryption pretty unusable for some people and is very annoying.

**Comment by t3chguy** [comment] 2019-08-16 12:04
Key rotation happens whenever the device list changes (to prevent leaking encryption keys) and also periodically to provide forward secrecy

The issue is easily worked around by keeping a session alive on a mobile device

**Comment by tx1683** [comment] 2019-08-16 13:46
I know about this workaround, but in my use case it isn't practical, sadly.
Is there any theoretical way to keep FS, and also deliver decryptable messages when recipient is offline?

**Comment by turt2live** [comment] 2019-08-16 14:44
Closing in favour of cross-signing, which should address this sort of use case. Tracking issue is https://github.com/vector-im/riot-web/issues/9631

**Closed by turt2live** 2019-08-16 14:44 UTC
Labels: bug

**Comment by gardenBanter** [comment] 2023-10-18 20:52
> Closing in favour of cross-signing, which should address this sort of use case. Tracking issue is #9631

How does cross-signing help in this scenario?
