### ISSUE TITLE
Interaction of redaction and encryption sometimes makes things look ugly

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/riot-web#4763] opened 2017-08-08 16:30 UTC
### Description

When I redact an event in an encrypted room, sometimes the redacted event will look like the below when I view it later.

![UTD with ugly background redaction strip](https://user-images.githubusercontent.com/17915621/29082898-05f4edbe-7c35-11e7-9c4b-a819dcf742c4.PNG)

This bug isn't for whatever is causing Riot to get confused but to fix the UI to look more appealing in these cases.

### Steps to reproduce

- Send a message into an encrypted room
- Redact that message
- Wait/reload riot/???

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 54.0.1 64-bit (but I believe I've seen this in other browsers as well)
- **OS**: Windows (but I believe I've seen this on linux as well)
- **URL**: riot.im/develop (but I believe I've seen this on /app as well)

**Comment by lampholder** [comment] 2017-08-08 17:09
Gah.

I think the redaction rip and the unable to decrypt message are both ugly in their own right; apparently they can join forces to birth something incredibly ugly :P

If you can't decrypt an event but you _can_ see enough about it to know that it was redacted, then I'd argue in favour of its simply rendering as redacted - who cares that you don't have its key.

**Comment by turt2live** [comment] 2017-08-09 01:13
Duplicate of https://github.com/vector-im/riot-web/issues/3744

**Comment by t3chguy** [comment] 2017-08-09 09:09
Closing as duplicate

**Closed by t3chguy** 2017-08-09 09:09 UTC
Labels: bug, cosmetic, minor, p2, type:e2e, ui/ux

**Comment by non-Jedi** [comment] 2017-08-09 10:30
Gah. My search-foo was weak.
