### ISSUE TITLE
More helpful message when giving a room an existing address

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10064] opened 2019-06-15 15:44 UTC
When one tries to give a room an address that is already in use, one gets a very generic and unhelpful error message.  It would be better to have a specific one saying 'This address is already in use', or even better 'There is already a room with this address'.
The message could also explain the rules on lower case matching upper case, and so on.

**Comment by turt2live** [comment] 2019-06-15 21:04
Duplicate of https://github.com/vector-im/riot-web/issues/9367

**Closed by turt2live** 2019-06-15 21:04 UTC
