### ISSUE TITLE
Add option for room lists with a stable ordering (perhaps alphabetical)

### ISSUE THREAD

**Issue by jrmuizel** [vector-im/riot-web#12242] opened 2020-02-04 23:23 UTC
Currently it seems like the order that rooms are listed is based on recent activity. This means that the order is constantly changing which means you have to search through the list each time to find the room that you want.

Slack orders the rooms alphabetically which means that the order doesn't change so you always know roughly where to look for a particular room.

**Comment by aaronraimist** [comment] 2020-02-04 23:32
I'm going to close this as a duplicate of #4343, feel free to thumbs up that issue

**Comment by jryans** [comment] 2020-02-05 12:23
I think I'd actually like to keep this open, as https://github.com/vector-im/riot-web/issues/4343 has a larger scope, and we might not do all of it at the same time.

**Comment by TestardR** [comment] 2020-02-08 18:06
![image](https://user-images.githubusercontent.com/40339476/74089835-a8300500-4aa5-11ea-9c2b-d87bc8d5f33f.png)

We could work on these settings to allow for alphabetical ordering.  Then, we would have 3 ordering possibilities: 1. Most recent, 2. Most important, 4, Alphabetical

**Comment by t3chguy** [comment] 2020-02-11 12:40
> it might make more sense to users choose:

Sort my rooms by
[x] Alphabetically (default)
[ ] Activity

... and separately have a toggle for:

Stick my notifications up top [ON/OFF]

**Comment by turt2live** [comment] 2020-02-11 15:43
That sort of option set doesn't describe how the algorithms work, at all. The importance algorithm uses activity as a tie break, not a feature. We already had a "Stick my notification up top"-like option before, and it was incredibly confusing for people.

I'm still not convinced that making the list alphabetical will fix the problem - there's a number of known bugs with the importance algorithm which happen just prior to most people suggesting that it should be alphabetical.

**Comment by nadonomy** [comment] 2020-02-11 17:17
We had some internal discussion on this. In the immediate term we'll update the Room list section of Settings to be as follows:

### Room list
Order rooms by message activity instead of by name [Toggle OFF/ON]
Show rooms with unread notifications first  [Toggle OFF/ON]
Show shortcuts to recently viewed rooms [Toggle OFF/ON]

**Comment by mjattiot** [comment] 2020-02-12 08:58
> Show shortcuts to recently viewed rooms [Toggle OFF/ON]

Speaking of which ! I think the above feature (i.e. breadcrumbs / recently viewed) should be shown as a room's sublist and not a breadcrumb. Why ? Because most of our rooms don't have any logo: people don't have the time to set them up. Therefore it leads to a breadcrumb full of colored bubbles that are not self explaining: we need to hover the mouse on a bubble to see the name of the room in a tooltip:
<img width="368" alt="Screenshot 2020-02-12 at 09 52 52" src="https://user-images.githubusercontent.com/17925691/74318717-0ac32280-4d7e-11ea-9e31-f1fe3bb266d0.png">

We think, a room section called "Recently Viewed" showing a maximum of ~5 rooms would be much more efficient. What do you guys think ?

**Comment by nadonomy** [comment] 2020-02-12 09:47
> > Show shortcuts to recently viewed rooms [Toggle OFF/ON]
> 
> Speaking of which ! I think the above feature (i.e. breadcrumbs / recently viewed) should be shown as a room's sublist and not a breadcrumb. Why ? Because most of our rooms don't have any logo: people don't have the time to set them up. Therefore it leads to a breadcrumb full of colored bubbles that are not self explaining: we need to hover the mouse on a bubble to see the name of the room in a tooltip:
> <img alt="Screenshot 2020-02-12 at 09 52 52" width="368" src="https://user-images.githubusercontent.com/17925691/74318717-0ac32280-4d7e-11ea-9e31-f1fe3bb266d0.png">
> 
> We think, a room section called "Recently Viewed" showing a maximum of ~5 rooms would be much more efficient. What do you guys think ?

This is interesting, but I'm not sure the trade off in space (less room to display other rooms) and number of rooms exposed (less rooms to navigate to) is aligned with users goals.

The breadcrumbs themselves speak to the failure of navigating rooms in general in Riot— we have immediate updates (like this issue) to help address sort ordering, medium term work planned to re-address the semantics of the room list entirely (moving away from unergonomic scrolling letterboxes) and long term plans to re-work communities to make the both the left most panel and room list sections 100x more useful.

From there, the requirement for a separate feature to expose a list of recently viewed rooms (as breadcrumbs, or in a section, or whatever) should be way less prevalent, and we could look at ways to iterate on it then trading off all of the above, where it may even make more sense to replace it with a back/forward interaction like a browser.

**Comment by mjattiot** [comment] 2020-02-18 13:24
@nadonomy I clearly understand that my need shall be less prevalent considering you have mid and long term ideas to rework the whole navigation. However could you be more specific on what you have planned for the mid-term ? I don't understand "re-address the semantics of the room list entirely". What do you mean ? Is there a draft of this work ? Maybe we can help, contribute to it.

**Closed** 2020-02-28 12:04 UTC
Labels: mozilla, suggestion, type:roomlist, ui/ux

**Comment by jrmuizel** [comment] 2023-01-19 15:10
Did this option get removed? My rooms are not ordered by name anymore and I don't see a preference to enable that.

**Comment by t3chguy** [comment] 2023-01-19 15:11
<img width="468" alt="image" src="https://user-images.githubusercontent.com/2403652/213479022-c31986c4-4887-4790-b9c8-e1b8cb74b07d.png">

**Comment by SeleDreams** [comment] 2023-10-31 20:58
Couldn't it be ordered like discord ? allowing the community's admin to reorder the channels as they see fit ?
