### ISSUE TITLE
Include PureOS in Debian package repositories

### ISSUE THREAD

**Issue by wtraylor** [vector-im/riot-web#13194] opened 2020-04-16 08:14 UTC
# Problem
I am using [PureOS](https://pureos.net/) `amber`, a Debian-based Linux distro by [Purism](https://puri.sm).
To install Riot.im I followed the instructions on <https://riot.im/download/desktop/>:

```bash
echo "deb [signed-by=/usr/share/keyrings/riot-im-archive-keyring.gpg] https://packages.riot.im/debian/ $(lsb_release -cs) main" |    sudo tee /etc/apt/sources.list.d/riot-im.list
```

The command `lsb_release -cs` yields `amber`, but `amber` is not among the distros on <https://packages.riot.im/debian/dists/>.
Therefore, the `apt update` fails. Compare issue #9663.

# Makeshift
Replacing `$(lsb_release -cs)` with `xenial` (Ubuntu) in the above command works.

# Suggested Solution
Add PureOS releases to <https://packages.riot.im/debian/dists/>, in particular `amber`.

## Alternative
Explain a work-around on <https://riot.im/download/desktop/> for PureOS users who are less tech-saavy and need a copy-paste solution. For example, a suggestion to use Ubuntu `xenial` *in lieu* of PureOS `amber`.

**Comment by t3chguy** [comment] 2020-04-16 08:48
Related/duplicate of https://github.com/vector-im/riot-web/issues/11929

**Comment by jryans** [comment] 2020-05-05 15:48
We have now created a `default` distribution for everyone to use going forward (https://github.com/vector-im/riot-web/issues/13367). The download page (https://riot.im/download/desktop/) has been updated to match.

**Closed by jryans** 2020-05-05 15:48 UTC
Labels: suggestion, type:electron, type:packaging
