### ISSUE TITLE
Invites wrap long account names

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#14072] opened 2020-06-17 20:29 UTC
When I invite @xxxx:matrix.valenciawireless.org, when I have typed in 31 characters, they disappear and only the last two remain visible.  The invite does work, though, so I strongly suspect the field has a length of 32 and the account name just wraps.

**Comment by t3chguy** [comment] 2020-06-17 20:30
duplicate of #13066

**Closed** 2020-06-17 20:31 UTC
