### ISSUE TITLE
Dropping an icon in the LLP while filtering causes the filter to be cleared

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6253] opened 2018-02-26 17:25 UTC
### Description

1. Click a group to filter on it
2. Move any group in the LLP

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 64
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment] 2018-02-28 08:45
So it does! That's annoying.

@lukebarnard1 if this is trivial to fix whilst we're in the area lets consider it for 0.14; I think if you're not expecting to touch that code again before 0.14 maybe lets leave it until (soon) after.

**Comment by lukebarnard1** [comment] 2018-02-28 16:49
I reckon this is the same thing causing https://github.com/vector-im/riot-web/issues/6156 which is in-turn caused by https://github.com/atlassian/react-beautiful-dnd/issues/273 and fixed by https://github.com/atlassian/react-beautiful-dnd/pull/353, but this hasn't been released.

**Comment by turt2live** [comment] 2018-02-28 16:56
Probably. Is the entire LLP background supposed to clear the filter, or just the X at the top? Currently it seems to still be the entire thing

**Comment by lukebarnard1** [comment] 2018-02-28 16:57
The intention is that the background also clears the filter.

**Closed** 2018-02-28 18:33 UTC
Labels: bug, minor, p1, type:llp, ui/ux
