### ISSUE TITLE
[Feature Request] Windows installer - Install options

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#9142] opened 2019-03-12 20:38 UTC
I like how streamlined the Riot installer is, however I don't just want to install it in my user profile. I'd like the option to install it for all users.

Naturally this means my login creds need to be stored securely in my user profile too.

As it is today, 1.0.3, the installer pops up, seems to run, and give the user zero indication what's going. This really needs to be improved to at least tell the user what is going on. And especially say something like "Installation successful!".

It's streamlined, but I think the UX and options needs some tuning ;)

**Comment by t3chguy** [comment] 2019-03-12 20:57
Duplicate of https://github.com/vector-im/riot-web/issues/2817

**Closed by t3chguy** 2019-03-12 20:57 UTC
Labels: suggestion

**Comment by BloodyIron** [comment] 2019-03-12 21:03
@t3chguy oops missed that in my search! Sorry!
