### ISSUE TITLE
People are losing rooms in 1.0.2 (clicking rooms causes other rooms to outright disappear)

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#9066] opened 2019-03-06 15:16 UTC
See debug logs submited a couple minutes ago by @as.tyrants.fall666:matrix.org. https://matrix.to/#/!iNmaIQExDMeqdITdHH:matrix.org/$155188427459574TebdF:matrix.org?via=matrix.org&via=linuxgaming.life&via=feneas.org

> We both sent each other invites about an hour ago, but nothing yet.

**Comment by turt2live** [comment] 2019-03-06 15:32
Unfortunately the logs don't reveal anything because the useful logging was included in a patch that didn't make it in because it evaded my lists :(

Conveniently, the patch that adds the useful debugging is also the one that fixes it. 

https://github.com/matrix-org/matrix-react-sdk/pull/2736 - Fixes the issue
https://github.com/matrix-org/matrix-react-sdk/pull/2741 - Adds useful logging
https://github.com/matrix-org/matrix-react-sdk/pull/2735 - Fixes the next complaint people would have

Dave is working on a 1.0.3 to fix my screwup (sorry!)

**Comment by turt2live** [comment] 2019-03-07 04:42
Fixed in 1.0.3 (confirmed)

**Closed by turt2live** 2019-03-07 04:42 UTC
