### ISSUE TITLE
Switching tabs with Ctrl-tab is broken

### ISSUE THREAD

**Issue by jo-so** [vector-im/riot-web#8342] opened 2019-01-31 12:49 UTC
- **Browser**: Firefox 56
- **OS**: Debian

### Description

I use the keys ctrl-tab to cycle through the tab list and ctrl-shift-tab to open the list of tabs. These keys seem to be blocked by Riot.

**Comment by lampholder** [comment] 2019-01-31 14:35
Are those standard key bindings? On my mac and my ubuntu machine, ctrl-tab cycles forward through tabs, and ctrl+shift+tab cycles backwards. And riot doesn't seem to block either.

Are you able to cycle through tabs until you hit riot, then get stuck?

**Comment by jo-so** [comment] 2019-01-31 22:02
> Are those standard key bindings? On my mac and my ubuntu machine,
> ctrl-tab cycles forward through tabs, and ctrl+shift+tab cycles
> backwards. And riot doesn't seem to block either.

I didn't recognise when sending this report, that it happens only when I'm
in the filter field.

1. press ctrl-k
1. press ctrl-tab

> Are you able to cycle through tabs until you hit riot, then get stuck?

Yes, I'm stuck in the room list. It cycles through the list, but not
through the tabs. Does the key event for this input field check for
modifier keys?

**Comment by lampholder** [comment] 2019-03-14 12:09
A lot has changed in this area recently, and I can't reproduce this on firefox or chrome on ubuntu or mac. I'm going to close the issue, but if you still have a problem do let me know.

**Closed by lampholder** 2019-03-14 12:09 UTC
Labels: question, redesign
