### ISSUE TITLE
Bottom align read receipts

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9525] opened 2019-04-18 13:37 UTC
Due to the nature of the timeline, we teach users to look at the bottom right corner for read receipts. However, as they're aligned to the top of messages, this muscle memory doesn't translate to long multi-line messages, or tall media. It's easy to mis-assign them or flat out miss them.

For example, Manu's read receipt here is actually signalling he's viewed the image, which isn't intuitive:

<img width="934" alt="Screenshot 2019-04-18 at 15 28 15" src="https://user-images.githubusercontent.com/4626865/56364772-b3046b00-61ef-11e9-84a0-b53f4b3a43e0.png">

**Comment by turt2live** [comment] 2019-04-18 15:45
Duplicate of https://github.com/vector-im/riot-web/issues/4377

**Closed by turt2live** 2019-04-18 15:45 UTC
