### ISSUE TITLE
Lock form fields on login screen immediately after submit

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#9305] opened 2019-03-28 09:47 UTC
Will be good to lock or gray-out login&passwords fields on login screen immediately after submit form. 

Also will be good to show larger "please wait" info, because now after submit there are only small rotating circle shown in right of headers. Because login time may be very long, many users will not see this circle and think that something broken.

**Comment by jryans** [comment] 2019-03-28 13:18
Thanks for the report! I believe this is a duplicate of https://github.com/vector-im/riot-web/issues/8417.

**Closed by jryans** 2019-03-28 13:18 UTC
