### ISSUE TITLE
I CAN NOT SCROLL ANYWHERE EXCEPT FOR THE SETTINGS PANE!

### ISSUE THREAD

**Issue by MparkG** [vector-im/riot-web#11141] opened 2019-10-14 17:19 UTC
I shall reopen a new issue because i can not set the status of the last one, which @t3chguy so promptly set to closed, without even bothering to concider theres some BUG MENTIONED which he should be working towards getting it fixed.

Here we go:

GO READ FOR YOURSELF!
LOOK INTO YOUR ISSUES!
TAKE NOTE OF THE LABEL "MAJOR" AND "BUG" which you generously added yourselves!
FIX IT!

IN CASE YOU ARE TOO LIMITED TO USE THE SEARCH for an appropriate term;
here you go with the results:
#9777 #10533 #11135 and finally  #8778

I havent seen people so ignorant, yet, as can be seen in these threads!

Hope you can **finally** find time to provide a solution to this.

**Comment by t3chguy** [comment] 2019-10-14 17:21
Closing as duplicate of https://github.com/vector-im/riot-web/issues/9777

Having duplicate issues just wastes time having to manage them

**Closed by t3chguy** 2019-10-14 17:21 UTC
Labels: bug
