### ISSUE TITLE
Allow for fixed custom Jitsi conference room URL

### ISSUE THREAD

**Issue by janvlug** [vector-im/riot-web#12751] opened 2020-03-16 20:59 UTC
Currently, you cannot set the Jitsi URL yourself. I would like to be able to provide a fixed URL myself for the Jitsi integration.

Use case: I work in a team where we have a fixed Jitsi room with a human readable name. This URL is well known by team members. Some team members use also Riot for collaboration. I added the Jitsi integration to our Riot room. During our daily meeting, some people want to join the well-known Jitsi room by using the Riot conference call button. But this does not work, as Riot has its own random Jitsi room. This behaviour led to a lot of confusing of a group split in two over two Jitsi rooms. The ability to manually configure a Jitsi URL for a Riot room would solve this issue.

**Comment by t3chguy** [comment] 2020-03-16 21:05
Duplicate of https://github.com/vector-im/riot-web/issues/5048

**Closed by t3chguy** 2020-03-16 21:05 UTC
Labels: suggestion

**Comment by janvlug** [comment] 2020-03-16 21:30
I saw #5048 and also #5388 before creating this issue. I thought that it would be more clear to create a new suggestion instead of adding my different use case to one of these existing issues.
