### ISSUE TITLE
on login on a new device, i no longer get key backup prompt UIs

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10695] opened 2019-08-30 09:52 UTC
i just installed FF develop edition and logged in on the new profile (at least, i hope it's a new profile). i see UISIs everywhere, but not the banner telling me to engage key backup

**Comment by turt2live** [comment] 2019-08-30 19:45
![image](https://user-images.githubusercontent.com/1190097/64047598-7bf27e80-cb2c-11e9-9945-0fa62d1c9002.png)

._.

**Comment by turt2live** [comment] 2019-08-30 19:49
in fact:
![image](https://user-images.githubusercontent.com/1190097/64047748-de4b7f00-cb2c-11e9-8cfd-94d48c2633b0.png)


@ara4n is it possible "Don't ask me again" got clicked without your knowledge?

**Comment by turt2live** [comment] 2019-09-03 16:10
@ara4n we're taking this off the fire because we can't reproduce it. Are there steps we might have missed?

**Comment by turt2live** [comment] 2020-02-28 21:25
Closing - cannot reproduce still and missing further information. If this is still happening, please open a new issue.

**Closed by turt2live** 2020-02-28 21:25 UTC
Labels: bug, cannot-reproduce, p1
