### ISSUE TITLE
If you're in a room and right-click->forget a historical room the view changes to an entirely different room

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9077] opened 2019-03-07 11:52 UTC
### Description

Quite an annoying bug actually. If you're in some room, and you have a historical room that you want to forget, if you right-click and forget a historical room you will be kicked out of the current room you are looking at and get put in (I believe) the top unread room in your account. Maybe you didn't want to read that room yet, but too bad!

### Steps to reproduce

- Be looking at some room and have another room in your historical list
- Forget that historical room by some means
- Be put in one of your unread rooms after the historical room is forgotten.

Log: not sent

- **Platform**: web
- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment] 2019-03-07 15:02
Duplicate of https://github.com/vector-im/riot-web/issues/2037

**Closed by turt2live** 2019-03-07 15:02 UTC
