### ISSUE TITLE
Quote function is not accessible if message is one line and last in chat

### ISSUE THREAD

**Issue by geleeroyale** [vector-im/riot-web#5897] opened 2017-12-30 13:14 UTC
### Description

When I want to quote the last message in a room, usually the 'quote' option vainshes behind the taskbar

### Steps to reproduce

- Have Riot.im on fullscreen
- Try to quote the last message in the room (might work for multi-line messages, doesn't work for messages that occupy single line)

Coming from Slack, I really miss threading. Quotes are the only way to have parallel 'topics' going. My only workaround now is to make the window smaller - that will show the 'quote' option

Log: sent/not sent?    

![image](https://user-images.githubusercontent.com/317685/34454425-805da512-ed6b-11e7-94b8-d347537a5230.png)

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Windows 10-64
- **Version**: 0.13.3

**Comment by t3chguy** [comment] 2017-12-30 13:36
Duplicate of #3429

**Closed** 2017-12-30 13:36 UTC
