### ISSUE TITLE
call button position during calls

### ISSUE THREAD

**Issue by Flexmaen** [vector-im/riot-web#13691] opened 2020-05-15 20:25 UTC
The button for ending a call is too unobtrusive.

In fact it is where you started the call, but people still get confused because the indication of the active call is far more present, while the button for ending the call is inconspicuously behind the sticker and attachment symbol.

![riot_anruf_usability](https://user-images.githubusercontent.com/6330276/82092774-2d0c6980-96fa-11ea-8311-466daaa50637.png)

**Comment by turt2live** [comment] 2020-05-15 20:37
Duplicate of https://github.com/vector-im/riot-web/issues/8809

**Closed by turt2live** 2020-05-15 20:37 UTC
Labels: bug, ui/ux
