### ISSUE TITLE
[Feature Change] Systray, left click open, right click menu

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#7553] opened 2018-10-25 02:27 UTC
I think this may be a feature regression in the last few months, because I recall it being the way I prefer in an earlier version.

I'm on Ubuntu, with XFCE4, and when I left or right click on the "systray" icon for Riot, both come up with the menu to open/quit.

I think the left click should just open/minimize it (depending on its state), and right click bring up the menu.

It's really annoying having to click on the pull-down menu to open it.

Small change, but would be really appreciated.

Please? :)

**Comment by lampholder** [comment] 2018-11-01 11:40
If this is a change, this could be another unintended side-effect of the electron version bump. Unfortunately I think the systray icon lives in a bit of a blind spot for us - there's no automated testing on it, and I don't know if anyone on the team regularly uses electron on a linux machine with a systray :\

So - thanks for this report, and if anyone has any ideas how we can keep an automated eye on systray behaviour I'd love to hear about them :)

**Comment by banholzer** [comment] 2018-11-06 10:54
I have the same issue and its quite annoying having to click multiple times to show/hide riot.

**Comment by BloodyIron** [comment] 2018-11-06 15:16
Yeah it did use to just be left click to open/close, right click for menu. That worked plenty well for me!

**Comment by gerroon** [comment] 2019-01-26 01:03
This is a harsh drag for the elderly users of Riot.

**Comment by BloodyIron** [comment] 2019-01-26 16:47
still really annoying

**Comment by gerroon** [comment] 2019-01-26 16:54
@BloodyIron,  I need to vnc to my mom's computer and click on Riot for her so that I can talk to her, she cant do it  as of now due to this bug. It is that bad :(

**Comment by Pointedstick** [comment] 2019-02-23 17:31
In KDE Plasma with Riot version 1.0.1 this now works as expected.

**Comment by BloodyIron** [comment] 2019-02-23 18:29
Hmm just tried in XFCE with 1.0.1, still doing the menu thing.

**Comment by pacien** [comment] 2019-04-09 02:54
Looks like a regression in Electron itself: https://github.com/electron/electron/issues/16462, https://github.com/electron/electron/issues/14941, https://github.com/electron/electron/issues/13087.

**Comment by akontsevich** [comment] 2019-06-22 21:28
Think #7553 and #7624 could be closed for now: works fine if libappindicator3 (libappindicator-gtk3) not installed. Unlike #6767 and #8819 (icon look) should be reopened and fixed: stopped to work even if I run with `Exec=XDG_CURRENT_DESKTOP=Unity riot %U`. For now icon looks like blank black square in KDE which is weird. I think local electron version used to build riot should be manually patched like Skype done previous year, where icon looks good for now with whatever appindicator is used or not, Unity desktop set or not. Otherwise we can wait too long it will be fixed in Electron. Makes sense?

**Comment by BloodyIron** [comment] 2019-06-23 14:04
Uhhh? If I left or right click it still brings up the menu. Still very much interested in left click open, right click menu.

**Comment by akontsevich** [comment] 2019-06-23 16:17
Left click open, right click menu works fine for me as expected in suse KDE without libappindicator3 installed. What disto/DE/packages installed do You have?

**Comment by gerroon** [comment] 2019-06-23 16:38
I get the same menu with either left or right or middle clicks. I do not get why Electron changed this behavior on Linux because this works as expected on Windows.

**Comment by MedicMomcilo** [comment] 2019-06-24 06:08
@akontsevich I'm not sure I understand.

If libappindicator is dependency for many programs, how can we uninstall it?
Wouldn't that leave us with unusable DE?

**Comment by akontsevich** [comment] 2019-06-24 13:55
Probably You're right. libappindicator is not a problem only in KDE. In Mate, Cinnamon, etc seems a problem.

**Comment by foresto** [comment] 2020-01-22 22:56
Confirmed on an Xfce desktop (Gtk widgets) that has both the Notification Area and the Indicator Plugin installed on the desktop panel.

It looks like the Riot icon is appearing in the Notification Area, which I think implies that it's using a Gtk StatusIcon rather than a Gtk AppIndicator. I'm not sure what it uses on a Qt desktop like KDE, but surely something different from either of those, which could explain why KDE users are not seeing the bad behavior.

And agreed: Having to fiddle with a menu when I just want to open Riot from the tray icon is an annoying hassle. I should be able to just click the icon, as I do with other apps that have a tray icon.

**Comment by foresto** [comment] 2020-02-20 03:47
This problem also occurs when using xfce's new Status Notifier Plugin.

It's still present in Riot-web 1.5.10.

**Comment by gerroon** [comment] 2020-02-20 04:48
I  think this is Electron shit storm all over again, they constantly f....k stuff.

**Comment by akontsevich** [comment] 2020-02-20 14:00
> This problem also occurs when using xfce's new Status Notifier Plugin.
> It's still present in Riot-web 1.5.10.

For me problem is fixed: https://github.com/electron/electron/issues/13087#issuecomment-589041302 in KDE while `libappindicator3` is not necessary and nor used any more.

**Comment by t3chguy** [comment] 2020-06-05 09:30
I believe this might actually be fixed with the whole electron tray mess right now

**Comment by akontsevich** [comment] 2020-06-05 09:47
It will be broken with this https://github.com/electron/electron/issues/21445 soon again.

**Comment by t3chguy** [comment] 2020-06-05 09:57
Duplicate of https://github.com/vector-im/riot-web/issues/3133

**Closed by t3chguy** 2020-06-05 09:57 UTC
Labels: bug, help-wanted, minor, p2, type:electron, type:trayicon

**Comment by BloodyIron** [comment] 2020-06-05 15:42
@t3chguy this isn't a duplicate of #3133 as we have (until the electron version bump) been able to interact with it. Just not left click show/hide.

**Comment by t3chguy** [comment] 2020-06-05 15:48
They all boil down to the same underlying issues between Electron and your DE/WM, there is no point tracking them as 3 here. There isn't anything Riot can really do about them.

**Comment by BloodyIron** [comment] 2020-06-05 15:49
@t3chguy yeah I see that reading the electron reversion thread. Well, hopefully that brings back the left click convenience functionality.
