### ISSUE TITLE
Useless error message when trying to invite a user to a room they're already in

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#12984] opened 2020-04-01 15:00 UTC
### Description

![image](https://user-images.githubusercontent.com/1342360/78152456-bceba200-7431-11ea-9442-809f594ac82b.png)

Trying to invite Half-Shot to a room he's already in produces this unhelpful error. Only upon inspecting my network logs did I discover the true reason the invite failed.

### Steps to reproduce

- Be in a room with another user
- Try to invite that user to that room

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by aaronraimist** [comment] 2020-04-07 01:11
Duplicate of #12281

**Closed by aaronraimist** 2020-04-07 01:11 UTC
Labels: bug, type:invite
