### ISSUE TITLE
Embeddable version of Riot for a single channel.

### ISSUE THREAD

**Issue by abompard** [vector-im/riot-web#5301] opened 2017-10-16 15:17 UTC
### Description

This is a feature request.

I am writing a webapp that will have a chat component and we would like to use matrix in the backend to connect to Freenode in IRC.
Each page in this webapp will be linked to a single IRC channel.

For the frontend, I have two options: 
- write a frontend
- find a way to embed Riot

I don't think that the Riot app can be embedded at the moment and I would love to see this feature. The chat component, similar to Facebook's chat popups at the bottom of the page, would display the contents of a specified room and allow posting there.

Do you think that it would be feasable and useful? Did you consider this feature before?

Thanks!

**Comment by turt2live** [comment] 2017-10-16 15:20
Related/duplicate of:
* https://github.com/vector-im/riot-web/issues/647
* https://github.com/turt2live/matrix-wishlist/issues/45

**Comment by t3chguy** [comment] 2017-10-16 16:34
Closing for reasons @turt2live outlined

**Closed by t3chguy** 2017-10-16 16:34 UTC
