### ISSUE TITLE
jitsi conf died when switching room

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#7877] opened 2018-12-17 10:54 UTC
happened on experimental but unsure if it's experimental specific

**Comment by bwindels** [comment] 2018-12-17 14:38
Duplicate of https://github.com/vector-im/riot-web/issues/7835 ?

**Comment by lampholder** [comment] 2018-12-20 11:24
Looks like a dup to me

**Closed by lampholder** 2018-12-20 11:24 UTC
