### ISSUE TITLE
'start chat'  turn up as a normal room.

### ISSUE THREAD

**Issue by gagarine** [vector-im/riot-web#5145] opened 2017-10-02 11:31 UTC
### Description

Clicking on the "start chat" create a normal room.
![screen shot 2017-10-02 at 13 22 00](https://user-images.githubusercontent.com/164074/31075402-9ee14318-a775-11e7-97dc-155d3f8447a0.png)

### Steps to reproduce

- Click on start a chat
- enter an email
- a room is created (see screenshot)

![screen shot 2017-10-02 at 13 30 21](https://user-images.githubusercontent.com/164074/31075452-de5e71fa-a775-11e7-8726-060f4ec67814.png)

Instead a direct conversation should be created.

### Version information
- **OS**: MacOS
- **Version**: Version 0.12.4 (0.12.4)

**Comment by gagarine** [comment] 2017-10-02 11:31
Linked to #5122

**Comment by turt2live** [comment] 2017-10-02 13:19
Duplicate of https://github.com/vector-im/riot-web/issues/2794

**Comment by uhoreg** [comment] 2017-10-02 14:46
closing as dup of #2794

**Closed by uhoreg** 2017-10-02 14:46 UTC
