### ISSUE TITLE
Regression in 1.2.4: tray icon is now tiny in KDE Plasma

### ISSUE THREAD

**Issue by bugger11** [vector-im/riot-web#10347] opened 2019-07-15 19:30 UTC
### Description

After upgrading from 1.2.3 to 1.2.4 the icon of Riot is not visible in the taskbar. In the prior version the Riot systray icon was visible, the same size as the other icons, and showed an unread message count. In 1.2.4, the icon is an electron icon with a tiny, tiny Riot icon inside it, and there is no message count.

### Steps to reproduce

- The only step I performed was a system update in Arch Linux. In Arch, which is a rolling release, all packages have to be updated together. I updated several different computers, and Riot has the same tiny systray icon issue on all of them after the update.

Describe how what happens differs from what you expected.

- I like the new updates. Would love the functional system tray icon back, too.
- This seems similar to the old issue #7555
- It does not (to me) seem related to issue #9897

Logs being sent: no (no errors show up in the logs)

![Screenshot_20190715_151615](https://user-images.githubusercontent.com/45881879/61243205-732d2100-a715-11e9-9272-4f3ced23ace7.png)

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.2.4

**Comment by turt2live** [comment] 2019-07-15 19:43
Duplicate of https://github.com/vector-im/riot-web/issues/7555

**Closed by turt2live** 2019-07-15 19:43 UTC
Labels: bug
