### ISSUE TITLE
'today' bar is shown when replying to message from previous day

### ISSUE THREAD

**Issue by ericmigi** [vector-im/riot-web#12885] opened 2020-03-26 04:31 UTC
### Description

Confusingly, when someone replies to a message from yesterday right around midnight, 'today' and 'yesterday' are right next to each and I can't tell which way time is going. Maybe replies don't need those bars? 

![image](https://user-images.githubusercontent.com/1048265/77610331-a1d3dc00-6edf-11ea-8a32-0fe991ee0ab2.png)

### Steps to reproduce

get a friend to reply to one of your messages from yesterday today

### Version information

- **Platform**: web (in-browser) or desktop?
ubuntu 18.04 chrome - riot.im/app

**Comment by jryans** [comment] 2020-03-26 10:16
Thanks for the report! I believe it's a duplicate of https://github.com/vector-im/riot-web/issues/9217, but please reopen if not.

**Closed by jryans** 2020-03-26 10:16 UTC
Labels: bug, ui/ux
