### ISSUE TITLE
Read receipts are sometimes invisible because they are on top of each other

### ISSUE THREAD

**Issue by zzottel** [vector-im/riot-web#10587] opened 2019-08-17 22:09 UTC
Seen in Riot Web 1.3.3:
![DeepinBildschirmfoto_Bereich auswählen_20190817235522](https://user-images.githubusercontent.com/1236369/63217748-137ac900-c14c-11e9-82e0-71df4943005b.png)

The issue seems to be that some of the avatars are shown on top of each other, see these screenshot from tulir:
![tulir1](https://user-images.githubusercontent.com/1236369/63217817-4b364080-c14d-11e9-9ed2-2444f8d12041.png)

![tulir](https://user-images.githubusercontent.com/1236369/63217764-53da4700-c14c-11e9-8597-e6d0732d69a9.png)

**Comment by jryans** [comment] 2019-09-04 12:18
Thanks for the feedback. I believe this is a duplicate of https://github.com/vector-im/riot-web/issues/9769, so we can track it over there.

**Closed by jryans** 2019-09-04 12:18 UTC
Labels: bug
