### ISSUE TITLE
Copy pasting multiple messages doesnt work

### ISSUE THREAD

**Issue by GriffGreen** [vector-im/riot-web#5892] opened 2017-12-28 09:17 UTC
### Description

If I try to copy multiple messages from the Riot Desktop App Version 0.13.3 (0.13.3) on macOS 10.12.6 and then paste it in the message box, it doesn’t show up.

### Steps to reproduce

- highlight multiple messages 
- Ctrl-c
- Ctrl-V in the message box

Describe how what happens differs from what you expected.

it should paste in, but it doesnt, instead i get this error

invariant.js:38 Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at r (file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:1:15471)
    at t.getEntity (file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:39:24858)
    at file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:129:10490
    at file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:24:20748
    at file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:12:31466
    at je.__iterate (file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:12:18411)
    at je.reduce (file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:12:31423)
    at n (file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:24:20709)
    at t.findEntityRanges (file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:15:22098)
    at t.value (file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:129:10412)
    at file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:94:20707
    at Array.forEach (native)
    at e.getDecorations (file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:94:20616)
    at Object.generate (file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:63:4769)
    at file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:11:6534
    at file:///Applications/Riot.app/Contents/Resources/webapp/bundles/218c3cb214d7e7acc7d4/bundle.js:11:27886

### Version information

For the desktop app:
 Riot Desktop App Version 0.13.3 (0.13.3) on macOS 10.12.6 

P.S. Gratitude to @gelee_royal for trying to help me with this and showing me where to put the issue

**Comment by t3chguy** [comment] 2017-12-28 10:23
Duplicate of #4926

**Closed** 2017-12-28 10:24 UTC
