### ISSUE TITLE
clicking on emoji loses focus

### ISSUE THREAD

**Issue by betz** [vector-im/riot-web#5677] opened 2017-11-23 17:03 UTC
Describe here the problem that you are experiencing, or the feature you are requesting.
When clicking on a emoji, the focus of the textfield is lost.
This means you have to click back on the textfield after clicking on a emoji.
Smaller issue, but breaks the flow.

**Comment by turt2live** [comment] 2017-11-23 17:31
Duplicate of https://github.com/vector-im/riot-web/issues/5078

**Closed** 2017-11-23 17:33 UTC

**Comment by betz** [comment] 2017-11-23 17:51
sorry. i did search before submitting a new one, but with the word emoji.
