### ISSUE TITLE
Option to disable viewing typing notifications

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#11896] opened 2020-01-17 02:54 UTC
<img width="415" alt="Screenshot 2020-01-17 at 02 54 44" src="https://user-images.githubusercontent.com/1294269/72580680-bccd1300-38d4-11ea-8136-a5d5ddf9618c.png">

**Comment by aaronraimist** [comment] 2020-01-17 04:03
Duplicate of #7283

**Closed by aaronraimist** 2020-01-17 04:03 UTC
Labels: mozilla, suggestion
