### ISSUE TITLE
Super compact mode

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#11862] opened 2020-01-15 14:30 UTC
Currently, compact more isn't very compact.  Degrees of compactness - especially more compact than the current compact mode - would be very appreciated: especially less vertical space between communities in the bar to the left, and between lines in the chat pane.

**Comment by aaronraimist** [comment] 2020-01-15 20:39
Thanks @Biep. I'm going to close this as a duplicate of #6982 and #4363 so feel free to thumbs up those.

**Closed by aaronraimist** 2020-01-15 20:39 UTC
Labels: suggestion
