### ISSUE TITLE
Dropdown "..." menu on messages can end up displaying below bottom of screen.

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/riot-web#6848] opened 2018-06-07 08:59 UTC
This is currently occurring on riot.im/develop:

When I click the "..." on a reply at the bottom of the screen, I get this:

![menu](https://user-images.githubusercontent.com/1917473/41089145-08d4122e-6a39-11e8-93c9-4c7b48f7eebe.png)

I'm then unable to use reply to that message as the "reply" option is below the bottom of the screen.

My suggested solution would be to pop the menu up higher on the page if the bottom of the menu is below the bottom of the screen.

**Comment by t3chguy** [comment] 2018-06-07 09:08
> I'm then unable to use reply to that message as the "reply" option is below the bottom of the screen.

heh glad people are using it ;)

*BUT* Duplicate of https://github.com/vector-im/riot-web/issues/3429

**Comment by t3chguy** [comment] 2018-06-07 09:09
annoyingly with a stalled PR :(
https://github.com/matrix-org/matrix-react-sdk/pull/1727

**Closed by t3chguy** 2018-06-07 09:08 UTC
