### ISSUE TITLE
Multiple mentions autocompletion UX

### ISSUE THREAD

**Issue by smichel17** [vector-im/riot-web#11729] opened 2019-12-27 17:13 UTC
Polari, the GNOME IRC client, has the best mention autocompletion UX, that I'd love for Riot to emulate.

- In both Polari and Riot, when you mention someone at the start of the message and tab-complete it, their name (pilled in Riot) is followed by a colon and a space.
- In Riot, when you tab-complete a second person's name immediately afterward, it simply pills it, as if you were mentioning them in the middle of a sentence.
- In Polari, it will add a colon after the second person's name, *and change the first colon to a comma.*

Here is a screencast of the polari behavior (it's annoyingly blurry unless viewed at native resolution, sorry about that):

![polari mentions screencast](https://user-images.githubusercontent.com/6563664/71525617-77529280-28a0-11ea-93e9-4557c89e2d14.gif)

And here is [polari's autocompletion code](https://gitlab.gnome.org/GNOME/polari/blob/master/src/tabCompletion.js#L199-232) (GPLv2)

I know it seems like a minor feature, but I use it so much that it's seriously important to the UX for me; it's pretty much the sole feature keeping me split between Riot and Polari, rather than using Riot exclusively. Please, go try it yourself; the screencast doesn't really do it justice. It's the kind of thing where, after you've used it, it's so glaringly obvious that this is the Right Way To Do It™ that you wonder how anybody did it any other way before. Like microwaves that combine the start and minute plus button.

**Comment by turt2live** [comment] 2019-12-27 17:16
Duplicate of https://github.com/vector-im/riot-web/issues/4883

**Comment by smichel17** [comment] 2019-12-27 17:17
Ack, I did search first, but didn't find that one :(

**Closed by turt2live** 2019-12-27 17:16 UTC
Labels: suggestion
