### ISSUE TITLE
Mark all as readed buttom

### ISSUE THREAD

**Issue by jitka** [vector-im/riot-web#11532] opened 2019-11-27 10:16 UTC
**Is your suggestion related to a problem? Please describe.**
When I miss long discussion and then I scan it or read quickly, messages are still marked as unreaded.

**Describe the solution you'd like**
Put button all readed just under the arrow up which is used for moving in discussion as well for notifiing that some messages are unreaded.

**Describe alternatives you've considered**
Any other 'mark as a readed' options.

**Comment by turt2live** [comment] 2019-11-27 16:05
Duplicate of https://github.com/vector-im/riot-web/issues/850

**Closed by turt2live** 2019-11-27 16:05 UTC
Labels: suggestion
