### ISSUE TITLE
GIFs now autoplay even if you've disabled the setting to do so

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#9658] opened 2019-05-09 08:45 UTC
regression.

**Comment by turt2live** [comment] 2019-05-09 13:57
I'm not able to reproduce this - was it a sticker by chance? (making it a duplicate of https://github.com/vector-im/riot-web/issues/6534)

**Comment by uhoreg** [comment] 2019-05-09 16:18
I'm seeing this too, ever since I upgraded to 1.1.0.  It happens with non-stickers.

**Comment by jryans** [comment] 2019-05-10 17:37
I am seeing this also, will investigate...

**Comment by turt2live** [comment] 2019-05-10 17:39
My testing was flawed I guess, as I can reproduce it now too. Possibly tested against an outdated version of Riot?

**Comment by jryans** [comment] 2019-05-13 17:31
The regression was caused by https://github.com/matrix-org/matrix-react-sdk/pull/2439.

**Closed** 2019-05-14 13:08 UTC
Labels: bug, regression
