### ISSUE TITLE
emoji reactions in riot-web look to be sending black & white rather than colour emoji variants again

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14446] opened 2020-07-13 15:46 UTC

**Comment by ara4n** [comment] 2020-07-13 15:47
or alternatively the New Theme is mangling the font ordering somehow and preferring monochrome ones over twemoji?

**Comment by turt2live** [comment] 2020-07-13 15:48
Duplicate of https://github.com/vector-im/riot-web/issues/14398

**Comment by turt2live** [comment] 2020-07-13 15:48
(yes, it is)

**Closed by turt2live** 2020-07-13 15:48 UTC
