### ISSUE TITLE
Room list is not moving rooms with unread to the start of the list

### ISSUE THREAD

**Issue by Standard8** [vector-im/riot-web#13717] opened 2020-05-19 17:44 UTC
### Description

The room list highlights the rooms that have messages, but generally fails to move them to the top of the list.

### Steps to reproduce

- I have both "order rooms by name" and show rooms with unread notifications first" turned on
- Load up the desktop client.
- Go into Settings, Help & about and select "Clear cache and reload"
- If you have rooms with unread, some of them might be at the top.
- Wait for a bit to get more messages in.

At this stage, the rooms with more unread don't get moved to the top.

Logs being sent: yes/no

### Version information

- **Platform**: desktop

- **OS**: macOS
- **Version**: 1.6.1

I also have the RiotX client installed on mobile. Using the mozilla.org server.

**Comment by LunarTwilight** [comment] 2020-05-19 22:14
This is happening for me too on Windows 10 on riot 1.6.1

**Comment by turt2live** [comment] 2020-05-28 18:19
Duplicate of https://github.com/vector-im/riot-web/issues/9216

**Closed by turt2live** 2020-05-28 18:19 UTC
Labels: bug
