### ISSUE TITLE
Inter font broke :arrow_up:

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#14494] opened 2020-07-15 17:36 UTC
now it looks like a white character

![image](https://user-images.githubusercontent.com/2403652/87577015-24202000-c6ca-11ea-976a-420ebb372d7a.png)

Before:
![image](https://user-images.githubusercontent.com/2403652/87577018-26827a00-c6ca-11ea-89e3-2bf6822a8f95.png)

**Comment by turt2live** [comment] 2020-07-15 17:37
Duplicate of https://github.com/vector-im/riot-web/issues/14398

**Closed by turt2live** 2020-07-15 17:37 UTC
