### ISSUE TITLE
trying to pop a jitsi widget out of its frame doesn't work any more

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12811] opened 2020-03-20 14:29 UTC
on firefox at least, it leaves the existing widget in place; the new tab can't open the camera(?), and things then get stuck in a strange state with no overlay in the iframed widget

**Comment by turt2live** [comment] 2020-03-20 15:38
I don't think this ever worked.

**Comment by t3chguy** [comment] 2020-03-31 13:26
It did work, people happily used it to pop out from Electron into browser to screen share. (including me seldom)

**Comment by t3chguy** [comment] 2020-03-31 13:26
Now the issue is much worse as it is guaranteed to fail as jitsi.html only works in a riot-web iframe due to its postMessage requirement.

**Comment by cw789** [comment] 2020-03-31 13:40
With the release of v1.5.14 this problem occurs also at my place.
But not only in Firefox also in Edge.

Problem description:
Within the pop out browser tab the click on "Join Conference" does nothing.
Without any console logs or anything else helpful for me to debug the problem.

Was still working in with v1.5.13 in Firefox.

**Comment by DJCrashdummy** [comment] 2020-03-31 13:47
in my case with riot-web <1.5.14 everything worked fine, even in firefox... video-chat, screen-sharing, within riot-web and even after poping-out the widget.
now after upgrading to 1.5.14 e.g. the jitsi widget still works within riot-web, but as soon i pop it out to its own tab, i can't even join the conference. :frowning_face: 

*not to mention, that - with this tiny widget window i'm forced to use now - it is kind of useless, especially the screensharing.* :disappointed:

**Comment by DJCrashdummy** [comment] 2020-03-31 14:08
i'm not 100% sure - i never timed it - but also within riot-web it seems that actually entering a conference (after clicking on "join conference") takes a good amount longer than it took until now... :thinking:

**Comment by dbkr** [comment] 2020-04-01 13:27
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/4319

**Closed by dbkr** 2020-04-01 13:27 UTC
Labels: bug, regression, type:jitsi, 🔥 Fire 🔥

**Comment by DJCrashdummy** [comment] 2020-04-11 08:25
> i'm not 100% sure - i never timed it - but also within riot-web it seems that actually entering a conference (after clicking on "join conference") takes a good amount longer than it took until now... :thinking:

indeed... at least some users reported to me, that it now takes longer to enter a conference - even after it works in a standalone tab again - than it took before.

perhaps it is not a riot, but a jitsi thing? ...or somehow related to https://github.com/jitsi/jitsi-meet/issues/4758?
