### ISSUE TITLE
Room with notifications is only bolded until it is clicked on when joining the room externally

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#13599] opened 2020-05-08 14:07 UTC
### Description

If you are invited to a room, and join that room via `curl` or the "Bulk join" button in Settings->Security & Privacy, then that room will only be bolded until clicking on it in Riot, in which case notification numbers start appearing.

I'm not sure whether this is a bug in Riot's notification processing, or if Synapse sets up a push rule when receiving the first read receipt.

### Steps to reproduce

- Have someone invite you to a room
- Accept without looking at the room in Riot (using "Bulk join" in Settings->Security & Privacy, or curl, etc)
- Have the other person send messages in the room
- Get notifications with the messages, but see the room is only bolded in the sidebar
- Click on the room in Riot, then go to another room
- Have the other person send more messages in the room
- See numbers in the room sidebar, as you'd expect

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment] 2020-05-08 15:32
Duplicate of https://github.com/vector-im/riot-web/issues/8016

**Closed by turt2live** 2020-05-08 15:32 UTC
Labels: bug
