### ISSUE TITLE
Repository update overwrites config.json with default

### ISSUE THREAD

**Issue by jacotec** [vector-im/riot-web#7207] opened 2018-08-21 11:37 UTC
Just did an update from riot-web 0.16.0 to 0.16.1 via the Debian/Ubuntu repository. The update did overwrite my config.json with the default file and all my customized changes were gone.

Updates should not overwrite the config without any confirmation. The best would be to have a "sample_config.json" in the repo which a user can use as a starting point (or where new config options can be added and commented), but taking the "hot" config.json out of the repo.

**Comment by t3chguy** [comment] 2018-08-21 12:26
`config.json` is a build config not a user config so yes it is expected that it is overwritten on update.
Also a dup

Closing as duplicate of https://github.com/vector-im/riot-web/issues/4394

**Closed by t3chguy** 2018-08-21 12:26 UTC
