### ISSUE TITLE
Insanely long og:description gets shown in entirety and causes message to flicker

### ISSUE THREAD

**Issue by alexgleason** [vector-im/riot-web#4006] opened 2017-05-23 19:25 UTC
### Description

When sharing a link with a super long og:description, Riot displays it in its entirety. This causes the message to flicker on the screen, and attempting to scroll up forces the scrollbar back to the bottom after a second.

### Steps to reproduce

- Open any room on Riot desktop
- Paste this URL into the message https://www.eff.org/issues/tpp
- See the message flicker incessantly and scrolling up is not possible

### Version information

- **Platform**: desktop, nothing else tested

For the desktop app:

- **OS**: elementary OS (based on Ubuntu 16.04)
- **Version**: 0.9.9

**Comment by t3chguy** [comment] 2017-05-23 19:26
closed by matrix-org/synapse/pull/2243

**Closed by t3chguy** 2017-05-23 19:26 UTC

**Comment by alexgleason** [comment] 2017-05-23 19:28
Hmm is this something Riot should deal with too, not just Synapse? Say an alternative server implementation doesn't truncate it, it's wrong to show that to the user either way.

**Comment by t3chguy** [comment] 2017-05-23 19:30
Sure, then duplicate of #2894

**Comment by alexgleason** [comment] 2017-05-23 19:31
Thank you!
