### ISSUE TITLE
ctrl+a to select the whole text in the input area on develop with the rte doesn't work.

### ISSUE THREAD

**Issue by aviraldg** [vector-im/riot-web#2257] opened 2016-09-17 14:52 UTC
on ff45, only in rich text mode, with multiple blocks of content

**Comment by t3chguy** [comment] 2017-05-13 13:31
FF45 is somewhat dated now, cannot reproduce on FF53

**Comment by t3chguy** [comment] 2017-10-25 16:04
Closing in favour of https://github.com/vector-im/riot-web/issues/4935

**Closed by t3chguy** 2017-10-25 16:04 UTC
Labels: bug, minor, p2, platform specific, type:rte
