### ISSUE TITLE
Make Markdown formatting disableable again

### ISSUE THREAD

**Issue by rohieb** [vector-im/riot-web#11924] opened 2020-01-17 22:31 UTC
### Description

Since CIDER is the only composer now in riot-web, it is apparently no longer possible to disable formatting completely. I've never felt the need for formatting in messaging apps at all, and want my keystrokes to appear like I wrote them. Now I have to first remember which characters I have to escape in the message, invest additional time to escape them (if it is at all possible, see #11230), and can no longer chat as quickly as before, so this is a regression for me.

Please re-introduce a setting to disable formatting in the new composer, preferrably as a global per-user setting.

### Steps to reproduce

* Use the new composer to send a message which includes characters used in Markdown formatting, e.g.: ``*dances across the room*``, ASCII smileys like ``>_>``, or random code snippets.

### Version information
- **Browser**: Firefox 72.0.1
- **OS**: Debian unstable
- self-hosted riot-web version: 1.5.7

**Comment by aaronraimist** [comment] 2020-01-17 22:49
Duplicate of #483, please thumbs up that one

**Closed by aaronraimist** 2020-01-17 22:49 UTC
Labels: bug

**Comment by aaronraimist** [comment] 2020-01-17 22:50
> Now I have to first remember which characters I have to escape

Also a better workaround is to start your message with `/plain` rather than escaping individual characters

**Comment by rohieb** [comment] 2020-01-17 22:55
> Duplicate of #483, please thumbs up that one

Oh thanks, that was unexpectedly far down the list, no wonder I didn't find it ^^
