### ISSUE TITLE
Element in Ubuntu can't become a favourite

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#14701] opened 2020-07-22 11:45 UTC
When trying to pin Element to the dash, the option is missing from the righ-click menu (for me, not for all).  Someone else is using Dash-to-panel and has issues there too.  See [this message](https://matrix.to/#/!uGTCmJuKfnAYNPNsZz:matrix.org/$bbbIV2blbWdMM5VOzc62upK0ko6SS2u3Uee8Wv-pMfc?via=matrix.org&via=mozilla.org&via=tchncs.de) and the sequel.

**Comment by t3chguy** [comment] 2020-07-22 11:46
Duplicate of solved https://github.com/vector-im/riot-web/issues/14619

**Closed** 2020-07-22 11:46 UTC

**Comment by Biep** [comment] 2020-07-22 11:49
My issue is different - I don't see any double icon, nor do I use dash-to-dock or any other dash addition or replacement.

**Comment by t3chguy** [comment] 2020-07-22 11:52
The cause is the same though.

**Comment by Biep** [comment] 2020-07-22 11:53
OK, if the patch solves it I'll wait for it to become stable.  Am on 1.7.1. currently.
