### ISSUE TITLE
Enable forwarding uploaded files

### ISSUE THREAD

**Issue by aurabindo** [vector-im/riot-web#3663] opened 2017-04-20 04:03 UTC
### Description

Make it possible to forward a particular file to different user once uploaded. This will reduce the duplication of data when I would want to send to different people who are not available though one group.

There is no forward option in Riot Web. Currently the forward option in Android app uploads a new version of the file. It would be faster experience for the user if forward option always reuse the uploaded file being forwarded.

**Comment by t3chguy** [comment] 2017-04-20 10:29
Duplicate of #3592

**Closed** 2017-04-20 10:32 UTC

**Comment by aurabindo** [comment] 2017-04-20 11:57
hmm the title of the referenced issue had `fwd` instead of `forward`, which is why I should have missed the original issue when searching
