### ISSUE TITLE
Ability to drag own video in video call

### ISSUE THREAD

**Issue by TheLastProject** [vector-im/riot-web#3635] opened 2017-04-15 23:53 UTC
### Description

Unlike on Android, your own video preview cannot be moved around. This makes it possible for the other person to end up behind your preview with no way to see them except telling them to move.

### Version information
- **Platform**: Desktop
- **OS**: Fedora
- **Version**: 0.9.7

**Comment by t3chguy** [comment] 2020-03-19 14:26
Duplicate of https://github.com/vector-im/riot-web/issues/1668

**Closed by t3chguy** 2020-03-19 14:26 UTC
Labels: feature, p2, type:voip, ui/ux
