### ISSUE TITLE
"This server does not accept room invites" should be displayed to the user.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#7681] opened 2018-11-10 16:22 UTC
...rather than the generic "The server might be down, overloaded or you hit a bug". None of those are actually true.

The error in question is my server complaining that the remote isn't accepting my invites over federation, I believe.

**Comment by turt2live** [comment] 2018-11-11 17:18
Duplicate of https://github.com/vector-im/riot-web/issues/4062

(given the failure is "invites that go wrong are cryptic")

**Closed by turt2live** 2018-11-11 17:18 UTC
