### ISSUE TITLE
Cannot accept invites

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4518] opened 2017-07-05 22:07 UTC
### Description

I join the room, but get an infinite spinner at the top until a page refresh.

```
rageshake.js:65 Caught /sync error TypeError: Cannot read property 'userId' of null
    at https://riot.im/develop/bundles/46db56eda6d4b8d666a7/bundle.js:65395:58
    at https://riot.im/develop/bundles/46db56eda6d4b8d666a7/bundle.js:172843:15
    at arrayMap (https://riot.im/develop/bundles/46db56eda6d4b8d666a7/bundle.js:30204:22)
    at https://riot.im/develop/bundles/46db56eda6d4b8d666a7/bundle.js:172842:21
    at https://riot.im/develop/bundles/46db56eda6d4b8d666a7/bundle.js:77547:24
    at https://riot.im/develop/bundles/46db56eda6d4b8d666a7/bundle.js:173290:12
    at baseMap (https://riot.im/develop/bundles/46db56eda6d4b8d666a7/bundle.js:77546:4)
    at baseOrderBy (https://riot.im/develop/bundles/46db56eda6d4b8d666a7/bundle.js:172841:17)
    at https://riot.im/develop/bundles/46db56eda6d4b8d666a7/bundle.js:78195:11
    at apply (https://riot.im/develop/bundles/46db56eda6d4b8d666a7/bundle.js:172020:26)
```

### Steps to reproduce

- Accept an invite

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 58
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment] 2017-07-06 09:30
I can reproduce this.

After refreshing on the infinite spinner I do then end up inside the room.

**Comment by lukebarnard1** [comment] 2017-07-06 10:54
@lampholder logs plz?

**Comment by lukebarnard1** [comment] 2017-07-07 19:04
Possible fix for this merged, let's wait and see if it's fixed. Also let's make a test for accepting invites etc.

**Comment by turt2live** [comment] 2017-07-07 22:15
I still can't accept invites while running /develop with that patch

**Comment by ara4n** [comment] 2017-07-07 22:58
what error do you get? it works for me...

**Comment by turt2live** [comment] 2017-07-08 00:25
It does actually seem fixed, I just wasn't patient enough. Took several minutes to join the room, but I'm comfortable with blaming my VPS for that.

**Comment by lukebarnard1** [comment] 2017-07-10 08:36
Closing this, as https://github.com/matrix-org/matrix-react-sdk/issues/1200 seems to have fixed it

**Closed by lukebarnard1** 2017-07-10 08:36 UTC
Labels: bug, major, p1, release-blocker
