### ISSUE TITLE
emoji one can't handle iOS12-style emoji, and fails to zoom them if on a single line

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7743] opened 2018-11-24 23:48 UTC
for instance, 👨‍✈️ is apparently an airplane captain. but is rendered as two emoji and not zoomed to large size if entered on a single line in Riot/Web

**Comment by aaronraimist** [comment] 2018-11-25 03:16
I assume this is caused by the old version of Emoji One that is being used in Riot not having the recent versions of the zero width joiner sequences http://unicode.org/emoji/charts/emoji-zwj-sequences.html (and not having drawings for the recently added emoji).

This can either be fixed by either upgrading emoji one (#7354) or getting rid of it (or allowing it to be disabled) (#7356).

I vote for getting rid of it and just showing the user's emoji.

**Comment by t3chguy** [comment] 2018-11-25 07:14
Indeed

**Closed** 2018-11-25 07:14 UTC
