### ISSUE TITLE
Save button gives zero UI feedback when adding/removing aliases in RoomSettings

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8783] opened 2019-02-19 13:53 UTC
There's no spinner, and the Save button doesn't transition to green->grey to show that stuff has been saved.  This is basically the same as https://github.com/vector-im/riot-web/issues/8581, and related to https://github.com/vector-im/riot-web/issues/8569 but i'd prefer we tracked it as a first class bug as it's really really bad UX.

**Comment by turt2live** [comment] 2019-02-19 15:05
This is also duplicate of several other issues with aliases. The component needs work as a whole because it doesn't match the theme at all.

The save button is intended to disappear.

**Comment by turt2live** [comment] 2019-02-22 16:41
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2679

**Closed by turt2live** 2019-02-22 16:41 UTC
