### ISSUE TITLE
Click on tray icon to bring to front does not work on Linux

### ISSUE THREAD

**Issue by gerroon** [vector-im/riot-web#7624] opened 2018-10-29 18:24 UTC
Hi

Please add the single click on the tray icon to bring the main window to front. 

This is such a big issue for elderly people. Please imagine elderly person trying to open the main Riot window via the tray icon, this is so painful for people with vision or joint pain issues using the mouse. It would be nice if a single click would just bring the window to the front.

thanks

**Comment by ejpcmac** [comment] 2018-10-30 09:37
Not only for old people, I’m a young guy and I find this pretty annoying not to be able to use the tray icon to show and hide the window. This is a regression.

**Comment by preemeijer** [comment] 2018-10-31 15:08
Within a KDE environment you have 2 single clicks to bring up the main Riot window (when closed).
When clicking on the tray icon (left or right mouse button) I get the option: Show / Hide Riot

**Comment by ejpcmac** [comment] 2018-10-31 15:25
@preemeijer So this issue occurs in Gnome. Something I have noticed: when starting Riot, the system tray shows up but Riot’s icon is empty. Clicking on this empty place shows / hides Riot. After hiding and showing again *the system tray*, Riot’s icon is OK, but clicking on it does nothing.

I have Gnome Shell `3.24.3`.

**Comment by gerroon** [comment] 2018-10-31 15:52
I use Lxpanel under Fluxbox. Every other tray icon works with a single click, Riot's icon brings a pulldown menu with open, close when clicked on the icon

**Comment by Extarys** [comment] 2018-12-13 08:07
Glad I'm not the only one annoyed with this.

**Comment by LuNiKoFf** [comment] 2018-12-31 10:47
Same problem with Awesome WM and XFCE.

**Comment by Flakebi** [comment] 2019-01-26 00:35
This issue looks like it is the same as #7553. I would also like to have this fixed :).

**Comment by gerroon** [comment] 2019-01-26 01:11
@Flakebi 

I don't think the proposed solution works for this like setting XDG_CURRENT_DESKTOP

They might be talkign about something else

**Comment by escafandra** [comment] 2019-02-17 04:11
Yes, I can confirm that. I use Riot on Debian Stretch with Gnome Shell and the Riot Icon in the Tray shows up but it's useless, I cannot click on it to bring Riot back.

**Comment by gerroon** [comment] 2019-02-17 04:39
Joplin uses Electron and that one has no issue with it.

**Comment by ecofintech** [comment] 2019-03-26 17:00
Same issue, in Debian stretch Kde the tray icon appears very small and doesn't work when cliking on it.... any idea how to fix it?

**Comment by akontsevich** [comment] 2019-06-22 21:28
Think #7553 and #7624 could be closed for now: works fine if libappindicator3 (libappindicator-gtk3) not installed. Unlike #6767 and #8819 (icon look) should be reopened and fixed: stopped to work even if I run with `Exec=XDG_CURRENT_DESKTOP=Unity riot %U`. For now icon looks like blank black square in KDE which is weird. I think local electron version used to build riot should be manually patched like Skype done previous year, where icon looks good for now with whatever appindicator is used or not, Unity desktop set or not. Otherwise we can wait too long it will be fixed in Electron. Makes sense?

**Comment by gerroon** [comment] 2019-06-22 22:46
" works fine if libappindicator3 (libappindicator-gtk3) not installed" 

Not true I do not have that file, and I unintalled the appindicator lib and still does not work, at least on Debian Buster

**Comment by akontsevich** [comment] 2019-06-23 01:25
Hmm, works for me in KDE, openSUSE. Actually libappindicator-gtk3 is a dependency for many Gnome, GTK3 apps, if not all. Could have different name in Debian.

**Comment by gerroon** [comment] 2019-06-23 01:54
Ok thanks I will take a look at it. I am using Xfce

**Comment by t3chguy** [comment] 2020-06-05 09:57
Duplicate of https://github.com/vector-im/riot-web/issues/3133

**Closed by t3chguy** 2020-06-05 09:57 UTC
Labels: bug, minor, p2, platform specific, type:electron
