### ISSUE TITLE
expanded read receipts gets covered by message box

### ISSUE THREAD

**Issue by tleydxdy** [vector-im/riot-web#8448] opened 2019-02-07 15:21 UTC
### Description

screenshot:
![image](https://user-images.githubusercontent.com/10610765/52421385-d58d5000-2aeb-11e9-9d35-883f0ab18089.png)

### Steps to reproduce

 - expand read receipts
 - try to click them

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox
- **OS**: GNU/Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment] 2019-02-08 19:32
Duplicate of https://github.com/vector-im/riot-web/issues/7608

**Closed by turt2live** 2019-02-08 19:32 UTC
