### ISSUE TITLE
Video call doesn't work on Mac Desktop app

### ISSUE THREAD

**Issue by ghost** [vector-im/riot-web#2695] opened 2016-12-05 16:55 UTC
Hello

I can see this error on js console : 

```
CallHandler.js:102 Call error: Error: Couldn't start capturing media! Is your microphone set up and does this app have permission?
    at v (file:///Volumes/Riot%200.9.0/Riot.app/Contents/Resources/app/webapp/bundle.04620ef3680f25f0f39c.js:127:26541)
    at r._getUserMediaFailed (file:///Volumes/Riot%200.9.0/Riot.app/Contents/Resources/app/webapp/bundle.04620ef3680f25f0f39c.js:127:22321)
    at file:///Volumes/Riot%200.9.0/Riot.app/Contents/Resources/app/webapp/bundle.04620ef3680f25f0f39c.js:127:28658(anonymous function) @ CallHandler.js:102
CallHandler.js:103 Error: Couldn't start capturing media! Is your microphone set up and does this app have permission?
    at v (call.js:1049)
    at r._getUserMediaFailed (call.js:727)
    at call.js:1188(anonymous function) @ CallHandler.js:103

```

thanks

**Comment by ara4n** [comment] 2016-12-20 02:16
@ghost - i think this has been fixed now; at least i can't reproduce it on 0.9.2.  Please can you try the latest & greatest, and reopen if it's still borked?

**Comment by ara4n** [comment] 2017-01-15 11:17
apparently 0.9.6 still exhibits this for you. what macos version is this?

**Comment by ara4n** [comment] 2017-01-16 15:51
now fixed properly in 0.9.6 final.

**Comment by ara4n** [comment] 2017-03-10 23:39
apparently this is still a problem for @ghost. please say precisely which version of macOS and Riot/Desktop this is with, and if the JS console shows the same error.

**Comment by thalieht** [comment] 2018-12-27 15:55
ghost is the placeholder name for deleted accounts on github.

**Comment by adam-tibbetts** [comment] 2019-05-13 22:02
I'm having this issue, here's the JS console:

`rageshake.js:107 Call error: Error: Couldn't start capturing media! Is your microphone set up and does this app have permission?
    at b (vector://vector/webapp/bundles/656af275775e44773b89/bundle.js:30:86707)
    at u._getUserMediaFailed (vector://vector/webapp/bundles/656af275775e44773b89/bundle.js:30:82228)
    at u._maybeGotUserMediaForInvite (vector://vector/webapp/bundles/656af275775e44773b89/bundle.js:30:78703)
    at vector://vector/webapp/bundles/656af275775e44773b89/bundle.js:30:88878
e.(anonymous function) @ rageshake.js:107
(anonymous) @ CallHandler.js:308
n.emit @ events.js:81
u._getUserMediaFailed @ call.js:798
u._maybeGotUserMediaForInvite @ call.js:576
(anonymous) @ call.js:1276
rageshake.js:107 Error: Couldn't start capturing media! Is your microphone set up and does this app have permission?
    at b (call.js:1141)
    at u._getUserMediaFailed (call.js:798)
    at u._maybeGotUserMediaForInvite (call.js:576)
    at call.js:1276`

on macOS 10.14.4, running Riot desktop app version 1.1.0.
In system preferences, Riot has access to the microphone, and has not requested access to the camera.

**Comment by t3chguy** [comment] 2019-05-13 22:03
@adam-tibbetts what do you see under Settings > Voice & Video
Do you get dropdowns for Audio Output, Microphone and Webcams? Is there a button to try request permissions?

**Comment by adam-tibbetts** [comment] 2019-05-13 22:37
It's saying no webcams detected, and there is no button to try to request permissions.
So it seems like the problem is more that there's no webcam detected.

**Comment by adam-tibbetts** [comment] 2019-05-13 23:37
I got the webcam recognized - issue went away. 

It might be a good idea to have a more descriptive error message, but everything's fine!

**Comment by t3chguy** [comment] 2019-05-14 08:42
Any chance you could share what you did in case someone has the same issue?

**Comment by adam-tibbetts** [comment] 2019-05-14 21:52
Yeah, it was an issue with a program called [OverSight](https://objective-see.com/products/oversight.html) blocking riot's access to the webcam.
If you happen to be running oversight, try clearing your rules and rebooting.

**Comment by jryans** [comment] 2019-05-15 09:20
Glad to hear this is fixed! 😄

**Closed by jryans** 2019-05-15 09:20 UTC
Labels: bug, cannot-reproduce, p2, type:electron, type:voip

**Comment by jryans** [comment] 2019-05-15 09:21
(If other people still have trouble, it's probably best to open a fresh issue to investigate separately.)
