### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by TheoMer** [vector-im/riot-web#2902] opened 2017-01-09 13:38 UTC
`'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.`

OS: Windows 10 Pro
Node: v6.1.0
Npm:  v3.8.6

So, I'm receiving the above mentioned error when running:

```npm run build```

The process I followed was as follows:

> git clone https://github.com/vector-im/riot-web.git
> cd riot-web
> npm install
> npm install electron
> npm run build

What is the issue here?

**Comment by richvdh** [comment] 2017-01-10 23:17
The issue is that the `build` script doesn't work with Windows. PRs to make this work correctly cross-platform would be welcome.

**Comment by TheoMer** [comment] 2017-01-10 23:27
@richvdh Unfortunately I only have a windows solution:

Amend package.json

```set NODE_ENV=production && webpack -p --progress```

and finally run

```node_modules\.bin\electron .```

**Comment by richvdh** [comment] 2017-01-10 23:41
since none of the core team use windows, that's not going to cut it ;)

**Comment by Kegsay** [comment] 2017-01-13 15:33
> since none of the core team use windows, that's not going to cut it ;)

Not entirely true, I've been trying to maintain cross-platform support for quite some time now. We can't set env vars in a cross-platform way, but `npm run start` should work in both Windows and *nix.

**Comment by richvdh** [comment] 2017-01-13 17:37
> npm run start should work in both Windows and *nix.

I believe the complaint is about `npm build`.

**Comment by ara4n** [comment] 2017-04-22 01:40
fixed by @t3chguy hopefully - thanks!

**Closed by ara4n** 2017-04-22 01:40 UTC
Labels: bug, maintenance, p2, platform specific

**Comment by TheoMer** [comment] 2017-04-22 10:43
@ara4n Nope. Still the same as I initially reported.

**Comment by t3chguy** [comment] 2017-04-22 11:53
@TheoMer that's impossible, as package.json no longer contains any lines that begin with `NODE_ENV...`
Could you please paste your local copy of package.json for me to compare

Thanks

**Comment by t3chguy** [comment] 2017-04-22 11:54
Actualy, the reproduction steps you listed would still result in that error, simply because the change hasn't made it to master yet

**Comment by TheoMer** [comment] 2017-04-22 11:57
@t3chguy 

> Actualy, the reproduction steps you listed would still result in that error, simply because the change hasn't made it to master yet

Aha! That explains why. Many thanks.
