### ISSUE TITLE
Seen messages still counted as unseen when hiding messages-seen icon

### ISSUE THREAD

**Issue by mne1991** [vector-im/riot-web#4705] opened 2017-07-30 01:03 UTC
Hello,

The situation: Messages-seen icon is disabled from my Riot settings.

The expected behavior: Unseen messages number (next to channel name) should be reset, because I read the messages, but of course the other users will not see that indication icon that I read the messages.

The problem: After reading the messages, the unread messages counter is **NOT** reset, and after that I cannot know in which rooms I was before, and which messages I really read and which are not!

**Comment by uhoreg** [comment] 2017-07-30 02:09
Duplicate of #4506

**Closed by uhoreg** 2017-07-30 02:09 UTC
