### ISSUE TITLE
clicking on empty space in community filter panel doesn't unselect all communities anymore

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#14632] opened 2020-07-19 12:53 UTC
### Description

IIRC in earlier versions it was possible to either click on the community icon (three persons) or click on empty space in the community filter panel to unselect all communities. When I click on empty space in 1.7.1 all selected communities stay selected.

### Steps to reproduce

- click on a community
- click on the empty space underneath the communities

I'd expect all communities are unselected and no filters are applied anymore.

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**: 1.7.1

**Comment by t3chguy** [comment] 2020-07-20 09:25
Duplicate of https://github.com/vector-im/riot-web/issues/12988

**Closed by t3chguy** 2020-07-20 09:25 UTC
Labels: bug, ui/ux
