### ISSUE TITLE
Hidden events can cause confusion with read receipts of previous events

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#3840] opened 2017-05-07 19:51 UTC
If an event is hidden, such as bundled into MELS, and is the latest read by person X, then it looks as though person X has not seen the events before the MELS due to it not showing the read receipts it contains, maybe it should propagate them or pass it to the closest previous non-hidden event

**Comment by turt2live** [comment] 2018-01-22 20:13
Duplicate of #2629

**Closed** 2018-01-22 20:14 UTC
Labels: bug, cosmetic, design, minor, p3, ui/ux

**Comment by justjanne** [comment] 2022-05-11 11:59
It was decided not to support this functionality for the time being. Read receipts for collapsed event summaries will remain the way they currently are.

See https://github.com/matrix-org/matrix-react-sdk/pull/8446#pullrequestreview-967589502 for clarification.
