### ISSUE TITLE
Long room topics do not overflow and cannot be read

### ISSUE THREAD

**Issue by amyspark** [vector-im/riot-web#6963] opened 2018-07-01 00:14 UTC
### Description

The room #freenode_#krita:matrix.org currently has the following topic:
`https://phabricator.kde.org/source/krita/. Unstable branch: master. Stable branch: krita/4.1 | Current stable release: 4.1.0 | Please wait around after asking a question | off-topic chat: ##krita-chat | This is not a company support channel, it's a chat channel for developers and users of Krita`
In Riot, the topic is readable until "Please wait around after asking a question"; the rest overflows into a hidden second column.

### Steps to reproduce

- Join #krita on Freenode with Riot.

The topic is correctly retrieved and rendered, but only the first part is readable.

![bug](https://user-images.githubusercontent.com/13498015/42129957-5add5d54-7caa-11e8-8b02-bf736af6dddc.jpg)

By unsetting `column-width` and setting `overflow: auto` on `.mx_RoomHeader_topic` , I can read the whole topic, even though the effective real estate is small.

![fixed](https://user-images.githubusercontent.com/13498015/42129958-5b57b50e-7caa-11e8-9d77-08346c011904.jpg)

Log: N/A (visual bug)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 63.0a1 (2018-06-30)
- **OS**: macOS 10.12.6
- **URL**: private server, 0.15.6

**Comment by t3chguy** [comment] 2018-07-01 09:06
Duplicate of https://github.com/vector-im/riot-web/issues/1836

**Closed** 2018-07-17 09:18 UTC
