### ISSUE TITLE
Direct Chats don't show presence indicators when pinned as favourites

### ISSUE THREAD

**Issue by fridtjof** [vector-im/riot-web#14545] opened 2020-07-16 15:26 UTC
### Description

When I pin direct chats to the favourite section, they lose the presence indicators they normally have in the "People" section

### Steps to reproduce

- Mark a direct chat as "Favourite"

Logs being sent: no (I don't feel they're necessary for this)

![grafik](https://user-images.githubusercontent.com/2780577/87689640-c1418e00-c788-11ea-919f-de46303f56ce.png)

### Version information

- **Platform**: desktop
- **OS**: Windows 10
- **Version**: 1.7.0

**Comment by t3chguy** [comment] 2020-07-16 15:28
Duplicate of https://github.com/vector-im/riot-web/issues/14524 (fixed)

**Closed by t3chguy** 2020-07-16 15:28 UTC
Labels: bug, ui/ux
