### ISSUE TITLE
Whitespace added in chat window pushes chat text over screen

### ISSUE THREAD

**Issue by PatrickRose** [vector-im/riot-web#9213] opened 2019-03-19 20:20 UTC
### Description

Sometimes, when I switch to my Riot window there's some added whitespace at the bottom of the chat window - in the screenie below it's added so much whitespace that the chat messages have gone all the way to the top of the screen. Scrolling in the window removes it, as does sending a message.

![riot-9213](https://user-images.githubusercontent.com/1681612/54639150-9821c800-4a84-11e9-9954-8fd2ffe73e45.png)

### Steps to reproduce

Not 100% sure, but it seems to be when another user in the chat is typing, and the "X is typing a message" notification appears at the bottom. If that person doesn't send the message, the whitespace is still there until a resize/scroll happens. Haven't confirmed this yet though, sorry!

Log: not sent    

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome Version 72.0.3626.122 
- **OS**: Linux 
- **URL**:  riot.im/app

**Comment by twexler** [comment] 2019-03-19 21:54
This might be a dupe of #9205, I've had the same experience when tabbed away from riot as is described in that issue

**Comment by lampholder** [comment] 2019-04-04 09:22
Since we've done some much work on the timeline scrollign recently (incluing the fix for #9205) I'm going to close this - please reopen/refile if you see this again.

**Closed by lampholder** 2019-04-04 09:22 UTC
