### ISSUE TITLE
Auto-redaction like in Signal?

### ISSUE THREAD

**Issue by sw1966** [vector-im/riot-web#6835] opened 2018-06-01 17:03 UTC
Pretty simple to describe: Signal has a feature that automatically disappears each message after a customizable period of time has passed. It would be cool to be able to set this for each room and conversation on Riot.

**Comment by t3chguy** [comment] 2018-06-01 17:21
Duplicate of https://github.com/vector-im/riot-web/issues/2497

**Closed by t3chguy** 2018-06-01 17:21 UTC
