### ISSUE TITLE
email-notification cannot be enabled

### ISSUE THREAD

**Issue by smoebody** [vector-im/riot-web#8837] opened 2019-02-20 19:50 UTC
### Description

It is not possible to enable email notification

### Steps to reproduce

- open riot.im/app/
- login
- open settings/notifications
- enable email notifications
- close preferences

When you open the settings/notifications again email-notifications are still disabled

Log: sent    

### Version information

- **Platform**: web and desktop

For the web app:

- **Browser**: Chrome 71.0.3578.98
- **OS**: Fedora 29
- **URL**: riot.im/app  v1.0.1

For the desktop app:

- **OS**: Fedora 29
- **Version**: 1.0.1

**Comment by PeerD** [comment] 2019-02-21 14:07
I can confirm this on Chrome on MacOS.  It just throws a javascript error:

```
Uncaught TypeError: Cannot read property 'checked' of undefined
    at Object.onEnableEmailNotificationsChange (Notifications.js:164)
    at n._onClick (ToggleSwitch.js:58)
    at Object.o (ReactErrorUtils.js:24)
    at s (EventPluginUtils.js:83)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:106)
    at f (EventPluginHub.js:41)
    at p (EventPluginHub.js:52)
    at Array.forEach (<anonymous>)
    at e.exports (forEachAccumulated.js:22)
    at Object.processEventQueue (EventPluginHub.js:250)
    at ReactEventEmitterMixin.js:15
    at Object.handleTopLevel [as _handleTopLevel] (ReactEventEmitterMixin.js:25)
    at p (ReactEventListener.js:70)
    at u.perform (Transaction.js:141)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:60)
    at Object.batchedUpdates (ReactUpdates.js:95)
```

The corresponding event seems to be pointed to a div, not a checkbox:
```
        if (event.target.checked) {
```

**Comment by turt2live** [comment] 2019-02-22 15:23
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2678

**Closed by turt2live** 2019-02-22 15:23 UTC
Labels: bug, defect, major, p1, type:usersettings
