### ISSUE TITLE
Invite via email address dialog entry is split too soon

### ISSUE THREAD

**Issue by the-moog** [vector-im/riot-web#13976] opened 2020-06-10 10:50 UTC
### Description
Riot 1.6.4
Entering a long email, e.g. "this.is.a.test.email+test1@gmail.com" into the invite dialog line gets split after the letter 'g' in gmail so that it reads.
    this.is.a.test.email+test1@g
    mail.com

### Steps to reproduce

Invite a user with a long email into a room. Or make up a long email on Gmail using the + email address extension.

You should be able to enter text to the width of the dialog and not have it go off the top
of the dialog half way through typing.

### Version information

Found in:
- Desktop Riot 1.6.4
- Riot/Web 1.6.4 on Win10/Firefox.

**Comment by t3chguy** [comment] 2020-06-10 10:58
So it doesn't look like it gets split but instead its just wrapped confusingly.
Duplicate of https://github.com/vector-im/riot-web/issues/13066

**Closed by t3chguy** 2020-06-10 10:58 UTC
Labels: bug
