### ISSUE TITLE
Build broken on Node 10(?) because of parallelshell

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6612] opened 2018-04-26 09:43 UTC
I was trying to create a fresh dev env last night and got errors from parallelshel. We should probably replace it with a more maintained alternative, or ideally get rid of it (again).

**Comment by rxl881** [comment] 2018-05-08 10:59
Ahh.. yes, I am running in to this right now. What't the best way to get round this at the moment?

**Comment by rxl881** [comment] 2018-05-08 11:27
Downgrading to node 9.11.1 works for me

**Comment by t3chguy** [comment] 2018-06-24 15:49
This seems to be caused by https://github.com/darkguy2008/parallelshell/pull/60 which doesn't account for "10" < "8" so breaks things. Pinning to the version before this PR was merged should work. (only change between the versions)

**Comment by t3chguy** [comment] 2018-06-24 15:49
Though a fix is due to be released soon:https://github.com/darkguy2008/parallelshell/issues/64#issuecomment-398621405

**Comment by z3ntu** [comment] 2018-08-31 13:07
This unfotunately still an issue and parallelshell didn't release a new version with the fix included.

Switching to `concurrently` (mentioned in one of the linked issues) takes just
```diff
diff --git a/package.json b/package.json
index 12396858..58a1cc18 100644
--- a/package.json
+++ b/package.json
@@ -44,8 +44,8 @@
     "start:res": "node scripts/copy-res.js -w",
     "start:js": "webpack-dev-server --output-filename=bundles/_dev_/[name].js --output-chunk-file=bundles/_dev_/[name].js -w --progress",
     "start:js:prod": "cross-env NODE_ENV=production webpack-dev-server -w --progress",
-    "start": "parallelshell \"npm run reskindex:watch\" \"npm run start:res\" \"npm run start:js\"",
-    "start:prod": "parallelshell \"npm run reskindex:watch\" \"npm run start:res\" \"npm run start:js:prod\"",
+    "start": "concurrently \"npm run reskindex:watch\" \"npm run start:res\" \"npm run start:js\"",
+    "start:prod": "concurrently \"npm run reskindex:watch\" \"npm run start:res\" \"npm run start:js:prod\"",
     "lint": "eslint src/",
     "lintall": "eslint src/ test/",
     "clean": "rimraf lib webapp electron_app/dist",
@@ -91,6 +91,7 @@
     "babel-preset-react": "^6.16.0",
     "babel-preset-stage-2": "^6.17.0",
     "chokidar": "^1.6.1",
+    "concurrently": "^4.0.1",
     "cpx": "^1.3.2",
     "cross-env": "^4.0.0",
     "css-raw-loader": "^0.1.1",
@@ -122,7 +123,6 @@
     "minimist": "^1.2.0",
     "mkdirp": "^0.5.1",
     "mocha": "^2.4.5",
-    "parallelshell": "^3.0.2",
     "postcss-extend": "^1.0.5",
     "postcss-import": "^9.0.0",
     "postcss-loader": "^1.2.2",
```

**Comment by ara4n** [comment] 2018-09-17 21:30
i worked around this with https://github.com/vector-im/riot-web/commit/588369d297cddfa14cc6ae96f01c1651a509ec7b

**Closed by ara4n** 2018-09-17 21:30 UTC
Labels: maintenance, p1
