### ISSUE TITLE
Request / Suggestion: The quoted message should be linked to the original.

### ISSUE THREAD

**Issue by Lokait** [vector-im/riot-web#5279] opened 2017-10-13 18:46 UTC
### Description

The messages that are quotes made with the "Quote" option under "..." should be linked to the original message and not just be text.
When a person clicks the quoted message (or some icon that indicates the link), it should take the user to the original message and maybe also highlight it, kind of like how clicking on a notification in notification section takes the user to the message and highlights it with user specified color scheme of channel.

### Related Issues!?

- **Link**: https://github.com/vector-im/riot-web/issues/5108

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox 56
- **OS**: Fedora 26
- **Riot Version**: 0.12.4

**Comment by t3chguy** [comment] 2017-10-13 19:07
Duplicate of https://github.com/vector-im/riot-web/issues/3571

**Closed by t3chguy** 2017-10-13 19:07 UTC
