### ISSUE TITLE
Allow user to send unencrypted messages in E2E rooms

### ISSUE THREAD

**Issue by barudaret** [vector-im/riot-web#11855] opened 2020-01-14 20:01 UTC
I have a private room that I want to send primarily encrypted stuff in, but every once in a while, I want to send something unencrypted in that room.  If I use a client that can't handle encryption and send something from there, I can send an unencrypted message in an encrypted room and the world doesn't crumble.  But I'd like this ability just within riot-web (and riotx too) instead of having to grab some other client.  Conversations, the XMPP client, does this beautifully actually.  You can switch at any time between OMEMO, PGP, or unencrypted messages, and it doesn't require the room to change anything about its state afaict.

This would allow users to interact with a bot or a bridge (and only when they want to) in an encrypted room.  Or send a message/file that will be available to anyone in that room, regardless of whether they have the keys to decrypt the messages around it.

**Comment by t3chguy** [comment] 2020-01-14 20:13
Closing as duplicate of https://github.com/vector-im/riot-web/issues/6050

**Closed by t3chguy** 2020-01-14 20:13 UTC
