### ISSUE TITLE
Hilarity ensues when clicking on a user whose display name ends in ]

### ISSUE THREAD

**Issue by jansol** [vector-im/riot-web#5474] opened 2017-10-30 18:20 UTC
### Description

Clicking a user to mention them breaks when the last character of their display name is `]`.

### Steps to reproduce

- Find user whose display name ends in `]`
- Click their name and type out a message for them
- Hit enter to send the message

Expected output: `Alice]: So what did you plan for today?`

Actual output: `[Alice]](https://matrix.to/#/@freenode_Alice]:matrix.org): So what did you plan for today?`

### Version information

- **Platform**: desktop, most likely affects web as well, regardless of browser or OS

For the desktop app:

- **OS**: macOS
- **Version**: 0.12.7

**Comment by turt2live** [comment] 2017-10-30 18:22
Similar/duplicate of https://github.com/vector-im/riot-web/issues/4867 (unsure)

**Comment by t3chguy** [comment] 2017-10-30 18:23
I'd say it has the same cause, lack of escaping, so closing as dup

**Closed by t3chguy** 2017-10-30 18:23 UTC

**Comment by jansol** [comment] 2017-10-30 18:25
Indeed, looks like I didn't search for existing issues thoroughly enough.
