### ISSUE TITLE
Special-case 3PID invites to be able to register even if registration is turned off

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3271] opened 2017-02-19 23:54 UTC
Right now, if you invite a user via 3PID to your HS but registration is disabled, they will never be able to join.

It would be very nice to be able to add an exception to let them register for that scenario.

I'm sure I've filed this before, but can't find the issue in riot-web, synapse nor matrix-doc.

**Comment by maxidor** [comment] 2017-05-22 17:27
Sounds like a bad idea: if registration is turned off, the HS users might not be aware of it, and this would go around the explicit configuration of the server.
Since the Identity Server is in charge of the actual notification, shouldn't the message include the info that the user must register on another server?

Also, that's exactly where federated Identity Server would come in handy: they can try to find 3PID mappings for 3PID invites and do a call to the inviter HS to tell about the relevant account, if the user published it.

**Comment by t3chguy** [comment] 2017-05-22 18:30
Duplicate of #2353

**Closed by t3chguy** 2017-05-22 18:30 UTC
Labels: feature, p2, type:signup
