### ISSUE TITLE
Riot-web is very greedy on RAM (and can make chrome crash)

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#3307] opened 2017-02-23 01:10 UTC
(where crash = sad folder of segfaultyness)

**Comment by richvdh** [comment] 2017-02-23 01:12
(Chrome 55.0 on linux)

**Comment by jfrederickson** [comment] 2017-02-23 03:53
If it's actually a segfault, that should probably be reported upstream to Chromium.

**Comment by richvdh** [comment] 2017-02-23 12:18
Attempting to send a rageshake is particularly likely to cause a crash, ironically. strace says the chrome process gets a sigill.

**Comment by richvdh** [comment] 2017-02-23 14:40
Seems to be something to do with memory usage. https://github.com/vector-im/riot-web/pull/3311 may help.

**Comment by ara4n** [comment] 2017-02-27 23:49
mine crashes on pretty much every time i unsleep my comp - it's like #2951 but worse. unclear if it's the rageshaking or the new sync stuff leaking.

**Comment by richvdh** [comment] 2017-03-14 13:48
ftr #3311 helped but didn't solve this

**Comment by ara4n** [comment] 2017-03-16 11:07
I briefly profiled it yesterday, and saw 110K RoomMembers being allocated in the space of 20 minutes.  As Chrome Debug Tools has no API, it's hard to do a stats analysis to see where these are coming from; kegan suggested we may be allocating new RoomMember objects on each and every event we're receiving.

**Comment by Kegsay** [comment] 2017-03-16 14:42
I'm operating under the assumption this is an OOM.

> kegan suggested we may be allocating new RoomMember objects on each and every event we're receiving

Tested locally and I see no evidence of this (both on sent messages and received messages).

----

Did a heap snapshot of my Riot. I have a 435MB heap, of which:
 - 254MB (58%) are retained by 209 `Room` objects. Of this 254MB:
     - 230MB (90%) are retained by 420 `RoomState` objects (all these objects are also retained by `Room` objects).
 - 41MB (9.4%) are retained by the `SyncAccumulator`.
 - 26MB (6%) are retained by `User` objects.
 - 114MB (26%) are retained by other junk.

The low-hanging fruit superficially looks to be `Room` objects, so I'm going to see exactly how this breaks down. STAY TUNED FOR MORE UPDATES :notes:

**Comment by Kegsay** [comment] 2017-03-16 15:18
So the `Room` object distribution is unsurprisingly not linear: there are a few huge rooms and most are small (all sizes in this post are retained sizes, NOT shallow sizes):
 - #go-nuts (49MB)
 - #rust (49MB)
 - Matrix HQ (44MB)
 - #ipfs (25MB)
 - Riot (17MB)
 - #rust-internals (10MB)
 - Riot Android (6MB)
 - and a long tail from 5MB down to 25KB

Note how this set of channels doesn't include high *traffic* rooms like `#matrix-dev`/Core/Internal, it seems to be correlated with member count more than anything else. Looking at #go-nuts (49MB):
 - 30MB (61%) `Room.currentState`
 - 18MB (37%) `Room.oldState`
 - 1MB (2%) other

So making `RoomState` use less memory looks to be the easiest win here. The `currentState` broken down (30MB):
 - 15.33MB (51%) `RoomState.members` - 400KB of which are simply the user ID keys.
 - 2.4MB (8%) `RoomState._sentinels`
 - 2.2MB (7.3%) `RoomState._displayNameToUserIds`
 - 400KB (1.3%) `RoomState.events`
 - 393KB (1.3%) `RoomState._userIdsToDisplayNames` - NB: The values in this map are all 1 bytes values (internalized `undefined`s)

Superficially, it appears that V8 does not just store pointers to the same repeated string (room IDs, user IDs), but instead stores the entire string again. This is why the maps appear to be so large. The `members` map has 10,163 entries, or 15,330KB/10163 = ~1.5KB each. Of this 1.5KB:
 - 1.3KB (87%) `_events` (from `EventEmitter`)

Reducing the number of maps we have may go a long way to help here, or somehow coercing V8 to store pointers to strings instead (e.g via `String` perhaps which is the object wrapper around `string` literals)?

**Comment by Kegsay** [comment] 2017-03-20 14:17
I had an epiphany on the way in today. What happens to the `RoomState` objects in the case of a `limited` sync? I thought this because Ara said:

> mine crashes on pretty much every time i unsleep my comp

and I thought there was significance to the "unsleep" part. What the JS SDK does is it will preserve where it got up to (room state and all) then create **a new copy** of the room state for the new data (so each dis-contiguous timeline corresponds to 2 `RoomState` objects: old and current (either end of the timeline)).

This scales extremely poorly when 1x `RoomState` object is between 5-20MB and you get ~50 `limited` responses on unsleeping your laptop... I have now "fixed" this in https://github.com/matrix-org/matrix-js-sdk/issues/395 by not holding onto the old dis-contiguous timelines but instead dropping them to the floor. This has helped dramatically.

**Comment by Kegsay** [comment] 2017-03-20 14:20
It's worth noting that the indexeddb stuff may have exacerbated this. The store is synced every 5 minutes. If there is enough traffic in a room (strictly speaking >20 messages within 5 mins: hi2u freenode channels) then on reload of the page it will get a `limited` sync back for that room, doubling the amount of space it would've taken up had it done a fresh /sync. This may be why we've noticed this now.

**Comment by ara4n** [comment] 2017-03-27 10:16
Current status: @kegsay fixed the main mem leak here (due to old state hanging around), however @richvdh and @erikjohnston are still seeing random crashes even immediately after boot.  They also can't even do a heap snapshot immediately after boot, which sounds like their heap is mysteriously full of something or other.  @kegsay hypothesises that this might be a bad extension, as nobody else has this problem apart from rich & erik who are both running an Adblock of some kind.  Next step to get erik to disable his adblock and see if everything gets fixed.

**Comment by richvdh** [comment] 2017-03-29 06:57
I disabled all extensions and still can't snapshot unless I ldpreload a library disabling setrlimit. 

On 27 March 2017 11:16:54 BST, Matthew Hodgson <notifications@github.com> wrote:
>Current status: @kegsay fixed the main mem leak here (due to old state
>hanging around), however @richvdh and @erikjohnston are still seeing
>random crashes even immediately after boot.  They also can't even do a
>heap snapshot immediately after boot, which sounds like their heap is
>mysteriously full of something or other.  @kegsay hypothesises that
>this might be a bad extension, as nobody else has this problem apart
>from rich & erik who are both running an Adblock of some kind.  Next
>step to get erik to disable his adblock and see if everything gets
>fixed.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/riot-web/issues/3307#issuecomment-289412445

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ara4n** [comment] 2017-03-29 07:36
so what does the snapshot show if you disable setrlimit?

**Comment by Kegsay** [comment] 2017-03-29 07:56
Nothing exciting. He has a 410MB heap on startup (I have 380MB on startup and have no trouble snapshotting). No explosion of RoomState objects either. The only thing which looked odd was some things have references to `chrome://` "things" which I hadn't seen before, hence my suspicion with extensions. Perhaps this is actually a dev tools add on instead? I know that React dev tools do things like send stuff over `postMessage`, so they are fairly intrusive.

**Comment by richvdh** [comment] 2017-03-29 08:08
react dev tools are certainly a memory and cpu sink once they are active, but I rather thought they didn't do much until the react dev tools tab was opened.

I've got a few snapshots from Friday and today, which I can share if it is of interest, but I didn't see a smoking gun.

Whilst extensions don't seem to make the difference between being able to snapshot and not, perhaps they do make the difference between the tab crashing under normal use and not. I have everything disabled for now; will keep using the session for a while and see what occurs.

**Comment by ara4n** [comment] 2017-03-30 14:29
@richvdh has it gone bang yet? might be worth running in safe mode as well as disabling all extensions?

**Comment by richvdh** [comment] 2017-03-30 22:31
Sorry. Yes, disabling extensions didn't help - it still goes bang after a few hours.

I haven't tried just leaving Riot running, but I also can't take a heap snapshot in safe mode, nor in a chrome instance in a completely new profile, nor under chromium. I *was* able to take a heap snapshot on @Kegsay's machine having logged in with my account, so this appears to be specific to my machine rather than my account.

**Comment by lampholder** [comment] 2017-04-12 09:43
We're sharing the details of supported countries here: https://medium.com/@RiotChat/extending-our-global-reach-for-phone-number-verification-78cc7ff41da7

**Comment by lampholder** [comment] 2017-04-12 13:52
We think the recent webworker-for-indexeddb improvements have resolved this, so closing.

**Comment by richvdh** [comment] 2017-04-26 15:35
iiiit's baaaack!

![image](https://cloud.githubusercontent.com/assets/1389908/25442926/418f64b4-2a9e-11e7-8de6-6aa681dc7e43.png)

**Comment by lampholder** [comment] 2017-04-27 12:38
😢 

Do we have any more information now? Is it at least less frequent?

**Comment by dbkr** [comment] 2017-04-27 13:29
I can fairly reliably repro this with chrome on ubuntu in a VM, although suffer from the same problem as @richvdh in that dev tools does not help to tell me why it is crashing.

**Comment by dbkr** [comment] 2017-04-28 09:53
Scratch that, I was reproducing an entirely different crash.

**Comment by richvdh** [comment] 2017-05-04 08:27
Having left riot running with `setrlimit` disabled in chrome for 48h, Chrome's task manager now reports that the tab in question is using 1.23G; RSS in `ps` is similar. I took a heap profile, but it only shows 312MB (which seems to be dominated by RoomState objects - including 4 at 20MB each (two each for #matrix and #rust) - anyway, nothing incriminating).

So it looks like most of Chrome's resource usage is by stuff outside the JS heap - which correlates with the fact that I don't see a "paused before out of memory crash" per https://v8project.blogspot.co.uk/2017/02/one-small-step-for-chrome-one-giant.html.

**Comment by Kegsay** [comment] 2017-05-04 08:37
I think this broadly makes sense if this is mainly caused by an extension / plugin / add-on / etc. I don't really know how you can go about seeing what the remaining 900MB in the Riot tab is going towards though...

**Comment by richvdh** [comment] 2017-05-04 08:47
I'm going to try running it in a separate instance of chrome, with all extensions/etc disabled.

**Comment by erikjohnston** [comment] 2017-05-04 09:00
Is it possible that it was a memory spike?

**Comment by richvdh** [comment] 2017-05-04 09:01
I don't know what you mean. It wasn't going down again, if that's what you mean?

**Comment by erikjohnston** [comment] 2017-05-04 09:09
I wouldn't be surprised if the runtime never returned memory back to the OS after memory is freed (most things don't). If that's the case then if riot allocates and then deallocates  lots of memory you may end up with the process using lots of memory, but very little on the heap.

**Comment by Kegsay** [comment] 2017-05-04 09:11
We can potentially rule that out by recording an allocation profile in Chrome and keep it running (and hope it doesn't OOM).

**Comment by Kegsay** [comment] 2017-05-04 09:16
Looks like we might be out of luck if that isn't the underlying cause. Chrome [used to](http://www.chromium.org/developers/deep-memory-profiler) have a memory profiler but doesn't anymore :/

**Comment by richvdh** [comment] 2017-05-04 09:31
Hrm... simplistically, this bit of JS makes it look like Chrome *does* return freed memory:
```
function f() { 
    var b = new Uint8Array(500*1000*1000); 
    setTimeout(function() { b[0]=1; console.log("done") }, 1000 );
}
f();
```

(You see the memory usage spike, and then later drop when the garbage colllector runs. The timeout is just to make the allocated memory hang around long enough that it isn't immediately freed on return fron the function).

On the other hand, I can imagine that fragmentation might make it difficult for memory to be returned in the general case.

**Comment by Kegsay** [comment] 2017-05-04 10:06
TBF I've seen the Freenode bridge readily give back memory to the OS (based on Leo's process metrics from `/proc`) and that uses V8 so I don't expect memory spiking to be the cause.

**Comment by richvdh** [comment] 2017-05-04 14:36
> I'm going to try running it in a separate instance of chrome, with all extensions/etc disabled.

that did not help; it lasted about 4 hours before crashing. Please stop blaming this on an extension now, @Kegsay? Also worth noting that it crashed while I was away from my desk.

Next I'm going to try disabling setrlimit and leaving an allocation profile running for a while.

**Comment by ara4n** [comment] 2017-05-05 03:00
i think i'm seeing this too. I'm on precisely 1.2GB of RAM attributed by the Chrome Task Manager after about 6 hours of usage; i had to restart earlier because my laptop ran out of RAM entirely which may have been due to Riot (although at the time i blamed Earlybird without checking).  My V8 heap however is 550MB, which is precisely as expected for my enormous account (220K members, 2000 rooms, etc).

**Comment by Kegsay** [comment] 2017-05-05 07:57
We should be able to see leaky DOM nodes in heap profiles but they don't count towards the heap size iirc. Given it crashed for @richvdh when he was away from his laptop, perhaps we leak when receiving events (messages?).

**Comment by ara4n** [comment] 2017-05-05 14:25
Agreed that leaking DOM should appear in the JS Heap; was just wondering what other native stuff it might be pulling in.  However, perhaps having 600MB of native heap + 600MB of JS heap isn't that unreasonable?

More datapoints from me: after sleeping my laptop for 12 hours, my /develop tab just took 2 minutes to come back to life, and repeatedly did the whole 'unresponsive' thing in the interim.  I had the task manager open though, and was intrigued that it started at 899MB of RAM RSZ, and stayed there for most of the 2 minutes until jumping up to 1.2GB at the end.  Meanwhile my log (which I could only open once the app  has:

```
Decrypted Olm message from qcXRfnKwDaEEk7XJinlXKHLlAZ9q1TL9/A2JRxN/G0Y with session 6TI8VbEbNs3S7FeQNMlveFb9jZ2TIuwQ78weYf7N1NI
15:16:26.473 bundle.js:59234 Adding key for megolm session qcXRfnKwDaEEk7XJinlXKHLlAZ9q1TL9/A2JRxN/G0Y|0M1tFBGb5GwAGWzWnpeyi1fDWKlqqdQpzElLg+E6uXE
15:16:26.532 bundle.js:59234 m.new_device event from @erikj:jki.re:WDNXTGHEYP for rooms !FGXeDOylLihwfdKAIx:matrix.org,!UCnwUWwIKhcpaPTHtR:sw1v.org,!opdbHDeKihqLYRaIlc:matrix.org,!pLAcOvLjsxbcgitday:matrix.org,!gddPaOMfPwbrTWyrji:matrix.org
15:16:26.535 bundle.js:59234 Marking device list outdated for @erikj:jki.re
15:16:26.549 bundle.js:59234 Request to reset timeline in room  !DgvjtOljKujDBrxyHk:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:29.453 bundle.js:59234 Request to reset timeline in room  !BziesDYHgIwoNBaUdY:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:29.781 bundle.js:59234 Request to reset timeline in room  !jlCdDSaAJksnmXkjwz:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:29.948 bundle.js:59234 Request to reset timeline in room  !JdjcnWDJwarwNtUfKd:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:30.187 bundle.js:59234 Request to reset timeline in room  !qwTvNobACZsjvbuLSZ:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:30.429 bundle.js:59234 Request to reset timeline in room  !pqwsHhdjYsAqQvRuls:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:30.465 bundle.js:59234 Request to reset timeline in room  !LJdMiciydqJhmdppLS:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:30.886 bundle.js:59234 Request to reset timeline in room  !WCHwNGGsrVwPeRtAnq:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:31.109 bundle.js:59234 Request to reset timeline in room  !UcYsUzyxTGDxLBEvLz:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:31.324 bundle.js:59234 Request to reset timeline in room  !DQssxOtiGAHLhbdzxt:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:31.531 bundle.js:59234 Request to reset timeline in room  !DdJkzRliezrwpNebLk:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:31.661 bundle.js:59234 Request to reset timeline in room  !OYyXUbcTKVsDBUniNn:matrix.eclabs.de  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:31.763 bundle.js:59234 Request to reset timeline in room  !HaYTjhTxVqshXFkNfu:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:31.897 bundle.js:59234 Request to reset timeline in room  !SnCqwjBFxKGDZmmeRW:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:32.148 bundle.js:59234 Request to reset timeline in room  !KcSkFhjaqIDFwwoMDR:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:16:32.169 bundle.js:59234 Request to reset timeline in room  !cURbafjkfsMDVwdRDQ:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:18:09.362 bundle.js:59234 Request to reset timeline in room  !qBIqxxVAlLiojhRYxM:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
15:18:09.423 bundle.js:59234 Marking device list outdated for @erikj:jki.re
15:18:09.424 bundle.js:59234 Queued key download for Array(3)
15:18:09.430 bundle.js:59234 MatrixClient sync state => SYNCING
15:18:10.801 indexeddb-local-backend.js?79bc:216 Persisting sync data up to  s145372813_231252415_38227_24578696_269367_79433_809601_695822
15:18:10.801 /develop/bundles/adc908334a8fdc2bd73f/indexeddb-worker.js:4014 Persisting sync data up to 
15:18:14.646 bundle.js:59234 Presence: online
```

...i.e. it took 2 minutes in `15:16:32.169 bundle.js:59234 Request to reset timeline in room  !cURbafjkfsMDVwdRDQ:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org`.  This feels like a very concrete thing going wrong...

**Comment by ara4n** [comment] 2017-05-05 14:26
oh, also worth noting that it took 4 minutes to mark me as online... :/

**Comment by Kegsay** [comment] 2017-05-05 15:13
```
15:16:26.549 bundle.js:59234 Request to reset timeline in room  !DgvjtOljKujDBrxyHk:matrix.org  viewing: !cURbafjkfsMDVwdRDQ:matrix.org
...
15:18:09.430 bundle.js:59234 MatrixClient sync state => SYNCING
```
These lines should all be done on a single tick of the event loop, so it sounds like we have a pathological `O(n^2)` somewhere, probably in relation to room members given it affected Matrix HQ so heavily. It's worth noting that all the other rooms would've had their timelines dropped, but Matrix HQ would not *iff* you were scrolled up when the `/sync` returned. Given the associated memory spike you reported, I hypothesise that the timeline was NOT reset so it was forced to copy the entire room state for Matrix HQ twice. Without CPU profiles though, I can only theorise. This isn't really relevant to this issue though, since it's not a Oh Snap failure.

**Comment by richvdh** [comment] 2017-05-05 15:25
FTR the takes-ages-to-resync looks the same as matrix-org/riot-web-rageshakes#43.

And I agree it may or may not be related to this bug.

**Comment by dbkr** [comment] 2017-05-08 10:00
I looked at the CPU churn on an incremental sync after load recently, and a lot of it was caused by the Constant Time Dispatcher now dispatching a separate Refresh event for every roomstate.member event, causing each RoomTile to refresh separately (if power levels change in a room, a roomstate.member event will be emitted for every member in the room).

I suspect this is not the cause of rich's woes though.

**Comment by richvdh** [comment] 2017-05-08 11:50
I left a heap timeline profile running for 3 hours. It doesn't seem to show anything interesting, but I have no idea what I'm looking for. I also have no idea if whatever makes memory usage explode happened in this timeframe.

http://www.sw1v.org/~rav/Heap-20170508T124658.heaptimeline.gz, if anyone is interested in looking.

**Comment by richvdh** [comment] 2017-05-08 11:52
> I also have no idea if whatever makes memory usage explode happened in this timeframe.

I suspect not, since having unloaded the profile, RSS usage has gone back down to 650M (it was about 1050M with the profile loaded in the devtools)

**Comment by richvdh** [comment] 2017-05-08 11:54
I'm unconvinced that a timeline is a sensible way to pursue this. It seems a common theme that when this happens, we see huge RSS usage by chrome, but only a few hundred MB of JS heap usage. Is there any way we can figure out where the other gig is going?

**Comment by ara4n** [comment] 2017-05-08 16:54
my windows chrome 57.0.2987.133 has now taken to crashing during processing initialSync during startup on a fresh install (i.e. before indexeddb has finished loading...).

**Comment by richvdh** [comment] 2017-05-08 17:12
filed the cpu churn as #3856

**Comment by ara4n** [comment] 2017-05-08 17:14
...my chrome looks to be simply running out of physical RAM; the box has only 3GB (32-bit Win7), and the tab shoots up to 900MB RSZ before suddenly vanishing.  (It doesn't even oh snap; it just goes dark grey :/)

**Comment by ara4n** [comment] 2017-06-13 13:04
i think this was likely a regression caused by the ConstantTimeDispatcher stuff.  We'll see if it starts happening again when that gets remerged.

**Comment by richvdh** [comment] 2017-09-28 14:17
This is still happening to me and @erikjohnston semi-regularly (every day or so).

Some more information:

The problems I am seeing here are at the process level. We are *not* (afaict) hitting the v8 heap limit so https://developers.google.com/web/updates/2017/03/devtools-release-notes#out-of-memory-breakpoints doesn't help us.

Chrome does a `setrlimit(RLIMIT_DATA, 2G-1)`. That appears to be coming from here: https://cs.chromium.org/chromium/src/content/common/sandbox_linux/sandbox_linux.cc?sq=package:chromium&dr=C&l=434. I believe it is that limit which we are hitting.

This 2G ends up being shared by everything from the JS heap to the image cache.

**Comment by richvdh** [comment] 2017-09-28 14:20
Oh, another datapoint: `RLIMIT_DATA` didn't really do much before linux 4.5 (see https://github.com/torvalds/linux/commit/84638335900f), which goes some way to explain why some people never see this.

(Thanks to @vext01 for making me aware of that...)

**Comment by erikjohnston** [comment] 2017-09-28 15:02
This happens to me multiple times a day. It also usually happens once after a refresh.

**Comment by richvdh** [comment] 2017-09-30 16:14
Here's a plot of VmData of the riot tab over time, leading up to the crash. I'm led to wonder what happened at 23:00 that made it nearly double in a short space of time. (I wasn't using the machine at the time, ftr. Sadly I don't know what room Riot was showing.)

It's probably worth noting that shortly before the crash, whilst the VmData was getting on for 2G (1775400 kB), RssAnon (which is what Chrome's task manager reports as 'memory') was only 665944kB. It might be interesting to look into the memory map of the process once it gets into a high VmData regime to see what it's doing with the other gig.

![vmdata](https://user-images.githubusercontent.com/1389908/31047445-c7b3f61a-a602-11e7-96bf-4dbfdcfbcbd4.png)

**Comment by ara4n** [comment] 2017-09-30 17:10
doesn’t the rageshake logging show precisely what it was up to?

**Comment by richvdh** [comment] 2017-10-01 20:33
Glad you're paying attention. FWIW it was open in matrix-internal, which was more-or-less silent during that period.

**Comment by ara4n** [comment] 2017-10-01 20:51
that is incredibly weird then. i wonder if a tonne of events came in on other rooms? or device updates? is there anything in the logs at all for that timeframe?

**Comment by richvdh** [comment] 2017-10-01 22:08
right now, my Riot tab has a VmData of 1.5G; a lot of that is due to a single region of 531932kB which appears to be almost entirely zeros.

**Comment by richvdh** [comment] 2017-10-01 22:15
> that is incredibly weird then. i wonder if a tonne of events came in on other rooms? or device updates? is there anything in the logs at all for that timeframe?

There is very little in the logs at that time tbh.

**Comment by Orbixx** [comment] 2017-10-03 01:33
I'm experiencing similar behaviour in Chrome Version 61.0.3163.100 (Official Build) (64-bit), on both /app and /develop. No sudden crashes though, just absurdly high memory usage which seems strongly correlated with rooms and the size of them.

Not sure how to provide any useful data for analysis, but if you need me to do anything I'm happy to oblige.

**Comment by ara4n** [comment] 2017-11-06 11:09
I've been seeing this getting much worse in the last few weeks; every time I unsleep Riot after overnight i get a flurry of unresponsive warnings.  I'll take a look.

**Comment by richvdh** [comment] 2017-11-06 11:11
what's the logic behind thinking that an unresponsive warning is the same problem as an excess of VmData?

**Comment by ara4n** [comment] 2018-02-20 18:19
So I did a bunch of memory profiling last week - the summary from https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1518745116614283uoTaQ:matrix.org was:

 * [ ] copy-on-write currentState from oldState (or vice versa)
 * [ ] copy-on-write sentinels (from members)
   * [ ] lazy-creating sentinels (almost as good as copy-on-write)
 * [ ] be more aggressive on interning (14MB of duplication of the strings "join" and "leave" alone!)
 * [ ] generate event.date on demand (and hope that doesn't slow rendering rooms down too much; perhaps we could then cache them)
 * [ ] ignoring state and members for users who have left (unless we paginate back far enough to view them). this could perhaps be done on the server to save bandwidth too, modulo having to resurrect them at the right point when you call /messages.

Filing this here for ease of reference and to track the bits which @dbkr has been attacking.

**Comment by dbkr** [comment] 2018-02-20 18:25
Things I've done to reduce memory usage:
 * https://github.com/matrix-org/matrix-js-sdk/pull/610
 * https://github.com/matrix-org/matrix-js-sdk/pull/612
 * https://github.com/matrix-org/matrix-js-sdk/pull/613

**Comment by dbkr** [comment] 2018-02-22 14:29
Data points on how much the above has improved matters:

My test account  on Chrome on an ubuntu VM:
before: 870000 live, 1041000 total
after: 705000 live, 801000 total

Travis: "Memory usage is down to just under 2gb, so about 500-600mb savings" (https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$15191517123083TkBgH:t2l.io)

Matthew: "dave: my heap is now 775MB (down from 1.2GB when this began :D)" (https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$1519152400200168zKZpA:matrix.org)

So based on those rough numbers, a saving of somewhere around the 20-25% mark.

**Comment by dbkr** [comment] 2018-02-22 16:37
I've also done the 'be more aggressive on interning' thing: https://github.com/matrix-org/matrix-js-sdk/pull/615

**Comment by ara4n** [comment] 2018-04-21 20:01
since dave's work in feb we seem to be just about okay again, so dropping prio

**Comment by richvdh** [comment] 2018-08-08 08:43
I'm no longer seeing frequent crashes. (It still happens occasionally, but...)

I'm not really sure there's any value in a "Riot uses too much memory" bug - that's kindof a given - unless we want to address a specific cause or set of symptoms.

Is this open because the checklist at https://github.com/vector-im/riot-web/issues/3307#issuecomment-367069588 still has outstanding items? If so, it might be worth moving them to a new bug - I think they are going to get lost among the other noise here.

**Comment by ara4n** [comment] 2018-09-30 16:03
lazy loading should have effectively fixed this for good. have split out the other two issues for posterity.

**Closed by ara4n** 2018-09-30 16:03 UTC
Labels: bug, major, p2
