### ISSUE TITLE
Set Up Encryption toast wording error

### ISSUE THREAD

**Issue by notramo** [vector-im/riot-web#13397] opened 2020-04-27 09:33 UTC
![image](https://user-images.githubusercontent.com/26059643/80357060-ad1d7d00-887a-11ea-84f4-4b5e63d41dc1.png)

**It doesn't upgrade anything. It isn't set up yet.**
It would be better:
![image](https://user-images.githubusercontent.com/26059643/80357162-d63e0d80-887a-11ea-98ec-80b9dfff5986.png)

**Comment by turt2live** [comment] 2020-04-27 17:20
Duplicate of https://github.com/vector-im/riot-web/issues/13231

**Closed by turt2live** 2020-04-27 17:20 UTC
Labels: bug, feature:e2e-cross-signing, phase:4, story:1, ui/ux
