### ISSUE TITLE
can't register because of recaptcha

### ISSUE THREAD

**Issue by 2403772980ygy** [vector-im/riot-web#12643] opened 2020-03-07 08:42 UTC
![image](https://user-images.githubusercontent.com/40046418/76139863-794e8400-608f-11ea-9033-3ed0b6ce118f.png)

![image](https://user-images.githubusercontent.com/40046418/76139997-f0384c80-6090-11ea-85ec-1f9bdd5e58d9.png)

### Description

I can't find the ReCaptcha after trying to register, however, I got my verifying email, but I can register again with the same username and email indicates that my account is not registered. And I got the warning like the image above

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

I tried to register and encountered this problem.

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web + desktop

For the web app:

- **Browser**: Chrome Canary
- **OS**: Windows 10 insiders preview
- **URL**: riot.im/app

For the desktop app:

- **OS**: Windows 10 insiders preview
- **Version**: I downloaded it today and I can't find the settings panel, I guess its 1.5.12

**Comment by t3chguy** [comment] 2020-03-07 09:46
Duplicate of https://github.com/vector-im/riot-web/issues/12137

**Closed by t3chguy** 2020-03-07 09:46 UTC
Labels: bug, ui/ux
