### ISSUE TITLE
global ability to resend unsent messages

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7695] opened 2018-11-13 17:42 UTC
if you are sending messages on bad connectivity it's a nightmare to remember which rooms have unsent messages and manually resend them. there should be a global resend button

**Comment by turt2live** [comment] 2018-11-13 17:51
Related/possible duplicate of https://github.com/vector-im/riot-web/issues/4824

**Comment by lampholder** [comment] 2018-11-15 13:11
Agreed this is a dup - @ara4n do you want to bump the priority? It's currently `P3` (== a good idea but not on our immediate horizon)

**Comment by lampholder** [comment] 2018-11-15 13:12
I'll close this - please continue the conversation on #4824 :)

**Closed by lampholder** 2018-11-15 13:12 UTC
