### ISSUE TITLE
Reaction is double-counted

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#12351] opened 2020-02-13 08:41 UTC
sometimes (seems to happen mostly after having just loaded riot) reactions are counted twice. See screenshot

**Comment by bwindels** [comment] 2020-02-13 08:41
![doublereaction](https://user-images.githubusercontent.com/274386/74416211-afa43500-4e3c-11ea-9503-b4478cf7948c.png)

**Comment by bwindels** [comment] 2020-02-13 09:23
Matthew: i think if a cached /sync and /messages overlap (for whatever reason) you get a doublecount.

**Comment by t3chguy** [comment] 2020-02-13 09:27
Duplicate of https://github.com/vector-im/riot-web/issues/11161

**Closed by t3chguy** 2020-02-13 09:27 UTC
Labels: bug
