### ISSUE TITLE
User pages let you close MemberInfo, leaving you in limbo

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2386] opened 2016-09-29 23:12 UTC
e.g.  https://vector.im/develop/#/user/@matthew:matrix.org is a blank MiddlePanel and a MemberInfo in the RHS. If you hit the close button on the MemberInfo you get stranded in a weirdly blank UI

**Comment by aaronraimist** [comment] 2020-01-27 01:59
Duplicate of https://github.com/vector-im/riot-web/issues/3586 (you can't actually close them right now due to https://github.com/vector-im/riot-web/issues/10306)

**Closed by aaronraimist** 2020-01-27 01:59 UTC
Labels: bug, cosmetic, p2, type:memberinfo
