### ISSUE TITLE
Since a recent update, channels/rooms with no unread messages are too bright/bold

### ISSUE THREAD

**Issue by RheingoldRiver** [vector-im/riot-web#14612] opened 2020-07-18 12:07 UTC
In night mode, the font on read conversations is now too bright & bold, and they look unread (these channels all have no new messages):
![image](https://user-images.githubusercontent.com/18037011/87852136-ed622980-c8c4-11ea-8dd3-6a33d2cc6f8c.png)

Previously I think read conversations/rooms were styled the same as the interface, and unread were this bright white/bold.

This is the desktop app.
- **OS**: Windows 10
- **Version**: 1.7.1

**Comment by t3chguy** [comment] 2020-07-18 15:02
Duplicate of https://github.com/vector-im/riot-web/issues/14481

**Closed by t3chguy** 2020-07-18 15:02 UTC
Labels: bug, ui/ux
