### ISSUE TITLE
Can't logout from existing identity server that is saved to an account

### ISSUE THREAD

**Issue by chrissi55** [vector-im/riot-web#11061] opened 2019-10-06 06:19 UTC
### Description

I am using matrix-synapse 1.4.0 on my own server. Since it is possible to make own email responsible for password resets e.g. i entered a valid email adress to my existing account.
Under riot-android i can see this saved user_threepid .> under riot-web it's place is empty i only see "+ Enter new Emailadress" that's all

### Steps to reproduce

- go to settings in riot-web
- klick on the "+ Enter new Email Adress"
- await the first Mail to verify your adress
- go back to riot-web and click on Forward
- Email saved -> check in your database (i use postgresql) and look into "user_threepids" if everything is saved as expected

In my case i expected a shown email in riot-web under user-account settings -> general
but it's place is empty. Going to settings under riot-android the email is there and working!

I described in riot-web room allready without success. Someone told me to delete my entry under identity server. i tried this, but the button "Trennen" is out of order. Clicking on it does not delete my identity server adress. And i don't get any error message when clicking on this red button under settings.

Maybe that why my email is not shown, not sure?

I have to mention, that i never used vector.im or matrix.org as identity server. Instead i fictively entered my riot-server url instead as dummy for that - in earlier versions it wasn't possible to leave this field blank.

After saving email to my account i cleared the cache in both cases riot-web AND riot-android

Log: sent/not sent?  sent  

### Version information

riot-web: 1.4.2
riot-android: 0.9.6 (Play Store)

- **Platform**: web (in-browser) or desktop?

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app: riot-web under zorinos 15 (ubuntu 18.04)
![Bildschirmfoto vom 2019-10-06 08-12-08](https://user-images.githubusercontent.com/22561479/66265170-ff7d4a80-e811-11e9-8fd7-b3ff797b512a.png)
![Bildschirmfoto vom 2019-10-06 08-14-34](https://user-images.githubusercontent.com/22561479/66265174-05732b80-e812-11e9-8955-076b8645a738.png)
![Bildschirmfoto vom 2019-10-06 08-17-30](https://user-images.githubusercontent.com/22561479/66265175-099f4900-e812-11e9-94a1-f469c865cb89.png)

- **OS**: ZorinOS 
- **Version**: 15

**Comment by jryans** [comment] 2019-10-07 11:48
Sorry to hear you are having trouble here!

I am curious what happens with the request `_matrix/client/r0/account/3pid` when you open Settings in Riot Web.

Could you open the browser / desktop app DevTools (Ctrl-Shift-I) and use the network tab to check the response to this request? Does it include your account email?

I think your issue with removing the identity server should be resolved once https://github.com/vector-im/riot-web/issues/10909 is fixed soon.

**Comment by jryans** [comment] 2019-10-09 16:28
Based on the info in this issue so far, I believe this is a duplicate of https://github.com/vector-im/riot-web/issues/10909, so let's check in again after that's fixed.

**Closed by jryans** 2019-10-09 16:28 UTC
Labels: phase:2, privacy-sprint, support, type:identity-server
