### ISSUE TITLE
Add text drag and drop support

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#7962] opened 2018-12-28 01:48 UTC
`@toruser1:matrix.org` would like to be able to drag in text from another application

Works on slatejs.org, was added in 0.6.3 of SlateJS https://github.com/ianstormtaylor/slate/issues/56#issuecomment-234686064

**Comment by bwindels** [comment] 2020-03-30 08:33
Duplicate of #10778

**Closed** 2020-03-30 08:32 UTC
Labels: feature, p2, type:composer

**Comment by bwindels** [comment] 2020-03-30 08:34
(we're using the type:composer label only for bugs in the new composer powered by CIDER, which we switched to mid last year)

**Comment by aaronraimist** [comment] 2020-03-30 16:19
Right... this is a bug in the new composer. I assume the original comment about Slate was that it previously did work in Slate and doesn't work in CIDER.

**Comment by bwindels** [comment] 2020-03-30 16:26
> Right... this is a bug in the new composer. I assume the original comment about Slate was that it previously did work in Slate and doesn't work in CIDER.

More that it worked on the slate demo site but not in Riot.
