### ISSUE TITLE
privacy leak when not using matrix.org

### ISSUE THREAD

**Issue by sneak** [vector-im/riot-web#12712] opened 2020-03-12 15:58 UTC
### Description

On first launch, Riot Desktop (OSX) version 1.5.0 contacts several remote servers with which I do not wish to communicate, leaking my IP and location to those remote servers, and exposing the fact that I am a Matrix user to the thousands that have access to my unencrypted IP metadata.

### Steps to reproduce

Launch Riot 1.5.0 on osx.

#### Actual:

The following connections occur:

<img width="548" alt="Screen Shot 2020-03-12 at 08 52 39" src="https://user-images.githubusercontent.com/408977/76540453-65b06e00-643f-11ea-82c0-127b83dee0b5.png">
<img width="548" alt="Screen Shot 2020-03-12 at 08 52 59" src="https://user-images.githubusercontent.com/408977/76540474-6b0db880-643f-11ea-82ab-55164a7cff5a.png">
<img width="562" alt="Screen Shot 2020-03-12 at 08 53 24" src="https://user-images.githubusercontent.com/408977/76540476-6c3ee580-643f-11ea-8280-8c9afabd9ddd.png">

<img width="609" alt="Screen Shot 2020-03-12 at 08 52 57" src="https://user-images.githubusercontent.com/408977/76540462-6812c800-643f-11ea-9a8d-b74e0a6bb427.png">

I have my own homeserver and do not wish for my client to contact matrix.org for any reason.  I'm not sure what those other requests are doing, but they're leaking to my ISP and national military that I am a Matrix user via SNI.

For comparison: my IRC client does not connect to third parties when I launch it - only the IRC servers to which it is configured to connect.

### Expected

No connections are made to any host until I sign in to a service, or opt-in to autoupdate checking.  (Autoupdate checks, implemented naively on-launch, are a form of inadvertent spying/telemetry, as they send an unencrypted identifier of the application (SNI hostname) on each and every launch.)

### Version information

- **Platform**: desktop
- **OS**: macOS, but I would assume this affects all versions
- **Version**: 1.5.0

**Comment by sneak** [comment] 2020-03-12 16:09
Confirmed on 1.5.12 (latest in caskroom) - sorry for testing against an old version.

**Comment by turt2live** [comment] 2020-03-12 16:09
This is a configuration validation check that is being performed in the background: https://github.com/vector-im/riot-web/issues/11655

As a workaround in the meantime, you can edit the config that riot-desktop uses to point at your homeserver instead of matrix.org, though the config ends up getting overwritten because it's a build config.

Closing as a duplicate of https://github.com/vector-im/riot-web/issues/11655

**Closed by turt2live** 2020-03-12 16:09 UTC
Labels: bug, privacy
