### ISSUE TITLE
Labels on input boxes are misplaced & ineligible

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#10315] opened 2019-07-11 13:41 UTC
<img width="642" alt="Screenshot 2019-07-11 at 14 40 08" src="https://user-images.githubusercontent.com/4626865/61055952-75783e00-a3ea-11e9-97e5-551791ccb634.png">

Latest /develop on Chrome.

**Comment by bwindels** [comment] 2019-07-11 13:45
What exact version of Chrome? Any extensions active?

**Comment by bwindels** [comment] 2019-07-11 13:45
(sorry, finger slipped)

**Comment by bwindels** [comment] 2019-07-11 13:46
I assume https://github.com/matrix-org/matrix-react-sdk/pull/3204 will fix this

**Comment by nadonomy** [comment] 2019-07-11 13:47
> What exact version of Chrome? Any extensions active?

Version 75.0.3770.100 (Official Build) (64-bit) on macOS.

Can be reproduced in ingonito windows (extensions disabled) so I'm not sure they're interfering.

**Comment by nadonomy** [comment] 2019-07-11 13:47
> I assume [matrix-org/matrix-react-sdk#3204](https://github.com/matrix-org/matrix-react-sdk/pull/3204) will fix this

Ah! Good find. @jryans can you confirm? If so, feel free to just close this issue.

**Comment by turt2live** [comment] 2019-07-11 13:47
Duplicate of https://github.com/vector-im/riot-web/issues/10311 (so yes, that PR should do it)

**Closed by turt2live** 2019-07-11 13:47 UTC
Labels: p1
