### ISSUE TITLE
Add a button (next to stickers selection) to interactively choose smiles

### ISSUE THREAD

**Issue by dogsleg** [vector-im/riot-web#7088] opened 2018-07-25 16:39 UTC
### Description

Add a button (next to stickers selection) to interactively choose smiles. Sometimes it is not very convenient to type and search for relevant smile, it would be more convenient to have a menu with all available smiles.

### Steps to reproduce

Well, there's nothing to reproduce, it's an UX issue, it's just there. ;-)

### Version information

- **Debian GNU/Linux**: Firefox 62.0b3, riot.im/app

**Comment by t3chguy** [comment] 2018-07-25 17:11
Duplicate of #1107

**Closed** 2018-07-25 17:11 UTC
