### ISSUE TITLE
Getting search failures due to locked & malformed DB in Seshat.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13123] opened 2020-04-10 19:06 UTC
<img width="790" alt="Screenshot 2020-04-10 at 20 05 15" src="https://user-images.githubusercontent.com/1294269/79016420-caf29e80-7b66-11ea-97f5-6c508fd0bc4b.png">

<img width="785" alt="Screenshot 2020-04-10 at 20 05 21" src="https://user-images.githubusercontent.com/1294269/79016377-b31b1a80-7b66-11ea-85cd-d0d5ac04c074.png">

**Comment by poljar** [comment] 2020-04-10 19:25
Is the DB actually corrupted? Does opening it using the CLI tool still work?

**Comment by ara4n** [comment] 2020-04-14 11:31
it doesn't seem to be corrupted; hitting search again mostly works.

**Comment by poljar** [comment] 2020-04-21 07:03
Duplicate of https://github.com/vector-im/riot-web/issues/13108.

**Closed by poljar** 2020-04-21 07:03 UTC
Labels: bug, type:indexing
