### ISSUE TITLE
Replace native titlebar on desktop

### ISSUE THREAD

**Issue by iamtheoneaboveall** [vector-im/riot-web#9462] opened 2019-04-14 02:36 UTC
It would be very visually appealing and improve immersion if Riot desktop client on Windows and other OS possibly replaced the native title bar look with a custom dark one, kind of like what discord does as you can see here :  https://i.imgur.com/sfGghgp.png

**Comment by turt2live** [comment] 2019-04-14 02:44
Duplicate of https://github.com/vector-im/riot-web/issues/8302

**Closed by turt2live** 2019-04-14 02:44 UTC
