### ISSUE TITLE
Bots stay on Invited and don't join the rooms

### ISSUE THREAD

**Issue by OXERY** [vector-im/riot-web#14203] opened 2020-06-25 13:25 UTC
### Description

Whatever Bot i add, it stays on "invited" and doesn't join the room.
![image](https://user-images.githubusercontent.com/29032586/85727912-b77fba00-b6f7-11ea-83da-442ee7079453.png)
The Synapse logging is pretty much killing me, I don't see any useful information in there. Do you have any idea where I could take a look at? Asked in the Riot-room a few weeks before, but nobody was able to answer.

### Version information

- **Platform**: desktop
- **OS**: Windows 10
- **Version**: 1.6.6

**Comment by t3chguy** [comment] 2020-06-25 13:27
Duplicate of https://github.com/vector-im/riot-web/issues/3366

**Closed by t3chguy** 2020-06-25 13:27 UTC
