### ISSUE TITLE
New key verification is broken on riot-web desktop

### ISSUE THREAD

**Issue by pravi** [vector-im/riot-web#7173] opened 2018-08-15 18:38 UTC
It only allows "send anyway" which results in unreadable messages. Android app handles this correctly. At the key verification pop up, one can cancel verification and resend the message. But on desktop, even after cancel verification, a resend still pops up the verification screen.

This is riot-web 0.16.0 on debian.

**Comment by lampholder** [comment] 2018-08-20 13:04
I haven't been able to reproduce this I'm afraid.

When I send a message into a room which has devices my client hasn't seen before, I get the 'Message not sent due to unknown devices' popup:
![image](https://user-images.githubusercontent.com/1922197/44341980-842bce80-a481-11e8-89b7-558fba6db377.png)

For me, I can:
- click 'show devices' which shows the list of unknown devices in a modal
- click 'send anyway' when sends the message encrypted for the unknown devices, but without marking them as verified (the other devices could then read these messages when I checked)
- click 'cancel' which aborts the message send

It sounds like you're clicking 'send anyway' but finding that the recipients _can't_ read the message - is that right? Would you and a recipient be able to submit some debug logs (go to user settings, scroll right to the bottom and click 'submit debug logs' - if you put this github issue in the relevent box, too, that would be super helpful :smile: )

Thanks!

**Comment by lampholder** [comment] 2019-04-30 12:16
Not heard anything on this for a long time, so closing

**Closed by lampholder** 2019-04-30 12:16 UTC
Labels: bug, cannot-reproduce, type:e2e
