### ISSUE TITLE
Why do we show "verify by emoji?" button when that's the only choice?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#13218] opened 2020-04-16 15:29 UTC
When verifying web<->web, the only supported SAS mechanism is emoji. Why do we make the user click on the single "verify by emoji" button when they have no other choice?

**Comment by t3chguy** [comment] 2020-04-16 16:09
Duplicate of https://github.com/vector-im/riot-web/issues/12995

**Closed by t3chguy** 2020-04-16 16:09 UTC
Labels: bug
