### ISSUE TITLE
"Invite" not going away. 

### ISSUE THREAD

**Issue by 153** [vector-im/riot-web#14420] opened 2020-07-11 12:27 UTC
### Description

I received an invite to a channel by a user. I see the buttons "accept", "reject and ignore user", "reject". Selecting any option presents the message `Failed to join room -- Cannot join user who was banned` and the "invite" remains. App used: riot web. 

### Steps to reproduce

- see invite to channel
- click any button
- get an error message
- invite does not go away 

Describe how what happens differs from what you expected.

Logs being sent: yes/no

### Version information

- **Platform**: web (in-browser) or desktop?

Web; 1.6.3-rc.1

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version?
Palemoon 28.10.0 x64
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
Windows 7 x64
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?
1.6.3-rc.1

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
- **Version**: 1.x.y

**Comment by turt2live** [comment] 2020-07-11 16:46
Duplicate of https://github.com/vector-im/riot-web/issues/7362

**Closed by turt2live** 2020-07-11 16:46 UTC
Labels: bug
