### ISSUE TITLE
skipping time in the video player just pauses the video

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#13265] opened 2020-04-18 19:29 UTC
### Description

It's not possible to skip to a specific point in the video player. I can drag&drop the slider in that progress bar thingy, but it just pauses for a short moment and then resumes playing from the initial time before I dragged the slider.

The only time skip that works is the one to 0:00

![image](https://user-images.githubusercontent.com/1029578/79669111-8c3d9380-81b9-11ea-9dc0-bbd3770fb29f.png)

I've also made a video:
https://kskcloud.de/s/biRryMajEAWotb9

### Steps to reproduce

- receive a video
- play the video from within riot
- try to skip to a specific point in the video

I'd expect to skip to that point. Instead it just pauses the video for a moment.

Logs being sent: yes

### Version information

- **Platform**: [desktop](url)
- **OS**: Arch Linux
- **Version**: 2020041801 (nightly)

**Comment by t3chguy** [comment] 2020-04-18 21:04
Duplicate of https://github.com/vector-im/riot-web/issues/4265
it is actually a Synapse issue: https://github.com/matrix-org/synapse/issues/4780

**Closed by t3chguy** 2020-04-18 21:04 UTC
Labels: bug
