### ISSUE TITLE
Make the desktop app and the mobile app, multi account capable.

### ISSUE THREAD

**Issue by hhassey** [vector-im/riot-web#7381] opened 2018-09-24 20:50 UTC
### Description FEATURE REQUEST
Most users that have set their servers will actually have more than one, at least your.own.server and matrix.org. in many cases we have more.

I am a person that has adopted matrix for work communications. but also implemented a personal use server. it is impossible for me to use both on my mobile, because I can only have one account in it, and same thing on the desktop app.

We need to have multi account capabilities on our clients!

**Comment by t3chguy** [comment] 2018-09-25 09:09
Closing as duplicate of https://github.com/vector-im/riot-web/issues/2320

**Closed by t3chguy** 2018-09-25 09:09 UTC
