### ISSUE TITLE
Redesign: Community button three-dot menu low-contrast

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#8240] opened 2019-01-23 16:06 UTC
- **Browser**: Chrome
- **OS**: Debian Linux

### Description

The three-dot menu icon that appears when a community is hovered over has a very similar color to the `...` that's shown inside of it, making it look a bit messy overall. Would suggest updating to the redesign color scheme.

![community-light](https://user-images.githubusercontent.com/1342360/51619712-d093a280-1f28-11e9-91f6-7c0b89c1178c.png)

**Comment by yannicka** [comment] 2020-07-17 13:50
![image](https://user-images.githubusercontent.com/22885898/87793045-00351980-c845-11ea-8ac2-5129bc37d076.png)

I can't reproduce the issue (on Element Desktop 1.7.1). Do you still have it?

**Comment by t3chguy** [comment] 2020-07-17 14:04
Closing as fixed by new theming

**Closed by t3chguy** 2020-07-17 14:04 UTC
Labels: bug, cosmetic, minor, p2, redesign, ui/ux
