### ISSUE TITLE
Option to toggle "always view timestamp for messages"

### ISSUE THREAD

**Issue by derWalter** [vector-im/riot-web#3497] opened 2017-03-23 16:33 UTC
Title says it all, I would like to have an option to to toggle timestamp with every message, without having to hover over it with my mousepointer.

kinda, like it is in irc.
people comming from irc are used to very compact views and a lot of information on the screen, wasting no space and having everything available in front of them :+1:

**Comment by lampholder** [comment] 2017-03-28 13:08
This is a duplicate of #58 and is mentioned in #2984, so closing, but 👍 👍 👍  I would like to see this feature very much :)

**Closed by lampholder** 2017-03-28 13:08 UTC
