### ISSUE TITLE
No more tray icon

### ISSUE THREAD

**Issue by mase76** [vector-im/riot-web#13583] opened 2020-05-07 16:37 UTC
Hi!
Since I updated to 1.6.0 in Debian Testing, there is no more tray icon. I am using XFCE, but also an I3 user reported to me, that the icon is not there. I checked, that it is activated in the settings. However the client keeps running, but invisible.

**Comment by turt2live** [comment] 2020-05-07 16:38
Duplicate of https://github.com/vector-im/riot-web/issues/12518

**Closed by turt2live** 2020-05-07 16:38 UTC
Labels: bug

**Comment by gerroon** [comment] 2020-05-11 00:00
@turt2live 

I actually lost the tray icon in 1.6.0.1 on Debian Testing. This was working prior to this version, so I am not sure if it is a duplicate of that bug you referenced. It seems like that issue was showing up prior to the Desktop rebranding.

**Comment by turt2live** [comment] 2020-05-11 06:53
@gerroon that bug was created when we upgraded to Electron 8, which we quickly reverted due to the issue. The bug re-appeared in 1.6.0

**Comment by tycho-kirchner** [comment] 2020-05-11 13:25
Could someone of the contributors please re-enable commenting for [ #12518](https://github.com/vector-im/riot-web/issues/12518)?

I am using the xfce4-statusnotifier-plugin (not the old XEmbed tray) on xfce and it
stopped working from riot 1.6. Before that version it was using the statusnotifier correctly.

I mention this, because in  [this](https://github.com/vector-im/riot-web/issues/12518#issuecomment-621702146) comment, snixembed is mentioned, as if the dropped support for XEmbedded systemtray-spec icons was the problem here **which it is not** (in my case).

**Comment by t3chguy** [comment] 2020-05-12 09:33
@tycho-kirchner what distribution of riot-desktop are you using? The official deb repo? Flatpak? Snap?

**Comment by tycho-kirchner** [comment] 2020-05-12 09:37
Official deb-repo on Debian Buster and Debian Stretch.

**Comment by t3chguy** [comment] 2020-05-12 09:38
#12518 is unlocked

**Comment by tycho-kirchner** [comment] 2020-05-12 09:40
Thanks. Shall I cross-post the issue there as well?

**Comment by t3chguy** [comment] 2020-05-12 09:41
It'll get more attention than in a closed issue so perhaps that is best
