### ISSUE TITLE
Copy icon alignment in code listings

### ISSUE THREAD

**Issue by pacien** [vector-im/riot-web#6631] opened 2018-04-28 16:07 UTC
### Description

In code listings, the copy button follows horizontal scrolling instead of staying in place.

### Steps to reproduce

- Send a code listing with a long line with markdown enabled
- Scroll right and observe

![15249314028623](https://user-images.githubusercontent.com/1449319/39398456-88c6c534-4b0e-11e8-907e-a80039585c17.png)

![15249314211167](https://user-images.githubusercontent.com/1449319/39398457-8e3739fe-4b0e-11e8-91a6-49b2a28d1361.png)

### Version information

- **Platform**: "desktop"
- **Version**: 0.14.1
- **OS**: Debian 9.4

**Comment by t3chguy** [comment] 2018-04-28 16:30
Duplicate of https://github.com/vector-im/riot-web/issues/4341

**Closed by t3chguy** 2018-04-28 16:30 UTC
