### ISSUE TITLE
Editing a message while sending no longer sends the edit

### ISSUE THREAD

**Issue by Cadair** [vector-im/riot-web#12318] opened 2020-02-11 14:16 UTC
### Description

Send a message, while it's still sending edit the message. The edit is ignored.

For the desktop app:

- **OS**: Arch
- **Version**: ~develop

**Comment by t3chguy** [comment] 2020-02-11 14:21
Duplicate of https://github.com/vector-im/riot-web/issues/11834

**Closed by t3chguy** 2020-02-11 14:21 UTC
Labels: bug

**Comment by Cadair** [comment] 2020-02-11 14:25
I clearly did not search hard enough.
