### ISSUE TITLE
add options for enable "pin-code" for enter in Riot-web

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-web#10661] opened 2019-08-27 05:24 UTC
If user use Riot on work PC - admins will can access to secret chats of user. Logout from Riot is not variant because we lost validated device. And then, when user will login again - He get new device, which need to be validated - again and again - on every day. This is not nice.

If Riot-web will have option "pin-code for enter" - this will can help user lock his Riot-web and go home. If admins will try access to users private chats in his computer on users account - they can not do this, because they do not know "pin-code" for enter riot-web.

At next work day user will open riot-web, enter his pin-code and get access to his secret chats.

**Comment by t3chguy** [comment] 2019-08-27 07:39
Duplicate of #3777

**Closed** 2019-08-27 07:39 UTC
Labels: suggestion
