### ISSUE TITLE
unread message count does not get updated when reading messages that get received after the view for the room got opened

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-web#4461] opened 2017-06-29 13:53 UTC
### Description

Unread messages count on room and in the badge differs when reading messages that got received after the view opened

### Steps to reproduce

- Open a room with lots of unread messages (at least less then could fit the screen)
- Jump/Scroll up to not see the latest message anymore
- Wait for messages to get send. This causes the number on the room and in the buttom of the room to count up
- scroll down to read one of those messages

In this situation the number at the room gets updated and decreases but the number at the badge does not

![image](https://user-images.githubusercontent.com/11167142/27690661-3eb518d0-5ce2-11e7-9b96-c18f79529482.png)
### Version information

- **Platform**: web
- **Browser**: Chrome
- **OS**: Windows
- **URL**: self-compiled on current develop (js/react-sdk and riot-web)

**Comment by turt2live** [comment] 2017-06-29 18:41
Is your self-compiled version using https://github.com/matrix-org/matrix-react-sdk/pull/821 by chance? If so, that would be why.

**Comment by lampholder** [comment] 2017-07-05 15:08
Flagged as p1 major but from @turt2live's comment it sounds like this might already be fixed?

**Comment by turt2live** [comment] 2017-07-05 16:03
@lampholder further testing shows my comment is unrelated - sorry. This is an issue, and I can reproduce it

**Comment by MTRNord** [comment] 2017-07-05 17:06
PS: I got the same error on 2 devices with the new android version. Is this maybe a synapse issue?

**Comment by krombel** [comment] 2017-07-06 10:05
I do not think that this is an synapse issue.
I think that it is "just" a missing update-call to decrease the number in the lower badge of the room.
The "new message count" decreases in the left panel when messages got read that were received after the room opened but in the lower badge they are just increased on new messages and disappear when the end of the timeline got reached

**Comment by MTRNord** [comment] 2017-07-06 10:07
NVM my issue was that my synapse was outdated and there wasn't a fallack for the needed api endpint in the client.

**Comment by lukebarnard1** [comment] 2017-07-11 14:18
This is because the two numbers are not derived from the same information. The number in the room list is generated by the notification logic in synapse and is sent down the `/sync` stream. The number in the status bar in the room view is the number of messages that were received since you've scrolled up - they're totally orthogonal and shouldn't be in sync.

However, this UX is clearly super confusing and maybe we should do something different.

**Comment by turt2live** [comment] 2017-09-05 15:40
I've started seeing this more often in the last few days on riot.im/develop

It's always the same rooms, some of which were problem rooms before and have resurrected their unread status.

**Comment by turt2live** [comment] 2020-07-10 03:16
Fixed in the 2020 room list

**Closed by turt2live** 2020-07-10 03:16 UTC
Labels: bug, major, p1
