### ISSUE TITLE
Reactions in encrypted rooms still have stuck notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10169] opened 2019-06-25 15:14 UTC
I sent a message to Tom, who liked it, and I got stuck with a badge: ![](https://i.imgur.com/RnOuwvM.png)

**Comment by jryans** [comment] 2019-06-25 15:31
Duplicate of https://github.com/vector-im/riot-web/issues/10130

**Closed by jryans** 2019-06-25 15:31 UTC
