### ISSUE TITLE
Invite-only channels show as "guests can join" in listings

### ISSUE THREAD

**Issue by 5chdn** [vector-im/riot-web#5744] opened 2017-11-30 11:22 UTC
### Description

Invite-only channels show as "guests can join" in listings.

### Steps to reproduce

- Create a channel
- Set "WHO CAN ACCESS THIS ROOM?" to "Only people who have been invited"
- Set "Publish this room" to "false" (uncheck)
- Find

Invite-only channels show as "guests can join" in listings.

Log: not sent

Screenshot available in #5742 and #5743

### Version information

- **Platform**: web in-browser and web in-rambox.

For the web app:

- **Browser**: Chrome 62, and Firefox 57?
- **OS**: Arch Linux
- **URL**: riot.im/app

**Comment by turt2live** [comment] 2017-11-30 15:56
Duplicate of https://github.com/vector-im/riot-web/issues/5317

**Closed** 2017-12-01 09:11 UTC
