### ISSUE TITLE
Auto update on Mac restricted account breaks app

### ISSUE THREAD

**Issue by MacLemon** [vector-im/riot-web#8215] opened 2019-01-22 14:37 UTC
### Description

After autoupdate to Riot 0.17.9 the application doesn't launch anymore.

### Steps to reproduce

- Run Riot 0.17.8 on macOS
- get prompted that an update is available
- authorise with admin credentials
- click [Update] button
- wait for update to be applied
- be presented with an error message that the new application cannot be launched anymore.

You're now unable to use Riot.app.

### Describe how what happens differs from what you expected.

I'd expect the update to apply and the application to keep launching afterwards.

Log: sent/not sent?    
Can't find that function in the macOS Electron client.

Error message presented by macOS after the update indicating that the application cannot be run anymore.
![screen shot 2019-01-22 at 15 13 35](https://user-images.githubusercontent.com/90635/51541819-10d81f80-1e5a-11e9-881d-b6d4558c5d88.png)

### Version information

For the desktop app:

- **OS**: macOS Sierra 10.12.6 (16G1710)
- **Version**: Riot.app 0.17.9

This is a regression from 0.17.8 which worked fine on the same system.
There is no indication about incompatibility of the update with macOS before the update is installed or at all. The [Changelog](https://github.com/vector-im/riot-web/compare/v0.17.9-rc.1...v0.17.9) doesn't mention an increased system requirement.

### Workaround
You can manually downgrade to a working Riot.app 0.17.8 by editing the download URL to https://riot.im/download/desktop/install/macos/Riot-0.17.8.dmg

### Intuition
From the crash report it looks like the packaging for macOS is missing to include a required library.

```
Process:               Riot [59354]
Path:                  /Applications/Riot.app/Contents/MacOS/Riot
Identifier:            im.riot.app
Version:               0.17.9 (0.17.9)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Riot [59354]
User ID:               501

Date/Time:             2019-01-22 15:13:28.059 +0100
OS Version:            Mac OS X 10.12.6 (16G1710)
Report Version:        12
Anonymous UUID:        D9CAFAAA-AA40-317B-54AC-7B9694E1C3A5

Sleep/Wake UUID:       10C93AAF-9466-4F49-90FF-05D98F1485FE

Time Awake Since Boot: 320000 seconds
Time Since Wake:       50000 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Riot.app/Contents/MacOS/Riot
  Reason: no suitable image found.  Did find:
	/Applications/Riot.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=13

Binary Images:
       0x104e82000 -        0x104e82ffb +im.riot.app (0.17.9 - 0.17.9) <0B17EBD3-270D-3C7F-A47F-A50793EC943D> /Applications/Riot.app/Contents/MacOS/Riot
       0x108859000 -        0x108896dc7  dyld (434) <33DB4E37-BC29-37A4-92AB-30328E66A8FA> /usr/lib/dyld
    0x7fff9a288000 -     0x7fff9a288fff  com.apple.Cocoa (6.11 - 22) <85EDFBE1-75F0-369E-8CA8-C6A639B98FA6> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff9c2b6000 -     0x7fff9c65cff3  com.apple.Foundation (6.9 - 1349.92) <99B1320B-7E15-3E84-AB6E-574B57E81D64> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff9c81d000 -     0x7fff9c8b3ff7  com.apple.framework.IOKit (2.0.2 - 1324.60.6) <72AEAC01-3FDF-3F0F-8A4F-1D7CB00B569C> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fffa1061000 -     0x7fffa1363fff  com.apple.security (7.0 - 57740.60.26) <1C910BB7-5E7C-3738-BB1F-4118C0BBB5A2> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fffa178e000 -     0x7fffa17fdff7  com.apple.SystemConfiguration (1.14 - 1.14) <9B617B63-75E0-3F49-90F9-54C384C66063> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
```

**Comment by ara4n** [comment] 2019-01-22 15:01
it's working okay on Mojave. we're investigating.

**Comment by MacLemon** [comment] 2019-01-22 15:08
Sorry, my hardware doesn't support Mojave anymore. macOS Sierra is still an officially supported release by Apple.

**Comment by ara4n** [comment] 2019-01-22 15:10
yup, my point was just the datapoint that whatever's up doesn't appear to affect Mojave.

**Comment by MacLemon** [comment] 2019-01-22 15:22
I found out how to send debug logs from the Electron client. (buried in Settings at the bottom…)
Sent them with reference to this issue. Hope this helps.

**Comment by dbkr** [comment] 2019-01-22 15:52
This looks like a permissions error so this could be a regression in Electron / squirrel where it's not setting the perms correctly when updating an app it doesn't normally have write permission to. In the meantime, could you try downloading 0.17.9 directly and running it rather than letting it auto-update?

**Comment by dbkr** [comment] 2019-01-22 16:18
I've reproduced this locally with a restricted user account: the Electron framework is not getting its permission set correctly on the update. I'll see if this regression has been reported in the relevant place upstream and get it fixed. In the meantime, installing 0.17.9 directly from the DMG should work for you.

**Comment by dbkr** [comment] 2019-01-23 10:57
This seems to be fixed in the latest electron-builder so this shouldn't be a problem for the next update. Apologies to anyone affected by this: if the 0.17.9 update has broken your Riot, re-installing from https://riot.im/desktop.html will fix it.

**Closed by dbkr** 2019-01-23 10:57 UTC

**Comment by pkrasam** [comment] 2019-11-30 08:35
I am on `macOS Cataline Version 10.15.1` and the current Riot fires up okay, and nothing happens -- no screen -- can't tell what is happening? Is anyone else having similar issues?

**Comment by tristan957** [comment] 2020-02-26 20:06
@pkrasam I am having this same issue. When I start the application no window opens, but the application is definitely open....

**Comment by Pol-Lanski** [comment] 2020-07-16 05:40
Well, now it's happening to me. Firing up "Element (Riot)" and nothing happens. The icon on the dock does get red notification buttons if people message you, though.

**Comment by t3chguy** [comment] 2020-07-16 06:02
@Pol-Lanski try https://github.com/vector-im/riot-web/issues/12402#issuecomment-654187533

**Comment by Pol-Lanski** [comment] 2020-07-16 07:17
> @Pol-Lanski try [#12402 (comment)](https://github.com/vector-im/riot-web/issues/12402#issuecomment-654187533)

That worked! Thanks a lot!
