### ISSUE TITLE
Close button clips into title when waiting for self-verification to complete

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13014] opened 2020-04-02 18:58 UTC
![image](https://user-images.githubusercontent.com/1190097/78290869-a56bf200-74e1-11ea-8cf2-96021bb7bcaa.png)

**Comment by jryans** [comment] 2020-05-20 11:52
Duplicate of https://github.com/vector-im/riot-web/issues/12717

**Closed by jryans** 2020-05-20 11:52 UTC
Labels: bug, feature:e2e-cross-signing, phase:4, story:1
