### ISSUE TITLE
Sometimes browsers don't let call ringing sounds play 

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#11457] opened 2019-11-21 16:05 UTC
When we try to play sounds, eg. the call ringing sound, sometimes the browsers will decide we are not allowed to do that, eg. chrome goes:

```
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
```

According to the link, autoplay is supposed to be allowed if the user has interacted with the domain (ie. click or tapped) but empirically this is not the case (I am still getting this error when calling myself after clicking multiple times within Riot, even switching rooms).

**Comment by turt2live** [comment] 2019-11-21 16:26
Duplicate of https://github.com/vector-im/riot-web/issues/7657

**Closed by turt2live** 2019-11-21 16:26 UTC
