### ISSUE TITLE
Feature request: More details of Users like deaprtment, location, function, for internal use

### ISSUE THREAD

**Issue by ppabst** [vector-im/riot-web#11612] opened 2019-12-05 15:33 UTC
Hello,
we use riot.im for the internal communilation of our employees. 
Many employees do not know each other personally or even work in a different location. 
In the riot.im currently only the name, mail and phone can be read out via LDAP. 
It would be helpful if additional information about the employee from the LDAP can be displayed in the rioit.im, such as: Department, location, function

**Comment by turt2live** [comment] 2019-12-05 18:13
Duplicate of https://github.com/vector-im/riot-web/issues/1401

**Closed by turt2live** 2019-12-05 18:13 UTC
Labels: suggestion
