### ISSUE TITLE
remove /tint Command

### ISSUE THREAD

**Issue by NotAFile** [vector-im/riot-web#8950] opened 2019-02-26 14:17 UTC
the tint command is now unnecessary, unless there are plans to re-add tinting I guess

**Comment by jryans** [comment] 2019-02-26 14:33
The status of tinting is currently unclear. I think I'll mark this as a duplicate of https://github.com/vector-im/riot-web/issues/8421 for now. The reference there should remind us to do this (if decision is to remove it entirely).

**Closed by jryans** 2019-02-26 14:33 UTC
