### ISSUE TITLE
Can’t deactivate account on https://chat.mozilla.org

### ISSUE THREAD

**Issue by sideshowbarker** [vector-im/riot-web#12594] opened 2020-03-03 05:41 UTC
### Description

I’m unable to deactivate my account on https://chat.mozilla.org (while logged in from SSO via GitHub).

### Steps to reproduce

While logged into https://chat.mozilla.org from SSO via GitHub, I go under my account to Settings > General and press the <kbd>Deactivate Account</kbd> button.

That gives me a modal where I need to type in a password before I can press the <kbd>Deactivate Account</kbd> in that modal. I type in my password, and press the <kbd>Deactivate Account</kbd> button there, and I get a message saying **Unknown error**.

I try typing in another password, but I get the same **Unknown error** message regardless of what I type in.

Imagining it’s possible that I got the password wrong, I go to https://chat.mozilla.org/#/forgot_password and I try typing in my e-mail address and new password and then pressing <kbd>Send Reset Email</kbd> there.

But then I get a *Failed to send email: This email address was not found* message — which is not surprising, given that I’m logged in from SSO via GitHub and I don’t recall ever registering an e-mail address for the https://chat.mozilla.org account.

Given all that, I can’t seem to have any way to deactivate my account, nor to reset whatever password the system seems to be expecting me to type in when I try to deactivate the account.

Logs being sent: yes

### Version information

Platform: web (in-browser)
Browser: Chrome, Safari, Firefox
OS: macOS
URL: https://chat.mozilla.org/, https://chat.mozilla.org/#/forgot_password

**Comment by turt2live** [comment] 2020-03-03 06:19
Duplicate of https://github.com/vector-im/riot-web/issues/10847

**Closed by turt2live** 2020-03-03 06:19 UTC
Labels: bug
