### ISSUE TITLE
Room Icons are now larger in the new Element layout limiting the on screen rooms visible

### ISSUE THREAD

**Issue by Cerothen** [vector-im/riot-web#14519] opened 2020-07-16 01:58 UTC
### Description

Below you can see the same user logged into Riot and Element side by side as you can see I use a narrow view and with the new update more real estate for the rooms panel, in addition to that the icons themselves are larger which means that less rooms are on the screen for the same screen real estate which is also not as useful since there is no way to reduce that.

Element shows 14 rooms and Riot shows 22 rooms which is nearly a 40% reduction in visible rooms (and in this case Riot is in the browser and therefore loses space to the nav bar and bookmarks).

### Steps to reproduce

- Load both Element and Riot and look at the layout

Describe how what happens differs from what you expected.

Logs being sent: No

![Element](https://user-images.githubusercontent.com/9008757/87617241-02806200-c6e5-11ea-9529-f7a12dd0d236.PNG)
![Riot](https://user-images.githubusercontent.com/9008757/87617243-04e2bc00-c6e5-11ea-9d0e-13418f759d22.PNG)

### Version information

Applies to all electron and browser versions

**Comment by turt2live** [comment] 2020-07-16 02:06
Duplicate of https://github.com/vector-im/riot-web/issues/14099

**Closed by turt2live** 2020-07-16 02:06 UTC
Labels: bug, ui/ux
