### ISSUE TITLE
Add option to disable emojione and use native emojis instead

### ISSUE THREAD

**Issue by yangm97** [vector-im/riot-web#9102] opened 2019-03-11 02:23 UTC

**Comment by turt2live** [comment] 2019-03-11 02:40
I'm not sure if there's an issue for it, but I believe the plan is to actually remove emojione from the whole app for several reasons:
1. It's slow
2. It's big
3. It doesn't really provide what we wanted it to provide
4. Other alternatives might exist which better fit our needs
5. Some other reasons I'm probably forgetting

**Comment by t3chguy** [comment] 2019-03-11 06:35
Duplicate of #7356

**Closed** 2019-03-11 06:35 UTC
