### ISSUE TITLE
Riot will not allow me to login if my nameserver is down. 

### ISSUE THREAD

**Issue by wmmnola** [vector-im/riot-web#2910] opened 2017-01-10 22:23 UTC
If I login to a custom Namesever, and that nameserver goes down, riot will not allow me to change my nameserver.

**Comment by uhoreg** [comment] 2017-01-12 17:06
Do you mean Identity Server?

**Comment by ara4n** [comment] 2017-02-19 00:39
I'm going to assume this is a dupe of https://github.com/vector-im/riot-web/issues/2734

**Closed by ara4n** 2017-02-19 00:39 UTC
