### ISSUE TITLE
Riot seems to do markdown parsing inside URLs, rendering them invalid

### ISSUE THREAD

**Issue by staktrace** [vector-im/riot-web#13496] opened 2020-05-04 16:55 UTC
### Description

When pasting a URL like `https://searchfox.org/mozilla-central/source/__GENERATED__/__android-armv7__/dist/include/mozilla/dom/GeneratedAtomList.h` into Riot, Riot will treat the underscore characters in the URL as markdown, breaking up the URL and rendering components of the path as bold. This is obviously undesirable as it breaks URLs.

### Steps to reproduce

- Log in to a Riot instance (e.g. chat.mozilla.org)
- Go to a channel (e.g. #searchfox:mozilla.org)
- Paste a URL like `https://searchfox.org/mozilla-central/source/__GENERATED__/__android-armv7__/dist/include/mozilla/dom/GeneratedAtomList.h` into the chat

Describe how what happens differs from what you expected.

<img width="832" alt="Screen Shot 2020-05-04 at 12 52 29" src="https://user-images.githubusercontent.com/485789/80991488-216d9880-8e06-11ea-8908-f04e0daa376a.png">

^ screenshot shows what happens. Expectation is that the URL renders as... one would expect. i.e. no bold pieces, the entire thing gets linkified to the right destination.

### Version information

- **Platform**: web (in-browser) or desktop?

Web

For the web app:

- **Browser**: Firefox 75.0
- **OS**: macOS
- **URL**: chat.mozilla.org,  riot-web version: v1.5.15. olm version: 3.1.3

**Comment by staktrace** [comment] 2020-05-04 16:57
Link to bugzilla bug for posterity: https://bugzilla.mozilla.org/show_bug.cgi?id=1635188

**Comment by turt2live** [comment] 2020-05-04 17:05
Duplicate of https://github.com/vector-im/riot-web/issues/4674

**Closed by turt2live** 2020-05-04 17:05 UTC
Labels: bug
