### ISSUE TITLE
Cannot scroll using touchpad

### ISSUE THREAD

**Issue by MparkG** [vector-im/riot-web#10533] opened 2019-08-11 11:23 UTC
> i still (for/after multiple versions) cant scroll using my touchpad. Only the Settings window can be scrolled with it. No chat list, no chat itself, no member list, nothing on the main screen. Using a mouse however it works. Obviously in any normal program, including every other website, the touchpad does in fact scroll. Thanks!

**Comment by turt2live** [comment] 2019-08-11 18:35
@MparkG which operating system are you using?

**Comment by MparkG** [comment] 2019-08-11 18:37
Windows

Am 11. August 2019 20:35:31 MESZ schrieb Travis Ralston <notifications@github.com>:
>@MparkG which operating system are you using?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/riot-web/issues/10533#issuecomment-520250303

-- 
Max vom Telefon

**Comment by turt2live** [comment] 2019-08-11 18:45
I believe this is a duplicate of https://github.com/vector-im/riot-web/issues/8778 then. Thanks for reporting!

**Closed by turt2live** 2019-08-11 18:45 UTC
