### ISSUE TITLE
Jump to first unread message: does not jump, and the prompt to jump persists

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/riot-web#3746] opened 2017-04-27 02:11 UTC
### Description

At https://riot.im/develop/#/room/#riot:matrix.org the prompt to jump became ineffective.

### Steps to reproduce

As far as I recall: 

- I sped through a number of pages of unread messages
- no appearance of a prompt to jump
- the absence of a prompt seemed contrary to the excessive prompting that was recently mentioned at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1493142037349322RBKPm:matrix.org
- aiming to understand how I might have overcome the excessive prompting, I varied my paging behaviours (sometimes pointing at messages, without clicking, after using the keyboard alone to page; and so on) 
- I experimented with the pointer at either side of the message column before using the keyboard alone to page
- eventually a prompt to jump appeared
- I soon realised that jumping did not (or had ceased to) occur but (sorry) I can't recall whether the affected prompt was the first, or a subsequent prompt
- I recorded the screen
- whilst recording, I keyed F11 to take the Firefox window full screen (I _might_ have also entered then exited full screen some time _before_ observing the bug … in and out of full screen is the type of action that I perform instinctively, without making a mental note of the action)
- after recording, whilst drafting this report, I prepared to send the application log but those preparations failed. 

### Version information

- Firefox 53.0 (64-bit)
- TrueOS Desktop
- https://riot.im/develop/#/room/#riot:matrix.org

```text
$ about

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170330_080908 NR 2017-03-30
       after restart (R) … 12.0-CURRENT-up-20170330_080908 NR 2017-03-30
boot loader …………………………………… BSD
            type ……………………… EFI
CPU ………………………………………………………… Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
    number of cores ……………… 4
host ……………………………………………………… momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
memory ………………………………………………… 16384 MB available, 4279 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… a009033ff
OS kernel build time ………………………………………………………… Wed 2017 Mar 29 20:13:33 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… CUSTOM
TrueOS version …………………………… TrueOS-Desktop-201703201429
uptime ………………………………………………… 8:38
user  …………………………………………………… grahamperrin

More (TrueOS Desktop):

    desktop environment …… KDE
    sound card driver ………… pcm1: <Realtek (0x0280) (Analog 2.0+HP/2.0)> on hdaa1  (1p:2v/1r:4v) default
    wireless driver ……………… iwm0
    X11 drivers ………………………… intel_drv.so 

$ 
```

[2017-04-27 02-47 Firefox troubleshooting information.txt](https://github.com/vector-im/riot-web/files/960240/2017-04-27.02-47.Firefox.troubleshooting.information.txt)

**Comment by grahamperrin** [comment] 2017-04-27 02:29
## Screen recording

In my new _Riot_ album at https://goo.gl/photos/xmKAnhE3WDsLQLFj8

## Application log

Sent, with reference to this issue but I suspect that **part of the log may be misleading** because before I had an opportunity to send it, the application lost the ability to show settings. Screenshot below, this should be a separate issue: 

![2017-04-27 03-12-55](https://cloud.githubusercontent.com/assets/192271/25465293/3ac0a412-2af9-11e7-8df8-c8d3e89a3025.png)

(Notes to self: maybe lost after an attempt to escape from the bug reporting dialogue; and at some point after that shot, I observed a URL for a different room (not the Riot room) in the address field of Firefox.)

For me to regain the ability to show settings, it might have been necessary to browse back and/or reload; if actions such as those were logged, maybe ignore them (and I hope that the relevant part of the log was not lost).

**Comment by grahamperrin** [comment] 2017-04-27 02:58
Maybe relevant, at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1493144151588XEmtU:riot.ovh (19:16, undated) 𝔱𝔷𝔠𝔥𝔤𝔲𝔶 wrote: 

> … joining a new room has the "Jump to first unread message" banner visible yet it doesn't go anywhere 
> on /develop/

**Comment by grahamperrin** [comment] 2017-04-27 06:47
For me the issue recurred after browsing: 

- from https://riot.im/develop/#/room/#riot:matrix.org/$1493151364489488bSikR:matrix.org
- to a room that I joined a few days ago, a room that I favoured then dragged to the top of my FAVOURITES before clicking, https://riot.im/develop/#/room/#bsd:matrix.org

Before jumping: 

![before](https://cloud.githubusercontent.com/assets/192271/25466474/c388eb5e-2b00-11e7-894d-d685997e7228.png)

After jumping – a spin of the asychronous progress indicator, then reappearance of the same set of messges: 

![after](https://cloud.githubusercontent.com/assets/192271/25466487/e1b51f26-2b00-11e7-860b-d4305d422614.png)

Preparing to browse back: 

![back menu](https://cloud.githubusercontent.com/assets/192271/25466502/fed35212-2b00-11e7-8d5b-a727830a80f6.png)

**Comment by lukebarnard1** [comment] 2017-04-27 08:48
This will hopefully be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/837

**Comment by grahamperrin** [comment] 2017-04-28 01:58
> … After jumping – a spin of the asychronous progress indicator, then reappearance of the same set of messges: …

Now at https://riot.im/develop/#/room/#bsd:matrix.org I have a comparable set of symptoms. 

>> **Jump to first unread message: does not jump, and the prompt to jump persists**

– that is true

> … asychronous progress indicator …

– that is not true. 

I _assume_ that it is the same underlying bug. I will use the application to send a log with reference to this comment. 

If not the same, please ask me to seek (or raise) a separate issue. Thanks.

**Comment by lukebarnard1** [comment] 2017-04-28 08:44
Sadly, there aren't any logs for debugging this, but thanks. @grahamperrin, could you give the steps to reproduce this?

**Comment by grahamperrin** [comment] 2017-04-28 09:54
Thanks, 

> Sadly, there aren't any logs for debugging this, …

Please, do you mean that even if I provide [a relatively clean log](https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$1493351288796839zgTEg:matrix.org) the log certainly will _not_ include information that might help to diagnose this issue?

**Comment by lukebarnard1** [comment] 2017-04-28 10:16
> Please, do you mean that even if I provide a relatively clean log the log certainly will not include information that might help to diagnose this issue?

yes

**Comment by lukebarnard1** [comment] 2017-04-28 13:25
So I think that this is being caused by MELS still, because you can't jump to an event that's in a MELS at all. This can be fixed by expanding a MELS if it contains the highlighted event ID.

**Comment by lukebarnard1** [comment] 2017-05-02 15:49
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/855

**Closed** 2017-05-02 15:49 UTC
Labels: bug, minor, p1

**Comment by grahamperrin** [comment] 2017-05-02 17:59
Thanks, is the fix rolled out yet? 

Not chasing, just curious. Bugged: 

![not jumping](https://cloud.githubusercontent.com/assets/192271/25631590/ca0d54da-2f68-11e7-9d3f-3b30500ac7f3.png)

In that shot: 

- the topmost message is https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$149321398321713fCFAR:matrix.org 
- a click on the prompt to jump is not followed by an asychronous progress indicator. 

> matrix-react-sdk version: 4f72450847b7739868bd258342b1510db58ad321
> riot-web version: 9f3c1deae600-react-4f72450847b7-js-acd7f15c8376
> olm version: v2.2.1

**Comment by lukebarnard1** [comment] 2017-05-02 19:57
@grahamperrin the referenced PR hasn't been merged yet, so no.

**Comment by grahamperrin** [comment] 2017-05-29 16:31
:+1: I have not seen this issue in a while. Thanks again.
