### ISSUE TITLE
Validation emails are being spamcanned again

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#2547] opened 2016-11-05 20:22 UTC
We seem to have reintroduced the "HTML_IMAGE_ONLY_28" rule again, presumably when rebranding for Riot :(

```
X-Spam-Report: 
        *  3.5 BAYES_99 BODY: Bayes spam probability is 99 to 100%
        *      [score: 1.0000]
        * -0.0 SPF_PASS SPF: sender matches SPF record
        *  0.2 BAYES_999 BODY: Bayes spam probability is 99.9 to 100%
        *      [score: 1.0000]
        *  1.4 HTML_IMAGE_ONLY_28 BODY: HTML: images with 2400-2800 bytes of words
        *  0.0 HTML_MESSAGE BODY: HTML included in message
        *  1.1 DCC_CHECK Detected as bulk mail by DCC (dcc-servers.net)
        * -0.4 AWL AWL: Adjusted score from AWL reputation of From: address
```

**Comment by ara4n** [comment] 2016-12-24 01:18
this is still true on arasphere:

```
X-Spam-Report: 
    *  3.5 BAYES_99 BODY: Bayes spam probability is 99 to 100%
    *      [score: 1.0000]
    *  0.0 URIBL_BLOCKED ADMINISTRATOR NOTICE: The query to URIBL was blocked.
    *       See http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block
    *      for more information.
    *      [URIs: vector.im]
    * -0.0 SPF_PASS SPF: sender matches SPF record
    *  0.2 BAYES_999 BODY: Bayes spam probability is 99.9 to 100%
    *      [score: 1.0000]
    *  1.4 HTML_IMAGE_ONLY_28 BODY: HTML: images with 2400-2800 bytes of words
    *  0.0 HTML_MESSAGE BODY: HTML included in message
    *  1.1 DCC_CHECK Detected as bulk mail by DCC (dcc-servers.net)
    *  0.8 RDNS_NONE Delivered to internal network by a host with no rDNS
    * -0.3 AWL AWL: Adjusted score from AWL reputation of From: address
```

**Comment by lukebarnard1** [comment] 2017-03-31 09:49
According to http://serverfault.com/a/174022, the email needs to have more text in it! This could be quite simple.

**Comment by ara4n** [comment] 2017-03-31 10:36
@lampholder can you bulk out the verbiage a bit please? they live in https://github.com/matrix-org/sydent/tree/master/res and Dave can deploy when done (or show you how)

**Comment by lampholder** [comment] 2017-03-31 10:47
Heh, did we trigger this by removing the (broken) reference to the IP address?

/me takes a crack at the wording.

**Comment by ara4n** [comment] 2017-03-31 11:21
it was a problem before, but it probably got exacerbated by removing the IP address.  Worst case, just chuck a more detailed "You're receiving this because..." section at the bottom.

**Comment by lampholder** [comment] 2017-03-31 13:18
I've bulked it out significantly by borrowing some of the blurb from riot.im:

https://github.com/matrix-org/sydent/tree/registration_wording_change

@ara4n / @AmandineLP would you like to review the content? I conflated bulking out the word count with addressing a pet peeve about the email's somewhat robotic tone, because I'm a nuisance.

/me intends to fix up the matrix version of the file too after verifying that this change does indeed do the needful.

**Comment by lampholder** [comment] 2017-03-31 14:04
Our SpamAssassin score is now 0.0/5 (according to https://spamscorechecker.com/check anyway)

**Comment by lampholder** [comment] 2017-03-31 14:36
We're still triggering HTML_IMAGE_ONLY_20 on the matrix validation token email.

**Comment by lampholder** [comment] 2017-03-31 15:21
That's now fixed too.

**Comment by ara4n** [comment] 2017-04-01 11:08
this looks good but is there a reason we don't think that invite mails won't be suffering the same problem too?

**Comment by lampholder** [comment] 2017-04-03 08:43
We haven't changed invite emails recently AFAIK.

...but a quick check reveals they're every bit as bad: 

`* 1.6 HTML_IMAGE_ONLY_24 BODY:HTML: images with 2000-2400 bytes of words.`

**Comment by lampholder** [comment] 2017-04-03 08:44
Are there any other categories of email we send? Notification emails might be affected too?

**Comment by lampholder** [comment] 2017-04-21 10:26
I can confirm that I have not received notification emails (though my email setup is now... complicated so it's not super obvious where it might be being canned).

**Comment by ara4n** [comment] 2017-04-21 10:51
as a first cut please let's fix invite emails? they may not have been changed, but they were borderline problematic in the first place...

**Comment by lampholder** [comment] 2017-04-21 17:27
More words here: https://github.com/matrix-org/sydent/pull/44

**Comment by lampholder** [comment] 2017-04-21 17:40
Cool; changes merged for invites - I'll test against the spamwhatsit when they've been pushed live (which won't happen last thing on a Friday)

**Comment by ara4n** [comment] 2017-04-22 20:19
just to confirm, invites are indeed failing right now, with:

```
X-Spam-Status: Yes, score=6.0 required=5.0 tests=AWL,BAYES_99,BAYES_999,
    HTML_IMAGE_ONLY_28,HTML_MESSAGE,RCVD_IN_DNSWL_NONE,URIBL_BLOCKED autolearn=no
    autolearn_force=no version=3.4.1
X-Spam-Report: 
    *  0.0 URIBL_BLOCKED ADMINISTRATOR NOTICE: The query to URIBL was blocked.
    *       See http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block
    *      for more information.
    *      [URIs: matrix.org]
    * -0.0 RCVD_IN_DNSWL_NONE RBL: Sender listed at http://www.dnswl.org/, no
    *      trust
    *      [83.166.64.11 listed in list.dnswl.org]
    *  3.5 BAYES_99 BODY: Bayes spam probability is 99 to 100%
    *      [score: 1.0000]
    *  1.4 HTML_IMAGE_ONLY_28 BODY: HTML: images with 2400-2800 bytes of words
    *  0.0 HTML_MESSAGE BODY: HTML included in message
    *  0.2 BAYES_999 BODY: Bayes spam probability is 99.9 to 100%
    *      [score: 1.0000]
    *  0.9 AWL AWL: Adjusted score from AWL reputation of From: address
```

**Closed** 2017-04-24 12:56 UTC
Labels: bug, critical, p1, regression, type:signup

**Comment by lampholder** [comment] 2017-04-24 13:13
spamscoreschecker.com is down, but I _can_ verify that invite emails are now coming through to gmail successfully (from both riot and matrix).
