### ISSUE TITLE
Unhandled rejection doesRoomHaveUnreadMessage

### ISSUE THREAD

**Issue by Linuxine** [vector-im/riot-web#8696] opened 2019-02-15 10:35 UTC
Hi, after installing the V1.0.0 this morning, I am totally unable to access to Riot web. After the login, I get this error, which seems fatal, since I only get a blank page and a spinner :

```
TypeError: e is null[Learn More] ReactDOMComponentTree.js:111    p7React     dispatchEvent (index):1019 

Unhandled rejection doesRoomHaveUnreadMessages@/riot2/bundles/b3e62be02a3770812395/bundle.js:31:42493
makeRoomTile@/riot2/bundles/b3e62be02a3770812395/bundle.js:61:396318
value@/riot2/bundles/b3e62be02a3770812395/bundle.js:61:408885
_renderValidatedComponentWithoutOwnerOrContext@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:52835
_renderValidatedComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:52952
performInitialMount@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:48855
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:47905
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
mountChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:43237
_createInitialChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:32521
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:30743
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
mountChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:43237
_createInitialChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:32521
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:30743
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
performInitialMount@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:49019
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:47905
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
performInitialMount@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:49019
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:47905
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
mountChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:43237
_createInitialChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:32521
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:30743
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
performInitialMount@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:49019
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:47905
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
mountChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:43237
_createInitialChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:32521
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:30743
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
performInitialMount@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:49019
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:47905
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
mountChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:43237
_createInitialChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:32521
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:30743
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
mountChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:43237
_createInitialChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:32521
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:30743
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
performInitialMount@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:49019
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:47905
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
mountChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:43237
_createInitialChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:32521
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:30743
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
performInitialMount@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:49019
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:47905
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
mountChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:43237
_createInitialChildren@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:32521
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:30743
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
performInitialMount@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:49019
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:47905
mountComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:125577
_updateRenderedComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:52568
_performComponentUpdate@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:52089
updateComponent@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:51367
performUpdateIfNecessary@/riot2/bundles/b3e62be02a3770812395/bundle.js:63:50710
performUpdateIfNecessary@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:126155
b@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:43804
perform@/riot2/bundles/b3e62be02a3770812395/bundle.js:30:84990
perform@/riot2/bundles/b3e62be02a3770812395/bundle.js:30:84990
perform@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:44258
E@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:44435
closeAll@/riot2/bundles/b3e62be02a3770812395/bundle.js:30:85572
perform@/riot2/bundles/b3e62be02a3770812395/bundle.js:30:85070
batchedUpdates@/riot2/bundles/b3e62be02a3770812395/bundle.js:61:163638
e@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:44769
a@/riot2/bundles/b3e62be02a3770812395/bundle.js:53:5963
enqueueSetState@/riot2/bundles/b3e62be02a3770812395/bundle.js:53:6809
s.prototype.setState@/riot2/bundles/b3e62be02a3770812395/bundle.js:61:146186
_onWillStartClient/<@/riot2/bundles/b3e62be02a3770812395/bundle.js:106:68517
n.prototype.emit@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:4995
b.prototype._updateSyncState@/riot2/bundles/b3e62be02a3770812395/bundle.js:68:131129
e/<@/riot2/bundles/b3e62be02a3770812395/bundle.js:68:120719
E@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:162937
b/i._invoke</<@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:162727
w/</e[t]@/riot2/bundles/b3e62be02a3770812395/bundle.js:23:163113
c@/riot2/bundles/b3e62be02a3770812395/bundle.js:1:141420
e.exports</<[16]</t.exports/p.prototype._promiseFulfilled@/riot2/bundles/b3e62be02a3770812395/bundle.js:1:98421
e.exports</<[22]</n.exports/R.prototype._settlePromise@/riot2/bundles/b3e62be02a3770812395/bundle.js:1:115552
e.exports</<[22]</n.exports/R.prototype._settlePromise0@/riot2/bundles/b3e62be02a3770812395/bundle.js:1:116147
e.exports</<[22]</n.exports/R.prototype._settlePromises@/riot2/bundles/b3e62be02a3770812395/bundle.js:1:117499
p@/riot2/bundles/b3e62be02a3770812395/bundle.js:1:69641
d@/riot2/bundles/b3e62be02a3770812395/bundle.js:1:69582
e.exports</<[2]</l.prototype._drainQueues@/riot2/bundles/b3e62be02a3770812395/bundle.js:1:71090
l/this.drainQueues@/riot2/bundles/b3e62be02a3770812395/bundle.js:1:69322
a@/riot2/bundles/b3e62be02a3770812395/bundle.js:61:632608
A/<@/riot2/bundles/b3e62be02a3770812395/bundle.js:61:632753
u@/riot2/bundles/b3e62be02a3770812395/bundle.js:39:28888
```

**Comment by Linuxine** [comment] 2019-02-15 10:54
I manage to be login again, after restoring the previous version of riot (17.9), accept any pending invitation (in a community) and updating the version again. Maybe the pending invitation was causing the issue ?

**Comment by jryans** [comment] 2019-02-15 11:11
This sounds like a duplicate of https://github.com/vector-im/riot-web/issues/8692. If I am wrong, please feel free to reopen!

**Closed by jryans** 2019-02-15 11:11 UTC

**Comment by Linuxine** [comment] 2019-02-15 12:03
> This sounds like a duplicate of #8692. If I am wrong, please feel free to reopen!

Sorry, I did not make the relation at first with the pending invitation, could be related indeed !
