### ISSUE TITLE
Markdown button should give hint about what Markdown actually is

### ISSUE THREAD

**Issue by pafcu** [vector-im/riot-web#5801] opened 2017-12-10 08:40 UTC
### Description

The Markdown button in the text editor should probably give _some_ hint as to what Markdown actually is (and say what pressing the button does, rather than the current state). Perhaps the button could be changed from "Markdown is Enabled" to "Disable Markdown text formatting". 

### Version information

- **Platform**: web
- **Browser**:Firefox
- **OS**: Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment] 2019-02-15 03:29
Duplicate of https://github.com/vector-im/riot-web/issues/3728

**Closed by turt2live** 2019-02-15 03:29 UTC
Labels: bug, minor, p2, ui/ux
