### ISSUE TITLE
`code` or `pre` formatted hyperlink color is inverted in default and custom dark themes …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13454] opened 2020-04-30 08:38 UTC
<img width="440" alt="Screenshot 2020-04-30 at 10 30 35" src="https://user-images.githubusercontent.com/11408027/80689595-db46cb00-8acd-11ea-9b2c-86a1d7a1f51c.png">
<img width="440" alt="Screenshot 2020-04-30 at 10 31 16" src="https://user-images.githubusercontent.com/11408027/80689598-dc77f800-8acd-11ea-96eb-b4fcdc0c6e4e.png">

Maybe a fix would be as simlpe as excluding `code a` and `pre a` from `filter: invert(1);` … or, which sounds a bit odd, adding another `filter: invert(1);` just for `code a` and `pre a` …

One of the files responsible for this is, I think, `matrix-react-sdk/res/css/views/rooms/_EventTile.scss` …

**Comment by turt2live** [comment] 2020-04-30 15:51
Duplicate of https://github.com/vector-im/riot-web/issues/2988 or https://github.com/vector-im/riot-web/issues/7872 or https://github.com/vector-im/riot-web/issues/8554

(any one of these 3 captures the same bug)

**Closed by turt2live** 2020-04-30 15:51 UTC
Labels: bug, ui/ux

**Comment by fooness** [comment] 2020-05-08 22:37
@turt2live Those issue reports are one, two, and three years old. Any idea when that bug will be fixed? Maybe a good idea to keep it open as that’s a rather breaking bug (when not using blue or orange as colors, but black and white — then there’s black on black).

**Comment by turt2live** [comment] 2020-05-11 06:55
It might get fixed during our FTUE (First Time User Experience) sprint, or possibly require a community PR for us to have the time to look at it.

Sorry, we don't keep duplicate issues open as a general rule - please add a 👍 to the issue description of the one that is open instead.
