### ISSUE TITLE
Extremly hard to find login page for newbie users.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [vector-im/riot-web#7671] opened 2018-11-07 21:54 UTC
My friend open riot.im. OK, he press hamburger button and press "launch now".
He gets:

![image](https://user-images.githubusercontent.com/14617699/48163427-b3b7dd80-e2f0-11e8-9b4e-1dcc7d3c434a.png)

How should he find  https://riot.im/app/#/login link here?

**Comment by turt2live** [comment] 2018-11-07 22:19
Duplicate of https://github.com/vector-im/riot-web/issues/7629

**Closed by turt2live** 2018-11-07 22:19 UTC

**Comment by c-e-p-x-u-o** [comment] 2018-11-07 22:37
Sorry.
