### ISSUE TITLE
Use fallback instead of showing Unable to load event that was replied to

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#13380] opened 2020-04-25 00:38 UTC
For this message I see the error "Unable to load event that was replied to, it either does not exist or you do not have permission to view it." (which really needs some more decoration to make it clear that it isn't just quoting a message that said that) but the event source contains the message that was being replied to, why not use it?

<img width="552" alt="Screen Shot 2020-04-24 at 7 35 36 PM" src="https://user-images.githubusercontent.com/5855073/80266677-c815a480-8662-11ea-8b94-fe1b9445468c.png">

```
{
  "content": {
    "body": "> <@sorunome:sorunome.de> wasn't there some talk about some api to backfill history? what happened to that?\n\nshot down instantly like all the other good proposals, probably",
    "format": "org.matrix.custom.html",
    "formatted_body": "<mx-reply><blockquote><a href=\"https://matrix.to/#/!uOjvskgRfNgksdiArw:sorunome.de/$uPDwKsh-nB7tC86QoqYy41avPjEkhysc51B5X8d2Y0k?via=sorunome.de&via=matrix.org&via=privacytools.io\">In reply to</a> <a href=\"https://matrix.to/#/@sorunome:sorunome.de\">@sorunome:sorunome.de</a><br>wasn&#39;t there some talk about some api to backfill history? what happened to that?</blockquote></mx-reply>shot down instantly like all the other good proposals, probably",
    "m.relates_to": {
      "m.in_reply_to": {
        "event_id": "$uPDwKsh-nB7tC86QoqYy41avPjEkhysc51B5X8d2Y0k"
      }
    },
    "msgtype": "m.text"
  },
  "origin_server_ts": 1587483222983,
  "sender": "@qy:cs.xa0.uk",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$-bQduIFOKrmapgOcNf1Fp4xpP0SZK5SL8zh5MsBLI_Q",
  "room_id": "!uOjvskgRfNgksdiArw:sorunome.de"
}
```

**Comment by turt2live** [comment] 2020-04-25 04:11
Duplicate of https://github.com/vector-im/riot-web/issues/6977

**Closed by turt2live** 2020-04-25 04:11 UTC
Labels: suggestion, type:replies
