### ISSUE TITLE
Block users on other matrix homeservers from joining this room  is not honored

### ISSUE THREAD

**Issue by psaavedra** [vector-im/riot-web#5654] opened 2017-11-19 21:34 UTC
### Description

**Block users on other matrix homeservers from joining this room** in the Room creation menu. The `https://matrix.org/_matrix/client/r0/createRoom` sent by Riot never includes:`"creation_content": {    "m.federate": false  },`. Therefore, the created room is always `federate=true` which is a flaw indeed. 

### Steps to reproduce

Riot sends a `createRoom` action as follows:
```
https://matrix.org/_matrix/client/r0/createRoom?access_token=XXXXXXXXXXXXXXXXXX
{"room_id":"!TKUBrjjSZCffJsElgH:matrix.org"}
```

with this content:
```
{"room_id":"!TKUBrjjSZCffJsElgH:matrix.org"}
```
but I miss: 

```
"creation_content": {
    "m.federate": false
  },
```
### Version information

0.13.

- **Platform**: web (in-browser) or desktop?

browser

**Comment by t3chguy** [comment] 2017-11-19 21:36
Cannot reproduce:
![image](https://user-images.githubusercontent.com/2403652/32995804-c2733850-cd71-11e7-8120-3a2076fd203a.png)

**Comment by t3chguy** [comment] 2017-11-19 21:50
Seems to be resolved by clearing cache or retesting:
https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$15111281514606586vaJVn:matrix.org

> the issue is gone. Don't know what was the problem. Sorry for the noise.

**Closed by t3chguy** 2017-11-19 21:50 UTC
Labels: cannot-reproduce

**Comment by psaavedra** [comment] 2017-11-19 21:51
The issue is gone. I can not reproduce the problem with other browser or with incognito mode.

Please, mark this issue as invalid/cannot-reproduce.
