### ISSUE TITLE
MacOS NoDisplaySleepAssertion

### ISSUE THREAD

**Issue by mcodev31** [vector-im/riot-web#7284] opened 2018-09-05 10:04 UTC
On macos (10.12.6) Riot (0.16.3) will occasionally set NoDisplaySleepAssertion and never release it.

```
> pmset -g assertions
...
   pid 849(Riot): [0x000008d7000582bd] 21:21:24 NoDisplaySleepAssertion named: "Electron" 
```

I'm not sure how to reliably reproduce (usually don't notice right away), but it seems to happen when there is a failed voice call, or a call that I answer on a different device.

**Comment by t3chguy** [comment] 2018-09-05 10:30
Duplicate of https://github.com/vector-im/riot-web/issues/6814

**Comment by t3chguy** [comment] 2018-09-05 10:31
(same cause anyway)

**Closed by t3chguy** 2018-09-05 10:30 UTC
Labels: bug, question
