### ISSUE TITLE
Room upgrades: Old room sometimes appears in room list even though I left the upgraded room

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#8918] opened 2019-02-24 16:08 UTC
I upgraded a room from v1 to v3 and then left the new v3 room. Every couple days that old v1 room will appear and then disappear when I click on it.

**Comment by turt2live** [comment] 2019-02-24 18:27
Duplicate of https://github.com/vector-im/riot-web/issues/8539

**Closed by turt2live** 2019-02-24 18:27 UTC
