### ISSUE TITLE
1-to-1 room uses my own avatar when the other person doesn't have one

### ISSUE THREAD

**Issue by spantaleev** [vector-im/riot-web#7295] opened 2018-09-07 05:39 UTC
Seems to be a problem on riot-web `0.16.3`. It wasn't a problem on `0.16.1`, so it must be some regression that occurred in `0.16.2` or `0.16.3`.

For direct chats with only 1 other person, the default room avatar is wrong when the other person doesn't have an avatar image. Instead of using an avatar showing their display name initial, riot-web would instead show my own avatar for the room.

For direct chats where the other person has an avatar image, the room avatar would default to that person's avatar, as expected.

---------

In addition to this, rooms with just myself (self chat) display an avatar with my initial instead of my actual avatar, like one would expect.

**Comment by lampholder** [comment] 2018-09-07 09:00
Hi @spantaleev - we've got a fix for this in the pipeline (the issue is already tracked here: https://github.com/vector-im/riot-web/issues/7235). We plan to get the fix out soon - most likely early next week.

Sorry for the inconvenience, and thanks for the report!

**Closed by lampholder** 2018-09-07 09:00 UTC
