### ISSUE TITLE
New DM created as private room, and Element no longer has a "mark as DM" button

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#14536] opened 2020-07-16 11:16 UTC
### Steps to reproduce

- Click a user
- Click the Direct Message button
- Room is created under the Rooms heading
- DM cannot be moved to DMs, because the button has gone

For the desktop app:

- **OS**: Linux
- **Version**: 1.7.0

**Comment by t3chguy** [comment] 2020-07-16 12:31
This'll unlikely be fixed before Canonical DMs

**Comment by turt2live** [comment] 2020-07-16 13:23
This is not a bug, it's a feature.

**Comment by turt2live** [comment] 2020-07-16 13:24
oh, hmm, actually a bug

**Comment by turt2live** [comment] 2020-07-19 15:54
@Half-Shot I can't reproduce this. Do you have any more information?

**Comment by turt2live** [comment] 2020-07-20 20:16
This can't be reproduced, so closing. If it continues to be an issue, please include a bit more detail about what exactly went wrong in step 4

**Closed by turt2live** 2020-07-20 20:16 UTC
Labels: bug, cannot-reproduce, feature:immutable-dms

**Comment by Half-Shot** [comment] 2020-07-20 20:28
>If it continues to be an issue, please include a bit more detail about what exactly went wrong in step 4

- I clicked on `@half-shot:vector.modular.im` and clicked Direct message
- A room was created, but it was under the Rooms heading rather than the DM header.

Logs attached.

**Comment by turt2live** [comment] 2020-07-20 20:34
@Half-Shot does clicking off the room cause it to go to the right place?

**Comment by Half-Shot** [comment] 2020-07-20 20:36
![image](https://user-images.githubusercontent.com/2072976/87983867-fde6ef80-cad0-11ea-9f7f-0bc37a390d55.png)

It did not.

**Comment by turt2live** [comment] 2020-07-20 20:46
That would be https://github.com/vector-im/riot-web/issues/14046 or https://github.com/vector-im/riot-web/issues/2099 or https://github.com/vector-im/riot-web/issues/2455 then
