### ISSUE TITLE
Can't add extra sticker packs

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/riot-web#6557] opened 2018-04-19 08:16 UTC
### Description
If I have previously subscribed to a sticker pack, there is no obvious way to add more sticker packs. This behaviour existed in the past.

### Steps to reproduce

Subscribe to a sticker pack
Click on the sticker pack button, expect that I will see some way to edit my sticker packs.

Instead the only way to add more seems to be to remove the existing one and then add multiple ones.

### Version information

- **Platform**: web (in-browser) or desktop?
In browser
For the web app:

- **Browser**: Chrome
- **OS**: macOS
- **URL**: riot.im/develop /

**Comment by rxl881** [comment] 2018-04-20 09:30
It looks like there was a temporary regression in riot-web / react-sdk that was preventing the edit button from being shown in the sticker picker.

It appears that this has now been fixed / reverted and you should be able to add more stickerpacks by clicking on the edit icon in the top right of the sticker picker.

<img width="378" alt="screen shot 2018-04-20 at 10 29 35" src="https://user-images.githubusercontent.com/6763606/39043641-d8b6312c-4485-11e8-9472-e50426f99cc1.png">

@neilisfragile has confirmed that this is now fixed from his point of view.

**Closed by rxl881** 2018-04-20 09:30 UTC
Labels: bug, major, p1, type:scalar, ui/ux
