### ISSUE TITLE
v1.0 marks messages as read prematurely

### ISSUE THREAD

**Issue by spantaleev** [vector-im/riot-web#8643] opened 2019-02-14 17:57 UTC
- **Browser**: Firefox, but also Electron (packaged v1.0rc1 and v1.0rc2 manually)
- **OS**: Arch Linux
- **Versions tested**: v1.0.0rc1 was exhibiting the bug. rc2 seems to have it too.

### Description

If the window is raised, even if not focused, all newly-arriving chat messages are automatically marked as read.

If the window is focused and you're not active on it, the same thing happens - messages are automatically marked as read as soon as they arrive.

### Steps to reproduce

- Use Firefox (or Electron) and open some chat
- Open another window, so that it would get focused and Firefox (or Electron) would not. **Alternatively**, just stay on the same window (don't open another one) and make sure not to move your mouse or type anything.
- Have the other person send some messages to you
- Observe how all newly-arriving messages are immediately marked as read

Previously (before v1.0rc1, at least), even if the window were focused, if you're not moving your mouse or typing something, it would not consider you active and would not mark messages as read.

Log: not sent

**Comment by turt2live** [comment] 2019-02-14 18:07
Duplicate of https://github.com/vector-im/riot-web/issues/8041

**Closed by turt2live** 2019-02-14 18:07 UTC
Labels: redesign
