### ISSUE TITLE
Sticky day divider in feed with day and date

### ISSUE THREAD

**Issue by plainspace** [vector-im/riot-web#12915] opened 2020-03-28 18:45 UTC
**Is your suggestion related to a problem? Please describe.**
It is difficult to scroll back in time and see at a glance on what date a post was made.

**Describe the solution you'd like**
Make a sticky, horizontal divider that shows day and date so it is easy to see where you are in history.

**Describe alternatives you've considered**
The current alternative is to hover the time and wait for the native browser tooltip.

**Comment by t3chguy** [comment] 2020-03-28 18:56
Duplicate of #7575

**Closed by t3chguy** 2020-03-28 18:56 UTC
Labels: suggestion
