### ISSUE TITLE
Segmentation fault upon file upload

### ISSUE THREAD

**Issue by kwaadschiks** [vector-im/riot-web#10265] opened 2019-07-05 08:01 UTC
### Description

When clicking the upload file button the programme crashes with a segmentation fault.

### Steps to reproduce

- Open riot-desktop
- Click the "upload file" button
- Either choose a file from the dialog window that appears or choose "cancel" and the programme crashes.

One would expect the file to be uploaded to the channel as was previously the case.
[strace.txt](https://github.com/vector-im/riot-web/files/3361677/strace.txt)

### Version information

- **Platform**: Desktop
- **OS**: Linux think 5.1.11-arch1-1-ARCH #1 SMP PREEMPT Mon Jun 17 18:56:30 UTC 2019 x86_64 GNU/Linux
- **Version**: matrix-react-sdk version: \<local\>
riot-web version: 1.2.2
olm version: 3.1.0
https://www.archlinux.org/packages/community/any/riot-desktop/
https://www.archlinux.org/packages/community/x86_64/electron/

**Comment by jryans** [comment] 2019-07-05 11:43
Hmm, sorry to hear about this. As far as I know, file upload does work for other Linux users. So I would guess either there's some system-specific issue in Electron, or maybe you're using some kind of sandboxing that's causing this...?

**Comment by kwaadschiks** [comment] 2019-07-05 12:27
> So I would guess either there's some system-specific issue in Electron, or maybe you're using some kind of sandboxing that's causing this...?

Could well be. I can upload fine using the  webclient. Although I am using the normal arch linux packaged versions. So, no sandboxing, afaik.

**Comment by ArchangeGabriel** [comment] 2019-07-14 11:11
I cannot reproduce. Are you still having this issue?

**Comment by jryans** [comment] 2019-07-19 10:48
Closing due to lack of reply. (I don't really think Riot can do much here anyway.)

**Closed** 2019-07-19 10:49 UTC
Labels: support, type:electron
