### ISSUE TITLE
Clicking an inline mention causes room column content to disappear

### ISSUE THREAD

**Issue by grahamperrin** [vector-im/riot-web#4726] opened 2017-08-01 19:39 UTC
## Steps

1. mention a user in a message
2. click the mention

## Expected

3. the mentioned user's details, without disappearance of the message

## Actual results

- messages and other content disappear from the room column
- close the user's details
- content disappears from the right-hand column

## Workaround

- browse back

## Screen recording

[2017-08-01 20-29-51.tar.gz](https://github.com/vector-im/riot-web/files/1191719/2017-08-01.20-29-51.tar.gz)

## Environment

`riot-web version: af85f18eae78-react-ff378cc85af9-js-bdb90b4b334f`

Firefox 54.0.1 (64-bit)

**Comment by t3chguy** [comment] 2017-08-01 19:57
Duplicate of https://github.com/vector-im/riot-web/issues/3586

**Closed by t3chguy** 2017-08-01 19:57 UTC
