### ISSUE TITLE
Can't disinvite users I invited

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8602] opened 2019-02-13 19:43 UTC

**Comment by ara4n** [comment] 2019-02-13 19:44
<img width="299" alt="screenshot 2019-02-13 at 19 43 36" src="https://user-images.githubusercontent.com/1294269/52738967-c44eb280-2fc7-11e9-8e0e-50af34548041.png">

<img width="291" alt="screenshot 2019-02-13 at 19 43 42" src="https://user-images.githubusercontent.com/1294269/52738966-c44eb280-2fc7-11e9-8b14-17f3a65d3bfe.png">

**Comment by ara4n** [comment] 2019-02-13 20:20
or is it that it doesn't realise that i'm allowed to disinvite people i invited myself despite not being an op?

**Comment by turt2live** [comment] 2019-02-13 20:23
> it doesn't realise that i'm allowed to disinvite people

This is false: https://github.com/matrix-org/matrix-doc/issues/664

**Comment by lampholder** [comment] 2019-02-19 12:58
Yeah, it's a spec issue not a riot one. Leaving with a wontfix 'cause we've gone down this avenue a few times.

**Comment by aaronraimist** [comment] 2020-01-26 20:54
Duplicate of https://github.com/vector-im/riot-web/issues/1378

**Closed by aaronraimist** 2020-01-26 20:54 UTC
Labels: wontfix
