### ISSUE TITLE
Missing tray icon (GNU/Linux Debian 10)

### ISSUE THREAD

**Issue by LorenzoAncora** [vector-im/riot-web#13781] opened 2020-05-23 12:49 UTC
### Description

The tray icon does not appear and restarting the application does restore the window but the tray icon remains hidden.

### Steps to reproduce

1. Start `im.riot.Riot`;
2. Enable the tray icon;
3. Close the window.

The tray icon should be always visible after if is enabled by end users.

### Version information

- **Platform**: desktop
- **OS**: Debian GNU/Linux 10 ([buster](https://www.debian.org/releases/buster/), [MATE 1.24](https://mate-desktop.org/))
- **Version**: 1.6.2 (Flatpak: [app/im.riot.Riot/x86_64/stable](https://flathub.org/apps/details/im.riot.Riot))

**Comment by t3chguy** [comment] 2020-05-23 12:50
Duplicate of https://github.com/flathub/im.riot.Riot/issues/1

**Closed** 2020-05-23 12:50 UTC
Labels: bug

**Comment by LorenzoAncora** [comment] 2020-05-23 12:53
>  t3chguy closed this 41 seconds ago 

@t3chguy so the next version won't have this bug when using MATE 1.24?

**Comment by t3chguy** [comment] 2020-05-23 13:00
You'd have to ask that in the issue i referenced, the flatpak is unofficial.

**Comment by LorenzoAncora** [comment] 2020-05-23 13:10
> You'd have to ask that in the issue i referenced, the flatpak is unofficial.

@t3chguy it says the issue does not depend from Flatpak but from one of your dependencies.
Do you want to reopen this issue or do I have to forward the issue to Flathub?

**Comment by t3chguy** [comment] 2020-05-23 13:28
https://github.com/flathub/im.riot.Riot/issues/100#issuecomment-626665452

Flatpak doesn't support SNI very well.

**Comment by t3chguy** [comment] 2020-05-23 13:29
It's a new issue because riot is using a newer version of electron which dropped support for xembed tray which was used previously

**Comment by LorenzoAncora** [comment] 2020-05-23 14:05
> Flatpak doesn't support SNI very well.
> It's a new issue because riot is using a newer version of electron which dropped support for xembed tray which was used previously

@t3chguy I see, this is a tricky situation. The question now is what dev team should fix the issue. Does the Riot dev team have plans to offer retrocompatibility or end users should wait for Flatpak to offer dedicated support for SNI?

**Comment by t3chguy** [comment] 2020-05-23 14:36
Riot won't be offering compatibility beyond that supported by Electron.

**Comment by LorenzoAncora** [comment] 2020-05-23 15:43
> Riot won't be offering compatibility beyond that supported by Electron.

@t3chguy if I understood correctly, you can't offer backward compatibility because you are limited by the framework (Electrum) you chose at the beginning of development?
This is a pity as there is actually no client which features a fully working tray icon, as even the one I can directly download from your official [repository](https://packages.riot.im/debian/) does not include a working icon.
This is only the humble _suggestion_ of one of your users, but I think you should distribute a real desktop application instead of simulating it by embedding a webpage in a stripped down browser window. I _think_ computing resource footprint would also be lighter and you would have full control of your own code, including the tray icon.

**Comment by t3chguy** [comment] 2020-05-23 15:46
> @t3chguy if I understood correctly, you can't offer backward compatibility because you are limited by the framework (Electrum) you chose at the beginning of development?

Precisely

> as even the one I can directly download from your official repository does not include a working icon.

The official debian distribution of the riot-desktop client works in DE/WMs which support SNI or libappindicator successfully. Chromium 80.x (which is what electron 8 is based on) dropped support for the legacy XEmbed Tray Icons for similar reasons as KDE did.

> This is only the humble suggestion of one of your users, but I think you should distribute a real desktop application instead of simulating it by embedding a webpage in a stripped down browser window.

The team is not large enough to support yet another standalone app at this time, it may be something that is revisited later on but there are plenty other native Matrix clients from which you can choose: https://matrix.org/clients/

**Comment by t3chguy** [comment] 2020-05-23 15:48
> simulating it by embedding a webpage in a stripped down browser window.

The desktop app does feature native extensions not possible in the browser version, like the seshat integration for encrypted message search and in the future secure enclave support.

**Comment by t3chguy** [comment] 2020-05-23 16:10
Just to prove the above, did a fresh install using the official instructions https://riot.im/download/desktop/ on Ubuntu 20.04:

![image](https://user-images.githubusercontent.com/2403652/82735260-3740f000-9d18-11ea-81b7-bb284c2fdba6.png)

You can see the Riot tray icon in the top right.

**Comment by LorenzoAncora** [comment] 2020-05-25 19:45
> Just to prove the above, did a fresh install using the official instructions https://riot.im/download/desktop/ on Ubuntu 20.04:
> 
> ![image](https://user-images.githubusercontent.com/2403652/82735260-3740f000-9d18-11ea-81b7-bb284c2fdba6.png)
> 
> You can see the Riot tray icon in the top right.

Hi, **you need to prove nothing, I trust you**. If I wouldn't, I wouldn't execute your software and I wouldn't employ my time here.

I did a fresh install along with the Flatpak version, while using MATE 1.24 on Debian 10 (Debian != Ubuntu) and both versions were not able to not show a tray icon. Do you think it is an incompatibility or maybe a library is misnomed or something like that?

> simulating it by embedding a webpage in a stripped down browser window.
>> The desktop app does feature native extensions not possible in the browser version, like the seshat integration for encrypted message search and in the future secure enclave support.

...but it still remains a browser window with a webpage inside incapable of showing a little 32px icon: I can see that the window used by riot is called renderer and the string "WebComponents" is present in its command line. When I start Riot, it creates up to 26 processes and uses more than 10.7G of virtual memory; each process uses more than 100mb of physical memory. In comparison, the Flatpak version of Telegram Desktop (so, heavier that the standalone version) uses 1/10 of the memory used by Riot and only has 3 processes, offering many more features without the need to load a new webpage each time. Notwithstanding the high memory footprint, Riot's performance is inconsistent: sometimes I click on a pane/symbol and it loads immediately, other times I have to wait for up to 30 seconds or more, and that only to show a few strings.
The average journalist who wants to communicate safely may not have big and powerful machines at his/her disposal and the amounts of resources employed to execute a chat should be both low (because it is a chat, not a game) and justified.

> @t3chguy if I understood correctly, you can't offer backward compatibility because you are limited by the framework (Electrum) you chose at the beginning of development?
>>Precisely (note: Electron)

I guess it's an unsolvable problem, unless you distribute a patched version of Electron. However, you would be better creating a new client from scratch and have less dependencies.

> This is only the humble suggestion of one of your users, but I think you should distribute a real desktop application instead of simulating it by embedding a webpage in a stripped down browser window.
>> The team is not large enough to support yet another standalone app at this time, it may be something that is revisited later on but there are plenty other native Matrix clients from which you can choose: https://matrix.org/clients/

I'm _suggesting_ to _replace_ the current client: the number of issues in this repository is very high (total: 12181 issues, of which 5964 bugs): this is ~24 bugs reported for each release. This number seem very high and I believe it does not depend only on you but also on your dependencies.

That said, you just advertised other clients to me, which is like "throwing in the towel". However, I would like to read that you are willing to improve your product to remain competitive, either by dropping this encumbering dependency or by rewriting it from scratch.

**Comment by t3chguy** [comment] 2020-05-25 19:50
> I did a fresh install along with the Flatpak version, while using MATE 1.24 on Debian 10 (Debian != Ubuntu) and both versions were not able to not show a tray icon. Do you think it is an incompatibility or maybe a library is misnomed or something like that?

As someone in #riot-web:matrix.org found today, the Flatpak's solution is not perfect due to how KDE's SNI works with Flatpak.

![image](https://user-images.githubusercontent.com/2403652/82839981-0227cf80-9ec9-11ea-97a6-0bd61deeadc9.png)

So looking at your dbus and correcting the override `--own-name` argument is the workaround if flatpak won't fix it themselves. 

> I'm suggesting to replace the current client: the number of issues in this repository is very high (total: 12181 issues, of which 5964 bugs): this is ~24 bugs reported for each release. This number seem very high and I believe it does not depend only on you but also on your dependencies.

This repo is the 1st layer dumping ground for all user facing issues, probably 60% of which are not riot-web specific at all.

> I'm suggesting to replace the current client

The riot-web client will not be *replaced*, it is one of the primary entrypoints into the Matrix ecosystem.

**Comment by t3chguy** [comment] 2020-05-25 19:50
See https://github.com/flathub/im.riot.Riot/issues/100#issuecomment-633625336

**Comment by LorenzoAncora** [comment] 2020-05-26 16:52
> I did a fresh install along with the Flatpak version, while using MATE 1.24 on Debian 10 (Debian != Ubuntu) and both versions were not able to not show a tray icon. Do you think it is an incompatibility or maybe a library is misnomed or something like that?
>> As someone in #riot-web:matrix.org found today, the Flatpak's solution is not perfect due to how KDE's SNI works with Flatpak.
>> ![image](https://user-images.githubusercontent.com/2403652/82839981-0227cf80-9ec9-11ea-97a6-0bd61deeadc9.png)
>> So looking at your dbus and correcting the override `--own-name` argument is the workaround if flatpak won't fix it themselves.

Hi @t3chguy I've tried the offered solution (`flatpak --user override im.riot.Riot --own-name=org.kde.*`) but it does not work: Riot desktop starts and runs normally but no icon is visible in the tray of MATE.

> I'm suggesting to replace the current client: the number of issues in this repository is very high (total: 12181 issues, of which 5964 bugs): this is ~24 bugs reported for each release. This number seem very high and I believe it does not depend only on you but also on your dependencies. 
>> This repo is the 1st layer dumping ground for all user facing issues, probably 60% of which are not riot-web specific at all.

Riot is the first client in the list of clients available on the reference site, so it is normal for end users to test it first and more often.

I am an end user and I don't know how you are organized internally (should I? :-) ), I just see the repository statistics and the high number of complaints. Since your Issues do not have `riot-desktop` or `riot-linux` labels that allow me and other users to clearly categorize them and since riot desktop's GUI is composed by remote web pages, it is difficult to distinguish the product to which a certain Issue belongs. Provided that users are so virtuous that they do not "judge the book by the cover".

> > I'm suggesting to replace the current client
> 
> The riot-web client will not be _replaced_, it is one of the primary entrypoints into the Matrix ecosystem.

My suggestions were for the _desktop_ client _only_, not for the web application (the one you use in a real web browser).
As you said before, there are many promising alternatives to Riot desktop: if you don't develop a native client, another client like [Nheko](https://github.com/Nheko-Reborn/nheko) might fill the void you left behind. I see in the documentation of some of these clients that independence from Electron is specified and highlighted.
Stressing my immense ignorance of your actual capabilities, I _suggest_ that you write a native client and totally replace Riot desktop with a version that is totally independent of Electron and release it under a free software license.

**Comment by t3chguy** [comment] 2020-05-26 16:57
> but it does not work:

If you have any other flatpak doing the same thing then it won't work, quite a few have baked this in, like Zoom Conferencing and Dropbox. https://github.com/flathub/com.dropbox.Client/commit/a0594d16997f6f9c65919d0c8afd056137737957 https://github.com/flathub/us.zoom.Zoom/commit/348ff4e59ac6cc8104a729710dd11dba67147f51

> My suggestions were for the desktop client only
> Stressing my immense ignorance of your actual capabilities, I suggest that you write a native client and totally replace Riot desktop with a version that is totally independent of Electron and release it under a free software license.

Fair enough, but as said previously:

> The team is not large enough to support yet another standalone app at this time

**Comment by LorenzoAncora** [comment] 2020-05-26 18:16
> If you have any other flatpak doing the same thing then it won't work, quite a few have baked this in, like Zoom Conferencing and Dropbox. flathub/com.dropbox.Client@a0594d1 flathub/us.zoom.Zoom@348ff4e

Tested and does not work: I've closed **all** Flatpak apps with a tray icon (Telegram and Nheko), killed all processed belonging to Riot and started it again. No icon. 💀
By the way, it does not work without Flatpak, I don't understand why should it work with it. 🤔

> My suggestions were for the desktop client only.
> Stressing my immense ignorance of your actual capabilities, I suggest that you write a native client and totally replace Riot desktop with a version that is totally independent of Electron and release it under a free software license.
>> Fair enough, but as said previously:
>The team is not large enough to support yet another standalone app at this time

I _think_ Riot desktop cannot be defined as standalone, because it depends on Electron and on webpages to work properly. More correctly, we can say it is _portable_.
I see that other clients are being developed (from what the repository statistics say, I might be wrong) each by teams composed of a maximum of 3 people, while you have 10 active contributors, of which [5](https://github.com/vector-im/riot-web/blob/3164655a214422c6f2e9a3fe4548c8a6f2d7c584/AUTHORS.rst) are authors. However, I imagine you have other technical difficulties. 🙂

**Comment by t3chguy** [comment] 2020-05-26 18:21
Sure, but other clients aren't feature complete, so if the team would be cut in half then it'd fall behind the mobile apps in terms of feature parity and development.
