### ISSUE TITLE
Add mandatory password requirements

### ISSUE THREAD

**Issue by 35609902357** [vector-im/riot-web#13253] opened 2020-04-18 09:53 UTC
In light of previous successful breaches into matrix.org servers (which can happen to any server), and of #6779, #8751 and #13252, passwords should be mandatorily 16+ characters, with at least 1 uppercase, 1 lowercase, 1 digit and 1 symbol.

**Comment by cyphar** [comment] 2020-04-18 10:51
This is a duplicate of matrix-org/synapse#5112 and there is an MSC for this ([MSC2000](https://github.com/matrix-org/matrix-doc/pull/2000)). It looks like some bits and pieces to implement this were merged (matrix-org/synapse#5214 and matrix-org/synapse#7118) but it's all in the develop branch of synapse.

**Closed** 2020-04-18 11:08 UTC
Labels: suggestion
