### ISSUE TITLE
Can't input russian 'б' char when starting a chat

### ISSUE THREAD

**Issue by w1r0x** [vector-im/riot-web#4523] opened 2017-07-06 11:48 UTC
### Description

Incorrect filter implementation on Start Chat input.

### Steps to reproduce

- Press "Start Chat" button 
There is a input for "Who would you like to communicate with?".
- Input russian char 'б' or 'Б'
it says "You have entered an invalid contact. Try using their Matrix ID or email address." and no char inputs there.

So I can't search people who name starts with 'Б'.

Web App:
- **Browser**: Chromium 59.0.3071.115 amd64
- **OS**: Arch Linux
- **URL**: v0.11.4

**Comment by w1r0x** [comment] 2017-07-06 11:49
It seems, problem appears because russian 'б' shared with english comma ',' on the keyboard. But in different layouts.

**Comment by w1r0x** [comment] 2017-07-06 11:51
Keyboard like this one ![image](https://user-images.githubusercontent.com/1043901/27909710-9a7a6742-625a-11e7-9002-84f3e7af86f6.png)

**Comment by lukebarnard1** [comment] 2017-07-06 13:19
@w1r0x I'm not convinced the problem is with this particular character, I'm able to search for a variety of different queries, including your "Б" with no problems. 

In fact, when you type any single character and just hit <kbd> Return  </kbd>, "You have entered an invalid contact" which could mean that you haven't added anyone to be invited. This indicates that the UX for inviting users is a bit subtle and could be better.

**Comment by w1r0x** [comment] 2017-07-06 13:46
I also can search if i copy and paste 'Б'. But when I'm trying to type it by keyboard I have an error.

**Comment by lukebarnard1** [comment] 2017-07-06 14:05
That's very odd. AH. It might actually 100% be to do with the fact the character shares a key code with the comma.

And this is why:
```js
        } else if (e.keyCode === 188 || e.keyCode === 9) { // comma or tab
            e.stopPropagation();
            e.preventDefault();
            this._addInputToList();
        }
```

**Comment by w1r0x** [comment] 2017-07-06 14:32
Yeah it is what I'm talking about.
Maybe in some other non-English languages there will be same problem with comma key.

To enter text we switch layouts. In english layout you type english letters, then press smth like Alt+Shift - switch to russian and type russian text.

**Comment by AlexDaniel** [comment] 2017-09-13 13:23
I'm actually experiencing the same issue but with other (custom) layouts. Indeed, special keys (like arrows, delete, etc) that have different meaning on a different layout don't work as they should. So a “Delete” key that should type something else on a different layout works like Delete even though it shouldn't.

What can I do to help with this issue? Do you need exact steps to reproduce?

**Comment by AlexDaniel** [comment] 2017-09-13 13:30
@lukebarnard1 where did you take that code? I can't find it anymore. Any ideas on what would be the relevant part of code today?

**Comment by AlexDaniel** [comment] 2017-09-14 22:48
Nevermind, turns out it is a bug in electron. There's no ticket yet though.

**Comment by AlexDaniel** [comment] 2017-09-14 22:58
Actually, it's a bug in chromium.

There's no ticket for my issue yet, but here are some that may be related:
* https://bugs.chromium.org/p/gerrit/issues/detail?id=3177
* https://bugs.chromium.org/p/gerrit/issues/detail?id=5080

**Comment by lukebarnard1** [comment] 2017-09-18 17:20
@AlexDaniel that seems to be a separate issue. @uhoreg has outlined the fix for this.

**Comment by slipeer** [comment] 2019-01-16 10:45
If there is a need to filter comma, it is probably better to process the whole line before sending it to the server?

**Comment by t3chguy** [comment] 2020-04-10 14:28
This should be fixed as nowadays we no longer use `event.keyCode` and instead use `event.key`

**Closed by t3chguy** 2020-04-10 14:28 UTC
Labels: bug, major, p1
