### ISSUE TITLE
The sticker button in its current form is an anti-feature

### ISSUE THREAD

**Issue by Valodim** [vector-im/riot-web#11413] opened 2019-11-18 17:22 UTC
Apologies for the excessively negative title :)

Let me clarify at first: Stickers are a great feature, and one that people really want (see Telegram). It's great to have support in Matrix the protocol, and Riot should also have it at some point.

That said, I really think the sticker button in the composer, as currently implemented in riot-web, is not only not useful, but sheds an unnecessarily thoughtless light on the project.

1. Most importantly, Telegram sets strong expectations for users on how stickers are supposed to work, and when the user goes looking for those expectations they are bound to be disappointed. In particular, this relates to the user-customizability, which make stickers a great basis for in-jokes on Telegram.
2. Some of my users expressed annoyance that the button they expected to be an emoji picker actually was something else, some said they even fell for this multiple times
3. I have heard from multiple folks that they don't find the default available sticker packs particularly appealing
4. Anecdotally, I can't recall anyone using an actual sticker in any room, other than for testing or on accident

I'm certain that there are nuanced reasons for why things are the way they are. But that isn't something end users care about, and in this case it's just plain unnecessary to frustrate them with a half-baked feature that commonly falls flat of expectations.

As a simple solution, perhaps move the sticker button into a lab for the time being?

**Comment by turt2live** [comment] 2019-11-18 18:12
Thanks for the feedback, though I think it's largely a duplicate of a couple issues here. 

Stickers are indeed a bit of a lacking feature in Riot, and there's some easy things we can do to make them better. They are used (quite a lot), and users over Telegram bridges particularly like having them show up in Riot normally - putting them behind labs would mean we lose this too :(

Much of the stuff we haven't done is covered by https://github.com/vector-im/riot-web/issues/2950 - namely the custom stickers (which is also covered by https://github.com/vector-im/riot-web/issues/2648) and sharing of packs. We also need a way to actually add these sticker packs to the picker, which is where the MSCs come in: https://github.com/matrix-org/matrix-doc/pull/1951 and https://github.com/matrix-org/matrix-doc/pull/1959

https://github.com/matrix-org/matrix-doc/pull/1959 has the added benefit of allowing Riot to render a more native picker instead of relying on an iframe provided by a third party. Personally I think a native picker is going to be better (and best for when we add the emoji picker to the mix), but this largely hasn't been designed/thought out yet from the product side.

Having emojis is covered by https://github.com/vector-im/riot-web/issues/9484 - it's honestly just something we haven't gotten around to yet given all the other things we're working on. The above might be a reason we haven't gotten to it yet.

The default packs being sub-par is something I've heard a lot too. I've opened a separate issue to track this issue independently (and to cover my thoughts on how we might be able to solve it): https://github.com/vector-im/riot-web/issues/11414

As mentioned, putting the feature behind labs is a bit crap because we'd almost certainly put the whole thing behind labs. Instead, we should definitely move forward on it though balancing it against bugs, features, and user expectation is difficult. We have a new (well, kinda new) focus on making the app better for the average person, and I would fully expect that the sticker picker falls into this - it might just be a bit longer than anyone would like because other features are taking priority. I'm not sure how valuable promises are to you, but when we're re-evaluating our roadmap, which happens roughly every few months, I'll bring it up (and not only because I have a ton of opinions in this area).

I think I've addressed each of the concerns you've raised, but if I've missed one then please open an independent issue so we can track the unique problems. We're clearly not scared of having a large number of open issues.

**Closed by turt2live** 2019-11-18 18:12 UTC
Labels: bug, ui/ux

**Comment by Valodim** [comment] 2019-11-18 19:52
> Stickers are indeed a bit of a lacking feature in Riot, and there's some easy things we can do to make them better. They are used (quite a lot), and users over Telegram bridges particularly like having them show up in Riot normally - putting them behind labs would mean we lose this too :(

I was very specifically talking about the sticker button. Are you saying that one is used quite a lot? The only stickers I ever saw in any channel came from Telegram bridged users. If that button is indeed used quite a lot, I would be very surprised and please disregard the rest of everything I'm writing.

> As mentioned, putting the feature behind labs is a bit crap because we'd almost certainly put the whole thing behind labs.

I see no reason why display of stickers and the button would have to be linked together in a feature flag. After some more searching, I also realized putting the sticker button behind a lab is basically the same as what you suggested in #6998, except it can be enabled or disabled both by the Riot instance maintainer, or left up to the user. Sounds perfect to me (and I know I would disable it).

> We have a new (well, kinda new) focus on making the app better for the average person, and I would fully expect that the sticker picker falls into this - it might just be a bit longer than anyone would like because other features are taking priority.

I completely understand. Doing stickers right is a ton of work, and other things are more important. I *don't* want to escalate stickers in priority. Compared to other more important stuff, they are more of a nice-to-have on the wishlist. Stickers haven't moved in one and a half years (your issue about hiding the button is from July 18), they probably won't soon, and that's okay.

That's why my suggestion wasn't "please finish this real quick", but "trivially drop the half-baked workflow that makes the product look worse overall".

People who aren't developers and/or involved in the community don't typically compartmentalize their experience with some specific feature from the rest of the product like "oh yeah well that feature was a disappointment, probably they'll redo it at some point, but the rest is still fine." They take it in as a whole. It makes me very happy that Riot is slowly approaching a point where there aren't a dozen or two other things that are also super rough so that one more rough spot doesn't matter.

Anyways, thanks for getting back to me and considering.

**Comment by turt2live** [comment] 2019-11-18 20:00
The button is in fact used quite a lot, at least from the circles I'm aware of. It's not used so much in the meta rooms for Matrix, but is common in other groups.

We typically put features behind flags, and rendering is part of the feature. This is why rendering would also go away, and I still think that we can move forward better than disabling it.

On the product looking bad: my goal isn't to catapult this issue (or any sticker issue) to the top of the queue, though I think it could benefit the app if it were higher than, say, low bandwidth tooling. Bringing it up at the next roadmap discussion is also not to make it get solved then and there, but to get it on the track for being fixed. It'd almost certainly take another 6-12 months to actually see some code changes in the area, and disabling the button has some large decisions associated with it that would take a couple months to work out. In the interest of time and energy, it's best to leave it as is and incrementally improve it over time, therefore making the product hopefully look better.
