### ISSUE TITLE
Pinned messages caused crashloop

### ISSUE THREAD

**Issue by verymilan** [vector-im/riot-web#11299] opened 2019-11-04 07:33 UTC
### Description

I've tried to access the pinned messages in a room and riot-chat has fallen in a crashloop in this room... even with pinned messages disabled in the settings.

### Steps to reproduce

1. pin a message
2. click on 'pinned messages'

Describe how what happens differs from what you expected.
 
Log:
````
rageshake.js:108 TypeError: Cannot read property 'name' of null
    at t.render (PinnedEventTile.js:127)
    at ya (react-dom.production.min.js:173)
    at va (react-dom.production.min.js:172)
    at Zs (react-dom.production.min.js:247)
    at qs (react-dom.production.min.js:216)
    at Gs (react-dom.production.min.js:210)
    at Ms (react-dom.production.min.js:206)
    at react-dom.production.min.js:114
    at t.unstable_runWithPriority (scheduler.production.min.js:20)
    at po (react-dom.production.min.js:113)
    at _o (react-dom.production.min.js:114)
    at go (react-dom.production.min.js:113)
    at Is (react-dom.production.min.js:204)
    at Object.enqueueSetState (react-dom.production.min.js:127)
    at t.E.setState (react.production.min.js:13)
    at PinnedEventsPanel.js:116
````

### Version information

- **Platform**: web (in-browser), selfhosted, 1.5.0

- **Browser**: Chrome, 78.0.3904.70+
- **OS**: Windows 10
- **Synapse:** 1.4.0 (i can't update just now)
- **Riot-web:** 1.4.2 & 1.5.0

**Comment by verymilan** [comment] 2019-11-04 08:22
(workarounded it by deleting cookies)

**Comment by t3chguy** [comment] 2019-11-04 11:34
This is already fixed in next release.
Duplicate of https://github.com/vector-im/riot-web/issues/11268

**Closed by t3chguy** 2019-11-04 11:34 UTC
