### ISSUE TITLE
I would like to delete my current avatar and revert to the default one.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#4611] opened 2017-07-17 16:55 UTC
From a rageshake.

**Comment by turt2live** [comment] 2017-09-29 22:42
Duplicate of https://github.com/vector-im/riot-web/issues/4611

**Comment by lampholder** [comment] 2017-10-13 09:56
#4611 is a dup of... #4611?

**Comment by t3chguy** [comment] 2017-10-13 09:56
@turt2live you've outdone yourself this time :P

**Comment by turt2live** [comment] 2017-10-13 14:44
I'm the best at this. I meant https://github.com/vector-im/riot-web/issues/682

**Comment by t3chguy** [comment] 2017-10-13 15:39
Duplicate confirmed!

**Closed by t3chguy** 2017-10-13 15:39 UTC
Labels: feature, p3, rageshake
