### ISSUE TITLE
From a rageshake: can't accept or reject a room invite from a friend on a .dog or .space tld homeserver.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#6073] opened 2018-01-31 14:14 UTC
CORS request rejected.

**Comment by turt2live** [comment] 2018-01-31 15:46
I can't reproduce this. I even deployed a relatively standard synapse on `homeserver.dog` to test with.

**Comment by HybridEidolon** [comment] 2018-06-02 18:22
I think this might just be a timeout/error response by the server that doesn't include the requisite CORS headers, which Riot sees as a CORS failure. Attempting to get the matrix.org room directory from my homeserver causes this, too, from a 504 Gateway Timeout.

**Comment by turt2live** [comment] 2019-02-15 03:54
As far as I can tell, the rageshake doesn't reveal anything special. Closing as cannot reproduce and needing more information - if it happens to someone, please open a new issue.

**Closed by turt2live** 2019-02-15 03:54 UTC
Labels: bug, major, p2
