### ISSUE TITLE
“Riot” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by dchatterjee172** [vector-im/riot-web#11139] opened 2019-10-14 14:49 UTC
- **OS**: Mac
- **Version**: Catlina 10.15

<img width="1440" alt="Screen Shot 2019-10-14 at 8 18 17 PM" src="https://user-images.githubusercontent.com/10482742/66760497-dc146880-eebf-11e9-932d-40019761faf1.png">

**Comment by t3chguy** [comment] 2019-10-14 14:51
Duplicate of https://github.com/vector-im/riot-web/issues/11093

**Closed by t3chguy** 2019-10-14 14:51 UTC
Labels: bug
