### ISSUE TITLE
Riot does line breaks when trying to invite a user with a long name

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#12634] opened 2020-03-06 11:59 UTC
### Description

Entering a long username inserts a line break way too early and makes for a confusing UX.

Video of the behaviour: https://streamable.com/k4o42

![image](https://user-images.githubusercontent.com/1342360/76081902-0fa47c00-5fa2-11ea-9abb-9c47e079b69b.png)

### Steps to reproduce

- Start a chat with a user
- Start entering a long username
- See the field break after you type ~25 chars

Logs being sent: no

### Version information

- **Platform**: web
- **Browser**: Firefox Nightly v75.0a1
- **OS**: Debian Linux
- **URL**: riot.im/develop

**Comment by turt2live** [comment] 2020-03-06 16:48
Effective duplicate of https://github.com/vector-im/riot-web/issues/12205

**Closed by turt2live** 2020-03-06 16:48 UTC
Labels: bug
