### ISSUE TITLE
feaure request: please implement group calls using jitsi-meet

### ISSUE THREAD

**Issue by spellauge** [vector-im/riot-web#5838] opened 2017-12-14 08:16 UTC
### Description

please implement group calls using jitsi-meet including the possibilitzy to use my own jitsi-meet server

### Steps to reproduce

-

### Version information

- **Platform**: web (in-browser) or desktop? both

For the web app:

- **Browser**: Chrome, Safari, Firefox? which version? all
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? all
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? all
- **Version**: 0.13.3

**Comment by turt2live** [comment] 2017-12-14 15:32
Related/duplicate of: https://github.com/vector-im/riot-web/issues/5048

Other related issues:
* https://github.com/vector-im/riot-web/issues/4957
* https://github.com/vector-im/riot-web/issues/5388

**Closed** 2017-12-15 17:54 UTC
Labels: feature
