### ISSUE TITLE
breadcrumbs are slightly eaten

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#9034] opened 2019-03-04 12:09 UTC
![image](https://user-images.githubusercontent.com/8582858/53732602-5f73d300-3e76-11e9-894a-6389bededcc7.png)

**Comment by anoadragon453** [comment] 2019-03-04 12:14
Possible duplicate of https://github.com/vector-im/riot-web/issues/8954

**Closed** 2019-03-28 17:29 UTC
Labels: bug, cosmetic, type:breadcrumbs, ui/ux
