### ISSUE TITLE
we need a way to highlight that there are unsent msgs in a room at the room list level

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-web#7754] opened 2018-11-27 15:05 UTC
true on every platform

**Comment by turt2live** [comment] 2018-11-27 16:31
Duplicate of https://github.com/vector-im/riot-web/issues/1351, https://github.com/vector-im/riot-web/issues/1898, or https://github.com/vector-im/riot-web/issues/4824

**Closed by turt2live** 2018-11-27 16:31 UTC
