### ISSUE TITLE
Users are getting lost in the reset password process

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-web#12395] opened 2020-02-17 10:28 UTC
Several users complained about not logging in after having reseting their password.
I investigated and realized that they did not go until the end of the forget password process. They go back to the login screen from the first screen which tells them about the email (they do not read that they have to press the button below after checking the email...)
So the new password is not set, and they fail to log in on a wrong password error...

This remark concerns **all** the clients (not only riot-web), because it is due to the current forget password process. This process is based on the [account/password](https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-account-password) API used with a `m.login.email.identity` authentication type, and `threepidCreds` data.

**Comment by turt2live** [comment] 2020-02-17 20:02
Duplicate of https://github.com/vector-im/riot-web/issues/2780

**Closed by turt2live** 2020-02-17 20:02 UTC
Labels: bug, ui/ux
