### ISSUE TITLE
suggestion for emoticons

### ISSUE THREAD

**Issue by aleex5** [vector-im/riot-web#9469] opened 2019-04-14 22:40 UTC
from what I saw they have a button for the stickers, but I do not see anywhere that you see a button to see the available emoticons

my suggestion is that on the same button of the stickers is added a tab that is for the emoticons
That way, it'd all be on the same button.

It would also be nice to add the option to add packs of emoticons or custom emoticons

**Comment by turt2live** [comment] 2019-04-14 22:41
Duplicate of https://github.com/vector-im/riot-web/issues/1107

**Closed by turt2live** 2019-04-14 22:41 UTC
Labels: suggestion
