### ISSUE TITLE
Allow blurbs for users

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#12105] opened 2020-01-28 13:45 UTC
User names may not be familiar, and are not the place for explanations.  Robots might have a global blurb explaining what they do.  Human users might have a global blurb, and then per-room specific blurbs informing how they are relevant to that room - knowledge, opinions/position, formal status, ..

**Comment by turt2live** [comment] 2020-01-28 14:06
Duplicate of https://github.com/vector-im/riot-web/issues/1401

**Closed by turt2live** 2020-01-28 14:06 UTC
Labels: suggestion

**Comment by Biep** [comment] 2020-01-28 14:15
It was indeed a duplicate, but rather of #7704
I added the bit about hierarchy there.
