### ISSUE TITLE
make access_token visible again in settings, but behind spoiler text

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3325] opened 2017-02-26 21:22 UTC

**Comment by ara4n** [comment] 2017-02-28 00:17
@richvdh you seemed to be objecting to this - what's the story?

**Comment by richvdh** [comment] 2017-02-28 16:37
not objecting, just thought we'd discussed it and you weren't in favour. I am in favour :).

**Comment by t3chguy** [comment] 2017-04-17 21:25
Duplicate of #3170

**Closed** 2017-04-18 06:41 UTC
Labels: feature, p2, type:usersettings
