### ISSUE TITLE
Etherpad have defaut focus over chat

### ISSUE THREAD

**Issue by nim65s** [vector-im/riot-web#12924] opened 2020-03-30 08:41 UTC
Hi,

### Description

In rooms without any integrations, the focus automatically goes to the chat, which is the behavior I'm expecting.
But in rooms with an etherpad integration, the pad gets the focus, so we are used to send keystrockes to the chat by default, but they are going to the pad instead, which is annoying.

This issue is an extension of #5775, which seems fixed in the case without etherpad.
I also tried with Jitsi, and it doesn't steal the focus.

### Version information

- **Platform**: both

For the web app:

- **Browser**: Firefox 
- **OS**:  Arch Linux
- **URL**: riot.im/app 1.5.13

For the desktop app:

- **OS**: Arch Linux
- **Version**: 1.5.12

**Comment by t3chguy** [comment] 2020-03-30 08:43
Duplicate of https://github.com/vector-im/riot-web/issues/5130

**Closed by t3chguy** 2020-03-30 08:43 UTC
Labels: bug, ui/ux
