### ISSUE TITLE
Riot Desktop taskbar icon disappearing despite Riot still running

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/riot-web#13854] opened 2020-05-28 21:54 UTC
### Description

The Riot taskbar icon disappears after a while on Ubuntu 20.04 and possibly other systems (untested) after a while. Riot is still running in the background.

### Steps to reproduce

- Open Riot on Ubuntu 20.04.
- Wait...
- Possibly try locking and unlocking the screen.

### Expectation

- The taskbar icon remains where it was.

### What actually happens

- The taskbar icon disappears **despite Riot still running in the background**.

### Version information

- **Platform**: Ubuntu 20.04 Desktop Client.
- **Version**: 1.6.2.

**Comment by t3chguy** [comment] 2020-05-28 22:26
Duplicate of https://github.com/vector-im/riot-web/issues/13692

**Closed by t3chguy** 2020-05-28 22:26 UTC
Labels: bug
