### ISSUE TITLE
can't accept or reject a chat invite

### ISSUE THREAD

**Issue by RubenKelevra** [vector-im/riot-web#14291] opened 2020-07-02 14:03 UTC
### Description

I'm using the desktop client under Linux with an matrix.org account.

I've got a chat invite by a user with the ID `@jake:hemmerle.dev`, which I can't accept nor deny. Both fails with this error message:

> Failed to join room
> No known servers

### Version information

For the desktop app:

- **OS**: ArchLinux
- **Version**: 1.6.4 (olm version: 3.1.3)

**Comment by t3chguy** [comment] 2020-07-02 14:14
Duplicate of https://github.com/vector-im/riot-web/issues/3743

After clicking Reject, go to Settings > Help & About > Clear cache and reload as a workaround

**Closed by t3chguy** 2020-07-02 14:14 UTC
Labels: bug
