### ISSUE TITLE
Hitting Ctrl-K highlights memberlist instead of room list

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-web#9029] opened 2019-03-03 00:41 UTC
### Description

Hitting the room filter shortcut (Ctrl-k) highlights the memberlist filter if it's open. Seems like it's overriding the room list filter if it's loaded.

### Steps to reproduce

- Go into room
- Make sure memberlist is open
- Hit Ctrl-k to filter rooms
- Filters memberlists instead

Ideally we'd have another shortcut for filtering memberlist as well.

Log: not sent    

### Version information

- **Platform**: web

For the web app:

- **Browser**: Chrome
- **OS**: Debian Linux
- **URL**: Independent build of riot.im/develop

**Comment by t3chguy** [comment] 2019-03-03 09:17
This may have been caused by me making them use a shared component and derping. Will fix tomorrow

**Comment by dbkr** [comment] 2019-03-06 13:47
Adding regression label - shipping regressions like this is really annoying to users who use the features regularly. We actually noticed this and still shipped the regression. :(

**Comment by jryans** [comment] 2019-03-06 15:15
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2759

**Closed by jryans** 2019-03-06 15:15 UTC
Labels: bug, major, p1, regression
