### ISSUE TITLE
Device verification dialog hidden behind unknown sessions dialog?

### ISSUE THREAD

**Issue by rxl881** [vector-im/riot-web#12745] opened 2020-03-16 11:10 UTC
### "Verify" button on "Room contains unknown sessions" dialog appears to do nothing. 

When attempting to verify a device (because of an unknown device in a room) the verify button (as shown in the following screenshot) appears to do nothing. When dismissing this dialog (by clicking the "send anyway" button) the verify dialog becomes visible and appears to have been hidden behind.

![e2e](https://user-images.githubusercontent.com/6763606/76750372-15564a80-6776-11ea-8e6d-bc934a1b310d.png)

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

Describe how what happens differs from what you expected.

* Try to send a message
* Warned that there are unverified devices in the room (verify device / send anyway)
* Click verify devices link.
* Try to click the "verify" button in the resultant dialog, nothing happens.
* Click "send anyway" which dismisses the dialog.
* Verify device dialog is then visible.

### Version information

- **Platform**: Web

For the web app:

- **Browser**: Chrome 80.0.3987.132 (Official Build) (64-bit)
- **OS**: Linux
- **URL**: https://vector.riot.im/ 1.5.12

**Comment by t3chguy** [comment] 2020-03-16 11:12
This dialog doesn't exist in cross-signing so considering *fixed*

**Comment by turt2live** [comment] 2020-03-16 15:53
Effectively a duplicate of https://github.com/vector-im/riot-web/issues/11800

**Closed by turt2live** 2020-03-16 15:53 UTC
Labels: bug

**Comment by jryans** [comment] 2020-03-17 16:51
Yes, this should be fixed by cross-signing work, so we just need to get that over the line. 😄
