### ISSUE TITLE
Deleted-Message-Placeholder is too bright in dark mode

### ISSUE THREAD

**Issue by targodan** [vector-im/riot-web#8655] opened 2019-02-14 20:42 UTC
Related to all versions. First observed on Windows 10 Desktop version.

### Description

The deleted-message-placeholder is glaring in dark-mode. A more muted design would be nice.

I experimented in the client a bit using `Ctrl+Shift+I` (that's a capital i) and changed the css of said placeholder by adding a bit of transparency.

```
background: repeating-linear-gradient( -45deg, #E2E2E0C0, #e2e2e2C0 3px, transparent 3px, transparent 6px );
box-shadow: 0px 0px 3px #ccccccc0 inset;
```

This is what it looks like after the change:
![capture](https://user-images.githubusercontent.com/6468902/52816099-cafd2880-30a0-11e9-9a3a-2827d53b59f8.PNG)

Since I don't know about riots architecture and I haven't tried this change in light mode I don't know where it should go.

### Steps to reproduce

- Enable dark mode
- Go into a room
- Write a message
- Delete it

Log: not sent

**Comment by turt2live** [comment] 2019-02-14 20:48
Duplicate of https://github.com/vector-im/riot-web/issues/8559

**Closed by turt2live** 2019-02-14 20:48 UTC
Labels: redesign
