### ISSUE TITLE
Rooms with expanded widgets hijack keyboard input

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#13075] opened 2020-04-08 11:33 UTC
If you navigate to a room with an expanded widget which accepts text input (e.g. etherpad) then your keyboard input is hijacked by the widget. In practise, this is incredibly frustrating as the (a) you end up typing with no idea where your text is going, making the app seem broken while adding extraneous bogus things to widgets & (b) you have to reach for your mouse to click on the composer & (c) CMD+K no longer works to navigate to another room.

**Comment by t3chguy** [comment] 2020-04-08 11:34
Duplicate of https://github.com/vector-im/riot-web/issues/5130

**Closed by t3chguy** 2020-04-08 11:34 UTC
