### ISSUE TITLE
New room list: Notification badge roulette

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#14348] opened 2020-07-06 13:37 UTC
When I get a bing, the badge at the top of the roomlist turns red. I can click that badge to go to the source of the bing, I think.

However I can't see which rooms have notifications other than by scrolling through the full list. So the only tractable way to find out who is binging me is to jump blind into the room. This can be problematic if it's not somebody I want to engage with right away. It's worse when there are lots of notifs - this UX doesn't let me choose the one I engage with first.

Personally, I'd prefer if clicking the notif count temporarily filtered the list of rooms to rooms with notifs so I could make that choice.

**Comment by t3chguy** [comment] 2020-07-06 13:42
Duplicate of https://github.com/vector-im/riot-web/issues/14307

**Comment by t3chguy** [comment] 2020-07-06 13:42
This isn't different behaviour than what we have today so I wouldn't say its new room list related

**Closed by t3chguy** 2020-07-06 13:42 UTC
Labels: suggestion, type:new-room-list
