### ISSUE TITLE
Timestamp overlaps avatar in reply to `/me` message …

### ISSUE THREAD

**Issue by fooness** [vector-im/riot-web#13132] opened 2020-04-11 15:06 UTC
<img width="452" alt="Screenshot 2020-04-11 at 17 03 12" src="https://user-images.githubusercontent.com/11408027/79047392-8de5e500-7c16-11ea-83ff-0df7ea5cc7f4.png">

Firefox `75.0` and Chromium `83.0.4099.0` on macOS `10.14.6` …

**Comment by t3chguy** [comment] 2020-04-11 15:07
Duplicate of https://github.com/vector-im/riot-web/issues/2284

**Closed by t3chguy** 2020-04-11 15:07 UTC
Labels: bug, ui/ux
