### ISSUE TITLE
Community Filter Panel turns off after Clear Cache and Reload

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/riot-web#8822] opened 2019-02-20 11:40 UTC
### Steps to reproduce

- go to settings
- turn off "Enable Community Filter Panel"
- close settings
- panel still visible
- reload browser
- panel still visible
- Clear Cache and Reload
- panel gone
- profit

### Version information

riot-web 1.0.1
chromium 72.0.3626.7

**Comment by jryans** [comment] 2019-02-20 12:02
Thanks for the report! I believe this is a duplicate of https://github.com/vector-im/riot-web/issues/8418.

**Closed by jryans** 2019-02-20 12:02 UTC
