### ISSUE TITLE
Writing lots of data to disk

### ISSUE THREAD

**Issue by kroeckx** [vector-im/riot-web#8863] opened 2019-02-21 17:29 UTC
I'm seeing writing to disk at an average rate of about 3 MB/s. I'm using the electron riot-web .deb package (1.0.1).

The console is showing a lot of saving of device tracking data. An other thing I notice, I'm not sure it's related, is that I see a lot of requests to synapse.

**Comment by ara4n** [comment] 2019-02-21 18:22
thanks for the logs.

```
2019-02-20T04:03:41.836Z I Saving device tracking data at token s1421792_77429083_33480_3960540_2045_2_24040_447135_1
2019-02-20T04:03:42.961Z I Saving device tracking data at token s1421792_77429085_33480_3960541_2045_2_24040_447135_1
2019-02-20T04:03:43.607Z I Saving device tracking data at token s1421792_77429086_33480_3960542_2045_2_24040_447135_1
2019-02-20T04:03:44.361Z I Saving device tracking data at token s1421792_77429087_33480_3960542_2045_2_24040_447135_1
2019-02-20T04:03:46.146Z I Saving device tracking data at token s1421793_77429087_33480_3960542_2045_2_24040_447135_1
2019-02-20T04:03:53.892Z I Saving device tracking data at token s1421794_77429087_33480_3960542_2045_2_24040_447135_1
```

is clearly completely broken. @uhoreg, any idea what could  be causing that?

**Comment by uhoreg** [comment] 2019-02-21 19:07
I'm not sure.  We'd need to figure out why the device list is being marked as dirty.

@kroeckx what requests to synapse are you seeing?  Which endpoint(s) is it hitting?

**Comment by turt2live** [comment] 2019-02-21 19:50
(fwiw, I see those same messages constantly as a result of /sync being hammered on my account)

**Comment by uhoreg** [comment] 2019-02-21 20:11
Actually, I'm seeing similar things too, even though it doesn't look like any device data is actually being changed.

**Comment by kroeckx** [comment] 2019-02-21 21:31
Yes, it's doing /sync all the time, I think on average about once
a second, I think it's as fast as synapse can respond to it.

The log looks like:
2019-02-21 21:28:04,110 - synapse.access.https.8448 - 233 - INFO - GET-468361- 2a02:1810:1d01:e000:3cce:a105:d643:68ca - 8448 - Received request: GET /_matrix/client/r0/sync?filter=5&timeout=30000&since=s1434417_77698564_7012_3988298_2070_2_24057_450067_1
2019-02-21 21:28:04,115 - synapse.util.caches.response_cache - 151 - INFO - GET-468361- [sync]: no cached result for [(@kurt:roeckx.be, 30000, 's1434417_77698564_7012_3988298_2070_2_24057_450067_1', '5', False, 'AVMYMXYMJA')], calculating new one
2019-02-21 21:28:04,968 - synapse.handlers.sync - 906 - INFO - GET-468361- Calculating sync response for @kurt:roeckx.be between StreamToken(room_key='s1434417', presence_key='77698564', typing_key='7012', receipt_key='3988298', account_data_key='2070', push_rules_key='2', to_device_key='24057', device_list_key='450067', groups_key='1') and StreamToken(room_key='s1434417', presence_key=77698565, typing_key=7012, receipt_key=3988298, account_data_key=2070, push_rules_key=2, to_device_key=24057, device_list_key=450067, groups_key=1)
2019-02-21 21:28:04,977 - synapse.access.https.8448 - 302 - INFO - GET-468361- 2a02:1810:1d01:e000:3cce:a105:d643:68ca - 8448 - {@kurt:roeckx.be} Processed request: 0.864sec/0.003sec (0.016sec, 0.000sec) (0.000sec/0.000sec/0) 281B 200 "GET
/_matrix/client/r0/sync?filter=5&timeout=30000&since=s1434417_77698564_7012_3988298_2070_2_24057_450067_1 HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.0.1 Chrome/69.0.3497.106 Electron/4.0.4 Safari/537.36" [0 dbevts]

**Comment by uhoreg** [comment] 2019-02-22 04:08
The issue is that sync now forcibly enables tracking of your own devices, and the function to enable tracking of devices set the dirty flag even if nothing changed, so it would try to save changes, even though there were no changes to save.  This should be fixed by https://github.com/matrix-org/matrix-js-sdk/pull/846

**Comment by kroeckx** [comment] 2019-03-18 14:11
I guess this can be closed now?

**Closed** 2019-03-18 14:32 UTC
Labels: bug, major, p1, type:e2e
