### ISSUE TITLE
Add a Native Emoji Pallet for the Compose Input Box

### ISSUE THREAD

**Issue by banjo8675309** [vector-im/riot-web#13392] opened 2020-04-27 04:17 UTC
Right now native emoji's can be added with point/click as feedback to existing messages, but in the compose box, they are only able to be chosen by typing ":" and then a limited view of a selection of emojis is shown.  It would be nice if a full categorized pallet was shown (just like when giving feedback to messages)

Showing this emoji pallet:
![image](https://user-images.githubusercontent.com/64051199/80333478-41a4c280-881c-11ea-83ce-fed322af3790.png)

Where this emoji partial listing is currently presented:
![image](https://user-images.githubusercontent.com/64051199/80333505-52edcf00-881c-11ea-9ce9-96b9868368eb.png)

**Comment by t3chguy** [comment] 2020-04-27 08:27
Duplicate of https://github.com/vector-im/riot-web/issues/1107

**Closed by t3chguy** 2020-04-27 08:27 UTC
Labels: suggestion
