### ISSUE TITLE
RTE doesn't let you autocomplete MXIDs

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#4794] opened 2017-08-14 21:17 UTC
If a user in the room has no displayname and you type @foo<tab> or foo<tab> they don't come up at all.  This is a regression relative to pre-RTE

**Comment by lukebarnard1** [comment] 2017-08-15 09:50
I can't reproduce this (tested by tab-completing `@alan.` in HQ).

**Comment by lukebarnard1** [comment] 2017-08-15 09:56
(Related to this, autocompletion of userIds where a user has set their displayname has been disabled - https://github.com/vector-im/riot-web/issues/4495)

**Comment by ara4n** [comment] 2017-09-26 13:45
Turns out this is specific to trying to autocomplete commands - e.g. `/op @Am<tab>` doesn't autocomplete to `/op @Amandine:matrix.org`.  I would expect the pre-RTE behaviour to work in this case (or for slash-commands to accept pills)

**Comment by pafcu** [comment] 2017-10-03 12:58
Duplicate of https://github.com/vector-im/riot-web/issues/4762 ?

**Comment by uhoreg** [comment] 2017-12-15 18:51
closing as a dup of #4762, as it is is (temporary) intentional behaviour as documented in that issue:

> For now, we shall disallow tab-completing when entering a command (probably showing the visual bell (red flash) instead).

**Closed by uhoreg** 2017-12-15 18:51 UTC
Labels: bug, p2, regression, type:rte
