### ISSUE TITLE
Multiple messages selection

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#14669] opened 2020-07-20 22:44 UTC
Please add support to select multiple messages for later deletion, forwarding or copying.

**Comment by t3chguy** [comment] 2020-07-21 00:59
Duplicate of https://github.com/vector-im/riot-web/issues/7660

**Closed by t3chguy** 2020-07-21 00:59 UTC
Labels: suggestion

**Comment by 532910** [comment] 2020-07-21 14:27
#7660 is about only message deletion, but this one is about multiple (or all) messages selection for the following action.
