### ISSUE TITLE
z-index is broken for CIDER toolbar wrt unsent message warning

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#10814] opened 2019-09-10 10:26 UTC
<img width="517" alt="Screenshot 2019-09-10 at 11 25 55" src="https://user-images.githubusercontent.com/1294269/64606287-d3f77380-d3bd-11e9-9787-73b30eef3b31.png">

**Comment by bwindels** [comment] 2019-09-10 12:08
Dupe of #10780

**Closed by bwindels** 2019-09-10 12:08 UTC
