### ISSUE TITLE
first time loading shows wrong homeserver

### ISSUE THREAD

**Issue by smoebody** [vector-im/riot-web#9846] opened 2019-05-25 10:00 UTC
### Description

When I load my instance of riot the first time in a browser, which is configured to connect to my custom synapse-instance as default homeserver, the homeserver is always matrix.org. 
After reload my custom homeserver is used.

i set up the homeserver with the following riot-configuration:
```
"default_server_name": "metaccount.de",
```
### Steps to reproduce

- go to chat.metaccount.de
- note that the homeserver is `matrix.org`
- reload the page
- note that the homeserver is now `metaccount.de` 

It should be `metaccount.de` from the beginning since it leads to confused users.

Log: not sent    

### Version information

- **Platform**: web
- **Browser**: Chromium, 73.0.3683.86 
- **OS**: Fedora Linux 30
- **URL**: chat.metaccount.de

**Comment by turt2live** [comment] 2019-05-25 15:06
Duplicate of https://github.com/vector-im/riot-web/issues/9224 - see https://github.com/vector-im/riot-web/issues/9224#issuecomment-495300813

**Closed by turt2live** 2019-05-25 15:06 UTC
Labels: bug
