### ISSUE TITLE
Riot/Element goes to the bottom of unread messages by default

### ISSUE THREAD

**Issue by nunoperalta** [vector-im/riot-web#14706] opened 2020-07-22 19:05 UTC
With the latest version of Riot/Element, when I see a room with unread messages and open it,
now I'm automatically going to the very bottom of the room.

I really preferred when Riot brought me automatically to where the unread messages begin.
I'm afraid this makes it really hard to keep up with unread messages, as if I'm already at the bottom, I have to scroll up, messages become all marked as Read, and if I want to leave and come back to continue to respond to the rest, I lost track where I was.

This is definitely a pain, especially since I cannot mark messages as Unread in Riot/Element (#4406).

Please:

1) When I open a Room with unread messages, put me right to where the unread messages begin. I can scroll to the very bottom if I wished (I don't anyway... if my colleague wrote me messages, I need to read and respond to them).

2) This not a regression yet, but I'm afraid you might want to change this in the future,
but please continue NOT to auto-scroll me to the very bottom every time I send a message. Unfortunately, other chat systems like Whatsapp and Skype do this, and it really makes it hard to respond to messages "as we go/read". And this was one of the main reasons we chose Riot as our main chat system.

Thank you.

**Comment by t3chguy** [comment] 2020-07-22 23:21
Riot has never gone to unread when you open a room. It either goes to where you were if you were scrolled up, or if you were scrolled to the bottom it'll open the room at the new bottom.

Duplicate of https://github.com/vector-im/riot-web/issues/11235

**Closed by t3chguy** 2020-07-22 23:21 UTC
Labels: bug
