### ISSUE TITLE
1.4.0 blank screen

### ISSUE THREAD

**Issue by pikkauzernamme** [vector-im/riot-web#10983] opened 2019-09-27 15:29 UTC
### Description
After client received an update to version 1.4.0 and reloading, I can see nothing but blank screen. Riot Desktop on Windows 10. Same after logging into the web version.

### Steps to reproduce
- Update to 1.4.0
- See the blank screen

Logs being sent: no

### Version information

- **Platform**: both browser and desktop

For the web app:

- **Browser**: Firefox last version
- **OS**: Windows
- **URL**: riot.im/app

For the desktop app:

- **OS**: Windows
- **Version**: 10

**Comment by pikkauzernamme** [comment] 2019-09-27 15:30
After reinstall to version 1.3.6 everything works perfectly, but after few minutes desktop client automatically receives the update and reloads, so I'm currently unable to use Riot.

**Comment by t3chguy** [comment] 2019-09-27 15:32
@jryans I believe also hit this issue but then could not reproduce it, I updated on two Windows 10 machines and both went without issue :/

Could you open up the console (Control Shift I) to see what is happening?

**Comment by pikkauzernamme** [comment] 2019-09-27 16:29
Attached screen here [https://framadrop.org/r/7ldfOj5eOh#ju8CVZV8U2cuUGKz1ohRQ0Bo3tnZ4j8rIH4KxE1OYAY=](url)

**Comment by pikkauzernamme** [comment] 2019-09-27 16:31
I can interact with the app window itself, like open console and so on. But inside this there is only one background color of dark theme which I use. And the app name displays like "Riot | <nickname of other person I was speaking before bug>"

**Comment by jryans** [comment] 2019-09-27 16:35
@pikkauzernamme Are there any logs in the console? There may be useful errors there.

**Comment by gtbuchanan** [comment] 2019-09-28 01:44
This is the JavaScript error I'm receiving on the Windows app in this situation:

![image](https://user-images.githubusercontent.com/715687/65809821-58d8e000-e167-11e9-8fd5-9ecf47f626c6.png)

It occurred after joining the #matrix:matrix.org and #riot:matrix.org rooms.

**Comment by turt2live** [comment] 2019-09-28 02:20
rageshake attached, see https://matrix.to/#/!YTvKGNlinIzlkMTVRl:matrix.org/$RnXc8O6zpDZkcGzRkXtv-AJszHOa2_rLK1RFHHogDQM?via=matrix.org&via=privacytools.io&via=feneas.org for info

**Comment by RiasMo** [comment] 2019-09-28 03:05
I'm a topic starter. Github froze my account.

>  It occurred after joining the #matrix:matrix.org and #riot:matrix.org rooms. Closing the app completely and relaunching seems to fix it, so I'm not sure if it's the same exact problem as the OP.

Sometimes after closing the app and relaunching it I can see the last opened e2ee chat room **just for a moment**, and then it gets empty again. Just a single color.

Here is a screenshot of my console: [https://framapic.org/gallery#WJh2AxsO3moD/LTdkQyXUyeBC.png](url)

**Comment by RiasMo** [comment] 2019-09-28 06:37
That is so weird. I can't even load messages history from my mobile client. And when I login via browser the same happens - blank screen. At the same time, new account on the same homeserver works great (at least in the public chat rooms, I didn't test in e2ee ones yet). It seems like my account is corrupted somehow.

**Comment by RiasMo** [comment] 2019-09-28 06:47
Now I have to run desktop app manually from the AppData/Local/riot-web/app-1.3.6 to access my account. And in that case it works great - chat history loads and that's fast, I can see all the messages and use it like I usually do

**Comment by DrJHD** [comment] 2019-09-28 11:25
I get exactly the same issue on Windows Server 2008. A link to the installer for the previous version would be very helpful.

**Comment by RiasMo** [comment] 2019-09-28 17:00
> 
> 
> I get exactly the same issue on Windows Server 2008. A link to the installer for the previous version would be very helpful.

https://packages.riot.im/desktop/install/win32/x64/Riot%20Setup%201.3.6.exe
Run manually from the %AppData%/Local/riot-web/app-1.3.6 folder so it doesn't automatically update to the newer version

**Comment by davehayes** [comment] 2019-09-28 20:11
This is an issue on MacOS too using the Riot installed from the DMG file.

**Comment by jryans** [comment] 2019-09-28 20:28
For those affected, does it only happen in the desktop app, or are https://riot.im/app and https://riot.im/develop exhibiting the same issue?

**Comment by RiasMo** [comment] 2019-09-29 02:16
@jryans I have tried with the desktop windows app and the web version on my homeserver. When I log in via web client, I instantly get this blank screen again. But when I created a new account via web client on the same homeserver, I was able to join public chat room, send a message and nothing happened. However, when I tried to change my password via desktop **1.3.6** client for _problem_ account, my Android client starts lagging, like reloading the same screen all the time non-stop, like swiping and loading screen again.

**Comment by haakonn** [comment] 2019-09-29 21:12
@jryans I haven't tried the desktop app, but https://riot.im/app and https://riot.im/develop are absolutely exhibiting the issue in Firefox. I've tried on two different machines, and also in a fresh profile with no add-ons.

**Comment by phil-flex** [comment] 2019-09-30 05:41
![image](https://user-images.githubusercontent.com/34325924/65852175-ef83e780-e387-11e9-94c0-35ceadb43de3.png)
via `yarn start` debug console shows error above

**Comment by phil-flex** [comment] 2019-09-30 05:43
![image](https://user-images.githubusercontent.com/34325924/65852282-3f62ae80-e388-11e9-81eb-4db4cb023fa5.png)

In Chrome, it display the error above.

**Comment by wobblywob** [comment] 2019-09-30 09:00
I have the same issue. 

Web client shows one of my rooms briefly, for about half a second, then I get a completely blank screen. Happens on chrome and firefox, on linux and mac.

This is a self-hosted synapse 1.3.1 on ubuntu 18.04, running through haproxy and url_preview_enabled.

- macOS app 1.3.6 works
- macOS app 1.4 doesn't work
- riot.im/app and riot.im/develop don't work on either chrome or firefox

**Comment by jryans** [comment] 2019-09-30 09:03
@phil-flex I am fairly confident the issue you are seeing is separate from this. See https://github.com/vector-im/riot-web/issues/10981#issuecomment-535966062 for steps.

**Comment by jryans** [comment] 2019-09-30 09:20
@gtbuchanan I believe the stack trace you've included there shows that React has fallen apart, but it doesn't really suggest the root cause... Is there anything earlier in the logs?

**Comment by jryans** [comment] 2019-09-30 09:28
At the moment, I am still not quite sure what the issue is... If others could attach logs or rageshakes, that would be helpful. You can still send a rageshake even from a white screen using the app or browser's console:

1. Ctrl-Shift-I to open the DevTools, go to Console tab
2. Run `mxSendRageshake("For https://github.com/vector-im/riot-web/issues/10983")` in the console

For now, I will focus on the the base avatar / length issue suggested in @RiasMo's screenshot.

**Comment by jryans** [comment] 2019-09-30 16:08
@RiasMo https://riot.im/develop has a potential fix for this issue. Could you retest there and capture a new set of logs if the issue persists?

**Comment by haakonn** [comment] 2019-09-30 17:51
@jryans https://riot.im/develop works for me now, and it did not last time I tried, 21 hours ago.

**Comment by wobblywob** [comment] 2019-09-30 18:53
@jryans develop works for me too

**Comment by davehayes** [comment] 2019-10-01 01:51
Here is another snapshot of devtools on an affected 10.13 mac:

![rsnap](https://user-images.githubusercontent.com/6225697/65928524-23c0cd80-e3b3-11e9-8b2f-f6a8f9e2c788.png)

**Comment by RiasMo** [comment] 2019-10-01 02:42
> 
> 
> @RiasMo https://riot.im/develop has a potential fix for this issue. Could you retest there and capture a new set of logs if the issue persists?

Unfortunately, I have deleted my account. But I think my problem was the same as @haakonn's.

**Comment by jryans** [comment] 2019-10-01 09:46
Great, I'll consider the current issue fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3498 then. We'll do another release soonish so that desktop users have the fix as well.

In addition, I'll look into ways of handling this class of errors more gracefully in the future.

**Comment by jryans** [comment] 2019-10-01 12:35
Riot 1.4.1 has been released for web and desktop with this fix. Thanks for reporting the issue and your patience while we worked on a fix.

**Closed by jryans** 2019-10-01 12:35 UTC
Labels: bug, defect, 🔥 Fire 🔥

**Comment by davehayes** [comment] 2019-10-01 20:28
This issue has been fixed on my client's computer.
