### ISSUE TITLE
Element canvas icons fail to render in Firefox nightly

### ISSUE THREAD

**Issue by tmarble** [vector-im/riot-web#14483] opened 2020-07-15 13:35 UTC
### Description

Icons (for users/rooms that have not uploaded an image avatar) are rendered incorrectly in Firefox.

### Steps to reproduce

- Open Element Web in Firefox: https://app.element.io/
- View any users or rooms that do _not_ have an image avatar

Describe how what happens differs from what you expected.

- These non-image icons are rendered incorrectly: there is not a solid color background, but instead some screen artifacts

_Workaround:_  I have to manually click in the icon in the toolbar (to the left of https) and allow the site to "Extract Canvas Permissions" -- and then reload the page.

For better UX the user should be explictly prompted to change this. This workaround will "fix" the UX, but leaves a big privacy concern: allowing canvas permissions is not a good idea for a privacy minded application like Element. How is using a canvas justified when there are alternatives: this could be a simple **div** or even an **svg** icon?

_NOTE:_ In Firefox various canvas security things can be toggled in **about:config** search: **canvas** (I have tried many permuations of these settings -- the only solution was allowing Canvas Extraction for this page)

Logs being sent: no

### Version information

- **Platform**: web (in-browser) or desktop?: 
  - **web**

For the web app:
- **Browser**: Chrome, Safari, Firefox? which version?
  - **Firefox Nightly: 80.0a1 (2020-07-14) (64-bit)**
- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc?
  - **Debian GNU/Linux - unstable**
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?
  - **https://app.element.io/**

![element-canvas-bug](https://user-images.githubusercontent.com/107828/87549179-04263780-c69d-11ea-8f6d-8f24b84ed41a.png)

**Comment by tmarble** [comment] 2020-07-15 13:38
label: privacy

**Comment by t3chguy** [comment] 2020-07-15 13:38
> For better UX the user should be explictly prompted to change this.

The issue is there is no way to tell it is disabled, Firefox used to error but now just gives random stripy data instead.

> How is using a canvas justified when there are alternatives: this could be a simple div or even an svg icon?

The canvas is used to client-side generate images, in this case solid coloured circles, to both render and pass to the Notifications API.
The canvas is also used to generate media thumbnails client-side instead of relying on server-generated thumbnails *for privacy reasons* in end-to-end encrypted rooms.

Closing as duplicate of resolved issue https://github.com/vector-im/riot-web/issues/14433

**Closed by t3chguy** 2020-07-15 13:38 UTC
Labels: bug, ui/ux
