### ISSUE TITLE
ILAG login can fail leaving you stuck on two spinners.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6734] opened 2018-05-15 15:47 UTC
I just tried to test following an link to a non-peekable but public join_rules room in an incognito tab (riot.im/develop/#/room/#foo:matrix.org) ; ILAG failed badly after signing up my account in order to join the room, leaving me staring at two spinners - one in the background trying to join the room; another in an ugly grey foreground overlay that covered the whole screen).

**Comment by bwindels** [comment] 2018-07-03 15:25
Was this filed before GDPR consent was put into place?

**Comment by ara4n** [comment] 2018-07-03 17:32
Yes it was. But the bug still exists, except we get stuck on one spinner rather than two now...

**Comment by bwindels** [comment] 2018-07-03 17:40
Went through it with Matthew and the remaining problematic behaviour is a dupe of #6679

**Closed** 2018-07-03 17:42 UTC
Labels: ILAG, bug, cannot-reproduce, major, p1
