### ISSUE TITLE
Customizable details/"about me" text/notes in member info

### ISSUE THREAD

**Issue by WebFreak001** [vector-im/riot-web#9244] opened 2019-03-22 08:05 UTC
**Is your suggestion related to a problem? Please describe.**
I want to show some user information stored on our active directory server such as telephone number, room number, etc. and need some sort of display method for the user for this.

**Describe the solution you'd like**
I'd like to have some kind of user notes, stored on the matrix server, (so they could also be changed by the server) which are shown and editable on all devices of the user when clicking on some member.

**Describe alternatives you've considered**
So far _some_ users have added their phone suffix into their username however this didn't really catch on with others and was kind of impractical.

Alternatively some kind of "About me" text would probably be good enough to and maybe easier to implement. This should also be settable by the server if possible.

**Additional context**
I like in discord that you can attach notes on any user with a very simple UI. Maybe something like that could be implemented here. In some other messaging services, a user can set an "About me" text which others can see which would also work well for this.

Being able to store markdown or basic html, or at least clickable URLs (also non-http) in this would be very nice to have.

UI suggestion: (maybe pencil button instead, or button completely hidden for other users depending on whether this is a user note or an "about me" section)
![image](https://user-images.githubusercontent.com/2035977/54808475-9b81a300-4c80-11e9-93a0-596ff2510249.png)

**Comment by turt2live** [comment] 2019-03-22 14:59
Thanks for the detailed post! Unfortunately this is a duplicate of https://github.com/vector-im/riot-web/issues/1401 however - I would recommend adding your 👍 to that issue.

**Closed by turt2live** 2019-03-22 14:59 UTC
Labels: suggestion

**Comment by WebFreak001** [comment] 2019-03-22 15:03
#7704 seems like a better duplicate of this
