### ISSUE TITLE
:+ doesn't bring up thumbsup emoji 

### ISSUE THREAD

**Issue by hpdeifel** [vector-im/riot-web#11657] opened 2019-12-12 17:13 UTC
### Description

Typing emoji `:+` recently stopped working in the flatpak version. It shows the emoji picker on `:` but doesn't narrow the results on `+`. Previously it narrowed the picker down to the :+1:  emoji. I'm not sure if flatpak is a red herring, but it still works for me in `/app`.

### Steps to reproduce

- Type `:+`

Expected result: The emoji picker narrows down to :+1: 
Actual result: The emoji picker shows the whole set of emojis

### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Fedora, Flatpak
- **Version**: 1.5.6

**Comment by turt2live** [comment] 2019-12-12 17:14
It's not a flatpack problem

**Comment by t3chguy** [comment] 2019-12-19 14:54
Pretty sure this is fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3745

```
Uncaught (in promise) TypeError: Cannot read property 'normalize' of null
    at stripDiacritics (QueryMatcher.js:27)
    at QueryMatcher.setObjects (QueryMatcher.js:76)
    at CommunityProvider.getCompletions (CommunityProvider.js:79)
```

seems to be the cause, some emoji don't have expected fields, I happened to add a null-guard in the above PR :)

**Closed** 2019-12-19 19:25 UTC
Labels: bug, type:emoji

**Comment by sikandar-quraishi** [comment] 2020-12-19 13:25
please tell me how to resolve "TypeError: Cannot read property 'thumbsUp' of undefined" in redux

**Comment by jryans** [comment] 2020-12-21 11:59
Please open a new issue or discuss in a room such as #element-web:matrix.org.
