### ISSUE TITLE
You can still click on rooms even when the roomlist is greyed out

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#5415] opened 2017-10-24 13:56 UTC
To reproduce:
- open user/room settings
- see the roomlist go grey
- click on it
- it works anyway

Potentially not actually a problem, but following principles of least surprise, @lukebarnard1 and I were both just surprised by this :P

**Comment by turt2live** [comment] 2017-10-24 15:58
Duplicate of https://github.com/vector-im/riot-web/issues/2073 (in a way)

**Comment by lukebarnard1** [comment] 2017-10-24 16:11
yep

**Closed by lukebarnard1** 2017-10-24 16:11 UTC
Labels: bug, minor, p3, ui/ux
