### ISSUE TITLE
Message stuck as newest message

### ISSUE THREAD

**Issue by AnthyG** [vector-im/riot-web#9443] opened 2019-04-12 13:28 UTC
### Description

After having sent one message (private chat, encrypted), that message kept staying at the very bottom of all new messages I sent (the timestamps were still correct).

### Steps to reproduce

- Send message
- ???
- Send more messages
- ???
- first message is still at the very bottom (as if it were the newest one)
- reload
- first message back at the correct place

The expected behaviour would be that the first message shouldn't move to the most recent slot in the history. And after reloading, the message should still be in the history, but it isn't.

Log: not sent (couldn't send)    

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 66.0.3 (32-Bit)
- **OS**: Windows 10
- **URL**: somewhere else, develop version

**Comment by bwindels** [comment] 2019-04-15 09:59
Hi @AnthyG , thanks for reporting this. Do you think the messages that ended up in the wrong order got sent? It sounds like they didn't, and we got the sorting of unsent messages wrong somehow, and then additionally you hit #7177 . Can I also ask if you were using the matrix.org homeserver or another one?

Would be great if you could retry sending logs, that should work again now.

**Comment by AnthyG** [comment] 2019-04-15 17:25
The messages did get sent, as I still saw them after reload, was also able to reply to them, and my conversation partner was also able to see them.
However, I believe they were in send-queue for a longer time than usual. Not sure if this might've been because of a bad connection at that time tho.
I was using an (I believe) up-to-date-with-the-latest-dev-version homeserver hosted by @anoadragon453.

Still got the log in form of an .har-file (which should contain everything you need, however you would need to decompress the compressed log file from that), and I guess that is the only way I can still send it to you, as I suppose, Riot doesn't keep a log beyond the current and last session. How should I go about in getting it to you?

**Comment by lampholder** [comment] 2019-04-30 14:04
I also have seen this recently.

**Comment by AnthyG** [comment] 2019-04-30 18:10
Do you guys still need my Log then?

**Comment by turt2live** [comment] 2019-04-30 19:01
if you've seen it again in the last 24ish hours, then yes please.

**Comment by hieronymousch** [comment] 2019-05-09 17:31
I have the same problem for the riot windows desktop client

**Comment by mstroud** [comment] 2019-05-10 16:24
I have the same problem. I've noticed that the offending (stuck) message is missing the the following information from the server message:

Most recent (actual) message:
```
...
"origin_server_ts": 1557503961694,
"unsigned": {
    "age": 40
  },
...
```

"Stuck" message:
```
...
"origin_server_ts": 1557499832504,
...
```
I'm using Riot Desktop/Web version "riot-web version: 1.1.0" on Windows 7 with a self-hosted synapse server (matrix-synapse==0.99.1.1)

**Comment by turt2live** [comment] 2019-05-10 16:33
@mstroud please go to your account settings, click on the "Help & About" tab, and submit debug logs for this issue. It's hard to figure out what is going on when no one is submitting logs :(

**Comment by mstroud** [comment] 2019-05-10 16:35
@turt2live Done

**Comment by hieronymousch** [comment] 2019-05-10 18:08
likewise

**Comment by matoro** [comment] 2019-05-12 17:25
I see this as well, desktop app 1.1.0 on Linux and synapse 0.99.3.2.  Seems to be a strictly visual bug as closing and reopening the app does fix it.

**Comment by procopsamuraev** [comment] 2019-05-14 09:11
have a same problem with 1-1 chat, not encrypted. Close/open application solve the problem for while.

**Comment by turt2live** [comment] 2019-05-15 20:05
I've definitely seen this personally, but can't reproduce it. From the 3 logs collected, "Unable to call 'setDMRoom' of undefined" comes up frequently - will investigate that.

**Comment by turt2live** [comment] 2019-05-15 20:19
I think this was actually fixed as https://github.com/matrix-org/matrix-react-sdk/pull/2951

**Closed by turt2live** 2019-05-15 20:19 UTC
Labels: bug, p1, type:timeline, 🔥 Fire 🔥

**Comment by ericmigi** [comment] 2019-05-16 04:47
Still occurring on 1.1.2. not 100% reproducible but happening pretty reliably. Need more logs on this one?

**Comment by hieronymousch** [comment] 2019-05-16 04:54
I can confirm that it still occurs on 1.1.2 (had one yesterday)

**Comment by turt2live** [comment] 2019-05-16 05:07
1.1.2 does not have the fix in it.

**Comment by hieronymousch** [comment] 2019-05-16 05:37
This is what we get: ![image](https://user-images.githubusercontent.com/7361893/57828887-5cb62800-77ad-11e9-8c42-4e815bac699a.png)

**Comment by amb26** [comment] 2020-11-26 14:40
I saw this just yesterday on Element version 1.7.14 - it was only fixed by the "clear cache and reload" button in settings. So far has occurred only once in about a month of usage.

**Comment by konomikitten** [comment] 2021-09-26 23:41
I had this occur recently this doesn't seem fixed, happened when in a DM with a friend, restarting the desktop client and removing the message worked for me.

Element version: 1.8.5
Olm version: 3.2.3

**Comment by anoadragon453** [comment] 2021-09-27 07:57
Note that this is currently being tracked from the Synapse side at https://github.com/matrix-org/synapse/issues/9424.
