### ISSUE TITLE
Offer to reduce image size on uploading

### ISSUE THREAD

**Issue by grafenhofer** [vector-im/riot-web#5813] opened 2017-12-12 08:50 UTC
In the Android version a resolution reduction is suggested before uploading a picture. This feature would be very helpful to have in the web client too, especially since image sizes can be huge when coming from high resolution cameras.

**Comment by uhoreg** [comment] 2017-12-13 17:15
somewhat related to https://github.com/vector-im/riot-web/issues/4426

**Comment by pafcu** [comment] 2017-12-14 08:45
Duplicate of https://github.com/vector-im/riot-web/issues/4144

**Comment by uhoreg** [comment] 2017-12-14 14:39
Good catch, @pafcu .  Closing.

**Closed by uhoreg** 2017-12-14 14:39 UTC
