### ISSUE TITLE
Gopher links don't display correctly

### ISSUE THREAD

**Issue by hook54321** [vector-im/riot-web#7802] opened 2018-12-10 13:58 UTC
Gopher links don't display correctly and clicking them doesn't do anything

- **Platform**: Desktop

![image](https://user-images.githubusercontent.com/7744057/49737009-8f4e7880-fc83-11e8-9732-4d872f37386b.png)

**Comment by lampholder** [comment] 2018-12-10 14:32
You're welcome to submit a PR to fix this (it's probably a trivial addition to the set of linkified protocols) but I'm afraid I don't think it's something we'll get to any time soon :P

**Comment by t3chguy** [comment] 2018-12-10 14:38
Sadly not that simple 
This is a duplicate of https://github.com/vector-im/riot-web/issues/5094

**Closed by t3chguy** 2018-12-10 14:38 UTC
Labels: feature, p4

**Comment by hook54321** [comment] 2018-12-10 14:40
What about https://github.com/vector-im/riot-web/issues/4457 ?

**Comment by t3chguy** [comment] 2018-12-10 15:10
That too, though that issue has slightly devolved into handling `file://` in the desktop app, which does get linkified correctly, so its just Related to that one
