### ISSUE TITLE
No arrows to previous/next image

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#8744] opened 2019-02-17 10:35 UTC
If I click on an image to see it full-screen, there are no arrows to move to the previous or next image in the room.  Please add those, as they are very handy if one wants to watch a bunch of images (or films)

**Comment by t3chguy** [comment] 2019-02-18 12:06
Duplicate of https://github.com/vector-im/riot-web/issues/337

**Closed by t3chguy** 2019-02-18 12:06 UTC
