### ISSUE TITLE
roomlist filter isn't recalculated when you unselect a community

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12977] opened 2020-04-01 10:54 UTC

**Comment by t3chguy** [comment] 2020-04-01 11:40
I cannot reproduce this, any chance of a gif?

![rlf](https://user-images.githubusercontent.com/2403652/78133247-00d0ae00-7416-11ea-8514-e3c3351291fd.gif)

**Comment by t3chguy** [comment] 2020-07-04 16:50
Presumably will be fixed by the new room list which rewrites this entire part of the app

**Comment by t3chguy** [comment] 2020-07-04 16:57
(Assuming solved, re-open if not)

**Closed by t3chguy** 2020-07-04 16:57 UTC
Labels: cannot-reproduce

**Comment by turt2live** [comment] 2020-07-04 17:18
(had better be solved, the filtering logic is 5x more intelligent now)
