### ISSUE TITLE
failure mode on starting chat when room creation fails is terrible

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#5169] opened 2017-10-05 13:00 UTC

**Comment by lampholder** [comment] 2017-10-11 14:37
Vague issue is vague :D 
Would you say it's P1 terrible, or more of a P3 terrible?

**Comment by dbkr** [comment] 2017-10-18 08:56
Sorry, probably about p2 terrible. :) The problem is that if the call to create the room fails, the exception basically gets caught by a handler intended to handle a different failure mode so the error message makes no sense.

**Comment by aaronraimist** [comment] 2018-10-27 02:00
Error message looks like and you still get an empty room even though the error message is failure to create room...

![screen shot 2018-10-26 at 8 18 50 pm](https://user-images.githubusercontent.com/5855073/47598503-1230a380-d962-11e8-9088-3a22b0d4d9b2.png)

**Comment by aaronraimist** [comment] 2018-10-27 02:01
Duplicate of #4062

**Closed** 2018-10-27 02:03 UTC
Labels: bug, major, p2, ui/ux
