### ISSUE TITLE
Attach to community feature in new room creating interface

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#5981] opened 2018-01-13 06:33 UTC
Will be good to see ability to attach room into community together with room creating process, so in new room creating window add selectlist with current user communities, and give optional ability to select community, to which room will be attached after creating.

**Comment by lampholder** [comment] 2018-01-16 11:48
This would be nice - we could use something not dissimilar to the "Display your community flair in rooms configured to show it" box from user settings to associate your new room with any group for which you are an admin.

**Comment by tulir** [comment] 2018-01-16 14:38
Isn't this a duplicate of #5819?

**Comment by t3chguy** [comment] 2018-01-16 14:40
Yup, closing as duplicate

**Closed by t3chguy** 2018-01-16 14:40 UTC
Labels: feature, p3, type:communities
