### ISSUE TITLE
DELETION via RIOT (room, community etc.)

### ISSUE THREAD

**Issue by frederic-loui** [vector-im/riot-web#8049] opened 2019-01-08 08:41 UTC
### Description
(First of all happy new year 2019)
I'm not sure if this is a bug, but I could not find a clear answer related to that as I have a particular setup. I use RIOT as a standalone client on MAC using the electron framework and logged in successfully on my private HS. I created TEST community and ROOM related to them. But now I would like to delete them properly (not hide them) But I could not find any "admin tool" so that I can do that properly. My google-fu led me to [synapse #2338](https://github.com/matrix-org/synapse/issues/2338) and also [riot-web #6978](https://github.com/vector-im/riot-web/issues/6978) but as of 2019.

### Steps to reproduce
(My particular setup)

- Installed Kubernetes 1.11.1
- Deployed synapse (without federation)
- Deployed mxisd and hook my LDAP server to it
- Deployed an Ingress that is a reverse proxy to my HS and mxisd identity server

All is working fine except that I'm facing the empty sticker issue. Community, room association is working fine, however now I would like to cleanup all my test room and community. Anyway to do this simply using the RIOT client ? Again, my client has bug like empty sticker page so I'm might have issues with deletion button not present etc. I found issues above but I'm not sure if these are still relevant. In the case this has been already debated, could you please point me out how I can delete Community and also Rooms even if this is a script on the server ? Some discussion state that this might be  a server issue, but I think that as an room admin or community admin, you should be able to do this on the client side. 

### Version information
- **Platform**: desktop
- **OS**: macOS
- **Version**: 0.17.8

**Comment by aaronraimist** [comment] 2019-01-21 01:33
This seems like a duplicate of #6978

**Closed** 2019-01-21 02:51 UTC
Labels: support
