### ISSUE TITLE
Unable to type umlauts in chat

### ISSUE THREAD

**Issue by kiliankoe** [vector-im/riot-web#8660] opened 2019-02-14 21:20 UTC
### Description

I'm on a US keyboard layout (running macOS) and I usually type German umlauts via option+U for the diaeresis ¨ followed by the respective letter. This unfortunately does not seem to be working in the redesigned Riot interface released today (congrats on that btw!) in Safari. It does work in current Firefox.

### Steps to reproduce

- Open any chat in Riot
- Attempt to type umlaut by typing diaeresis and letter separately

I can see the diaeresis appearing, but the cursor seems somewhat buggy. On typing the letter however the diaeresis disappears and I'm left with just the letter.

### Version information

- **Platform**: web (in-browser)

- **Browser**: Safari 12.1, 12.2 (technology preview)
- **OS**: macOS
- **URL**: riot.im/app

**Comment by turt2live** [comment] 2019-02-14 21:28
Duplicate of one of the issues on https://github.com/vector-im/riot-web/issues/7665

**Closed by turt2live** 2019-02-14 21:28 UTC

**Comment by kiliankoe** [comment] 2019-02-14 21:40
ah perfect, thanks 👍
