### ISSUE TITLE
_tr will only replace one of each tag

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#10564] opened 2019-08-15 10:43 UTC
```
_t(
    "<b>Thick</b> and <b>creamy</b>", {},
    { sub => <b>{sub}</b> },
)
```

Expected:
**Thick** and **creamy**

Actual:

**Thick** and creamy

The `_tr` function is complex but does have some unit tests. This would be an ideal candidate to get a regression test if/when it gets fixed.

**Comment by t3chguy** [comment] 2019-08-15 10:44
duplicate of https://github.com/vector-im/riot-web/issues/9086

**Closed by t3chguy** 2019-08-15 10:44 UTC
Labels: bug
