### ISSUE TITLE
Show presence in the left people section

### ISSUE THREAD

**Issue by tompinzler** [vector-im/riot-web#8988] opened 2019-02-28 12:50 UTC
I have presence enabled on my home server. If I want to see the status of another user I have to select that user and hover over him in the room member list in the column on the right.

It would be better to have something like a green/orange/grey dot on the users profile picture in the left column under PEOPLE.

Discord is doing this for example.

<img width="33" alt="screenshot 2019-02-28 at 13 46 07" src="https://user-images.githubusercontent.com/7597275/53567362-4fe74800-3b5f-11e9-8ad1-ae12ed392c81.png">

**Comment by turt2live** [comment] 2019-02-28 14:41
Duplicate of https://github.com/vector-im/riot-web/issues/4199

**Closed by turt2live** 2019-02-28 14:41 UTC
