### ISSUE TITLE
unsent messages get missed if you don't look at the room

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#7210] opened 2018-08-21 21:22 UTC
If a message fails to send, it's easy the alert doesn't show up anywhere until you go back to the room that you tried to send it from.  It would probably be nice to show a badge in the room list.

**Comment by turt2live** [comment] 2018-08-21 21:31
Duplicate of https://github.com/vector-im/riot-web/issues/1351

Related:
* https://github.com/vector-im/riot-web/issues/4824
* https://github.com/vector-im/riot-web/issues/1898

**Closed by turt2live** 2018-08-21 21:31 UTC
