### ISSUE TITLE
Server ACLs shouldn't cause unread notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10668] opened 2019-08-27 19:16 UTC
Particularly when 30-something rooms get the ACL at the same time

**Comment by aaronraimist** [comment] 2019-08-31 00:10
Can't remember where the issue is for this but I'll just include it here as well. Adding an alias to a room also causes a badge to appear.

**Comment by aaronraimist** [comment] 2020-02-22 02:59
Was fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3705

**Closed by aaronraimist** 2020-02-22 02:59 UTC
Labels: needs-product-decision, type:notifications
