### ISSUE TITLE
multiple account or user to link to different server

### ISSUE THREAD

**Issue by boistordu** [vector-im/riot-web#12676] opened 2020-03-10 15:03 UTC
Hi,

Sorry the template doesn't work at all with  the quesiton I want to ask and I don't where else to ask it.
Is there yet a possibility to be conencted to different matrix server? like is it possible with riot to be connected to the riot community server and the privacytools.io server for example?
Or is there a way to launch several instances with maybe config file then to do that? Anything at all would be appreciated, Because I don't see anywhere in the interface to actually add an identity or add a server which should ask then my identity for this server....
Thanks in advance for all your help

**Comment by turt2live** [comment] 2020-03-10 15:24
Duplicate of https://github.com/vector-im/riot-web/issues/2320

For questions, please use #riot-web:matrix.org as our issue tracker is specifically not meant to handle these sorts of queries.

**Closed by turt2live** 2020-03-10 15:24 UTC
Labels: bug, ui/ux
