### ISSUE TITLE
Pin to taskbar opens a duplicate on KDE Plasma

### ISSUE THREAD

**Issue by PopeRigby** [vector-im/riot-web#14638] opened 2020-07-19 18:23 UTC
### Description

Ever since the name change from Riot to Element, pinning Element to the taskbar, and then launching Element from the taskbar opens a duplicate of Element. Pinning the duplicate, closing it, and then clicking that icon opens the Electron launcher.

Here's a video of it happening: 
https://watch.haddock.cc/videos/watch/64c4288b-d540-4a16-ae2c-f09c804d899c

### Steps to reproduce

- Pin Element to the Icons-Only Task Manager
- Click on Element's icon

The expected result would be Element opening up from the pinned icon.

Logs being sent: No

### Version information

- **Platform**: Desktop 
- **OS**: Arch Linux
- **DE**: KDE Plasma 
- **Version**: 1.7.1

**Comment by t3chguy** [comment] 2020-07-20 09:42
Duplicate of https://github.com/vector-im/riot-web/issues/14619

**Closed by t3chguy** 2020-07-20 09:42 UTC
Labels: bug, platform specific, regression, type:electron
