### ISSUE TITLE
Clicking on a read receipt doesn't open their profile

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/riot-web#7609] opened 2018-10-26 14:58 UTC
I'm sure that when you used to click a read receipt it opened their profile in the right panel?

**Comment by t3chguy** [comment] 2018-10-26 15:00
Duplicate of https://github.com/vector-im/riot-web/issues/5784
(see that issue for reasons why this is problematic)
I do not believe this to ever have been the behaviour :(

**Closed by t3chguy** 2018-10-26 15:00 UTC
