### ISSUE TITLE
Riot app homepage with the list of channels can't be scrolled on Firefox on Mac (reproduced on both Nightly and Stable)

### ISSUE THREAD

**Issue by Porkepix** [vector-im/riot-web#4803] opened 2017-08-16 19:26 UTC
### Description

Riot app homepage with the list of channels can't be scrolled on Firefox on Mac (reproduced on both Nightly and Stable).

### Steps to reproduce

- Go to https://riot.im/develop/#/home or https://riot.im/app/#/home with Firefox on a mac
- Try to scroll
- It doesn't

Describe how what happens differs from what you expected.

Well… it should scroll

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox, stable and nightly.
- **OS**: macOS
- **URL**: riot.im/develop / riot.im/app

Can't be reproduced on Chrome on mac nor on Firefox on Linux or Windows.

Screen resolution if that can matters: 1440x900

**Comment by Porkepix** [comment] 2017-08-16 19:29
![Screenshot of the home](https://user-images.githubusercontent.com/709500/29381561-e95b37c6-82c9-11e7-8659-1c7ac56cf378.png)

This is the visible part. This can't be scrolled down.
There isn't even scrollbars that appear.

**Comment by sparky-raccoon** [comment] 2017-12-08 18:46
Hi guys,
I have the same issue! Are there any workarounds about it, in the develop branch or as a next feature? 
Thank you!

**Comment by pafcu** [comment] 2017-12-14 08:13
Duplicate of https://github.com/vector-im/riot-web/issues/4552 ?

**Comment by MTRNord** [comment] 2017-12-14 08:44
This issue feels more like the problem that the "someone is writing" overlay does in Chats. It is on all ui's these x px that are missing until I scroll up and back down

**Comment by pafcu** [comment] 2017-12-14 08:47
@MTRNord I'm not so sure. It sounds to me that there is an actual problem with scrolling, not just that some bit is missing. Perhaps there are actually multiple issues at work here?

**Comment by MTRNord** [comment] 2017-12-14 09:30
@pafcu yes I feel like All the Firefox related "bottom missing" or "scroll jumps" come down to either the same or a similar case. But I have no idea what exactly might cause it

**Comment by turt2live** [comment] 2019-02-15 02:12
We don't have a homepage anymore (and if we do, it doesn't have rooms)

**Closed by turt2live** 2019-02-15 02:12 UTC
Labels: bug, major, p1
