### ISSUE TITLE
Riot web crashed on FF tab switch

### ISSUE THREAD

**Issue by tyleradams** [vector-im/riot-web#12174] opened 2020-01-31 13:49 UTC
### Steps to reproduce

- Create 3 tabs
- Login on one tab.
- switch to another tab
- switch back, crashed

Describe how what happens differs from what you expected.
Should not crash
Log: sent    

### Version information

- web (in-browser) Firefox 72.0.2 for linux mint 

- **URL**: https://riot.im/app/#/room/!JeUyRIGdMGmngkfiJt:matrix.org

**Comment by turt2live** [comment] 2020-01-31 14:05
Stacktrace from logs:
```
2020-01-31T13:46:43.450Z E H.a.get(...) is null
render@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:3664589
$a@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2218118
Ya@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2217913
xs@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2253094
gc@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2237439
hc@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2237362
ic@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2234710
$o/<@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2193152
t.unstable_runWithPriority@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2267746
zo@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2192861
$o@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2193099
Yo@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2193032
ec@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2231499
enqueueSetState@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2197813
y.prototype.setState@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2126200
e/<@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:3647553
c@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:611746
s/i._invoke</<@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:611500
_/</e[t]@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:612103
n@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:21165
s@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:21377

2020-01-31T13:46:43.475Z E H.a.get(...) is null
render@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:3664589
$a@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2218118
Ya@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2217913
xs@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2253094
gc@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2237439
hc@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2237362
ic@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2234710
$o/<@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2193152
t.unstable_runWithPriority@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2267746
zo@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2192861
$o@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2193099
Yo@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2193032
ec@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2231499
enqueueSetState@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2197813
y.prototype.setState@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:2126200
e/<@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:3647553
c@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:611746
s/i._invoke</<@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:611500
_/</e[t]@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:612103
n@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:21165
s@https://riot.im/app/bundles/d441f426d823eb4f5dc4/bundle.js:2:21377

2020-01-31T13:46:43.475Z E The above error occured while React was rendering the following components: 
    in RoomView
    in div
    in t
    in div
    in LoggedInView
    in t
    in MatrixChat
```

**Comment by jryans** [comment] 2020-02-12 12:34
`H.a.get(...)` appears to be accessing the client inside RoomView, but the line / column info is all jumbled, so it's hard to tell where. 😓 

It looks like a race with multiple login attempts happening quickly in succession.

@tyleradams, are you able to reproduce this every time, or only in specific conditions?

**Comment by jryans** [comment] 2020-04-24 13:26
No reply, closing for now. Please reopen if more info becomes available.

**Closed by jryans** 2020-04-24 13:26 UTC
Labels: question
