### ISSUE TITLE
riot.im website l10n

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#9237] opened 2019-03-21 16:01 UTC
Please make https://riot.im website localized:

1. it should use Accept-Language HTTP header. (Like debian.org does, for example.)
2. and take translation from translate.riom.im

**Comment by turt2live** [comment] 2019-03-21 18:28
Duplicate of https://github.com/vector-im/riot-web/issues/4458

**Closed by turt2live** 2019-03-21 18:28 UTC
Labels: suggestion

**Comment by 532910** [comment] 2019-03-21 23:54
sorry

**Comment by turt2live** [comment] 2019-03-21 23:57
no worries, we'd rather have duplicates than silence. I just have to sound a bit cold in my message to make github do the right thing is all :)
