### ISSUE TITLE
Multiple Mods/Admins of community

### ISSUE THREAD

**Issue by DonaldTsang** [vector-im/riot-web#8914] opened 2019-02-24 08:05 UTC
It would be more convenient for people to make community (e.g. `+room:matrix.org`) management collaborative

1. Multiple Mods/Admin in the same community to allow better invites
2. Allows for sub-categories in communities by topic (see Discord)

**Comment by turt2live** [comment] 2019-02-24 08:15
Duplicate of https://github.com/vector-im/riot-web/issues/5259 and https://github.com/vector-im/riot-web/issues/5240

**Closed by turt2live** 2019-02-24 08:15 UTC
Labels: redesign
