### ISSUE TITLE
Exit filter mode when a filter is typed and a room selected pressing Enter

### ISSUE THREAD

**Issue by jcromero** [vector-im/riot-web#11630] opened 2019-12-08 13:36 UTC
**Is your suggestion related to a problem? Please describe.**
It's very inconvenient to use the keyboard to select rooms. I can do `Ctrl+K`, filter the name of the room hitting some keys, and press `Enter` to select the first filtered one. But the filter remains active and I have to `Ctrl+K` again and press `Backspace` to show all the rooms.

**Describe the solution you'd like**
When pressing `Enter` to select the first match in filter mode, the mode should be exited.

**Describe alternatives you've considered**
No one.

**Additional context**
If no filter is entered in the inputtext field and I press `Enter` the behaviour is the one suggested, so there is an inconsistency here.

**Comment by t3chguy** [comment] 2020-04-14 16:15
Duplicate of https://github.com/vector-im/riot-web/issues/7625

**Closed by t3chguy** 2020-04-14 16:15 UTC
Labels: suggestion
