### ISSUE TITLE
Password Reset flow via vector.im has a broken link to a Riot logo

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#9073] opened 2019-03-07 10:42 UTC
![image](https://user-images.githubusercontent.com/1922197/53951141-b1f6fe80-40c5-11e9-8820-8b6ff0326e80.png)

We moved https://riot.im/app/themes/riot/img/logos/riot-logo.svg

**Comment by jryans** [comment] 2019-03-07 10:48
Duplicate of #9006. Waiting on updated Sydent to be deployed.

**Closed by jryans** 2019-03-07 10:48 UTC
Labels: type:password-reset
