### ISSUE TITLE
Reactions are not cleared when a message becomes redacted

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#9947] opened 2019-06-04 11:19 UTC
![image](https://user-images.githubusercontent.com/274386/58875294-aada8f00-86ba-11e9-9c3e-d6d1b6231462.png)

**Comment by jryans** [comment] 2019-06-04 11:27
I believe this is a duplicate of https://github.com/vector-im/riot-web/issues/9843.

**Closed by jryans** 2019-06-04 11:27 UTC
Labels: bug, feature:reactions
