### ISSUE TITLE
Not all search results are green highlighted

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#14019] opened 2020-06-13 21:42 UTC
Searching `issues` in This room, some results are highlighted: ![image](https://user-images.githubusercontent.com/14617699/84579605-bd140080-add7-11ea-82b5-e82b7ec7b07e.png), others are not: ![image](https://user-images.githubusercontent.com/14617699/84579614-cef5a380-add7-11ea-8689-2b2b70a34d4f.png)

**Comment by t3chguy** [comment] 2020-06-13 21:43
Duplicate of https://github.com/vector-im/riot-web/issues/5007

**Closed by t3chguy** 2020-06-13 21:43 UTC
Labels: bug
