### ISSUE TITLE
hide scalar button if no scalar defined in config.json

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3467] opened 2017-03-18 22:31 UTC

**Comment by lampholder** [comment] 2017-03-20 17:19
This is the 'manage integrations' button?

Is config.json defined as part of the homeserver config, or elsewhere? When is this likely to be encountered?

**Comment by ara4n** [comment] 2017-03-20 17:30
config.json is riot-web's config file. if people deploy their own riot and don't want their users to try to configure scalar integrations (e.g. because scalar isn't FOSS), we should let them hide the 'manage integs' button.

**Comment by t3chguy** [comment] 2017-04-21 19:04
duplicate of #2606

**Closed** 2017-04-22 00:39 UTC
Labels: cosmetic, feature, p3, ui/ux
