### ISSUE TITLE
multiple p2p calls cause confusion for both parties

### ISSUE THREAD

**Issue by grinapo** [vector-im/riot-web#13362] opened 2020-04-24 10:00 UTC
### Description

When there are 2 people trying to start a video (or a voice) call and one have less Matrix experience, slower internet, laggy machine or else, it is possible that:

- party 1 starts call
- party 2 starts call
- p1 realise p2 have started a call, ends call
- p1 tries to answer call
- p2 waits
- p1 don't get reply, ends call, starts another
- p2 times out. 
- p1 get bored and start the discussion in the chat :-)
- p2 gets ringing from the __first__ call (hung up long ago), not possible to answer
- p2 times out then gets ringing from the __second__ call (which was also hung up)

It seems that calls nicely get queued, regardless of hangups? Also when p1 starts a call p2 can start a call as well, I am not sure it helps to prevent confusion, having two parallel p2p ongoing calls in the same room between the same parties, and I'm not sure there's a real use case for that. :-)

Can be related to #1964 (proudly going since 2016 :grin: ).

### Version information
riot-web version: 1.6.0-rc.3

**Comment by turt2live** [comment] 2020-04-24 15:41
Duplicate of https://github.com/vector-im/riot-web/issues/1325

**Closed by turt2live** 2020-04-24 15:41 UTC
Labels: bug, ui/ux

**Comment by grinapo** [comment] 2020-04-24 22:44
Uh. What **IS** #1325? It contains nothing. Since 2016.

**Comment by turt2live** [comment] 2020-04-24 22:46
It's talking about glare, the entire premise of your issue.

**Comment by grinapo** [comment] 2020-04-25 14:12
Okay, I say it more verbosely: the problem is (at least for me) that when I have an issue I first try to search for already reported issues to prevent duplicates. When an issue contains zero keywords a layperson could search for then it's bound to have duplicates. It seems to benefit the developers to have searchable issues. 

"Glare" is not in the top one million possible keywords I would have searched for. (Also I can't really imagine anyone searching for "vid" instead of "video", apart from that searching for three letter words is usually futile.)

Also I am not convinced that issues untouched for 4 years would have any benefits or chance of attention, but I would very much like to be contradicted at this one.
