### ISSUE TITLE
Please allow changing of size of the room icons

### ISSUE THREAD

**Issue by jeroenh** [vector-im/riot-web#14721] opened 2020-07-23 09:41 UTC
### Description

The previous (Riot) design had smaller icons next to room names. The newer version has larger icons, which take up more space in the list, leading to having fewer (~20%) room names available.

Also, the text size does not seem changed, which makes for a very empty-feeling design.

### Steps to reproduce

The old version had a room name list with smaller icons, with the same size window, this allowed for roughly 12 rooms to be listed.

![riot-old-design](https://user-images.githubusercontent.com/31300/88272014-5936fe80-ccd8-11ea-914b-c64eb1ea8135.png)

The new version has larger icons, so with the same size window, this allows for only 10 rooms to be listed.

![element-new-design](https://user-images.githubusercontent.com/31300/88272021-5c31ef00-ccd8-11ea-9cd1-a76dcd2c44eb.png)

This is also the case for the room where chat messages are shown, but there you can use the "modern" layout (hidden under advanced settings) to get back all the lost space.

### Version information

- Mac version 1.7.1

**Comment by t3chguy** [comment] 2020-07-23 09:44
Duplicate of https://github.com/vector-im/riot-web/issues/14099

**Closed by t3chguy** 2020-07-23 09:44 UTC
Labels: bug, ui/ux
