### ISSUE TITLE
After reloading, E2E rooms can be stale/blank with no spinner for ages

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7504] opened 2018-10-16 11:23 UTC
I just refreshed develop post the 0.17 release, and got a stale view of my E2E rooms (showing the last time the sync accumulator was persisted, i guess).  However, it then takes *minutes* for the missing messages to appear, and during that time, there is no spinne visible.  Sometimes the timeline shown can be entirely blank

**Comment by turt2live** [comment] 2018-10-16 14:44
Duplicate of https://github.com/vector-im/riot-web/issues/7116 (which is claimed as cannot reproduce?)

**Closed by turt2live** 2018-10-16 14:44 UTC
