### ISSUE TITLE
Right clicking a room tile the first time highlights it, right clicking again doesn't

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#6935] opened 2018-06-25 15:45 UTC
Related: https://github.com/vector-im/riot-web/issues/6910

First click (note Riot is highlighted):
![image](https://user-images.githubusercontent.com/1190097/41860699-7d9ba776-785c-11e8-8628-64de7ff1060d.png)

Second click (on riot-dev):
![image](https://user-images.githubusercontent.com/1190097/41860710-82da6db2-785c-11e8-9930-e3c7795280a2.png)

**Comment by yannicka** [comment] 2020-07-18 11:20
Do you still have the problem? I can't reproduce it.

**Comment by t3chguy** [comment] 2020-07-18 11:27
Good spot - fixed by new room list

**Closed by t3chguy** 2020-07-18 11:27 UTC
Labels: bug, cosmetic, minor, p2
