### ISSUE TITLE
Feature request: Change of Status away / DnD / activ

### ISSUE THREAD

**Issue by ppabst** [vector-im/riot-web#11611] opened 2019-12-05 15:29 UTC
Hello,
we use riot.im for the internal communilation of our employees. 
Here it is often necessary that an employee can change his status to work undisturbed (DnD) or maybe just in the lunch break is (away).
A manual setting of the status would be very helpful here.

**Comment by turt2live** [comment] 2019-12-05 18:15
Duplicate of https://github.com/vector-im/riot-web/issues/478

**Closed by turt2live** 2019-12-05 18:15 UTC
Labels: suggestion
