### ISSUE TITLE
Cannot dismiss invitations by users with bad federation configuration

### ISSUE THREAD

**Issue by flackr** [vector-im/riot-web#14093] opened 2020-06-18 15:33 UTC
### Description

When a user invites you to a chat but their server is not correctly configured for federation or is otherwise not responsive you see the following message:

> Failed to join room
>
> Failed to make_join via any server

However, the invitation is still there. Even if you reject the invitation it still remains in the invitation list.

### Steps to reproduce

- Send an invitation to chat from a user on homeserver A to homeserver B
- Take down homeserver A.
- Try to remove the invitation for the user on homeserver B.

While it makes sense that the accept fails, it's surprising that it seems like there's no way to remove the invitation.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome 83.0.4103.97 (Official Build) (64-bit)
- **OS**: ChromeOS
- **URL**: private server hosting riot-v1.6.5 from https://github.com/vector-im/riot-web/releases

**Comment by t3chguy** [comment] 2020-06-18 15:36
Duplicate of https://github.com/vector-im/riot-web/issues/3743

**Comment by t3chguy** [comment] 2020-06-18 15:37
See workaround listed in that issue, as this is a Synapse bug.

**Closed by t3chguy** 2020-06-18 15:36 UTC
Labels: bug
