### ISSUE TITLE
Invite emails use old branding

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#9139] opened 2019-03-12 16:52 UTC

**Comment by turt2live** [comment] 2019-03-12 16:53
This is technically a duplicate of https://github.com/vector-im/riot-web/issues/9009 and https://github.com/vector-im/riot-web/issues/9006 in that they fix the issue here. The stuff hasn't been deployed though - I'll go nag people again.

**Closed by turt2live** 2019-03-12 16:53 UTC
