### ISSUE TITLE
Prompt for device name early during login

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#9515] opened 2019-04-17 16:15 UTC
**(Originally written by @BloodyIron in https://github.com/vector-im/riot-web/issues/9495)**

I have so many devices that have the same name, and I can't tell if this was because of riot reinstalls, or whatever. But naming devices retroactively I think further complicates the situation. Prompting the user to set the name early on (in some way) I think will make this whole process much more self-evident as to which is which. And naturally, the user should still have the ability to skip or accept the default name, or whatever.

**Comment by turt2live** [comment] 2019-04-17 16:17
Duplicate of https://github.com/vector-im/riot-web/issues/2295

**Closed by turt2live** 2019-04-17 16:17 UTC
Labels: suggestion, type:e2e
