### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#8130] opened 2019-01-15 16:48 UTC
@lampholder hit this while testing the resizer, it looked liked an infinite loop in OpenRoomsStore on login, where it would redispatch on_logged_out infinitely. Not sure yet how easy it is to reproduce.

**Comment by turt2live** [comment] 2019-01-15 16:53
Duplicate of https://github.com/vector-im/riot-web/issues/8100

**Closed by turt2live** 2019-01-15 16:53 UTC
Labels: bug, critical, redesign
