### ISSUE TITLE
Automatically populate URL field with custom server

### ISSUE THREAD

**Issue by jzbz** [vector-im/riot-web#5582] opened 2017-11-13 07:26 UTC
### Description

It would be great to be able to populate the "Home server URL" setting in Riot by specifying a custom URL as a string in the registration link e.g., `https://riot.im/app/#/register&homeserver=https://<customURL>`

Currently there does not seem to be a way to avoid having the user enter this information manually unless you run your own instance of Riot as well.

**Comment by t3chguy** [comment] 2017-11-13 07:58
Appears there is && duplicate of: https://github.com/vector-im/riot-web/issues/5112

**Closed by t3chguy** 2017-11-13 07:58 UTC

**Comment by jzbz** [comment] 2017-11-13 23:06
That solution proposed in #5112 works for the login page but not for the registration page... Is there any chance of adding that ability?

**Comment by t3chguy** [comment] 2017-11-13 23:08
That doesn't seem to be the case looking at the PR that #5112 links to: https://github.com/matrix-org/matrix-react-sdk/pull/716#issuecomment-281137115

**Comment by jzbz** [comment] 2017-11-13 23:24
I must have screwed something up, seems to be working now, thanks.
