### ISSUE TITLE
EXIF rotation metadata of photos is not well handled

### ISSUE THREAD

**Issue by Ezwen** [vector-im/riot-web#10903] opened 2019-09-18 06:02 UTC
### Description

Consider a picture with EXIF rotation metadata (eg. a photo taken with a phone that was not turned 90° on the side), such as:

![IMG_20190915_082630](https://user-images.githubusercontent.com/1388961/65116530-3289a680-d9e9-11e9-9327-05e61c983ae8.jpg)

When opened in an application that takes into account EXIF rotation metadata, we see this:

![Capture d’écran du 2019-09-18 07-53-18](https://user-images.githubusercontent.com/1388961/65116718-6cf34380-d9e9-11e9-80b6-2ffe149de3d2.png)

**However** when we upload this picture in Riot, the thumbnail shows this:

![Capture d’écran du 2019-09-18 07-54-38](https://user-images.githubusercontent.com/1388961/65116842-93b17a00-d9e9-11e9-8a07-fa6220147f47.png)

And if we click on the picture to show it fullscreen, we see this:
![Capture d’écran du 2019-09-18 07-55-22](https://user-images.githubusercontent.com/1388961/65117056-d8d5ac00-d9e9-11e9-9c38-edd7b82a6080.png)

### Steps to reproduce

- Take a picture with your phone and without rotating your phone on the side.
- Upload the picture in a matrix room using Riot-web : the thumbnail appears, and while the photo was rotated by taking into account the EXIF metadata, it appears "squashed".
- Then click on the photo: the photo appears without rotation, which not only differs from the thumbnail, but sadly does not take into account EXIF rotation metadata. 

### Version information

- **Platform**: desktop
- **OS**: Fedora 30
- **Version**: 1.3.5

**Comment by turt2live** [comment] 2019-09-18 06:43
@Ezwen which server is this on?

**Comment by Ezwen** [comment] 2019-09-18 06:49
@turt2live my own homeserver running synapse 1.3.1

**Comment by turt2live** [comment] 2019-09-18 06:55
Looks like this was supposed to be fixed by https://github.com/matrix-org/synapse/pull/5039 but it looks like the thumbnail handling code is wrong. Riot should probably auto-rotate the image when possible, but the thumbnail looking weird is a Synapse issue.

**Comment by Ezwen** [comment] 2019-09-18 07:01
Oh I see! Should I open a synapse bug then?

**Comment by turt2live** [comment] 2019-09-18 07:23
for the thumbnail side, yes please. This issue should stay open to track Riot's problems.

**Comment by Flexmaen** [comment] 2020-04-13 10:59
I wonder that your image will be rotated at all.
When trying to upload an image that has the rotation info in the EXIF data, I get this result instead:
https://github.com/vector-im/riot-web/issues/1999#issuecomment-461393846

**Comment by turt2live** [comment] 2020-04-14 19:31
hmm, indeed. Closing this as a duplicate of https://github.com/vector-im/riot-web/issues/1999 for now.

**Closed by turt2live** 2020-04-14 19:31 UTC
Labels: bug
