### ISSUE TITLE
reply/reactions buttons missing for one message

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#10000] opened 2019-06-10 10:43 UTC
I have no real idea why this one event is missing the knobs

**Comment by richvdh** [comment] 2019-06-10 10:43
![image](https://user-images.githubusercontent.com/1389908/59190588-00101800-8b75-11e9-9e59-42a992e140fa.png)

**Comment by richvdh** [comment] 2019-06-10 10:44
(the message in question is a reply to me, obvs)

**Comment by jryans** [comment] 2019-06-10 10:46
Sounds similar to #9991 with messages that we weren't initially able to decrypt, but unsure if it's the same root cause.

**Comment by richvdh** [comment] 2019-06-10 10:54
sounds plausible

**Comment by jryans** [comment] 2019-06-10 11:38
I found a reproduction path for this and based on that it seems like a duplicate of #9991.

**Closed by jryans** 2019-06-10 11:38 UTC
Labels: bug, defect, feature:aggregations, feature:message-editing, feature:reactions, p2, type:timeline
