### ISSUE TITLE
 Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)'

### ISSUE THREAD

**Issue by shirishag75** [vector-im/riot-web#7506] opened 2018-10-16 14:14 UTC
I am running riot-web 0.17.0 

```
~$ cat /etc/apt/sources.list | grep riot
        deb https://riot.im/packages/debian/ stretch main
```

When running riot-web under Debian I get the following on the console - 

```
$ riot-web
(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead.
```

**Comment by t3chguy** [comment] 2018-10-16 14:36
Duplicate of https://github.com/vector-im/riot-web/issues/7481

**Closed by t3chguy** 2018-10-16 14:36 UTC
