### ISSUE TITLE
Jumping on the referred message

### ISSUE THREAD

**Issue by alittlebitofit** [vector-im/riot-web#9656] opened 2019-05-09 07:08 UTC
Suppose I am replying to a message that was sent/received a couple messages ago.
Currently, there is an option to reply to it, so the users would know what message I am replying to.
But sometimes it gets difficult to understand the context of the message because of x reasons.
So what I would suggest is: When one clicks/touches on the "replied" message, Riot should take us to that particular message.

If you have used Whatsapp, you might know that there's an option that does exactly that.

Hope I am thorough with the explanation. :)

**Comment by turt2live** [comment] 2019-05-09 14:05
Currently clicking the "In reply to" part should work, as does clicking the timestamp of the message.

**Comment by alittlebitofit** [comment] 2019-05-09 15:25
@turt2live Thanks. Also, can't jump to the referred message in android app.

**Comment by t3chguy** [comment] 2019-05-09 15:40
Feel free to open an issue in github.com/vector-im/riot-android if one does not yet exist

**Comment by alittlebitofit** [comment] 2019-05-09 15:42
@t3chguy Thanks. :)

**Comment by aaronraimist** [comment] 2020-05-14 03:17
Duplicate of #7151

**Closed by aaronraimist** 2020-05-14 03:17 UTC
Labels: suggestion

**Comment by alittlebitofit** [comment] 2020-05-14 05:15
s
