### ISSUE TITLE
Edited unsent message does not update visually

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/riot-web#11270] opened 2019-10-31 00:50 UTC
### Description

Editing a message that couldn't get sent (e.g. during network disconnect) does not show the edit was saved.

Under the hood, it works as expected, just missing UX.

### Steps to reproduce

- internet disconnected while composing a message
- sent anyway
- message is in "outbox".
- thought of something to edit
- edited as usual
- confirmed (sent)
- "outbox" red message does not update to show the edit, but initial content!
- type edit manually in another message as to not forget it
- internet connection restored, resend all messages
- turns out the edit was actually recorded and did get "edited" after resend. Thus second message is duplicate.

Logs being sent: yes/no

### Version information

- **Platform**: desktop
- **OS**: Windows 7
- **Version**: 1.5.0

**Comment by turt2live** [comment] 2019-10-31 01:50
Duplicate of #11035

**Closed by turt2live** 2019-10-31 01:50 UTC
Labels: bug, ui/ux
