### ISSUE TITLE
Ability to search for messages from a user

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12852] opened 2020-03-24 19:31 UTC
I thought we had a bug for this, but I can't find this.

The API supports it already, and it even seems to work - e.g.:

`curl 'https://matrix.org/_matrix/client/r0/search' -H "Authorization: Bearer $at" --data '{"search_categories":{"room_events":{"search_term":"search","filter":{"rooms":["!pcfWjiETvnVuspPLPl:mozilla.org"], "state": {"senders":["@jrmuizel:mozilla.org"]}},"order_by":"recent","event_context":{"before_limit":1,"after_limit":1,"include_profile":true}}}}'`

returns all messages sent by `@jrmuizel:mozilla.org` in #synchronicity:mozilla.org containing term 'search'.

**Comment by t3chguy** [comment] 2020-03-24 19:38
Duplicate of https://github.com/vector-im/riot-web/issues/4752 (which has a Community PR)

**Closed by t3chguy** 2020-03-24 19:38 UTC
Labels: suggestion
