### ISSUE TITLE
invitee list for groups doesn't update in realtime?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5651] opened 2017-11-19 10:22 UTC
if i'm viewing a group page, it feels like i have to refresh to see new invitees or invites being accepted...

**Comment by lukebarnard1** [comment] 2017-11-20 13:26
We do fetch a group's [invited] members after any invites are sent. 

It's expected that you'd have to refresh (or remount) in order to see new members (i.e. those who have accepted invites), which is similar to https://github.com/vector-im/riot-web/issues/5227

**Comment by lampholder** [comment] 2017-11-23 14:00
Considering this a bug from a usability perspective because (in the current impl of the UX at least) very much _not_ expected by users.

**Comment by turt2live** [comment] 2017-12-22 18:43
Duplicate of https://github.com/vector-im/riot-web/issues/5228

**Closed** 2020-01-15 20:49 UTC
Labels: bug, major, p2, ui/ux
