### ISSUE TITLE
matrix.org is seeing a constant 30Hz of POST /_matrix/client/unstable/keys/upload

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3810] opened 2017-05-04 20:11 UTC
30Hz of key upload seems bizarrely high - something seems to be happening to cause clients to constantly be uploading new one-time(?) keys.  Looking at the logs for /upload for a given device ID, it seems all web/ios/android are all uploading new keys each and every minute.  Is this really what's meant to be happening?

Right now we have 1983 unique IPs (4500 conns) connected to matrix.org; so 1983/60 = 33Hz which tallies up.

**Comment by richvdh** [comment] 2017-05-04 22:19
it's not uploading keys, just checking if we need to upload new OTKs. I'd assume those 1983 clients are also calling /sync substantially more often than every 60s.

**Comment by ara4n** [comment] 2017-05-04 22:38
they're calling at 240Hz, so 60Hz per synchrotron.  But none of that is hitting the poor overloaded master synapse...

**Comment by lampholder** [comment] 2017-05-05 09:45
With the limited context I've picked up from reading the thread I'm setting this to P1 minor bug - it sounds like there's a chance this is not a bug at all, but it also sounds like something that should be on people's radars until we've confirmed that it's not a bug.

**Comment by richvdh** [comment] 2017-05-05 09:55
I think we've confirmed it's not a bug, and is more-or-less expected right now. Whether it's optimal, or we should be doing something about it, is a separate question, but I don't think it's a P1. TBH i'd vote for closing it for now; if we decide that matrix.org is spending too much CPU servicing them we can reopen it

**Comment by ara4n** [comment] 2017-05-06 00:00
Yeah. I'm concerned that given how overloaded the main matrix.org synapse is, doing *anything* at 30Hz that involves multiple DB hits is needlessly chewing its CPU and should be handed to a worker or something.  I agree it's probably not P1 though, and really should be handed to @erikjohnston

**Comment by erikjohnston** [comment] 2017-05-08 09:13
I think the correct solution here is to change the API so that it doesn't need to poll; shoving the information down /sync strikes me as a sensible thing to do. If we are going to change the API we should probably do so sooner rather than later.

**Comment by erikjohnston** [comment] 2017-06-01 14:53
https://github.com/matrix-org/synapse/pull/2237

**Comment by richvdh** [comment] 2017-07-19 15:35
@krombel has done the client side of this in https://github.com/matrix-org/matrix-js-sdk/pull/493.

**Closed by richvdh** 2017-07-19 15:35 UTC
Labels: bug, minor, p2, performance
