### ISSUE TITLE
there is no way to re-check the fingerprints of a user's device after having verified it

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8403] opened 2019-02-04 21:26 UTC

**Comment by lampholder** [comment] 2019-02-18 14:19
I'm certain this is a dup but can't for the life of me find the original.

Let's make sure we bear this in mind as we look at E2E ux over the next few weeks.

**Comment by aaronraimist** [comment] 2020-01-15 20:57
Duplicate of #2735

**Closed by aaronraimist** 2020-01-15 20:57 UTC
Labels: bug, minor, p1, type:e2e, ui/ux
