### ISSUE TITLE
Clickable usernames span width of conversation area

### ISSUE THREAD

**Issue by effyn** [vector-im/riot-web#8737] opened 2019-02-16 22:28 UTC
I haven't bothered to inspect how this is set up, but I'm guessing an entire `<span>` or `<div>` element has the onClick event registered instead of just the text.

The problem this creates is having to "thread the needle" when copying logs to share or save. You really have to be precise to not accidentally start mentioning one of your room participants when you're highlighting text.

The solution to this I think is changing what the onClick event is bound to (the text rather than the container)

As this is my first issue, I'd like to say that I love the 1.0 release changes and everyone contributing is doing a great job :)

**Comment by turt2live** [comment] 2019-02-16 23:42
Duplicate of https://github.com/vector-im/riot-web/issues/5400

**Closed by turt2live** 2019-02-16 23:42 UTC
