### ISSUE TITLE
IRC room search / join has poor user experience

### ISSUE THREAD

**Issue by tgr** [vector-im/riot-web#9621] opened 2019-05-03 04:41 UTC
### Description

Using the room joining UI works poorly for bridged IRC networks:
* The search/list interface searches Matrix rooms, no IRC rooms, but the user gets no indication of this, giving the impression that the room they are looking for does not exist.
* I must enter a `#` mark before the channel name to be able to join (on Freenode at least). Again there is no indication for this. Probably confusing for IRC beginners, especially when paired with the previous issue.
* If you enter the channel name correctly, with a `#`, you get a tiny light-grey "join" button. It's hard to notice, the list still says "no rooms to show", it's unclear that this is actually a valid channel name.

### Steps to reproduce
- Click on add room icon ( (+) next to the room list on the left)
- Select Freenode in the dropdown
- Type `mediawiki` - error message about no rooms to show, no ability to join, no indication of what to do ![riot-irc-join-1](https://user-images.githubusercontent.com/145412/57119946-b7b63c80-6d22-11e9-83b3-3af8160e1309.png)
- Type `#mediawiki` - error message about no rooms to show, tiny hidden join button, no indication of what to do ![riot-irc-join-2](https://user-images.githubusercontent.com/145412/57119949-bb49c380-6d22-11e9-853a-0f1abf759f2f.png)

Ideally, there would be proper channel search (e.g. through [alis](https://freenode.net/kb/answer/findingchannels)), but if there isn't, at least the search area should be disabled (with text to clarify it's not working, as opposed to working but not finding anything). And if Riot does not accept channel names without the `#` (which is reasonable, requiring the exact channel name makes things less confusing in the long run), it should just automatically prefix it to the text field, or at least show a warning about it not being there.

### Version information
- **Platform**: web
- **Browser**: Chrome 73
- **OS**: Ubuntu 18.04
- **URL**: riot.im/app/

**Comment by turt2live** [comment] 2019-05-03 04:48
The "No rooms" part is a duplicate of https://github.com/vector-im/riot-web/issues/8646 and the overall bad UX is covered by https://github.com/vector-im/riot-web/issues/5265 and https://github.com/vector-im/riot-web/issues/4171, as well as a bunch of other issues.

**Closed by turt2live** 2019-05-03 04:48 UTC

**Comment by tgr** [comment] 2019-05-03 05:27
> The "No rooms" part is a duplicate of #8646

Thanks! Not sure how I missed that.

> and the overall bad UX is covered by #5265 and #4171, as well as a bunch of other issues.

Those seem to be about different issues. My point was that the join button is hard to notice + the UX would be better if got rid of the IRC baggage of having to manually type `#` before every channel name. Granted, if search did work, those issues would be a lot less relevant.

**Comment by turt2live** [comment] 2019-05-03 05:28
Those last two issues are more reference for "the join button sucks" and less so their titles. Theory is that when those issues go under review, this one pops up and gets resolved by proxy.
