### ISSUE TITLE
Auto url recognition doesn't recognize this particular URL with lots of underscores and dashes

### ISSUE THREAD

**Issue by csoghoian** [vector-im/riot-web#13995] opened 2020-06-11 15:22 UTC
### Description

Tried pasting in a URL with a particular format into a chat, and the feature in Riot that automatically recognizes URLs and turns them into a hyperlink only recognizes the first half of the URL, so that the page it links to isn't valid.

I've not been able to narrow down which particular character in the URL is causing this to break.

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

This URL causes the problem:
https://www.foo.org/foo_-_foo_.pdf

(There are two problems: When I type this URL into a chat window, the linked is truncated, and the the final underscore in the URL before the .pdf is missing from the text that is displayed).

However, these two slight variations work fine:
https://www.foo.org/foo_-_foo.pdf
https://www.foo.org/foo_-foo_.pdf

### Version information

- **Platform**: Windows 10, Desktop
<img width="238" alt="matrix-bug" src="https://user-images.githubusercontent.com/4551147/84404797-4d362800-abd5-11ea-9a67-94443aff7bc1.PNG">

**Comment by t3chguy** [comment] 2020-06-11 15:43
If you enter it as `<https://www.foo.org/foo_-_foo_.pdf>` then it works, this is the Commonmark (https://spec.commonmark.org/dingus/) URL syntax which makes it exempt from markdown.

**Comment by jryans** [comment] 2020-06-11 16:25
Thanks for the feedback! Sounds like a duplicate of https://github.com/vector-im/riot-web/issues/4674. We're contemplating changing our Markdown variant to resolve issues like. I'll close for now, as it seems fairly clearly the same, but please reopen if I've misunderstood.

**Closed by jryans** 2020-06-11 16:25 UTC
Labels: bug
