### ISSUE TITLE
room shield is incorrectly red if you haven't set up cross signing

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#12158] opened 2020-01-30 17:30 UTC
Presumably because it thinks you have unverified devices.

Conclusion from IRL: the room have a black shield if you haven't verified anyone else in the room. ie. it should only have a green or red shield if there is another user in the room who you've verified.

The rationale for this is that we're assuming user verification is always symmetrical (it should be) so having an unverified device yourself only causes the room to go red for you if it would *also cause it to go red for someone else*.

 * [ ] Sync with mobile on this

**Comment by jryans** [comment] 2020-01-30 17:33
Hmm, but I thought we specifically wanted to include yourself so that everyone has a consistent view of the trust status of the room? cc @nadonomy

**Comment by jryans** [comment] 2020-01-30 18:02
@dbkr will record the latest decision here, but no changes for now until after FOSDEM.

**Comment by jryans** [comment] 2020-02-11 15:34
Duplicate of https://github.com/vector-im/riot-web/issues/12214, already fixed on web and mobile notified.

**Closed by jryans** 2020-02-11 15:34 UTC
Labels: cross-signing-sprint, story:40
