### ISSUE TITLE
Spinner padding has broken uglily on registration page

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#14405] opened 2020-07-10 19:10 UTC
<img width="739" alt="Screenshot 2020-07-10 at 20 09 55" src="https://user-images.githubusercontent.com/1294269/87189902-67a11580-c2e9-11ea-855d-1d85831e5286.png">

**Comment by turt2live** [comment] 2020-07-10 20:37
Duplicate of https://github.com/vector-im/riot-web/issues/14322

**Closed by turt2live** 2020-07-10 20:37 UTC
Labels: bug
