### ISSUE TITLE
Redaction confirmation prompt doesn't have focus by default

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3508] opened 2017-03-24 16:08 UTC

**Comment by pafcu** [comment] 2017-12-15 08:32
@ara4n It seems to have nowadays? I also cannot reproduce the problem.

**Comment by aidalgol** [comment] 2018-04-15 10:54
I think this was fixed by matrix-org/matrix-react-sdk#1630 and matrix-org/matrix-react-sdk#1674.

**Comment by t3chguy** [comment] 2018-06-23 15:27
This was fixed

**Closed by t3chguy** 2018-06-23 15:27 UTC
Labels: cannot-reproduce, easy, minor, p2, ui/ux
