### ISSUE TITLE
Room / Community specific display names / alias .

### ISSUE THREAD

**Issue by dessalines** [vector-im/riot-web#7070] opened 2018-07-22 19:03 UTC
In certain rooms, I want my display name to be my real name and city for example, while on other rooms I might want a username that hides that. I think it should be possible to override your global display name in favor of a room or community specific one. 

Also in discord, a community admin ( or maybe in this case, a room admin ), can change a users' display names.

**Comment by t3chguy** [comment] 2018-07-22 19:34
Matrix has per room displaynames, there is just no UI to set one: https://vault.webdevguru.co.uk/Matrix/per-room-nickname/

**Comment by dessalines** [comment] 2018-07-22 19:39
Ah nice,  so this is just something riot needs to add as part of its client room settings.

**Comment by t3chguy** [comment] 2018-07-22 19:41
Closing as duplicate of #2458

**Closed** 2018-07-22 19:41 UTC
