### ISSUE TITLE
Can't scroll all the way down on timeline when "Jump to first unread message" banner is shown

### ISSUE THREAD

**Issue by bwindels** [vector-im/riot-web#7234] opened 2018-08-28 14:46 UTC
![scrollbug](https://user-images.githubusercontent.com/274386/44730499-6560b400-aae1-11e8-8d98-770566c1c1c1.gif)

Once you scroll up, it fixes itself. Seems to happen on firefox only.
Looking at the DOM, the element with class `gm-scroll-view` seems to be pushed down by the banner.

p1 because I personally find it annoying as hell :)

**Comment by bwindels** [comment] 2018-08-28 14:48
Happens with both LL on and off

**Comment by tulir** [comment] 2018-08-28 15:08
Duplicate of/related to #1770

**Closed** 2018-08-28 15:43 UTC
Labels: bug, minor, p1, type:roomview
