### ISSUE TITLE
Error decrypting on Video and Image uploads

### ISSUE THREAD

**Issue by krixano** [vector-im/riot-web#9873] opened 2019-05-28 16:27 UTC
### Description

I get the error `Error decrypting video` and `Error decrypting image` when I try to upload images or videos.

### Steps to reproduce

Upload video or image.

Log: sent    

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Microsoft Edge Canary (the Chromium Fork version) - Version 76.0.172.0 (Official build) canary (64-bit)
- **OS**: Windows
- **URL**: chat.amorgan.xyz
  - matrix-react-sdk version: <local>
riot-web version: 982416b3f76f-react-afd656ae2c6b-js-b199f133b345
olm version: 3.1.0

**Comment by turt2live** [comment] 2019-05-28 16:53
Duplicate of https://github.com/vector-im/riot-web/issues/6362 based on logs.

**Closed by turt2live** 2019-05-28 16:53 UTC
