### ISSUE TITLE
Last word of wide character (Chinese/Japanese/Korean) isn't sent 

### ISSUE THREAD

**Issue by eunchan** [vector-im/riot-web#5495] opened 2017-11-01 23:58 UTC
### Description

If user types CJK sentence and press enter to send the text, last word won't be transmitted to the server.

### Steps to reproduce

- Change to any CJK input method
- Type any sentence with a space between words.
- Press 'Enter' key while writing CJK word (period or space makes word complete so it will transmit the word)

### Version information

- **Platform**: web (in-browser) or desktop both

For the web app:

- **Browser**: Chrome, Safari tested
- **OS**: macOS
- **URL**: riot.im/develop / riot.im/app / somewhere else? If a private server, what version of riot-web?

For the desktop app:

- **OS**: macOS
- **Version**: 0.12.7

**Comment by lampholder** [comment] 2017-11-02 10:42
I haven't been able to reproduce this yet - I tried the `pinyin - simplified` input on macos and `Microsoft Pinyin` on windows and had a similar experience on both:

![image](https://user-images.githubusercontent.com/1922197/32321698-e363be42-bfb9-11e7-8031-8353f8e7e362.png)

Pressing enter will kill the character selector and leave the roman characters in the composer, but it doesn't send anything without pressing enter again (and then it sends the mostly-completed Chinese sentence with just the last syllable un-transliterated).

I guess this problem is at least partially dependent on the input method being used - can you advise which one were you using when you experienced this problem?

**Comment by eunchan** [comment] 2017-11-02 17:39
<img width="390" alt="riot 2017-11-02 10-35-59" src="https://user-images.githubusercontent.com/1192814/32341085-b61e9452-bfb9-11e7-8d64-f74af85fa07a.png">

Thanks for the reply. I've tried macOS default korean input method and also other 3rd party input method. Both shows same.  As you see on the screenshot, I've tried put the full sentence but it was only sent without last word.  I've seen the similar issue on other Electron app (VSCode) but that time, the only last character was not sent not the whole last word.

**Comment by eunchan** [comment] 2017-11-02 23:10
![riot_koreaninputissue](https://user-images.githubusercontent.com/1192814/32354728-4d426240-bfe8-11e7-952d-805d34174383.gif)

Maybe this GIF might useful.

**Comment by turt2live** [comment] 2018-10-31 23:07
@eunchan are you still seeing this on recent Riot versions (0.17 and higher)?

**Comment by aaronraimist** [comment] 2018-11-01 02:54
@turt2live Unfortunately there appears to be a pretty significant upstream bug in Slate that is worse than this issue.

Wrong:
![riot](https://user-images.githubusercontent.com/5855073/47829822-5a333a00-dd57-11e8-892e-74f041c79777.gif)

Wrong:
![slate](https://user-images.githubusercontent.com/5855073/47829828-5e5f5780-dd57-11e8-82df-4aa5bc47bd40.gif)

Correct:
![github_correct](https://user-images.githubusercontent.com/5855073/47829831-61f2de80-dd57-11e8-9298-2808a98bd23f.gif)

**Comment by aaronraimist** [comment] 2018-11-01 02:57
@turt2live I assume someone is going to write a bunch of tests for all of these input bugs?

**Comment by turt2live** [comment] 2018-11-01 04:57
> @turt2live I assume someone is going to write a bunch of tests for all of these input bugs?

First step is figuring out what all the root causes are, then determining if they are upstream issues (like this one), then fixing, then maybe tests. It's incredibly difficult to write tests for the thousands of different ways to type a message though.

**Comment by turt2live** [comment] 2018-11-05 23:08
Closing in favour of https://github.com/vector-im/riot-web/issues/7665 to track the upstream issue.

**Closed by turt2live** 2018-11-05 23:08 UTC
Labels: bug, major, p1, type:composer, upstream-issue
