### ISSUE TITLE
Incorrect escaping of IRC(?) nicknames

### ISSUE THREAD

**Issue by joepie91** [vector-im/riot-web#9771] opened 2019-05-20 09:09 UTC
### Description

Nicknames from IRC(?) get incorrectly escaped for certain special characters.

### Steps to reproduce

- Enter `#freenode_#bottest:matrix.org`
- Post a GitHub link, like `https://github.com/vector-im/riot-web/issues/7134`, wait for the bot to respond with the issue title
- Notice the wrong bot nickname :)

Original on IRC:

```
[10:56] <joepie91[m]> sphalerite: https://github.com/vector-im/riot-web/issues/7134 :)
[10:56] <{^_^}> vector-im/riot-web#7134 (by turt2live, 41 weeks ago, open): Pills for users with backticks get converted to code when complimented with another backtick
```

Bot nickname display in Riot (desktop):

![Selection_0017](https://user-images.githubusercontent.com/1663259/58009192-2dc1ee00-7aee-11e9-90db-71ff0ab3bcd6.png)

As you can see, some sort of encoding happens in the process, and turns the `{` into `=7b`, and the `}` into `=7d`. This *should* be displayed as `{^_^}` instead of `=7b^_^=7d`.

I don't know whether this is a bug in the IRC bridge or in Riot.

Log: not sent

### Version information

- **Platform**: desktop

- **OS**: NixOS 18.09, Riot desktop installed from unstable nixpkgs channel
- **Version**: matrix-react-sdk version: <local>  /  riot-web version: 1.0.8  /  olm version: 3.0.0

**Comment by jryans** [comment] 2019-05-20 09:13
This looks to be a duplicate of https://github.com/vector-im/riot-web/issues/9662, when it was mentioned that the actual issue is tracked at https://github.com/matrix-org/matrix-appservice-irc/issues/749, so it's a bridge issue.

**Closed by jryans** 2019-05-20 09:13 UTC
Labels: bug, ui/ux
