### ISSUE TITLE
option to tweak the FilePanel to show all the links in a room?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#3583] opened 2017-04-07 19:16 UTC
as per https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$1491592123253910fIpNO:matrix.org

**Comment by lampholder** [comment] 2017-04-20 17:00
gnos: I love how all the media posted in a room is listed. It would be awesome if there was also a list of all the links posted in a room.

So the scope of this would be to enhance the filepanel such that it could optionally show a list of links posted. Or even another top level entity on the right panel: people, media, notifications, links.

**Comment by lampholder** [comment] 2017-04-20 17:02
Or, even better than this, you could add your own customisable filters + regex substitutions, so you could have a quick view on all the messages posted by an individual, or to an individual, or containing links or links to a specific domain...

**Comment by aaronraimist** [comment] 2020-01-15 21:38
Duplicate of #8746

**Closed by aaronraimist** 2020-01-15 21:38 UTC
Labels: feature, p3
