### ISSUE TITLE
Redesign: membership list ordering is wrong; high PLs are no longer at the top.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7886] opened 2018-12-17 15:43 UTC
(instead it's ordering by broken presence)

**Comment by turt2live** [comment] 2018-12-17 15:47
Duplicate of https://github.com/vector-im/riot-web/issues/6953

**Comment by bwindels** [comment] 2018-12-18 14:04
@turt2live It's not broken on /develop though ... This is on /experimental.

**Comment by turt2live** [comment] 2018-12-18 15:02
#6953 is the issue for broken on develop. I've also seen it broken constantly on develop. Unless this issue is referencing something else, it's not an experimental-exclusive issue.

**Comment by bwindels** [comment] 2018-12-18 15:11
Ok, that does sounds like the same thing then.

**Closed by bwindels** 2018-12-18 15:11 UTC
