### ISSUE TITLE
Verification status icons look worse than before and have white pixelated halo in dark theme

### ISSUE THREAD

**Issue by Vroop** [vector-im/riot-web#11566] opened 2019-11-30 03:22 UTC
![Unverified Icon](https://user-images.githubusercontent.com/29561518/69895003-275ecb00-12f6-11ea-8e88-2e82e3bc14f3.png)
![Verified Icon](https://user-images.githubusercontent.com/29561518/69895004-275ecb00-12f6-11ea-9e6b-46aebb038532.png)

### Description

The new verification status icons (all devices Verified, some devices Unverified) clash stylistically with the rest of the icons, and also have a white pixelated halo around them when viewed in dark mode.

### Steps to reproduce

- Update to riot desktop 1.5.5
- Previously nice looking icons replaced by bad looking icons

I expected the same nice-looking icons to be there, and match stylistically with the other icons

Logs being sent: yes/no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Linux Mint
- **Version**: 19.2

**Comment by turt2live** [comment] 2019-11-30 03:34
Duplicate of https://github.com/vector-im/riot-web/issues/11490

**Closed by turt2live** 2019-11-30 03:34 UTC
Labels: bug, ui/ux
