### ISSUE TITLE
Debian package 'riot-web' overwrites config.json on update

### ISSUE THREAD

**Issue by robert-czechowski** [vector-im/riot-web#5553] opened 2017-11-09 14:25 UTC
### Description

When updating the debian package 'riot-web', the configuration file `config.json` is overwritten.

### Steps to reproduce

- Install package according to https://github.com/vector-im/riot-web#getting-started
- Change configuration in `config.json` according to https://github.com/vector-im/riot-web#configjson
- Update the package when a new version is released

The changes in `config.json` from step two are now overwritten.

Log: not sent    

### Version information

  $ dpkg -l | grep riot-web 
  ii  riot-web                               0.12.7                             amd64

- **Platform**: Web
- **Browser**: –
- **OS**: Debian 8.9
- **URL**: Private server. riot-web 0.12.7

**Comment by t3chguy** [comment] 2017-11-09 14:50
Duplicate of #4394

TL:DR; this is intentional as it is a build config rather than a user config.

**Closed by t3chguy** 2017-11-09 14:50 UTC
