### ISSUE TITLE
weird receipts (m.read) behavior

### ISSUE THREAD

**Issue by PhilipHomburg** [vector-im/riot-web#12265] opened 2020-02-06 13:40 UTC
For rooms that I follow, I switch to the room and then click on the up arrow with the green dot to continue reading where I left off.

What riot-web does is first set m.read to the most recent event (clearing the unread event counter on the way) as soon as I look at the room. Then the up arrow jumps to m.fully_read.

Note that to other people in the same room, this gives the impression that I read the entrie room, even when I just look at the screen long enough to find the up arrow.

My preference would be to have an option that  jumps to m.fully_read (or even m.read) when switching to a room instead of the most recent event. The down arrow makes it easy enough to reach the most recent event.

Alternatively, if showing the most recent events first is preferred, maybe delay setting the m.read pointer for 10 seconds to allow a user who wants to read the entire room to click the up arrow.

**Comment by t3chguy** [comment] 2020-02-06 13:44
Duplicate of https://github.com/vector-im/riot-web/issues/11235

**Closed by t3chguy** 2020-02-06 13:44 UTC
Labels: suggestion
