### ISSUE TITLE
Key exchange is not user friendly or very well documented

### ISSUE THREAD

**Issue by bkerensa** [vector-im/riot-web#4189] opened 2017-06-05 08:11 UTC
It is unclear how to send or share keys in Riot while other apps like Signal and Telegram make key exchange a lot more user friendly.

I am in a few groups that are considering leaving Riot because we have users complaint they cannot see messages and get this instead:
** Unable to decrypt: The sender's device has not sent us the keys for this message. **

It is unclear how those users can share their keys and this results in only some seeing messages.

Your help page and the app gives no indication how to send a key to another user and there is no way to request keys? Key exchange should be automatic like Telegram and Signal!

**Comment by uhoreg** [comment] 2017-06-06 01:32
Thank you for your report.  Sending of decryption keys should be automatic, but unfortunately, due to bugs, the keys may sometimes get lost, which is why encryption is still in beta.  Most of the causes are linked in the main tracking issue: #2996.  The developers are working on fixing this, though when this happens, you can help by getting both the sender and receiver to submit a bug report from within the app (e.g. using the "Report it" button in the user settings in the web/desktop app, and tell it to include the logs) to help the developers make sure that they have identified all the causes of this issue.

One thing to note is that the one time that message is expected is when you log in a new session and are trying to read messages sent before that session began, as that's just the way the encryption works.  Though in the future, if you had another device logged in previously, you will be able to send the decryption keys from your previously-logged-in device to your new device.

Closing this as a duplicate of #2996.

**Closed by uhoreg** 2017-06-06 01:32 UTC
