### ISSUE TITLE
Filter room members is styled differently to filter room names

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riot-web#8182] opened 2019-01-21 13:08 UTC
- Background, placeholder text & input text styled differently
- Missing an [x] button to clear on Filter members

Is there any reason why these shouldn't use a shared component? We may want to revisit this after standardising the new form controls built for login.

**Comment by bwindels** [comment] 2019-01-21 13:18
the placeholder, border and background color is a regression caused by these changes:
https://github.com/matrix-org/matrix-react-sdk/pull/2463/files#diff-d01743f8ba8d9fe036c6b6bdbf7df974R205

now this selector is more specific than the one that is scoped to .dark-panel, which is where the darker background color, color and no border is set.

**Comment by jryans** [comment] 2019-01-21 15:08
I moved "Missing an [x] button to clear on Filter members" to #8188, as apparently it did not have a clear button before, so it's not related to the styling regression.

**Comment by jryans** [comment] 2019-01-21 19:57
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2465.

**Closed by jryans** 2019-01-21 19:57 UTC
Labels: bug, redesign, regression
