### ISSUE TITLE
Tray icon on KDE Plasma 5 looks weird / wrong.

### ISSUE THREAD

**Issue by z3ntu** [vector-im/riot-web#5129] opened 2017-09-27 06:05 UTC
### Description

The Tray icon on KDE Plasma 5 looks weird / wrong.

### Steps to reproduce

- Start Riot Desktop on KDE Plasma 5.

![image](https://user-images.githubusercontent.com/3768500/30898203-5a87639c-a35a-11e7-9c24-343c0f555969.png)

I've also seen a version that's red-ish (probably when an unread message is waiting)

Log: sent/not sent?    
Can provide but don't think shows anything.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Arch Linux
- **Version**: 0.12.6

**Comment by MurzNN** [comment] 2017-09-27 06:50
This is KDE & Electron issue, here is solution: https://github.com/vector-im/riot-web/issues/3133#issuecomment-314980590
Duplicate of #3133

**Comment by z3ntu** [comment] 2017-09-27 06:54
Well I can interact with the tray icon... And I have libappindicator-gtk3 12.10.0-12 installed.

**Comment by MurzNN** [comment] 2017-09-27 07:00
You must remove libappindicator (or replace with dummy package) for enable working Electron icons :)

**Comment by z3ntu** [comment] 2017-09-27 08:24
Well I need libappindicator(-gtk3) for another package so I can't just nuke it.

**Comment by t3chguy** [comment] 2017-09-27 08:26
Closing as duplicate of #3133

**Closed by t3chguy** 2017-09-27 08:26 UTC

**Comment by ArchangeGabriel** [comment] 2017-10-31 21:30
@z3ntu We have normally removed all dependencies on it. So that you can get a pixellised icon instead. ;)
