### ISSUE TITLE
Reply is highlighted even without actual mention when domain matches username

### ISSUE THREAD

**Issue by pacien** [vector-im/riot-web#11132] opened 2019-10-12 19:06 UTC
### Description

My username matches my domain (MXID of the form `@<username>:<username>.tld`).
As a result, all replies to messages from any other user on my homeserver are highlighted in my Riot session, flooding me with urgent notifications without intended mentions.

### Steps to reproduce

Let `@alice:alice.tld`, `@bob:alice.tld` and `@caroline:alice.tld` be three users on the homeserver `alice.tld`. All three are members of a room in which:

1. Bob sends a message that does __not__ mention Alice.
2. Caroline replies to Bob's message using the reply feature, still __not__ mentionning Alice.
3. __Alice's Riot highlights Caroline's message and Alice is notified, even though nobody intended to mention her.__

### Remediation?

Do not allow partial matches on MXIDs contained in messages for highlighting purposes.
A highlight should require the whole MXID to match.

### Version information

- **Platforms**: all
- **Version**: 1.4.1

**Comment by t3chguy** [comment] 2019-10-12 19:08
Highlights are calculated server side, not in riot

**Comment by pacien** [comment] 2019-10-12 19:09
I haven't tested it, but the issue may probably also arise when someone's username is an infix of someone else's username: `@pierre:domain.tld` might get notified when someone replies to a message from `@jean.pierre@domain.tld`. To confirm.

> Highlights are calculated server side, not in riot

Should I submit this to the Synapse bug tracker instead?

**Comment by t3chguy** [comment] 2019-10-12 19:38
I think it's more of a matrix spec thing

**Comment by turt2live** [comment] 2019-10-12 20:31
Closing in favour of https://github.com/vector-im/riot-web/issues/7874

**Closed by turt2live** 2019-10-12 20:31 UTC
Labels: bug

**Comment by pacien** [comment] 2019-10-12 20:40
> Closing in favour of #7874

#7874 looks like a different issue in which messages contain pings hidden in the reply chain.

The current issue is about the way mentions are being matched incorrectly in the body field. In the given example, Alice gets notified even though no actual mention of her has ever been sent by anyone.

Please re-open.

**Comment by turt2live** [comment] 2019-10-12 20:44
Ah, well: in that case you need to adjust your notification preferences. Disable notifications for your username in settings, not just your display name. I recommend using keywords instead of the default options (it's how I survive).

Unfortunately notifications are complicated, but this is working as intended.

**Comment by pacien** [comment] 2019-10-12 21:10
The same problem appears with user-defined keywords too: they're still generating highlights/notifications when present in someone else's MXID.

I think that MXIDs strings should be excluded when scanning messages for mentions using strings. It makes no sense to try to find a substring in those as they already are explicit mentions as a whole.

Is there any chance to have the specification fixed for this?

**Comment by turt2live** [comment] 2019-10-12 21:25
The specification could be fixed, yes. It's a well known issue to the whole team that notifications are a bit annoying to handle.

If an issue doesn't exist already, please open one on matrix-doc
