### ISSUE TITLE
clicking on autocomplete loses composer focus

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#5078] opened 2017-09-18 16:05 UTC

**Comment by psaavedra** [comment] 2017-09-18 16:22
When you use the pop-up menu in the entry text box, if you use the mouse to click over a item, the focus doesn't return to the text box, so you are forced to click again in the text area to continue typing. An user expect the fo us returns and continues typing in the textarea

**Comment by lampholder** [comment] 2017-09-22 17:23
I've controversially p2'ed this, based upon my assumption that _most_ people use the keyboard (and mouse users won't be devastated by the need to click back into the composer).

It should certainly be fixed though, and I expect is v. easy to do.

**Comment by makedir** [comment] 2018-05-27 06:10
Still not FIXED. And it's even worse, the emoticons are in its current state totally useless, because there are at least two other bugs related to this:

- clicking on emoticon removes focus but if you click back with mouse into text field, NO CURSOR is present.

- happens a lot, I dont know how to reproduce it, that the emoticon gets "stuck" and messes up the text field, so you cannot send text away anymore via ENTER. Enter just becomes a new line if pressed in the text field, it doesnt send messages away anymore. Only way to fix this is to restart RIOT client.

**Comment by t3chguy** [comment] 2018-05-27 08:04
This is likely fixed by the switch to slate. Which is in a pr right now.

**Comment by makedir** [comment] 2018-07-04 13:21
Still not fixed.

**Comment by t3chguy** [comment] 2018-07-04 13:22
@makedir Yes. Slate hasn't landed yet.
> Which is in a pr right now.

**Comment by ara4n** [comment] 2018-07-16 17:05
fixed by matrix-org/matrix-react-sdk#1890

**Closed by ara4n** 2018-07-16 17:05 UTC
Labels: bug, easy, minor, p2, type:rte, ui/ux
