### ISSUE TITLE
Systray Icon keeps disappearing, can't quit properly

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#13588] opened 2020-05-07 19:01 UTC
Naturally, I upgraded to 1.6 as soon as it came out.

Unsure why, but since I've upgraded to 1.6 the systray icon for Riot keeps disappearing. I'm unsure if this is after a set of time, or when I lock, or random. I'm on Ubuntu Linux 19.10 btw.

The issue with this is that I now do not have a nice way to quit Riot, as there is no "Exit" option in the pull-down menu. Just "Sign out". I also don't see the number of alerts for me, since no systray icon.

In order to solve this, I have to forcefully kill the Riot thread, and re-open it. Pretty annoying.

Unsure what more to add here.

**Comment by t3chguy** [comment] 2020-05-07 19:04
Duplicate of #12518

**Comment by BloodyIron** [comment] 2020-05-07 19:05
Uh this didn't happen until 1.6 though. I didn't have the issue before then, so I would not classify this as duplicate. @t3chguy

**Closed** 2020-05-07 19:04 UTC
Labels: bug

**Comment by t3chguy** [comment] 2020-05-07 19:09
Yes, this same thing happened when 1.5.10 upgraded to electron 8 before we rolled back to 7

Now 1.6 needs electron 8.read the last few comments on that issue.

**Comment by BloodyIron** [comment] 2022-08-04 18:40
This issue is still happening, let's re-open this please @t3chguy

**Comment by br3eze** [comment] 2023-01-27 09:21
ArchLinux, last updates. No sys-tray icon at all. Re-enabling doesn't help.

**Comment by BloodyIron** [comment] 2023-01-30 19:14
I still get randomly the systray icon just going "blank", it could take hours to days, I'm really not sure truly how long.

Currently:

Element version: 1.11.21-rc.1
Olm version: 3.2.12
