### ISSUE TITLE
Discord-style search in rooms

### ISSUE THREAD

**Issue by BearerOfHonesty** [vector-im/riot-web#9761] opened 2019-05-19 10:02 UTC
Discord-style search in rooms. At least media types, links, messages from or mentioning users based on account name.

**Comment by julianfoad** [comment] 2020-03-04 14:11
This is a duplicate of #4752 (where a Discord search UI is shown as an example in a comment).

**Comment by turt2live** [comment] 2020-03-04 17:18
indeed, thanks!

**Closed by turt2live** 2020-03-04 17:18 UTC
Labels: suggestion
