### ISSUE TITLE
Error in single public room list prevents other lists from loading

### ISSUE THREAD

**Issue by gtbuchanan** [vector-im/riot-web#11640] opened 2019-12-10 16:28 UTC
### Description

When a public room list fails to load, all other room lists refuse to load until the "Explore rooms" dialog is reopened.

### Steps to reproduce

1. Load matrix.org room list (which is currently returning a 500 error) or another broken list

![image](https://user-images.githubusercontent.com/715687/70545078-a6dc6d80-1b32-11ea-97d2-b82961b05ea9.png)

2. Switch to another room list (e.g. privacytools.io) and it shows the same error even though the server is not returning a 500 error:

![image](https://user-images.githubusercontent.com/715687/70545276-edca6300-1b32-11ea-9cf1-b1e94e4caed0.png)

3. Close "Explore rooms" dialog

4. Reopen and go directly to working room list (e.g. privacytools.io) to confirm it is really working

![image](https://user-images.githubusercontent.com/715687/70548018-7fd46a80-1b37-11ea-825b-48f1b1b65e6d.png)

### Version information
- **Platform**: Riot Web and Desktop v1.5.6
- **Server**: Synapse v1.6.1

For the web app:

- **Browser**: Firefox 71
- **OS**: Windows 10
- **URL**:  Self-hosted Riot Web v1.5.6

For the desktop app:

- **OS**: Windows 10
- **Version**: 1.5.6

**Comment by turt2live** [comment] 2019-12-10 16:31
Duplicate of https://github.com/vector-im/riot-web/issues/10506

**Closed by turt2live** 2019-12-10 16:31 UTC
Labels: bug, ui/ux
