### ISSUE TITLE
repeatedly jumping to a message doesn't work

### ISSUE THREAD

**Issue by lub** [vector-im/riot-web#13319] opened 2020-04-22 08:41 UTC
### Description

If you repeatedly click on a matrix.to link/message timestamp it only jumps to the message the first time. You have to focus another message first to jump to the desired message again

### Steps to reproduce

- Reply to an older message (old enough so Riot has to scroll up to display it)
- click on the timestamp in the replied-to message
- (Riot focuses the message and scrolls up)
- click "Scroll to most recent messages"
- (Riot scrolls down to the bottom)
- again click on the timestamp in the replied-to message

At that point Riot will do nothing, because the message is already focused (has that green bar on the left). I'd expect it to again scroll to the message behind the timestamp.

For clarification I mean that timestamp:
![image](https://user-images.githubusercontent.com/1029578/79960511-c5118d00-8485-11ea-8461-916e56700e2c.png)

Logs being sent: yes

### Version information

- **Platform**: desktop
- **OS**: Windows
- **Version**: 1.5.15

**Comment by t3chguy** [comment] 2020-04-22 09:14
Duplicate of https://github.com/vector-im/riot-web/issues/2903

**Closed by t3chguy** 2020-04-22 09:14 UTC
Labels: bug, ui/ux
