### ISSUE TITLE
failing to screen share

### ISSUE THREAD

**Issue by vaschw** [vector-im/riot-web#8926] opened 2019-02-25 04:56 UTC
### Description

Failing to screen share.

### Steps to reproduce

-Use two computers to log in to two accounts on riot.im, using the web browser interface.
-I'm using Firefox 64.0 on each computer (one 32-bit, one 64-bit)
-Get both accounts into same chat room
-Neither computer has a microphone or a camera, so plug in a microphone to each computer.
-On one computer, shift-click the "video" button to start a call and initiate a screen share.
-Firefox requests permission to share the screen.  Allow sharing of the "Entire screen".
-Firefox now requests access to the microphone.  Allow it.
-This initiates a call, with an attempted screen share.
-Accept the call on the other computer.

Resulting popup on the computer *receiving* the call (happens instantly):
"Call Failed. Couldn't start capturing media! Is your microphone set up and does this app have permission?"

On the *calling* computer:
It continues to ring for some time, not seeing an answer, and eventually times out.
"Call Timeout: The remote side failed to pick up."

Yes, both microphones are plugged in.  The microphones should also have permission, because I can attempt to initiate the call in the other direction and this causes me to be asked for permission to use the microphone on the other previously-receiving / now-sending computer.  Both computers have the same popup, even after repeated attempts at calling in both directions.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 64.0 (64-bit) and 64.0.2 (32-bit) on the two computers
- **OS**: Windows 7 (both computers)
- **URL**: riot.im/app

**Comment by t3chguy** [comment] 2019-02-26 16:01
Is this not simply related to the fact that to pick up a Video (screenshare) call you need a Video source (webcam)?

**Comment by vaschw** [comment] 2019-02-27 13:17
@Ryan
I am able to initiate a voice call without receiving errors.
(Voice calls do not work perfectly, but that is not my primary concern at
this point.  I can hear myself from one set of computer speakers, but not
the other.  I tested both speakers, and both microphones, and they both
work for other programs.  The one microphone level may be too low, or it
may be a problem with Riot.  This is yet TBD.)

<mmcco@mykolab.com>@Michael
I do not want to have a video call.  I want to share my screen for a
presentation, i.e. show the other user what is displayed in a slideshow on
my screen.  Initiating a screenshare is done by shift-clicking on the
camera symbol (as opposed to just clicking, which gives a video chat).  If
the error results from me not having a webcam, then 1) this is not what the
error message says, and 2) it seems like this error should not occur,
because a webcam is not necessary for a screenshare.

Thank you both for your quick responses.  Any further suggestions?

-Andrew

**Comment by t3chguy** [comment] 2019-02-27 15:39
@vaschw 

> "Call Failed. Couldn't start capturing media! Is your microphone set up and does this app have permission?"

The error is a bit useless but this error is probably saying that you're trying to answer a video call (screen sharing is video) but have don't have the matching device, e.g webcam, its a bit annoying that Riot doesn't support answering a Video call with voice-only but that's https://github.com/vector-im/riot-web/issues/466

**Comment by vaschw** [comment] 2019-03-06 04:12
@Michael / t3chguy,

It's disappointing that screen sharing seems to be impossible without a
webcam; I cannot think of a logical reason why a webcam would be necessary
to screen share.  Thank you for the clarification.  I hope this requirement
will be eliminated in a subsequent revision of riot.im / matrix.org.

Thanks again for your help,
-Andrew

**Comment by t3chguy** [comment] 2019-03-06 08:46
@vaschw Yes. That's issue https://github.com/vector-im/riot-web/issues/466 as linked in my previous comment.

**Comment by jryans** [comment] 2019-03-06 10:20
It looks like this is a duplicate of #466. Please let me know if I have misunderstood.

**Closed by jryans** 2019-03-06 10:20 UTC
Labels: question
