### ISSUE TITLE
camera left on after closing jitsi widget :/

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#7351] opened 2018-09-17 10:19 UTC

**Comment by lampholder** [comment] 2018-09-19 13:02
Seems to be trivially reproducable.

Steps I followed:
- go to room with more than 2 participants in which I have perms to add a jitsi widget
- click the video call button
- join the conference
- click the red dustbin 'delete widget' icon
- agree to this deleting it for everybody
- look at the camera light still shining bright

**Comment by turt2live** [comment] 2018-10-19 22:18
This is because the JitsiMeet instance (buried in the iframe for the widget) doesn't get the proper shutdown signal. The iframe that holds the widget simply winks out of existence, leaving the stream open.

Riot can't do much to actually trigger a shutdown on the iframe due to cross-origin request prevention (even though Riot is the parent). Instead, we can use a dirty hack to change the iframe's source momentarily which is enough for JitsiMeet to receive the shutdown signal ergo releasing the stream.

**Comment by turt2live** [comment] 2018-10-26 14:09
Fixed by https://github.com/matrix-org/matrix-react-sdk/issues/2232

**Closed by turt2live** 2018-10-26 14:09 UTC
Labels: bug, major, p1, type:voip
