### ISSUE TITLE
Login Popup on public rooms for guest users that they must login with account to see the room

### ISSUE THREAD

**Issue by flyinghuman** [vector-im/riot-web#13655] opened 2020-05-13 11:43 UTC
### Description

Public available Rooms are firstly not available for Guests even if the Permissions are set correctly to everyone. If you make some actions on the Site you will see the room as it should be, see below:

### Steps to reproduce

1. make a room public and access the shareable link
2. "Join the conversation with an account" pops up, so that you cannot see the public available chat
3. Click on + Communities
4. Click another time on # Communities to close it
5. you are redirected to standard-login page
6. now use the browser back button
7. you see the public chat with content and only a small reminder on bottom to login if you want to join the conversation with an account

Describe how what happens differs from what you expected:

The expected behavior would be Number 7 straight from beginning.

### Version information
- **Platform**: web
- **Browser**: Chrome, Firefox latest release
- **OS**: Windows
- **URL**: If a private server, what version of riot-web: 1.6.0

OKAY:
![okay](https://user-images.githubusercontent.com/3713548/81808143-91270600-951f-11ea-9675-cf2557429853.JPG)

Not Okay:
![not_okay](https://user-images.githubusercontent.com/3713548/81807785-ffb79400-951e-11ea-8ce8-b83fe91f6e65.JPG)

**Comment by t3chguy** [comment] 2020-05-13 11:46
Duplicate of https://github.com/vector-im/riot-web/issues/12307

**Closed by t3chguy** 2020-05-13 11:46 UTC
Labels: bug
