### ISSUE TITLE
Minimized Room list headers sometimes hide themselves on scrolling the room list

### ISSUE THREAD

**Issue by jaywink** [vector-im/riot-web#14385] opened 2020-07-09 07:21 UTC
### Description

*Edit: was able to reproduce, see comment below.*

Happening often in a last few days on Riot Nightly, room list headers, especially the "People" disappear randomly. I have not figured out how to get them visible again except by restarting the client OR it comes back at some time later. Could not find an existing issue.

Filtering for the rooms in the hidden sections also does not work so gaining access to DM's that I see notifications for requires restarting.

Just now when starting to report, I had the Favorites also disappear for the first time.

![Selection_667](https://user-images.githubusercontent.com/1174866/87009321-acd02500-c1cd-11ea-8c84-719de71e0a5e.png)

Will upload logs.

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu
- **Version**: 2020070801

**Comment by jaywink** [comment] 2020-07-09 07:26
Oh! I just reproduced it many times.

* Expand favorites (~20 or so)
* Minimize People
* Expand rooms (~170 or so)

Use mouse wheel to scroll up and down. Sometimes the "People" disappears and sometimes it comes back, scrolling up and down.

**Comment by turt2live** [comment] 2020-07-09 13:05
Duplicate of https://github.com/vector-im/riot-web/issues/14371

**Closed by turt2live** 2020-07-09 13:05 UTC
Labels: bug, type:new-room-list
