### ISSUE TITLE
make it possible to change font size

### ISSUE THREAD

**Issue by IzabellaDK** [vector-im/riot-web#3160] opened 2017-02-07 13:39 UTC
Being of a somewhat mature age the eyes are not happy with too small fonts. And it feels a bit awkward to sit with a magnifying glass just for reading a comment...
So: Please make give me to option to choose the size of typeface in the chatwindow. Would be nice though if everything was a bit more readable for old eyes that have seen so much of the world...

Thx in advance for your effort - and a nice app for all the main platforms!

**Comment by richvdh** [comment] 2017-02-07 15:18
Have you tried zooming in?

**Comment by IzabellaDK** [comment] 2017-02-07 15:29
With a magnifying glass? :)

**Comment by IzabellaDK** [comment] 2017-02-07 16:05
Dark Theme actually helps a bit - but still..

**Comment by richvdh** [comment] 2017-02-07 16:24
> With a magnifying glass? :)

That, or you could try your browser's zoom controls... ctrl-plus/minus here.

**Comment by IzabellaDK** [comment] 2017-02-07 17:46
Ofc it would work in a browser but uses the Riot windows app. 

Mag glasses are great but not if you write with 10 fingers at the same time 💃

**Comment by richvdh** [comment] 2017-02-07 19:50
Right, the fact you are using the electron app would have been helpful information upfront ;)

**Comment by ara4n** [comment] 2017-02-09 00:42
yeah, there's a weird problem here. even if you /do/ use ctrl-plus/minus (or pinch-zoom on macOS) it only remembers it for a single page for some reason.

**Comment by ara4n** [comment] 2017-02-09 00:44
have filed the brokenness as #3179. let's keep this bug as tracking exposing the setting more clearly.

**Comment by IzabellaDK** [comment] 2017-02-09 08:11
Thx very much!!

**Comment by Mikaela** [comment] 2017-07-18 18:08
> That, or you could try your browser's zoom controls... ctrl-plus/minus here.

The issue for me is that this isn't remembered and the zoom randomly reverts to original 100%.

I have two use cases:

* Group HQ where there are messaging clients (Slack, Riot and HexChat) either on TV or projector screen and one of the reasons why people won't bother with Riot is it being so small and the zoom being hidden under alt, view, zoom in and repeating that a few times.
* My laptop which under Arch with resolution 1920x1080 makes mostly everything unpleasantly small in some apps (mainly Chromium, Slack, Riot, Telegram and all others have option for setting zoom or interface scaling).

* ![Chromium](https://user-images.githubusercontent.com/831184/28332012-e09be732-6bfb-11e7-861c-5b72b0f660df.jpg)
* ![Slack](https://user-images.githubusercontent.com/831184/28331835-54160b44-6bfb-11e7-98a7-64c4a1e3c4b8.jpg)
* I understood this issue to be about Riot missing this option.
* ![Telegram](https://user-images.githubusercontent.com/831184/28332090-22a5d44e-6bfc-11e7-9f7b-17e8e5c62b13.jpg)

On my laptop I am able to read all the other apps by adjusting my desktop settings and if Riot is not going to follow them (why?) I would like to have the option like in the other apps.

![Appreance Preferences](https://user-images.githubusercontent.com/831184/28332360-35035944-6bfd-11e7-9600-6c84ca86f5c9.jpg)

**Comment by NessBird** [comment] 2017-09-12 15:02
It's very upsetting to me that Github Desktop doesn't accommodate older users.  I think this should be a priority.

**Comment by ara4n** [comment] 2017-09-12 15:26
i believe this was fixed a while back - ctrl-plus and ctrl-minus (or cmd-plus/cmd-minus on a mac) should change the zoom, and i believe it is now remembered when you switch room?

**Comment by NessBird** [comment] 2017-09-12 15:54
No, those keys do not do anything.  There appears to be no way to zoom.

**Comment by NessBird** [comment] 2017-09-12 15:58
Now I have it up to Things Done Hastily, same behavior.

**Comment by t3chguy** [comment] 2017-09-12 16:57
@NessBird wrong repo, those are versions of Github Desktop - this is riot-web.

**Comment by ara4n** [comment] 2017-10-29 21:51
I think all that is needed here is really to hook up the `View: Zoom In/Zoom Out` menus in Electron, much as you have in plain old Chrome.

**Comment by status-open-bounty** [comment] 2017-11-27 18:35
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf80de6e9e0d571572f6068d206743814ec566cd9622232a4c170f849eb899b47](https://etherscan.io/tx/0xf80de6e9e0d571572f6068d206743814ec566cd9622232a4c170f849eb899b47)

**Comment by monokh** [comment] 2017-12-02 09:08
Hi i'd like to work on this but a little confused on the requirements.
From my testing (mac OSX) Ctrl +, Ctrl - work just fine. It applies in the same session although not the next time you launch riot. It seems that electron has actually remembered the zoom level but not applied it, because if you zoom (ctrl +) you will be back to the zoom level you had previously. 

So is the main idea to preserve the zoom level across different sessions?

**Comment by IzabellaDK** [comment] 2017-12-02 10:00
Well - the problem persists when using Riot in Windows 10 and Ubuntu 17.xx since no shortcuts are working to increase/decrease font size in these environments - and it is not possible to change font in settings

**Comment by t3chguy** [comment] 2017-12-02 10:13
Better would be to add a font size slider like discord has

**Comment by monokh** [comment] 2017-12-02 19:54
Ok understood. Is this setting to be visible on both desktop and web or will this be a "desktop specific" setting that changes the electron window zoom level (given that the problem is not applicable in web). I imagine having the setting work uniformly across desktop and web may be a bit more challenging.

**Comment by monokh** [comment] 2017-12-03 08:52
@IzabellaDK i've just got windows running now and tested zoom. I can to zoom with the following combinations:
Zoom Out (Ctrl -)
Zoom in (Ctrl Shift +)
Can anyone confirm if this works on their side? It's less than ideal but it narrows down the root problem.

**Comment by IzabellaDK** [comment] 2017-12-03 10:00
Does not work in this build of W10: 17046 - which is an rs_prerelease version

**Comment by IzabellaDK** [comment] 2017-12-03 10:19
I only use Riot in desktop versions on Windows, Ubuntu (soon to be changed to another dist) and Android

**Comment by monokh** [comment] 2017-12-03 11:52
I've also tested this on ubuntu now and the same shortcuts as windows apply:
Zoom Out (Ctrl -)
Zoom In (Ctrl Shift +)
In windows, this is displayed in the menu accordingly as well (Alt + view). Do you see these shortcuts in your version of windows? 

If the issue is with very specific versions of OS, it is highly likely an issue in electron and should be fixed there. The zooming feature works pretty well from what I've tested and I think introducing an option for zoom separately that works across devices and versions will be more difficult and less maintainable compared to keeping up with the electron implementation of this.

I have a fix for changing the Zoom In shortcut to <Ctrl +> on windows and ubuntu, let me know if this would help.

**Comment by IzabellaDK** [comment] 2017-12-03 12:20
It works now when using the keys on keyboard - not the numbers part. 

So from here I would call this problem solved: **Thank you very much!!**

**Comment by t3chguy** [comment] 2017-12-03 16:14
The app (and site) still needs a font control setting, to be user friendly

**Comment by monokh** [comment] 2017-12-05 23:12
@t3chguy made an initial stab at implementing the setting :) will refine it soon. Let me know if any concerns

**Comment by monokh** [comment] 2017-12-14 17:42
The pull request open (https://github.com/matrix-org/matrix-react-sdk/pull/1651) for adding this setting is ready now. Let me know if something different/more advanced is needed.

**Comment by uhoreg** [comment] 2018-04-13 19:28
I just [found out](https://www.reddit.com/r/kde/comments/3s2qbn/how_does_the_display_setting_screen_scaling_work/cwucu18/) that you can start the desktop app with `--force-device-scale-factor={decimal}` (where `{decimal}' is a decimal number) to scale things.  Obviously, this isn't a replacement for a proper UI, but maybe can help some people until it is fixed.

**Comment by aienabled** [comment] 2018-07-28 16:58
I'm using Telegram with 200% scale on my 4K screen but it's too small.
`--force-device-scale-factor={decimal}` doesn't work to me anymore as well as Ctrl+Plus shortcut... it's really frustrating to use now, especially in comparison to other chat apps I'm using.

**Comment by aaronraimist** [comment] 2018-10-28 16:39
It seems like in v0.17.0 (haven't tested earlier versions) zooming out and resetting the room (ctrl +0) are hooked up but not zooming in.

**Comment by pavi** [comment] 2018-10-28 16:52
In the **new design** will there be option to scale up the interface. It would be nice to have the scaling implemented like in telegram where the whole interface scales up organically. If this is left up to the browser the browser can scale as it likes without much control.  

The example of such scaling option is given above at https://github.com/vector-im/riot-web/issues/3160#issuecomment-316148333

**Comment by rubo77** [comment] 2018-11-10 10:40
On Ubuntu 18.04 with riot-web 0.17.0 the zoom factor is remembered well.

If you don't find the zoom, press ALT once and you get the menu on top which has View->Zoom in and out

You can also zoom via shortcuts:

- CTRL SHIFT +  : zoom in
- CTRL - : zoom out

(This seems a bug, because the menu sais CTRL +)

A sentence in the settings 

    Use CTRL + and - keyt to zoom

would be great thoug!

**Comment by t3chguy** [comment] 2018-11-10 11:52
@rubo77 yes but typically the =+ key requires the shift modifier to be + as opposed to =

**Comment by rubo77** [comment] 2018-11-13 19:30
In the german QWERTZ Keyboard layout the + key is reacheable without SHIFT, so this IS a bug!

**Comment by t3chguy** [comment] 2018-11-13 19:36
This is an electron bug then as it is what adds that behaviour

**Comment by rubo77** [comment] 2018-11-13 22:38
So #7696 was not the right place to post this?

**Comment by kascana** [comment] 2019-01-05 14:34
As other users have suggested above, it would be much more user-friendly to have the ability to change the font size easily. Users with poorer eyesight and particularly elder people would have difficulties to modify the font size, if this setting is hard to find and not directly visible. Ctrl+/- is helpful for scaling the fonts and icons, but in my opinion it will be much better to have the option to increase and decrease the font size internally. I appeal to have the possibility to change the font size and also to select a dark or bright theme directly from the main panel, preferably by just one click. A nice solution would be to have a slider or a dedicated icon in the top right corner with a functionality similar to the one visible in the following image:
![ereader prestigio style settings](https://user-images.githubusercontent.com/921607/50725392-3a284a00-10fd-11e9-9249-f0ae5655d891.png)

**Comment by pravi** [comment] 2019-02-06 06:32
I opened #8416 as it was working earlier but stopped working now.

**Comment by davidbarratt** [comment] 2019-02-22 18:13
[Atom ](https://atom.io/) allows you to zoom the entire interface (just like the browser) and that works well, so I'd like something like that.

**Comment by kascana** [comment] 2019-02-22 18:28
The point is not to zoom the entire interface, but only to increase or decrease easily the font size of the written messages. The issue is even bigger for people using various scripts (other than Latin), when it can be desirable to have a bigger or smaller font size. Any e-book reader and text-orientated program has this basic functionality. I can only hope that in the interest of many users this will be implemented soon. Of course, zooming the entire intefcace with ctrl +/- should work as well, but this is a different matter.

**Comment by aaronraimist** [comment] 2019-02-22 18:29
(@davidbarratt @kascana zooming the entire interface with ctrl +/- should work, if it doesn't file a separate issue)

**Comment by davidbarratt** [comment] 2019-02-22 18:34
> (@davidbarratt @kascana zooming the entire interface with ctrl +/- should work, if it doesn't file a separate issue)

It does not work. :(

**Comment by kascana** [comment] 2019-02-22 18:40
> > (@davidbarratt @kascana zooming the entire interface with ctrl +/- should work, if it doesn't file a separate issue)
> 
> It does not work. :(

It does work on a Windows desktop riot version (at least), but I don't see how one can easily modify the font size without changing the entire interface. This is in my view a big must in programs like this.

**Comment by aaronraimist** [comment] 2019-02-22 18:42
@kascana yes that is what this issue is for

@davidbarratt please file a separate issue

**Comment by d2dyno** [comment] 2019-05-03 20:37
Looking forward to this, and also experiencing #9533

**Comment by PeterKassab** [comment] 2019-05-15 10:34
It would be great to have this option, this option is present in most development tools. Just like the Dark theme.

**Comment by PeterKassab** [comment] 2019-05-15 10:36
Hey guys, this option already exists, try View + Zoom in or Ctrl + =

Good work.

**Comment by t3chguy** [comment] 2019-05-15 10:38
That's zoom, changes the scale of everything, not just the font

**Comment by kascana** [comment] 2019-05-15 22:10
Indeed, Ctrl +/- scales everything and is not always a practical solution, especially when someone is using different scripts/languages for writing messages. It would be much better to be able to modify the size of the text indepentently of the interface. I can only refer one more time to my suggestion and the attached example from January 5. Is it so difficult to implement such a basic functionality?

**Comment by PeterKassab** [comment] 2019-05-15 22:21
Yes i got it, it would be a nice option.

**Comment by n1trux** [comment] 2019-11-03 19:14
Zooming with Ctrl + plus and minus on the numpad or scrolling the mouse wheel doesn't work, but users probably expect that.

**Comment by brandonkal** [comment] 2020-01-26 06:15
It is the font that is the issue. For example, GitHub uses a font size of 14px. So does Riot, but its chosen font is clearly smaller. Setting it to 15px makes the text height on par with GitHub's. The other issue is the light theme does not have enough contrast. For example, typing "help" in the Riot-bot room returns grey text. This should be black.

It would be nice to see an option to adjust the font in app, but those two tweaks will improve readability immensely.

**Comment by meteorpublish** [comment] 2020-04-16 20:10
If Riot desktop doesn't implement this, I'm gonna switch to Wire!

Oh wait... https://github.com/vector-im/riot-web/issues/3160

**Comment by t3chguy** [comment] 2020-04-16 20:11
https://github.com/matrix-org/matrix-react-sdk/pull/4424

**Closed** 2020-05-20 14:29 UTC
Labels: Community PR, bounty, bounty?, cosmetic, feature, in progress, mozilla, p2, type:electron, ui/ux
