### ISSUE TITLE
Search for something. Resize the window until you collapse the left panel. Re-widen the window. Result: the search is still active but the box is blank

### ISSUE THREAD

**Issue by benparsons** [vector-im/riot-web#8399] opened 2019-02-04 17:52 UTC
- **Browser**: Chrome
 **OS**: macOS

### Description

Search for something. Resize the window until you collapse the left panel. Re-widen the window. Result: the search is still active but the box is blank

![riot-search-bug](https://user-images.githubusercontent.com/1197991/52226638-6f16f080-28a5-11e9-9a2f-b3c93d328d53.gif)

**Comment by benparsons** [comment] 2019-02-04 17:53
Bad gif, my ffmpeg-fu is weak :/

**Comment by bwindels** [comment] 2019-02-04 18:47
Duplicate of #7716

**Closed by bwindels** 2019-02-04 18:47 UTC
Labels: redesign
