### ISSUE TITLE
Unable to remove account when server is offline

### ISSUE THREAD

**Issue by FunkenTom** [vector-im/riot-web#9996] opened 2019-06-09 20:53 UTC
### Description

I'm unable to log out of a dead/offline server.

### Steps to reproduce

- Add Server/Account to Desktop Client
- Turn the Synapse Server offline
- Start the Riot client and try to log out

Describe how what happens differs from what you expected.

Expect to be able to remove an account from a dead/offline server.

![Screenshot from 2019-06-09 21-49-24](https://user-images.githubusercontent.com/49377510/59164108-922a0900-8b00-11e9-94d6-719e8bd998d6.png)

### Version information

- **Platform**:

- **OS**: ElementaryOS
- **Version**: 1.2.1

**Comment by turt2live** [comment] 2019-06-09 21:49
Duplicate of https://github.com/vector-im/riot-web/issues/2289

**Closed by turt2live** 2019-06-09 21:49 UTC
Labels: bug
