### ISSUE TITLE
remove colon after first tab-completed user

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/riot-web#5126] opened 2017-09-26 14:57 UTC
because it's ugly and makes no sense with new tab-completion and with multiple names

![scrot-1506437796](https://user-images.githubusercontent.com/7166727/30867261-26406866-a2e4-11e7-8a40-e88d16d35b67.png)

**Comment by lampholder** [comment] 2017-09-27 13:04
This is a duplicate of https://github.com/vector-im/riot-web/issues/4883

**Closed by lampholder** 2017-09-27 13:04 UTC
Labels: duplicate
