### ISSUE TITLE
Riot Desktop don't apear in system tray after 1.5.15

### ISSUE THREAD

**Issue by mmmm1998** [vector-im/riot-web#13628] opened 2020-05-11 11:28 UTC
### Description

I have Riot app from package `riot-web`. After upgrade (on 8 May 2020) from 1.5.15 to 1.6.0 (according log, see below) Riot stopped to apears in system tray. I see, that process is still active after closing application and it is correct, because i set option "Go on tray after application close", but the app is missing in system tray.

Attachment 1: part of apt log
````
Start-Date: 2020-05-08  14:05:49
Commandline: apt upgrade
Requested-By: mmmm1998 (1000)
Install: <other packages> riot-desktop:amd64 (1.6.0-1, automatic), <other packages>
Upgrade: <other packagtes> riot-web:amd64 (1.5.15, 1.6.0), <other packages>
End-Date: 2020-05-08  14:09:59
````

Attachment 2: example of present Riot 1.5.15 in system tray (system tray is a right part of panel)
![aCnZ-Vp0lhY](https://user-images.githubusercontent.com/32711843/81556314-c9e5a480-9392-11ea-9055-771117bdeb7c.jpg)

Logs being sent: yes (but I haven't been understand, where they send and how attach them to this bug)

### Version information

- **Platform**: desktop
- **Riot version**: 1.6.0
- **OS**: Ubuntu
- **Version**: 18.04.4 LTS

**Comment by t3chguy** [comment] 2020-05-11 11:37
Duplicate of #12518

**Closed** 2020-05-11 11:37 UTC
Labels: bug
