### ISSUE TITLE
Can't tell who's online on the People list

### ISSUE THREAD

**Issue by iuliuh** [vector-im/riot-web#9999] opened 2019-06-10 09:39 UTC
### Description

I can't tell who's online while looking at the People list

![DeepinScreenshot_select-area_20190610113734](https://user-images.githubusercontent.com/11448193/59184752-7746ab80-8b77-11e9-84fb-fdb247d675b7.png)

although if you look at the discussion group's Members section, i.e.

![DeepinScreenshot_select-area_20190610120323](https://user-images.githubusercontent.com/11448193/59184898-cf7dad80-8b77-11e9-88ba-a9e08a5b380b.png)

you can easily tell who's online and who's not.

Is it possible to make it so it's clear who's online and who's not also by looking at the People's list?

I would expect something like:

![DeepinScreenshot_select-area_20190610113734](https://user-images.githubusercontent.com/11448193/59186887-b0cde580-8b7c-11e9-9020-c59df9d16074.png)

Or maybe gray out the names for the contacts that are offline(or any other UX approach that would clearly suggest the presence status)

### Version information

I tested on Riot Web Desktop client on Ubuntu and the Riot Web inside Firefox 67.0.1 64-bit:

For the desktop app:
- **OS**: Ubuntu 19.04
- **matrix-react-sdk version**: <local>
- **riot-web version**: 1.2.0
- **olm version**: 3.1.0

For the web app:
- **URL**: riot.im/app
- **Browser**: Firefox 67.0.1 64-bit
- **OS**: macOS Sierra 10.12.6
- **matrix-react-sdk version**: <local>
- **riot-web version**: a00bceaff737-react-2e556b7df43c-js-7080458f7eaa
- **olm version**: 3.1.0

- **URL**: riot.im/develop
- **Browser**: Firefox 67.0.1 64-bit
- **OS**: macOS Sierra 10.12.6
- **matrix-react-sdk version**: <local>
- **riot-web version**:  a00bceaff737-react-2e556b7df43c-js-7080458f7eaa
- **olm version**: 3.1.0

**Comment by t3chguy** [comment] 2019-06-10 09:42
Duplicate of https://github.com/vector-im/riot-web/issues/4199

**Closed by t3chguy** 2019-06-10 09:42 UTC
Labels: bug, ui/ux
