### ISSUE TITLE
'Failed to join room' dialog still shows 'CORS request rejected' on timeout

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#7526] opened 2018-10-20 15:32 UTC
which is not the most friendly error message, and they were all supposed to be eradicated. See https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$1540049084858VhyjG:fam-ribbers.com

**Comment by lampholder** [comment] 2018-10-23 15:40
I've added this to the first impressions project, but it's hard to know whether it really qualifies without knowing what triggers it.

Do we have any idea?

**Comment by turt2live** [comment] 2018-11-08 00:17
I'm not able to reproduce this. Was it possibly a legitimate CORS error?

![image](https://user-images.githubusercontent.com/1190097/48169510-de824180-e2b0-11e8-8b80-20fd68070765.png)

(although the error still isn't great)

**Comment by turt2live** [comment] 2018-11-08 23:12
... and of course now I've managed to reproduce it. It happens at least when the connection is reset from under the client.

**Comment by tya99** [comment] 2018-11-26 02:34
I am able to reproduce and willing to help however I can.

**Comment by turt2live** [comment] 2018-11-26 02:38
Exact and specific steps including the error code would be hugely appreciated.

**Comment by tya99** [comment] 2018-11-26 02:44
Sure.

I was able to reproduce this with

* [riot-web](https://riot.im/app) in Firefox
* [riot-desktop](https://www.archlinux.org/packages/community/any/riot-desktop/) (Electron desktop client)

Then either type /join #matrix:matrix.org or click on "Matrix HQ" from the Home screen.

When clicking on "Matrix HQ" from the Home screen I am able to see other people joining and leaving and typing messages.

Otherwise all that seems to happen is the "Joining room..." status and the spinning loading icon stay there.

**Comment by turt2live** [comment] 2018-11-26 02:58
`ERR_NETWORK_CHANGED` is not really something we can really do anything about, and it looks like your failing request is unrelated to joining a room.

The discussion about `ERR_NETWORK_CHANGED` is best held elsewhere (new issue if one doesn't already exist), however for the sake of providing a quick answer: if you're seeing it often, check your proxy settings, VPN software, and network connection stability. Sometimes VPN software can interfere with the connection and cause `ERR_NETWORK_CHANGED` errors due to rapidly trying to establish a connection with whatever endpoint. The same can apply on unstable networks where things like physical issues with the network and routing problems cause some operating systems to change between network devices rapidly.

**Comment by tya99** [comment] 2018-11-26 03:03
Right. I am on a VPN. I do agree that it's probably not related to why I am unable to join Matrix HQ. The VPN is OpenVPN and it's [running on the router](https://wiki.alpinelinux.org/wiki/Linux_Router_with_VPN_on_a_Raspberry_Pi_(IPv6)). All traffic goes into the VPN because of the VLAN that I am on - those routing decisions are made by the router.

I should also mention every other room seems to work but #matrix

**Comment by turt2live** [comment] 2018-11-26 03:11
Honestly this sounds like a great thing to discuss in [#riot:matrix.org](https://matrix.to/#/#riot:matrix.org) as it seems like a problem on your end, not so much with the client. I see that there's a related issue (https://github.com/vector-im/riot-web/issues/7745) which is probably the place to keep discussion about the top-level issue of not being able to join HQ for unknown reasons.

**Comment by tya99** [comment] 2018-11-26 09:00
So I ruled out the network errors as being related to this problem.

* Direct connection (VLAN2) via Ethernet
* VPN tunnel (VLAN3) via Ethernet
* To nearest LTE tower via tethered phone
* On a different computer

As soon as I tried with a different account it worked. It turned out that the server still thought I was in the #matrix:matrix.org room despite it not showing under "Rooms". I think I had joined it in the past and left.

@tulir made a suggestion that seemed to solve the issue for me, send a HTTP POST request to the server forcing a leave. Using the   `"room_id": "!QtykxKocfZaZOUrTwp:matrix.org"` inspected from the raw source option and the access token from user settings I tried this `curl` command.

ie `curl -XPOST 'https://matrix.org/_matrix/client/r0/rooms/!QtykxKocfZaZOUrTwp:matrix.org/leave' -H 'Authorization: Bearer <access token>'

It resulted in people in the room 'seeing me leave' and I was then able to rejoin.

**Comment by lampholder** [comment] 2018-11-30 09:45
Would I be right in saying then that:
- Riot's local state was wrong (thinking the user was not in the room when they were)
- Either:
    - Synapse doesn't handle a user's request to join a room they're already in well, or
    - Riot doesn't handle whatever error response Synapse provides to represent a user is trying to join a room they're already in

My guess would be that a 'clear cache and refresh' on the client would have fixed this, but (if Synapse is providing enough information at least) Riot should be able to recover from this.

**Comment by tya99** [comment] 2018-11-30 13:09
> My guess would be that a 'clear cache and refresh' on the client would have fixed this, but (if Synapse is providing enough information at least) Riot should be able to recover from this.

I forgot to mention during my testing I was noticing this in the electron riot-desktop app. I tried it in my Firefox browser and that didn't fix it either. I also tried it in Firefox from a livecd.

**Comment by turt2live** [comment] 2018-12-05 20:54
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2306 although the real fix would be https://github.com/vector-im/riot-web/issues/7785. We'll use https://github.com/vector-im/riot-web/issues/7785 to track the bad error experience in the app.

**Closed by turt2live** 2018-12-05 20:54 UTC
Labels: bug, major, p1
