### ISSUE TITLE
A way to view the key of a device

### ISSUE THREAD

**Issue by dbkr** [vector-im/riot-web#6955] opened 2018-06-28 10:56 UTC
Currently the only way I can see the key of a device once I've verified it is to unverify it and click the verify button

**Comment by lampholder** [comment] 2018-06-29 07:38
Is this the same usecase as https://github.com/vector-im/riot-web/issues/6095 ?

**Comment by t3chguy** [comment] 2018-06-29 11:30
@lampholder 6095 is seeing all of your own keys easily, this is about seeing a peer's keys after verifying it

**Comment by Mikaela** [comment] 2019-11-27 12:39
Is this a duplicate of https://github.com/vector-im/riot-web/issues/6676 and https://github.com/vector-im/riot-web/issues/2735 ?

**Closed** 2019-11-27 15:59 UTC
Labels: feature, p1, type:e2e
