### ISSUE TITLE
MacOS emoji picker results get mangled for some emojis

### ISSUE THREAD

**Issue by HerrSpace** [vector-im/riot-web#8148] opened 2019-01-16 23:12 UTC
### Description

When trying to insert emojis via the MacOS integrated emoji picker the emojis get sometimes mangled in the text writing area or after sending or both. It depends on the emoji in question.

### Steps to reproduce

Here are some screenshot of the problem:
Case1: Picking the female shrug
<img width="561" alt="screenshot 2019-01-16 at 23 41 50" src="https://user-images.githubusercontent.com/224042/51284451-dc90d900-19eb-11e9-9a58-588cc2b1652f.png">

Case1: It gets put to the text area like this:
<img width="171" alt="screenshot 2019-01-16 at 23 42 13" src="https://user-images.githubusercontent.com/224042/51284450-dc90d900-19eb-11e9-83ff-bd180bdcef5a.png">

Case1: And appear like this after sending:
<img width="159" alt="screenshot 2019-01-16 at 23 42 20" src="https://user-images.githubusercontent.com/224042/51284449-dbf84280-19eb-11e9-88f7-99264b86e5e3.png">

Case2: The fire looks broken in the text area but okay after sending:
<img width="198" alt="screenshot 2019-01-17 at 00 00 49" src="https://user-images.githubusercontent.com/224042/51284448-dbf84280-19eb-11e9-99f2-5ce4dfdc0947.png">
<img width="149" alt="screenshot 2019-01-17 at 00 01 25" src="https://user-images.githubusercontent.com/224042/51284447-dbf84280-19eb-11e9-8fdb-7a4a926789e6.png">

Case3: Some look fine in both:
<img width="142" alt="screenshot 2019-01-17 at 00 09 55" src="https://user-images.githubusercontent.com/224042/51284580-427d6080-19ec-11e9-82ba-992c49388ace.png">
<img width="149" alt="screenshot 2019-01-17 at 00 02 15" src="https://user-images.githubusercontent.com/224042/51284446-dbf84280-19eb-11e9-9854-7a294c5cd294.png">

### Version information

- **Browser**: FF 64.0.2 (64-bit)
- **OS**: macOS 10.14.1 (18B75)
- **URL**: both https://riot.im/experimental and https://riot.im/app

**Comment by turt2live** [comment] 2019-01-16 23:16
Duplicate of https://github.com/vector-im/riot-web/issues/7665

**Closed by turt2live** 2019-01-16 23:16 UTC
