### ISSUE TITLE
Themed title bar in Windows

### ISSUE THREAD

**Issue by Mattwmaster58** [vector-im/riot-web#13659] opened 2020-05-13 16:54 UTC
### Description

Riot could really use a themed title bar to integrate better with Windows. Here's an example of how Discord does it: 
![image](https://user-images.githubusercontent.com/26337069/81841445-b14acb00-9507-11ea-8bfe-51c4d2beb644.png)

And here's how Riot does it right now:
![image](https://user-images.githubusercontent.com/26337069/81841572-e9520e00-9507-11ea-8f4b-f1a5b6b84b4b.png)

For the desktop app this feature is not preset in these versions:

- **OS**: Windows
- **Version**: 1.6.0

**Comment by t3chguy** [comment] 2020-05-13 18:25
Duplicate of https://github.com/vector-im/riot-web/issues/8749

**Closed by t3chguy** 2020-05-13 18:25 UTC
Labels: bug, ui/ux
