### ISSUE TITLE
remove reply when pressing esc

### ISSUE THREAD

**Issue by NotAFile** [vector-im/riot-web#8484] opened 2019-02-08 19:56 UTC
A thing I've gotten really used to in chat apps like telegram is being able to cancel my reply by pressing ESC. This leaves the message in place, but removes the reply. It would be nice if riot supported this.

**Comment by turt2live** [comment] 2019-02-08 21:14
Duplicate of https://github.com/vector-im/riot-web/issues/6818

**Closed by turt2live** 2019-02-08 21:14 UTC
