### ISSUE TITLE
Stickers are broken when zoomed in

### ISSUE THREAD

**Issue by targodan** [vector-im/riot-web#10019] opened 2019-06-11 17:30 UTC
### Description

Stickers are not displayed when in zoomed in mode (Ctrl+'+').
The web request made to the media repo contains floating point values for the width and height, like this: `https://targodan.de/_matrix/media/v1/thumbnail/targodan.de/[redacted]?width=960.0000381469727&height=720.0000286102295`
This trips up TravisR's media-repo (don't know about synapses internal repo), it responds with `{"errcode":"M_UNKNOWN","error":"Width does not appear to be an integer","mr_errcode":"M_UNKNOWN"}`

### Steps to reproduce

To break it:

1. Send a sticker in any chat.
2. Zoom in via Ctrl+'+'
3. Clear cache and reload => stickers are broken

To fix it:

1. Reset zoom via Ctrl+0 (number zero)
2. Clear cache and reload
3. Stickers work again.

Log: not sent   

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows 10 x64
- **Version**: 1.2.1

**Comment by targodan** [comment] 2019-06-11 17:34
PS: Since I can't change font size in riot, zooming is my only way of making it comfortably readable.

**Comment by turt2live** [comment] 2019-06-11 17:40
Duplicate of https://github.com/vector-im/riot-web/issues/9690 - will be fixed in the next release

**Closed by turt2live** 2019-06-11 17:40 UTC
Labels: bug

**Comment by targodan** [comment] 2019-06-11 17:42
Right, didn't see that issue and wasn't aware you were referring to the release beyond 1.2.1 (I kinda missed the 1.2.1 release until today)
