### ISSUE TITLE
Simplify login page and get rid of select menu ("Sign in with: Username/3pids") on login page

### ISSUE THREAD

**Issue by menturion** [vector-im/riot-web#10063] opened 2019-06-15 06:32 UTC
Simplify login page and get rid of select menu ("Sign in with: Username/3pid") on login page.
Parse input value (of ".mx_Field mx_Field_input > input") instead and decide whether it is ...
-- username
-- email
-- phone number

**Comment by jryans** [comment] 2019-06-17 13:14
Thanks for filing! This is a duplicate of https://github.com/vector-im/riot-web/issues/8311.

**Closed by jryans** 2019-06-17 13:14 UTC
Labels: suggestion

**Comment by menturion** [comment] 2019-06-17 13:36
Thanks!
I'm sorry for filing a duplicate.

**Comment by jryans** [comment] 2019-06-17 14:24
No problem at all! The important thing is to know what issues people are facing. 😁
