### ISSUE TITLE
"New Recovery Method" detected when I delete my backup

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#8046] opened 2019-01-07 23:18 UTC
The dialog indicates that a new one was set up for me, not that it was deleted. It should say it was deleted.

**Comment by dbkr** [comment] 2019-01-11 13:32
This now behaves correctly for me: I think it's been fixed in the recent key backup work. Can you retest?

**Comment by jryans** [comment] 2019-01-11 14:31
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2427.

**Closed by jryans** 2019-01-11 14:31 UTC
Labels: bug, major, mvp, p1, type:e2e, ui/ux

**Comment by jryans** [comment] 2019-01-11 14:40
> It was, in fact, specifically fixed, but not removed from the backlog board.

We seem to all have a different process for when to remove things from the backlog board, so maybe we should settle on a common approach for less confusion... I have observed:

* @dbkr removes them as soon as they go to Workflow
* I have been archiving when the issue is closed 
* @bwindels I think doesn't remove them at all but instead filters the board by `is:open`
