### ISSUE TITLE
Can't Delete Existing Widgets

### ISSUE THREAD

**Issue by jph168** [vector-im/riot-web#9827] opened 2019-05-23 17:48 UTC
Update: Had to Manually Clear Cache and Reload under help and About, fixed it(for my Client). Other Friends still had the widget till they also Cleared Cache and Reloaded. Restarting the Desktop Client doesn't automatically refresh this.
### Description

Widget disappears as it would being deleted, error message appears, then widget comes back. 
For a workaround I deleted the room and made another. The only thing is I've managed to recreate this Issue again. 

### Steps to reproduce

- Adding/Deleting (Modified?) Widgets

Log: sent/not sent?Debug Logs are sent, made the issue reoccur multiple times in the Client to make sure its in the Debug Logs before I sent them.    
![Failed to Remove widget](https://user-images.githubusercontent.com/31376624/58274703-40376400-7d48-11e9-9a30-c91893ecfb21.png)

### Version information

- **Platform**: Desktop 

For the web app: Not Affected.

For the desktop app:

- **OS**: Linux
- **Version**: 1.1.2-1

**Comment by jryans** [comment] 2019-05-24 09:30
Flagging for @jaywink to investigate.

**Comment by jaywink** [comment] 2019-05-28 07:11
Relevant parts of the log:

```
2019-05-23T17:33:43.340Z E Failed to delete widget Timed out waiting for widget ID youtube_%40xxxxxxxxxxxxxxxx%3Amatrix.org_1558235511345 to appear
Error: Timed out waiting for widget ID youtube_%40xxxxxxxxxxxxx%3Amatrix.org_1558235511345 to appear
    at vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:23:65689
From previous event:
    at R.U [as _captureStackTrace] (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:1:27587)
    at R._then (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:1:53198)
    at R.then (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:1:51554)
    at Function.value (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:23:66641)
    at onFinished (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:63:52785)
    at Object.l [as onFinished] (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:1:149662)
    at t.onOk (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:30:40253)
    at Object.o (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:46:425216)
    at s (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:46:423417)
    at Object.executeDispatchesInOrder (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:46:424146)
    at f (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:30:55998)
    at p (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:30:56124)
    at Array.forEach (<anonymous>)
    at e.exports (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:63:98369)
    at Object.processEventQueue (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:30:57516)
    at vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:73:37497
    at Object.handleTopLevel [as _handleTopLevel] (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:73:37519)
    at p (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:73:58580)
    at u.perform (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:46:20749)
    at Object.batchedUpdates (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:63:113464)
    at Object.batchedUpdates (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:23:56495)
    at dispatchEvent (vector://vector/webapp/bundles/8090f6060e50e2366e06/bundle.js:73:59361)
2019-05-23T17:33:43.341Z I Starting load of AsyncWrapper for modal
2019-05-23T17:33:43.538Z W Adding fromWidget messaging endpoint for youtube_%40xxxxxxxxxxx%3Amatrix.org_1558235511345 {"widgetId":"youtube_%40xxxxxxxxxxxx%3Amatrix.org_1558235511345","endpointUrl":"https://scalar.vector.im"}
2019-05-23T17:33:43.538Z W Requesting capabilities for youtube_%40xxxxxxxxxxxxxxxx%3Amatrix.org_1558235511345
2019-05-23T17:33:43.541Z W Got capabilities for youtube_%40xxxxxxxxxxxxxxx%3Amatrix.org_1558235511345 []
2019-05-23T17:33:43.541Z I Widget youtube_%40xxxxxxxxxxxxxxxxxxxxxxxx%3Amatrix.org_1558235511345 requested capabilities: 
2019-05-23T17:33:44.005Z W Widget reported content loaded for youtube_@xxxxxxxxxxxxxxxxx:matrix.org_1558235511345
```

There is also a probably not related 502:

    2019-05-23T17:34:55.155Z E Failed to get URL preview: Error: Server returned 502 error

The 502 is possibly an indication of a wider problem with the HS. Widgets are stored in room state. The [spec](https://docs.google.com/document/d/1re56Br1wd4Tcw6j4ptZk3lMRmSbVbXb2lAzkudwnPvc/edit#heading=h.wo8p6jsd5hyv) indicates widgets are removed by sending a new event with the `url` set to empty, which tells clients to ignore the widget. 

It looks like the widget delete calls `WidgetUtils.setRoomWidget` (https://github.com/matrix-org/matrix-react-sdk/blob/51750cf153561b1aa9761cbcf2ca2c0b5cbfaa7a/src/components/views/elements/AppTile.js#L307) which then does a `client.sendStateEvent` which fails in timeout (https://github.com/matrix-org/matrix-react-sdk/blob/2dcb40f1be6a90b628a84581f838a012821547f6/src/utils/WidgetUtils.js#L285). 

So something related to matrix.org server misbehaving at the time or something related to room state corruption client side? This seems maybe likely since the OP mentions issue was fixed by clearing client cache. Removing Scalar label anyway as Scalar is not involved with Room based widgets except to offer a "shop" for them.

**Comment by jph168** [comment] 2019-05-30 00:01
room state corruption client side? I believe so it's just how it is happening between multiple User Clients. Is it possible Local Client Cache is suppose to sync with the Server Side?

**Comment by turt2live** [comment] 2020-04-03 21:30
This is a duplicate of https://github.com/vector-im/riot-web/issues/12941

Closing in favour of that issue as it's more tightly scoped on information.

**Closed by turt2live** 2020-04-03 21:30 UTC
Labels: bug, defect, type:widgets
