### ISSUE TITLE
Clicking invite in the memberlist for a left user fails with 'userId is not defined'

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#8773] opened 2019-02-18 23:07 UTC
Although, the invite still works. https://matrix.half-shot.uk/_matrix/media/v1/download/half-shot.uk/a6a3c4232d26f9f76fce98d79d58abe8

**Comment by turt2live** [comment] 2019-02-19 04:25
Duplicate of https://github.com/vector-im/riot-web/issues/7986

**Closed by turt2live** 2019-02-19 04:25 UTC
