### ISSUE TITLE
Stop-the-world saves becoming more noticeable

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3538] opened 2017-03-29 21:54 UTC
### Description

Just over a month ago the IndexedDB stuff was pushed and the stop-the-world saving effect was quite noticeable. It was later fixed by https://github.com/matrix-org/matrix-js-sdk/commit/d23d5b50a37ae2f7c3ec78c2901f9ff4fecd925d however it appears as though the issue has returned.

For background: I'm in quite a few rooms. Not as many as some, but in quite a lot either way. I've been using riot.im/develop exclusively for chat and see a fair amount of traffic come to my client.

When https://github.com/matrix-org/matrix-js-sdk/commit/d23d5b50a37ae2f7c3ec78c2901f9ff4fecd925d was implemented, the "stop the world" effect diminished significantly to have Riot be more usable, however as time has progressed, I'm seeing **3-7 second delays** each time a save occurs. This locks up the UI thread annoyingly and has me waiting to see what I typed so I can continue what I was doing. 

*I was unable to find the original issue that brought up the stalling effect previously, apologies if it exists somewhere and is still open*

### Steps to reproduce

- Be in a lot of rooms and use /develop
- Wait for a save

I would expect the saves not be noticed by the user. Granted, this is a hard issue to solve because saving is a necessary action, however it stalling for several seconds is incredibly annoying.

Log: not sent (unable)    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 56
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment] 2017-03-30 09:42
Could be related to #3252 which is currently under investigation.

**Comment by Kegsay** [comment] 2017-03-30 10:09
@turt2live can you please verify that the stop the world pause is in fact caused by the indexeddb stuff? You can verify this by checking the JS console when it stops the world - there will be line about it "persisting sync data". If you can confirm that the pauses *only* happen then, then that will help us greatly. Thanks.

**Comment by turt2live** [comment] 2017-03-30 14:29
@Kegsay I can confirm it prints 'Persisting data' then locks up.

**Comment by lampholder** [comment] 2017-04-03 08:39
In which case this looks like a duplicate of #3252, so I'll close this one and we can track progress there. Thanks all :)

**Closed by lampholder** 2017-04-03 08:39 UTC
Labels: bug, p1, performance, regression
