### ISSUE TITLE
Disarm warning in encrypted Rooms

### ISSUE THREAD

**Issue by martinberg212** [vector-im/riot-web#10381] opened 2019-07-21 21:00 UTC
### Description

When using rooms with more then a handful of people, encryption is basically unuseable due to constant warnings about new unknown devices.

![riot](https://user-images.githubusercontent.com/51055896/61596836-d7b21980-ac08-11e9-8a70-882a63da422f.PNG)

This warning is generally a good idea but it should be possible to disable it or make it less drastic.

### Steps to reproduce

1. Create a room
2. enable encryption
3. have a new user join the room
4. send a message
5. warning will appear and prevent message from being sent
6. users have to verify the new device to continue

Describe how what happens differs from what you expected.

The steps above have to be repeated for each new user.
If I want to create a chat room for my local knitting club I cannot expect the users to repeat each of the above steps for e.g. 30 users.

This is very bad useability and the very reason people will instead just keep using whatsapp or discord...

The only way to use riot/matrix with a larger number of participants is to disable room encryption, which should not be necessary. Looking at the existing rooms on matrix, this is actually the case, meaning the state of communication security with riot/matrix isn't any higher than that of telegram, which has been critiszied a lot for this.

Please consider an option to disable or disarm those warnings.
Signal shows the way in this regard without compromising security or usability

### Version information

Windows 7, Riot 1.3.0

**Comment by jryans** [comment] 2019-07-22 12:46
Thanks for the feedback! We're quite aware that the current experience is not ideal for large rooms, less technical users, etc.

We plan to improve the experience through cross-signing so that you can verify a user once instead of each of their N devices.

Since I believe this feedback is effectively the same as https://github.com/vector-im/riot-web/issues/9245, I'll close this.

Duplicate of https://github.com/vector-im/riot-web/issues/9245

**Closed by jryans** 2019-07-22 12:46 UTC
Labels: bug, ui/ux
