### ISSUE TITLE
Leftbar (Chatlist, Roomlist) sindle scrool view

### ISSUE THREAD

**Issue by toger5** [vector-im/riot-web#10432] opened 2019-07-27 17:26 UTC
### Description
The left bar can make it hard to find the room you are searching for beacuse the categories have individual scroll views. sometimes rooms from my favorites are hidden. And i am searching the ppls list to find out that they are just behind the scroll view. 
I prefer the solution how fractal handles the categories. I would highly appreciate if it could become an option that all the rooms are in just one scroll view.
@bwindels

**Comment by t3chguy** [comment] 2019-07-29 12:28
Duplicate of https://github.com/vector-im/riot-web/issues/3824

**Closed by t3chguy** 2019-07-29 12:28 UTC
Labels: bug, ui/ux

**Comment by toger5** [comment] 2019-07-30 01:39
sorry for not finding it (used different words to search for it.) Ty!!!
