### ISSUE TITLE
Your Riot is misconfigured Invalid homeserver discovery response

### ISSUE THREAD

**Issue by student-sx** [vector-im/riot-web#13036] opened 2020-04-05 21:26 UTC
### Description

When I start riot-web I get the following error message:

![Error](https://user-images.githubusercontent.com/18629143/78510079-fb1af580-7792-11ea-917a-fbcf4cda0451.png)

### Steps to reproduce

Install riot on ubuntu 19.04 following the instructions on https://riot.im/download/desktop/ 
(using xmonad as window manager).

Then start `riot-web` from command line and get the error message above.

**Comment by PipsqueakH** [comment] 2020-04-06 03:35
same on manjaro, and the problem is it seems that there is nowhere to configure the homeserver?

**Comment by dbkr** [comment] 2020-04-06 13:02
Check you can reach matrix.org: https://github.com/vector-im/riot-web/issues/11154 means that this is the error you get if the default homeserver is inaccessible.

**Comment by kortschak** [comment] 2020-04-14 11:28
matrix.org appears to be unreachable right now (as does vector.im) (tinfoil hat time).

**Comment by 5p4r70n** [comment] 2020-04-14 12:36
i can access matrix.org but my riot desktop clint shows //Your Riot is misconfigured
Invalid homeserver discovery response // this

**Comment by Krysme** [comment] 2020-05-07 09:54
This is a serious problem for users in China, since the official server is blocked by the GFW, but my homeserver isn't. I was planning to set the server after the software has been launched, but the software is blocked at startup.

**Comment by turt2live** [comment] 2020-05-07 16:26
This sounds like a duplicate of https://github.com/vector-im/riot-web/issues/11154

**Closed by turt2live** 2020-05-07 16:26 UTC
Labels: bug
