### ISSUE TITLE
Missing encryption icons in room list after upgrading to Element

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/riot-web#14616] opened 2020-07-18 12:44 UTC
![2020-07-18-144151_51x78_scrot](https://user-images.githubusercontent.com/43568459/87852745-0b4f7e80-c905-11ea-8589-df03da13b298.png)

In Riot it used to show that the room is encrypted and that everyone is verified in the room. I could probably get a screenshot of that one, too, if necessary.

### Version information

- **OS**: Arch Linux
- **Version**: 1.7.1 (element-desktop)

**Comment by t3chguy** [comment] 2020-07-18 12:46
> In Riot it used to show that the room is encrypted and that everyone is verified in the room. 

Yup but design moved that to only be when you are in the room. Both in the header and composer.

![image](https://user-images.githubusercontent.com/2403652/87852815-16061580-c8fd-11ea-98f6-8215888d7ecb.png)


Globe icons only show up on `Public` rooms

![image](https://user-images.githubusercontent.com/2403652/87852818-1f8f7d80-c8fd-11ea-925b-136a91b9be6e.png)

**Comment by odiferousmint** [comment] 2020-07-18 12:50
Oh I see. I liked having those icons because it was easier to mentally filter that way. Thank you for the reply. :)

**Comment by t3chguy** [comment] 2020-07-18 12:51
Is this an issue for you asking Design to reconsider that choice?

**Comment by odiferousmint** [comment] 2020-07-18 12:56
Yes, I would like to have this reconsidered. Could have an option similarly to "Always show encryption icons" if one wishes. Those globe icons made me filter them out easier. An example: I had a couple of rooms where I was planning to have everyone verified, so I could easily see which ones required that. Now I would have to go through them one by one. :/

**Comment by turt2live** [comment] 2020-07-18 16:23
The encryption icon representation is not complete yet, and is not addressed by the room list.

**Closed by turt2live** 2020-07-18 16:23 UTC
Labels: bug, needs-design, type:new-room-list, ui/ux

**Comment by odiferousmint** [comment] 2020-07-20 02:19
> and is not addressed by the room list

What do you mean by that? Are those globe icons going to be brought back or not? Is it going to be at the very least considered?

**Comment by t3chguy** [comment] 2020-07-20 09:29
The encryption icons in the room list were removed by design intentionally and are not coming back due to adding visual noise.
