### ISSUE TITLE
Mute person in channel, cannot unmute them without closing and reopening their user settings

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#5908] opened 2018-01-03 05:59 UTC
Testing muting someone in channel (text), by clicking on their profile in the right pane. I hit "mute", text goes white. But then I hit "mute" again, and it does non unmute them.

I have to click on the "X" to close the user settings, and click on the user again, to then see "unmute", and click on that to unmute them.

Again does not update the text to "mute" again, so to toggle this setting, back and forth, requires closing and reopening the user settings each time.

**Comment by turt2live** [comment] 2018-01-03 07:36
This is probably a duplicate of https://github.com/vector-im/riot-web/issues/1185 although in a roundabout way.

**Comment by BloodyIron** [comment] 2018-01-03 18:37
Yeah they may be related, I am unsure.

**Comment by t3chguy** [comment] 2018-01-03 22:26
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/1679

**Comment by BloodyIron** [comment] 2018-01-03 22:34
Nice! Good to know! I take it that'll get baked into main at some point soon-ish or something? ;)

**Comment by t3chguy** [comment] 2018-01-03 22:41
into main, it has yet to land in /develop

**Comment by BloodyIron** [comment] 2018-01-03 22:42
Ahh, well, all in good time I suppose then. Not a breaker for me right now, just wanted to pass along what I saw. :)

**Closed** 2019-12-17 12:07 UTC
Labels: bug, major, p2, ui/ux

**Comment by BloodyIron** [comment] 2019-12-17 18:00
Closed? fixed? I haven't checked recently.

**Comment by t3chguy** [comment] 2019-12-17 18:16
Definitely fixed in UserInfo which is behind a flag in riot.im/develop
