### ISSUE TITLE
Catastrophical break after out of space event on Linux.

### ISSUE THREAD

**Issue by cloudyfuel** [vector-im/riot-web#13402] opened 2020-04-27 16:41 UTC
### Description

After filling disk space Riot shows UTDs, restarting it shows an in-app white background error asking to re-login, clicking on the white space bypasses it and completely breaks Riot in a non-obvious way - every E2EE message is UTD, all devices are not trusted, other devices see a new device, but keys cannot be fetched from them nor any message can be received despite devices being trusted.

This is a completely terrible UX which is not straightforwardly fixable. Meanwhile precisely all other apps on my desktop work as usual, not a tiniest hiccup.

// Also, when I sent a message, I've seen a prompt telling me that devices aren't verified, when clicking the verify button, nothing happens, because the verification dialog shows *underneath* the prompt.

### Steps to reproduce

Fill disk space while Riot is running.

### Version information

- **Platform**: web desktop

For the desktop app:

- **OS**: Debian GNOME
- **Version**: current

**Comment by turt2live** [comment] 2020-04-27 17:01
Duplicate of https://github.com/vector-im/riot-web/issues/9108
Duplicate of https://github.com/vector-im/riot-web/issues/10948
Duplicate of https://github.com/vector-im/riot-web/issues/10891
Duplicate of https://github.com/vector-im/riot-web/issues/4014

There's nothing we can really do about browsers (because we're electron-based) evicting storage from under us.

**Closed by turt2live** 2020-04-27 17:01 UTC
