### ISSUE TITLE
I hate new contacts layout!

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#14563] opened 2020-07-16 23:24 UTC
1. It wastes space:
![image](https://user-images.githubusercontent.com/14617699/87731797-fd4e1080-c7d3-11ea-8f54-c09d59d98b55.png)

2. While before it was possible to see top 20 people and top 10 rooms and independently scroll them; now the all them has the common scrollbar and I need to collapse-expand them each time.

**Comment by turt2live** [comment] 2020-07-17 00:23
Wasting space is a thing you can solve with resizing or showing more rooms.

As for the rest: Duplicate of https://github.com/vector-im/riot-web/issues/14538

This is also a room list, not anything to do with contacts.

**Closed by turt2live** 2020-07-17 00:23 UTC
Labels: bug, ui/ux
