### ISSUE TITLE
Windows taskbar icon doesn't update when the application is backgrounded

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#13643] opened 2020-05-12 16:23 UTC
the taskbar icon flashes orange when needed (but doesn't stop when the notification is read - a different issue), however the count only updates if the application is in focus

**Comment by t3chguy** [comment] 2020-05-12 16:31
Duplicate of https://github.com/vector-im/riot-web/issues/13035

**Closed by t3chguy** 2020-05-12 16:31 UTC
