### ISSUE TITLE
Reaction count only updates on hover

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-web#9820] opened 2019-05-23 10:52 UTC
If someone updates the count for a given reaction for a given message by clicking on a reaction, others can only see the updated count when placing the mouse cursor over the reaction under the message

In action (cursor isn't captured but stuff happens once my cursor gets over the reaction; the second :gb: reaction happened before as I could see it with the "Show hidden events in timeline" labs feature):

![Peek 2019-05-23 11-46](https://user-images.githubusercontent.com/5547783/58247045-9b6d5480-7d50-11e9-86da-86ed79b26f1d.gif)

Got to observe a few of these happening consistently on latest develop.

**Comment by jryans** [comment] 2019-06-07 14:45
Duplicate of https://github.com/vector-im/riot-web/issues/9954. Fixed on develop.

**Closed by jryans** 2019-06-07 14:45 UTC
Labels: bug, defect, feature:aggregations, feature:reactions, p2
