### ISSUE TITLE
While typing, a dialog box popped up and I hit space and it immediately did... something.

### ISSUE THREAD

**Issue by tomrittervg** [vector-im/riot-web#12007] opened 2020-01-22 18:52 UTC
### Description

While typing in a channel, someone sent me the crypto device verification request.  I happened to hit space which immediately dismissed the box before I could see what it was.

Describe how what happens differs from what you expected.

I would expect that a dialog box reject keyboard-based commands within N seconds of open, where N is something like .75 or 1 or something.  This would give the user an opportunity to actually see the dialog box.

### Version information

Desktop macOS, Version 1.5.7 (1.5.7)

**Comment by turt2live** [comment] 2020-01-22 19:00
Duplicate of https://github.com/vector-im/riot-web/issues/8270

**Closed by turt2live** 2020-01-22 19:00 UTC
Labels: bug
