### ISSUE TITLE
When an IS isn't configured, the registration page says that users won't be able to reset their passwords.

### ISSUE THREAD

**Issue by uhoreg** [vector-im/riot-web#11208] opened 2019-10-24 02:42 UTC
It says 'No Identity Server is configured: no email addreses can be added. You will be unable to reset your password.'

**Comment by turt2live** [comment] 2019-10-24 02:51
Duplicate of https://github.com/vector-im/riot-web/issues/11100

**Closed by turt2live** 2019-10-24 02:51 UTC
