### ISSUE TITLE
Enable users to examine debug logs

### ISSUE THREAD

**Issue by kortschak** [vector-im/riot-web#13693] opened 2020-05-16 04:59 UTC
**Is your suggestion related to a problem? Please describe.**
Submitting bugs allows a user to upload the debug log. There is no way for the user to examine the logs from within the application and no clear documentation about the format of the logs for a user to examine them externally. Before submitting logs it would be nice to be able to vet them and would be helpful to be able to perform initial debugging research prior to filing an issue.

**Describe the solution you'd like**
Either a log viewer or a log exporter (or both).

**Describe alternatives you've considered**
Spelunking the code to write my own external tool.

**Comment by turt2live** [comment] 2020-05-16 06:24
Duplicate of https://github.com/vector-im/riot-web/issues/3879

**Closed by turt2live** 2020-05-16 06:24 UTC
Labels: suggestion
