### ISSUE TITLE
Add emoji picker to message composer

### ISSUE THREAD

**Issue by tredondo** [vector-im/riot-web#13391] opened 2020-04-27 04:12 UTC
**Is your suggestion related to a problem? Please describe.**
I'm trying to include emojis in the messages I compose, but the only way to do so is by typing `:` and then trying to guess a matching name. There's no way to visually choose an emoji from the [emoji UI](https://github.com/vector-im/riot-web/issues/1107)

**Describe the solution you'd like**
Include a clickable button to launch the [emoji picker](https://github.com/vector-im/riot-web/issues/1107) from the Message Composer.

**Describe alternatives you've considered**
I'd rather have this emoji picker button replace the stickers button, because I don't use stickers (separate privacy policy, not my style etc.)

**Comment by t3chguy** [comment] 2020-04-27 08:27
Duplicate of the issue you linked... 
Duplicate of https://github.com/vector-im/riot-web/issues/1107

**Closed by t3chguy** 2020-04-27 08:27 UTC
Labels: suggestion
