### ISSUE TITLE
"Empty room" should just say the room mxid instead.

### ISSUE THREAD

**Issue by jevolk** [vector-im/riot-web#6297] opened 2018-03-11 16:22 UTC
The phrase "Empty room" appears in the rooms list as a fallback when the app lacks enough state to say anything else. It would be better if the room's mxid was used instead, preferably in a monospace font to convey a more technical fall-backy meaning; also truncated if it overflows.

By showing the MXID, the user can differentiate between different otherwise identically appearing "Empty room"'s in addition to knowing the domain affixed to the MXID.

If this is too technical for default behavior consider a UI setting.

**Comment by lampholder** [comment] 2018-03-13 16:21
At the moment we have a 'hard rule' (not always honoured, but only in error) that we never display the matrix room id in the UX.

We might be able to in preference explore replacing 'Empty Room' with whatever state we _do_ have (e.g. Empty Room (formerly chat with Bob, Alice and 4 more)).

**Comment by turt2live** [comment] 2018-03-13 16:24
If the preference is "Empty Room (was So and So)", this becomes a duplicate of https://github.com/vector-im/riot-web/issues/396

**Comment by jevolk** [comment] 2018-03-13 16:41
> We might be able to in preference explore replacing 'Empty Room' with whatever state we do have (e.g. Empty Room (formerly chat with Bob, Alice and 4 more)).

Okay, but if there is nothing else known and there was never anything else known except an MXID: displaying "Empty room" multiple times isn't UX-acceptable.

You might have to bend this rule in that case when no other alternative is available. While that is a corner-case for the ideal end-user experience, it's not at all for developers and bug-reporting; a technical fallback is very useful to them.

**Comment by turt2live** [comment] 2019-02-14 21:08
Closing in favour of #396 as that seems to be what we adopted.

**Closed by turt2live** 2019-02-14 21:08 UTC
Labels: design, feature, p4
