### ISSUE TITLE
there's huge RHS padding on the new DM invite text field

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#12282] opened 2020-02-07 11:21 UTC
which means that if you're zoomed in or on a narrow screen, the mxid wraps mid-string for no obvious reason

**Comment by turt2live** [comment] 2020-02-07 11:53
@ara4n screenshot? The text field is a bit of a lie, but should be fixed properly in the future.

**Comment by turt2live** [comment] 2020-02-27 18:24
Closing - need more information/cannot reproduce.

**Closed by turt2live** 2020-02-27 18:24 UTC
Labels: bug, project:ftue-user-lists

**Comment by ara4n** [comment] 2020-04-07 20:57
please chase me if i miss a notification like this, rather than closing the bug... i can't believe this one has been open since FOSDEM :(

reopened at https://github.com/vector-im/riot-web/issues/13066
