### ISSUE TITLE
Message forwarding needs fixing for redesign

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#10335] opened 2019-07-12 17:39 UTC
Context menu on an event -> forward.

**Comment by richvdh** [comment] 2019-07-12 19:13
s/room/event/ ?

**Comment by turt2live** [comment] 2019-07-12 19:40
technically message, but yes - thanks

**Comment by aaronraimist** [comment] 2019-07-16 21:24
Related/dup: https://github.com/vector-im/riot-web/issues/10165

**Comment by jryans** [comment] 2019-07-19 10:43
Yes, I think we can treat this as a duplicate of https://github.com/vector-im/riot-web/issues/10165.

**Closed by jryans** 2019-07-19 10:43 UTC
Labels: feature, needs-design, p2, redesign
