### ISSUE TITLE
Theme defaults white

### ISSUE THREAD

**Issue by NonstickAtom785** [vector-im/riot-web#12467] opened 2020-02-21 19:30 UTC
### Description

Theme keeps defaulting to white for the Chrome App and the online version. 

### Steps to reproduce

- For bugs, list the steps
- that reproduce the bug
- using hyphens as bullet points

I expect to see my theme stay dark but when I open the browser or app it changes back to white. I thought that the user setting were saved. However when you close the app then reopen it then it turns black again. Starting it however just gives it the white theme.

Log: not sent    

### Version information

- **Platform**: Both but on ChromeOS

For the web app:

- **Browser**: Chrome,
- **OS**: ChromeOS
- **URL**: https://riot.im/app

For the desktop app:

- **OS**: ChromeOS
- **Version**: 1.5.10

**Comment by turt2live** [comment] 2020-02-21 20:09
Duplicate of https://github.com/vector-im/riot-web/issues/12308 (will be fixed in the next release)

**Closed by turt2live** 2020-02-21 20:09 UTC
