### ISSUE TITLE
Make it possible to display keys of already verified devices

### ISSUE THREAD

**Issue by Matombo** [vector-im/riot-web#12429] opened 2020-02-20 09:05 UTC
**Is your suggestion related to a problem? Please describe.**
When I verifiy all devices of a person on one of my device and then install Riot on another device, I have to ask the person again for verification for all devices.

**Describe the solution you'd like**
An easy solution would be, when I could display the keys of already verified devices. Then I could use the legacy verification on the new device to verify all devices again without having to re-request them from the other person.

**Describe alternatives you've considered**
An alternative would be cross verification: If the old devices has verified all the devices of another person, and the old and the new devices have verified each other, the new device automatically verifies all devices the old device has verified. (but that's not a part of riot as far as i know and it's already worked on, but the suggestions in this thread would be a easy to implement workaround till then I think)

**Comment by aaronraimist** [comment] 2020-02-21 00:02
Duplicate of #2735, please thumbs up that issue

(Cross signing is coming in the next few weeks which should reduce the need for this but it would still be nice to have)

**Closed by aaronraimist** 2020-02-21 00:02 UTC
Labels: suggestion
