### ISSUE TITLE
Riot is frozen - Lots of Error: live timeline 0 is no longer live

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#9241] opened 2019-03-22 00:11 UTC
### Description

After rageshaking for #8593 Riot completely froze for me. Every animation has stopped. I can still scroll up and load old messages but no buttons work.

Log: sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Firefox 66
- **OS**: macOS
- **URL**: riot.im/develop https://github.com/vector-im/riot-web/commit/8e5147976aba

**Comment by aaronraimist** [comment] 2019-03-22 00:14
Refresh seems to fix it

**Comment by turt2live** [comment] 2019-03-22 00:16
(ftr, [I asked for this to be a new issue](https://github.com/vector-im/riot-web/issues/8593#issuecomment-475448745) to track it as a performance bug. It may ultimately be a duplicate of 8593 - investigation required).

**Comment by turt2live** [comment] 2019-04-16 18:47
Having experienced and investigated, I think this is just a nasty case of https://github.com/vector-im/riot-web/issues/8593 gone wrong. By fixing the bug, we fix this.

**Closed by turt2live** 2019-04-16 18:47 UTC
Labels: bug, critical, p1, performance
