### ISSUE TITLE
widgets frame blends into the bg on dark theme

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#8630] opened 2019-02-14 14:44 UTC
<img width="1206" alt="screenshot 2019-02-14 at 14 44 44" src="https://user-images.githubusercontent.com/1294269/52794126-1f83b200-3067-11e9-8193-4d79fb995985.png">

**Comment by jryans** [comment] 2019-02-14 15:17
Duplicate of https://github.com/vector-im/riot-web/issues/8554#issuecomment-463286392

**Closed by jryans** 2019-02-14 15:17 UTC
