### ISSUE TITLE
Allow disabling link preview before sending message 

### ISSUE THREAD

**Issue by Qwertie-** [vector-im/riot-web#6116] opened 2018-02-10 06:26 UTC
### Description

A helpful feature in Riot would be the ability to remove a link preview before sending a message for example if the preview shows a spoiler or something else that you don't want displayed before someone clicks the link. Some groups on irc and telegram also allow posting links that may not be appropriate to open in all situations as long as the the link preview is deleted and it is mentioned in the message that the link is nsfw. This is currently impossible on Riot.

Telegram has this feature 
![screenshot from 2018-02-10 16-50-36](https://user-images.githubusercontent.com/6601505/36059183-ace9f4c2-0e82-11e8-9db4-501719bd813f.png)
clicking the x in the top right will delete the preview and not show it for other users in the group.

### Version information

- **Platform**: Both

For the web app:

- **Browser**: Applies to all
- **OS**: Applies to all
- **URL**: https://riot.im/app

**Comment by t3chguy** [comment] 2018-02-10 09:38
Duplicate of #5470

**Closed by t3chguy** 2018-02-10 09:38 UTC
