### ISSUE TITLE
[Feature request] Make option in Riot for enable preview of room messages in invite page

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4686] opened 2017-07-27 12:49 UTC
There are large problem with invites that in most cases on new talks - user can't understand who is invite user to chat, because it see only login and name of interlocutor, and that's all.

And for new interlocutor - name and login don't talk anything useful for understanding this.
For understand who is this want to talk with you - you must read first message text.
For read first message, that new user wrote to you - now you must accept invite.
If you accept invite - interlocutor already see agreement and can continue talking.

So in invite page users will reject invites very rarely, because they want to know topic of current discussion before rejecting.

But enabling preview of room without accepting invite got another problem with spammers, that can post spam messages to users on invite step.

For move this problem and solution to user side  - will be good to add option (maybe disabled by default) in Riot `Preview room messages on invite page`, and maybe with selection "for all users / for users from your domain / for users in my contact list". 

For example, Facebook have user option - accept messages from unknown users or disable receive message from not-friends. We can compare Riot invite action with "Add friend" action on Facebook (I don't want to add all users as friends), and "enable preview of room messages" with receive message from not-friend on Facebook (I don't want to disable accepting messages from new unknown people, but I can mark and blacklist spammers).

And maybe will be good to discuss here about other solutions of described problem.

**Comment by lampholder** [comment] 2017-07-28 09:03
This is a really interesting problem; there might be some easy wins (putting the display name of the inviter would be great if it's not there already).

**Comment by turt2live** [comment] 2019-02-15 02:11
Duplicate of https://github.com/vector-im/riot-web/issues/807

**Closed by turt2live** 2019-02-15 02:11 UTC
Labels: feature, p3
