### ISSUE TITLE
Allow for commented uploads

### ISSUE THREAD

**Issue by Biep** [vector-im/riot-web#10084] opened 2019-06-18 07:57 UTC
Often, people want to send a picture with a caption, or to send a file with a note what it is about.  Sending a separate message before or after can be confusing in the case of a string of uploads: does the message refer to the preceding or the following upload.

**Comment by t3chguy** [comment] 2019-06-18 08:39
Duplicate of #1818

**Closed** 2019-06-18 08:39 UTC
