### ISSUE TITLE
side tab opening/closing scrolls message view to bottom

### ISSUE THREAD

**Issue by hramrach** [vector-im/riot-web#11168] opened 2019-10-20 15:52 UTC
### Description

When a side tab is opened/closed message view scrolls to bottom. 

### Steps to reproduce

- Go to a channel with more than one screenful of messages
- Click one of the icons that open a tab located on the top right or a person's avatar

A side tab appears and the message view scrolls to the very bottom. It is very confusing and makes the message view hard to navigate. Especially when you click an avatar picture in the message view you get information on an avatar that scrolls away from your view.

### Version information

- **Platform**: web 
- **Browser**: Chromium 77.0.3865.90
- **OS**: Linux
- **URL**: riot.im/app

**Comment by t3chguy** [comment] 2019-10-20 21:08
Duplicate of https://github.com/vector-im/riot-web/issues/9822

**Closed by t3chguy** 2019-10-20 21:08 UTC
Labels: bug, ui/ux
