### ISSUE TITLE
New room list: Can't expand Low Priority

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#14273] opened 2020-06-30 18:07 UTC
No errors. This happened to me in the demo for System Alerts

**Comment by t3chguy** [comment] 2020-07-06 21:08
Caused by `mx_RoomSublist2_headerContainer_sticky` *sticking* around, cannot repro

**Comment by t3chguy** [comment] 2020-07-06 21:21
Assuming fixed by Bruno's latest patches, re-open if it bites you again!

**Comment by t3chguy** [comment] 2020-07-06 21:24
Travis hit it again

**Comment by t3chguy** [comment] 2020-07-08 19:11
This depends on the sticky behaviour of the bottom-most sublist header; Sticky headers are changing, this is blocked.

**Comment by turt2live** [comment] 2020-07-09 17:07
with the new sticky headers this seems to behave weirdly now: the top sticky header appears to jump-then-expand appropriately but the bottom (often Low Priority) has strange conditions:
* If you're scrolled all the way to the top, it expands (unexpected - should jump first)
* If you're scrolled all the way to the bottom, it expands (expected)
* If you're in the middle, it jumps (expected)
* If you jump, it appropriately expands (expected)

**Comment by t3chguy** [comment] 2020-07-12 08:32
So the issue with this behaviourally is that if you jump/scroll to bottom and then click to expand then it'll be expanded off-screen as we pivot out scroll on the top (natural)

1. jump to Low Priority (bottom sublist) / scroll manually to the bottom
2. click again and see the list expand outside of the scrolled in view
3. scroll down manually to be able to see it

this feels like a painful interaction which would be behaviorally solved if jumping would also expand.

**Comment by t3chguy** [comment] 2020-07-13 14:26
To avoid the above detailed painful interaction, expanding a sublist should additionally scroll it into view

**Closed** 2020-07-13 16:36 UTC
Labels: bug, type:new-room-list
