### ISSUE TITLE
"Seen" notices don't appear next to collapsed joins and quits

### ISSUE THREAD

**Issue by devnoname120** [vector-im/riot-web#4389] opened 2017-06-22 00:50 UTC
### Description

"Seen" notices don't appear next to collapsed joins and quits. It needs to be expanded to appear.

![github 1](https://user-images.githubusercontent.com/2824100/27412503-5f70c684-56f5-11e7-8695-50e45990a360.PNG)
-----------------------
![github 2](https://user-images.githubusercontent.com/2824100/27412505-62862878-56f5-11e7-8755-770b045801c3.PNG)

### Version information

- **Platform**: Desktop
- **OS**: Windows
- **Version**: 0.9.6

**Comment by t3chguy** [comment] 2017-06-22 01:01
Duplicate of #3840

**Closed by t3chguy** 2017-06-22 01:01 UTC

**Comment by justjanne** [comment] 2022-05-11 11:59
It was decided not to support this functionality for the time being. Read receipts for collapsed event summaries will remain the way they currently are.

See https://github.com/matrix-org/matrix-react-sdk/pull/8446#pullrequestreview-967589502 for clarification.
