### ISSUE TITLE
Make the left panel narrower

### ISSUE THREAD

**Issue by rkfg** [vector-im/riot-web#8652] opened 2019-02-14 19:36 UTC
- **Browser**: desktop version (electron)
- **OS**: Debian Testing amd64

### Description

The left panel is too wide and has too much empty space thanks to the plus buttons. I prefer to keep it as narrow as possible but it still doesn't look good. I propose making those (+) buttons hidden so they only appear when you point at the hide/show arrow. Let's be honest, they're used much less often compared to the rooms/people, they don't need to be visible all the time.
![2019-02-14_22-18-32](https://user-images.githubusercontent.com/184066/52812297-31397980-30a8-11e9-9f19-6627778dd142.png)

**Comment by nadonomy** [comment] 2019-02-15 09:38
Dupe of https://github.com/vector-im/riot-web/issues/8507.

**Closed by nadonomy** 2019-02-15 09:38 UTC
Labels: redesign
