### ISSUE TITLE
Command list entries overlapping making text unreadable on small windows

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/riot-web#14120] opened 2020-06-19 22:56 UTC
### Description

When typing `/` in the message box, a command suggestion window opens. If the Riot window is sufficiently small, the text in the command hint box will overlap making it unreadable.

### Steps to reproduce

- Start a message with the `/` character
- Wait for command suggestion menu to appear
- Shrink the main Riot window until text overlaps

The text should wrap as much as possible (without overlapping) and eventually some parts of the suggestion box should disappear like the hint message and then the args.

Logs being sent: no

### Screenshots
- Normal:
![image](https://user-images.githubusercontent.com/37966924/85184340-5daa6a80-b287-11ea-88db-609f9e4548de.png)

- Slightly cramped:
![image](https://user-images.githubusercontent.com/37966924/85184376-8c284580-b287-11ea-83af-393dd861b83e.png)

- Very cramped:
![image](https://user-images.githubusercontent.com/37966924/85184482-d90c1c00-b287-11ea-992f-40728f244f98.png)

- Tiny:
![image](https://user-images.githubusercontent.com/37966924/85184549-03f67000-b288-11ea-9094-7a98ef1e6671.png)

### Version information

- **Platform**: Desktop
- **OS**: Ubuntu 20.04
- **Version**: 1.6.5

**Comment by t3chguy** [comment] 2020-06-19 23:12
Duplicate of https://github.com/vector-im/riot-web/issues/6335

**Closed by t3chguy** 2020-06-19 23:12 UTC
Labels: bug, ui/ux
