### ISSUE TITLE
Built-in option to use proxy

### ISSUE THREAD

**Issue by RiasMo** [vector-im/riot-web#11018] opened 2019-10-01 15:55 UTC
That would be very useful to have some feature when you can turn on the option in your client, fill in the server and the port and your connection will be routed through a desired proxy server.

**Comment by t3chguy** [comment] 2019-10-01 15:59
Duplicate of https://github.com/vector-im/riot-web/issues/3320

**Closed by t3chguy** 2019-10-01 15:59 UTC
Labels: suggestion
