### ISSUE TITLE
Rooms chats dissapear after selecting a Community

### ISSUE THREAD

**Issue by sepu85** [vector-im/riot-web#9858] opened 2019-05-28 09:29 UTC
After seeing the Community feature in my desktop linux app, and clicking on it, I can see only one chat-room (the one belonging to such community) ant the rest of my rooms (that I guess were not tagged to belong to an specific community) dissapeared.

Now, I can't find all (but one) of my chat rooms!

**Comment by jryans** [comment] 2019-05-28 10:16
It's definitely confusing. 😭 To de-select a community and remove the filter, you currently have to click the empty area of the community bar. I believe this is a duplicate of https://github.com/vector-im/riot-web/issues/7953, but please reopen if I misunderstood.

**Closed by jryans** 2019-05-28 10:16 UTC
Labels: bug

**Comment by sepu85** [comment] 2019-05-28 10:40
thanks!! that's working
