### ISSUE TITLE
Be able to edit past messages

### ISSUE THREAD

**Issue by vmassol** [vector-im/riot-web#4300] opened 2017-06-14 08:18 UTC
Hi, right now when I click the up arrow and make a change, a new message is posted. It would really be nice if, instead, the previous message could be modified (as it happens in several other chat tools such as Skype, Slack, etc).

Right now this is the feature we miss the most from skype (yes trying to move away from skype to matrix/riot ;)).

Using "Redact" to remove the message is also not perfect as a workflow.

WDYT?

**Comment by t3chguy** [comment] 2017-06-14 08:31
Duplicate of #1862
but note, it requires protocol/spec changes.

**Closed by t3chguy** 2017-06-14 08:31 UTC

**Comment by vmassol** [comment] 2017-06-14 08:45
Indeed I'm on:

```
matrix-react-sdk version: 0.8.6
vector-web version: unknown
olm version: 2.2.1
```

(not sure why the web version is not specified)

**Comment by vmassol** [comment] 2017-06-14 08:57
Seems related to https://github.com/matrix-org/matrix-react-sdk/pull/588

**Comment by t3chguy** [comment] 2017-06-14 09:06
It is, but `m.room.edit` has not been specced or implemented in the protocol yet, which is why I said
> but note, it requires protocol/spec changes.
