### ISSUE TITLE
read receipts stack on top of each other

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#11385] opened 2019-11-14 16:40 UTC
this is a regression

**Comment by jryans** [comment] 2019-11-14 17:27
Duplicate of https://github.com/vector-im/riot-web/issues/10007 or https://github.com/vector-im/riot-web/issues/9769?

**Comment by turt2live** [comment] 2019-11-14 17:28
This is technically a duplicate of both of those, though since the last release it has gotten significantly worse and happening every time.

**Closed** 2019-11-29 14:41 UTC
Labels: bug, regression, type:readreceipts
