### ISSUE TITLE
Discrepancy of the profile color between PM and other rooms

### ISSUE THREAD

**Issue by devnoname120** [vector-im/riot-web#3436] opened 2017-03-15 09:18 UTC
### Description

Profile color is not consistent.

### Steps to reproduce

- Join a room
- Start a private chat with a user of this room
- The color of the profile looks different in the discussion compared to the one in the left panel

![riot bug](https://cloud.githubusercontent.com/assets/2824100/23941238/5d78b5a6-0968-11e7-8064-ee18213916f3.png)

### Version information

- **Platform**: desktop
- **OS**: Arch Linux
- **Version**:
matrix-react-sdk version: 0.8.4
vector-web version: 0.9.5
olm version: 2.1.0

**Comment by lampholder** [comment] 2017-03-15 16:41
To clarify - are you seeing that the colour of the generic 'room avatar' (to the left of the room name) is different from the colour of the generic user avatar (to the left of the user name in the room members list) when you start a private chat?

If so - I see this too :)

**Comment by devnoname120** [comment] 2017-03-15 17:41
Yes, this is it. :)

**Comment by pafcu** [comment] 2017-12-15 10:13
Duplicate of https://github.com/vector-im/riot-web/issues/2449

**Closed** 2017-12-15 18:11 UTC
Labels: bug, cosmetic, minor, p3
