### ISSUE TITLE
hitting 'send anyway' from UnkDeviceDialog then shows for 'send/cancel' in the statusbar too

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#5152] opened 2017-10-03 11:21 UTC
Presumably because riot wedges whilst it encrypts after hitting 'send anyway', the user is presented with a statusbar warning saying 'some messages are unsendable due to unknown devices - send/cancel?'.  This is horrible because it's stale information, they can't interact with it, and it shouldn't be there at all.  I think the intended behaviour is that the RoomStatus is the primary notification, with the UnkDeviceDialog only shown as a big ugly popup if the user then clicks a 'manage device' option from that prompt - e.g. the status prompt could be: 'Message is queued becaue unknown devices have been added to the room. Click here to manage them, or here to send anyway

**Comment by turt2live** [comment] 2017-10-03 14:54
Duplicate of https://github.com/vector-im/riot-web/issues/3401

**Closed** 2017-10-03 14:55 UTC
