### ISSUE TITLE
Cannot minimize to system tray (Cinnamon, LMDE 3)

### ISSUE THREAD

**Issue by jsbrn** [vector-im/riot-web#13867] opened 2020-05-30 17:41 UTC
### Description

The system tray icon on my desktop disappeared after the most recent update. The settings to allow minimizing to tray and showing the icon do not work as intended. No tray icon appears and closing the window makes it disappear entirely, despite the process still being active.

### Steps to reproduce

- Launch the program while using Cinnamon 4.2.4 and LMDE 3 (Linux kernel 4.9.0-12-amd64)
- Observe the lack of an icon despite the settings allowing for it

Logs being sent: yes

### Version information

- **Platform**: Desktop
- **OS**: Linux Mint Debian Edition 3 (kernel 4.9.0-12-amd64)
- **Version**: riot-web 1.6.2 (olm 3.1.3)

**Comment by t3chguy** [comment] 2020-05-30 18:34
You might have to enable Cinnamon's SNI/libappindicator support.

Duplicate of https://github.com/vector-im/riot-web/issues/12518

**Closed by t3chguy** 2020-05-30 18:34 UTC
Labels: bug
