### ISSUE TITLE
Changing Link Shortening Service

### ISSUE THREAD

**Issue by martindale** [vector-im/riot-web#9057] opened 2019-03-05 23:03 UTC
When changing line 21 of `src/matrix-to.js` in `matrix-react-sdk` to a self-hosted instance, pillboxes in Riot break.  This value should be easily configured, perhaps from `config.json`.

**Comment by turt2live** [comment] 2019-03-05 23:04
Duplicate of https://github.com/vector-im/riot-web/issues/8968

**Comment by t3chguy** [comment] 2019-03-05 23:04
Even if configurable via config.json it'd still break pills, because the pills are based on your selected matrix-to instance.

**Closed by turt2live** 2019-03-05 23:04 UTC
