### ISSUE TITLE
command help menu is unreadable

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#10336] opened 2019-07-13 04:10 UTC
The desktop riot client windows size is 1200x1600

![image](https://user-images.githubusercontent.com/14617699/61166823-095a1f00-a53d-11e9-8d65-366ded0092d8.png)

**Comment by turt2live** [comment] 2019-07-13 04:11
Duplicate of https://github.com/vector-im/riot-web/issues/6335

**Closed by turt2live** 2019-07-13 04:11 UTC
Labels: bug
