### ISSUE TITLE
Start Chat / Invite dialog lets you put in newlines which break things

### ISSUE THREAD

**Issue by Y0ngg4n** [vector-im/riot-web#14376] opened 2020-07-08 06:58 UTC
### Description
 
If i want to add a user to a Room it appears following Error:
`Fehler beim Einladen der folgenden Benutzer: @marcel:oblivioncoding.pro`
this also appears with matrix.org users:
`Fehler beim Einladen der folgenden Benutzer: @y0ngg4n:matrix.org`

In console appears following 502 Error

`index.js:218 GET https://synapse.oblivioncoding.pro/_matrix/client/r0/profile/%40y0ngg4n%3Amatrix.org 502`
Then two warnings:
```rageshake.js:65 Non-fatal error trying to make an invite for a user ID
e.<computed> @ vendors~init.js:2
(anonymous) @ vendors~init.js:2
async function (async)
(anonymous) @ vendors~init.js:2
Promise.then (async)
(anonymous) @ vendors~init.js:2
setTimeout (async)
(anonymous) @ vendors~init.js:2
a @ vendors~init.js:2
p @ vendors~init.js:2
(anonymous) @ vendors~init.js:2
f @ vendors~init.js:2
st @ vendors~init.js:2
rt @ vendors~init.js:2
at @ vendors~init.js:2
pt @ vendors~init.js:2
L @ vendors~init.js:2
G @ vendors~init.js:2
Jt @ vendors~init.js:2
Xt @ vendors~init.js:2
t.unstable_runWithPriority @ vendors~init.js:2
Vr @ vendors~init.js:2
M @ vendors~init.js:2
$t @ vendors~init.js:2
```
```
rageshake.js:65 M_UNKNOWN: Failed to fetch profile
    at https://riot.im/app/bundles/77f1636ec2fbdc83b047/vendors~init.js:2:473607
    at https://riot.im/app/bundles/77f1636ec2fbdc83b047/vendors~init.js:2:473764
    at Object.callback (https://riot.im/app/bundles/77f1636ec2fbdc83b047/vendors~init.js:2:472918)
    at https://riot.im/app/bundles/77f1636ec2fbdc83b047/vendors~init.js:2:20760
    at XMLHttpRequest.r.onreadystatechange (https://riot.im/app/bundles/77f1636ec2fbdc83b047/vendors~init.js:2:20784)
```

My hypothesis is because it tries to request to a url that does not exists.
The Profile URL is `https://synapse.oblivioncoding.pro/_matrix/client/r0/profile/@y0ngg4n:matrix.org`
and not the escaped version of it.
This error does only appear in riot-web on my self hosted instance and on riot.im aswell as the Desktop version of Riot. With the riot.im app and riotx it is working.
I have no tailing in my nginx reverse Proxy proxy pass.
Nginx config:

```
server {

    server_name synapse.oblivioncoding.pro;

    include "/etc/nginx/conf.d/global/listen_https.conf";
    include "/etc/nginx/conf.d/global/oblivioncoding_ssl.conf";
    include "/etc/nginx/conf.d/global/disable_robots.conf";
    include "/etc/nginx/conf.d/global/logs_container.conf";
    include "/etc/nginx/conf.d/global/well_known.conf";

    location /_matrix {
        proxy_pass http://172.19.0.1:45000;
        proxy_set_header X-Forwarded-For $remote_addr;
        client_max_body_size 10M;
    }
}

server {
    listen 8448 ssl default_server;
    listen [::]:8448 ssl default_server;
    server_name oblivioncoding.pro;

    include "/etc/nginx/conf.d/global/oblivioncoding_ssl.conf";
    include "/etc/nginx/conf.d/global/logs_container.conf";

    location / {
        proxy_pass http://172.19.0.1:45000;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}

```

### Steps to reproduce

Method 1:
- Create a new Direct Message Room and Add a User to it
- It will create the room but don´t invite the user.

Method 2:
- Try to add a user to a existing Room

![error](https://user-images.githubusercontent.com/30302975/86886802-d61e8180-c0f7-11ea-8518-64b4296186b1.png)

### Version information

- **Platform**: web (in-browser) on self-hosted (latest) riot-web and riot.im (web)

For the web app:

- **Browser**: Chrome, Opera, Firefox (All latest version)
- **OS**: Windows 10 and Manjaro Linux?
- **URL**: / riot.im/app, Latest version of riot-web on self-hosted instance

For the desktop app:

- **OS**: Windows 10
- **Version**: Version von riot-web: 1.6.8, Version von olm: 3.1.3

**Comment by t3chguy** [comment] 2020-07-08 07:06
> and not the escaped version of it.

But it should support the escaped version of it as per the spec: https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-profile-userid-displayname

So the issue lies somewhere on the server side of things.

**Comment by Y0ngg4n** [comment] 2020-07-08 07:48
@t3chguy so it is a synapse issue?

**Comment by t3chguy** [comment] 2020-07-08 07:53
Either Synapse or something with your server-side configuration. I would suggest chatting in https://matrix.to/#/#synapse:matrix.org

**Comment by Y0ngg4n** [comment] 2020-07-08 08:02
@t3chguy ok thank you

**Comment by Y0ngg4n** [comment] 2020-07-08 09:51
@t3chguy ok i have found the issue, it was because i have pressed enter after entering the matrix user id. 
If you press enter after entering the id it appends the new line character at the end and the user cannot be found.
I think this is very confusing, because if you press enter it starts a new line. and the first line gets invisible. 
With the arrow up button you can switch back to the first line. 
Maybe you can change this field to a single line field so it does not happen that you cant find the user because of the new line character. And maybe you can change the action on Enter Press to the Button right next to the field so it automatically adds the user if you press enter.

**Comment by t3chguy** [comment] 2020-07-08 09:53
NLs don't get trimmed off for API requests

**Comment by Y0ngg4n** [comment] 2020-07-08 09:58
@t3chguy yes i think this is a design issue. 
also if you press Enter every normal user would excpect that he is hitting the Go button with his enter press.
Thank you for your support so far 👍

**Comment by turt2live** [comment] 2020-07-08 13:44
Duplicate of https://github.com/vector-im/riot-web/issues/13977

**Closed by turt2live** 2020-07-08 13:44 UTC
Labels: bug
