### ISSUE TITLE
Windows: Delete file from 'Files' tab

### ISSUE THREAD

**Issue by LaraSQP** [vector-im/riot-web#14739] opened 2020-07-23 22:48 UTC
I have deleted some messages before deleting the files attached first.

As a result, I don't seem to be able to delete the (rather large) files in them.

My fault, no doubt.

So, how can I delete them? The **Files** tab lists them but there is no option I can see to get rid of them.

Is there a limit to files on the server, btw?

**Comment by t3chguy** [comment] 2020-07-23 23:00
> Is there a limit to files on the server, btw?

Ask the server which you are using.

Duplicate of https://github.com/vector-im/riot-web/issues/14641

**Comment by LaraSQP** [comment] 2020-07-23 23:01
Thank you for the quick reply.

**Closed by t3chguy** 2020-07-23 23:00 UTC
Labels: suggestion

**Comment by LaraSQP** [comment] 2020-07-23 23:04
Sorry, but nope, I am afraid I am too dumb to understand what you told me to do.

The link does not help although it is the case that the problem I have is in an encrypted room.

**Comment by t3chguy** [comment] 2020-07-23 23:05
The link is to another report of the same issue. No point having two issues saying the same thing so I closed the duplicate one.

**Comment by LaraSQP** [comment] 2020-07-23 23:08
Got that but how do I resolve the problem?

_"Ask the server which you are using"_ is too cryptic for me.

**Comment by t3chguy** [comment] 2020-07-23 23:10
If you want to know the limit to files on the server you are using you'll have to ask that server. For file deletion in the local index follow updated in the issue i linked above.

**Comment by LaraSQP** [comment] 2020-07-23 23:43
Your patience is appreciated.
