### ISSUE TITLE
"The other party cancelled the verification" during cross-signing

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-web#12226] opened 2020-02-04 09:35 UTC
They most certainly did not.

Video at https://matrix.sw1v.org/_matrix/media/r0/download/sw1v.org/WqtCHVeowZXnIMrNpQjkBdOW

**Comment by turt2live** [comment] 2020-02-04 09:37
please rageshake from both sides when you get the chance

**Comment by bwindels** [comment] 2020-02-04 09:43
There should be a blank event tile at the bottom of the timeline that is actually the `m.key.verification.cancel` event. Could you paste the sender and (decrypted) source here please?

Also, it looks like the riot on the right isn't latest develop and/or doesn't have the cross signing flag enabled. You can do this by adding `"feature_cross_signing": "enable"` to the `features` key in the config.json.

**Comment by richvdh** [comment] 2020-02-04 10:09
rageshakes sent.

> There should be a blank event tile at the bottom of the timeline 

errr which timeline?

> Also, it looks like the riot on the right isn't latest develop and/or doesn't have the cross signing flag enabled.

probably both. seems like there should be a different failure mode though?

**Comment by bwindels** [comment] 2020-02-04 11:01
> errr which timeline?



> rageshakes sent.
> 
> > There should be a blank event tile at the bottom of the timeline
> 
> errr which timeline?

Sorry, the timeline of the DM where the request was sent.

> 
> > Also, it looks like the riot on the right isn't latest develop and/or doesn't have the cross signing flag enabled.
> 
> probably both. seems like there should be a different failure mode though?

Indeed.

**Comment by bwindels** [comment] 2020-02-04 13:38
I added extra logging to see the `{reason, code}` of cancelling in the rageshakes, which has now been deployed to /develop. @richvdh, could you please repro it again with one of the clients being latest /develop and rageshake? Thanks!

**Comment by bwindels** [comment] 2020-02-13 14:50
Hmm, the rageshake doesn't contain the logging I added before. It does contain a line that the verification failed because a key mismatch ... which seems odd.

Could you please try to reproduce again with latest develop on both sides and `feature_cross_signing` enabled on both sides?

**Comment by richvdh** [comment] 2020-02-13 15:07
I think the problem might be happening because one side isn't on develop (though the side that I sent the rageshake from should have been). I can try with develop on both sides, but no guarantee that will repro the problem.

**Comment by richvdh** [comment] 2020-02-13 16:44
well I tried, and got #12357 instead

**Comment by richvdh** [comment] 2020-02-13 16:44
oh wait, I need to set `feature_cross_signing` somewhere?

**Comment by bwindels** [comment] 2020-02-13 16:50
> oh wait, I need to set `feature_cross_signing` somewhere?

Yeah. it's enabled by default on riot.im/develop, but follow these steps if you're hosting yourself: https://github.com/vector-im/riot-web/issues/12226#issuecomment-581824286

**Comment by richvdh** [comment] 2020-02-13 17:08
new failure mode: apparently I'm being mitmed or something:

![Peek 2020-02-13 17-06](https://user-images.githubusercontent.com/1389908/74459444-38de5a80-4e83-11ea-92f4-a57de212ba02.gif)

**Comment by bwindels** [comment] 2020-02-17 12:34
So, looking at the rageshakes, the verification is cancelled because while checking the MAC, there is a key mismatch. The ed25519 device key for device `UX...` is different on the device checking the MAC (`OH...`), namely `cHDuL73yDdJBpfPLN3tVcMJSHkaerOFthIeMP//JhSk` than device `UX...` sends for themselves, namely `VazsJl37/bvHYNifBxlwzNB8V5EbKCLVjsxVYjRuwNE`.

**Comment by bwindels** [comment] 2020-02-17 12:48
Rich mentioned something about this particular device being b0rked, it does seem so. When looking for the device key in question with `/keys/query` it returns the key the `UX...` device is sending. How can a device end up with a stale/wrong key for another device?

**Comment by bwindels** [comment] 2020-02-17 14:28
So, most likely scenario:
 - device `UX...` was running short on disk-space and the browser purged its device keys in indexeddb.
 - riot detected this and created new keys and uploaded them
 - device `OH...` somehow didn't update the keys after this ... looking into how this could happen.

**Comment by bwindels** [comment] 2020-02-17 15:23
Ok, apparently we don't persist device key changes, as they might as well have come from a MITM'ing HS admin...

https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/crypto/DeviceList.js#L943

**Comment by bwindels** [comment] 2020-02-19 11:16
Hubert [argues](https://github.com/matrix-org/matrix-js-sdk/pull/1215#pullrequestreview-360841535) that we rather want to prevent keys rotating than accepting rotated keys. I guess one thing we can do to avoid this is request persistent storage to the browser so it becomes less likely it will evict our indexeddb. Only reason we haven't done so so far is that FF shows you a prompt, so we'd have to be careful about how and when we do that.

**Comment by jryans** [comment] 2020-02-19 11:25
> I guess one thing we can do to avoid this is request persistent storage to the browser so it becomes less likely it will evict our indexeddb. Only reason we haven't done so so far is that FF shows you a prompt, so we'd have to be careful about how and when we do that.

Definitely agreed that we should do something there. I have updated https://github.com/vector-im/riot-web/issues/9362 to track.

**Comment by bwindels** [comment] 2020-02-19 13:45
Apart from trying to prevent indexeddb getting evicted, we should also detect this case since https://github.com/matrix-org/matrix-react-sdk/pull/2841, and show a dialog that forces a logout. Somehow that didn't happen here :thinking:

**Comment by bwindels** [comment] 2020-02-19 15:57
Confirmed that the session that rotated keys is "years rather than months", so closing this as https://github.com/matrix-org/matrix-react-sdk/pull/2841 for sessions not as old.

**Comment by richvdh** [comment] 2020-04-09 10:22
this is still an issue even on new sessions.

**Comment by bwindels** [comment] 2020-04-09 12:29
Closing this as the cause is not a rotated device key as before. I've created https://github.com/vector-im/riot-web/issues/13105 instead.

**Closed by bwindels** 2020-04-09 12:29 UTC
Labels: bug, cross-signing-sprint, phase:2, story:2
