### ISSUE TITLE
Reactions / Toolbar have red text if the message is highlighted

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#9715] opened 2019-05-14 16:00 UTC
![image](https://user-images.githubusercontent.com/2072976/57713195-e1982900-7669-11e9-8730-5322023803a2.png)

I guess it's not the worst, but seems a little odd. The toolbar is hard to screenshot for obvious reasons but the dislike emoji (which doesn't render for me) is red.

**Comment by turt2live** [comment] 2019-05-14 16:13
Duplicate of https://github.com/vector-im/riot-web/issues/9697

**Closed by turt2live** 2019-05-14 16:13 UTC
