### ISSUE TITLE
photo with exif orientation is not rotated

### ISSUE THREAD

**Issue by florianjacob** [vector-im/riot-web#1999] opened 2016-08-23 15:15 UTC
I just uploaded a portrait photo taken by my camera via file upload of vector-web. In the chat view as well as when I click on the thumbnail to display the photo as full screen, it is displayed in landscape mode.

I checked that the exif orientation is correct with:

```
> identify -verbose <photo.jpg> | grep exif:Orientation
exif:Orientation: 8
```

which is the right setting according to the diagrams at http://sylvana.net/jpegcrop/exif_orientation.html.

According to [this stackoverflow answer](http://stackoverflow.com/a/36593389/4415604), at least firefox supports a css property to rotate the image according to the exif orientation.

Similar issue for vector-android: https://github.com/vector-im/vector-android/issues/409

**Comment by ara4n** [comment] 2016-08-26 22:52
Good point. iOS & Android work around this now i think by pre-rotating the image before upload, but we don't do this on vector-web.

This is a slightly sensitive subject: https://matrix.org/jira/browse/SPEC-85 is the attempt to formalise handling EXIF in Matrix, but it's never landed yet.  Thanks for flagging it for Vector.  Volunteers would be welcome to implement this properly....

**Comment by arthurlutz** [comment] 2017-05-03 13:14
The issue has been migrated to github https://github.com/matrix-org/matrix-doc/issues/483

I'd like a fix for this too...

**Comment by Flexmaen** [comment] 2019-02-07 12:08
Still existing problem.

Riot-Web will ignore the EXIF-data and show wrong rotation (while browser might show the correct rotation after you download the image).
Riot for Android seems to rotate the image and remove the Exif-Info.

**Comment by Siegfriedk** [comment] 2019-07-10 08:55
Took a picture with my smartphone, downloaded it from Google Photos and uploaded it through riot web ui. Its orientation is broken.

I'm surprised this doesn't isn't fixed.

**Comment by schopenhauer** [comment] 2020-04-13 12:12
I agree with @Siegfriedk. While this is not a blocking point, but it is somewhat surprising this has not been fixed since 2016.

**Comment by ara4n** [comment] 2020-04-13 12:51
it’s simply not got to the top of the todo list relative to more painful issues.

**Comment by Flexmaen** [comment] 2020-04-28 14:48
Still... having this as minor issue within 4289 issues will mean that it still might be open in 5 years.
So it might be a factor how complicated it is to fix an issue that still is annoying.

BTW: Today in a chat I experienced the bug mentioned in https://github.com/vector-im/riot-web/issues/10903 that was merged into this issue.
So sometimes the image will be rotated, but will have the wrong proportions.

**Comment by bwindels** [comment] 2020-04-29 11:56
[`image-orientation: from-image`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation) is deprecated but [still widely supported](https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation), so could be an easy fix for now.

**Comment by rgpublic** [comment] 2020-05-19 14:59
Hm, reading the comments here, it sounds like on Android the problem is automatically fixed *during upload*. But: I just took a selfie with my smartphone cam and uploaded it with RiotX. It looked perfectly normal there. On the Riot desktop client (Linux) the same photo appears rotated. So, it seems the photo is rather automatically rotated *for display* on Android, right?

**Comment by Flexmaen** [comment] 2020-05-19 21:05
I did test with the old Riot-Android, not with RiotX. Maybe RiotX can handle it while Riot-Web can't. That would explain the behaviour.
However, I tried to reproduce this but figured out that Riot-Web 1.6 seems to display it correctly now. So maybe this is already fixed?

**Comment by bwindels** [comment] 2020-06-15 11:45
> Hm, reading the comments here, it sounds like on Android the problem is automatically fixed _during upload_. But: I just took a selfie with my smartphone cam and uploaded it with RiotX. It looked perfectly normal there. On the Riot desktop client (Linux) the same photo appears rotated. So, it seems the photo is rather automatically rotated _for display_ on Android, right?

I am not able to reproduce. Would you be able to provide an image where the problem occurs for you?

I have tried uploading all the images from https://github.com/recurser/exif-orientation-examples and displaying worked fine on riot-web, riotx and riot android. Uploading worked everywhere apart from riotx, for which I have filed https://github.com/vector-im/riotX-android/issues/1482

**Comment by Ezwen** [comment] 2020-06-15 11:56
I have this photo that opens well with correct orientation in Eye of GNOME (eog) :

![Capture d’écran de 2020-06-15 13-50-47](https://user-images.githubusercontent.com/1388961/84654425-745f6300-af0f-11ea-8307-4d97ccef6767.png)

But here is the result when uploaded using riot-web 1.6.4, and visualized using the same riot-web : 

![Capture d’écran de 2020-06-15 13-53-14](https://user-images.githubusercontent.com/1388961/84654515-9c4ec680-af0f-11ea-918d-82a7ba4b7e41.png)

Here is the original photo : https://drop.infini.fr/r/fVBQ6FCWMN#sXJggzxQcLqyNfljtVogIpGJ5frZ6J7DcEsc6i2oSaU=

**Comment by rgpublic** [comment] 2020-06-15 12:02
![lizard](https://user-images.githubusercontent.com/17726950/84654943-5c3c1380-af10-11ea-8aea-ea970e6dd385.jpg)

@bwindels  I can definitively reproduce it. I just took a selfie (it's not me, obviously, LOL) with my phone's camera and shared it via RiotX on Android. It looked normal even after posting in the message pane. Then I went to my desktop PC, opened Riot, and the photo appears 90° degrees rotated CW. I've downloaded the file on the desktop PC via Riot (hope Riot doesn't change anything already during upload so it should be the original) and attached it for reference.

**Comment by bwindels** [comment] 2020-06-15 12:06
@rgpublic Thanks for the image, it seems to be specific to riot-desktop, having a look ...

**Comment by bwindels** [comment] 2020-06-15 12:39
Looks like electron `8.0.3` (at least on Linux) doesn't handle these images in the same way as Chrome, and it also does not seem to support `image-orientation` at all...

**Comment by rgpublic** [comment] 2020-06-15 12:53
According to [CanIUse](https://caniuse.com/#feat=css-image-orientation) this is supported in Chrome since v81. Electron 8.0 is based on Chromium v80 according to the [ElectronBlog](https://www.electronjs.org/blog). On that same page, you can find that Electron 9.0 is based on v83. Consequently, if Riot Desktop would be upgraded to Electron 9.0, this bug would be fixed.

**Comment by jryans** [comment] 2020-06-19 10:24
@bwindels We have now merged the Electron 9 upgrade and it seems to have stuck, so should be possible to try again I think.

**Comment by bwindels** [comment] 2020-06-22 08:16
Yeah, works like a charm now.

**Closed by bwindels** 2020-06-22 08:16 UTC
Labels: bug, minor, p2, project:bite-sized, type:electron
