### ISSUE TITLE
Electron: additionally map ctrl (or cmd) + '=' to zoom in

### ISSUE THREAD

**Issue by natestemen** [vector-im/riot-web#7721] opened 2018-11-19 22:22 UTC
### Description

In the app, I can only zoom out, and not in. So `cmd`+`-`, and `cmd`+`0` work, but just not `cmd`+`+`.

### Version information

- **Platform**: Desktop
- **OS**: macOS Mojave 10.14.1
- **Version**: 0.17.6

**Comment by aaronraimist** [comment] 2018-11-21 15:41
Related to / duplicate of #3160 (specifically
https://github.com/vector-im/riot-web/issues/3160#issuecomment-433721141)

@t3chguy what is the status on that zoom demo you had made a while ago?

**Comment by t3chguy** [comment] 2018-11-21 15:44
@aaronraimist Wasn't me. https://github.com/matrix-org/matrix-react-sdk/pull/1651

**Comment by lampholder** [comment] 2018-11-23 13:48
Yeah, this is a dup, and zooming in and out does work (on the mac electron app at least) but people appear to struggle to discover it because the shortcut is cmd and +, which you achieve by pressing <kbd>cmd ⌘</kbd>+<kbd>⇧</kbd>+<kbd>=</kbd> ('+' requires the shift key).

It looks like firefox/chrome have also mapped <kbd>cmd ⌘</kbd><kbd>=</kbd> to zoom - perhaps we could do the same.

**Comment by aaronraimist** [comment] 2019-02-14 18:02
This was fixed by https://github.com/vector-im/riot-web/pull/8381

**Closed** 2019-02-14 18:08 UTC
Labels: bug, help-wanted, minor, p2, ui/ux
