### ISSUE TITLE
riot-electron hangs with white screen trying to send big video file

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-web#14333] opened 2020-07-04 16:43 UTC
While riot-web in ff works fine, riot-electron hangs with white screen trying to send the same 200Mb H264 video file.

v1.6.8

**Comment by turt2live** [comment] 2020-07-04 16:46
Duplicate of https://github.com/vector-im/riot-web/issues/11479

**Closed by turt2live** 2020-07-04 16:46 UTC
Labels: bug
