### ISSUE TITLE
With markdown off, RTE requires Enter key 3 times to send a code block

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4931] opened 2017-08-28 20:11 UTC
1. Press the code block button
2. Add some text
3. Press enter (note the second block it creates)
4. Press enter again (clears the block)
5. Press enter once more - this sends the message with a blank line at the end

**Comment by lukebarnard1** [comment] 2017-08-30 16:03
This is pretty much as intended. What would expect to happen differently, @turt2live?

**Comment by turt2live** [comment] 2017-08-30 16:10
1 less enter, also not 2 code blocks.

![image](https://user-images.githubusercontent.com/1190097/29882773-595e6768-8d6b-11e7-8519-0229298d2d8b.png)

That should probably just be a continuation, instead of a whole new block.

**Comment by lampholder** [comment] 2017-09-05 14:00
Interestingly gitter and slack have each adopted quite a different approach to multiline messages - gitter has a 'composer mode' (essentially something that stops enter from submitting until you disable it) and slack has a 'snippet' editor - a whole separate modal editor for editing multi-line code blocks.

**Comment by rkfg** [comment] 2017-09-12 09:33
I would prefer Enter to always send the message and Shift+Enter to insert a new line. It's quite a common pattern in desktop messengers I used before.

**Comment by ara4n** [comment] 2018-07-16 17:52
fixed in matrix-org/matrix-react-sdk#1890

**Closed by ara4n** 2018-07-16 17:52 UTC
Labels: bug, minor, p2, type:rte, ui/ux
