### ISSUE TITLE
Need recovery key instead of passphrase when setting up cross signing.

### ISSUE THREAD

**Issue by Bubu** [vector-im/riot-web#13618] opened 2020-05-10 12:19 UTC
(Sorry no screenshots, as I don't want to reset my E2EE state again,  I'm happy that I got it working now.)

### Description

When prompted to upgrade the encryption riot asked me for my recovery key. I didn't have this, only had my recovery key passphrase but I couldn't use this.

### Steps to reproduce

- Generate a new recovery key
- enter a recovery passphrase
- There's a screen which presents you with the option to save the generated recovery key, it tells you, you'll need it, when you forget the passphrase.
- don't save the key because the passphrase is already saved in my password manager, so saving the key alongside it didn't seem useful
- Next screen asks for the recovery key even though I *did not* indeed forget my passphrase...

Describe how what happens differs from what you expected.

Have an option to use the passphrase and not the recovery key.

Logs being sent: no

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu 18.04
- **Version**: 1.6.0

**Comment by dbkr** [comment] 2020-05-11 15:11
I can't reproduce this behaviour - after resetting the recovery key, Riot asks me for my account passphrase.

In general, Riot will only ask you for your recovery key if a) your account is set up with only a recovery key and not a passphrase, or b) you opted to use a recovery key instead when prompted for the passphrase. This suggests that your account might actually be set up in recovery-key-only mode and not key+passphrase mode as you suggest.

**Comment by Bubu** [comment] 2020-05-11 15:41
Mmh, I'm not sure how I could reproduce this behaviour now. I guess I'd need an old install of riot somewhere, set up key backup and then upgrade to a new install :-/.

**Comment by jryans** [comment] 2020-05-12 10:20
Hmm, so far it sounds like the dialog is perhaps a bit confusing, or it was unclear how they account was set up at the time, but I don't see a clear path to something we can fix or change here yet.

Since you were able to get it working in the end, I think I'll close this for now, but if something like this happens again to you or others, let's dig in again.

**Closed by jryans** 2020-05-12 10:20 UTC
Labels: bug, ui/ux
