### ISSUE TITLE
The text input field for editing topics randomly deletes itself every few seconds when editing topics for rooms with no name

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-web#6091] opened 2018-02-05 15:57 UTC
It looks like React might be refreshing the component occasionally for some reason, and destroying the WIP text input value

**Comment by t3chguy** [comment] 2018-02-05 16:00
Duplicate of #6019

**Comment by ara4n** [comment] 2018-02-12 11:30
it's not a dup, this happens without state changes.

**Comment by turt2live** [comment] 2018-02-12 14:07
#6019 describes the react state updating. I haven't seen it delete itself otherwise.

**Comment by lukebarnard1** [comment] 2018-02-13 12:13
@ara4n I think this is a dup, as @turt2live has said, #6019 is caused by a React state change (caused by a state event arriving down the /sync stream).

**Closed** 2018-02-13 12:16 UTC
Labels: bug, major, p1, regression
