### ISSUE TITLE
[Windows 10/other] Desktop icon, option or setting, keeps getting remade (even though I don't want it on the desktop)

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-web#10885] opened 2019-09-16 23:14 UTC
Icons on the desktop are dumb, and that's my opinion. I delete them all.

However, whenever Riot on the desktop (Windows 10, at least) gets updated, it re-creates the icon on the desktop. No prompting, nothing. I have to go delete it again, ARGH.

Can we get prompted at some point for "do you want the desktop icon?" (and a "remember" setting so it doesn't need to ask each time) so that way it stops remaking the icon I don't want?

Please?

**Comment by turt2live** [comment] 2019-09-17 00:10
Duplicate of https://github.com/vector-im/riot-web/issues/9210

**Closed by turt2live** 2019-09-17 00:10 UTC
Labels: suggestion

**Comment by BloodyIron** [comment] 2019-09-17 03:48
@turt2live oops, sorry!
