### ISSUE TITLE
Invitation form textarea field is too narrow

### ISSUE THREAD

**Issue by mcnesium** [vector-im/riot-web#14029] opened 2020-06-14 10:39 UTC
![Screenshot from 2020-06-14 12-33-42](https://user-images.githubusercontent.com/476060/84591066-bdde7e00-ae3b-11ea-9b02-330cd68422a0.png)

The invitation form textarea has a width of 40% declared, which makes long email addresses break and wrap to a new line, even though there would be enough room for it. Why is this 40% rule there? Can it be removed?

**Comment by t3chguy** [comment] 2020-06-14 12:06
Duplicate of https://github.com/vector-im/riot-web/issues/13066

**Closed by t3chguy** 2020-06-14 12:06 UTC
Labels: bug, ui/ux
