### ISSUE TITLE
[OSX][QWERTY] Emphasized character preceded by the unaccented character

### ISSUE THREAD

**Issue by Arubinu** [vector-im/riot-web#7419] opened 2018-09-29 12:09 UTC
### Description

Hello, I use a Macbook Pro with Qwerty keyboard. When I want to write an accented character, a box offers me to choose after a long press. The trouble is that the accented character added later is preceded by the character without accent.

### Steps to reproduce

- Long press on the E key: displays the selection box of the accent (possibility to use the numbers of the keyboard to choose).
- Before the choice, the letter is already displayed.
- Once the letter É chosen, it is added to the continuation, example in French: Ce texte comporte des caract**eè**res accentu**eé**s et chacun est doubl**eé** **aà** chaque fois !

In general, the unaccented character is not displayed at all (so it is not deleted later), which makes no duplication.

<img width="431" alt="accents" src="https://user-images.githubusercontent.com/6209760/46245588-55920380-c3f0-11e8-86e9-9bb030194d49.png">

### Version information

- **Platform**: web (in-browser) and desktop

For the web app:

- **Browser**: Vivaldi 2.0.1309.29 (Stable channel) (64 bits)
- **OS**: macOS 10.13 & macOS 10.14
- **URL**: riot.im/app 0.16.4 & 0.16.5

For the desktop app:

- **OS**: macOS 10.13 & macOS 10.14
- **Version**: 0.16.4 & 0.16.5

**Comment by lampholder** [comment] 2018-10-01 16:58
Even worse, the accented character seems to be appended to the message text, _after_ the caret (so you'd have to navigate to the end of the text manually to continue typing).

**Comment by aaronraimist** [comment] 2018-10-01 16:58
Working on the fix for this

**Comment by lampholder** [comment] 2018-10-01 17:06
Excellent news :) In case it's useful (though at this stage I imagine it is not), this problem is not inherent to draft.js (the demo draft.js at https://draftjs.org/ works fine).

**Comment by lampholder** [comment] 2018-10-01 17:07
Oh, and just to save anyone else who's looking into this a Google - if like me you'd turned this feature off so long ago you'd forgotten it existed, you can toggle it with

`defaults write -g ApplePressAndHoldEnabled -bool false`

(or `true`, obvs)

**Comment by Arubinu** [comment] 2018-10-01 17:31
It still does not work for me with the latest version (riot-web: 0.16.5, olm: 2.2.1).

**Comment by aaronraimist** [comment] 2018-10-21 01:32
This issue can be closed, should be fixed now in v0.17.0 and later.

**Comment by turt2live** [comment] 2018-10-31 19:48
@Arubinu @lampholder are you able to confirm if this is fixed? I don't have a mac to test with unfortunately.

**Comment by lampholder** [comment] 2018-11-01 09:43
I'm afraid this still seems to be broken on latest /develop (ca305399c3a1-react-cf31f01c8584-js-62b2c07be2fa):

![ee](https://user-images.githubusercontent.com/1922197/47844472-73210700-ddba-11e8-9a01-55b043b4e531.gif)

**Comment by aaronraimist** [comment] 2018-11-01 13:28
Ohh 😟
It got fixed in Firefox and Safari but is still broken in Chrome

**Comment by aaronraimist** [comment] 2018-11-01 13:31
?? I could have sworn it *wasn't* an upstream bug before but today I can reproduce it on slatejs.org in Firefox and Chrome (but not Safari)

**Comment by turt2live** [comment] 2018-11-05 03:19
I'm going to trust that this is an upstream issue - if it's not, well, bleh :(

**Comment by turt2live** [comment] 2018-11-05 23:05
Closing in favour of https://github.com/vector-im/riot-web/issues/7665 to track the upstream issue.

**Closed by turt2live** 2018-11-05 23:05 UTC
Labels: bug, minor, p1, platform specific, type:composer, upstream-issue
