### ISSUE TITLE
Riot-web times out on verifying device

### ISSUE THREAD

**Issue by PC-Admin** [vector-im/riot-web#9737] opened 2019-05-16 02:55 UTC
```
'Verify device

Waiting for partner to accept...'
```

I'm trying to verify 2 accounts, both using Riot Desktop on Debian. One is on 'matrix.org' the other 'perthchat.org', it just times out.

I can't get either client to see the verification request of the other.

**Comment by PC-Admin** [comment] 2019-05-16 03:20
Finally arrived on my phone about 30 minutes later but not my desktop. By then:

'Request Cancelled

The verification is cancelled.
Reason: The user cancelled the verification'

I guess i'm a bad person for wanting to use riot again instead of waiting 30 minutes :<

**Comment by turt2live** [comment] 2019-05-16 03:22
sending debug logs from both devices, referencing this issue, would be a great help to see if there's anything obvious in the logs for us to fix. Click your name in the top left then 'Settings', go to the Help tab, and finally click the 'Submit Debug Logs' button.

**Comment by PC-Admin** [comment] 2019-05-16 03:59
Sent 3 reports for you. Strangely the perthchat.org desktop client had not verified any of the other users keys yet 3 messages were sent through in the clear? That seems like an even bigger bug. :/

**Comment by PC-Admin** [comment] 2019-05-16 04:00
Perhaps it was because the matrix.org account had 2 keys, one of them being old. Strange.

**Comment by turt2live** [comment] 2019-06-19 20:47
I think this is a duplicate of https://github.com/vector-im/riot-web/issues/9103

**Closed by turt2live** 2019-06-19 20:47 UTC
Labels: bug, feature:e2e-sas-verification, p1, type:e2e

**Comment by zeex124** [comment] 2019-07-11 20:12
Personnaly i have to revirify my devices everytime i log in same goes for everyone in a room... its really anoying.
