### ISSUE TITLE
room preview bar [object Object]

### ISSUE THREAD

**Issue by t3chguy** [vector-im/riot-web#4052] opened 2017-05-27 12:23 UTC
![image](https://cloud.githubusercontent.com/assets/2403652/26521403/a5851640-42df-11e7-853e-b2ea51c0cc4f.png)
on /develop/

on /app/ the text is
```
You are trying to access Home Assistant.
Click here to join the discussion!
```

**Comment by uhoreg** [comment] 2017-05-27 13:25
@MTRNord is this caused by the translation changes?

**Comment by ara4n** [comment] 2017-05-27 15:03
fixed in matrix-org/matrix-react-sdk@957aa04

**Closed by ara4n** 2017-05-27 15:03 UTC
