### ISSUE TITLE
Mark message as unread in Matrix room thread via Riot interface

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-web#4545] opened 2017-07-10 06:12 UTC
At now, when I opening room thread with many messages, I see last message and have ability for jump to first unread message. But when new messages are too many - very often I have no time to read all of them, and want to split reading, but all messages already marked as read. 

For solve this problem will be good to have ability for mark custom message (and all later messages after it) as unread, for scroll-back to it later and continue reading.

**Comment by turt2live** [comment] 2017-07-10 14:12
Duplicate of #4406

**Closed** 2017-07-10 14:17 UTC
