### ISSUE TITLE
Tone down the "message" sound

### ISSUE THREAD

**Issue by MightyCreak** [vector-im/riot-web#13783] opened 2020-05-23 15:55 UTC
**Is your suggestion related to a problem? Please describe.**
The "[message](https://github.com/matrix-org/matrix-react-sdk/blob/develop/res/media/message.ogg)" sound is really loud compared to the notification sounds from other IM application.

**Describe the solution you'd like**
It would be nice to tone down the "message" sound.

Even better would be to tone down [all the sounds](https://github.com/matrix-org/matrix-react-sdk/tree/develop/res/media) to a defined dB level in line with the ones found in other IM apps.

**Describe alternatives you've considered**
Reduce system volume, but then I lose the sound from my other apps...

**Additional context**
Here is a comparison of the "message" sound from Riot with the "drip" sound from GNOME (its default alert sound). As you can see Riot's sound is twice as loud:
![image](https://user-images.githubusercontent.com/6382548/82734959-38f4be80-9cec-11ea-8c9a-2b8f928a3037.png)

**Comment by turt2live** [comment] 2020-05-23 22:33
Duplicate of https://github.com/vector-im/riot-web/issues/12360

**Closed by turt2live** 2020-05-23 22:33 UTC
Labels: suggestion

**Comment by MightyCreak** [comment] 2020-05-24 13:53
Oh, sorry. I did search for an existing issue, but my main search word was "sound". Good to know it already exists! I've added my vote :wink:
