### ISSUE TITLE
Disable Alt toggle of the window menu bar

### ISSUE THREAD

**Issue by odiferousmint** [vector-im/riot-web#14615] opened 2020-07-18 12:29 UTC
I am on Linux and I move the windows by pressing (and holding down) the Alt key which keeps toggling the menu bar. It is extremely annoying. The only way to make it less annoying is to enable the "Always show the window menu bar" option, but it is only a workaround; I would like to have an option that would completely disable it, or at least not toggle it when I press the Alt key.

**Comment by t3chguy** [comment] 2020-07-18 12:45
That is a feature of Electron, not Element

anyhow duplicate of https://github.com/vector-im/riot-web/issues/6640

**Closed by t3chguy** 2020-07-18 12:45 UTC
Labels: suggestion
