### ISSUE TITLE
Render bug with multiple /me in a row for different people

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/riot-web#14813] opened 2020-07-29 13:57 UTC
### Description

Render bug with multiple /me in a row for different people. The profile pictures are on top of the message timestamps. Persists over hard refresh of browser tab

<img width="562" alt="Screen_Shot_2020-07-29_at_2_51_57_PM" src="https://user-images.githubusercontent.com/19155609/88808960-69a11a80-d1ab-11ea-99fd-7f5e7ee2110e.png">

### Steps to reproduce

- unsure

Logs being sent: yes

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 79.0 (64-bit)
- **OS**: macOS Catalina 10.15.5 (19F101)
- **URL**: develop.element.io

**Comment by turt2live** [comment] 2020-07-29 13:58
Duplicate of https://github.com/vector-im/riot-web/issues/2284

**Comment by t3chguy** [comment] 2020-07-29 13:58
Dammit I just hunted for it

**Comment by turt2live** [comment] 2020-07-29 13:59
well, I was about to close the rageshake so it's only fair :p

**Comment by Twi1ightSparkle** [comment] 2020-07-29 13:59
> Duplicate of #2284

uups, rip my searching skills :P

**Closed by turt2live** 2020-07-29 13:58 UTC
Labels: bug
