### ISSUE TITLE
Feature request: Add muffle/soft ignore 

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/riot-web#7521] opened 2018-10-19 01:09 UTC
I'd love to get a muffle feature in addition to ignore. Currently if you ignore a user, you never get any indication that they said anything so I'm hesitant to ignore people unless they are just straight up spammers.

A muffle (idea stolen from the Twitterrific Twitter client) would be a soft ignore. The message would be collapsed/minimized so you couldn't read the content of it without clicking on it but you would still see some indication that this person had said something.

https://support.iconfactory.com/kb/twitterrific/muffling-and-muting-tweets-in-twitterrific-ios-and-macos

Example of interface:
![](https://sixcolors.com/images/content/2017/muffle-6c.jpg)
from https://sixcolors.com/post/2017/12/muffling-many-tweets-in-twitterrific/

Theoretically this could be combined with something like #7120 so you could muffle specific phrases but that would be a more advanced feature. I'd love to just be able to muffle individual users as a first step.
![](https://sixcolors.com/images/content/2017/filter-twitter2-6c.jpg)

Somewhat related: #5550

**Comment by turt2live** [comment] 2018-10-19 01:28
Duplicate of #6819

**Closed by turt2live** 2018-10-19 01:28 UTC
