### ISSUE TITLE
Highlighting text then pressing backspace leaves the formatting bar behind

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#12671] opened 2020-03-10 04:48 UTC
Windows 10, develop.

**Comment by bwindels** [comment] 2020-03-10 10:10
Which browser?

**Comment by t3chguy** [comment] 2020-03-10 10:37
I am unable to repro on Windows 10 with latest stable Chrome, Firefox and riot-desktop (/develop)

**Comment by turt2live** [comment] 2020-03-10 15:31
Chrome.

![image](https://user-images.githubusercontent.com/1190097/76329171-d88bde80-62b1-11ea-8a81-18badee70598.png)

**Comment by ThobyV** [comment] 2020-03-21 09:42
Can I be assigned to this issue?

I Sent some very basic (css) fixes I'm looking to take on slightly more engaging issues to get familiar with the awesome codebase.

It seems that a blank space character is left even after sending highlighted message hence making format bar visible. Is this an intentional behaviour?

**Comment by turt2live** [comment] 2020-03-21 17:43
@ThobyV sure, though we generally don't assign external contributors until there's a PR out.

**Comment by turt2live** [comment] 2020-03-21 17:43
also it's probably not intended to have a blank character

**Comment by ThobyV** [comment] 2020-03-21 17:57
@turt2live thanks for the opportunity. 

Looking through devtools I think the blank character may be due to a bug that inappropriately applies `::before` selector to the input element that creates a div with ``::before` as a direct child of the input in an `empty` state.

**Comment by ThobyV** [comment] 2020-03-23 19:30
I'm unable to reproduce this on my environment. Is it in relation or identical to this issue? https://github.com/vector-im/riot-web/issues/12817

I was able to fix https://github.com/vector-im/riot-web/issues/12817

**Comment by turt2live** [comment] 2020-03-23 19:34
I can still reproduce this: 
1. Type `asdf`
2. Highlight `df`
3. Press backspace

**Comment by ThobyV** [comment] 2020-03-23 19:51
Oh! Reproduced! fixing it asap.

**Comment by ThobyV** [comment] 2020-03-23 22:38
I managed to fix this issue but I can't send a PR for proper review yet.  It seems my branch build & some tests are failing since most recent I pulled from `upstream/develop`.

Are you experiencing build issue too?

**Comment by bwindels** [comment] 2020-03-24 09:33
@ThobyV You can already make a draft PR, then we can have a look where the tests are failing.

**Comment by ThobyV** [comment] 2020-03-24 12:27
@bwindels  thanks I will make sure to do that next time. Got help from riot:dev matrix channel why build was failing. I Just sent a PR for review on the issue.

**Closed** 2020-03-26 13:19 UTC
Labels: Community PR, bug, type:composer
