### ISSUE TITLE
Custom Widget no longer allows variables in URL

### ISSUE THREAD

**Issue by oddsock** [vector-im/riot-web#13449] opened 2020-04-29 18:24 UTC
### Description

using a custom widget with url fetching $matrix_display_name for example no longer works after release v1.5.14. As reported to work in the WIP API document https://docs.google.com/document/d/1uPF7XWY_dXTKVKV7jZQ2KmsI19wn9-kFRgQ1tFQP7wQ/edit

### Steps to reproduce

1. in message window: /addwidget https://www.example.com&username=$matrix_display_name
2. Custom widget created but site reports: "Cannot use username $matrix_display_name"

Describe how what happens differs from what you expected.

Addwidget should fetch matrix username to pass through to custom URL.

Logs being sent: no

### Version information

v1.5.15

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Firefox 74.0 (64-bit)
- **OS**: Windows 10
- **URL**: riot-web v1.5.15

**Comment by t3chguy** [comment] 2020-04-29 18:26
Duplicate of https://github.com/vector-im/riot-web/issues/12985

**Closed by t3chguy** 2020-04-29 18:26 UTC
Labels: bug
