### ISSUE TITLE
Webapp doesn't scale with window size (and is therefore unusable) on Firefox on some macbooks

### ISSUE THREAD

**Issue by AdrienMatricon** [vector-im/riot-web#6396] opened 2018-03-27 09:24 UTC
### Description

The layout doesn't scale with the window size, scrolling is impossible, and in particular there is no way to access the buttons that are supposed to be at the bottom left (which makes the webapp unusable).

### Steps to reproduce

- Just go to https://riot.im/app/ or login to a session

It looks like this (logged in):

<img width="1440" alt="screen shot 2018-03-27 at 11 01 35" src="https://user-images.githubusercontent.com/14818215/37957622-ba0f68ea-31ae-11e8-9cf0-dd58a9dcae0e.png">

And there is no way to scroll.

Changing the window size vertically just makes fewer things visible:

<img width="1440" alt="screen shot 2018-03-27 at 11 07 03" src="https://user-images.githubusercontent.com/14818215/37957820-3606ae0e-31af-11e8-8742-c7c90cddc353.png">

Changing it horizontally does lead to some changes but it doesn't help:

<img width="300" alt="screen shot 2018-03-27 at 11 07 21" src="https://user-images.githubusercontent.com/14818215/37957965-86ad4674-31af-11e8-88cd-4ea7ba0245c2.png">

Log: None, because I don't have access to the Settings page

### Version information

- **Platform**: web (in-browser)
- **Browser**: Firefox v59.0.1 (64-bit) and v59.0.2 (64-bit). I tried fully uninstalling Firefox and installing a new one, but the problem persists. I tried on Safari, and there the problem doesn't occur.
- **OS/Hardware**: The problem occurs on my macbook (MacBook Pro, 13-inch, 2017, Four Thunderbolt 3 Ports) running macOS High Sierra v10.13.3, while it doesn't when using the same Firefox version on my desktop computer running Ubuntu. I'm not sure if it's hardware related, but the problem occurs on both my macbook and the one from a colleague who I asked and who has the same OS (MacBook, Retina, 12-inch, Early 2015). I asked another colleague with the same OS and the problem doesn't occur on it though (MacBook Pro, Retina, 15-inch, mid-2015).
- **URL**: https://riot.im/app/#/home

### Edit: additional information

I just used Firefox's web inspector to compare the page which is displayed properly on ubuntu with the one which isn't on my mac.

It turns out that `<div class="mx_RoomList_scrollbar gm-autoshow gm-scrollbar-container"> (...) </div>` is missing its last element `<object class="gm-resize-trigger" type="text/html" data="about:blank"></object>`.

I'm guessing this means that the problem originates from somewhere in the JS.

**Comment by turt2live** [comment] 2018-03-27 15:43
I think this sounds like https://github.com/vector-im/riot-web/issues/4803

**Comment by lampholder** [comment] 2018-03-27 16:23
I think it sounds like that, too.

Closing this as a duplicate.

The cause though appears to be a problem that has been masked on other platforms by our use of gemini scrollbar (a library that gives mac-like scrollbars to non-mac platforms, but leaves the native scrollbars unmolested (and in this case broken) on mac).

**Closed by lampholder** 2018-03-27 16:23 UTC
