### ISSUE TITLE
'Disinvite' shows kick dialog and is confusing

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#3512] opened 2017-03-24 20:07 UTC
### Description

When disinviting someone, the user is presented with a kick dialog. Although the action is the same in the backend, having this dialog is confusing. Maybe it should just confirm and move on instead of asking for a reason to kick?

### Steps to reproduce

- Invite someone
- then don't

I would have expected either no confirmation or a confirmation dialog asking if I'd like to disinvite the user, not kick them.

Log: not sent    

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 56
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by lampholder** [comment] 2017-03-28 15:03
Looks like this is a dupe of #3347 which just got fixed :)

**Closed by lampholder** 2017-03-28 15:03 UTC
