### ISSUE TITLE
Screen sharing on Linux desktop doesn't work

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [vector-im/riot-web#10782] opened 2019-09-06 15:15 UTC
I'm using Manjaro with Riot Desktop 1.3.3-1.
If I shift-click at a video call button, I get the following error message:

Failed to get screen-sharing stream: NotReadableError: Could not start video source

**Comment by turt2live** [comment] 2019-09-06 16:19
Duplicate of https://github.com/vector-im/riot-web/issues/4880

**Closed by turt2live** 2019-09-06 16:19 UTC
