### ISSUE TITLE
Jitsi screenshare isn't working in latest Riot Electron

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7123] opened 2018-08-01 13:25 UTC
Maybe something changed when we updated jitsi, maybe when we wrapped jitsi up in a persistent widget. Either way, sharing the screen with the jitsi UX just shows an infinite jitsi spinner instead of letting you choose a tab/application/the whole desktop

**Comment by t3chguy** [comment] 2018-08-01 13:52
This has been always been like this :(
It's because of it being two nested iframes so we can't pass the jitsi electron module through to it due to browser restrictions

**Comment by t3chguy** [comment] 2018-08-01 13:52
Duplicate of #4880

**Closed** 2018-08-01 13:53 UTC
Labels: bug, major, p1, type:electron, type:voip
