### ISSUE TITLE
Unable to login via .well-known to custom HS with Riot Desktop 0.17.9

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-web#8428] opened 2019-02-07 08:35 UTC
So I just installed the latest riot on a new computer (win16, riot 64-bit) and ran into this problem. I am unable to login. Using custom server settings does not work. My homeserver implements the .well-known for matrix. 
(1) Login is not possible with the riot-desktop version!
(2) There is no way to exit the login dialog other than killing riot in the task manager and starting it again.
(I wanted to update the riot desktop version for some of my homeserver users and I am glad I didn't because they might not be able to login anymore)
Hope this gets fixed soon.

_Originally posted by @chresan in https://github.com/vector-im/riot-web/issues/7925#issuecomment-461167473_

**Comment by chresan** [comment] 2019-02-07 15:05
uhoreg mentioned I should set the Access-Control-Allow-Origin header for the URL https://meshspace.de/.well-known/matrix/client
I set it to '*' but it does not fix the login problem.

(@jryans : thanks for opening this issue)

**Comment by chresan** [comment] 2019-02-07 15:48
So I had time to try out the login process more. It appears also if .well-known is not configured. Basically login to riot is not possible anymore if the homeserver is not matrix.org. I opened a new more generic issue  #8451

**Comment by jryans** [comment] 2019-02-07 16:05
@chresan Is this still an issue, or was it also fixed by removing the script blocker as in #8451?

**Comment by chresan** [comment] 2019-02-07 16:07
The well-known discovery works find using the web-client on riot.im. It persists on the desktop version of riot (v0.17.9, tested on win10 and on linux).

**Comment by chresan** [comment] 2019-02-08 22:06
I was able to workaround the issue and login using following steps (works only in this order):
(1) Add custom server settings
(2) Add user name (local part only, otherwise it fails)
(3) Add Passwort
(4) Click the login button

**Comment by lampholder** [comment] 2019-02-18 14:30
Sounds similar to https://github.com/vector-im/riot-web/issues/7875

**Comment by turt2live** [comment] 2019-04-11 04:52
This does indeed sound eerily similar to https://github.com/vector-im/riot-web/issues/7875 or at least https://github.com/vector-im/riot-web/issues/7845 - closing as a duplicate of those issues.

**Closed by turt2live** 2019-04-11 04:52 UTC
Labels: bug, major, p1, type:electron, type:login
