### ISSUE TITLE
Not refreshing after name change.

### ISSUE THREAD

**Issue by sk-alexis** [vector-im/riot-web#12862] opened 2020-03-25 01:51 UTC
### After display name change the name on the top corner is not refreshed, there is the need to logout and log back in for riot to give the right updated name

the feauture requested is for riot to refresh account panel on top left, after a display name, or even profile changes for that matter. 

### Steps to reproduce

- go to profile settings
- change a display name
- hit save
- and notice that although in room your name is updated on the top left corner on account panel, there is still the old name.

the expect behaviour would be to riot refresh profile so updated name is displayed.

- **Debian**: web (in-browser)

For the web app:

- **gnomeWEB(epiphany)/firefox**

**Comment by sk-alexis** [comment] 2020-03-25 01:54
@ara4n  #312 this bug might be related although it is about unrelated result though.

This seams to have a simple fix, which I would love to commit, which is just refresh profile after any changes. But unfortunately my coding skills are still lacking for such commit.

Cheers

**Comment by turt2live** [comment] 2020-03-25 03:03
Duplicate of https://github.com/vector-im/riot-web/issues/8570

**Closed by turt2live** 2020-03-25 03:03 UTC
Labels: bug

**Comment by sk-alexis** [comment] 2020-03-25 03:47
@turt2live Sorry I look it up but could find anything, Cheers.

**Comment by sk-alexis** [comment] 2020-03-25 03:48
#8570 could use the descripption if needed
