### ISSUE TITLE
[Room Directory] Retain homeserver's entered into the dropdown.

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riot-web#6259] opened 2018-02-27 13:35 UTC
When entering a homeserver domain into the dropdown, we should save this to the user's settings if the request succeeds so they do not need to re-enter it.

**Comment by turt2live** [comment] 2018-02-27 15:42
Duplicate of https://github.com/vector-im/riot-web/issues/3770

**Closed** 2018-02-27 15:46 UTC

**Comment by Half-Shot** [comment] 2018-02-27 15:57
I am really failing to search for these -_-
