### ISSUE TITLE
New room list: online status not show for favorites, encripted DM, DM with bots

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-web#14524] opened 2020-07-16 06:43 UTC
As I understand - now "element" show "online status circle" with green filling, when user is online for DM. So, today in favorites we can not understand - what type this room - DM, or "room".

But this circle not showing at cases:
1. For encripted DM (red line on screenshot)
1. For DM with bots (yellow line on screenshot) - some times we use bots in DM - for informations, translating, converting voce to text, git, redmine and other...
1. For all favorites DM (blue line on screenshot)

May be 2 item can not be fixed - becouse app will can not understand - which "online status" it must be show - bots or other user, and can not be understand - who is real user and who is bot... :-/ 
![1](https://user-images.githubusercontent.com/1297163/87635748-ea5f2000-c782-11ea-91ee-ad8fb0f87cfe.png)

Linux Ubuntu 16.04 LTS amd64
Element 1.7.0 (desktop)

**Comment by t3chguy** [comment] 2020-07-16 06:45
> For encripted DM (red line on screenshot)

This is because its in Favourites.

The tile only shows in the `People` category.

> For DM with bots (yellow line on screenshot) - some times we use bots in DM - for informations, translating, converting voce to text, git, redmine and other...

The bot has likely just never sent a presence update hence it is unknown whether online/offline, likely does not support it.

Duplicate of https://github.com/vector-im/riot-web/issues/14503

**Closed by t3chguy** 2020-07-16 06:45 UTC
Labels: bug, ui/ux

**Comment by progserega** [comment] 2020-07-16 06:51
> This is because its in Favourites.

Why we can not know online status for favorites? O_o

> The bot has likely just never sent a presence update hence

Hmm... voice2text - is my bot. I do not write any "status update code" for them, but it show as online:
![1](https://user-images.githubusercontent.com/1297163/87636709-7a519980-c784-11ea-9cfc-1573782eb428.png)

**Comment by progserega** [comment] 2020-07-16 06:54
What about encripted DM?

**Comment by t3chguy** [comment] 2020-07-16 06:56
![image](https://user-images.githubusercontent.com/2403652/87637224-d3e0a680-c739-11ea-9e84-b84aca806917.png)

^ Are all encrypted DMs. DMs are encrypted by default. They all have functional indicators.
