### ISSUE TITLE
Code blocks add unnecessary slashes

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#4901] opened 2017-08-27 15:59 UTC
Pasting URLs like `ttps://t2l.io/_matrix/client/r0/user/%40travis%3At2l.io/openid/request_token?access_token=` into Riot and surrounding them with backticks leads to escape sequences

**Comment by t3chguy** [comment] 2017-08-27 16:00
Dup https://github.com/vector-im/riot-web/issues/4809

I THINK

**Comment by turt2live** [comment] 2017-08-27 16:01
It's related, but only recently has it started affecting URLs. Probably the same fix though.

Close at discretion, I suppose.

**Comment by lukebarnard1** [comment] 2017-08-30 08:44
> leads to escape sequences

@turt2live if you could be more specific, that'd be great

**Comment by t3chguy** [comment] 2017-08-30 08:49
@lukebarnard1 
![image](https://user-images.githubusercontent.com/2403652/29863718-787e4576-8d68-11e7-80e6-34a0ec400f35.png)
pasting the string in the original report leads to the above, see all the random `\`

**Comment by lukebarnard1** [comment] 2017-08-30 10:11
OK, yep this is a dupe of #4809

**Closed by lukebarnard1** 2017-08-30 10:11 UTC
Labels: type:rte
